### ISSUE TITLE
Feature Request: php please build:static

### ISSUE THREAD

**Issue by humanjpg** [statamic/v2-hub#1000]
Would be cool if once you run `php please clear:static` it either automatically rebuilds all the pages or happens on command.

Can foresee potential complexity of establishing what constitutes a page e.g. `page 231 of 353` in a paginated list of entries. But perhaps all page and entry URLs, sans pagination would be a sensible start.

Just trying to avoid any users seeing a site until it's been properly cached or they might be sitting there a while :)

**Comment by humanjpg** [comment]
A good workaround for this:

1. Open all the links to the pages you need to be rebuilt

2. Save them using the [Session Buddy](https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko) chrome extension. 

3. Each time you clear your static cache, open that session to rebuild all the pages

**Comment by jackmcdade** [comment]
Coming in v3.
