### ISSUE TITLE
Cache::clear() throws member function error

### ISSUE THREAD

**Issue by squashedpixel** [statamic/v2-hub#1002]
### Expected behaviour

When calling Cache::clear() or Stache::clear() from within the plugin API it clears the cache, then rebuilds on the next page load on the front end of the site
### Actual behaviour

When calling Cache::clear() or Stache::clear() from within the plugin API, when you then navaigate to any page on the front end of the site it then shows this error: Call to a member function in() on a non-object being thrown from: PageStructureService.php

The only way to clear the cache is to either delete the cache folder via FTP or go to the settings page in the admin and saving ( both option which i assume rebuild the cache )
### Server configuration

**Operating system**:
Mac OSX 10.11.6

**Web server:**
Linux/Apache

**PHP version:**
5.6

**Statamic version:**
2.1.12

**Updated from an older Statamic or fresh install:**
Updated from 2.1.11

**List of installed addons:**
Workshop
Custom Plugin ( which is calling Cache::clear(); )

**Comment by jasonvarga** [comment]
Do you get an error?

Can you confirm what class you are using? `Statamic\API\Cache`?
