### ISSUE TITLE
Search results pagination

### ISSUE THREAD

**Issue by stevieg83** [statamic/v2-hub#1003]
I can add `limit="2"` to search results so I'd assume then I could add `paginate="true"` to paginate through them as per a collection. However adding the paginate param breaks the results.

Is search pagination a thing?

**Comment by jasonvarga** [comment]
Are you using the `as` parameter?

**Comment by stevieg83** [comment]
@jasonvarga started doing that after a Slack conversation with Jack - we're all set - could probably be added to the docs though.
