### ISSUE TITLE
Collections widget should link to collection page, not configure page

### ISSUE THREAD

**Issue by than** [statamic/v2-hub#1008]
### Expected behaviour

I expected that clicking on the header of a dashboard collection would take me to the collections content page.
### Actual behaviour

It takes you to the configuration page. In this screenshot, it's the Current Research link.

![screen shot 2016-09-30 at 9 54 34 am](https://cloud.githubusercontent.com/assets/510790/18995914/fd8bcd50-86f3-11e6-956f-ea662fa397ca.png)

**Statamic version:**
2.1.12

**Comment by jackmcdade** [comment]
Good catch, i totally forgot that header was a link :)
