### ISSUE TITLE
Errors when using cmd-enter keyboard shortcut

### ISSUE THREAD

**Issue by than** [statamic/v2-hub#1009]
### Expected behaviour

Create a new entry. (Has happened on both taxonomies and entries).

Press _cmd-Return_ to save the entry and return to the collection page.
### Actual behaviour

In Safari - Statamic saves the entry, but it throws a js error. 

![screen shot 2016-09-30 at 11 01 41 am](https://cloud.githubusercontent.com/assets/510790/18998220/50ecb8a2-86fd-11e6-9c06-c468a4832d75.png)

I've also seen some cache corruption occur, where the entry will appear twice in the CP.

![screen shot 2016-09-30 at 11 07 45 am](https://cloud.githubusercontent.com/assets/510790/18998386/2c0b8e5e-86fe-11e6-94bd-80f99c199ab9.png)

In Chrome, saving a taxonomy, the taxonomy collection would not display.

![screen shot 2016-09-30 at 10 56 50 am](https://cloud.githubusercontent.com/assets/510790/18998171/129325dc-86fd-11e6-996a-86d2209fb832.png)
### Steps to reproduce
1.  Create a new entry.
2.  Save the entry by pressing cmd-return.
### Server configuration

**Web server:**
local dev with Valet

**PHP version:**
7

**Statamic version:**
2.1.12
### Logs

If any logs (browser, server, or Statamic) are appropriate...

```
Add those logs here
```

**Comment by jackmcdade** [comment]
Got any logs? I can't recreate this.

**Comment by than** [comment]
Doesn't seem to be throwing any logs... 😕

**Comment by jackmcdade** [comment]
Sounds like file permissions to me then. Try to `sudo chmod -R 777 site local statamic` and try again.

**Comment by than** [comment]
Negative, ghost rider. All `777` all the time. Might have a hint here...

**Comment by jackmcdade** [comment]
What's the hint?

**Comment by than** [comment]
Looks like the `publish` endpoint is being called twice.

![screen shot 2016-09-30 at 11 12 16 am](https://cloud.githubusercontent.com/assets/510790/18998560/ca9085d4-86fe-11e6-9afc-42ab5632a257.png)

**Comment by jasonvarga** [comment]
I get that popup if I try to navigate away from the page while the AJAX request is going. Probably the same thing here.

**Comment by than** [comment]
So CP isn't waiting for the request to finish?

**Comment by than** [comment]
Feels like a race condition, since it isn't 100% of the time reproducible for me.

**Comment by jasonvarga** [comment]
Does stuff work if you click save instead?

**Comment by than** [comment]
Yessir. 

But the tax of moving my hand from the keyboard to the mouse is too heavy. 😆

**Comment by than** [comment]
BTW, `cmd-S` for saving in place is working just fine.

**Comment by jasonvarga** [comment]
Happens to me in ~~IE~~ Safari.

**Comment by than** [comment]
I was able to do something similar in Chrome, too. see above.

**Comment by than** [comment]
One other side effect... I end with with the phantom entries if I don't `clear:cache` and the a request to Delete all of those entries fails.

![screen shot 2016-09-30 at 11 36 58 am](https://cloud.githubusercontent.com/assets/510790/18999270/580df31c-8702-11e6-9a7d-f9a29cb66bee.png)

![screen shot 2016-09-30 at 11 38 02 am](https://cloud.githubusercontent.com/assets/510790/18999304/81708d28-8702-11e6-96ee-7876c0372712.png)
