### ISSUE TITLE
Adding custom Nav items to CP throws an error on server (not locally)

### ISSUE THREAD

**Issue by aryehdesigns** [statamic/v2-hub#1015]
### Expected behaviour
I expect the custom nav items to show up with the main navigation and lead to the corresponding route.

### Actual behaviour
Throws an ErrorException on the server (details below).

(Everything works perfectly locally using Valet.)

### Steps to reproduce
1. Add some custom nav items via Addon's Listener.
```php
public $events = [
    'cp.nav.created' => 'addNavItems'
];

public function addNavItems($nav)
{
    $propertyManager = Nav::item('propertymanager')->title('Property Manager')->route('reservations')->icon('archive');

    $propertyManager->add(function ($item) {
        $item->add(Nav::item('Reservations')->route('reservations'));
    });

    $nav->addTo('content', $propertyManager);
}
```

2. Go to Addon's route.

3. Errorz...

If any further details are needed / would help debug, please let me know!

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Nginx
**PHP version:**
7
**Statamic version:**
2.1.12
**Updated from an older Statamic or fresh install:**
Updated
**List of installed addons:**
Custom Addon

### Error
While on a normal CP route (eg. `/pages`), everything works fine and the custom nav item shows up in the sidebar. After clicking on it to go to `/cp/addons/propertymanager/reservations`, this error is shown:

<img width="989" alt="screen shot 2016-10-04 at 17 25 28" src="https://cloud.githubusercontent.com/assets/5065331/19080518/a28a0dec-8a57-11e6-8975-03eeb276844f.png">

---

### Update 1
After a bit of digging I came to this conclusion:

It seems that just before Statamic triggers the `cp.nav.created` event, the `app('Statamic\CP\Navigation\NavFactory')->build()` is called which builds the entire nav structure -- that is then passed on with `cp.nav.created` for custom items to be added before being passed back.

When `dd`ing `$nav` on the server (on a 'normal' route) just before the event is triggered, the Nav tree is complete. When `dd`ing the same thing while on a custom route, the Nav tree is empty.

This doesn't seem to be an issue with my Addon per se because the problem seems to happen before the Addon's Listener is even reached.

---

### Update 2

When removing the event listener and navigating directly to `/cp/addons/propertymanager/reservations`, the Addon's view shows up (YAY)! But now most of the navigation items have disappeared:

![cp](https://cloud.githubusercontent.com/assets/5065331/19081276/04364b3a-8a5a-11e6-9d7b-33b9e3b6f4d0.jpg)

**Comment by aryehdesigns** [comment]
I'm not sure _what_ changed exactly but upgrading Statamic from `2.1.12` to `2.1.13` has fixed the issue when deploying on the server. The Nav items are all there, and nothing breaks!

Closing the issue and apologies if you spent any time looking into the problem...

**Comment by jackmcdade** [comment]
![Confetti yay!](https://media.tenor.co/images/a54c3b8287bd918c44aa21f3e8db67c2/raw)
