### ISSUE TITLE
'required' is not enforced on an Addon's Settings page

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1018]
### Expected behaviour

Error should be presented when saving the addon settings if a field is required and it's empty
### Actual behaviour

Saving occurs and no error is displayed
### Steps to reproduce
1. Create a settings page for an addon and add `validate: required` to a field
2. leave that field blank
3. Save the settings

**Statamic version:**
2.1.13

**Comment by jcohlmeyer** [comment]
I am also experiencing this issue with my addon.
