### ISSUE TITLE
User unable to login if user role cannot Edit Pages

### ISSUE THREAD

**Issue by deepsurface** [statamic/v2-hub#1019]
### Expected behaviour

I expected to create a new user and be able to fine-tune permissions 
### Actual behaviour

I created a user role, logged in as a test user with that role and realized I wanted to further limit the user's ability to edit content. So I unchecked Edit Pages. I was then unable to login as the new user even after resetting the password. 
### Steps to reproduce
1.  Uncheck Edit pages from a user role and then try to login as a user with that role assigned.
2. Note the inability to login as that user. 
3.  Recheck Edit Pages and try to login again as that user.
4. Note the ability to successfully login has been restored.
### Server configuration

**Operating system**:

**Web server:**

**PHP version:**

**Statamic version:**

**Updated from an older Statamic or fresh install:**

**List of installed addons:**
### Logs

If any logs (browser, server, or Statamic) are appropriate...

```
Add those logs here
```

**Comment by jasonvarga** [comment]
Is your start page set to pages?

**Comment by deepsurface** [comment]
Yes. I suppose that was the problem. Looking at the User Role permission options, I didn't really intend to limit access to Pages. That said, I would have rather seen an error message or completely stunted CP interface instead of being unable to login. That result makes it harder to figure out where I screwed up.

**Comment by jackmcdade** [comment]
Understood. We'll work on improving those errors messages.
