### ISSUE TITLE
Missing string in English language file (2.1.12+) : upgrading process

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#1021]
Upgrading from 2.1.13 to 2.1.14 (but I thing I first saw this when upgrading from 2.1.12)

We can see below an untranslated string `cp.download_latest` which appears no to be included in the `en` default language file, therefore is not included here in my own `fr` language file.

![capture d ecran 2016-10-06 a 20 56 08](https://cloud.githubusercontent.com/assets/1823359/19166899/c8249032-8c09-11e6-9a5e-bb1075851f6e.png)

**Comment by ebeauchamps** [comment]
If your default locale is `en` I am pretty sure you are seeing `cp.download_latest` too.

**Comment by ebeauchamps** [comment]
Ah, found it: `downloading_latest` instead of `download_latest`

**Comment by jaggy** [comment]
Yeah, sorry. I must've missed it. It'll be up on the next version. Thanks! 👍

**Comment by ebeauchamps** [comment]
my pleasure

**Comment by ebeauchamps** [comment]
Solved in 2.1.15
