### ISSUE TITLE
UserGroup fieldtype doesn't work

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1022]
### Expected behaviour
Creating/editing content with a usergroups fieldtype works 

### Actual behaviour
Endless spinning loading graphic

### Steps to reproduce
1.  Make a fieldset with a usergroup fieldset
2.  Add a page with that fieldset

### Server configuration
**Operating system**:
macOS Sierra

**Web server:**
Valet 

**PHP version:**
7.0.10

**Statamic version:**
2.1.13 & 2.1.14

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**

**Comment by danieljwestman** [comment]
+1

And the field type options are missing (like Label and UI Mode) for UserGroup.

**Comment by danieljwestman** [comment]
What's up with this?! Not solved in the new fresh relase (2.1.15)?

**Comment by jackmcdade** [comment]
Daniel, We can't fix every open bug for every patch. We'll look into this soon.

**Comment by danieljwestman** [comment]
Cool
