### ISSUE TITLE
CP > Pages does not load in IE11

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1028]
### Steps to reproduce
1.  Go to the CP
2.  Click pages
3.  Blank screen

**Comment by dannyuk1982** [comment]
Anyone else have this in IE?

**Comment by jackmcdade** [comment]
Can you share a screenshot? Also, why are you using IE? 😊

**Comment by dannyuk1982** [comment]
I'm not, but the client is - I imagine many, many end users use Windows + IE, and "use another browser" isn't possible much of the time due to their IT policies/setup
![Uploading Screen Shot 2016-10-17 at 17.57.53.png…]()
.

**Comment by jackmcdade** [comment]
This is the first i've ever heard of it.

**Comment by dannyuk1982** [comment]
I guess many more use/can use Chrome! The odd one can't though - this one was using Chrome, then had to change to IE this month. Guessing it's a FB height bug as the height seems to be 0

**Comment by dannyuk1982** [comment]
OK, I don't know how you do this in whatever is generating the page, but changing #pages from v-cloak 

![screen shot 2016-10-17 at 18 07 01](https://cloud.githubusercontent.com/assets/7669885/19447260/9cf1a1e6-9494-11e6-9b84-601e6189de23.png)

to v-show, makes them appear

![screen shot 2016-10-17 at 18 07 09](https://cloud.githubusercontent.com/assets/7669885/19447269/a415a5a8-9494-11e6-9994-19612da6e036.png)

**Comment by dannyuk1982** [comment]
Is there any way this can be looked at in the near future? I have a client bugging me almost daily as they have to use IE due to their IT policy and so they can't update their website pages when at work.
