### ISSUE TITLE
Unable to create multiple locales in the same language

### ISSUE THREAD

**Issue by huntie** [statamic/v2-hub#1031]
### Expected behaviour

I need to set three locales in a Statamic project – `en_GB`, `en_CA` and `en_US`. I noted that these must be labelled with a two character shortcode, assuming this was just a local name, and that the _Full Locale_ field would be the real value used underneath.

![image](https://cloud.githubusercontent.com/assets/2547783/19280124/4f19f32c-8fdc-11e6-8fe5-7e2ad56e260a.png)
### Actual behaviour

In truth, this is not the exact behaviour, as the shortcode value is used in direct comparison with the localised files within the _Carbon_ date library, which happen to be in the two character format.

**It is critical to localise the site by country, independent of language**, and I can't duplicate the key `en` for each locale.

I suggest a hard fix of making `shortcode` available as an separate property from the locale name, and communicating to the user that this will be used for date localisation. I would then be able to set the following:

| name | title | shortcode | full | url |
| --- | --- | --- | --- | --- |
| gb | English (UK) | en | en_GB | / |
| ca | English (CA) | en | en_CA | /ca/ |
| us | English (US) | en | en_US | /us/ |

Note that `name` would then be the given name to the language by the user, and the value returned by `{{ locale }}` in templates.
### Logs

This is the error logged when visiting the route `/us/` (local project path omitted).

```
[Tue Oct 11 17:50:45 2016] ::1:50519 [500]: /us/ - Carbon\Carbon::setLocale(): Failed opening required 'statamic/vendor/nesbot/carbon/src/Carbon/Lang/us.php' (include_path='.:') in statamic/vendor/nesbot/carbon/src/Carbon/Carbon.php on line 962
```

**Comment by jasonvarga** [comment]
Good find!

**Comment by johanlinander** [comment]
@jasonvarga 

This issue is critical for us when building a international site. Since the app crashes when Carbon does not find a corresponding php-file, it is hard to find a workaround.

I looked at the newer versions of the Carbon library and now they check if the file exist before trying to include it. Maybe you could include a newer version of the lib until you find a good solution?

I think that the proposed solution from @huntie looks good 👍

**Comment by jasonvarga** [comment]
We ended up making the `shortcode` @huntie referenced into a dynamic value. You won't need to make any changes to your `locales` array.

We just take the `full` variable and split it by the underscore.

For example, `full: en_GB`, we'll treat `en` as short and send that along to Carbon.
