### ISSUE TITLE
Underscore & numbered page prevents template from displaying

### ISSUE THREAD

**Issue by PhilippeGauthier** [statamic/v2-hub#1033]
### Expected behaviour
Hiding a page in the nav by using the `_` and a number, such as `_9.contact` shouldn't prevent the template from rendering.

### Actual behaviour
It prevents the template from rendering.

**Comment by jasonvarga** [comment]
Underscores are drafts. Sounds expected.

**Comment by PhilippeGauthier** [comment]
Wasn't there a way of keeping a page out of the nav by using underscores or am I making that up?

**Comment by edalzell** [comment]
@PhilippeGauthier just make a toggle on a page and filter the nav on it.

**Comment by PhilippeGauthier** [comment]
I know there are ways of fixing the issue. For some reason I thought pages
could be prepended with underscores and that would hide them from the nav
but make them visible on the front end if you went directly to the URL (as
opposed to entries). Maybe a bug was fixed and the pages stopped being
visible if they were unpublished, or maybe there was a caching issue and
unpublished pages were visible if you went from being published to
unpublished. Regardless, on browsers i tested with (chrome and safari) an
unpublished page (prepended with an underscore and number) the template
displayed as if it were published but to others it returned a 404. I had
cleared the cache countless times and it made no difference.

**Comment by jackmcdade** [comment]
I think you're thinking of `__` double underscores in v1. A single underscore is a draft, and therefore a 404 by nature. To hide a page from Nav, you can set up a toggle field and filter them out with a condition. Docs here: <https://docs.statamic.com/tags/nav#hidden-pages>
