### ISSUE TITLE
Can't combine replace with other modifiers

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1036]
{{ thing replace="foo|bar" }}
works fine

{{ thing replace="foo|bar" | lower  }}
{{ thing | lower replace="foo|bar" }}
{{ thing | lower | replace="foo|bar" }}
don't work.

**Comment by jackmcdade** [comment]
That's because you're mixing and matching the string and array syntaxes. Try one of these instead:
```
{{ thing replace="foo|bar" lower="true" }}
{{ thing | replace:foo:bar | lower }}
```
Gotta pick _either_ the pipes _or_ the params.
