### ISSUE TITLE
Saving Routes went to a funky URL and 404

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1042]
### Expected behaviour
Stay on routes page, indicating success

### Actual behaviour
went to `http://szc.dev/cp/settings/cp/settings/routes` and got a 404

### Steps to reproduce
1.  add a route
2. save

### Server configuration

**Web server:**
Valet

**PHP version:**
7.0.11

**Statamic version:**
2.1.14

**Comment by jasonvarga** [comment]
Is this the same site where you experienced the /cp/cp/cp/cp redirect after updating?

**Comment by edalzell** [comment]
Sorry Jason, I don't remember. I can try it on a few other of my sites if you like?

**Comment by jasonvarga** [comment]
It's okay. Just think those issues are related.

**Comment by jasonvarga** [comment]
Yup. Fixed.
