### ISSUE TITLE
FR: Publish controls at the bottom on mobile

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#1044]
When editing a long blog post on mobile, you must scroll way back to the top of the Edit page to Save. Could you add Publish controls at the bottom of the page? 

Even better if they were Sticky:

<img width="326" alt="screenshot 2016-10-17 11 39 30" src="https://cloud.githubusercontent.com/assets/414211/19450624/0eb1b7de-945f-11e6-85d2-5e2792f1a980.png">

**Comment by jackmcdade** [comment]
Aren't the control sticky already?

**Comment by jackmcdade** [comment]
Ah no, not on mobile. If we add that, I would make it configurable. Personally I wouldn't like losing 60-80px of vertical space.

**Comment by mikemartin** [comment]
@jackmcdade Not sure if there was a resolution here but the controls don't have to be sticky. There could still be secondary publish buttons at the bottom on mobile.

**Comment by jackmcdade** [comment]
I could get behind that.

**Comment by mikemartin** [comment]
Thank you sir!!

**Comment by jackmcdade** [comment]
Will be revisiting this in v3!
