### ISSUE TITLE
Bug: CP Localisation

### ISSUE THREAD

**Issue by esonesson** [statamic/v2-hub#1047]
### Expected behaviour
When translating the CP to Swedish (site/lang/sv/cp.php), I expected the strings I translated to show up when visiting the CP.

### Actual behaviour
But only some of the translated strings are being translated. Maybe all the strings aren't "tagged" in the view?

### Server configuration
Ubuntu 16.04.1 / Nginx

**PHP version:**
PHP 7.0.8

**Statamic version:**
2.1.13

**Updated from an older Statamic or fresh install:**
Updated from older Statamic (fresh install was v.2)

**Comment by jasonvarga** [comment]
Maybe, but also - if you haven't translated a string into Swedish, it will fall back to our English translation.

**Comment by jasonvarga** [comment]
Are you on the latest version of Statamic?

**Comment by esonesson** [comment]
Nope, 2.1.13. Are more strings added in later updates?

**Comment by jasonvarga** [comment]
I believe so.

**Comment by ebeauchamps** [comment]
Assets should translate nicely
Search for anything will not translate
2.1.14 added some more strings compared to 2.1.13, but Assets has been translated long ago
