### ISSUE TITLE
Contact form page throws error

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#1054]
### Expected behaviour

No error and submissions would be listed out.
### Actual behaviour

An error was thrown and there is nothing listed in the submissions section.
### Steps to reproduce
1.  Click on the Forms link.
2. Click on the form that you want to view submissions for.
3.  Error is thrown.
### Server configuration

**Operating system**:
Ubuntu

**Web server:**
Apache / nginx.

**PHP version:**
7

**Statamic version:**
2.1.13.

**Updated from an older Statamic or fresh install:**
Fresh install.

**List of installed addons:**
None.
### Logs

If any logs (browser, server, or Statamic) are appropriate...
[statamic-2016-10-21.txt](https://github.com/statamic/v2-hub/files/543388/statamic-2016-10-21.txt)

![screen shot 2016-10-20 at 10 17 41 pm](https://cloud.githubusercontent.com/assets/1793867/19584562/64ea378c-9713-11e6-800d-beb3c04aa4f2.png)

**Comment by jasonvarga** [comment]
Try moving chunks of form responses out of the folder and see when it starts working again.

Looking at the logs, there's a familiar error that we've seen when there's some weird data in a file.

If you find the problem file, let us know what was in it.

**Comment by thestepafter** [comment]
Found the offender for you.

[1475682931.txt](https://github.com/statamic/v2-hub/files/543399/1475682931.txt)

**Comment by jasonvarga** [comment]
Looks like it might be those characters you're using for bullets. Can you try replacing them with dashes or something?

**Comment by thestepafter** [comment]
I'm not using them for bullets. That is what the person put in their message, it is out of my control. I will remove them for testing purposes but it is out of my control what people put in the text box.

**Comment by jasonvarga** [comment]
Of course. I'm just trying to narrow down the problem.

**Comment by thestepafter** [comment]
I removed the special characters and it is now work. Please note that on the server when I opened the .yaml in vi the special character shows as <95>.

![screen shot 2016-10-20 at 10 40 00 pm](https://cloud.githubusercontent.com/assets/1793867/19584929/2b1fae30-9716-11e6-9bed-37d2876c2376.png)

**Comment by jasonvarga** [comment]
Looks like that's the problem. Not quite sure of a solution yet though.

**Comment by thestepafter** [comment]
Ok, thanks!

**Comment by jackmcdade** [comment]
Since we're unable to recreate this and haven't received any more info, I'm going to close this issue. If you or anyone else has more information leading to the identification and elimination of this oddity, please reopen with said knowledge!
