### ISSUE TITLE
'get:slug' (modifier) doesn't work on content

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1057]
### Expected behaviour
The `slug` is retrieved

### Actual behaviour
Nada

### Steps to reproduce
1. on an `id`, use the `get:slug` modifier. i.e. `{{ get:course | get:slug }}` 

**Statamic version:**
2.1.15

**Comment by jasonvarga** [comment]
Fixed in the next release. We're performing `->toArray()` on the relationship now before retrieving your requested value.
