### ISSUE TITLE
Saving Taxonomy with Search Auto Index using Zend breaks CP

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/v2-hub#1066]
### Expected behaviour
Saving / creating taxonomy to save and continue to let me access the CP.

### Actual behaviour
Saving a new taxonomy troughs an error and I can not access CP until I manually delete the taxonomy's md file.

### Steps to reproduce
1.  Enable Search with Zend
2.  Enable Search Auto Index
3.  Create a new Taxonomy term

### Server configuration
**Operating system**: Mac OSX 10.11.6

**Web server:** Apache

**PHP version:** 7

**Statamic version:** 2.1.15

**Updated from an older Statamic or fresh install:** 2 fresh & upgrade(s)

**List of installed addons:**
Colorpicker

### Logs
[2016-10-25 20:02:34] dev.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getItem() on null in /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Data/Services/TermsService.php:27
Stack trace:
#0 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/API/Term.php(27): Statamic\Data\Services\TermsService->id('a8edc93b-5a5a-4...')
#1 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Data/Content/ContentCollection.php(162): Statamic\API\Term::find('a8edc93b-5a5a-4...')
#2 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Data/Taxonomies/Term.php(168): Statamic\Data\Content\ContentCollection->filterByTaxonomy('a8edc93b-5a5a-4...')
#3 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Data/Taxonomies/Term.php(314): Statamic\Data\Taxonomies\Term->collection()
#4 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Data/Taxonomies/Term.php(330): Statamic\Data\Taxonomies\Term->count()
#5 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Data/Data.php(582): Statamic\Data\Taxonomies\Term->supplement()
#6 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/bundles/Search/SearchListener.php(57): Statamic\Data\Data->toArray()
#7 [internal function]: Statamic\Addons\Search\SearchListener->insert(Object(Statamic\Events\Stache\RepositoryItemInserted))
#8 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Array, Array)
#9 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(355): Illuminate\Events\Dispatcher->fire('Statamic\\Events...', Array, false)
#10 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Repository.php(259): event(Object(Statamic\Events\Stache\RepositoryItemInserted))
#11 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/AggregateRepository.php(256): Statamic\Stache\Repository->setItem('a8edc93b-5a5a-4...', Object(Statamic\Data\Taxonomies\Term))
#12 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Updater.php(251): Statamic\Stache\AggregateRepository->setItem('a8edc93b-5a5a-4...', Object(Statamic\Data\Taxonomies\Term))
#13 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(135): Statamic\Stache\Updater->Statamic\Stache\{closure}(Array, 0)
#14 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Updater.php(255): Illuminate\Support\Collection->each(Object(Closure))
#15 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Updater.php(268): Statamic\Stache\Updater->updateItems(Object(Illuminate\Support\Collection), 'tags')
#16 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(135): Statamic\Stache\Updater->Statamic\Stache\{closure}(Object(Illuminate\Support\Collection), 'tags')
#17 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Updater.php(285): Illuminate\Support\Collection->each(Object(Closure))
#18 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Updater.php(138): Statamic\Stache\Updater->updateAggregate()
#19 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Updater.php(109): Statamic\Stache\Updater->updateDefault()
#20 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/UpdateManager.php(55): Statamic\Stache\Updater->update()
#21 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(135): Statamic\Stache\UpdateManager->Statamic\Stache\{closure}(Object(Statamic\Stache\Drivers\TermsDriver), 'terms')
#22 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/UpdateManager.php(63): Illuminate\Support\Collection->each(Object(Closure))
#23 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Manager.php(79): Statamic\Stache\UpdateManager->update()
#24 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Providers/StacheServiceProvider.php(138): Statamic\Stache\Manager->update()
#25 [internal function]: Statamic\Providers\StacheServiceProvider->boot(Object(Illuminate\Http\Request))
#26 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#27 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#28 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(Statamic\Providers\StacheServiceProvider))
#29 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Statamic\Providers\StacheServiceProvider), 25)
#30 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure))
#31 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#32 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Statamic\Application))
#33 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(222): Illuminate\Foundation\Application->bootstrapWith(Array)
#34 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->bootstrap()
#35 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#36 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#37 {main}  
[2016-10-25 20:02:39] dev.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getItem() on null in /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Data/Services/TermsService.php:27
Stack trace:
#0 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/API/Term.php(27): Statamic\Data\Services\TermsService->id('a8edc93b-5a5a-4...')
#1 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Data/Content/ContentCollection.php(162): Statamic\API\Term::find('a8edc93b-5a5a-4...')
#2 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Data/Taxonomies/Term.php(168): Statamic\Data\Content\ContentCollection->filterByTaxonomy('a8edc93b-5a5a-4...')
#3 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Data/Taxonomies/Term.php(314): Statamic\Data\Taxonomies\Term->collection()
#4 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Data/Taxonomies/Term.php(330): Statamic\Data\Taxonomies\Term->count()
#5 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Data/Data.php(582): Statamic\Data\Taxonomies\Term->supplement()
#6 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/bundles/Search/SearchListener.php(57): Statamic\Data\Data->toArray()
#7 [internal function]: Statamic\Addons\Search\SearchListener->insert(Object(Statamic\Events\Stache\RepositoryItemInserted))
#8 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Array, Array)
#9 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(355): Illuminate\Events\Dispatcher->fire('Statamic\\Events...', Array, false)
#10 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Repository.php(259): event(Object(Statamic\Events\Stache\RepositoryItemInserted))
#11 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/AggregateRepository.php(256): Statamic\Stache\Repository->setItem('a8edc93b-5a5a-4...', Object(Statamic\Data\Taxonomies\Term))
#12 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Updater.php(251): Statamic\Stache\AggregateRepository->setItem('a8edc93b-5a5a-4...', Object(Statamic\Data\Taxonomies\Term))
#13 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(135): Statamic\Stache\Updater->Statamic\Stache\{closure}(Array, 0)
#14 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Updater.php(255): Illuminate\Support\Collection->each(Object(Closure))
#15 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Updater.php(268): Statamic\Stache\Updater->updateItems(Object(Illuminate\Support\Collection), 'tags')
#16 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(135): Statamic\Stache\Updater->Statamic\Stache\{closure}(Object(Illuminate\Support\Collection), 'tags')
#17 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Updater.php(285): Illuminate\Support\Collection->each(Object(Closure))
#18 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Updater.php(138): Statamic\Stache\Updater->updateAggregate()
#19 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Updater.php(109): Statamic\Stache\Updater->updateDefault()
#20 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/UpdateManager.php(55): Statamic\Stache\Updater->update()
#21 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(135): Statamic\Stache\UpdateManager->Statamic\Stache\{closure}(Object(Statamic\Stache\Drivers\TermsDriver), 'terms')
#22 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/UpdateManager.php(63): Illuminate\Support\Collection->each(Object(Closure))
#23 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Stache/Manager.php(79): Statamic\Stache\UpdateManager->update()
#24 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/core/Providers/StacheServiceProvider.php(138): Statamic\Stache\Manager->update()
#25 [internal function]: Statamic\Providers\StacheServiceProvider->boot(Object(Illuminate\Http\Request))
#26 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#27 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#28 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(Statamic\Providers\StacheServiceProvider))
#29 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Statamic\Providers\StacheServiceProvider), 25)
#30 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure))
#31 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#32 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Statamic\Application))
#33 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(222): Illuminate\Foundation\Application->bootstrapWith(Array)
#34 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->bootstrap()
#35 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#36 /Volumes/Work Disk/jcohlmeyer/Sites/sdg/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#37 {main}

**Comment by dannyuk1982** [comment]
This looks similar to https://github.com/statamic/v2-hub/issues/1070 but in addition it doesn't matter if Zend or Search Auto Index are in use, and it also breaks the site in addition to the CP

**Comment by jasonvarga** [comment]
I believe this is fixed in 2.1.17
