### ISSUE TITLE
Ability to enable/disable the CP per environment

### ISSUE THREAD

**Issue by jasonvarga** [statamic/v2-hub#1067]

**Comment by kmccauley138** [comment]
I would love to have this capability

**Comment by jackmcdade** [comment]
You could gitignore index.php and then have separate copies on dev and production. Just an idea!

**Comment by peterbaker** [comment]
Or use $_SERVER['REQUEST_URI'] in the index.php to check for a production URL. I'm hesitant to ignore index.php in Git because it's 100% crucial to deploying the site and running locally, so it'd be a major point of documentation/setup beyond just "pull from git and get going".

**Comment by kmccauley138** [comment]
Thanks a bunch for the quick responses! Went with the $_SERVER['REQUEST_URI']
solution due to working with a team & less to have to explain/document...

**Comment by kevnk** [comment]
For latest documentation on this, check out https://docs.statamic.com/control-panel

> If you want to disable per-environment, you may add the following to your `.env` file on the appropriate environments.
>
> ```
> DISABLE_CP=true
> ```
