### ISSUE TITLE
Exceptions and bugs should not take out entire site/cp

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1071]
### Expected behaviour
If there is a problem/bug it should be logged

### Actual behaviour
Some problems/bugs cause a "Whoops" error that takes the entire site and cp offline

### Steps to reproduce
1.  Find a serious bug
2.  Site and CP go off line

Much of the time clearing the cache fixes at least access to the site/CP, could this be automated? This would cause far less downtime than waiting for a human to see the fault, SSH/FTP in and clear the cache manually. Or can exceptions be caught in such a way that they do not take out the site - i.e. if the cache is corrupted do not use it (slow, but far better than no site)

**Comment by jasonvarga** [comment]
If there's an issue when building the cache it'll throw an exception. I agree with you. But I'm closing this issue though since its not really specifically addressable.

**Comment by dannyuk1982** [comment]
OK, can cache exceptions be caught at least then? And any other exceptions that currently take out the whole site?
