### ISSUE TITLE
Can edit a search setting controlled by an environment setting

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1073]
### Expected behaviour

Field can't be edited
### Actual behaviour

Field can be edited 
### Steps to reproduce
1. Use Algolia & set your default index to something (I have `live`)
2. Set it to something else in your local environment (I have `dev`)
3. Go edit it.
### Server configuration

**Statamic version:**
2.1.17

**Comment by edalzell** [comment]
It gets a little worse...if you have something like `"{env:ALGOLIA_API_KEY}"` in your `search.yaml` file, when you save the settings, that is overwritten w/ the actual key.

**Comment by curtisblackwell** [comment]
I see this same problem with the debug toggle in the CP settings. I have an env var set for it and I can still change it in the CP.
