### ISSUE TITLE
FR: make the console commands consistent

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1074]
Sorry, another "Erin" issue...

I can never remember the `please` commands because some of them are `verb:noun` and some are `noun:verb`

Anyway to make it consistent?

**Comment by jackmcdade** [comment]
They follow the same pattern as Laravel. `make:something` or `noun:verb`.

**Comment by edalzell** [comment]
well not really, `convert:email-login` and `clear:static`, but not a big deal. Just my poor memory.
