### ISSUE TITLE
CP Form Widget should display the newest submissions first

### ISSUE THREAD

**Issue by pmeissner** [statamic/v2-hub#1075]
The Form Widget displays oldest submissions first so new submissions are missed if they fall below the max display threshold.

The newest submissions by default should come first.

**Comment by pmeissner** [comment]
Can I open this one back up? The form widget shows the newest one first FROM LAST YEAR. But submissions made this year (2017) fall below below the 2016 year submissions.

I don't think the year is considered when the widget displays them chronologically.

**Comment by jackmcdade** [comment]
This is working correctly now.
