### ISSUE TITLE
CP Pages links are finicky

### ISSUE THREAD

**Issue by PhilippeGauthier** [statamic/v2-hub#1076]
### Expected behaviour

Clicking the anchor links on individual pages in the CP results in going to the desired edit Page.
### Actual behaviour

Clicking the links does nothing some times. I think it may be because they're wrapped in `<div class="page-text">`. 

Happens in Chrome and Safari.

**Comment by curtisblackwell** [comment]
James and I both run into this all the time.

**Comment by jasonvarga** [comment]
Can you record a video of this?

**Comment by curtisblackwell** [comment]
Not encountering the problem now that I want to record it… I'll do so next time I see it happen.

**Comment by PhilippeGauthier** [comment]
Here you go:

https://cl.ly/0n3N362v4329/o

The last click was a double click which took me to the page.

**Comment by peimn** [comment]
I have had this before: #899
