### ISSUE TITLE
UserTags method doesn't seem to do what it says?

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1080]
Am I misreading this:

```
/**
 * Dynamically fetch a user's data by variable_name
 *
 * Maps to {{ user:variable_name }}
 *
 * @return string
 */
public function __call($method, $args)
{
    $id = array_get($this->context, $method);

    if ($user = User::find($id)) {
        return $this->parse($user->toArray());
    }
}
```

I was trying to check for the `super` field in a user, so I went `{{ user:super }}`, but that first line is looking for `super` in the context, which isn’t right and won’t get the `id`.

**Comment by jasonvarga** [comment]
It works just like the relate tag. The variable name should hold a user ID.

**Comment by edalzell** [comment]
OK, so the comment isn't clear then. Got it. No biggie.
