### ISSUE TITLE
Email Settings Don't Load ENV Variables

### ISSUE THREAD

**Issue by warkior** [statamic/v2-hub#1085]
### Expected behaviour
When adding ENV variables to the email.yaml file, they should be loaded properly into the mail system for use in delivery. For example...
```
host: {env:MAIL_HOST default='smtp.mailservice.com'}
port: {env:MAIL_PORT default='587'}
encryption: {env:MAIL_ENCRYPTION default='tls'}
username: {env:MAIL_USERNAME}
password: {env:MAIL_PASSWORD}
```

### Actual behaviour
`[2016-11-03 21:10:00] local.ERROR: ErrorException: strtolower() expects parameter 1 to be string, array given in /Users/myusername/sites/mystatamicsite/statamic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php:143`

... and ...

```
[2016-11-03 21:11:07] local.DEBUG: array (
  '$encryption' => 
  array (
    0 => 'env:MAIL_ENCRYPTION default=\'tls\'',
  ),
)  
```

... also ...

`[2016-11-03 21:12:13] local.ERROR: ErrorException: Array to string conversion in /Users/myusername/sites/mystatamicsite/statamic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:253`

### Steps to reproduce
1.  See above
2. Sending mail from an addon using `Statamic\API\Email::create()`

### Server configuration
**Operating system**: MacOS

**Web server:** Valet

**Statamic version:** 2.0.11

**Updated from an older Statamic or fresh install:** Updated from old

(edited steps to reproduce)

**Comment by warkior** [comment]
To clarify things further, I am attempting to send the mail manually in an addon using `Statamic\API\Email::create()`

**Comment by jasonvarga** [comment]
You have to wrap the values in quotes.

value: "{env:FOO}"

**Comment by warkior** [comment]
@jasonvarga - Pretty sure I tried that with no success.

**Comment by jasonvarga** [comment]
The defaults parameters don't work when using them in YAML.

**Comment by warkior** [comment]
@jasonvarga - Ah hah! That did it. Switching to the following...
```
host: "{env:MAIL_HOST}"
port: "{env:MAIL_PORT}"
encryption: "{env:MAIL_ENCRYPTION}"
username: "{env:MAIL_USERNAME}"
password: "{env:MAIL_PASSWORD}"
```

**Comment by warkior** [comment]
Thank you sir! Marking this closed.
