### ISSUE TITLE
FR: Better errors in the CP when asset upload fails

### ISSUE THREAD

**Issue by gmcz** [statamic/v2-hub#1090]
When uploading an asset fails in the Control Panel, the user gets raw HTML output into the CP. Even for those of us who make websites for a living and can parse it, it’s no fun to look at. It would be much better if this was cleaned up... even if it just said “there’s an error. check the logs”. 

Outputting raw HTML as text in the CP seems like a pretty hostile experience for CP users.

**Comment by jasonvarga** [comment]
Yup that sucks. It's on our list for 2.2
