### ISSUE TITLE
OAuth logins taking ~20s

### ISSUE THREAD

**Issue by markzegarelli** [statamic/v2-hub#1096]
### Expected behaviour
Login should be expedited

### Actual behaviour
On login, via a New Relic dashboard, I see that the `/oauth.callback` transaction is taking anywhere from 15-30s.

Logging shows me that [roughly 85%](http://imgur.com/ynq4QZv) of that time is taken up by `Spyc::loadWithSource`. I can see that this is being called [hundreds of times](http://imgur.com/3CcdUFs).

I think the issue is caused by the `getOauthID` function in `statamic/core/Data/Users/User.php` parsing every line in `local/cache/oauth_ids.yaml` until it finds the match.

FYI, this is the custom OAuth solution provided by you, prior to releasing the official version.

### Steps to reproduce
1.  Seed a site with a few hundred users and ids in `oauth_ids.yaml`.
2.  Log in to the site via OAuth.
3.  

### Server configuration
**Operating system**:
Ubuntu
**Web server:**
Nginx
**PHP version:**
7
**Statamic version:**
2.1.16
**Updated from an older Statamic or fresh install:**

**List of installed addons:**

**Comment by jasonvarga** [comment]
Fixed for next release.
