### ISSUE TITLE
Clicking on pages in CP causes duplicate page

### ISSUE THREAD

**Issue by brianyuen** [statamic/v2-hub#1097]
### Expected behaviour
Clicking on page should take user to page details

### Actual behaviour
Clicking on page duplicates page

### Steps to reproduce
1.  Click on page link (lower part of link) 

### Server configuration
**Operating system**:
Linux

**Web server:**

**PHP version:**

**Statamic version:**
2.1.17

**Updated from an older Statamic or fresh install:**
Fresh

**List of installed addons:**
None

### Video link
https://cloudup.com/cQcPmzEdcEs

**Comment by than** [comment]
See also #1103

**Comment by jasonvarga** [comment]
Confirmed. I can only make it happen when there's only one page. Sound about right for you guys?

**Comment by than** [comment]
Yep. Problem seemed to go away when I added subsequent pages.
