### ISSUE TITLE
Taxonomy field with max_items: 1 prevents saving when the field is empty

### ISSUE THREAD

**Issue by miktirr** [statamic/v2-hub#1101]
### Expected behaviour
If a taxonomy field has a `max_items` setting that is set to `1`, the field can be saved with only one taxonomy term or without a taxonomy term (i.e. as empty) in CP.

### Actual behaviour
Trying to save when the field is empty throws ”There was a problem saving the data. Please check your logs.” and in the logs there is:

`[2016-11-03 08:22:40] production.ERROR: ErrorException: Undefined offset: 0 in [...]/statamic/bundles/Relate/RelateFieldtype.php:29`

### NB
Saving empty fields works if the `max_items` is set as `max_items: "1"` (not `max_items: 1`). But this seems at least inconsistent with the `max_files` setting for assets.

### Server configuration

**Web server:**
Apache

**PHP version:**
7.0.12

**Statamic version:**
2.1.17

**Comment by jackwakefield** [comment]
A temporary fix is changing line 11 in statamic/bundles/Relate/RelateFieldtype.php from
```php
if ($this->getFieldConfig('max_items') === 1 && is_array($data)) {
```
to
```php
if ($this->getFieldConfig('max_items') === 1 && is_array($data) && array_key_exists(0, $data)) {
```
