### ISSUE TITLE
Password reset returns WHOOPS for some users.

### ISSUE THREAD

**Issue by danielfowler** [statamic/v2-hub#1114]
[Try it on our dev server](https://dev.coe.uga.edu/forgot-password) with one user `dfo` (that's me) and another user `cseymour` (that's Chris). Our user files are mostly the same, with the same roles and types of content.

I expect you to get a WHOOPS error on my username, but not his.

**Comment by jasonvarga** [comment]
The whoops screen without a stack trace unfortunately isn't helpful to us.

**Comment by danielfowler** [comment]
![screenshot](https://i.imgur.com/VorGN7U.png)

**Comment by jasonvarga** [comment]
Are you doing a AJAX request there? I get a 500 for both usernames, and also when leaving it blank.

**Comment by danielfowler** [comment]
No. We can't use AJAX for core functionality (accessibility rules).

**Comment by jasonvarga** [comment]
How come you see the trace and we don't? Are you testing on a separate server?

**Comment by danielfowler** [comment]
No. Turning on debug broke our server. So I turned it back off.

![debug broke our server](https://i.imgur.com/mPdHyhM.png)

**Comment by dannyuk1982** [comment]
Is that page cached, or full measure? The _token hidden form input (`IgbwmKpDCezUyTkBLGMUzo21NCfztWghG7f2o4cO`) is always the same for me. I think that should change?

**Comment by jackmcdade** [comment]
Is this still an issue here? Any new info that could help if so?

**Comment by danielfowler** [comment]
I've not noticed this problem in the past couple of weeks, so.... /shrug
