### ISSUE TITLE
Illuminate/Support/Collection::Map takes a total of 30% - 50% of page load time

### ISSUE THREAD

**Issue by markzegarelli** [statamic/v2-hub#1116]
Using NewRelic, I can see that the `Illuminate/Support/Collection::Map` function takes more time than any other function on most pages.

![Imgur](http://i.imgur.com/fUjimLL.png)

These calls happen during the Stache loading process, specifically called from `Statamic\Stache\Drivers\UsersDriver::load` in most cases.

![Imgur](http://i.imgur.com/bCM5ZRI.png)

The site currently has 609 users.

This issue is mitigated after running `cache:clear`. Page loads go from ~3s to <1 as you can see in the following image, in which the cache was cleared around 10:15.

![Imgur](http://i.imgur.com/SwMYfVk.png)

## Background
**Server**: Digital Ocean 1cpu / 512mb droplet. Forge provisioned.
**PHP**: 7
**Site Size**: ~425 entries / pages
**Users**: 609
**OAuth**: yes

**Comment by jackmcdade** [comment]
Yep, that method wraps a lot of the caching work. There's not much I can do directly that would let me resolve this issue, so I'll close it with this:

We're working on performance from many angles. It'll keep getting better.

**Comment by AdilAmanat** [comment]
@jackmcdade  I can still see same after more than 5 years. Can you please add any update on it what should be a better way to proceed? For me, it is taking 9 seconds and the total request time is 10 sec.

**Comment by jesseleite** [comment]
@AdilAmanat If you want to avoid function calls on page load/render, you can utilize our cache tags, static caching solutions, etc. Read more here: https://v2.statamic.com/caching

I should also note that there have been many improvements to performance in Statamic v3, and most of our efforts are going into v3 at this point.
