### ISSUE TITLE
FR: Search Scope

### ISSUE THREAD

**Issue by humanjpg** [statamic/v2-hub#1118]
### Expected behaviour
Would be great to be able to set search to only return specific entities in accordance with:

```
is_page
is_entry
is_term
```

So, effectively something like:

```
{{ search:results target="entries|pages" }} 
...
```

Should just return entries and pages.

### Actual behaviour
Pagination includes `terms`, `pages` and `terms` in the results even when you use a conditional:

```
{{ search:results paginate="true" }}
  {{ if is_entry }}
    {{ title }}
  {{ /if }}
  {{ theme:partial src="pagination" }}
{{ / search:results }}
```

Which obviously makes sense as there's no scope limitation to the search.

**Comment by humanjpg** [comment]
Is there any way around this?

**Comment by jasonvarga** [comment]
This is _kinda_ done in 2.6.
You can search within a collection.
