### ISSUE TITLE
FR: Static cache invalidation when deleting content

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1122]
### Expected behaviour
When a page is deleted it should be removed from the navigation

### Actual behaviour
The newly removed page does not update in the navigation until another the cache is cleared

### Steps to reproduce
1.  Make sure Static page caching (half measure) is on
2. Delete a page
3. Check the nav & page - as before the deletion
4. Clear the cache - the nav updates and the page is now a 404 

### Server configuration
**Operating system**:
centos

**Web server:**
apache

**PHP version:**
7

**Statamic version:**
2.2.18

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**
none

**Comment by dannyuk1982** [comment]
same thing is happening with entries

**Comment by jasonvarga** [comment]
This makes sense because you've statically cached a page, and there's currently no rule for what URLs should get invalidated when a page gets deleted.

This issue should instead of being a considered a bug, it should be an (absolutely reasonable) feature request for invalidating stuff when content is deleted.

**Comment by dannyuk1982** [comment]
That is confusing if that is by design then, when it says this on that page:

![screen shot 2017-01-20 at 19 18 43](https://cloud.githubusercontent.com/assets/7669885/22162137/4ad81f74-df45-11e6-826d-a52fb017a292.png)

It definitely needs to be an option then, as otherwise the CP + caching makes no sense for the end user (without installing EMD's powertools and telling them to click "clear cache" after every change)

**Comment by jasonvarga** [comment]
The setting you just screenshotted is about updating the Stache.
The Stache _does_ get updated when you edit something in the CP.

The Stache is completely separate from the Static Cache.
The Static Cache is a whole other level of caching. _That's_ what needs to be cleared.

I'm saying what you're essentially asking for should exist in Statamic. It's just not a "bug".

**Comment by dannyuk1982** [comment]
How does this work with `static_caching_invalidation` as well? Because, e.g. I have this for blog

```static_caching_invalidation:
  collections:
    blog:
      urls:
        - /
        - /about-us/blogs
        - '/about-us/blogs/*'
        - '/about-us/staff/*'
```

Yet deleting a blog item does not update `/about-us/blogs`

**Comment by dannyuk1982** [comment]
Ah OK - I think I understand. The difference between Stache and Static Cache in my mind is a bit muddy!

**Comment by jasonvarga** [comment]
Please re-read [my earlier comment](https://github.com/statamic/v2-hub/issues/1122#issuecomment-274145903).

I said nothing is invalidated when something gets deleted. It should.

**Comment by dannyuk1982** [comment]
I think I wrote that about 2 seconds after you posted - I getcha
