### ISSUE TITLE
FR: Enable PHPUnit tests to work with addons

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1125]
### Expected behaviour
Running `phpunit` does work an runs all tests in `site/tests`

### Actual behaviour
It does not work and shows error:

#### 1. Autoloader is not loaded
`PHP Fatal error:  Uncaught Error: Class 'Statamic\API\Path' not found in .../statamic/bootstrap/start.php:20`

*Workaround*, replace `/helpers.php` with `/autoload.php` inside `site/tests/bootstrap.php`

#### 2. StacheServiceProvider references class which is not included in distributed sources
By running `phpunit` the tests are executed but fail with following error:

`Error: Class 'Tests\Doubles\StacheTestManager' not found` this class is referenced inside the `StacheServiceProvider`

Inside `core/Testing` there is another reference to a class not included in the available source.
`TestCase.php` uses `Tests\Doubles\EventFake`

### Steps to reproduce
1.  `cd statamic`
2.  `composer install` required to install the dev dependencies
3.  `cd ..`
4. `phpunit` (must be already be installed on the host, example `brew install phpunit`)

### Server configuration
**Operating system**: MacOS

**PHP version:** 7.0

**Statamic version:** 2.1.18

**Comment by warkior** [comment]
+1 for this. I'd love to be able to use phpunit to run proper tests for both addons and general site functionality. Currently have to use codeception but it's VERY slow to run.

**Comment by glennkarlsen** [comment]
+1

**Comment by jasonvarga** [comment]
Fixed for next release, with new commands.

```
php please test
php please test:site
php please test:addons
php please make:test
```
