### ISSUE TITLE
Add limit and offset parameters to nav tag

### ISSUE THREAD

**Issue by jasonvarga** [statamic/v2-hub#1127]

**Comment by rockethouse** [comment]
+1

**Comment by beeldr** [comment]
I'm having the same issue as [this guy](https://lodge.statamic.com/questions/2597-statamic-2-nav-limit-and-offset), is there any progress on this issue?

**Comment by rickysalsberry** [comment]
+1 – this would be useful. Thanks!

**Comment by mrkaluzny** [comment]
+1 Still not done? Wow.

**Comment by jackmcdade** [comment]
It doesn't _really_ make sense to have this on the nav tag. If you want to just list and filter and control your pages, you can use the [Pages Tag](https://docs.statamic.com/tags/pages). The Nav tag is meant to output your structured nav.

**Comment by mrkaluzny** [comment]
@jackmcdade It makes sense if you have a custom menu that's divided into different segments. Limit makes it easier for people working with Statamic's backend to set the nav the way they want. The structured nav works well with "classic" navbars, but something more complicated and it's really hard to create a flexible and editable nav + you can't use nav variables ;)

**Comment by jackmcdade** [comment]
What about the Pages tag though? Wouldn't that let you grab things however you want?

**Comment by mrkaluzny** [comment]
@jackmcdade I can do that, but the problem with checking which link still persists. The more optimal way to do that would be limiting with the nav tag.

```
{{ nav from="/" exclude="/in-person|/services|/contact|/blog" }}
  <li class="nav-item {{if is_current}} active {{endif}}">
    <a class="nav-link" href="{{ url }}">{{ title | lower}}</a>
  </li>
 {{ /nav }}
``` 

That's my current solution which isn't optimal at all. With limit property, anyone can easily reorder pages in the nav but not completely (excluded one's will always be excluded), but the is_current is probably worth the tradeoff. But maybe I'll switch to Pages tag after all...

**Comment by jackmcdade** [comment]
You could make that less brittle by just adding a toggle fieldtype and then filtering those pages out. Something like `hide_from_nav`.

```
{{ nav from="/" hide_from_nav:isnt="true" }}
...
{{ /nav }}
```

**Comment by jackmcdade** [comment]
All things considered though, who are we to judge? It'll be in the next release.
