### ISSUE TITLE
taxonomy ids getting created as other taxonomy md files.

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/v2-hub#1128]
I'm not sure how or what is causing this but in many of our taxonomy folders we have had the ids of one taxonomy created as a separate taxonomy item.

<img width="685" alt="screen shot 2016-11-25 at 10 13 13 am" src="https://cloud.githubusercontent.com/assets/622598/20633109/d2398194-b2f7-11e6-979f-8571edc9dc51.png">

I'm running 2.1.18 but not sure when this started.

**Comment by jasonvarga** [comment]
I believe its the same or similar issue as: https://github.com/statamic/v2-hub/issues/1093

I think it has something to do when "adding" a new term that already exists.

Thank you for the report.

**Comment by sheldonkotyk** [comment]
![screen shot 2016-11-25 at 11 28 23 am](https://cloud.githubusercontent.com/assets/622598/20634149/50a62528-b302-11e6-9a67-3967cea4f6e7.png)

We use panes. Not sure how the team would add a duplicate to that taxonomy.

**Comment by jasonvarga** [comment]
Then its not that :)

**Comment by sheldonkotyk** [comment]
[2016-12-21 19:21:05] dev.ERROR: Exception: Taxonomy and/or slug have not been specified. in /home/statamic/core/Data/Content/PathBuilder.php:114

**Comment by jasonvarga** [comment]
When 2.5 is here, this should be a non-issue.

After it's released, please reopen if it still exists for you.

**Comment by sheldonkotyk** [comment]
OK, looks like we still have an issue in 2.5.1.

![image001](https://cloud.githubusercontent.com/assets/622598/22449420/fb2543f8-e714-11e6-9032-4cf75d618527.png)

No files were created with the IDs though.

**Comment by jasonvarga** [comment]
The IDs – which were created by the previous bug – are still in your content. Since they're in there, they are getting picked up as taxonomy terms. So, it's working correctly.

You need to remove those IDs from the content.

**Comment by sheldonkotyk** [comment]
You're right. I thought my previous find and replaces got them all. Sorry for the not a bug.
