### ISSUE TITLE
With "stache_always_update: false" set, a new page added through CP is not visible in page listing

### ISSUE THREAD

**Issue by castirondesign** [statamic/v2-hub#1134]
### Expected behaviour
With stache_always_update: false set, publishing via CP should update the stache. When adding a new page it should show up in the CP pages listing.

### Actual behaviour
New pages do not appear in the pages listing unless you manually update the stache (such as by saving something in the settings). Collection entries work as expected.

### Steps to reproduce
1.  Set stache_always_update: false
2.  Create a new page and save it
3.  View pages listing and see page is not there

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache

**PHP version:**
7

**Statamic version:** 
2.1.18

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**
None

**Comment by AndyBursh** [comment]
Is there an expected time frame for a fix on this? I have a site for which the `stache_always_update: true` workaround doesn't work (because of what seems like another bug, as [described on slack](https://statamic.slack.com/archives/statamic-v2/p1481120207001019))
