### ISSUE TITLE
Translations: Fields on a form get untranslatable ' field' appended to validation errors

### ISSUE THREAD

**Issue by tkuijer** [statamic/v2-hub#1135]
### Expected behaviour
When I add a new language and add translations for validation rules, I expect to see a translated text on the validation error message.

### Actual behaviour
I see my translated validation message, but the field labels all have ' field' appended to them.

### Steps to reproduce
1. Set up statamic with a different locale
2. Set up a Form (ie. a Contact form) with field validations
3. Add translated validation messages
4. Submit Form with data triggering validation errors

### Server configuration
**Operating system**:
Linux Mint 17

**Web server:**
Apache 2.4

**PHP version:**
PHP 7.0

**Statamic version:**
Statamic 2.1.16

**Updated from an older Statamic or fresh install:**
Fresh install

### Cause
This unexpected behavior is caused by the 'Submission' (`core/Form/Submission.php`) class appending ' field' (Line `218`) to every form field. 
Comment states this is to define a friendly name for form fields, but it also causes validation messages to not be properly translatable.

**Comment by patrikkernke** [comment]
I have the same bug. Is there a solution? My customer want quick a clean validation message :) my client site is already in production.

Thanks in advanced!

**Comment by patrikkernke** [comment]
Is this bug already solved? It shows really a bad validation message in other translations than english.

**Comment by jasonvarga** [comment]
Seems fine to me, maybe I'm missing a detail.

![image](https://user-images.githubusercontent.com/105211/40994161-8c6cf7d4-68c9-11e8-803d-f8875263f667.png)

**Comment by patrikkernke** [comment]
But in your message ":attribute" is substituted with "Name field"  ... and the word "field" is english language. I couldn't find another place to translate the word "field".

**Comment by jasonvarga** [comment]
Hah, yes its obvious now. Got it! Thanks.
