### ISSUE TITLE
FR: When collections are ordered by date, option to remove the time section in the CP

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1136]

**Comment by jasonvarga** [comment]
Where do you mean? In the listing?

**Comment by dannyuk1982** [comment]
I'm struggling to remember 2 months ago, haha. I think it was the mandatory 'date and time' under the slug. IIRC I was using a collection of events and they never needed a time (they had a start and end time - later on in the fieldset) so the addition time field was confusing the client, and I couldn't get rid of it

**Comment by jackmcdade** [comment]
This is possible now.
