### ISSUE TITLE
Can't use conditions on the `form:submission` tag

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1141]
In `ConditionFilterer` line 61 it expects the object to have a `getWithCascade` method. `Submission`s do not inherit from `Data` and do not have this method.

Consequence is that you can't use a condition on the `form:submission` tag and you get a undefined method error.

**Comment by aerni90** [comment]
The docs say, that you can use {{ form:submissions }} like the {{ collection }} tag. Conditions don't work though. https://docs.statamic.com/tags/form-submissions
