### ISSUE TITLE
Docs Typo

### ISSUE THREAD

**Issue by mariovass** [statamic/v2-hub#1143]
https://docs.statamic.com/forms
```<label>Level of Adoration</label>
  <select name="adoration">
    <value>Appreciation</value>
    <value>Fixation</value>
    <value>Obsession</value>
  </select>

should be
<label>Level of Adoration</label>
  <select name="adoration">
    <option>Appreciation</option>
    <option>Fixation</option>
    <option>Obsession</option>
  </select>

**Comment by jackmcdade** [comment]
Thanks! Fixed.

FYI you can send Pull Requests on the docs themselves, in case you wanted to. There's an Edit button on each page to get you to the right file.

![image](https://cloud.githubusercontent.com/assets/44739/21782518/b690cbc0-d681-11e6-93af-13bb4f0f311d.png)
