### ISSUE TITLE
Assets can't read from a container

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1144]
My file structure `/assets/resources/assets are here`

container.yaml for that container
```
path: assets/resources
url: assets/resources
driver: local
title: Resources
```

template
```	
{{ assets path="assets/resources" }}
    <img src="{{ url }}" />
{{ /assets }}
```

This gives, when `path` is set:
`FatalThrowableError in AssetsTags.php line 65: Call to a member function assets() on null`

That line 65 is
`$container = ($id) ? AssetContainer::find($id) : AssetContainer::wherePath($path);`

and for `wherePath`
```
/**
     * Get an asset container by path
     *
     * @param string $path
     * @return \Statamic\Contracts\Assets\AssetContainer
     */
    public static function wherePath($path)
    {
        // @todo
    }
```

If this could be expedited that would be much appreciated - need this to finish a site now, final page - which is a resources page, and needs to list all the assets in a container.

**Comment by dannyuk1982** [comment]
OK after much Slack'ing, we've (well, mainly kbadgley) worked out that you need to use `container` and not `path` - so probably just a case of the docs need updating than a bug?

**Comment by jackmcdade** [comment]
Ah yes, that would be it. Will all be addressed shortly.
