### ISSUE TITLE
Add modifier not working with variables into single antler, only double 

### ISSUE THREAD

**Issue by debone** [statamic/v2-hub#1148]
### Expected behaviour
```
{{ index add="{index}" }} 
```
It should work as a 2x multiplier ( I'm not doing, it's just a good easy example )

### Actual behaviour
The number in the variable doesn't get parsed with single antlers

This example with double antlers works
```
{{ index add="{{ index }}" }}
```

### Steps to reproduce
1.  Add any number variable to itself using single antler

### Server configuration
**Operating system**: MacOS

**Web server:** MAMP

**PHP version:** 5.6.25

**Statamic version:** 2.1.18

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:** None

**Comment by debone** [comment]
Actually, it works with index only... My use case is passing a number from a template to a partial, and this passed number don't work regardless using `number="2"` or `number=2`

**Comment by jackmcdade** [comment]
Can you show me what you’re trying to do? I’m pretty lost :(

**Comment by debone** [comment]
I wanted to use a number in the partial.

I have a template that calls a partial with a number:
```
{{ posts }}
  {{ partial:post desiredNumber="2" }}
{{ /posts }}
```

In the partial I want to use that number with some other number from the `{{ posts }}`

```
{{ postNumber add="{desiredNumber}" }}
```

And I couldn't make the add works regardless the way I inserted it. Though the "{index}" worked.

**Comment by jackmcdade** [comment]
Try `desired-number` or `desired_number`?

**Comment by jackmcdade** [comment]
Ah yeah so that's actually how it works. Single braces inside tag parameters, but if you want a var to parse inside a var... two braces. I think two braces work everywhere now, in fact. We'll update some docs.
