### ISSUE TITLE
Collection ordered by Title not alphabetical in CP

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/v2-hub#1149]
### Expected behaviour
Collection ordered by Title should be alphabetical

### Actual behaviour
Mostly alphabetical.

### Steps to reproduce
I wish I knew :(

**Statamic version: 2.1.18

![screen shot 2016-12-07 at 2 00 56 pm](https://cloud.githubusercontent.com/assets/622598/20988439/9e5a161c-bc85-11e6-9be3-9ef9d4559225.png)
![screen shot 2016-12-07 at 1 48 48 pm](https://cloud.githubusercontent.com/assets/622598/20988440/9e71a048-bc85-11e6-80d1-9fec069b8daa.png)
![screen shot 2016-12-07 at 1 33 45 pm](https://cloud.githubusercontent.com/assets/622598/20988441/9e771352-bc85-11e6-9efd-4ec3b9b4a6c0.png)

**Comment by jackmcdade** [comment]
Try learning your cache manually?

**Comment by sheldonkotyk** [comment]
many times. also happens on multiple computers and in different environments. staging/Linux and dev/OSX.

**Comment by sheldonkotyk** [comment]
Note that sorting by slug seems to order them correctly.

**Comment by sheldonkotyk** [comment]
Verified that it is not ordering by last modification timestamp using VueTools. Here's the view of the first out of order author.
![screen shot 2016-12-07 at 3 08 44 pm](https://cloud.githubusercontent.com/assets/622598/20990716/1ff96b92-bc8f-11e6-8319-e51bedbc4fde.png)

**Comment by jasonvarga** [comment]
Is this still happening in 2.5.1?

**Comment by sheldonkotyk** [comment]
Yes. slug seems to work but Title is still not sorting properly.

**Comment by jasonvarga** [comment]
Give this another shot in 2.5.2 and let us know. We tweaked the sorting, however I could never get titles to sort incorrectly to begin with.
