### ISSUE TITLE
nav:breadcrumbs are broken when using routes

### ISSUE THREAD

**Issue by mwesten** [statamic/v2-hub#1150]
### Expected behaviour
Display the breadcrums for the URL-parts that are actual pages.

### Actual behaviour
Breadcrumbs are shown for all URL-parts even if the pages don't exist (as in routing or vanity urls).

### Steps to reproduce
Install Statamic 2.1.18 (in my case on http://breadcrumbs.dev )
Add the following to /sites/themes/redwood/layouts/default.html

```
{{ nav:breadcrumbs }}
  {{ title }}&nbsp;-&nbsp;
{{ /nav:breadcrumbs }}
```
![added snippet](https://cloud.githubusercontent.com/assets/66753/21005852/ca15c934-bd36-11e6-8b02-844dd828cf97.png)

Now go to the following URLs:
`http://breadcrumbs.dev/about` This looks like it should
![about breadcrumb](https://cloud.githubusercontent.com/assets/66753/21005901/04ce6fe0-bd37-11e6-9c21-325f25603eb6.png)

`http://breadcrumbs.dev/blog` This looks like it should too
![blog breadcrumb](https://cloud.githubusercontent.com/assets/66753/21005923/1553b49c-bd37-11e6-97dd-41d69bc34815.png)

Now go to to `http://breadcrumbs.dev/blog/tags/harry-potter` 
![breadcrumb tag](https://cloud.githubusercontent.com/assets/66753/21005977/4631176c-bd37-11e6-84fa-325195c4da5f.png)

or `http://breadcrumbs.dev/blog/2015/07/22/fire-fire-looking-forward-to-hearing-from-you`
![breadcrumb blogpost](https://cloud.githubusercontent.com/assets/66753/21005958/34c71f94-bd37-11e6-9e3d-8be722b5efb7.png)

it shows `Home` for all routed paths that aren't actual pages

### Server configuration
**Operating system**: OSX 10.11.6

**Web server:** Apache 2.4.18

**PHP version:** 7.0.4

**Statamic version:** 2.1.18

**Updated from an older Statamic or fresh install:** Fresh Install

**List of installed addons:** none

**Comment by mwesten** [comment]
Hmmmm digging into it, it seems that code is there that should fix this (`/statamic/bundles/Nav/NavTags.php` line 128 and further).

![nav:breadcrumbs current](https://cloud.githubusercontent.com/assets/66753/21013401/3abf7ea0-bd5a-11e6-9d44-81227135d018.png)

Looking into it, the check that is done, tries to lookup the url and fetch the respective object containing data. The problem in the current situation is that the `$default_segment_uri` of the non-existent URL-parts are NULL values and fetching the Content of a NULL item returns an object, so all URL-parts are rendered as bredcrumbs.

Changing the code to this however checks if the `$default_segment_uri` `is_null()` and if it does, skips over it. This seems to do the trick !
![nav:breadcrumbs working](https://cloud.githubusercontent.com/assets/66753/21013572/ee66a03c-bd5a-11e6-96f8-b101fc1364eb.png)

**Comment by jasonvarga** [comment]
Thanks @mwesten !

**Comment by mwesten** [comment]
np ;) hope this works under all circumstances... just tested a couple of scenarios, but seems to hold up...
