### ISSUE TITLE
Widgets - width is not respected (with fix)

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1151]
Setting a width in widgets does nothing.

This can be fixed by, in `/statamic/resources/views/dashboard.blade.php`

Change line 25 to:
`<div class="widget" style="flex-basis: {!! $widget['width'] !!}%">`

And,  in `/statamic/resources/sass/components/dashboard.scss`

Change line 18 to:
`padding: 15px;`

**Comment by jackmcdade** [comment]
We removed that setting because it doesn’t work right in Safari.

**Comment by dannyuk1982** [comment]
Works fine for me

![screen shot 2016-12-08 at 14 19 36](https://cloud.githubusercontent.com/assets/7669885/21013276/5d3ce818-bd51-11e6-96c2-40037664bd52.png)

**Comment by jackmcdade** [comment]
Depends on the widget.

**Comment by dannyuk1982** [comment]
Fair enough, I am running the collection widget, updated, emd's powertools and a pages one I made - they all work fine. If there are any other widget types let me know what they are, I can test them?

**Comment by jackmcdade** [comment]
Was testing this again and once you inline the flex-basis, it becomes even harder to adjust them responsively. I'll revisit this with a different approach in the future.

**Comment by dannyuk1982** [comment]
They probably need the flex basis setting to auto on everything and then just using widths - I've been doing this more and more lately with flexbox
