### ISSUE TITLE
CP doesn't work with Internet Explorer

### ISSUE THREAD

**Issue by noendservers** [statamic/v2-hub#1152]
### Expected behaviour
Should be working as in other browsers (as far as it goes with IE). 

### Actual behaviour
When you login to CP (if you manage) the page is totally empty (except for the side menu). None of the views are rendered at all. In other words; it's impossible to update and work with the sites (if you are stuck with IE, as some of my clients are, pity them). 

I'm not the only one experiencing this problem I've been told in the wonderful world of Slack...

### Steps to reproduce
1.  Give your best to find a computer with Internet Explorer (I've tried with version 11.0.10 on Windows 10)
2.  Log in to CP on a Statamic site of your choice (I've tried on the latest release, 2.1.18)
3.  You see nothing on the right side of the menu

### Server configuration
Ubuntu
Nginx
PHP7

### Logs
Sometimes, not every time, I get some kind of error like:

> Object doesn't support property or method 'includes'

in cp.js

**Comment by rrelmy** [comment]
IE does not yet support the `includes` method on strings

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/includes

**Comment by jackmcdade** [comment]
We'll have a fix asap

**Comment by jasonvarga** [comment]
It's fixed in dev.

**Comment by jasonvarga** [comment]
(Stupid IE)

**Comment by sebszocinski** [comment]
Hey guys,

Just had a client email me about the CP not working properly (screenshots revealed IE)... I'm fine with not supporting IE or having fallbacks, but I think we should definitely show a message if they are using IE telling him it's not supported and the easy fix is to go download Google Chrome..?

Thoughts?
