### ISSUE TITLE
FR: Addons Pulled With Composer

### ISSUE THREAD

**Issue by warkior** [statamic/v2-hub#1155]
It would be very helpful to be able to pull in Addons using composer. This would allow developers to maintain central addon repositories on GitHub and pull changes or tagged versions as needed into the statamic based site using standard composer commands.

I have noticed that statamic already pulls the addons in to it's own core using a custom repository path with a composer structure like this:
```
    "repositories": [
        {
            "type": "path",
            "url": "../site/addons/*",
            "options": {
                "symlink": false
            }
        }
    ]
```

I also know it's possible to put in references to our own repos just generally in composer using this sort of structure:
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/name/project"
        }
    ],
    "require": {
        "name/project": "sample-tag"
    },
```

Can this be done in a way that avoids maintaining the addon code in the statamic site entirely, and just having it available as a composer dependency as listed above? Is this a feature that would be fairly easy to implement?

**Comment by jackmcdade** [comment]
This is likely how we'll do it in v3 👍
