### ISSUE TITLE
HTML document downloaded multiple times

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#1158]
### Actual behaviour
On a site I'm building the html document is loading multiple times (always six times). This doesn't have any visible impact on the site for users and the performance impact is minimal, but something's not quite right. 

### Steps to reproduce
1. Navigate to any page on the site
2. Open Dev Tools > Network tab
3. Empty cache & hard reload page
4. Page appears to fully load but the Network Tab continues to download the document five more times.

NB: Have tried the following to resolve:
- cleared cache, stache and static (via command line)
- turned on & off static page caching with caching type as `file`

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache

**PHP version:**
5.6

**Statamic version:**
2.1.18

**Updated from an older Statamic or fresh install:**
Fresh install

**List of installed addons:**
None

### Screenshot
![network-multiple-docs](https://cloud.githubusercontent.com/assets/3920126/21138666/fd313134-c126-11e6-8d89-b4277b4640b7.png)

**Comment by rrelmy** [comment]
Your favicon urls are empty, the browser tries to download them ;-)
```
<!-- Start partial: favicon.html -->
<link rel="icon" type="image/png" sizes="16x16" href="" />
<link rel="icon" type="image/png" sizes="32x32" href="" />
<link rel="icon" type="image/png" sizes="96x96" href="" />
<link rel="icon" type="image/png" sizes="128x128" href="" />
<link rel="icon" type="image/png" sizes="196x196" href="" />
<link rel="apple-touch-icon-precomposed" sizes="57x57" href="" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="" />
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="" />
<link rel="apple-touch-icon-precomposed" sizes="60x60" href="" />
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="" />
<link rel="apple-touch-icon-precomposed" sizes="76x76" href="" />
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="" />
```

**Comment by wesort** [comment]
Ahhh, thanks @rrelmy - I'll see if that fixes it.

**Comment by wesort** [comment]
Adding the asset sorted this out. Thanks again @rrelmy
