### ISSUE TITLE
Missing translation strings in CP

### ISSUE THREAD

**Issue by esonesson** [statamic/v2-hub#1161]
Hello, I found some missing translations in CP. Here's the list of what I could find. Thanks!

**General**
”Search For Anything…”

**Menu/Sidebar**
Menu name ”Tags”

**Dashboard Widget**
Title ”Recent Submissions”

**Pages**
”Show Urls”
The three dots on a page:
”Create Page Button”
”Mount Collection”
”Delete”
Collection pages:
”Add”
”Edit”

**Page Edit**
”Sneak Peek”
Save button:
”Save”
”Save And Continue”
”Edit Layout”

**Collections**
The three dots on a colleciton:
”Edit”

**Collections Entries**
”Search”
”Title”
”Slug”
The three dots on a entry:
”Edit”
”Delete”

**Collections Edit**
Save button:
”Save”
”Save And Continue”
”Edit Layout”
Asset Fieldset:
”Add Asset”
”or upload new file”
”Slug”
”Date And Time”
”Published”

**Tags**
”Search”
The three dots on a tag:
”Edit”
”Delete”

**Tags Edit**
”Sneak Peek”
Save button:
”Save”
”Save And Continue”
”Edit Layout”
”Slug”

**Assets**
Title ”Main Assets”
”Sync Assets”
”Upload Asset”
”Delete”
”New Folder”
”Upload Asset”
”Search”
List of assets:
”Title”
”Filename”
”Filesize”
”Date Modified”
Size of files ”x bytes” etc.
The three dots on a asset:
”Edit”
”Delete”

**Assets Edit**
Title ”Editing Asset”
”Filename”
”Close”
”Save”

**Globals**
Save button:
”Save”
”Save And Continue”
”Edit Layout”

**Content**
The three dots on a collection:
”Edit”
”Delete”

**Fieldsets**
The three dots on a fieldset:
”Edit”
”Delete”

**Fieldsets Edit**
Title ”Editing Fieldset:”
”Save”
”Title”
”Fieldset Title Instructions”
”Create Title”
”Fieldset Create Title Instructions”
”Hide”
”Fieldset Hide Instructions”
”Fieldset Fields Instructions”
”Handle”
”Label”
”Type”
”Select a field to add”

**Settings - Assets**
”Save”
”Save And Continue”
”Image Manipulation Route”
”Image Manipulation Secure”
”Auto Crop”
”Image Manipulation Driver”
”Image Manipulation Cached”
”Image Manipulation Cached Path”

**Settings - Caching**
”Save”
”Save And Continue”
”Stache” (Maybr not important because it’s a name?)
”Stache Always Update”
”Static Caching”
”Static Caching Enabled”
”Static Caching Length”
”Static Caching Type”
”Cache”
”File”
”Static Caching File Path”
”Static Caching Ignore Query Strings”

**Settings - CP**
”Save”
”Save And Continue”
”Start Page”
”Date Format”
”Widgets”

**Settings - Debug**
”Save”
”Save And Continue”
”Debug”
”Debug Bar”
”Loggers”

**Settings - Email**
”Save”
”Save And Continue”
”Section General”
”Driver”
”From Email”
”From Name”
”Section SMTP”
”Host”
”Port”
”Encryption”
”Username”
”Password”
”Section Mandrill”
”Mandrill Secret”
”Section Mailgun”
”Mailgun Secret”
”Mailgun Domain”

**Settings - Routes**
”Save”
”Save And Continue”
”Routes”
”Collections”
”Taxonomies”
”Redirect”
”Vanity”

**Settings - Search**
”Save”
”Save And Continue”
”Driver”
”Algolia Api Key”
”Algolia App Id”
”Algolia Searchable Attributes”
”Auto Index”
”Default Index”

**Settings - System**
”Save”
”Save And Continue”
”License Key”
Locales, title and all fields in the table
”Add Locale”
”Timezone”
”Date Format”
”Default Extension”
”Filesystems”
”App Key”
”Redactor”
”Name”
”Settings”
”Csrf Exclude”

**Settings - Theming**
”Save”
”Save And Continue”
”Themes”
”Templates”
”Default Layout”
”Default Page Template”
”Default Entry Template”
”Default Taxonomy Template”
”Error Template Folder”
”Fieldsets”
”Default Fieldset”
”Default Page Fieldset”
”Default Entry Fieldset”
”Default Term Fieldset”
”Default Asset Fieldset”
”Misc”
”Smartypants”
”Allow Php”

**Settings - Users**
”Save”
”Save And Continue”
”Login Type”
”New User Roles”

**Users**
”Search”
Columns:
”Name”
”Username”
”Email”
The three dots on a user:
”Edit”
”Delete”

**User Edit**
”User Options”
”Send Password Reset Email”
”Copy Password Reset Link”
”Save”
”Save And Continue”
”Edit Layout”
”Username”
”Roles”
”Email address”
”First name”
”Last Name”
”Biography”

**User Groups / Roles**
”Search”
”Title”
Create Group:
Lists of users ”Filter” and ”Selected”

**Statamic version:**
2.1.18

**Updated from an older Statamic or fresh install:**
Tested on updated and fresh install

**Comment by SuperKiwi** [comment]
#1068 
Have a look at this referenced issue

**Comment by ebeauchamps** [comment]
With 2.1.17 I had the same problem. But it is solved with 2.1.18.

**Comment by danieljwestman** [comment]
Solved what? The strings are not translated..

**Comment by ebeauchamps** [comment]
What locale are you using and have you checked you translated all the strings?

Then,  did you put locale: xx (xx being your locale shortcode) in your user yaml file (the one who is accessing the CP) ?

**Comment by ebeauchamps** [comment]
My 2.1.18 CP is 100% translated

**Comment by peda** [comment]
It definitely got better in 2.1.18 but one string which definitely isn't translate is the "cp.locales" above the locale dropdown.

**Comment by peda** [comment]
Page title isn't translated either "cp.nav_pages"

**Comment by ebeauchamps** [comment]
`'nav_pages' => 'Pages'` in French, so I guess I could not see it isn't translated....

**Comment by peda** [comment]
@ebeauchamps It's not workng for me (see screenshot below)

maybe you can reproduce it with the following steps
- set the locale in `index.php` to `$locale = 'de';`
- copy the entire folder `statamic/resources/lang/en` and rename it to `de`
- set the CP locale in either `cp.yaml` or in the users yaml to `de`

![statamic1](https://cloud.githubusercontent.com/assets/559490/21366707/3dea0992-c6fb-11e6-9214-88448832a0e8.png)

**Comment by ebeauchamps** [comment]
The language folder must be located in `site/lang/`

**Comment by peda** [comment]
@ebeauchamps just tried it with `de` folder in `site/lang/` but I'm still facing the same issue

**Comment by ebeauchamps** [comment]
The only difference in my setup (compared to yours) is that I still have `$locale: en` in `index.php` 
I had some exchanges with the Gentlemen about something...

**Comment by peda** [comment]
Maybe you can give it a try with `$locale` set to `de` in `index.php` ?

**Comment by ebeauchamps** [comment]
testing a few setups right now ;-)

**Comment by ebeauchamps** [comment]
OK found it: in `system.yaml`, under `locales:` you should only have 
```
locales:  
  de:
    full: de_DE
    name: Deutsch
    url: http://statamic2.dev/
```
 If you still have `en` with `de` there is a "multiple redirect" error when accessing the CP

**Comment by ebeauchamps** [comment]
my setup:
in index.php $locale is set to de
in system.yaml, there only is a reference to the de locale
in my user yaml file, I put locale: de

**Comment by peda** [comment]
I'm not sure if I fully understand what you are trying to say - that's what my `locales:` block inside `system.yaml` looks like:

```
locales:
  de:
    full: de_DE
    name: German
    url: http://localhost.dev/
  en:
    full: en_US
    name: English
    url: http://en.localhost.dev/
```

**Comment by ebeauchamps** [comment]
You have to get ride of en: and what is below.

**Comment by peda** [comment]
But what if I want it to be multi-language with German as primary locale?

`en.localhost.dev` is a separate VirtualHost in my Apache pointing to `/en` folder - this folder does contain `index.php` with `$locale` set to `en`, a copy of `.htaccess` and a symlink to `../site` and another one to `../assets` as per the Statamic documentation. The symlink to `../assets` is not mentioned in the documentation put it's required if you use `{{ url }}` of an asset

**Comment by peda** [comment]
I anyway tried your suggestion of removing the entire `en:` block from `system.yaml` and while this fixes the `cp.nav_pages` in the header it's still showing me `cp.locales` in the sidebar

**Comment by ebeauchamps** [comment]
In my opinion, and given my experience, If you change the default locale in index.php, the only way to access the CP is to get ride of "english" in system.yaml

My experience only is with keeping "en" as the default locale in index.php and with that I can have and English site and a French one and I can give access to the CP in either language.

Therefore I cannot answer properly your situation, sorry about that.

But I can confirm indeed that `cp_locales` is showing in the sidebar using the setup I tested above, although everything is OK with my usual French setup...and I don't know why, sadly.

**Comment by peda** [comment]
Thanks four your help.

For me it's a quite common usecase that all pages do exist in `de` locale and that for some (sometimes only a few, sometimes most of them) do exist in `en` or other locales as well. In this particular case I'd like to have `de` as the primary locale.

**Comment by ebeauchamps** [comment]
Following up on this:
Can't you stay with the default statamic locale being English AND the base URL of your site being in German?
i.e. http://statamic.dev/ providing the default German site
http://en.statamic.dev/ providing the English version

Or do we have to conclude that the current version of the cms doesn't work well in multi-locale environments where the English locale isn't the default locale?

**Comment by danieljwestman** [comment]
The CP still can't handle other languages then EN as default locale...

**Comment by thomasgerard** [comment]
Hi, I think there are quick easy fixes to do in /statamic/core/Translation/Translator.php
I saw the all() method is what is used to collect all translations and print them in the templates as a javascript object (Statamic.translations).
But in line
`$this->getTranslations(base_path() . '/resources/lang/en'),`
'en' shouldn't be hardcoded but take the locale as variable
Then in line
`$this->getTranslations(site_path() . '/lang/' . $this->locale())`
$this->locale() actually returns 'en' even if another locale is active.
Finally, the getTranslations() method returns translations with keys like 'locale.cp', 'locale.fields', 'locale.markdown' ... but the javascript translate() function searches for 'en.cp', 'en.fields', 'en.markdown' so it seems there's something hardcoded on that side also.

I used this quick super dirty fix for now for the all() method (for french)
`public function all()
    {
		$translations = collect(array_replace_recursive(
			$this->getTranslations(base_path() . '/resources/lang/fr'),
			$this->getTranslations(site_path() . 'lang/fr')
		))->merge($this->getAddonTranslations());
		foreach($translations as $key => $value) {
			$translations['en'.substr($key, 2)] = $translations[$key];
		}
        return $translations;
    }`

**Comment by danieljwestman** [comment]
I came up a similar solution. Please fix this "simple" bug, it's a huge issue with many corresponding issue tickets here on the hub..

**Comment by ebeauchamps** [comment]
@jaggy Did you see the above message from @thomasgerard ?

**Comment by jaggy** [comment]
Hey @ebeauchamps, @thomasgerard, this will be fixed in the next release. 

I got to see the implementation of other's and got to narrow down the issue most of the people are having both in using the front end translations and in the backend.

**Comment by ebeauchamps** [comment]
Crossing fingers

**Comment by danieljwestman** [comment]
+1 !
