### ISSUE TITLE
CP ignores locale set in cp.yaml

### ISSUE THREAD

**Issue by peda** [statamic/v2-hub#1162]
### Expected behaviour
When primary language is changed to German (DE) and the cp.yaml has locale: en then the CP is expected to be in English

### Actual behaviour
The setting in cp.yaml is ignored and it still tries to load German strings (which obviously fails) and results in the placeholders being displayed

### Steps to reproduce
/index.php changed `$locale = 'de';` for the page to be in German
/statamic/site/settings added `locale: en` for the CP to be in English

### Server configuration
**Statamic version:** 2.1.18

**Updated from an older Statamic or fresh install:** fresh install

**Comment by mwesten** [comment]
Same here....

**Comment by peda** [comment]
At the moment it's working for me ... don't know why ? Looks like this bug does only occur under special circumstances

**Comment by ebeauchamps** [comment]
Question: did you put `locale: en` in your user yaml file (for the user who has access to the cp)?

**Comment by peda** [comment]
When I had this issue there was no locale defined in the users yaml file.

I just did the following steps to reproduce it

- fresh install of Statamic with just one locale which is set to `de`
- changed `$locale` to `de` in `index.php`
- added `locale: en` as a first line inside `cp.yaml`
- logged into the CP (see screenshot below)

![statamic2](https://cloud.githubusercontent.com/assets/559490/21367348/20f9795a-c6fe-11e6-9c54-033f86bb650b.png)

**Comment by ebeauchamps** [comment]
Interestingly enough:
-  fresh install of Statamic 2.1.19 with just one locale which is set to `fr` (default `en`locale is deleted during the setup)
-  changed $locale to `fr` in index.php
-  put the `fr` folder in `site/lang`
-  logged into the CP

=> The CP isn't fully translated (i.e. Search For Anything...at the top)
=> If I add `locale: fr` as a first line inside cp.yaml: the CP isn't fully translated either (which is consistant with @peda's message above)

The ONLY way for me to get a fully translated CP is to stick with `$locale: en` in index.php AND to declare the French locale either at the user level or in the cp.yaml setting.

Hope it can help.
