### ISSUE TITLE
Can't modify asset fieldset when changing primary locale

### ISSUE THREAD

**Issue by peda** [statamic/v2-hub#1163]
### Expected behaviour
When primary language is changed to German (DE) (/index.php changed $locale to 'de') I do expect to still be able to edit asset fields

### Actual behaviour
No fields are displayed in the asset edit screen

### Steps to reproduce
/index.php changed `$locale = 'de';` for the page to be in German

### Server configuration
**Statamic version:** 2.1.18

**Updated from an older Statamic or fresh install:** fresh install

asset-editor.template.html has locale="en"  hardcoded
`                <publish-fields :fieldset-name="asset.fieldset"
                                :uuid="asset.uuid"
                                locale="en"
                                :field-data="fields"
                                :focus="true">
                </publish-fields>`

**Comment by danieljwestman** [comment]
Aha thats why it's not working for me (sv, Swedish)!

Please fix, thx

**Comment by peimn** [comment]
That's the long awaited issue that many noticed, and we hope it will be fixed in 2.2 ...

**Comment by jasonvarga** [comment]
Ah yes you're absolutely right, sorry about that. Assets aren't localizable, however it should use your default locale, not English :) We will fix it.

**Comment by jasonvarga** [comment]
Fixed for 2.2

**Comment by ebeauchamps** [comment]
As I previously said, localized assets should be a thing in a future version (Feature Request then). Think of a product packaging.

**Comment by peda** [comment]
@ebeauchamps localizing assets would be a great thing especially for SEO purposes in the meanwhile I've to use workaround for that
