### ISSUE TITLE
FR: Resolve Addon Command Dependencies from Service Container

### ISSUE THREAD

**Issue by JohnathonKoster** [statamic/v2-hub#1168]
### Expected behaviour

When constructing addon commands like so:

```php
<?php

namespace SomeNamespace;

use Statamic\Extend\Command;

class SomeCommand extends Command
{

    public function __construct(SomeDependency $dep)
    {
            // Do something with resolved dependency.
    }

}

```

It would be nice to have Statamic's console kernel resolve the dependencies from the underlying service container.

### Actual behaviour

No dependencies are automatically resolved. Type errors are thrown.

### Steps to reproduce
1.  Create any command class that requires a dependency to be supplied through its constructor.
2.  Call the command.
3.  Witness exceptions.

**Comment by rrelmy** [comment]
The `handle` method inside the command class does resolve dependencies like you would expect ;-)
At least in statamic 2.6
