### ISSUE TITLE
Issue with Path on Windows

### ISSUE THREAD

**Issue by kobadg** [statamic/v2-hub#1170]
### Expected behaviour
When trying to use the getDirectory() function from the Extensible Class (In Addon), path returns correctly with path to addon directory.

### Actual behaviour
When trying to use the getDirectory() function from the Extensible Class (In Addon), path returns "".

### Steps to reproduce
1.  Be on Windows
2.  create use of getDirectory() function
3.  use dd() to output with results being ""

### Server configuration
**Operating system**: Windows 10

**Web server:** Apache

**PHP version:** 7.0.0

**Statamic version:** Latest

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** CPTheme - Creating

### Fix
Change all hardcoded "/" to DIRECTORY_SEPARATOR in Path.php file (And possibly other files that have this same sort of setup?) - Example of fix.

```public static function popLastSegment($path)
    {
        $parts = explode(DIRECTORY_SEPARATOR, $path);
        array_pop($parts);

        return implode(DIRECTORY_SEPARATOR, $parts);
    }```

**Comment by edalzell** [comment]
There are other methods in there that have the same issue:
`replaceSlug`, `folder`, `hidden` maybe, `isDraft`

**Comment by jackmcdade** [comment]
All sorted for next release.
