### ISSUE TITLE
Can't use Dossier as a mixin

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1172]
I'm creating an addon and I wanted to use the Dossier components instead of rolling my own to maintain the same look and behaviour users would expect.

However, when I tried to import Dossier.vue, I got a `babel-loader` error because it couldn't find the `node_modules`. It was trying to look in the `statamic` directory instead of my addon dir.

I ended up just copying the dossier directory into my addon, but that doesn't feel like the right solution as I'd prefer to just reference it.

**Comment by jackmcdade** [comment]
Won't be supporting this at this time.
