### ISSUE TITLE
Use blade files as layouts

### ISSUE THREAD

**Issue by andreportaro** [statamic/v2-hub#1179]
Hi!
It would be great if we could use Blade all the way from the layouts.

The reason for that is that it would be insanely easier to bring projects that were already running on laravel using strictly blade templates inside Statamic.

Also, maybe as Stamic offers both template and include parsing with blade and Antlers, why shouldnt it work with layouts?

Looking for the code on the backend, I see the Antlers Engine looks always for a html file:

```
-- Statamic\View\Antlers\Engine
    /**
     * Gets the raw contents of the layout
     *
     * @return string
     * @throws \Illuminate\Contracts\Filesystem\FileNotFoundException
     */
    private function loadLayout()
    {
        foreach (Helper::ensureArray($this->data['layout']) as $layout) {
            $layout_path = "layouts/{$layout}.html";

            if (File::disk('theme')->exists($layout_path)) {
                return File::disk('theme')->get($layout_path);
            }
        }

        // If there's no layout file available, we're not going to be getting very far. Let's
        // throw an exception here to kill the request. It doesn't make sense to continue.
        throw new FileNotFoundException("Layout [{$this->data['layout']}] doesn't exist.");
    }

```
and my guess is that antlers engine is **always** used to load layouts.

Thank you very much :)

**Comment by jackmcdade** [comment]
Will look into it! It’s a totally reasonable request.
