### ISSUE TITLE
Redwood Theme Missing Hamburger Icon?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#1180]
(Copy/Pasted from Slack:) Just noticed a teensy :bug:  in the default v2 install (2.1.18): below width of 768px the Redwood theme menu bar disappears (OK), but AFAICT there's no :hamburger: or other icon suggesting "click me"—although there's a place for it, and you can rollover and click the spot and get the dropdown.

**Comment by jackmcdade** [comment]
Good catch. The icon is white, and therefore invisible for all intents and purposes.
