### ISSUE TITLE
Form submission file url issue

### ISSUE THREAD

**Issue by mariovass** [statamic/v2-hub#1183]
Statamic 2.1.19

File is submitted with the "fancy" method from the docs. Full a ref url is shown in the cp submission and when you click into the submission it shows the ID which is not a link to open.

![image](https://cloud.githubusercontent.com/assets/3165071/21986867/de622814-dc09-11e6-911d-97607a832dc9.png)

this work fine in 2.1.18

**Comment by jackmcdade** [comment]
I guess we get to pick whether we want HTML or XSS.
