### ISSUE TITLE
CP locale is hardcoded inside the javascript translator 🇨🇭 

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1186]
### Expected behaviour
The JavaScript translator in the CP should respect the current locale and translate non english languages correctly

### Actual behaviour
The JavaScript translator always uses english because the current locale is never set.

The translations are prefixed with the correct locale (Inside `Statamic.translations`) but the method `Lang.setLocale` is never used to set the correct locale.

A good place to see that is the `cp.add_row` button on grids.

### Steps to reproduce
1.  Change CP language to `de` (or any other language)
2.  Create a translation directory for it (copy the original en version)
3.  use `translate('cp.addons_empty')` inside your JS console

Be aware that there is a fallback when no message is found the key is _titleized_ (add_row => Add row)

### Server configuration
**Statamic version:** 2.1.19

**Comment by rrelmy** [comment]
Related: #1162

**Comment by peda** [comment]
I didn't debug it, but I do have the same issue with `cp.add_row` on grid fields (my setup is very similar)

Most of #1162 has been fixed in 2.1.19 but it seems like there is still some work to do.

**Comment by ebeauchamps** [comment]
ah, getting close!

**Comment by peimn** [comment]
#585 #issuecomment-209625019

**Comment by jaggy** [comment]
We've rewritten how translations on the front end work so all the translations won't be all bottled up in the `en` prefix.

The translations on the front end should look like this when this gets out. http://d.pr/i/I9nI

**Comment by jaggy** [comment]
@reelmy do you mind if You send me a zip of your project so I can see what's up?

jaggy@statamic.com

**Comment by rrelmy** [comment]
@jaggy Just sent you a mail

**Comment by jaggy** [comment]
Just got it. I'll let you know what I find.

**Comment by jaggy** [comment]
Hey @rrelmy, thanks for the archive. Narrowed down the issue some of the people here are having. 👍
