### ISSUE TITLE
Adding an already uploaded asset to a page

### ISSUE THREAD

**Issue by JayVerb** [statamic/v2-hub#1192]
### Expected behaviour
When adding/editing a page, I select the "Add Asset" which is set in the fieldset. I expect to see a list of thumbnails for images already uploaded.

### Actual behaviour
Files have already been uploaded and display on the Assets page, but the modal when selecting "Add Asset" is clicked, the modal only shows a blank directory.

### Steps to reproduce
1.  Any fieldset with an "Assets" field.
2.  Select the "Container" and choose a sub folder
3.  Looks like it happens no matter how the "Restrict to Folder" is set
4. Go to a page with that fieldset and select the "Add Asset" button
5. sub folders don't even show

### Server configuration
**Operating system:**
Mac OS X 10.12.2

**Web server:**
Apache

**PHP version:**
7.0.2

**Statamic version:**
2.5.0

**Updated from an older Statamic or fresh install:**
Updated from previous latest version

**List of installed addons:**
Null

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Add those logs here
```

**Comment by jasonvarga** [comment]
Do you see the assets at all when you go to "Assets" in the CP sidebar?

**Comment by JayVerb** [comment]
Yes, the assets are there when I go to "Assets"

**Comment by jasonvarga** [comment]
Can you record a quick video of the behavior?

**Comment by sheldonkotyk** [comment]
I'm experiencing this as well.

**Comment by sheldonkotyk** [comment]
I also can't upload an asset in that modal.

**Comment by JayVerb** [comment]
I can't at the moment, but will try to get you a video today.

**Comment by jasonvarga** [comment]
It's a Safari CSS issue. ~Hooray!~

Don't worry about the video @JayVerb

**Comment by JayVerb** [comment]
Awesome, thank you!
