### ISSUE TITLE
Display bug in "Published" toggle switch

### ISSUE THREAD

**Issue by bcartier** [statamic/v2-hub#1193]
### Expected behaviour
I expected that clicking on a toggle switch in the CP would toggle visually between 2 states. 

### Actual behaviour
toggle switch does not change in appearance on click or clack-and-drag.

### Steps to reproduce
1.  Edit any of the default pages
2. Notice the published switch should be active, but displays as inactive
3. Clicking on the switch doesn't change the appearance of the component, but actually does toggle (editing a published page, then clicking once on the toggle, and saving the page sets the page to unpublished)

I tried on Chrome, Firefox and Safari - same issue.

### Server configuration
**Operating system**:  macOS

**Web server:**  MAMP

**PHP version:**  7.1

**Statamic version:** 2.5

**Updated from an older Statamic or fresh install:** Fresh Install - no changes aside from creating a user

**List of installed addons:** None

**Comment by bcartier** [comment]
I looked at other areas of the CP with toggle fields. The toggle appear to be fine under Settings->Cache,  but have the same display bug in other areas like Fieldsets > About : The "Hide" toggle.

**Comment by jasonvarga** [comment]
Yep its fixed for 2.5.1

**Comment by bcartier** [comment]
Great! Thanks Jason.
