### ISSUE TITLE
Taxonomy 'terms' don't support alias

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1194]
### Expected behaviour
`{{ tags as="foo" }}` should work

### Actual behaviour
Parser error

### Steps to reproduce
1.  `{{ tags as="foo" }}` in a template

### Server configuration

**Statamic version:**
2.5

**Comment by jackmcdade** [comment]
Aliasing isn't support on the var level, just the Tag level. It's as if you were aliasing any array var here.

**Comment by edalzell** [comment]
issue is @jackmcdade that `tags` is a replacement for `relate` so I expected the same behaviour.

Perhaps a docs issue then?

**Comment by jasonvarga** [comment]
We can make it clearer or work out something else, for sure.

In the mean time, you're still able to use the relate tag just like before.
