### ISSUE TITLE
Date based sorting of entries seems broken

### ISSUE THREAD

**Issue by warkior** [statamic/v2-hub#1201]
### Expected behaviour
Date sorted entries should appear in the proper order by date.

### Actual behaviour
They don't. 
http://s.warkior.com/sorting_1E3BECAB.png

### Steps to reproduce
1.  Have several pages of date based entries in a collection
2.  View the collection in the CP
3.  Attempt to sort by date

**Comment by humanjpg** [comment]
I'm experiencing the same issue. Appears to be manifesting itself in the frontend too. So taxonomies ordered by `sort="order"` appear in a strange order. 

I fixed that using `sort="date:desc"`, but thought it may give some clues as to what lies beneath as the order matched the new order in the CP.

**Comment by jackmcdade** [comment]
I can't recreate this. Any tips?

![screen shot 2017-02-01 at 11 01 16 am](https://cloud.githubusercontent.com/assets/44739/22514724/3f5ded90-e86e-11e6-840b-b019370f9444.png)

**Comment by jackmcdade** [comment]
Spoke too soon. I missed the part about entries are across multiple pages.

**Comment by humanjpg** [comment]
This is how my markdown content files are prefixed:

<img width="108" alt="dates" src="https://cloud.githubusercontent.com/assets/9616783/22514913/c2b83d56-e898-11e6-8244-72bf65e70a8a.png">

**Comment by jasonvarga** [comment]
I believe this is sorted in 2.5.2 (releasing shortly) let us know if that's not the case.
