### ISSUE TITLE
Update from 2.1.19 to 2.5.1: missing translation within the CP

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#1202]
### Expected behaviour

b.  new button labels introduced by 2.5.1 are translatable

### Actual behaviour

b1.  On the Main Assets page, there are 2 new buttons
-  `New Folder` can be found in the `cp.php` file so it can be translated (OK with my French translation)
- `Upload` cannot be found and therefore this word stays in English
  
In `cp.php`:
```
'new_folder' => 'New Folder',
 'uploads' => 'Upload|Uploads',
```
The Upload button should probably use this key, but is it?
  
b2.  There is a new `Move` button showing when selecting an asset, but there isn't any key for Move in the `cp.php` file, therefore it cannot be translated. (`Uncheck All` has been added so it's OK for this one)
  
b3.  Editing an asset shows that various buttons are not translated. This is not critical, but I can provide you with the culprits if needed
  
### Steps to reproduce
Update a site that uses the French folder in site/lang/ with a user whose default locale is set to fr

**Comment by jaggy** [comment]
Which page is the untranslated `Upload` in? Thanks!

**Comment by ebeauchamps** [comment]
http://mysite.red/cp/assets/browse/380dc8d9-481c-4d18-9162-ecd5688f98a8/  (button on the top right)
=> the page that shows when clicking on "Assets" in the sidebar

http://mysite.red/cp/assets/browse/380dc8d9-481c-4d18-9162-ecd5688f98a8/img (button on the top right)
=> the page that shows when clicking on a container on the previous page

http://mysite.red/cp/collections/entries/blog/create  (button to add an image, within the fieldset)

**Comment by danieljwestman** [comment]
+1

And Globals save notification in CP aren't translatable either. In swedisn it says "Global sparad" (the word "Global" should be translated).

**Comment by jackmcdade** [comment]
These should all be translatable now.

**Comment by danieljwestman** [comment]
When, in the next release? In 2.5.5 they aren't..

**Comment by jackmcdade** [comment]
They are for me. Are you sure?
