### ISSUE TITLE
2.5.1: Hide/Show setting for fieldset uncaught?

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#1203]
### Expected behaviour
The hide/show setting saved for a fieldset is caught and the fieldset select dropdown that appears when creating a new collection only displays fieldsets with `hide: false`

### Actual behaviour
All fieldsets are always displayed

### Steps to reproduce
base install of statamic 2.5.1. Create a new collection. The "About" fieldset is displayed in the dropdown (as are "Default Globals", "Things", "Blog Post", "User") though only the "Gallery" fieldset hasn't `hide: true` in its settings.

**Comment by jackmcdade** [comment]
Ah I see. That setting was originally intended for the Add Page feature, since it was the only place we listed fieldsets. Right now you can set `hidden: false` on the fieldtype to hide em, but I'll switch this default for next patch. 👍

**Comment by ebeauchamps** [comment]
Solved with 2.5.2
