### ISSUE TITLE
Our site is down. with an error "Collection [capabilites] doesn't exist": The capabilities collection is there in the file system.  I have rebooted the server and restarted the web and php service multiple times with no luck. We made no changes to the system, no upgrades. We are still running on 2.1.8

### ISSUE THREAD

**Issue by ToddGregory** [statamic/v2-hub#1204]
### Expected behaviour
Tell us what you assumed would happen, as optimistically as possible.  
If it's just "it should work", you can remove this section.

### Actual behaviour
Tell us what happened instead

### Steps to reproduce
1.  
2.  
3.  

### Server configuration
**Operating system**:

**Web server:**

**PHP version:**

**Statamic version:**

**Updated from an older Statamic or fresh install:**

**List of installed addons:**

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Add those logs here
```

**Comment by jackmcdade** [comment]
Hey there, for the quickest, best support, requests like this should be on <https://statamic.com/support>. This is the public bug forum and isn't necessarily tied to email triggers or urgency.

That being said, I obviously still want to try to help. Can you try clearing your cache? Restarting PHP wouldn't have any helpful effect I can think of. Run `php please cache:clear` or delete the contents of the `/local` directory. If those don't help, please open a support request. For Urgent, use the "sky is falling" option.

**Comment by sheldonkotyk** [comment]
Had this happen to me the other day. Clearing cache helped. 2.1.18 as well. Haven't had it happen with 2.5.1 yet.
