### ISSUE TITLE
assets with spaces in filename fail in 2.5+

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/v2-hub#1205]
### Expected behaviour
Spaces in filename should be replaced with %20 as in 2.1.19

**Statamic version:**
2.5.1

**Updated from an older Statamic or fresh install:**
updated from 2.1.19

**Comment by sheldonkotyk** [comment]
also, it seems to have broken my assets area in the CP and assets modal.

Note sure if it is just a bad upgrade or not.

**Comment by jackmcdade** [comment]
We wouldn't ever actually replace the spaces with `%20` permanently, just encode them when they need to be. I did find (and fix) an issue with the Focal Point Editor not working with spaces, but can't find any other areas with issues.

When you say "it seems to have broken my assets area in the CP and asses modal", what do you mean specifically? What's broken?

**Comment by sheldonkotyk** [comment]
Going to the assets index page or opening the modal just brings up an eternal loading spinner.

I just did some more testing and it seems to be the 2.5.1 update that is causing it. 2.5.0 upgrade alone worked but adding the 2.5.1 upgrade after breaks it.

**Comment by jackmcdade** [comment]
Do you get any errors? The AJAX requests should say something.

**Comment by sheldonkotyk** [comment]
oh. tried again and 2.5.0 didn't work. Must have been cached or something.

![screen shot 2017-02-01 at 9 53 52 am](https://cloud.githubusercontent.com/assets/622598/22519198/6219f48c-e864-11e6-80d3-66b95e473e3f.png)

**Comment by jackmcdade** [comment]
CSS FTW!

`background: url('your url')` and `background: url(your url)` were not made equal.

**Comment by sheldonkotyk** [comment]
The other issue here was the CP was broken due to the index.php "resources" change I think? Anyone else with that issue may have a problem.

**Comment by jeffmckeand** [comment]
Not sure this is completely fixed. I'm running into the same issue on 2.5.2 when loading the edit modal for an S3 asset that has spaces in the filename.

**Comment by sheldonkotyk** [comment]
Ya me too.

**Comment by jackmcdade** [comment]
Are you sure it's the spaces that's the problem?

**Comment by sheldonkotyk** [comment]
Nope. Not sure.

**Comment by jeffmckeand** [comment]
Assets with no spaces in the filename work just fine, so I'm assuming it is.

**Comment by jackmcdade** [comment]
What's not working for you?

**Comment by jeffmckeand** [comment]
I can easily browse a list of images in an S3 container; all of the thumbnails load just fine. But when I go to **_edit_** an image with spaces in the filename, I get an endless spinner and a 500 error.
Attempting to directly load the asset in the browser (e.g. nbcc.dev/cp/assets/s3/lessons/Mosaic/Square%20Share%20500x500.jpg) yields this error:
```
ErrorException in DimensionBuilder.php line 110:
getimagesize(https://s3.amazonaws.com/nbccweb/lessons/Mosaic/Square Share 500x500.jpg): failed to open stream: HTTP request failed! HTTP/1.1 505 HTTP Version not supported
```

No such error on files where the name doesn't contain spaces. The modal loads just fine.

**Comment by lardnicus** [comment]
Client keeps breaking the cp by uploading complete garbage... I like that the 2.5+ now catches corrupt images, but for some reason after I leave them alone with it they eventually upload something which breaks it

http://thesite.com/cp/assets/browseFailed to load resource: the server responded with a status of 500 (Internal Server Error)
