### ISSUE TITLE
Control panel issues when page slug match file extension on macOS

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1208]
If you give a page a slug that matches a file extension, and that page has child pages, the control panel is:

1. unable to reorder pages: causes a 500 error in console and the "saving" state never goes away
2. change the slug of that page: a new folder with an `index.md` but the existing folder is left in place with all the child pages

My use case is having a page with a slug of `help` and then sub pages under that page. On macOS the OS sees this as a "Help bundle".

After trying to load a page after the save fails, i get the error in the attached screen shot.
![screen shot 2017-01-30 at 14 30 18](https://cloud.githubusercontent.com/assets/16148258/22427828/901ce600-e6fc-11e6-80b1-169277af867e.png)
Toggling debug from true to false in the settings allows pages to load again.

### Server configuration
**Operating system**:
macOS 10.11.6

**Web server:**
Valet

**PHP version:**
7

**Statamic version:**
2.5.1

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**
None

**Comment by jackmcdade** [comment]
Luke, I'm unable to recreate this. A made a quick video to show you what i did, let me know if there are any missing steps! <http://d.pr/v/Czw1>
