### ISSUE TITLE
After save, collection disappears in CP

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/v2-hub#1211]
### Expected behaviour
After saving, it should redirect me to the collection index.

### Actual behaviour
Took me to the collections page when there are no entries in the collection.

### Steps to reproduce
1.  Add/edit articles (seems to be 5-10 before it happens)

### Server configuration
**Operating system**: 
Ubuntu

**Web server:**
Nginx

**PHP version:**
7.0

**Statamic version:**
2.5.1

**Updated from an older Statamic or fresh install:**
updated from 2.19 -> 2.50 -> 2.5.1

![image002](https://cloud.githubusercontent.com/assets/622598/22449812/41bd2a68-e717-11e6-8a1a-919f3b71d4f0.jpg)

**Comment by sheldonkotyk** [comment]
This isn't new to 2.5.1

**Comment by jackmcdade** [comment]
What else can you say about the site? This issue seems pretty specific to your site (and probably stemming from a similar/same cause based on your other open Issues).

**Comment by sheldonkotyk** [comment]
I've had it happen on multiple sites of various sizes but it starts after 100 or so entries in a collection. Usually when multiple editors are working in it but even when it was just me. I believe it is probably that race condition as it will occasionally happen when double clicking the save button. Requires clearing the cache to revive.

**Comment by jasonvarga** [comment]
I believe #1212 is the same thing and contains more info, so I'm closing this one.

**Comment by sheldonkotyk** [comment]
It may be the same but they present differently. I'm hoping if the underlying condition is fixed that everything will be hunky dory.
