### ISSUE TITLE
Forms files cause error on cp in v 2.5.2

### ISSUE THREAD

**Issue by mariovass** [statamic/v2-hub#1214]
When click into a form to view submissions i get a form error.

![image](https://cloud.githubusercontent.com/assets/3165071/22458362/d7268dfa-e7a4-11e6-84c0-d03d049a7e6c.png)

[statamic-2017-01-31.txt](https://github.com/statamic/v2-hub/files/741470/statamic-2017-01-31.txt)

**Comment by colinmeinke** [comment]
For context, this was after running the upgrader to 2.5. Before that viewing these forms worked fine. The forms that throw this error seem to all have file fields in common.

**Comment by jaggy** [comment]
Could you try running `php please clear:cache` and `php please clear:stache` and see if that fixes it?

**Comment by mariovass** [comment]
@jackmcdade what more info would you like?

**Comment by jackmcdade** [comment]
What's some of the data in the submissions? I'm pretty sure any display issues would be because of a datatype we didn't expect

**Comment by mariovass** [comment]
@jackmcdade it is all forms with files.

Here is one form with 5 responses these are the file types and this is the formset settings.
```title: HPP
fields:
  name:
    display: Name
    validate: required
  email:
    display: Email
    validate: required|email
  phone:
    display: Phone
  company:
    display: Company
  lead_page:
    display: Lead Page
  existing_account:
    display: Existing Account
  merchant_id:
    display: Merchant ID
  dba:
    display: DBA
    validate: required
  looking_for:
    display: Looking For
    validate: required
  logo:
    display: Logo
    validate: required|mimes:gif,jpeg,jpg,png
    type: asset
    container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
    folder: partner-logos
columns:
  - name
  - email
  - phone
  - company
  - merchant_id
  - existing_account
  - dba
  - looking_for
  - logo
email:
  - 
    to: marketing@cardconnect.com
    from: marketing@cardconnect.com
    subject: HPP form submitted
    template: hpp
  - 
    to: cardpointesupport@cardconnect.com
    from: marketing@cardconnect.com
    subject: HPP form submitted
    template: hpp
```
![image](https://cloud.githubusercontent.com/assets/3165071/22525135/c4f3c3a2-e8ce-11e6-9797-977931ee30c6.png)

Sample of one of the submissions
```name: Larry Gilman
email: lgilman@lgdirect.net
phone: 267-908-3863
company: Larry Gilman Direct
existing_account: 'yes'
merchant_id: "496216110882"
dba: Larry Gilman Direct
looking_for:
  - Customized Payments Page
  - Default Payments Page
lead_page: https://cardconnect.com/partner/hpp
logo: 1730eb5f-0eea-4abd-8008-422667bcf777
```
