### ISSUE TITLE
I want to set primary locale anything other than "EN", but can't

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1215]
### Expected behaviour
Main domain (http://statamic.dev) should work for TR locale
and http://statamic.dev/en/ should work for EN locale

### Actual behaviour
Whole website got troubles

### Steps to reproduce
1. Created en folder as described in docs and added and edited index.php:
$statamic = '../statamic';
$site_root = '/en/';
$locale = 'en';
2. Edited index.php:
$site_root = '/';
$locale = 'tr';
3. Modified Nginx config and slapped one of those bad boys in for each locale:
location @enrewrites {
    rewrite ^/en/(.*)$ /en/index.php last;
}
location /en/ {
    try_files $uri $uri/ @enrewrites;
}
4. Did any stuff about settings in yamls
5. Restarted Nginx (To be sure that I did!)
6. Reloaded page and seeing this dreadful scene of ruin:
<img width="567" alt="screen shot 2017-02-01 at 12 58 43 am" src="https://cloud.githubusercontent.com/assets/5695187/22485132/a5ed393a-e819-11e6-9574-c12b583919b3.png">

### Server configuration
**Operating system**: macOS

**Web server:** Nginx

**PHP version:** 7.1.1

**Statamic version:** 2.5.1

**Updated from an older Statamic or fresh install:** Freash

**List of installed addons:** Nothing

### Logs
There on the shot you can see browser logs, yeah

**Comment by jasonvarga** [comment]
Temporary fix is to open `statamic/settings/defaults/system.yaml` and remove the `locales` array.

**Comment by peimn** [comment]
I didn't that, just reordered the array from:
en:
    full: en_US
    name: English
    url: /en
  tr:
    full: tr_TR
    name: Turkçe
    url: /

to:

tr:
    full: tr_TR
    name: Turkçe
    url: /
  en:
    full: en_US
    name: English
    url: /en

and it works now

**Comment by jasonvarga** [comment]
Oh I see. Yes, the first locale in the array is the default.

**Comment by peimn** [comment]
But now in CP , I am editing the home page:

- The content for default locale (TR in this case) is visible
- But the content for secondary locale (EN yes you guessed right!) is invisible

**Comment by jasonvarga** [comment]
If you put `tr` first, does it fix your problem?

**Comment by peimn** [comment]
It seems that doing that solved the problem, but their must be a better solution, may be we can reorder the array programmatically and bring the default locale to the front of array

**Comment by jackmcdade** [comment]
We're working on it.
