### ISSUE TITLE
Localized control panel

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1216]
### Expected behaviour
After adding other locales and making Statamic localized I want to have CP in both TR and EN locales:

http://statamic.dev/cp <<<< TR dashboard
http://statamic.dev/en/cp <<<< EN dashboard

### Actual behaviour
http://statamic.dev/en/cp redirects to http://statamic.dev/cp

### Steps to reproduce
1.  Did the stuff about adding locales to Statamic and get it to work by help of a Statamic gentleman
2.  Went to dashboard and envisage I will see English dashboard in http://statamic.dev/en/cp
3.  But it redirected me to http://statamic.dev/cp

### Server configuration
**Operating system**: macOS

**Web server:** Nginx

**PHP version:** 7.1.1

**Statamic version:** 2.5.1

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** Nothing

**Comment by jasonvarga** [comment]
The CP will only ever be accessible in the default locale.

To change the language the CP is displayed in, add `locale: whatever` to your `site/settings/cp.yaml` or a user file.

**Comment by peimn** [comment]
"The CP will only ever be accessible in the default locale."
Why ?!

**Comment by jasonvarga** [comment]
You can translate it. Why do you need to access it from two different places?

**Comment by jackmcdade** [comment]
It's just a URL thing. It has to route through the main index.php file. You can _change the default locale_ globally or on a per-user basis.

**Comment by peimn** [comment]
"To change the language the CP is displayed in, add locale: whatever to your site/settings/cp.yaml or a user file."

I added but doesn't work!

locale: en
widgets:
  -
    type: collection

**Comment by jasonvarga** [comment]
That's a different problem. I just opened https://github.com/statamic/v2-hub/issues/1218 for you.
