### ISSUE TITLE
Content for secondary locale is invisible

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1217]
I am editing the home page:

The content for default locale is visible
But the content for secondary locale is invisible

**Comment by jasonvarga** [comment]
Have you made any fields in the fieldset `localizable: true`?

**Comment by peimn** [comment]
@jasonvarga I did what you said and we get into the way faced with issues #1221 and #1222

**Comment by jackmcdade** [comment]
Since we're unable to recreate this and haven't received any more info, I'm going to close this issue. If you or anyone else has more information leading to the identification and elimination of this oddity, please reopen with said knowledge!
