### ISSUE TITLE
Debugbar grows at alarming rate on a larger site. 16GB folder in 5 hours.

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/v2-hub#1219]
**Statamic version:**
2.5.1 with 1200ish entries in a collection. less in multiple other collections.

zip sent via email to Jack. Just 200MB in about 5 mins.

```forge@here:~/example.com/local/storage$ du -hd 1
16G    ./debugbar
18M    ./search
9.4M    ./frameworknew
1.6M    ./logs
8.1M    ./framework
16G    .```

**Comment by jasonvarga** [comment]
Hah, yeah okay. You can run `php please debugbar:clear` on a regular basis.
