### ISSUE TITLE
FR: Add a setting to make all content fieldsets localizable

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1220]
### Expected behaviour
When I made my site multi language and localized I am expected the content fieldsets must be localizable
### Actual behaviour
In any of the fieldsets that we want to be multilingual we have to set it localizable, but in pages that no have specific fieldset (like home page in default installation of Statamic) the content is not localizable until you make a fieldset for it and define it localizable there is also a bug of doing this way, I'll post it as another issue

It may be useful to have a global settings to make all content localizable.

### Edit: ###
I posted mentioned issue: #1221

**Comment by peimn** [comment]
I have realized that the pages that don't have fieldset in their content use default fiedlset but the default fieldset is not included with default installation bundle of Statamic

**Comment by jasonvarga** [comment]
Create a `default.yaml` fieldset.

**Comment by jasonvarga** [comment]
We'll make sure to document this better, and/or make the fields localizable out of the box. It was an easy thing to miss!

**Comment by ebeauchamps** [comment]
Similar to a FR already opened regarding a way to localized the `display: ` part of a fieldset

**Comment by jasonvarga** [comment]
I've made the `content` field in the default fieldset localizable for next release so it works better out of the box.
