### ISSUE TITLE
Adding a fieldset property to content and making a field localizable causes other localizable fields in that fieldset lossing their old translated content

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1221]
### Expected behaviour
The field being localizable and every thing will persist and will be ok
### Actual behaviour
The old content of the localaized fields in the fieldset will be cleared and replaced with main locales's content

### Steps to reproduce
1.  We have home page (or any other page) that don't have fieldset (there is also no default fieldset [here you see](https://github.com/statamic/v2-hub/issues/1220#issuecomment-276643973)) first we insert some content for both locales
2.  Then we make a fieldset for our page and define non localizable fields as localizable and back to cp and refresh the edit page
3.  Change the locale, you will see your old localizable title is missed and filled by main locale's old content

### Server configuration
**Operating system**: macOS

**Web server:** Nginx

**PHP version:** 7.1.1

**Statamic version:** 2.5.1

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** Nothing

**Comment by jasonvarga** [comment]
Looks like you've just opened 3 issues that are all basically the same thing?

**Comment by peimn** [comment]
I just don't want to make it complex, and separate the issues

**Comment by peimn** [comment]
@jasonvarga there is a different between this issue and issue #1222 
On that issue you remove fieldset then you see the issue, here you add fieldset then you see the issue

**Comment by sebszocinski** [comment]
+1 this just happened to me... any progress on this?

**Comment by jasonvarga** [comment]
I believe this has been fixed for the next release. Please let us know once it's out.
