### ISSUE TITLE
Removing fieldset property from content causes localizable fields in that fieldset losing their content

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1222]
### Steps to reproduce
1.  Make a fieldset for a page and some localizbale fields
2.  Inter some data and save (In all locales)
3.  Remove fieldset property from content
4. Get back to edit page and refresh
5. Check content in all locales

### Server configuration
**Operating system**: macOS

**Web server:** Nginx

**PHP version:** 7.1.1

**Statamic version:** 2.5.1

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** Nothing

**Comment by jackmcdade** [comment]
What content is lost? The translations, or everything?

**Comment by jasonvarga** [comment]
Nice find. That's a weird one. Clearing the cache fixes it (obviously that's not the solution, though)

**Comment by peimn** [comment]
HI there, how it is going for this bug? Is it solvable?

**Comment by sebszocinski** [comment]
+1 this just happened to me but when adding a new field

**Comment by jasonvarga** [comment]
Closing this in favor of #1987
