### ISSUE TITLE
"Search for anything..." isn't translatable 

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1226]
### Expected behaviour
The placeholder of search input is translated
### Actual behaviour
The placeholder of search input isn't translated

### Steps to reproduce
1.  Create another locale
2.  Duplicate en from lang folder and rename it to desired language
3.  Find 'search_for_anything' in cp.php and translate it
4. Get back to dashboard and refresh it

**I also realized that 'en' locale is hard coded in 'cp.js' and in 'jabbascripts.js' as default locale, but in my setup en is secondary locale**

### Server configuration
**Operating system**: macOS

**Web server:** Nginx

**PHP version:** 7.1.1

**Statamic version:** 2.5.1

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** Nothing

**Comment by ebeauchamps** [comment]
Solved in 2.5.2 because the sentence was removed...the sentence was translated when the default language was left to `en` in `index.php`.
