### ISSUE TITLE
Sort should ignore spaces and quotes/apostrophies in titles

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/v2-hub#1230]
I'm not sure if this is a localization problem with special characters or not.

**Comment by jackmcdade** [comment]
Can you share an example on how this creates undesirable behavior? You mean like a quote at the beginning or something? I'm not sure I've seen people custom tailoring sort algorithms to this degree before.

**Comment by sheldonkotyk** [comment]
I believe that this is an issue in the CP, not sure about the front-end.

"A Title" or one with a space before the real characters was not sorted where expected.

**Comment by jackmcdade** [comment]
I've done some testing and research on this and unfortunately we won't be adding it. To string manipulate each title before sorting will make loading large datasets very slow, and may also affect use cases where people deliberately name things to bubble them to the top (e.g. _Awesome Company). Sorry man.
