### ISSUE TITLE
Too many redirects after installing 2.5.2 in /cp

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1231]
<img width="754" alt="screen shot 2017-02-02 at 12 13 28 am" src="https://cloud.githubusercontent.com/assets/5695187/22525549/d4797d9a-e8dc-11e6-8672-cf2d02243a23.png">

### Server configuration
**Operating system**: macOS

**Web server:** Nginx

**PHP version:** 7.1.1

**Statamic version:** 2.5.2

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** Nothing

**Comment by jackmcdade** [comment]
Are you saying that you installed Statamic itself into a subdirectory called `/cp` ?

**Comment by peimn** [comment]
No I mean control panel.

I just downloaded and replaced www content with new downloaded files and on that case this error raised.

But I cleaned everything and installed it again and now it not have this error

**Comment by jackmcdade** [comment]
Ah okay cool, must have been something with your locale or system settings. Feel free to open a new issue or ask for support at <https://statamic.com/support> if you run into anything.

**Comment by peimn** [comment]
No thanks I just want to close it  :)
