### ISSUE TITLE
View site in CP to be contextually aware (feature request)

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#1234]
### Expected behaviour
The "View Site" link in the top right of the control panel should open the site at the page / slug being editing. 

![view-site](https://cloud.githubusercontent.com/assets/3920126/22542410/8d8ed460-e923-11e6-84f9-492c30816ae9.png)

### Actual behaviour
Clicking "View Site" always opens the site at root.

**Comment by jackmcdade** [comment]
The contextually aware one is tucked under Sneak Peek: 

![image](https://cloud.githubusercontent.com/assets/44739/22549322/cc4b0ca6-e918-11e6-9522-beb81fd6fd67.png)

**Comment by wesort** [comment]
I think this is debatable based on user / client feedback. Anything wrong with my suggestion or simply a reiteration of a feature?

**Comment by jackmcdade** [comment]
Not every screen of the control panel has a corresponding URL, so for consistency it just pops you out to the main site. All screens that have one, have that Visit URL link now. I'd lean more towards removing it entirely than making it change.
