### ISSUE TITLE
Search bar for assets

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#1235]
_NB: I presume this is on the roadmap already and coming back at some point following the assets refactoring on v2.5+_

### Expected behaviour
The Assets realm of the control panel has a search bar that updates the results as one types. Search operates on filename, title, alt text, or any other text fields set on assets.

### Actual behaviour
No search bar.

**Comment by jackmcdade** [comment]
Yes, all the table searches on the roadmap. They're all interconnected, so I'm gonna close this issue down.

**Comment by ndf3** [comment]
Hey.

Was this feature deployed yet?
