### ISSUE TITLE
Asset preset-generation for CP causes slow pagination

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#1237]
### Expected behaviour
Navigation of pages of assets in CP

### Actual behaviour
Clicking pagination links does nothing. Looking closer the `href` is blank.

![cp-pagination](https://cloud.githubusercontent.com/assets/3920126/22546380/c277a010-e934-11e6-8e79-a6ae54b83908.png)

### Steps to reproduce
1.  Open CP > Assets 
2.  Ensure plenty of assets added and CP pagination setting forces 2+ pages
3.  Click page 2+ or »

**Comment by wesort** [comment]
Update: This appears to be occurring (AJAX? so the href is irrelevant?? ) but is very slow (5 minutes +) and no progress indication.

**Comment by jackmcdade** [comment]
Until those thumbnails are generated, there's not much we can do!
