### ISSUE TITLE
A rename file warning in all assets

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1238]
### Expected behaviour
It should say what is the problem with changing the name

### Actual behaviour
Just a rename file warning message appears 
<img width="385" alt="screen shot 2017-02-03 at 10 38 14 am" src="https://cloud.githubusercontent.com/assets/5695187/22582614/218e87da-e9fd-11e6-8bbd-0c45cb3165e2.png">

<img width="374" alt="screen shot 2017-02-03 at 10 41 45 am" src="https://cloud.githubusercontent.com/assets/5695187/22582678/6bd896a0-e9fd-11e6-955d-2274840c25d2.png">

### Steps to reproduce
1.  Go to asset manager
2.  And edit any asset 
3.  Click on rename or move

### Server configuration
**Operating system**: macOS

**Web server:** Nignx

**PHP version:** 7.1.1

**Statamic version:** 2.5.2

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** Nothing

**Comment by jasonvarga** [comment]
These are translations that have been recently added. Your custom translation file must not have them, so they just show the key.

This is in `cp.php`:

```
'rename_file_warning' => 'Renaming a file will not update any references to it, which _may_ result in broken links in your site.',
```

You'll want to add the appropriate translation to yours.
