### ISSUE TITLE
Bring back the collection search function

### ISSUE THREAD

**Issue by humanjpg** [statamic/v2-hub#1243]
Personally, I reckon the original search field for collections was better than the global search. It was really useful to be able to filter down through your entries.

_Example use case: If you want to delete an entry that's buried within a large collection, you have to paginate through and find it, because there's no delete button on the entry edit page._

(The global search is sluggish and sometimes doesn't even work. Also a bit strange that the clear button is on the left rather than the right.)

**Comment by jasonvarga** [comment]
It wasn't actually searching. It was just filtering the contents of the current view.

Now that we added pagination, you can't do that across pages. We removed the search due to time constraints. It'll definitely be back, though!

**Comment by danieljwestman** [comment]
+1

Is this something coming i next release? (Don't see the label but crossing my fingers!). Also need search function back for the users list. Thanks!
