### ISSUE TITLE
Control Panel: 2nd level nav items icons overlap with 1st level's

### ISSUE THREAD

**Issue by hmalaud** [statamic/v2-hub#1245]
### Expected behaviour
In CP, when adding subnav items with an icon, they should display on the left of the item, on the same line

### Actual behaviour
They overlap with their parent

### Steps to reproduce
1.  Create addon
2.  Add parent page with icon
3.  Add subpage with icon

### Server configuration
**Operating system**: OSX Sierra

**Web server:** Apache

**PHP version:** 7.0

**Statamic version:** 2.5.1

**Updated from an older Statamic or fresh install:** Fresh install

**Possible fix**: 
```
nav.nav-main > ul > li li .icon{
	top: auto;
	margin-left: 14px;
}
nav.nav-main > ul > li li .icon + .title{
	margin-left: 6px;
}
```

![cp-overlap-icons](https://cloud.githubusercontent.com/assets/1000119/22649615/06ed9db8-ec7c-11e6-9149-03ba83329ddc.jpg)

**Comment by rrelmy** [comment]
I still have this issue with v2.5.3

**Comment by rrelmy** [comment]
@jackmcdade @jasonvarga Can we reopen this issue? It is still present in v2.5.5

**Comment by jackmcdade** [comment]
I don't see it, the icons look in the right place to me. Where is it?

**Comment by jackmcdade** [comment]
Icon's can only be applied to the parent, designating a _section_. The subpages inside each section don't get icons. That's how it's designed.

**Comment by rrelmy** [comment]
But it worked before v2.5 😢
