### ISSUE TITLE
FR: template (in front matter) defaults to fieldset

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#1252]
When a piece of content doesn't have a specified `fieldset`/`template` in its front matter, it falls back to `default`. Since a template's vars match up with fields from the fieldset, it makes sense to name fieldsets and templates identically.

It would knock out a tedious chunk of our workflow if content w/o a specified `template` would fall back first to the value of `fieldset` and then  to `default`.

Would this ruin everyone else's life?

**Comment by jasonvarga** [comment]
> fall back first to the value of `fieldset`

What does first value mean?

**Comment by curtisblackwell** [comment]
```yaml
id: 7567ds6f7sdafa6ds7f6s5d67
fieldset: blog-post
# no template specified
```

Since `template` isn't specified, it should fall back to `blog-post`.

```yaml
id: 7567ds6f7sdafa6ds7f6s5d67
# no fieldset or template specified
```

Since neither `template` nor `fieldset` is specified, both would be `default`.

**Comment by jasonvarga** [comment]
Does this affect your workflow that much?
You end up going and setting the fieldset, is it much more effort to also set the template?

If you're using entries, you can always put `template` in the `folder.yaml` too.

**Comment by curtisblackwell** [comment]
How much it affects our workflow depends on who's creating the pages. You don't interact directly with the front matter when you create pages via the CP. When done this way, it requires opening up every page and adding the `template`.

Right, we do that for entries.

**Comment by jasonvarga** [comment]
Fair enough.

**Comment by jackmcdade** [comment]
This would change the default behavior too much. If you want to set a default, you can do it in a global, or collection-level, etc. 👍
