### ISSUE TITLE
What does this + button do?

### ISSUE THREAD

**Issue by than** [statamic/v2-hub#1253]
### Expected behaviour
Given where it is in the Collection creation screen, I'm assuming it is supposed to allow me to create a new field type at the same time as a new collection, which seems like a natural find.

### Actual behaviour
However, clicking the button just triggers the save new collection action.

### Steps to reproduce
1.  In Collections, click on Manage Collections.
2.  Click Create Collection
3.  Enter a title, then click the plus button in the field type selector. 

<img width="1000" alt="screen shot 2017-02-10 at 4 03 03 pm" src="https://cloud.githubusercontent.com/assets/510790/22845940/bf13fdde-efaa-11e6-8f2b-e82e27c0a9ac.png">

### Server configuration
**Operating system**:

**Web server:**

**PHP version:**

**Statamic version:**

**Updated from an older Statamic or fresh install:**

**List of installed addons:**

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Add those logs here
```

**Comment by jackmcdade** [comment]
It creates a new empty Fieldset with the name you give it, so you don't have to go make it and come back.
