### ISSUE TITLE
Taxonomy terms don't resolve with {{ entries }} tag for mounted collection

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1254]
With a mounted collection you can use `{{ entries }}` instead of `{{ collection:foo }}`

Inside a `{{ collection }}` tag, `{{ tags }}{{ title }}{{ /tags }}` will show the titles for the tags taxonomy.

In an `{{ entries }}` tag, `{{ tags }}{{ title }}{{ /tags }}` will just show the title of the entry

### Steps to reproduce
1.  open default Redwood theme
2.  add `{{ tags }}{{ title }},{{ /tags }}` to `partials/block.html`
3. view /blog - works fine
4.  change `{{ collection:blog }}` to `{{ entries }}` in `templates/blog/index.html`
5. view /blog - shows post title instead of taxonnomy term

**Comment by jasonvarga** [comment]
Good catch! Fixed for next release.
