### ISSUE TITLE
In Statamic 2.5.x updates, migration of IDs to paths not applied to User files

### ISSUE THREAD

**Issue by Robert-Black** [statamic/v2-hub#1258]
### Expected behaviour

When I upgraded to Statamic 2.5(.2), migration of IDs to paths should have been applied to the ~100 user files (inside /site/users/), which contain references to images and taxonomies for those users.

### Actual behaviour

When I upgraded to Statamic 2.5(.2), migration of IDs to paths **hasn't** been applied to the ~100 user files, which contain references to images and taxonomies for those users. They all still have IDs for their taxonomies and images. 

### Steps to reproduce
1.  Start with a site running Statamic 2.1.19
2.  Have user files with image fields that reference image and/or taxonomy IDs.
3.  Upgrade to Statamic 2.5, then 2.5.1, then 2.5.2
4.  None of the IDs for taxonomic and images in the user files have been migrated.

### Server configuration
**Operating system**: macOS 10.12.3

**Web server:** Apache/2.4.23

**PHP version:** PHP/5.5.29

**Statamic version:** 2.5.2

**Updated from an older Statamic or fresh install:** from 2.1.19

**List of installed addons:**

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Add those logs here
```

**Comment by jasonvarga** [comment]
Run `php please update:housekeeping`

Some users have reported the migrations not running when using the updater. Can't quite work out the cause yet.

**Comment by jasonvarga** [comment]
Oh, users! Totally missed that. I think thats on us.

**Comment by Robert-Black** [comment]
Output: Performing clean up steps for a 2.1.19 to 2.5.2 upgrade.


Running update: Statamic\Updater\Updates\MigrateAssets
------------------------------------------------------

Gathering asset related files...
[✗] There are no asset containers to migrate.


Running update: Statamic\Updater\Updates\MigrateTaxonomies
----------------------------------------------------------

Gathering taxonomy related files...
[✗] There are no taxonomies to migrate.


Running update: Statamic\Updater\Updates\MigrateTaxonomyFields
--------------------------------------------------------------

[✗] Fieldset about already migrated.
[✗] Fieldset gallery already migrated.
[✗] Fieldset globals already migrated.
[✗] Fieldset home already migrated.
[✗] Fieldset page already migrated.
[✗] Fieldset portfolio already migrated.
[✗] Fieldset post already migrated.
[✗] Fieldset Stanleys Results already migrated.
[✗] Fieldset taxonomy_ fieldset already migrated.
[✗] Fieldset things already migrated.
[✗] Fieldset user already migrated.


[✓] Housekeeping complete.

**Comment by jasonvarga** [comment]
You can now perform an update from 2.1 to 2.5

(2.5.x to 2.5.3 will not make any changes. If you're already on 2.5, you'll need to roll back manually then re-update)

**Comment by Robert-Black** [comment]
Thanks :-) But sorry, rewound back to 2.1.x, and updated to 2.5.0, then to 2.5.1, 2.5.2, and 2.5.3

No apparent change to any of the user files.

Case in point:
```first_name: Robert
last_name: Black
portfolio: true
left_handed: true
roles:
  - d32e14fb-08c9-44c2-aaf8-21200852bafd
email: robert@robertblack.com.au
website: http://www.robertblack.com.au
image2:
  - ec23060e-7eec-4106-ab00-ff7e2771dd1f
  - 2d949063-bf81-4f8f-a1de-45ae0c3792c2
  - 530676ef-c560-4872-86d5-aa0d9303221f
portfolio_video: '<iframe src="//player.vimeo.com/video/177974114?title=0&byline=0&portrait=0" class="vimeo" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'
locations: 
  - 7e2ae351-6f9f-452d-9c45-a9ffe87f9c6a
cartooncategories:
  - 8eeda501-107a-4c92-81dd-72e36c732e49
  - bdb7de2f-d659-4433-b812-26f97fff8599
  - ef39709e-cd42-4ff2-a6fa-7d4d7d7d5055
image1: /assets/img/gallery_mensa_homophones.png
id: 087d4c41-81f0-4afb-a950-070900e66c8b
password_hash: xxxx
state: Victoria```
