### ISSUE TITLE
If page is not published it should not create a cache if viewed by an admin!

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/v2-hub#1261]
### Expected behaviour
If page is not published it should not create a cache if viewed by an admin!

### Actual behaviour
If you hit the page whilst logged in, it'll get cached.

### Steps to reproduce
1.  Turn on Static Caching
2.  View Unpublished Page as an admin (you see it and cache gets made ... wrong this should not be made)
3.  View page not logged in ... you see it because a cache was made.

**Comment by jasonvarga** [comment]
In 2.5.4, draft pages will get an `X-Statamic-Draft` header, and will not be cached by Static Caching.
