### ISSUE TITLE
URL encode asset URLs with {{ url }} tag.

### ISSUE THREAD

**Issue by alexroper** [statamic/v2-hub#1262]
Related to previous [feature request implemented in v2.0.6](https://github.com/statamic/v2-hub/issues/74#issuecomment-222798966). 

Recent update has regressed this feature as of Statamic v2.5.3. {{ url }} tags are no longer url encoded.

### Expected behaviour

`{{ url }}` tag should url encode a filename with a space in it.

Filename `name with spaces.jpg` should be output as `name%20with%20spaces.jpg`.

### Actual behaviour

Filename output as just `name with spaces.jpg`.

### Server configuration
**Operating system**:
macOS Sierra 10.12.3

**Web server:**
Apache (MAMP Pro 4.1)

**PHP version:**
5.6.28

**Statamic version:**
2.5.3

**Updated from an older Statamic or fresh install:**
Updated.

**List of installed addons:**
None.

**Comment by jackmcdade** [comment]
This was on purpose. The previous behavior was actually unintentional. Does this cause any issues on your site?

**Comment by alexroper** [comment]
It did cause an issue. Using {{ url }} as a background image in a style attribute didn't work with the unencoded url. Worked before my upgrade to 2.5.3.

`<div style="background-image: url(name with spaces.jpg)">`

Here's an example:
https://jsfiddle.net/hnhmrxL7/

So the url encode from 2.0.6 release was unintentional?

**Comment by jackmcdade** [comment]
You should just be able to use ‘ ‘ quotes around the URL inside url(). That’s how you solve that :)

**Comment by alexroper** [comment]
Well, I just wanted to let you know in case the regression was unintentional.

Personally, I would prefer this solution: #1263

**Comment by jackmcdade** [comment]
Closing this. After careful considering, the current behavior is the desired one. Two way to solve the reported problem:

```
<div style="background: url('{{ url }}')"></div> # with quotes
<div style="background: url({{ url | rawurlencode }})"></div> # with rawurlencode modifier
```
