### ISSUE TITLE
FR: Replace spaces in uploaded asset filenames

### ISSUE THREAD

**Issue by alexroper** [statamic/v2-hub#1263]
Feature Request: When an asset is uploaded to the control panel, replace spaces in the filename with a word separator character. By default this would be a dash ('-').

So the filename, 'name with spaces.jpg' becomes 'name-with-spaces.jpg.'

Ideally, this would be the default behavior.

This should able to be overridden in Settings [similar to how Craft CMS does it](https://craftcms.com/docs/config-settings#filenameWordSeparator). So if you don't want filenames modified, change the setting to `null` to have them left alone.

I know that technically spaces in filenames are still valid filenames, but from the client's perspective, it would take a lot of headaches out of managing assets. Filenames with spaces sometimes cause unexpected problems and it's difficult for clients to remember to always remove spaces for their filenames.

Related to this issue:
[Assets manager should have the option to convert filenames to web-friendly format](https://github.com/statamic/v2-hub/issues/74#issuecomment-222798966)

**Comment by than** [comment]
Would partially resolve the issue in #1241

**Comment by jackmcdade** [comment]
This was added in 2.8.12. 👍
