### ISSUE TITLE
CP only notifies you you're logged out on posting an entry meaning you lose data

### ISSUE THREAD

**Issue by humanjpg** [statamic/v2-hub#1265]
### Expected behaviour
Entries should autosave, or the CP should at least check whether you're logged out or not (or something clever like the CP should cache and repost the entry submission data)

### Actual behaviour
When you post a new entry using a page that was open from the CP it only tells you you're logged out once you hit Save for the first time.

### Steps to reproduce
1. Open a new entry page  
2. Leave it for long enough that you're logged out of the session
3. On the page add some data and hit save for the first time and you'll be sent to the login screen

### Server configuration
**Operating system**:
Mac OSX

**Web server:**
Apache

**PHP version:**
7.0

**Statamic version:**
2.5.2

**Comment by jackmcdade** [comment]
Works totally fine for me. Was it working _before_ you switched? Maybe the search index hadn't been created yet? Also, are you using Algolia or the local (Zend) driver?
