### ISSUE TITLE
FR: automatically create redirect when slug changes?

### ISSUE THREAD

**Issue by ericwenger** [statamic/v2-hub#1266]
### Suggestion:
Is there a way for Statamic to create a redirect when someone changes an existing slug? Some of my SEO co-workers like to change slugs when they're optimizing a site, and it would be super if Statamic would sense that change and automatically create a redirect.

**Comment by edalzell** [comment]
After thinking about this, this *could* be handled w/ an event (content.before_saved) or by passing the old data in the `content.saved` event.

Would allow you solve both natively and give devs more options.

**Comment by ilyaskorik** [comment]
This is real problem. I can't update Entry itself in 'content.saved' event, because there endless cycle.

**Comment by jasonvarga** [comment]
@ilyaskorik Erin's suggestion was to create a redirect somewhere else (eg. the routes file or htaccess). I don't think he suggested for anything to be written back into the entry.

@ericwenger Here's a little addon to do it. Put it in `site/addons/CreateRedirectWhenChangingSlug/CreateRedirectWhenChangingSlugListener.php`

``` php
<?php

namespace Statamic\Addons\CreateRedirectWhenChangingSlug;

use Statamic\API\Entry;
use Statamic\API\Config;
use Statamic\Extend\Listener;

class CreateRedirectWhenChangingSlugListener extends Listener
{
    /**
     * The events to be listened for, and the methods to call.
     *
     * @var array
     */
    public $events = [
        'content.saved' => 'handle'
    ];

    public function handle($content, $old)
    {
        $oldContent = clone $content;
        $oldContent->slug($old['attributes']['slug']);

        $redirects = Config::get('routes.redirect', []);
        $redirects[$oldContent->url()] = $content->url();
        Config::set('routes.redirect', $redirects);
        Config::save();
    }
}
```

**Comment by edalzell** [comment]
Were it me, I'd probably add a check in there to see if the slug actually changed...otherwise your routes file might get quite big as this is fired whenever any content is saved.

**Comment by jasonvarga** [comment]
Good thinking. That wasn't intended to be the perfect solution or to turn this issue the support thread for it, it was just an example.
