### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by danieljwestman** [statamic/v2-hub#1269]
### Expected behaviour
Everything in CP should be possible to translate. 

### Actual behaviour
Almost everything is, but not the Upload button (on every place it's located). Maybe some other strings I haven't found yet (working on it).

### Steps to reproduce
1.  Translate the CP in your own site lang folder
2.  Look at the assets browser (or in fieldsets with assets)
3.  The button for uploading new assets aren't translated

### Statamic version
Latest for now, 2.5.3.

**Comment by ebeauchamps** [comment]
Dup

**Comment by danieljwestman** [comment]
Oh sorry, missed that one
