### ISSUE TITLE
Taxonomies in pages

### ISSUE THREAD

**Issue by marconucara** [statamic/v2-hub#1270]
### Expected behaviour
I hope that you can also use taxonomies in pages, not only collections.

### Actual behaviour
Taxonomy tems used in page doesn't increment correctly the counter in `cp/taxonomies/<taxonomy_name>`, also taxonomy tag doesn't work properly in template (can't loop and getting title/slug, if i print it i get only the id).

### Steps to reproduce
Use taxonomies in a page.

### Server configuration
**Operating system**:
OSX or Amazon linux
**Web server:**
Valet or Apache
**PHP version:**
7.0.19
**Statamic version:**
2.5.2 and 2.5.3
**Updated from an older Statamic or fresh install:**

**List of installed addons:**
Placid and Spock

**Comment by nuky89** [comment]
I start to think that the problem is not the use within the pages. I used it in other pages and it works. The only difference that i can notice is the name of the variable. The case that works use a variable named as the taxonomy. Anyway a bug, i presume.

**Comment by jackmcdade** [comment]
The taxonomies are attached to the fieldset now. Have you seen how that works in 2.5?
