### ISSUE TITLE
Clicking on Fieldset + in edit collection mode jumps away

### ISSUE THREAD

**Issue by manogi** [statamic/v2-hub#1273]
### Expected behaviour
On the editing page of a collection (f.e. "Blog"), clicking on the + icon, the input field and the blue create button should appear to create a new Fieldset.

### Actual behaviour
When I click on the + icon next to the Fieldset dropdown, sometimes I see the input field and the blue create button appear very shortly, but always the page jumps to the main collections/entries/blog page flashing "Blog updated." This happens with all collections. If there is no entry, it does not flash the message.

When I hit the browser back button, it shows me the input field and the blue create button and I can create a new Fieldset.

### Steps to reproduce
see above (tried Browsers Chrome, Safari and Firefox)

### Server configuration
**Operating system**: 
OSX

**Web server:**
Valet

**PHP version:**
 7.1

**Statamic version:**
 2.5.3

**Updated from an older Statamic or fresh install:**
Fresh install

**List of installed addons:**
none

**Comment by ebeauchamps** [comment]
See #1253

**Comment by manogi** [comment]
Aah, didn't see that one.
