### ISSUE TITLE
Pages do not appear in Control Panel when running in a subdirectory

### ISSUE THREAD

**Issue by sarahkyler** [statamic/v2-hub#1276]
### Actual behaviour
Regardless of whether or not there are pages in the Statamic build, the CP shows the pages display as if there aren't any pages. This is happening when the statamic install is working inside a subdirectory/subfolder. 

### Server configuration
**Operating system**:
CentOS
**Web server:**
Apache
**PHP version:**
5.6+
**Statamic version:**
(Might be on 2.5.0 or 2.5.1, I jumped straight to 2.5.2)
2.5.2
**Updated from an older Statamic or fresh install:**
Updated
**List of installed addons:**
None

**Comment by jackmcdade** [comment]
Working on a fix for this!
