### ISSUE TITLE
Sneak Peek no longer create placeholder taxonomy objects

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#1278]
### Actual behaviour
When "Sneaking a Peek" at a NEW post, ALL tags get displayed as a copy of the current Title
When "Sneaking a Peek" at an OLD post, ANY NEW tags are also displayed as a copy of the Title

### Steps to reproduce
1. Default 2.5.3 install, straight out of the box.
2. Open CP (http://localhost/cp/dashboard)
3. Click on big blue button in center: "New Blog Post"
4. Without doing anything else, click on dark gray button in upper right: "Sneak Peek"
5. Without doing anything else, click left panel field labeled: "Tags" and in the dropdown list that appears, select "coffee"
6. Observe: an empty light gray rectangle appeared in the whitespace below the circular avatar of Niles Peppertrout.  
7. Click again in the "Tags" field and type: "hi", [tab], "there" [tab]
8. Observe: there are now three grey rectangles in the whitespace below the avatar, one for each "Tag".
9. Click the top left panel field labeled: "Title" and type "Wow!"
10. Observe: The title of "Wow!" appears as expected, but all three light gray Tag rectangles also contain "Wow!"
11. Confirm by clicking again in Tags field and select "star-wars" from the drop down.
12. Observe: a fourth "Wow!" tag appeared.

13. Click Blue "Done" button in top left panel, then "Dashboard" in top left panel to abandon unwanted changes.

14. Mess with any of the existing out-of-the-box blog posts, and you'll see Sneak Peek respects pre-existing taxonomy tags, but likewise echos the title for tags you try to add.

### Server configuration
**Operating system**:
Mac OS Sierra 10.12.3

**Web server:**
Apache/2.4.25 (Unix)

**PHP version:**
PHP 7.0.15

**Statamic version:**
2.5.3

**Updated from an older Statamic or fresh install:** 
fresh install

**List of installed addons:**
(whatever's in the box)

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
(n/a)
```

**Comment by jackmcdade** [comment]
Nice catch, it looks like the new taxonomy approach hasn't been adapted to sneaking the peeks. We shall endeavor upon a fix for all.

**Comment by jackmcdade** [comment]
No longer an issue.
