### ISSUE TITLE
'required_if' does not work in an addon setting

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1281]
### Expected behaviour
When I add `required_if:add_new_users,true` to an addon setting and save the settings, I want an error to occur if `add_new_users` (a toggle) is true and the field is empty.

### Actual behaviour
Settings are saved

### Steps to reproduce
1. Create an addon setting with a toggle and a text field
2. Add `required_if:add_new_users,true` as the validation for the text field
3. Turn the toggle on and leave the field blank
4. Save the settings

### Server configuration
**Statamic version:**
2.5.3

**Comment by edalzell** [comment]
Perhaps related to #1018?

**Comment by jasonvarga** [comment]
Since fields are nested in `fields`, you need to write your validation rule that way.

```
required_if:fields.add_new_users,true
```
