### ISSUE TITLE
Default Install Has "Inception"-ish Blog Post Footers?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#1282]
### Expected behaviour
In the Default Install's Blog page footers, there should be no blog post after the last blog post, and posts referenced in the footers should only reference their own info.

### Actual behaviour

(This was a "learning experience" for me, so please bear with me…?)

### Steps to reproduce
1.  Install 2.5.3
2.  Go to last blog post: `/blog/2015/01/18/my-first-day`, and note title is "My First Day"
3.  Scroll to bottom of page and under "Next Up on the Blog" click… "My First Day" 
4.  (Don't) Repeat forever…

Seems `partial/article-footer` does not currently test for `no_result`, so when it calls `partial/block` on the last blog post, `block` mistakenly reuses the `intro_image` and `content` from the current (last) blog post. So, although `article-footer` does set a scope via `{{ collection:next in="blog" limit="2" scope="tag" }}` I can't figure out how that's intended to work. Seems `scope="tag"` is not quite right?

#### In a similar way…

1. Go to `/blog/2015/05/15/speeder-bikes-and-wookiees`
2. Scroll to bottom of page and under "Next Up on the Blog" note that the "Spring has Sprung" snippet is reusing the same image as at the top of the page.

Here again `partial/block` is "looking up" too far when it tests for `{{ if intro_image }}`. Turns out there is none for "Spring has Sprung" (which instead has a `hero_image`), but there *is* one in the containing context of the page, so… Again, some kind of scope repair is necessary. Thing is, I'm too new at this scope business to suggest a good generalized solution. `¯\_(ツ)_/¯` (Sorry)

### Server configuration
**Operating system**:
macOS Sierra 10.12.3

**Web server:**
Apache/2.4.25 (Unix)

**PHP version:**
7.0.15

**Statamic version:**
2.5.3

**Updated from an older Statamic or fresh install:**
fresh install

**List of installed addons:**
(/na)

### Logs
(n/a)

**Comment by jackmcdade** [comment]
Fixed by adding `url:not="{url}"` :)
