### ISSUE TITLE
Taxonomy fieldtype doesn't show values in Tags mode

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1284]
### Expected behaviour
Add a taxonomy fieldtype to a fieldset and set to tags mode (with the relevant taxonomy turned off in the taxonomies section of the the fieldset edit page). Edit an entry with that fieldset. You should be able to select taxonomy values from the field.

### Actual behaviour
The field won't let you type and no drop-down appears.

Switching to panes mode allows values to be selected.

### Statamic
2.5.3, Updated

**Comment by jackmcdade** [comment]
What do you have set for the `label`?
