### ISSUE TITLE
Toggle default value overwrites disabled toggles

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1287]
### Expected behaviour
Disabled toggle should not change it's value to enabled if the default is enabled.

### Actual behaviour
If a fieldset contains a toggle with a default of `'1'` (enabled)  but the entry has an disabled state it always gets enabled again when opened because the disabled state is not saved in the yaml file.

### Server configuration
**PHP version:** 2.5.3

**Comment by jasonvarga** [comment]
I think we fixed this in 2.5.6, while fixing something else.
