### ISSUE TITLE
CP "Upgrade Available" Notice Persists—Until Cache Cleared.

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#1289]
Two CP Updater Upgrades from Statamic 2.1.18 to 2.5.3 went without any problems whatsoev… except the "Upgrade Available" notice was "stuck" in the upper left of the CP window until I cleared the cache.

Maybe add an automatic clearing of the cache to the Updater script?

**Comment by jackmcdade** [comment]
We already do clear the cache afterwards. There must be another reason is sticks. Browser caching, perhaps?

**Comment by lukeagsmith** [comment]
I get this too, even after a `shift+refresh` in the browser.

**Comment by gmcz** [comment]
FWIW, I used to have to manually clear the cache as well, but since 2.5 it’s worked as I would’ve expected it to.

**Comment by jackmcdade** [comment]
It happens sometimes, and not other times. It's the darndest thing. We really do clear the whole cache on upgrade, I promise. :) Maybe something just happens after the clear, before it discovers the new version number... We'll keep poking around on this one. At least it's not a mission critical thing.

**Comment by iDGS** [comment]
Yep. Seems to be fixed! Thanks!
