### ISSUE TITLE
Title field title does not show in edit screen

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1291]
### Expected behaviour
The `display` value for a title field of a fieldset should show in an edit template.

### Actual behaviour
It always reads "title"

![statamic__title-field--display](https://cloud.githubusercontent.com/assets/16148258/23507814/a6d2f0da-ff46-11e6-9bbe-b7e658bf7b78.png)

**Comment by jackmcdade** [comment]
We do it this way so that placeholder can be translated. It follows the formula `new` `$content_type`. Good idea, and if we every come up with an easy way to translate fieldset values like that, we'll revisit!
