### ISSUE TITLE
Bug? Date and Time fieldtypes setting non-null value

### ISSUE THREAD

**Issue by chris-79** [statamic/v2-hub#1292]
### Expected behaviour
Null/unset values in an existing entry should not cause the date picker or time picker to become set when the entry's edit page is opened.

### Actual behaviour
When the field value is null/not set, the `date` field defaults to today and the `time` field defaults to midnight, **BUT ONLY** if the entry already exists (aka when editing an existing entry).

### Example entry data causing the issue:
```
end_date: ""
end_time: ""
```

– and –

```
end_date:
end_time:
```

#### Observed
![screenshot](https://i.imgur.com/ynxXTde.png)

#### Expected

![screenshot](https://i.imgur.com/nW9k4Sp.png)

### Steps to reproduce
1.  Create entry with date and/or time fieldtype data that is null
2.  Open the Edit page for the entry 
3.  Observe that the fields now have values

### Server configuration
**Operating system**:
MacOS 10.12.3

**Web server:**
    2.4.25

**PHP version:**
    7.0.15

**Statamic version:**
    v2.5.3

**Updated from an older Statamic or fresh install:**
    Updated

**List of installed addons:**
- **[imgix 2.0.0](https://github.com/imgix/imgix-statamic)** by imgix
- **Loop 1.0.0** by Jason Varga & Rudy Affandi
- **[ParseURL 1.0](https://github.com/chris-79/statamic-ParseURL)** by Chris S.
- **[TaxonomyFilter 1.0](https://github.com/chris-79/statamic-TaxonomyFilter)** by Chris S.
- **[Workshop 1.0](https://addons.statamic.com/workshop)**

### Logs
_none_

**Comment by jackmcdade** [comment]
Looking into it!

**Comment by jackmcdade** [comment]
Squashed for release in 2.5.6.
