### ISSUE TITLE
Bug: Time fieldtype weirdness

### ISSUE THREAD

**Issue by chris-79** [statamic/v2-hub#1293]
### Actual behaviour
The `time` filedtype renders wrong information if data is not using 24-hour time

#### Correct

- `end_time: 13:23`<br> ![](https://i.imgur.com/qZDhaSQ.png)

#### Incorrect

- `end_time: 1:23 PM`<br> ![](https://i.imgur.com/g07a7zN.png)

### Server configuration
**Operating system**:
MacOS 10.12.3

**Web server:**
    2.4.25

**PHP version:**
    7.0.15

**Statamic version:**
    v2.5.3

**Updated from an older Statamic or fresh install:**
    Updated

**List of installed addons:**
- **[imgix 2.0.0](https://github.com/imgix/imgix-statamic)** by imgix
- **Loop 1.0.0** by Jason Varga & Rudy Affandi
- **[ParseURL 1.0](https://github.com/chris-79/statamic-ParseURL)** by Chris S.
- **[TaxonomyFilter 1.0](https://github.com/chris-79/statamic-TaxonomyFilter)** by Chris S.
- **[Workshop 1.0](https://addons.statamic.com/workshop)**

### Logs
_none_

**Comment by jackmcdade** [comment]
Looking into this along with your #1292.

**Comment by jackmcdade** [comment]
Okay, so the time fieldtype only supports 24 hour time, so that kind of makes sense. We'll look at upgrading the fieldtype in the future, but this one isn't actually a bug, per sé.
