### ISSUE TITLE
Can't drag sets order inside replicator modal in CP fieldset editor

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1294]
Clicking and dragging on the three line icon for sets inside the field editor modal for a replicator doesn't work

**Statamic version:**
2.5.3

**Comment by lukeagsmith** [comment]
This also seems to be the case on the formset edit screen.

Safari 10.0.3

**Comment by jackmcdade** [comment]
Seems to work fine to me, can you confirm in 2.5.5?
