### ISSUE TITLE
FR: automatic form emails to use label instead of fieldname

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1296]
Using the display value from the yaml would make for a friendlier email when a custom email template isn't really required.

For bonus points:
- `site_url` could be changed to `current_url` to show which page the form was submitted from
- `date`, `now` and `today` are all in the email and always seem to be the same. Are all 3 of these required, perhaps just the submission date is a useful default?

**Comment by rrelmy** [comment]
Dupe of #1267

**Comment by lukeagsmith** [comment]
You're right rrelmy, apologies for not checking more thoroughly first. I'll close.
