### ISSUE TITLE
Closing "new folder" window with the X makes the "new folder" button not working anymore

### ISSUE THREAD

**Issue by manogi** [statamic/v2-hub#1298]
### Expected behaviour
The "New Folder" button should keep on working.

### Actual behaviour
The "New Folder" Button stops working after closing the window with the "X" (but not when closing it with the "Close" button, weirdly).

### Steps to reproduce
In Assets, click on "new folder".
Close with "X".
Try clicking "new folder" again.

### Server configuration
**Operating system**:
OSX with Chrom or Safari

**Statamic version:**
2.5.3

**Comment by jackmcdade** [comment]
Got this sorted out for next release.

**Comment by manogi** [comment]
Great, thanks.
