### ISSUE TITLE
Feature Request: CP - select multiple assets at once

### ISSUE THREAD

**Issue by manogi** [statamic/v2-hub#1299]
When adding assets to a collection in the CP it would be great if one could select multiple lines for example with clicking in the first asset and then shift+ or command+ clicking on the last asset - all assets between those two should be selected.

Or a "select all" button to select all assets in a folder.

Or both.

Cheers, Sebastian

**Comment by jackmcdade** [comment]
Would be nice but not plans to add it at this time. It's pretty hairy :)
