### ISSUE TITLE
Accessing asset folders via cp with oddly sized image times out.

### ISSUE THREAD

**Issue by markzegarelli** [statamic/v2-hub#1302]
### Actual behaviour
When trying to open a specific folder within the asset container, the spinner spins, and an error is logged. (see below)

There is one image that causes this to happen, which measures 799x45. I was able to fix it by resizing the image to roughly square (799x800). This allowed the thumbnail to generate properly.

After the thumbnail was built, I resized the image back to 799x45 and did not see this error. However, after clearing the glide cache, it reappeared.

I assume what is that Glide is attempting to do math on that image which has a very weird aspect ratio, and it is Glide that's causing the error 

Here is the offending image:

![audience-3](https://cloud.githubusercontent.com/assets/5651320/23634853/65bb31aa-0281-11e7-9407-317a7632f201.png)

### Server configuration
**Operating system**:
Mac OS 10.12.3

**Web server:**
nginx (valet)
**PHP version:**
7.1.1
**Statamic version:**
2.5.3

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
ERROR
[2017-03-06 23:13:39] dev.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 134217728 bytes exhausted (tried to allocate 71020001 bytes) in /Users/mark/work/support-site-2/statamic/vendor/intervention/image/src/Intervention/Image/Gd/Commands/ResizeCommand.php:56 Stack trace: #0 {main} [] []
```

**Comment by jackmcdade** [comment]
I think this is the second time we've seen this, with super tall or skinny images, Intervention\Image freaks out. We'll submit a report over there and see what sticks!

**Comment by jackmcdade** [comment]
For reference: <https://github.com/Intervention/image/issues/701>

**Comment by edalzell** [comment]
Not sure if it's the author or not, but he asked a followup question @jackmcdade https://github.com/Intervention/image/issues/701#issuecomment-291511711

**Comment by jasonvarga** [comment]
This appears to have disappeared in 2.5.7
