### ISSUE TITLE
FR: Image thumbnails possible in CP collection list

### ISSUE THREAD

**Issue by manogi** [statamic/v2-hub#1304]
I would really really need to be able to show a uploaded image in the collection list. Or ist that already possible? 

Lets say the field name is `main_image` - if I add `- main_image` to the columns in the folder.yaml, it just shows the URL of the image. Is there no way to show a thumbnail of the image?

**Comment by jackmcdade** [comment]
Now possible in 2.9.0. 🔥

**Comment by manogi** [comment]
I saw - very niiiiiiiiice
