### ISSUE TITLE
UserRoles fieldtype doesn't save single role properly

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1309]
When `max_items` is set to one, the drop down properly appears in the UI but when the data is saved it's still save as an array:

```
    role:
      - dd062758-f56c-4ca5-a381-fe88f9c54517
```

Then because it's an array it's not loaded properly into the UI (it expected a string and gets an array)

### Server configuration
**Statamic version:**
2.5.4

**Comment by jackmcdade** [comment]
Should be fixed for next release.
