### ISSUE TITLE
FR - Option to add custom CSS to CP

### ISSUE THREAD

**Issue by manogi** [statamic/v2-hub#1310]
It would be great if there was an option to add some custom CSS to the CP. At the moment after each update I manually add a one liner to the `head.blade.php` file:
```
{!! isset($GLOBALS['override_css']) ? $GLOBALS['override_css'] : '' !!}
```
And I have an addon that takes care of the `$GLOBALS['override_css']`.
But that's an ugly hack. I don't like using the `GLOBALS` variable, and also it outputs the CSS inline into the header (ugh!). 
It would be great I one could have like an `overrides` folder or similar inside the `site` folder and the CP would automatically look for any css files in there and reference them in the head.

I think I can't write all of that functionality alone, because I needed to touch the core file `head.blade.php`. Right?

I don't want to change a lot (promise!), just small things. For example in some cases the "Panes" are a little too small if one wants to reorder lots of entries in there, and I make them taller... these kind of things.

Cheers, Sebastian

**Comment by rrelmy** [comment]
You can do this from inside an addon, take a look the [`cp.add_to_head` event](https://docs.statamic.com/addons/events#cpaddtohead)

Sample code
``` php
    /**
     * @return string
     */
    public function addToHead()
    {
        return $this->css->tag("style") . PHP_EOL;
    }
```

**Comment by manogi** [comment]
Thank you! I am still getting to know Statamic, learn something new every day.
This is great.
