### ISSUE TITLE
500 returned when trying to mount a Collection to the homepage

### ISSUE THREAD

**Issue by crash13override** [statamic/v2-hub#1311]
### Expected behaviour
I'd expect the Collection to be added to the homepage just like for the other pages

### Actual behaviour
It returns a 500 error and I attach the Laravel Exception to show the actual problem

### Steps to reproduce
1.  Open the Pages section
2.  Click "Mount Collection" for the Home page
3.  it returns a 500 error code

### Server configuration
**Operating system**:
MacOS
**Web server:**
Nginx
**PHP version:**
7.0
**Statamic version:**
2.5.3
**Updated from an older Statamic or fresh install:**
updated from 2.5 I think
**List of installed addons:**
no addons installed

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Add those logs here
```
![screen shot 2017-03-09 at 15 18 37](https://cloud.githubusercontent.com/assets/1100260/23754181/5592f364-04dc-11e7-9207-970caeb933cf.png)

**Comment by jackmcdade** [comment]
Fixed for next release!

**Comment by crash13override** [comment]
great, thanks!
