### ISSUE TITLE
Assets dialog does not limit max_files

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1313]
### Expected behaviour
The assets dialog should not allow selecting more files than the defined `max_files` from the Assets fieldtype

### Actual behaviour
It is possible to select more files than allowed

### Steps to reproduce
1.  Open assets dialog
2.  Select more files than `max_files`
3.  😭 

### Server configuration
**Operating system**: macOS 

**Web server:** Valet

**PHP version:** 7.2

**Statamic version:** 2.5.5

**Updated from an older Statamic or fresh install:** Updated

**Comment by rrelmy** [comment]
Just realised it happens also outside of replicators

**Comment by jasonvarga** [comment]
Are you using `max_files: "1"` or `max_files: 1`?

Try changing it to the integer if its a string.

**Comment by rrelmy** [comment]
It was a `string`, after changing it to an `int` it works.

Adding an asset fieldtype through the interface saves `max_files` as `string`
