### ISSUE TITLE
CP: Collection Fieldset and Max Items 1 set as Panes

### ISSUE THREAD

**Issue by JayVerb** [statamic/v2-hub#1314]
### Expected behaviour
When  adding a _Collection_ field type in a fieldset, if you set it to _Max Items_ 1 and _UI Mode_ to Panes, it should display as a dropdown list rather than Panes when adding new content.

### Actual behaviour
It still displays as _Panes_ 

### Steps to reproduce
1.  Make sure you have a _Collection_ with entries
2.  Add a _Collection_ Field within a  fieldset
3.  Set _Max Items_ to 1
4.  Set _UI Mode_ to _Panes_
5.  Add a new entry where the fieldset you just edited is present

### Server configuration
**Operating system**:
Mac 10.12.3

**Web server:**
Apache

**PHP version:**
7.0.2

**Statamic version:**
2.5.5

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**
N/A

### Logs
N/A

<img width="525" alt="panes fieldset display" src="https://cloud.githubusercontent.com/assets/139255/23807452/96dabb38-057a-11e7-95d9-e096f828987c.png">

**Comment by jackmcdade** [comment]
Got this one fixed up. It was the age-old "YAML is parsing `1` as the string "1"`.

**Comment by JayVerb** [comment]
Awesome @jackmcdade, thank you! Does the YAML still save the result as an array if set to 1? It would be nice to get rid of all my `relate` tags .

**Comment by edalzell** [comment]
Perhaps this is the same issue: https://github.com/statamic/v2-hub/issues/1309 ?
