### ISSUE TITLE
Asset max files doesn't work

### ISSUE THREAD

**Issue by danieljwestman** [statamic/v2-hub#1321]
### Expected behaviour
When setting max files to 1 in a assets filedtype in fieldsets you should only be able to select ONE file in the assets browser.

### Actual behaviour
You can select multiple

### Steps to reproduce
1. Create a fieldset with an asset fieldtype
2. Create a page (or other data type) with that fieldset
3. Click to add asset
4. Select assets

### Server configuration
**PHP version:**
7.1

**Statamic version:**
2.5.5

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**
Many

### Logs
Nothing

**Comment by rrelmy** [comment]
Same as #1313
