### ISSUE TITLE
Firefox cutting off assets window

### ISSUE THREAD

**Issue by okse** [statamic/v2-hub#1323]
### Expected behaviour
Being able to add assets when using Firefox (51.0.1).

### Actual behaviour
The popup window extends the viewport, and makes the bottom buttons (and the pagination) unreachable.

See brief video of behaviour here: https://db.tt/Et6rfKSSC7

### Steps to reproduce
1.  Use Firefox
2.  Add asset in popup
3.  Unable to scroll, thus adding asset or paginate.

### Server configuration
**Operating system**:
OS X 10.12
Firefox 51.0.1
whatsmybrowser.org/b/26L1GA9

**Statamic version:**
2.5.5

**Updated from an older Statamic or fresh install:**
Updated (can't remember form which version).

**List of installed addons:**
None.

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Add those logs here
```

**Comment by jackmcdade** [comment]
Looking into it!

**Comment by jackmcdade** [comment]
Got it. That one was a beast.
