### ISSUE TITLE
Glide images start erroring randomly.

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/v2-hub#1327]
### Expected behaviour
Glide images continue working.

### Actual behaviour
In the middle of the night, we all of a sudden started getting 
```ErrorException·unserialize(): Error at offset 13887 of 14021 bytes```

### Steps to reproduce
Wait for intermittent issue to appear? Can't figure out the cause.

### Server configuration
**Operating system**:
Ubuntu

**Web server:**
Nginx

**PHP version:** 
7.1

**Statamic version:**
2.5.3

**Updated from an older Statamic or fresh install:**
Has been updated.

**List of installed addons:**
A number of custom addons.

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
ErrorException unserialize(): Error at offset 13887 of 14021 bytes 
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:78 Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
    [internal] unserialize
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:78 Illuminate\Cache\FileStore::getPayload
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:47 Illuminate\Cache\FileStore::get
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:98 Illuminate\Cache\Repository::get
    [internal] call_user_func_array
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:318 Illuminate\Cache\CacheManager::__call
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:217 Illuminate\Support\Facades\Facade::__callStatic
    
.../releases/20170314184929/statamic/core/Http/Controllers/GlideController.php:146 Statamic\Http\Controllers\GlideController::cachePath
    
.../releases/20170314184929/statamic/core/Http/Controllers/GlideController.php:130 Statamic\Http\Controllers\GlideController::createResponse
    
.../releases/20170314184929/statamic/core/Http/Controllers/GlideController.php:101 Statamic\Http\Controllers\GlideController::generateByAsset
    [internal] call_user_func_array
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:256 Illuminate\Routing\Controller::callAction
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:164 Illuminate\Routing\ControllerDispatcher::call
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:112 Illuminate\Routing\ControllerDispatcher::Illuminate\Routing\{closure}
    [internal] call_user_func
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    [internal] call_user_func
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102 Illuminate\Pipeline\Pipeline::then
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:114 Illuminate\Routing\ControllerDispatcher::callWithinStack
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:67 Illuminate\Routing\ControllerDispatcher::dispatch
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php:203 Illuminate\Routing\Route::runWithCustomDispatcher
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php:134 Illuminate\Routing\Route::run
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php:708 Illuminate\Routing\Router::Illuminate\Routing\{closure}
    [internal] call_user_func
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    [internal] call_user_func
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102 Illuminate\Pipeline\Pipeline::then
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php:710 Illuminate\Routing\Router::runRouteWithinStack
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php:673 Illuminate\Routing\Router::dispatchToRoute
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php:635 Illuminate\Routing\Router::dispatch
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:236 Illuminate\Foundation\Http\Kernel::Illuminate\Foundation\Http\{closure}
    [internal] call_user_func
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    
.../releases/20170314184929/statamic/core/Http/Middleware/PersistStache.php:22 Statamic\Http\Middleware\PersistStache::handle
    [internal] call_user_func_array
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:50 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::handle
    [internal] call_user_func_array
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49 Illuminate\View\Middleware\ShareErrorsFromSession::handle
    [internal] call_user_func_array
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:62 Illuminate\Session\Middleware\StartSession::handle
    [internal] call_user_func_array
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::handle
    [internal] call_user_func_array
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:59 Illuminate\Cookie\Middleware\EncryptCookies::handle
    [internal] call_user_func_array
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    
.../releases/20170314184929/statamic/core/Http/Middleware/Glide.php:50 Statamic\Http\Middleware\Glide::handle
    [internal] call_user_func_array
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    
.../releases/20170314184929/statamic/core/StaticCaching/Middleware/Retrieve.php:33 Statamic\StaticCaching\Middleware\Retrieve::handle
    [internal] call_user_func_array
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:44 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::handle
    [internal] call_user_func_array
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    [internal] call_user_func
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102 Illuminate\Pipeline\Pipeline::then
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:122 Illuminate\Foundation\Http\Kernel::sendRequestThroughRouter
    .../releases/20170314184929/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:87 Illuminate\Foundation\Http\Kernel::handle
    /home/forge/issuesiface.com/releases/20170314184929/public/index.php:155 [main]
```

**Comment by jackmcdade** [comment]
Out of nowhere is very strange. Do you have anything that happens on a cron or schedule or anything? Or is there user submitted content involved?

**Comment by sheldonkotyk** [comment]
Nope. Multiple sites. One with large collections, one with small. We're going to try serving from the glide cache and see if it happens again.

**Comment by sheldonkotyk** [comment]
I'm thinking maybe a spider hit it or something. Weird that it only affects the images though.

**Comment by jamiedumont** [comment]
I'm experiencing this issue too (which seems the same as #1212 ?). Judging by the frequency, it's happening whenever an image is requested.

This happens until eventually the error becomes 
```
ErrorException: unserialize(): Unexpected end of serialized data in /home/forge/magazine.bikesoup.com/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:78
```
at which point all images across the site fail.

Once that has happened, `php please clear:glide` has no effect, producing the same error as above. Instead, I have to delete the `/local` folder.

This is happening for me in Statamic 2.6.1 on a Laravel Forge server.

**Comment by jasonvarga** [comment]
Just fyi guys, I don't think that has anything to do with Glide. It's just a race condition where one request tries to read a cache file that another request hasn't finished writing. We're working on ways to address this.

**Comment by jamiedumont** [comment]
Thanks Jason. Any hacky ways of preventing it in the meantime?

**Comment by jasonvarga** [comment]
Are you guys (or your clients) using the CP?

Does this only seems to happen after some time? Like, immediately after clearing the cache its fine, then starts erroring out down the road?

**Comment by jasonvarga** [comment]
I believe I have this fixed for the next release.

**Comment by peda** [comment]
@jasonvarga has this already been released? #1327 is listed on 2.6.2 release notes, but this issue just happend to me on a live website running 2.6.4

`[2017-09-01 10:35:16] production.ERROR: exception 'ErrorException' with message 'unserialize(): Error at offset 13392 of 13551 bytes' in /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:78
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'unserialize(): ...', '/home/dkleiten/...', 78, Array)
#1 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(78): unserialize('a:89:{s:32:"e92...')
#2 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(47): Illuminate\Cache\FileStore->getPayload('glide::paths')
#3 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(98): Illuminate\Cache\FileStore->get('glide::paths')
#4 [internal function]: Illuminate\Cache\Repository->get('glide::paths', Array)
#5 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(318): call_user_func_array(Array, Array)
#6 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Illuminate\Cache\CacheManager->__call('get', Array)
#7 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Illuminate\Cache\CacheManager->get('glide::paths', Array)
#8 /home/dkleiten/www/at/dkl-statamic/statamic/core/Http/Controllers/GlideController.php(146): Illuminate\Support\Facades\Facade::__callStatic('get', Array)
#9 /home/dkleiten/www/at/dkl-statamic/statamic/core/Http/Controllers/GlideController.php(146): Illuminate\Support\Facades\Cache::get('glide::paths', Array)
#10 /home/dkleiten/www/at/dkl-statamic/statamic/core/Http/Controllers/GlideController.php(130): Statamic\Http\Controllers\GlideController->cachePath('containers/main...')
#11 /home/dkleiten/www/at/dkl-statamic/statamic/core/Http/Controllers/GlideController.php(61): Statamic\Http\Controllers\GlideController->createResponse('containers/main...')
#12 [internal function]: Statamic\Http\Controllers\GlideController->generateByPath('assets/img/oest...')
#13 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#14 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('generateByPath', Array)
#15 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\GlideController), Object(Illuminate\Routing\Route), 'generateByPath')
#16 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\GlideController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'generateByPath')
#22 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'generateByPath')
#23 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#24 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#34 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /home/dkleiten/www/at/dkl-statamic/statamic/core/Http/Middleware/PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#44 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#47 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#50 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#53 /home/dkleiten/www/at/dkl-statamic/statamic/core/Http/Middleware/Glide.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: Statamic\Http\Middleware\Glide->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#56 /home/dkleiten/www/at/dkl-statamic/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#59 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#62 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#64 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#65 /home/dkleiten/www/at/dkl-statamic/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#66 /home/dkleiten/www/at/dkl-statamic/index.php(157): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#67 {main}  
`

**Comment by jasonvarga** [comment]
Hi @peda you can comment out line 130 of GlideController.php (`$this->cachePath($path)`) temporarily.

**Comment by peda** [comment]
@jasonvarga thanks, I'll try that
