### ISSUE TITLE
CP - Closed #1314 now doesn't display anything in dropdowns

### ISSUE THREAD

**Issue by JayVerb** [statamic/v2-hub#1328]
### Expected behaviour
#1314 Was fixed and if only max 1 is set in collection, It does now display a dropdown, but it is empty. It does successfully save, just shows a blank dropdown.

### Actual behaviour
Blank Dropdown

### Steps to reproduce
1.  just open a page where you have a collection to allow for max 1

### Server configuration
**Operating system**:
OS X 10.12.3
**Web server:**
localhost Mac
**PHP version:**
7.0.2
**Statamic version:**
2.5.6
**Updated from an older Statamic or fresh install:**
Updated from 2.5.5
**List of installed addons:**

### Logs
No Logs

**Comment by jackmcdade** [comment]
This is now working as intended. 🏄
