### ISSUE TITLE
Missing translations in 2.5.7

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#1330]
-  the "MOVE" button in the assets submenu
![capture d ecran 2017-03-17 a 22 59 10](https://cloud.githubusercontent.com/assets/1823359/24064579/85fd0eb0-0b65-11e7-8891-2d7f8014d27a.png)
  
-  the "Size" word when editing an image
![capture d ecran 2017-03-17 a 22 59 46](https://cloud.githubusercontent.com/assets/1823359/24064588/962c7e2e-0b65-11e7-8414-1616696d76d2.png)

**Comment by ebeauchamps** [comment]
And having a possibility to get translated Dates would be a great plus (see above: "1 month ago")

**Comment by ebeauchamps** [comment]
Ah, sorry, found a third one:
-  When editing a field in a formset, I found that "Validation rules" is not translated.
![capture d ecran 2017-03-17 a 23 08 47](https://cloud.githubusercontent.com/assets/1823359/24064770/c7d8ed44-0b66-11e7-877d-d2cf619dc1de.png)

**Comment by jaggy** [comment]
@ebeauchamps Thanks for that!

Missing strings you've mentioned will be up next release.

Also, if Carbon supports the locale set by the user, the relative dates (`diffForHumans`) will be translated.

<img width="233" alt="screen shot 2017-03-22 at 12 44 02 pm" src="https://cloud.githubusercontent.com/assets/1993075/24182516/53ec59d0-0efd-11e7-9ee3-39e24bde8cd6.png">

**Comment by ebeauchamps** [comment]
Hello @jaggy 
Can you tell me how did you get to display "il y a 1 mois"?? Is there any setting I have to change and where do I have to look for this? sorry for being a noob with this...

**Comment by jaggy** [comment]
I added the localization for Carbon. It'll be up next release. To implement it now though, `\Carbon\Carbon::setLocale('fr');`
