### ISSUE TITLE
It seems some words missed for translating

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1331]
In page /cp/forms I saw some words didn't translated
<img width="216" alt="screen shot 2017-03-18 at 5 01 52 pm" src="https://cloud.githubusercontent.com/assets/5695187/24072486/da713d4e-0bfc-11e7-81a0-835ea2b789a6.png">

### Server configuration
**Operating system**: macOS

**Web server:** NGINX

**PHP version:** 7.1.1

**Statamic version:** 2.5.7

**Updated from an older Statamic or fresh install:** Updated from 2.5.5

**List of installed addons:** Nothing

**Comment by jaggy** [comment]
Thanks @peimn! 👍

**Comment by peimn** [comment]
Your welcome
