### ISSUE TITLE
I can't cancel adding field on formset creation 

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1332]
### Expected behaviour
Clicking on close or X button will cancel the adding process of field

### Actual behaviour
Anyway, the field will be created! 

Also the title of Modal is 'Edit field' and that confuses me that I'm creating new or editing an old one!

### Steps to reproduce
1.  Go to /cp/forms/create
2.  In Fields section click on Field +
3.  Do nothing and try to cancel adding by clicking X or close

### Server configuration
**Operating system**: macOS

**Web server:** NGINX

**PHP version:** 7.1.1

**Statamic version:** 2.5.7

**Updated from an older Statamic or fresh install:** Updated from 2.5.5 to 2.5.7

**List of installed addons:** Nothing

**Comment by jackmcdade** [comment]
After some discussion, this behavior is as intended, if only to support the Quick Add scaffolding feature.
