### ISSUE TITLE
default.yaml doesn't respect hide: true

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1336]
### Expected behaviour
`default.yaml`, if `hide: true` is set should not display in the list of pages to choose from - also the title and create title are ignored.

### Actual behaviour
`Default` always appears

in `CreatePage.vue` this code always adds in a link to default

```
// Ensure there is a default
if (! _.findWhere(fieldsets, { value: 'default' })) {
  fieldsets.push({ value: 'default', text: 'Default' });
}
```

**Comment by dannyuk1982** [comment]
To add to this as to why this is important:

- Much of the time a default page isn't called default - it might be something more descriptive, this makes it confusing for the client as they may have i.e.

- Default
- Page (home page)
- Page (images/gallery)
- Page (text heavy)
- Page (regular)
- Page (2 columns with form)

it isn't obvious at all what Default is

**Comment by beeldr** [comment]
Any news on this bug? Or whether it is fixed in V3, that would be great 😄

**Comment by hmalaud** [comment]
Would looove to have the possibility to disable that default fieldset from the pages list too.

**Comment by circleddie** [comment]
Was this included in a release? I'm selecting a specific fieldset built for a specific collection, however default keeps being included even though I've tried type: hidden, hide: true, etc... and nothing.
