### ISSUE TITLE
FR: Ability to specify title for Replicator field items

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/v2-hub#1337]
It would be great it we could specify the *title/label* of the items in a *Replicator* field in a similar way that you can specify the *label* to be used on a collection field. IE: `{{ title }}`

*Existing behaviour:*
<img width="902" alt="screen shot 2017-03-21 at 1 52 36 pm" src="https://cloud.githubusercontent.com/assets/1778271/24162969/9722680c-0e3f-11e7-9008-761f785bdeab.png">

*Purposed behaviour:*
<img width="876" alt="screen shot 2017-03-21 at 1 55 08 pm" src="https://cloud.githubusercontent.com/assets/1778271/24162995/aa2ec580-0e3f-11e7-95f7-3b910c3ba9c9.png">

Doing this would make it easier to re-arrange / drag and drop items in a *Replicator* field when they are all collapsed.

**Comment by jasonvarga** [comment]
In an upcoming release, we'll be adding previews of the data to the collapsed state.
So while it's not exactly what you requested, it's a solution to the same problem.

**Comment by jcohlmeyer** [comment]
It looks even better!
