### ISSUE TITLE
FR: Ability to filter a replicator field based on type

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/v2-hub#1338]
Add the ability to filter a replicator field based on the type. For example:

`{{ page:section type:is='anchor' }}`

Bonus, the ability to see if a replicator field has an item of a specific type.

Use case. I want to add a navigation `<nav>` only if a replicator field has anchors in it, and then iterate only over the anchors for the nav items. Then also add the anchors to the content as I iterate over the replicator field again.

A long form example:

```
{{ if page:section | contains='anchor' }}
  <nav>
    {{ page:section type:is='anchor' }}
      <a href="#{{ title | slugify }}" class="anchor">{{ title }}</a>
    {{ /page:section }}
  </nav>
{{ /if }}

<section class="main">
  <h1>{{ page:title }}</h1>
  
  {{ page:content | markdown }}
  
  {{ page:section }}
    {{ partial src="sections/{type}" }}
  {{ /page:section }}
  
  {{ partial src="{mount}" }}
</section>
```

**Comment by jackmcdade** [comment]
You can do that now like so:

```
{{ replicator_field where="type:anchor" }}
  // stuff
{{ /replicator_field }}
```
