### ISSUE TITLE
JS error in ascent.min.js

### ISSUE THREAD

**Issue by brettdewoody** [statamic/v2-hub#1339]
### Actual behaviour
The issue was brought to my attention by my client. When I first logged in the Admin worked ok, but after a refresh the error appeared. A JS error of `Uncaught SyntaxError: Invalid or unexpected token ascent.min.js?v=1.8.2:2`

Getting a JS error on all Admin pages. The error prevents Redactor fields from initializing which makes editing content impossible. 

### Steps to reproduce
1.  Open the admin
2.  Go to any page and the JS error will be present

### Server configuration
**Operating system**:
Mac, on Chrome

**Web server:**
Apache

**PHP version:**
7

**Statamic version:**
1.11.3

**Updated from an older Statamic or fresh install:**
Update

**List of installed addons:**
parent

### Logs
<img width="854" alt="screen shot 2017-03-21 at 8 18 07 pm" src="https://cloud.githubusercontent.com/assets/409070/24168861/9e7cd784-0e73-11e7-930f-c7c575cfc17d.png">

**Comment by jackmcdade** [comment]
Are there js files that are 404ing? It looks like jQuery isn't loading, and it's having a trickle-down effect throughout the JS stack.

**Comment by brettdewoody** [comment]
I thought that too, but I think its due to the error in `ascent.min.js` that the other files don't load. There are no 404s in the dev console network waterfall.

**Comment by jackmcdade** [comment]
I don't have any errors in ascent.min.js myself though, running the same version. There must be something about your site or environment that's breaking it.

**Comment by jackmcdade** [comment]
We set a few javascript variables in the `<head>` area of the admin, can you look at the source there and see if maybe one of them is broken? That could, in theory, cause a chain reaction... It's the only idea i've got!

**Comment by brettdewoody** [comment]
Here are the vars set in the header:

    <script>
      var transliterate = "";
  </script>
  <script>
      var content_type = "md";
  </script>

Looking at where the error is pointing to, something looks weird about this object. The quote styles change from `"` to `'`, and there's a rogue `"` within the `closeWith` property:
    
    {
      id:"link",
      name:"Link",
      key:"L",
      openWith:'"',
      closeWith:'([![Title]!])":[![Link:!:http://]!]',
      placeHolder:"Your text to link here..."
    }

**Comment by jackmcdade** [comment]
Bingo! Where is that coming from? Is that Redactor?

**Comment by brettdewoody** [comment]
Seems like it, because the Redactor fields don't fully load.

**Comment by jackmcdade** [comment]
Did you customize the redactor settings at all?

**Comment by brettdewoody** [comment]
No changes in `/_config/bundles/redactor/redactor.yaml` from what's in the Statamic download. Settings in the fieldtype config are `type: redactor` and a `image_dir`.

**Comment by jackmcdade** [comment]
Can you do a project search + find and see where that closeWith is coming from?

**Comment by brettdewoody** [comment]
Looks like it's only present in `ascent.min.js`

**Comment by brettdewoody** [comment]
Any other ideas on where to look? Something to do with the `link` button in Redactor but I can't find where or how that would have been messed up.

**Comment by brettdewoody** [comment]
@jackmcdade The issue went away for a short time, but reappeared on my next login. Between those 2 visits I believe the content was wiped by me, then reinserted by the client. Could that mean the issue is caused by some of the content? And not a redactor setting?

**Comment by jasonvarga** [comment]
Not to derail this, but this repo is for Statamic v2 issues. Better off shooting us an email in the future for v1.

**Comment by brettdewoody** [comment]
Sure thing. Didn't see a place for posting v1 issues other than the Slack channel but it seemed a bit vacant.

**Comment by brettdewoody** [comment]
@jackmcdade, @jasonvarga - can you tell me where ascent.min.js is created, or when? Is it using dynamic vars created elsewhere? Or recompile on some change? Need to resolve this as the client has an important deadline with traffic being directed to the site coming up soon. 

Seems the file is ok sometimes (after I revert content), then broken at other times due to the invalid token (when the client adds some content).

**Comment by jackmcdade** [comment]
It's created in our private build process (with files not included in the build package). Can you send us a zip of the site in its broken site? gentlemen@statamic.com

**Comment by yoannisj** [comment]
@jackmcdade , @brettdewoody was this resolved? I recently updated a Statamic v1 install to 1.8.2 and started running in a very similar (the same?) issue. I am getting a `Statamic is not defined` error (see screenshot), which seems to come from the `ascent.min.js` file, and breaks some of the content fields in the Admin.

There are no 404 js files, and I can not find any other reference to the `Statamic` variable in the admin (publish) template's `<head>` tag. I would guess the ascent.min.js file is faliing to expose the Statamic global.

Maybe there is also a missing js dependency (I can see no reference to jQuery, and `window.jQuery` is `undefined` in the browser's console).

I am not able to debug this, as I don't have access to the ascent theme's source files (i.e. `ascent.js` file). I would be happy to send a copy of the project files, or give access to whoever is able to help. Thanks!
