### ISSUE TITLE
Cannot reorder the pages in CP

### ISSUE THREAD

**Issue by danieljwestman** [statamic/v2-hub#1340]
### Expected behaviour
When creating some new pages I should be able to reorder them. 

### Actual behaviour
The CP breaks down in endless saving loop

### Steps to reproduce
1.  Create 3 new pages
2.  Move 2 of the new pages into the third one
3.  Hit Save changes
4. Saving saving saving.... Nothing happens. error in log.
5. Works again if cache is cleared (please clear:cache)

### Cache settings
`stache_always_update: false`

### Server configuration
**Web server:**
Ubuntu, Nginx

**PHP version:**
7.1

**Statamic version:**
2.5.5

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**
Many

### Logs
```
[2017-03-22 08:17:05] prod.ERROR: Statamic\Exceptions\DuplicateIdException: Cannot add [pages/4.web-master/2.en-testsida/1.en-testsida-2/index.md] to Stache repository [pages]. File at [pages/4.web-master/3.en-testsida-2/index.md] already exists in repository [pages] with an ID of [effce952-fbdc-4f86-a1d0-594fee0f0512]. in /var/www/sites/orion-taby/statamic/core/Stache/Drivers/AbstractDriver.php:231
Stack trace:
#0 /var/www/sites/orion-taby/statamic/core/Stache/Updater.php(356): Statamic\Stache\Drivers\AbstractDriver->ensureUniqueId(Object(Statamic\Data\Pages\Page))
#1 /var/www/sites/orion-taby/statamic/core/Stache/Updater.php(334): Statamic\Stache\Updater->ensureUniqueId(Object(Statamic\Data\Pages\Page))
#2 /var/www/sites/orion-taby/statamic/core/Stache/Updater.php(249): Statamic\Stache\Updater->ensureId(Object(Statamic\Data\Pages\Page))
#3 /var/www/sites/orion-taby/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(135): Statamic\Stache\Updater->Statamic\Stache\{closure}(Array, 'pages/4.web-mas...')
#4 /var/www/sites/orion-taby/statamic/core/Stache/Updater.php(260): Illuminate\Support\Collection->each(Object(Closure))
#5 /var/www/sites/orion-taby/statamic/core/Stache/Updater.php(144): Statamic\Stache\Updater->updateItems(Object(Illuminate\Support\Collection))
#6 /var/www/sites/orion-taby/statamic/core/Stache/Updater.php(109): Statamic\Stache\Updater->updateDefault()
#7 /var/www/sites/orion-taby/statamic/core/Stache/UpdateManager.php(55): Statamic\Stache\Updater->update()
#8 /var/www/sites/orion-taby/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(135): Statamic\Stache\UpdateManager->Statamic\Stache\{closure}(Object(Statamic\Stache\Drivers\PagesDriver), 'pages')
#9 /var/www/sites/orion-taby/statamic/core/Stache/UpdateManager.php(63): Illuminate\Support\Collection->each(Object(Closure))
#10 /var/www/sites/orion-taby/statamic/core/Stache/Manager.php(76): Statamic\Stache\UpdateManager->update()
...
```

**Comment by Rias500** [comment]
I've been running into this sometimes too, but I can't get it to reproduce consistently

**Comment by benjamin** [comment]
I'm getting this consistently in production, and it pretty much makes the CP unusable for reordering pages. 

I get the same exception in my logs, and the CP "hangs" during saving. However the pages on disk do actually get reordered and if I clear the stache the changes are reflected.

@jasonvarga is there anything more I can do/provide to help you debug this?

**Comment by danieljwestman** [comment]
Same here, I still have this issue. The reorder functionality isn't something you should use and haven't been for quite some time now (posted this issue in march).

**Comment by jasonvarga** [comment]
`statamic/core/Http/Controllers/PagesController.php` line 160

Change `Stache::update();` to `Stache::clear();`

**Comment by noendservers** [comment]
I'll try..

**Comment by danieljwestman** [comment]
I'll try

**Comment by bialousz** [comment]
Hi. I was getting `[2018-10-01 13:46:15] production.ERROR: Cannot add [pages/***] to Stache repository [pages]. File at [pages/***] already exists in repository [pages] with an ID of [6e5287a8-bd9a-47c0-a4fe-804cc82578a3].` while trying to reorder page. When I changed `statamic/core/Http/Controllers/PagesController.php` how 
@jasonvarga described reordering works correctly, but now when loading pages after reodering them I get never ending "Loading" circle and following Error `production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum execution time of 30 seconds exceeded' in ***/statamic/vendor/danielstjules/stringy/src/Stringy.php:65`. Did you have solution for this problem?
