### ISSUE TITLE
Cannot include globals in data content

### ISSUE THREAD

**Issue by danieljwestman** [statamic/v2-hub#1341]
### Expected behaviour
I should be able to write a global/variable tag in the page (data) content.

### Actual behaviour
Outputs something like `callback_blocks_83127ffa68116d184dc5c957ee55eeb3`

### Steps to reproduce
1.  Create or edit a page
2.  Add content like "Hi there, this is a global {{ my_global_set.name }}"
2.  Save
3.  View the page and be disappointed

### Server configuration
**Web server:**
Ubuntu, Nginx

**PHP version:**
7.1

**Statamic version:**
2.5.5

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**
Many

### Logs
No errors, but strange outputs like `callback_blocks_83127ffa68116d184dc5c957ee55eeb3`

**Comment by Rias500** [comment]
It works if you use `{{ my_global_set.name | markdown }}` to parse it to markdown. Although it would be a lot nicer to just be able to to `{{ my_global_set.name }}`

**Comment by danieljwestman** [comment]
Would be great if a fix is coming up. I pointed out this problem very long ago, before this issue was posted.

**Comment by jackmcdade** [comment]
I can't recreate this, it works fine for me. What page/content are you referring to? Page? Entry? Taxonomy? Maybe it's something that granular?

**Comment by danieljwestman** [comment]
It’s on a page

**Comment by jasonvarga** [comment]
Works here too. Can you include more details?

- The global filename and its contents
- The content filename and its contents
- Which content field you are trying to use the global inside
- Your template
