### ISSUE TITLE
[FR] Ability to change avatar source

### ISSUE THREAD

**Issue by chrisburton** [statamic/v2-hub#1342]
<img src="https://d3uepj124s5rcx.cloudfront.net/items/1m3e2k180h2N2J2V2s0B/Screen%20Shot%202017-03-22%20at%2012.53.19%20PM.jpg" />

### Use case

Statamic uses Gravatar for your account photo in the Control Panel by default. It would be nice for those of us using oauth to have the provider's avatar showing.

**Comment by OwenMelbz** [comment]
Was just looking for this functionality! :D

**Comment by jackmcdade** [comment]
We added an option to use the user's initials as an alt a while back. Should do the trick 👍
