### ISSUE TITLE
Exception thrown when uploading image in cp (win)

### ISSUE THREAD

**Issue by idonix** [statamic/v2-hub#1344]
### Expected behaviour
Image uploaded to Assets

### Actual behaviour
Exception thrown (either from page fieldset asset control, or from assets upload - although it seems different exceptoions are throw in each case - see attached logs)

### Steps to reproduce
1.  Open cp
2.  Select content... assets
3.  Hit upload button, and select a file from local file system

### Server configuration
**Operating system**: Win 10

**Web server:** IIS10

**PHP version:** 7

**Statamic version:** 2.5.7

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:** Marbles Cookie Consent, Marbles Sitemap, Recaptcha

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Add those logs here
```

[statamic-2017-03-23_assets.log.txt](https://github.com/statamic/v2-hub/files/865775/statamic-2017-03-23_assets.log.txt)
[statamic-2017-03-23_pages.log.txt](https://github.com/statamic/v2-hub/files/865774/statamic-2017-03-23_pages.log.txt)

**Comment by rrelmy** [comment]
That seems to be an issue with IIS+PHP, I have no problems uploading assets with my Windows 10, Caddy, PHP 7 setup.

I don't know much about IIS and PHP setups but I heard a lot of problems regarding file permission issues.

**Comment by idonix** [comment]
Hmm. Obviously IIS related an environment issue then. I have the issue on both dev (as outlined above) and on production (an Azure app service, so IIS again). However I don't <think> it's a permissions issue - I just double checked and the worker process account (IIS_IUSRS) has modify permissions to my root assets folder.

**Comment by jasonvarga** [comment]
Closing this because its a bit outdated (so it may be fixed) and seems to be a bit of an edge case. From what I see, it may still be a permissions issue. If you're still running into this issue, please feel free to comment.
