### ISSUE TITLE
Form fieldtype loads all submissions

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1346]
### Expected behaviour
Form fieldtype loads quickly

### Actual behaviour
When you have a lot of submissions the form fieldtype is slow because it loads all the submissions.

### Steps to reproduce
1.  Put a form fieldtype in an addon's settings
2. Have lots of submissions
3. Load the addon settings page

**Comment by danielfowler** [comment]
So would this also affect saving a page in CP, even if that page's fieldset doesn't have a form fieldtype in it?

**Comment by edalzell** [comment]
Maaaaaaybe? Saving could just be a cache issue as it has to update the cache (which has > 1000 entries in it).

Easiest way to confirm that is to remove the submissions and see if that speeds up the saving.
