### ISSUE TITLE
[FR] Ability to customize User listing columns in CP

### ISSUE THREAD

**Issue by chrisburton** [statamic/v2-hub#1349]
It appears you cannot customize the Users page fields in the Control Panel. In my case, I am using OAuth where name and email are not relevant to my needs. I would like the ability to add in a user's avatar, profile url, data created, etc. 

<img src="http://cl.ly/3I2Y013A0h1F/Screen%20Shot%202017-03-23%20at%2010.50.26%20PM.jpg" />

### Update:
Providing more clarification of what I'm looking to do.

<img src="http://cl.ly/26322q2w3D0t/Screen%20Shot%202017-03-24%20at%202.39.21%20PM.jpg" />

**Comment by steveallinson** [comment]
Has this been added yet or is it coming in the next release?

**Comment by jackmcdade** [comment]
We don't close the ticket until it's been released. Check out the docs on customizing listing columns here: <https://docs.statamic.com/control-panel#customizing-listing-columns>

**Comment by jackmcdade** [comment]
It’s ALREADY released. In 2.9.0 I believe. Same process as the link I posted, just do it on the user settings yaml file.
