### ISSUE TITLE
Change asset path links when assets are moved on file system

### ISSUE THREAD

**Issue by subpixelch** [statamic/v2-hub#1350]
Would be great if we could move around assets on the file system (p.e. move into a sub folder) and the correspondenting links in the md-files get updated to that new path...

index.md:
```
img:
  - /asset/img.jpg
```

move `asset/img.jpg` to `asset/new_subfolder/img.jpg` in the assets manager.

Update path in index.md:

```
img:
  - /asset/new_subfolder/img.jpg
```

Maybe it's necessary to make filesnames of assets unique on upload automaticaly to achieve this...

Statamic 2.5+

**Comment by jackmcdade** [comment]
It's not possible because we don't track the files. It would have been possible with the ID based method, but that caused another whole set of UC issues.
