### ISSUE TITLE
Allow capitalized file extensions in assets

### ISSUE THREAD

**Issue by than** [statamic/v2-hub#1351]
### Expected behaviour
I should be able to upload images with a capitalized .JPG file extension.

### Actual behaviour
CP errors saying .JPG does not actually appear to be an image.

![](http://than.to/2dPZ.png)

### Steps to reproduce
1.  Create an S3 assets container
2.  Attempt to upload a file with ".JPG"
3.  💣

### Server configuration
**Operating system**:

**Web server:**
The usual

**PHP version:**
7

**Statamic version:**
Latest - 2.5.7

**Updated from an older Statamic or fresh install:**

**List of installed addons:**

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Add those logs here
```

**Comment by jackmcdade** [comment]
This will get lowercased automatically on upload now. Problem solved in a round about way :)
