### ISSUE TITLE
FR: Add {{ count }} variable to Grid tags

### ISSUE THREAD

**Issue by than** [statamic/v2-hub#1352]
### Expected behaviour
Given a grid fieldtype, the template tags count return a count variable similar to Assets or terms.

i.e. grid with 3 rows
```
{{ grid }}
  {{ if count == 3 }}
    The count is 3.
  {{ /if }}
{{ grid }}
```

### Actual behaviour
Nothing :(

### Server configuration
**Operating system**:

**Web server:**

**PHP version:**

**Statamic version:**
2.5.7

**Comment by edalzell** [comment]
Than, is there not an `index` var in there?

**Comment by than** [comment]
There is, but I want the count. `{{ if grid | count == 1 }}` worked for my specific application, but it seems clunkier?

**Comment by jasonvarga** [comment]
Do you want the number of the iteration? or the total number of items in the grid?

**Comment by than** [comment]
Total number of items/rows in the grid.

**Comment by than** [comment]
Use case for me here is that I want to have a grid field available to power a carousel (I know) but if the client only puts in 1 row/slide, I want to efficiently pull out the classes and other things that boot up the carousel script.

**Comment by rrelmy** [comment]
Couldn't you use `{{ grid | length }}`?

**Comment by jasonvarga** [comment]
As @rrelmy suggested, you can do something like this:

```
{{ if (grid|length) == 1 }}
  the grid has one item.
{{ /if }}
```
