### ISSUE TITLE
Glide outputs urls with only one slash when using s3 and cached image manipulations

### ISSUE THREAD

**Issue by than** [statamic/v2-hub#1354]
### Expected behaviour
I set up an S3-backed assets container and set up a glide tag to output a cropped image.

`{{ glide:image width="2000" height="1200" fit="crop_focal" }}`

This works.

Once I turn on `image_manipulation_cached: true`, a url is being passed somewhere along the glide path that is missing a slash after the protocol.

![](http://than.to/Q0Tu.png)

### Server configuration
**Operating system**:

**Web server:**

**PHP version:**

**Statamic version:**
2.5.7

**Updated from an older Statamic or fresh install:**

**List of installed addons:**

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Add those logs here
```

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
