### ISSUE TITLE
Form submission times are incorrect in the CP

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1359]
Form submissions are saved with a timestamp, that timestamp isn't correctly displayed in the CV, it's always a seemingly random hour, followed by 03 as the minutes,

i.e. for these submissions

<img width="147" alt="screen shot 2017-03-29 at 14 49 59" src="https://cloud.githubusercontent.com/assets/7669885/24459566/c73000b8-1493-11e7-8c90-cb2caa18d0b2.png">

Their timestamps should be converted to i.e. `12:14:18`, `12:24:18`, `12:24:35` etc. but they are in fact all `13:03` in the CP.

Setup:
OS X, MAMP, Apache, PHP 7.1, Statamic 2.5.7

**Comment by jasonvarga** [comment]
Let's see your formset yaml file, and your site/setting/cp.yaml file.

**Comment by dannyuk1982** [comment]
It's doing it on all forms, here is one formset:

`prize-draw.yaml`

```title: Prize draw
honeypot: f_company
fields:
  f_first_name:
    display: First name
    validate: required|min:1
  f_last_name:
    display: Last name
    validate: required|min:1
  f_email:
    display: Email
    validate: required|email
  f_date_of_birth:
    display: Date of birth
    validate: required|date_format:d/m/Y
  f_accepted:
    display: Accepted
    validate: required
  f_branch:
    display: Branch
    validate: required|min:1
columns:
  - f_first_name
  - f_last_name
  - f_email
  - f_date_of_birth
  - f_branch
```

`site/setting/cp.yaml file`:

```start_page: dashboard
date_format: Y/n/d
pagination_size: 25
widgets:
  -
    type: collection
    collection: offer
    limit: 5
    width: 50
  -
    type: collection
    collection: blog
    limit: 5
    width: 50
  -
    type: collection
    collection: restaurant
    limit: 5
    width: 50
  -
    type: collection
    collection: menu-items
    limit: 5
    width: 50
  -
    type: PowerTools
    width: 100
```

**Comment by jasonvarga** [comment]
Actually...

![](http://mrwgifs.com/wp-content/uploads/2013/06/Alison-Brie-Its-Not-You-its-Me-On-Community.gif)

Fixed for next release. We were hardcoding the minutes. But it wasn't minutes. It was the month.

The patch, if you want to fix it now is this.
![image](https://cloud.githubusercontent.com/assets/105211/24461406/ff1df6d0-146e-11e7-896a-2f474c198524.png)

 It goes in `statamic/core/Forms/Submission.php`
`$this->form()->dateFormat()` for your copy/pasting pleasure.

**Comment by dannyuk1982** [comment]
I have done that many a time with PHP date params, they are confusing! Cheers :)

**Comment by dannyuk1982** [comment]
This is a better fix, as it keeps the time in, can you please implement this instead?

```$this->formset()->get('date_format', 'Y-m-d H:i')```

**Comment by jasonvarga** [comment]
Put the time in your `date_format`

**Comment by dannyuk1982** [comment]
oh, in site settings - ok... what else will that affect?

**Comment by jasonvarga** [comment]
You can put it in your formset though.

**Comment by dannyuk1982** [comment]
Ah cool, and this is the point where I moan about I couldn't see that in the docs :)

**Comment by jasonvarga** [comment]
You can moan some more because it's not in the CP either. ;)

**Comment by dannyuk1982** [comment]
A double moan with whipped cream coming right up!

**Comment by jasonvarga** [comment]
![](https://media.giphy.com/media/12QzT6DbZT1P0I/giphy.gif)
