### ISSUE TITLE
Forms can't reverse sort by date column

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#1362]
### Expected behaviour
Forms can be resorted by clicking the column titles. By clicking the active column title again, it reverses the sorted data. This should also be possible for the date column.

### Actual behaviour
The date column only sorts in one direction.

### Steps to reproduce
1.  Click the `date` column title
2. Nothing changes

**Comment by lukeagsmith** [comment]
Just bumped into this myself.

Still and issue in v2.6.1

**Comment by beeldr** [comment]
Same here on 2.6.8

**Comment by bgarrant** [comment]
Please fix this one.  I have a client that is growing form submissions fast.  Like 200 already and not having recent ones on top is tough.

**Comment by bgarrant** [comment]
Since 2017 this one is still around?

**Comment by lukeagsmith** [comment]
+1
