### ISSUE TITLE
Requesting a better UI for List fieldset

### ISSUE THREAD

**Issue by rockethouse** [statamic/v2-hub#1363]
### Expected behaviour
Better UI - the cross for the first line is pushed onto a new line so it looks like an error. It's also not very apparent that you can re-order the items. This is minor but would be nice to see fixed at some stage, not urgent.

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/5466694/24539342/a5d791e4-1635-11e7-9af8-b55d1ec75bae.png)

**Comment by dannyuk1982** [comment]
I agree it is not obvious how to add (press enter) and that you can reorder. A work around is to add `instructions` that tell the user how to do both of these.

To have the x not on another line, if it's inserted inline this is not simple to fix. A work around would be to add some right padding, and have this absolutely positioned say 10px from the top right of the item.
