### ISSUE TITLE
Deleting Collections causes Fatal Error

### ISSUE THREAD

**Issue by iantaylor91** [statamic/v2-hub#1364]
### Expected behaviour
I deleted the two collections accompanied with the Redwood theme using the control panel, I expected it to warn of linked content or optionally delete all linked content

### Actual behaviour
After deleting the "blog" and "things" collections using the CP, every single page of the CP is showing the same error:

![image](https://cloud.githubusercontent.com/assets/16960672/24544914/0ba0afa8-15fd-11e7-9aac-e97d102af101.png)

### Steps to reproduce
1.  Fresh install Statamic 2.5.7 on Windows 10 (all PHP extensions installed and enabled, including recommended)
2.  Clone Redwood theme to a new theme. 
3.  Change all references to redwood to new theme name
4.  Using the Control Panel delete the collections.

### Server configuration
**Operating system**: Windows 10 Home Edition

**Web server:** Apache

**PHP version:** 5.6.30

**Statamic version:** 2.5.7

**Updated from an older Statamic or fresh install:** Fresh Install

**List of installed addons:** None

### Side note
Partly my own fault for not immediately version controlling Statamic, but this issue is worrying as I plan to use Statamic for the majority of clients in the future.

**Comment by jasonvarga** [comment]
I cannot replicate this when using the steps you've described. Any more details?

**Comment by jackmcdade** [comment]
Since we're unable to recreate this and haven't received any more info, I'm going to close this issue. If you or anyone else has more information leading to the identification and elimination of this oddity, please reopen with said knowledge!
