### ISSUE TITLE
FR: Form submissions mass delete

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1365]
Form submissions should have checkboxes and a delete, like collections do.

Use case: on the site I am building now the form is used to collect entries for a monthly prize draw, there are loads each month and it takes forever to delete them all from the control panel one at a time.

Another use case: to collect CVs for vacancies, after the job has gone, many of the submissions need to be deleted.

Having a checkbox/delete button like entries do, would solve this problem.

**Comment by jackmcdade** [comment]
Closing in favor of #1748, which is connected to other GDPR features.
