### ISSUE TITLE
Creating an Asset Container via control panel does not save correctly and related display issues

### ISSUE THREAD

**Issue by jasonbell** [statamic/v2-hub#1368]
Most likely related to #1244, but experienced through the UI.

### Expected behaviour
Following prompts to create an Asset container for S3, the validation of keys works, and content list is properly determined. When pressing Next Step from the Fieldset settings, I expect to redirect to the properly configured Asset Container form at `/cp/configure/content/assets/container_name`.

### Actual behaviour
The Asset Container form loads without the Amazon S3 information and driver selected as “Local”. The Asset Container file reads…

```
key: XXXXXXXXXXXXX
secret: XXXXXXXXXXXXX
bucket: XXXXXXXXXXXXX
region: us-east-1
title: S3 Bucket
```
No driver setting is made.
The Assets configuration screen errors at `/cp/configure/content/assets`

### Steps to reproduce
1.  Configure > Content > Assets > New Asset Container
2.  Follow on screen prompts using S3 credentials
3.  Click “Next Step” on Fieldset settings
4. Observe above description in UI and file system

### Attempted fixes
-  Manually adding `driver: s3` to the config file appears to fix, then just waiting out the slow load noted in #1271.
- If a `path` parameter is in the config file, then `/cp/configure/content/assets` doesn’t load
- If a `path` parameter is in the config file,then `/cp/assets/browse/CONTAINER` doesn’t load (unless it’s the slowness issue)
- Removing `path` allows both of those pages to load

### Server configuration
**Operating system**:
OS X 10.11.6

**Web server:**
Apache 2.2 (MAMP)

**PHP version:**
PHP 5.6.28 (MAMP)

**Statamic version:**
Statamic 2.5.7

**Updated from an older Statamic or fresh install:**
Fresh install

**List of installed addons:**
none

### Logs
Here’s the top portion form the log...
```
[2017-04-03 18:25:10] production.ERROR: exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(//.DocumentRevisions-V100): failed to open dir: Permission denied' in /statamic/statamic/vendor/league/flysystem/src/Adapter/Local.php:267
Stack trace:
#0 [internal function]: RecursiveDirectoryIterator->__construct('//.DocumentRevi...', 4096)
#1 /statamic/statamic/vendor/league/flysystem/src/Adapter/Local.php(267): RecursiveDirectoryIterator->getChildren()
#2 /statamic/statamic/vendor/league/flysystem/src/Filesystem.php(270): League\Flysystem\Adapter\Local->listContents('', true)
#3 /statamic/statamic/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(227): League\Flysystem\Filesystem->listContents('', true)
#4 /statamic/statamic/core/Filesystem/FolderAccessor.php(79): Illuminate\Filesystem\FilesystemAdapter->files('', true)
#5 /statamic/statamic/core/Assets/AssetContainer.php(289): Statamic\Filesystem\FolderAccessor->getFiles(NULL, true)
#6 /statamic/statamic/core/Assets/AssetContainer.php(328): Statamic\Assets\AssetContainer->files(NULL, false)
#7 /statamic/statamic/core/Http/Controllers/AssetContainersController.php(37): Statamic\Assets\AssetContainer->assets()
#8 [internal function]: Statamic\Http\Controllers\AssetContainersController->get()
```

**Comment by jasonbell** [comment]
Just updated to 2.5.9 and this issue persists when creating Asset containers using S3 as the driver. Form reloads with driver set back to local.

As it stands, none of the workarounds are effective enough for production.

**Comment by jasonvarga** [comment]
Fixed for next release.

Just checking - does creating it through the CLI work using `php please make:asset-container` ?

**Comment by jasonbell** [comment]
Just tested via CLI and yes, it creates it—though I notice the `title` is missing.
