### ISSUE TITLE
FR: Provide a way for addons to have code when they're loaded

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1369]
Right now, I use a ServiceProvider to do init-y things in my addon, like this:
```
        // gotta add myself to the CSRF exclude list so Stripe can send the webhooks
        $excludes = Config::get('system.csrf_exclude', []);

        $excludes[] = $this->actionUrl('webhook');
        Config::set('system.csrf_exclude', array_unique($excludes));
```

Apparently this is not how Service Providers are supposed to be used.

Can you make a way, maybe an event?, that we can use to do similar things?

**Comment by DavidStrada** [comment]
A suggestion could be once the plugin get's activated fire an event `cp.plugin_activated` or along with those lines. 

As a way to add custom logic that get's initialize as soon as the plugin is installed and ready to performed it's actions.

**Comment by jasonvarga** [comment]
Service Provider `boot` method is fine and dandy.
