### ISSUE TITLE
Assets folder not loading, and upload not possible

### ISSUE THREAD

**Issue by localmedia** [statamic/v2-hub#1370]
### Expected behaviour
When clicking "Add Asset" button in a section like e.g. the Cover Slider, the images from the Main Assets should load.
When clicking the "Upload" Button, the selected image should be uploaded.

### Actual behaviour
When clicking "Add Asset" button in a section like e.g. the Cover Slider, the loading graphic spins endlessly.
Uploads fails with the message "Internal Server Error"

### Steps to reproduce
1.  Update from a pre- 2.5.0 version to the latest 
2.  Add the Main Assets Container
3.  Try to add assets or upload images on a page

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**PHP version:** 5.6

**Statamic version:** 2.5.7

**Updated from an older Statamic or fresh install:** Happened after update

**List of installed addons:** -

### Logs
If any logs (browser, server, or Statamic) are appropriate...
We get this error in the log files:

[2017-04-03 11:58:26] production.ERROR: Error inserting [e8c9db37-6ddf-4364-b8a7-7fcbe50f741f] into search index.  
[2017-04-03 11:58:26] production.ERROR: exception 'ZendSearch\Lucene\Exception\RuntimeException' with message 'Index is under processing now' in /home/httpd/vhosts/die-naerrischen-alten.ch/httpdocs/statamic/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Index.php:137

**Comment by jasonvarga** [comment]
Did you ever get this worked out?

**Comment by jasonvarga** [comment]
The error in the log is related to zend, which has been removed.
