### ISSUE TITLE
Taxonomies are not translated

### ISSUE THREAD

**Issue by joaojoyce** [statamic/v2-hub#1371]
Hi,

I'm using Stamic v. 2.5.7

### Expected behaviour
I'm trying to show all entries in a taxonomy by doing the following:

```
        {{taxonomy:clinical_case_type  show="all" }}
            <div>
                <h3>{{ title }}</h3>
                <a href="{{ url }}" >View</a>
            </div>
        {{/taxonomy:clinical_case_type}}
```

But my content shows in the default locale.
To try and fix this I have created a new tag taxonomy_switch to force the translation:

```
    public function index()
    {
        $url       = $this->get('url', URL::getCurrent());
        $lang      = $this->get('lang',site_locale());
        $term      = $this->get('term','url');

        $uri = URL::getDefaultUri(site_locale(), $url);
        return Content::whereUri($uri)->in($lang)->get($term);
    }
```

But I still get some errors because sometimes I can't get the URI.

### Actual behaviour
I believe the code bellow should work fine! 
But if there is some custom tag as workaround I would use it.

```
        {{taxonomy:clinical_case_type  show="all" }}
            <div>
                <h3>{{ title }}</h3>
                <a href="{{ url }}" >View</a>
            </div>
        {{/taxonomy:clinical_case_type}}
```

**Comment by jasonvarga** [comment]
How have you translated your taxonomy term?

**Comment by joaojoyce** [comment]
We have:
1. Created a Taxonomy in the backoffice
2. Attributed a simple fieldset (title text and template). 
3. Created new terms and translated them.

When we try to do:
```
        {{taxonomy:clinical_case_type  show="all" }}
            <div>
                <h3>{{ title }}</h3>
                <a href="{{ url }}" >View</a>
            </div>
        {{/taxonomy:clinical_case_type}}

```

Neither of the terms get translated.

To fix it we have tried to build custom tags. Should this functionality work out of the box?

**Comment by jasonvarga** [comment]
Fixed for next release. Good catch!

Here's the patch if you want to apply it right now.

![image](https://cloud.githubusercontent.com/assets/105211/25019977/a699c834-205a-11e7-9c66-0616226498b1.png)

```
$this->terms = $this->terms->localize($this->get('locale', site_locale()));
```
