### ISSUE TITLE
Assets Container don't show custom fieldset

### ISSUE THREAD

**Issue by patrikkernke** [statamic/v2-hub#1372]
### Expected behaviour
When creating an assets container with setting a fieldset, the added fields should show up when editing an asset.

### Actual behaviour
Only the default fields are visible.

### Steps to reproduce
1.  Creating assets container and set the fieldset
2. upload an asset
3.  click on edit asset

Maybe important: Default locale is de (German).

### Server Details

**Operating System**:
mac OS Sierra 10.12.4

**Web Server:**
nginx (Laravel Valet)

**PHP Version:**
php 7.1

**Statamic Version:**
2.5.7

**Updated from an older Statamic or fresh install:**
Yes

**List of installed addons:**
No Addon

**Comment by jasonvarga** [comment]
Fixed for next release.

**Comment by patrikkernke** [comment]
Do you can say when the release is? This week? I have to publish the website for my client.

**Comment by jasonvarga** [comment]
Do you have multiple asset containers? If not, it still works right now if you name it asset.yaml

**Comment by patrikkernke** [comment]
I have five asset containers for different kind of assets, so I can call them directly and display them at the right place. I need them for a clear structure and they need individual custom fields (hyperlinks, company, address ... .

**Comment by jasonvarga** [comment]
Release is this week but if you can't wait, update the `fieldset` method in `statamic/core/Assets/AssetContainer.php` to this:

```
    public function fieldset($fieldset = null)
    {
        if (is_null($fieldset)) {
            if (! $fieldset = array_get($this->data, 'fieldset')) {
                return null;
            }
            return Fieldset::get($fieldset);
        }
        if ($fieldset === false) {
            $fieldset = null;
        }
        $this->data['fieldset'] = $fieldset;
    }
```

**Comment by patrikkernke** [comment]
Thank you very much for your quick help! Your support is the best!
