### ISSUE TITLE
Nav sub-items don't get 'active' if they have query params

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1375]
### Expected behaviour
If I have a sub-items under my main nav item, when they are clicked on, they should look 'active'

### Actual behaviour
They do not look active

### Steps to reproduce
1. Have Nav sub-items w/ query strings. Mine are `http://v2.dev/cp/addons/akismet/queue?form=contact`. The route is:
```
  # Spam Queue
  /queue:
    uses: queue
    as: queue
```
2. Click on it

### Server Details
Statamic 2.5.5

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.

**Comment by edalzell** [comment]
![image 1](https://user-images.githubusercontent.com/6069653/40986339-d03fd366-689a-11e8-83b3-45c0a34b0da9.png)

Still exists on 2.9.6, please reopen @jasonvarga

**Comment by jasonvarga** [comment]
Should *now* be fixed for next release.
