### ISSUE TITLE
FR: Don't cache white screen(s) of death

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/v2-hub#1382]
### Expected behaviour
White screen(s) of death and other internal server errors 5xx should not be cached in full measure (file caching).

### Actual behaviour
White screen(s) of death and other internal server errors 5xx are cached in full measure (file caching).

**Comment by jasonvarga** [comment]
We only cache `200` responses.

**Comment by jasonvarga** [comment]
As of next release, we also won't cache empty (but "successful") responses.
