### ISSUE TITLE
FR: Skip Choose Page type if only one available

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/v2-hub#1383]
### Expected behaviour
It would be nice if you did not have to chose the page type when there is only one available.

### Actual behaviour
You have to choose the page type if there is only one available.

<img width="425" alt="screen shot 2017-04-10 at 6 40 57 pm" src="https://cloud.githubusercontent.com/assets/1778271/24909842/a79aff6e-1e93-11e7-9eff-49c55d267522.png">

**Comment by jackmcdade** [comment]
It works as desired now.
