### ISSUE TITLE
An optional "expires" date meta field for entries

### ISSUE THREAD

**Issue by beckysoll** [statamic/v2-hub#1385]
### Requested behaviour
It would be great to have the option to set a date by which entries should become un-published, or expire

### Actual behaviour
Not currently possible with creating a filter or posessing a magic wand and a lot of time

### Use Case
I can see a lot of use cases, but at the moment mine is to have an announcement area that shows up if there is at least one "announcement" (entry) that is a. published AND b. either has no expiration date, or the expiration date is in the future. And, to be able to do this and still index just the results, use if first and if last, etc. etc.

**Comment by jackmcdade** [comment]
We plan to add this in v3 :)
