### ISSUE TITLE
Using taxonomy="false" in a collection tag still tries to filter by taxonomy.

### ISSUE THREAD

**Issue by mariovass** [statamic/v2-hub#1388]
Our blog & Careers listings are all broken due to the update in 2.5.8. Now we get the famous "Whoops, looks like something went wrong."

[statamic-2017-04-13.txt](https://github.com/statamic/v2-hub/files/918821/statamic-2017-04-13.txt)

Error Log.

**Comment by colinmeinke** [comment]
Not sure if this helps with context - looking back it seems the upgrade to 2.5.3 on the 10th Feb removed all of the taxonomy files. And just left us with a root file for each type. Pretty sure that shouldn't have happened? Mario has added these tags back manually following the structure from another new site running 2.5.8, but we are still getting the error above.

Before 2.5.3 upgrade:

![](https://dl.dropboxusercontent.com/u/474775/statamic-before.png)

After 2.5.3 upgrade:

![](https://dl.dropboxusercontent.com/u/474775/statamic-after.png)

**Comment by colinmeinke** [comment]
Okay I think I've found the issue. We have a partial, and that outputs a list of jobs.

```
{{ collection:jobs sort="date:asc" taxonomy="{ t }" scope="job" }}
  ...
{{ /collection:jobs }}
```

Where `t` is either `true` or `false`. 2.5.8 now throws when passed `false`. Seems to work okay if always set to `true` tbh - if there isn't a taxonomy term in the url it displays all by default.

**Comment by jasonvarga** [comment]
We made some changes to the collection tag in the last release. Didn't really think about people passing `false` into the `taxonomy` parameter.

The following fixes it. `taxonomy="false"` will act as though you don't have the parameter there at all. That's what you want, right?

`statamic/bundles/Collection/CollectionTags.php`

![image](https://cloud.githubusercontent.com/assets/105211/25005534/4fb32a52-2027-11e7-96d6-533c5c98bd6b.png)

...and here's the raw text for copy/pasting:

```
        if ($this->get('taxonomy') === 'false') {
            return false;
        } elseif ($this->get('taxonomy') === 'true') {
            $taxonomyCollection = $this->getTaxonomyCollectionFromUri();
        } else {
            $taxonomyCollection = $this->getTaxonomyCollectionFromParams($collection);
        }
```

Regarding the taxonomy term files being removed... Did they have anything inside them?

**Comment by colinmeinke** [comment]
Cool, thanks. Yes they all had a title and an id:

![](https://dl.dropboxusercontent.com/u/474775/statamic-taxonomy.png)

**Comment by jasonvarga** [comment]
Yep. The migrator handles those. They can be removed.

**Comment by colinmeinke** [comment]
Okay great, where does that data live now, out of interest? On another new Statamic site it's still adding that tag data into directories within taxonomies.

**Comment by jasonvarga** [comment]
It lives in the content.

```
tags:
  - Enterprise Solutions
  - Another One
```

If you create the taxonomies manually through the CP, it'll create the files. Since 2.5 there's generally no reason to manually create them, though.

https://docs.statamic.com/taxonomies

**Comment by colinmeinke** [comment]
Nice, thanks!
