### ISSUE TITLE
🐞 dates in markdown fields are rendered wrong...

### ISSUE THREAD

**Issue by subpixelch** [statamic/v2-hub#1393]
### Expected behaviour
A list of dates in a markdown-field:

<img width="272" alt="gartnerei_und_mobiles_grun___statamic" src="https://cloud.githubusercontent.com/assets/5087726/25167780/1ac3a722-24e1-11e7-8324-7a5aa2dedfe5.png">

### Actual behaviour

They get rendered wrong:

Preview:

<img width="219" alt="gartnerei_und_mobiles_grun___statamic" src="https://cloud.githubusercontent.com/assets/5087726/25167812/37e553c8-24e1-11e7-91eb-65950a7abfc7.png">

And also wrong in front-end:

<img width="232" alt="gartnerei_und_uberwinterung_von_kubelpflanzen_in_gewachshaus_pratteln" src="https://cloud.githubusercontent.com/assets/5087726/25167839/543350ca-24e1-11e7-8aea-fea8566f1dc7.png">

### Steps to reproduce
1.  Write dates as a list in a markdown field...

### Server Details

**Web Server:** Nginx/Apache

**PHP Version:** 7.1.x

**Statamic Version:** 2.5.8

**Updated from an older Statamic or fresh install:** 2.5.5

**Comment by gmcz** [comment]
I don't think this is a Statamic bug, this is how [PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/), which Statamic uses, handles an unordered list with an ordered list nested inside it. 

Even here on github what you typed is rendered oddly, see:

- 29. April 2017
- 29. April 2017
- 29. April 2017
- 29. April 2017

Here's exactly what I put in the GitHub editor:

```md
- 29. April 2017
- 29. April 2017
- 29. April 2017
- 29. April 2017
```

So, to solve your issue I would suggest you escape the period so markdown knows that you're not trying to create an ordered list inside the unordered list, as here:

- 29\. April 2017
- 29\. April 2017
- 29\. April 2017

and the markdown code to produce that:

```md
- 29\. April 2017
- 29\. April 2017
- 29\. April 2017
```

**Comment by jasonvarga** [comment]
Thanks for the info @gmcz - I have to agree with you here. It's just the way it is.

**Comment by subpixelch** [comment]
Maybe this should be documented in the statamic docs somewhere @jason
