### ISSUE TITLE
Changes to pages do not take effect until cache is manually cleared

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1395]
#### Steps to reproduce
1.  Ensure Static Page Caching is enabled (Caching Type = Cache)
2.  Unpublish a page
3.  Look at the website

#### Expected behaviour
The page should no longer be on the navigation or accessible

#### Actual behaviour
The page _is_ still on the nav and accessible

.

#### Steps to reproduce
1.  Ensure Static Page Caching is enabled (Caching Type = Cache)
2.  Publish a page previously unpublished
3.  Look at the website

#### Expected behaviour
The page should now be on the nav

#### Actual behaviour
The page is _not_ on the nav

.

#### Steps to reproduce
1.  Ensure Static Page Caching is enabled (Caching Type = Cache)
2.  Change the order of pages
3.  Look at the website

#### Expected behaviour
The new order should display in the nav

#### Actual behaviour
The new order does _not_ display in the nav

.

**Statamic Version:**
2.5.8

**Comment by jasonvarga** [comment]
Fixed in 2.5.9

**Comment by dannyuk1982** [comment]
@jasonvarga this is doing this in 2.5.10

**Comment by dannyuk1982** [comment]
@jasonvarga we went over this in Slack, and the workaround was to use `static_caching_invalidation: all` in `caching.yaml` - just trying on a new site though (with that added), and it's requiring a manual cache clear to show/hide pages from the nav when the publish state is changed - happy to provide more details if needed.

`caching.yaml` is:
```stache_always_update: true
static_caching_enabled: true
static_caching_type: cache
static_caching_file_path: static
static_caching_ignore_query_strings: true
static_caching_exclude: [ ]
static_caching_invalidation: all
static_caching_lock_hold_length: 0
```

**Comment by dannyuk1982** [comment]
`static_caching_invalidation: all` probably fixes this
