### ISSUE TITLE
Glide absolute path doesn't use the URL declared in environment yaml

### ISSUE THREAD

**Issue by wuhhh** [statamic/v2-hub#1400]
### Expected behaviour
I am using the new absolute parameter with Glide tags, I thought it would use the URL from my dev environment yaml file, it doesn't.

### Actual behaviour
It used the server host name (or does it come from somewhere else? Not sure). This causes a discrepancy between ```{{ page:permalink }}``` (uses the URL from the env.yaml) and the absolute path from Glide.

### Steps to reproduce
1. Create environment yaml file with custom URL, e.g:
```
  system:
    locales:
      en:
        url: http://my.site
```
2.  Use Glide to output an image path
3.  Observe!

### Server Details

**Operating System**: Ubuntu

**Web Server:** Apache

**PHP Version:** 7.1.4

**Statamic Version:** 2.5.9

**Comment by jasonvarga** [comment]
I can confirm this behavior, but I'd like to know in what situation do you have a different URL in your settings than the URL you're actually browsing.

**Comment by wuhhh** [comment]
I can't remember the exact setup, but I was using ngrok to test the site outside my local network. Putting the ngrok URL in env.yaml worked as expected for {{ page:permalink }} but Glide used the regular (non-ngrok) hostname

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
