### ISSUE TITLE
Redactor stopped working

### ISSUE THREAD

**Issue by danieljwestman** [statamic/v2-hub#1401]
### Expected behaviour
You should be able to make text bold

### Actual behaviour
Nothing happens

### Steps to reproduce
1.  Add the fieldtype Redactor to a fieldset
2.  Create or edit some content with that fieldset
3.  Try to make some text bold in the edit area
4. Check HTML view and see that nothing is added

See attached GIF
![apr 28 2017 10-08 am - edited](https://cloud.githubusercontent.com/assets/20950568/25520804/938d216a-2bfd-11e7-99c8-b0913e3e2a68.gif)

### Notes

This seems to be in the latest Chrome (58.0.3029.81) - auto updated. It worked in the previous version I think.

The latest Redactor (on the example site) is working in the new Chrome. So it's the very old Redactor version in Statamic that is failing!

### Server Details

**Operating System**:
MacOS

**Browser**
Google Chrome 58.0.3029.81

**Web Server:**
MAMP

**PHP Version:**
PHP 7.1

**Statamic Version:**
Statamic 2.5.9

**Updated from an older Statamic or fresh install:**
New (and updated)

**List of installed addons:**
None (and a lot)

### Logs
No errors in the log

**Comment by dannyuk1982** [comment]
To confirm, works fine in Chrome 57 - updating to 58 it no longer works (i.e. as you have described in this issue).

**Comment by dannyuk1982** [comment]
If you select multiple words - it bolds some of them, just not all...

**Comment by subpixelch** [comment]
seems to be fixed in original Redactor https://imperavi.com/redactor/log/

**Comment by jackmcdade** [comment]
@subpixelch That's using Redactor 2, we're on 1 right now because extending 2 was crazy town.

**Comment by danieljwestman** [comment]
@jackmcdade So, can this be fixed without extending Redactor 2. A lot of clients are using the latest Chrome (auto update) and wants to edit their site content...

**Comment by jackmcdade** [comment]
I'll take a look and see if there are any legacy updates.

**Comment by jackmcdade** [comment]
Redactor team said we were SOL, but I found a fix in the Concrete5 community. Huzzah!

<https://github.com/concrete5/concrete5/pull/5425/files>

Will be in the next patch update.

**Comment by dannyuk1982** [comment]
@jackmcdade could you please patch V1 as well with this?
