### ISSUE TITLE
Asset name already in use error on file upload form submission

### ISSUE THREAD

**Issue by colinmeinke** [statamic/v2-hub#1403]
We have a form with a file upload field that has been working fine on production for a year, and still is.

However, locally and on our staging server we get the following error on the submission of this form, even after deleting and re-cloning the site.

```
[2017-05-03 08:50:51] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Cannot use Statamic\API\Asset as Asset because the name is already in use in /path/to/statamic/core/Assets/AssetContainer.php:5
Stack trace:
#0 {main}
```

We are running Statamic 2.5.8 on all systems (also tried upgrading to 2.5.9).

Local: osx php 7.012
Staging: ubuntu php 7.0.8
Production: ubuntu php 7.0.8

**Comment by jasonvarga** [comment]
It's been a while and doesn't appear to be an issue so I'm closing this one. Please let us know if it's still an issue.
