### ISSUE TITLE
Saved S3 assets not persisting when editing entry in CP (2.5.8+)

### ISSUE THREAD

**Issue by jeffmckeand** [statamic/v2-hub#1406]
### Expected behaviour
Previously selected/saved S3 asset(s)<sup>[1](#footnote1)</sup> should appear in asset field when going back to edit an entry in the CP.

### Actual behaviour
Previously selected/saved S3 asset(s) do not persist within the asset field when reopening an entry where they were saved. UI assumes the field is empty and deletes the key:value on CP save.

Note: A rollback to 2.5.7 alleviates the issue.

### Steps to reproduce
1.  Add an S3 asset to an asset field
2.  Save entry
3.  Re-open entry and see asset field is blank, _even though_ the value is saved in the markdown file
4. Save entry and see that the field is assumed to be empty, therefore deleted from the markdown file

### Server Details

**Operating System**: macOS Sierra<sup>[2](#footnote2)</sup>

**Web Server:**: Apache 2.4

**PHP Version:** 7.1.4

**Statamic Version:** Confirmed on 2.5.8 & 2.5.9

**Updated from an older Statamic or fresh install:** update from 2.5.7

**List of installed addons:**
- Google Maps
- Location
- SVG Output
- Taxonomy Slug Filter
- Tel

***
<a name="footnote1">1.</a> Doesn't appear to affect assets stored in a local container.
<a name="footnote2">2.</a> This isn't isolated to my local dev environment. It's also happening on my Forge/DigitalOcean production server running NGINX and PHP 7.1.2.

**Comment by jeffmckeand** [comment]
@jasonvarga FYI, this issue popped back up for me with 2.6.0+  :/

**Comment by jeffmckeand** [comment]
Still an issue in 2.7.0

**Comment by jeffmckeand** [comment]
Interesting that it was "fixed" in 2.5.10, but reappeared in subsequent releases. Any ideas for a temporary fix? I couldn't figure it out from a cursory scan of changes from 2.5.9 to 2.5.10.

**Comment by jeffmckeand** [comment]
Bump 😕

**Comment by jasonvarga** [comment]
What exactly is the issue? I can't replicate any problems. Can you show an example of what gets saved to the file?

**Comment by jeffmckeand** [comment]
Sure. I'll put together a more detailed example later with some screen caps , but here's the fullest explanation of the problem I can give at the moment:

I have a collection with multiple single-asset fields pointing to an S3 asset container. An author goes in and adds an entry with new assets, saves, and the `.md` file is created with correct values for those asset fields. No problem.

However, on certain versions of Statamic (basically anything after 2.5.11), if a user opens one of those entries in the CP, those asset fields are completely blank. The values are stored correctly in the `.md` file, but they don't make it back to the corresponding Vue elements. So if something in another field is changed -- let's say a quick copy update -- and the entry is saved, those asset fields now save as empty because the Vue elements don't have any value assigned to them. Data is essentially erased, and content disappears.

No errors are reported to logs, and there are no errors in the console or Vue developer tools. I'm stumped.

The issue first showed up for me in 2.5.8. Based on the history of this issue, it appears you fixed it in a May release (2.5.10?), but then it reappeared in 2.5.12 and above.

**Comment by jasonvarga** [comment]
Cool.  If you can provide an example of what is saved in the file, that could help. Also, your asset container yaml file (without your credentials).

**Comment by jeffmckeand** [comment]
Of course. Thanks for taking a look at this again. Apologies for being a pest :)

**Comment by jeffmckeand** [comment]
Months later, a potentially facepalm-worthy update:

After taking a break from maintaining the site in question, today I took a look at how the Asset field was saving data to each entry's MD file. At some point, it seems Statamic's preferred format for S3 URLs changed from `https://s3.amazonaws.com/bucketname/...` to `https://bucketname.s3.amazonaws.com/...`. Now that all of those references are fixed in my site content, everything seems to be working fine. Asset fields pointed to S3 buckets are populating correctly when opening entries to edit.

Not sure if I missed something in release notes along the way. 🤷‍♂️ 🤦‍♂️

**Comment by jasonbell** [comment]
Just quick followup that I can confirm that now when re-selecting the asset from an S3 container, the MD file saves `tile_image: /path/to/asset.jpg` now rather than the complete S3 path.

What’s the asset container config look like you ask?

Well for some reason, I had a previous `url` parameter configured that matched the path and so was saving as it should (now). I commented out the `url` parameter and paths now save properly. The upside seems to be that I can now use the `url` parameter of an S3 asset container to store something like a Cloudfront distribution path.

Think we’re good here. Thanks for watching me troubleshoot in real time. 🤦‍♂️

**Comment by jasonvarga** [comment]
Phew! What a rollercoaster!

**Comment by paulstewart** [comment]
> Sure. I'll put together a more detailed example later with some screen caps , but here's the fullest explanation of the problem I can give at the moment:
> 
> I have a collection with multiple single-asset fields pointing to an S3 asset container. An author goes in and adds an entry with new assets, saves, and the `.md` file is created with correct values for those asset fields. No problem.
> 
> However, on certain versions of Statamic (basically anything after 2.5.11), if a user opens one of those entries in the CP, those asset fields are completely blank. The values are stored correctly in the `.md` file, but they don't make it back to the corresponding Vue elements. So if something in another field is changed -- let's say a quick copy update -- and the entry is saved, those asset fields now save as empty because the Vue elements don't have any value assigned to them. Data is essentially erased, and content disappears.
> 
> No errors are reported to logs, and there are no errors in the console or Vue developer tools. I'm stumped.
> 
> The issue first showed up for me in 2.5.8. Based on the history of this issue, it appears you fixed it in a May release (2.5.10?), but then it reappeared in 2.5.12 and above.

I'm working with 2.11.19 and this appears to be an issue with local assets.
