### ISSUE TITLE
Glide tag with fm="pjpg" (progressive JPG) uses extension .pjpg not .jpg

### ISSUE THREAD

**Issue by gmcz** [statamic/v2-hub#1409]
### Expected behaviour
I expect that a .jpg file would be created

### Actual behaviour
A file with the extension ".pjpg" is created

### Steps to reproduce
1.  Use a glide tag with `fm="pjpg"`
2.  Check the output

### Server Details

**Operating System**: Mac & Linux

**Web Server:** Nginx

**PHP Version:** 7

**Statamic Version:** 2.5.9

**Comment by jackmcdade** [comment]
Looks like that was fixed in Glide 1.2 (we're on 1.1.x). Will get that sorted out. 👍

**Comment by jackmcdade** [comment]
Actually just kidding, we _are_ running the latest version of Glide, and I don't see an issue with `fm="pjpg"`. How do I recreate your issue exactly?

**Comment by jasonvarga** [comment]
Confirmed bug (in Glide) - but I'll fix it and open a PR.

**Comment by jasonvarga** [comment]
Fixed for next release.

**Comment by gmcz** [comment]
Thanks, Gentlemen! 👍
