### ISSUE TITLE
Global content files that start with global_ highlight General

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#1414]
### Expected behaviour
All of our global content files start with `global_` as part of the name.

![screen shot 2017-05-10 at 4 42 31 pm](https://cloud.githubusercontent.com/assets/1793867/25920589/76a60a56-35a0-11e7-971b-8c1b7a5216d8.png)

In the control when you are viewing one of these global setting files the General and file you are viewing are highlighted.

![screen shot 2017-05-10 at 4 39 53 pm](https://cloud.githubusercontent.com/assets/1793867/25920611/8969c4ac-35a0-11e7-9a23-41fd4b0e1835.png)

Removing the `global_` from the front of the file name causes the highlighting to work as expected.

![screen shot 2017-05-10 at 4 44 23 pm](https://cloud.githubusercontent.com/assets/1793867/25920703/d03092f8-35a0-11e7-9a28-8357f11b471c.png)

### Actual behaviour
Please see above.

### Steps to reproduce
1.  Name a file in `content/globals/global_x.yaml`.
2.  Now you will see in the control panel that General and the file you are viewing is highlighted.

### Server Details

**Operating System**:
OSX

**Web Server:**
nginx

**PHP Version:**
7.0

**Statamic Version:**
2.5.9

**Updated from an older Statamic or fresh install:**
Updated.

**List of installed addons:**
None.

### Logs
None.

**Comment by JesseLeite** [comment]
Seems fine now?  If it's still an issue, please re-open!

<img width="653" alt="screen shot on 2018-06-06 at 15_40_53" src="https://user-images.githubusercontent.com/5187394/41061261-0e7289ac-69a0-11e8-94c3-e9a898cc024c.png">
