### ISSUE TITLE
List fieldtype validation failing

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [statamic/v2-hub#1415]
List fields are not working with the `validator: numeric` validation (and probably other validation rules)

this is the fieldset
```  milestones:
    type: list
    display: Milestones
    validate: numeric
```

when i try and add items in the CP, and save, i get a validation error: `The Milestones field must be a number.`

i think whats happening is its trying to validate the _whole_ field (eg the array of values), instead of each specific value in the array?

**Comment by matthewjumpsoffbuildings** [comment]
Ok I also tested this with a Replicator field, and if I have any validation on the sub fields, that validation doesnt seem to get processed at all? Eg if one of the sub fields in a replicator set has `required`, it doesnt enforce it.

It appears Statamic only does validation on the top level field?

**Comment by jasonvarga** [comment]
Technically the validation is working for the list field. Like you said, it's validating that the whole field is numeric. Gotta work out a nice way for you to add validation to each item.

Regarding the replicator, yes, only top level fields are being validated. It's up there on our todo list.

**Comment by Illizian** [comment]
@jasonvarga I discovered this issue whilst looking for problems validating replicator fields. Could we add a note about this within the documentation please - it seems like somewhat of an oversight.

**Comment by jasonvarga** [comment]
Closing this in favor of #345
