### ISSUE TITLE
Validation Errors Not Obvious

### ISSUE THREAD

**Issue by PhilippeGauthier** [statamic/v2-hub#1416]
### Expected behaviour
If you've got a long page in the control panel that uses validation and you create some data that doesn't pass validation you'd expect to be notified in an obvious way that ideally shows you the error and tells you the page / entry was NOT saved.

I think a modal or at the very least you kick the users to the top of the page so they see the errors would be really helpful.

### Actual behaviour
There's no obvious indication the page / entry wasn't saved.

https://cl.ly/361H3Z1o1G1F

Kind of okay if you know what to look for but impossible for clients.

**Comment by matthewjumpsoffbuildings** [comment]
Just ran into this problem today.

**Comment by jasonvarga** [comment]
Nice find.

In the mean time, tell your clients not to enter any incorrect data.

![](https://media.tenor.co/images/3b243afad73c9e3a1384d945603ea3a2/tenor.gif)
