### ISSUE TITLE
Able to configure roles so user can't log in to CP

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1418]
If a site has no dashboard widgets then a user is kicked to the pages screen when the log in.

However, if a user does not have permissions to view pages, when they log in they are kicked straight back out with an access denied error.

Presumably, this would also be the case if the start page was also set to "Pages".

I'm not sure where this user should land if this conflict occurs but being asked to log in again doesn't seem like the right behaviour.

**Comment by jasonvarga** [comment]
Perhaps, but if they have nowhere to go, where should they go?

**Comment by lukeagsmith** [comment]
I don't know how the list of what they have access to is stored, but perhaps the "first" thing they permissions for e.g. the first collection in the list they have access to view.

The only other option I can think of would be change the behaviour of no dashboard widgets automatically kicking you to the pages view so it becomes a safe landing place for all (as I don't think you can deny access to the dashboard). Obviously a blank dashboard isn't the prettiest thing, but if people don't want the dashboard to appear they can use the setting the CP.

**Comment by lukeagsmith** [comment]
Update to the last comment, I meant to say:

>Obviously a blank dashboard isn't the prettiest thing, but if people don't want the dashboard to appear - for users who have access to pages - they can use the setting the CP.

No permissions to view pages would have to override the CP setting to land on the pages view.
