### ISSUE TITLE
Empty Date Fields

### ISSUE THREAD

**Issue by PhilippeGauthier** [statamic/v2-hub#1420]
### Expected behaviour
I'd like to be able to have a date field in the CP that can be empty. The use case would be creating an optional date that I can then sort / filter by. 

### Actual behaviour
Date fields default to the current date and there's no way of clearing them. That basically means the field is created automatically which prevents me from filtering.

**Comment by jackmcdade** [comment]
This feature exists :) 

![image](https://user-images.githubusercontent.com/44739/40987326-40f0f62e-68b6-11e8-9c73-c721015d8cd0.png)

<https://docs.statamic.com/fieldtypes/date>
