### ISSUE TITLE
Bug: "Leave site" prompt appears when Saving fieldset

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#1424]
### Expected behaviour
Fieldset should save and show updated success message

### Actual behaviour
"Do you want to leave this site" prompt appears when Save is clicked. 
Clicking "Leave" saves the fieldset

![screenshot 2017-05-18 10 44 53](https://cloud.githubusercontent.com/assets/414211/26210653/512f83b4-3bbe-11e7-9704-47ebd10bed2d.png)

### Steps to reproduce
1.  Edited fieldset (/cp/fieldsets/project)
2.  Toggled a taxonomy on
3.  Click Save

### Server Details

**Operating System**:

**Web Server:**

**PHP Version:**

**Statamic Version:** 2.5.10

**Updated from an older Statamic or fresh install:**

**List of installed addons:**

### Logs
If any logs (browser, server, or Statamic) are appropriate...
<details>
```
Paste em here
```
</details>

**Comment by jasonvarga** [comment]
Derp. Noticed and fixed that for the publish page. Missed it for fieldset builder. Good one.
