### ISSUE TITLE
Sorting of the collections

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1426]
### Expected behaviour
Collections should be sorted alphabetically with the Title.
Or it should be possible to customize the order.

### Actual behaviour
It is not sorted by slug, title or creation date.
Seems pretty random

### Steps to reproduce
1. Have some collections
2. Hopefully you see random sorted list of collections

### Server Details
**PHP Version:** 7.1  
**Statamic Version:** 2.5.10

**Comment by jasonvarga** [comment]
Where are you seeing the incorrectly sorted collections?

**Comment by rrelmy** [comment]
Everywhere in the CP

 - Content » Collections
 - Config » Content » Collections
 - Collection Fieldtype Suggestions

![image](https://cloud.githubusercontent.com/assets/442683/26821848/32231f32-4aa8-11e7-9738-02272f4b0491.png)
