### ISSUE TITLE
Regression: Pages fieldtype with parent stopped working

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1428]
This regression has been introduced in v2.5.8 or v2.5.9. v.2.5.7 was working without problems.

### Expected behaviour
Pages fieldtype with a `parent` should show suggestions.

### Actual behaviour
It is just a spinning gif.

### Steps to reproduce
1.  Add a Pages field to the fieldset
2.  Watch the spinner
3.  Find a 500 Server error message in the network panel of your dev tools

### Temporary workaround
Remove the parent from the fieldtype.

### Server Details

**Operating System**: macOS / Linux

**Web Server:** Valet / Apache

**PHP Version:** 7.1

**Statamic Version:** 2.5.10

**Updated from an older Statamic or fresh install:** Update

### Logs
If any logs (browser, server, or Statamic) are appropriate...

```
[2017-05-19 17:14:03] local.ERROR: ErrorException: mb_strpos() expects parameter 1 to be string, array given in C:\projects\suissetec\statamic\vendor\laravel\framework\src\Illuminate\Support\Str.php:393
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mb_strpos() exp...', 'C:\\projects\\sui...', 393, Array)
#1 C:\projects\suissetec\statamic\vendor\laravel\framework\src\Illuminate\Support\Str.php(393): mb_strpos(Array, '/')
#2 C:\projects\suissetec\statamic\bundles\Suggest\Modes\PagesMode.php(17): Illuminate\Support\Str::startsWith(Array, '/')
#3 C:\projects\suissetec\statamic\bundles\Suggest\SuggestController.php(33): Statamic\Addons\Suggest\Modes\PagesMode->suggestions()
#4 [internal function]: Statamic\Addons\Suggest\SuggestController->suggestions()
```

**Comment by jasonvarga** [comment]
Can you post the fieldtype config?

**Comment by rrelmy** [comment]
Of course

```
  field_3:
    type: pages
    display: Field 3
    parent: c44d9a45-5555-41b9-beba-c2beda6131d4
```

`c44...` is the id of the `/` page

**Comment by jasonvarga** [comment]
In `statamic/bundles/Relate/RelateFieldtype`'s `preProcess` method, at line 19 just before the `return` statement, add this:

```
if ($this->is_config && $max_items == 1) {
    return $data[0];
}
```

**Comment by jeffmckeand** [comment]
Ran into the same issue, so thanks for the fix, @jasonvarga. Safe to assume this will be rolled into an upcoming update? :)

**Comment by beckysoll** [comment]
👏 👏 👏  yay for finally having a problem that has a google-able solution 👏 👏 👏

**Comment by rrelmy** [comment]
You found it via google?  :-D

**Comment by beckysoll** [comment]
sure did @rrelmy
