### ISSUE TITLE
Error Exception on translating entries with empty RelateFields

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#1430]
I'm on Statamic 2.5.10.

When I'm trying to save a collection entry (I guess it doesn't matter which content type) in the non-standard locale (i.e. translate it), and a non-localizable `RelateField` in the entry is empty, an ErrorException will occur:

[2017-05-22 16:09:39] dev.ERROR: ErrorException: Undefined offset: 0 in …/statamic/bundles/Relate/RelateFieldtype.php:27

A workaround is to make the suggest-field localizable, but if that's not intended, it'll be an error source for authors.

Thanks for looking into this.

**Comment by rrelmy** [comment]
I can confirm this bug in 2.5.11 too

Here a patch (PHP 7 only) for the relate field type

``` patch
Index: statamic/bundles/Relate/RelateFieldtype.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- statamic/bundles/Relate/RelateFieldtype.php	(date 1498490393000)
+++ statamic/bundles/Relate/RelateFieldtype.php	(date 1498491970000)
@@ -32,7 +32,7 @@
         $max_items = (int) $this->getFieldConfig('max_items');
 
         if ($max_items === 1 && is_array($data)) {
-            return $data[0];
+            return $data[0] ?? null;
         }
 
         return $data;
```

@jasonvarga could we get a fix in the next release? 😸

**Comment by ASochat** [comment]
I can confirm this too

Any update on this bug ?

**Comment by jasonvarga** [comment]
Seems to be okay on 2.9. @ASochat 's comment was May 15, which is before it was released.
Let us know if its still broken.
