### ISSUE TITLE
Base64-urlencode collision, incorrect formation of url addresses

### ISSUE THREAD

**Issue by ilyaskorik** [statamic/v2-hub#1435]
Hello! The base64 dictionary contains the + and / symbols, which are also used in the url schema as special characters. Therefore, very often when working with unicode, your code does not handle this behavior correctly.

It is enough to load files with names in unicode and with a high probability your code will throw 404 error in \Statamic\Http\ResourceServer\Server::setResourceUri.

Therefore, you need to add urldecode / urlencode to all the places where base64 is used to generate the url. For example in \Statamic\Imaging\ThumbnailUrlBuilder::build

### Server Details

**Operating System**:

Any

**Web Server:**

Any

**PHP Version:**

Any

**Statamic Version:**

Any

**Updated from an older Statamic or fresh install:**

Any

**List of installed addons:**

Any

**Comment by jasonvarga** [comment]
Thanks Ilya!

**Comment by jasonvarga** [comment]
Closing this as it's pretty old and it's solved in v3.
