### ISSUE TITLE
display:myfield is missing in forms

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#1436]
### Expected behaviour

I'd expect `display:myfield` to work exactly the same as `old:myfield` in forms.

Otherwise there's two places where to define the display of fields in the formset (for error messages and emails), and in the HTML for the visible label. 

### Actual behaviour

`display:myfield` is just empty.

**Comment by jackmcdade** [comment]
`old` is the _value_, `display` is generally for a label, which isn't a Forms feature. Those are two different things. Feel free to correct me if I misunderstood this request though :)
