### ISSUE TITLE
https://store.statamic.com/statamic - trial link broken

### ISSUE THREAD

**Issue by randohinn** [statamic/v2-hub#1437]
### Expected behaviour

In https://store.statamic.com/statamic the ` try Statamic out for free ` link should direct to the trial page at `statamic.com/try`.

### Actual behaviour
It redirects to `accounts.statamic.com/try` instead. Which is Bob Ross.
### Steps to reproduce
1.  Go to https://store.statamic.com/statamic .
2.  Click the `try Statamic out for free link`.

**Comment by jasonvarga** [comment]
Bob Ross is pretty cool, though.
