### ISSUE TITLE
Did localized image assets break in 2.5?

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#1440]
On some page, the _index.md_ file contains this:

`image: /assets/img/test.jpg`

The _en.index.md_ file contains exactly the same, but the image is completely missing on the English page (being served on _/en/_).

The template contains this:

```
{{ asset:image }}
  <img src="{{ url }}">
{{ /asset:image }}
```

It seems the `asset:image` array is empty on the English page, since nothing between the array-tags will be output.

Another example with a PDF file works, but not images.

I double-checked my configuration and it should be fine.
What am I missing? Or did image assets break somewhen?

Thanks a bunch!

**Comment by andypillip** [comment]
I analyzed the code, and there's some fixes I'd suggest.

@jackmcdade @jasonvarga It would be great if you could review these bugfixes and apply them to the core. 

core/API/Asset.php, `function whereUrl($url)`:

```php
$fullUrl = (Str::contains($url, '::') || Str::startsWith($url, ['http://', 'https://']))
            ? $url
            : URL::prependSiteRoot($url, Config::getDefaultLocale());
```
It's necessary to pass the default locale, since otherwise the asset URL will always depend on the locale, which is not the intended behaviour.

This first change will at least fix basic images. Glide Images will still have the locale in their URL and will not be found.

**Comment by jasonvarga** [comment]
Thank you @andypillip 

I'm focusing on localization fixes for the next couple of days. This issue is one of them. Thanks for the suggestion!

**Comment by andypillip** [comment]
@jackmcdade @jasonvarga the second fix is for core/Imaging/GlideUrlBuilder.php, `function build(…`:

```php
return URL::prependSiteRoot($builder->getUrl($path, $params), Config::getDefaultLocale());
```

Here it's the same – the address output to the frontend needs to be locale-independent – so I'd take the default locale.

**Comment by andypillip** [comment]
@jasonvarga that's great new to me.

Thanks already.

**Comment by jasonvarga** [comment]
@andypillip What's the issue you are having with Glide, exactly?

**Comment by andypillip** [comment]
@jasonvarga the URL variable output to the Frontend will begin with /it/ for the Italian site without my fix, which is just wrong. It'll give a 404.

What I didn't think of is different hostnames for languages, but even then you'd like the same address for assets for caching purposes and to avoid duplicate content, no?

**Comment by Francisdakin** [comment]
Thanks @andypillip ! Your solution did the trick. Had the exact same issue ! Hope it will be fixed soon.

**Comment by manogi** [comment]
For those who use this to quick fix: remember you have to add `use Statamic\API\Config;` at the top.

**Comment by jasonvarga** [comment]
@andypillip and @manogi - Regarding the Glide issue, the images should still load even when prepended with your locale subfolder.

Is this not the case for you?

`/img/something...` and `/fr/img/something...` both work for me.

What kind of server are you using?
Can you please show me your `site/settings/assets.yaml`?

**Comment by andypillip** [comment]
Hi @jasonvarga 
Thanks for getting back to us.

I checked and on the production server with the Apache rewrite it actually works. Btw I'm using only one .htaccess, not one for each locale.

Nevertheless, assets shouldn't have multiple URLs, it would results in missed caching opportunities, and in additional costs for CDN and data transfer.

Locally I'm not using Apache, but a customized _server.php_, which includes either _/index.php_ or _/en/index.php_. So I guess it should have also worked, but it doesn't.

My _assets.yaml_:
```
image_manipulation_route: /img
image_manipulation_secure: true
auto_crop: true
image_manipulation_driver: gd
```

Best regards.

**Comment by jasonvarga** [comment]
Cool, I just wanted to confirm what was going on before implementing it.
That makes sense. Thanks for clarifying.

**Comment by manogi** [comment]
sorry, was away for a few days:

I use laravel forge.
My assets.yaml is empty.

I found the following somewhere (forgot where) and added it to the nginx configuration:

```
    location /de/ {
        try_files $uri $uri/ @derewrites;
    }
    
    location @derewrites {
        rewrite ^/de/(.*)$ /de/index.php last;
    }
```

**Comment by andypillip** [comment]
@jasonvarga is this pending 2.6 as well?

In the latest 2.5 the Glide Tag is not fixed yet.

**Comment by jasonvarga** [comment]
Let me know once you try 2.6

**Comment by FR6** [comment]
I had the problem in 2.5.8 and now it's solved in 2.6.0.

**Comment by aryehraber** [comment]
Hey there, just to chip in; I'm also having issues getting Glide images to work on localised URLs (getting 404s).

I'm using Valet locally and Nginx on a DO server in production with the suggested rewrite rules from the docs.

While the default locale (`/img/something`) works fine (both locally and in prod), the localised versions don't i.e: `/nl/img/something` and `/gr/img/something`.

Same issue on v2.5.11 and now on v2.6.1.

@jasonvarga Let me know if you need more info!

**Comment by rrelmy** [comment]
@aryehraber Not sure if this is the same issue as we have, but maybe this will help you.
In our setup the assets are saved to `public/assets` and the static glide cache is `public/img`.

The other language is under `public/fr` inside this directory we symlink `assets` to `../assets` the same for the `img` directory.
That works for us.

This is described in the docs somewhere 😉

**Comment by aryehraber** [comment]
Remy's suggestion fixed it! Silly I didn't think of this myself... Thank you @rrelmy!

**Comment by andypillip** [comment]
@jasonvarga I just updated to 2.6.9 and _statamic/core/Imaging/GlideUrlBuilder.php_ is still generating different URLs for the same asset.

Did this error swoop back in?

@aryehraber @rrelmy if I understand correctly, your problem is because of this. The very same asset should not have language-dependent URLs. Because of this the symlink is necessary. It shouldn't.

**Comment by jasonvarga** [comment]
Nothing changed regarding what you're requesting. The Glide URLs are relative to the locale.

They are locale dependent because of what you pointed out a while ago.

> What I didn't think of is different hostnames for languages

If you are using different domains or subdomains for locales, instead of subdirectories, it may be odd to request an image from a different domain.

We may add an option to make them locale independent later but right now they are dependent.

**Comment by mpenna** [comment]
Can somebody please point to some good documentation on how to properly set this up? I'm trying out version 2.7.2 and two days have already gone by and I can't seem to get this whole "localized asset" issue fixed. I have localized other items such as pages and blog posts but no matter what I try, images are still displaying broken when visiting the localized versions.

**Comment by mpenna** [comment]
They're broken for instance on the "blog index" page, where I believe it's Glide that's generating their thumbnail versions. These thumbnails are broken when visiting this same page under another locale (subfolder approach).

**Comment by jasonvarga** [comment]
Can you give an example of one of the broken URLs?

**Comment by mpenna** [comment]
@jasonvarga Thanks for trying to help. 

This is an example URL which is broken: 

/en/img/asset/bWFpbi9pbWcvc3RldHNvbi5qcGc=?w=140&h=140&s=aee885f8a337065f1bbc1daadc482103

This example I pulled from the following blog index page: 

/en/blog?page=2 

This page pulls the corresponding 'es' version which I've added of one of the default blog posts that come with the Redwood theme: 

![snag- 2017-12-20-15-04-53](https://user-images.githubusercontent.com/6953141/34219108-4cd1dd66-e597-11e7-8d80-01e022572f8f.png)


I'm trying out Statamic and I've been using the default Redwood theme to get to know how all this works and I have configured my project with 3 locales - english no longer being the default: 

![snag- 2017-12-20-14-51-47](https://user-images.githubusercontent.com/6953141/34218728-23138782-e596-11e7-87d2-6402964bb9b3.png)

I have followed the documentation regarding localization (subfolder approach), so I believe everything is setup correctly: 

![snag- 2017-12-20-14-52-33](https://user-images.githubusercontent.com/6953141/34218858-8ce0ea60-e596-11e7-8503-360cbaabb5a0.png)

That's how I've set up my physical folders. I'm using nginx, so as I understand there's no need for .htaccess files inside the root folders for the other locales. And I have also configured the corresponding nginx virtual host configuration file with the recommended rewrite rules (as stated in the documentation): 

    location @enrewrites {
        rewrite ^/en/(.*)$ /site_en/index.php last;
    }

    location /en/ {
        try_files $uri $uri/ @enrewrites;
    }

    location @esrewrites {
        rewrite ^/es/(.*)$ /site_es/index.php last;
    }

    location /es/ {
        try_files $uri $uri/ @esrewrites;
    }

So, not sure what's happening here. Must be missing something.

**Comment by jasonvarga** [comment]
I've only ever tried with the same directory as the URL.

eg. Instead of `statamic/site_en/index.php` mapping to `/en` I would have just done `statamic/en/index.php`.

**Comment by mpenna** [comment]
I'll try that, but shouldn't the rewrite on the nginx config file take care of that?

**Comment by mpenna** [comment]
Renaming the locales root folders did the trick. But still intrigued why it didn't work before, given that the nginx rewrites should've taken care of that. Anyway, thanks @jasonvarga.

**Comment by mpenna** [comment]
@jasonvarga All was well until I decided turning on the "Serve cached images directly" setting inside site/settings/assets.yaml. Now the thumbnails are all broken again. 

I was trying out the image manipulations (https://vimeo.com/129033181) and to make it work as shown in the video, I also had to turn off the "Secure image assets" setting. Not sure though if it has anything to do with the issue here. Anyway, right now, between images and thumbnails, I have three whole different places where these assets pop up: 

![snag- 2017-12-20-18-41-17](https://user-images.githubusercontent.com/6953141/34228061-82d2373e-e5b6-11e7-9e77-90146fc9054b.png)

This is a tad bit confusing. Any ideas?

**Comment by jasonvarga** [comment]
- `app/assets/img` are just where your assets are.
- `app/img` is where the manipulated ones go now that you've turned on the cached setting
- `app/local/cache/glide` is where they went before you turned off the cached setting (they won't just disappear when you toggle the setting)

When _not_ using the cached setting, the images are served through PHP. It's actually going through index.php and through Statamic.

When you _are_ using the cached setting, the images get saved to a location where the server will serve them directly. In this case, you'll need to symlink `app/es/img` and `app/en/img` to your `app/img` directory.

**Comment by mpenna** [comment]
@jasonvarga Got it! It's working now. Once again, thanks.

**Comment by mpenna** [comment]
@jasonvarga Sorry for the truck-load of questions, but I'm still finding my way around the framework. Would it make sense to you to keep on using the old cache location instead of the new one (/img). As you pointed out, I imagine the following symlinks would be in order to keep everything working: 

- /app/en/img => /app/local/cache/glide
- /app/es/img => /app/local/cache/glide
- /app/img => /app/local/cache/glide (not sure about this one)

What would you say? Good? Bad? Whatever?

I'm asking this because - it wasn't showing on the screen grab - there's more than one folder inside  /app/local/cache/glide: 

- /app/local/cache/glide/containers
- /app/local/cache/glide/paths

Not sure how that second one (paths) got there in the first place. So in the event other folders end up being created there, I'd like to keep everything as tidy as possible.

**Comment by jasonvarga** [comment]
They are saved differently depending on whether you are using the cached option. So, no.

Wherever you tell it to save using `image_manipulation_cached_path` should be symlinked from `/en/{image_manipulation_route}` and `/es/{image_manipulation_route}`

**Comment by mpenna** [comment]
Thanks. I'll give it a go to see how it works.

**Comment by iljapanic** [comment]
Hey all,

I'm facing the same issue with cached Glide generated assets and linking to them from a locale.

I've tried following symlink with no success:

```
ln -s img cz/img
```

I simply went from Statamic error to 403 Forbidden error when trying to open the image url.  What method would you suggest for symlink-ing?

**Comment by aerni90** [comment]
> They are saved differently depending on whether you are using the cached option. So, no.
> 
> Wherever you tell it to save using `image_manipulation_cached_path` should be symlinked from `/en/{image_manipulation_route}` and `/es/{image_manipulation_route}`

@jasonvarga This solution should be mentioned in the docs. I was having the exact same issue and was looking for more than an hour until I came across this.

**Comment by FrittenKeeZ** [comment]
So... because we already hacked `index.php` to be used for all languages, we couldn't use the symlink approach.
Instead, I made a patch to remove the locale part from the generated URL.
```diff
diff --git statamic/bundles/Glide/GlideTags.php statamic/bundles/Glide/GlideTags.php
index 257300c..fcba437 100644
--- statamic/bundles/Glide/GlideTags.php
+++ statamic/bundles/Glide/GlideTags.php
@@ -152,6 +152,8 @@ class GlideTags extends Tags
         }
 
         $url = ($this->getBool('absolute')) ? URL::makeAbsolute($url) : URL::makeRelative($url);
+        // Remove locale from URL.
+        $url = str_replace('/' . site_locale() . '/', '/', $url);
 
         return $url;
     }
```

**Comment by andypillip** [comment]
Hi there @FrittenKeeZ.

Thanks for sharing your suggestion.

I consider removing some string from the URL quite risky though. What if some user actually used the locale as a page name? Page names are user input, after all.

A cleaner way would be to not include the locale in the URL in the first place.

In my suggested patch #issuecomment-306224891 I used yet another approach: Always using the default locale to generate Glide URLs.

**Comment by FrittenKeeZ** [comment]
@andypillip I can't get your patch to work - it still renders the URLs with locale prefixed.

**Comment by andypillip** [comment]
@FrittenKeeZ the change in  core/Imaging/GlideUrlBuilder.php should still work – the other one I don't know, you're right that was for an older version of Statamic.

Yes, the image URL will still have a locale, but it's the default locale for all locales. So f.e. the site _/de/test_ will still reference an image at _/en/img/image.jpg_.

So your image can be cached on a CDN f.e., and wont be duplicated.

**Comment by jonassiewertsen** [comment]
I am having the same problem and cant get it to work. 

It works fine under the default: mydomain.com   (default is de)
All assets cant be loaded via mydomain.com/en

```
 {{ photos }}
    <img src="{{ glide:value width="800" }}" />
 {{ /photos }}
````

I am using Laravel forge. 
Statamic version 2.11.14

I did add to nginx.conf (being in my root file)
```
# The files to try when it's not a static cache request (ie. anything other than GET)
    location @default {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location / {
        try_files $uri $try_files; # Use the dynamically assigned locations from above.
    }

    # English
    location @enrewrites {
        rewrite ^/en/(.*)$ /en/index.php last;
    }

    location /en/ {
        try_files $uri $uri/ @enrewrites;
    }
```

In the root folder i did add the 'en' folder and did the changes in the index.php as written in the docs.  The picture cant be found.
