### ISSUE TITLE
License key entry form after updating does nothing

### ISSUE THREAD

**Issue by lardnicus** [statamic/v2-hub#1443]
### Expected behaviour
Site just works after updating

### Actual behaviour
After updating, I am asked to enter the license key (single text entry with button). I enter the license key and it asks me again... and again... nothing happens so I jump into site>settings>system.yaml
Add key manually and then the site stops working completely

### Steps to reproduce
1.  update from 2.1.9 to 2.5
2.  enter a valid license key assigned to the correct url
3.  profit?

### Server Details

**Operating System**:
linux

**Web Server:**
apache

**PHP Version:**

**Statamic Version:**
2.5 (I think...)

**Updated from an older Statamic or fresh install:**
updated from 2.1.9

**List of installed addons:**
none

### Logs
If any logs (browser, server, or Statamic) are appropriate...
<details>

[statamic-2017-06-03.txt](https://github.com/statamic/v2-hub/files/1049493/statamic-2017-06-03.txt)
</details>

**Comment by jasonvarga** [comment]
Enter the `license_key` manually into `site/settings/system.yaml`.

This is being removed in 2.6 anyway.
