### ISSUE TITLE
How to use variables inside Modifiers? 

### ISSUE THREAD

**Issue by ilyaskorik** [statamic/v2-hub#1445]
For example, in 

{{ if array_var | contains:{id}  }}
   {{ value }}
{{ /if }}

**Comment by andypillip** [comment]
Hi @ilyaskorik.

I think this is a support question and usually better asked in a more relaxed atmosphere [in the lodge](https://lodge.statamic.com/questions).

Nevertheless, [according to the docs](https://docs.statamic.com/modifiers/contains) variables are used without any special notation inside modifiers:

`{{ if array_var | contains:id }}`
