### ISSUE TITLE
Asset cannot rename with dash in filename

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1450]
Try to rename a file to i.e. `test - test` within the asset browser results in this error:
```The filename may only contain letters, numbers, and dashes.```

It seems any filename with a hyphen/dash `-` does not work. 

As a side - surely also, files can contain other characters than letters, numbers and dashes?

**Comment by jasonvarga** [comment]
The issue is the space, not the dash.

In 2.6 we're going to slugify filenames on upload to make everyone's lives easier.

So, this validation behavior is (or, will be) correct.

However in this dialog, we'll allow spaces, but automatically slugify.

**Comment by dannyuk1982** [comment]
Ah what an idiot I am! I think the fact you can upload with spaces threw me. OK cool - sounds good on 2.6!

**Comment by jasonvarga** [comment]
That _was_ inconsistent. I'd call it a bug if we weren't going to change the behavior _to_ how it works now anyway.
