### ISSUE TITLE
Using same variable in multiple conditions returns NULL on secondary uses

### ISSUE THREAD

**Issue by ScottHarrisonDev** [statamic/v2-hub#1456]
### Expected behaviour
If you use a variable, for example `{ lesson_id }` within more than one condition of an `{{ if }}` each condition should receive the variable.

### Actual behaviour
`{{ if { questionnaire:questions l_id="{ lesson_id }" } &&  { user_auth:is_done_with_course l_id="{ lesson_id }" } }}`

The `user_auth:is_done_with_course` condition gets `NULL` for `{ lesson_id }` but `questionnaire:questions` received the value perfectly (in this case the int 10). If I switch the conditions around the first condition still gets the value but the second condition gets `NULL`. Looks like you can’t use the same variable more than once in the same conditional statement but I’m sure this is not true.

To debug this and see what each tag call gets as parameters, inside each tag function code as the first line I’m doing `var_dump($this->getParam('l_id'));` and viewing it at the top of the page and I’m seeing `10` and then `NULL`.

### Steps to reproduce
1.  Create two (or more) tag functions that accept a single parameter and have a `var_dump();` for the parameter value as the first line in the function.
2.  In a template write an `{{ if }}` with two (or more) conditions, one for each tag. Pass in the same variable to both of these conditions.
3.  View output.

### Server Details

**Operating System**: Mac OS X 10.11.3

**Web Server:** Nginx (through Laravel Valet)

**PHP Version:** PHP Version 7.1.5

**Statamic Version:** 2.5.10

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:** Bool, RedactorPlugins, Sections, SparkOpportunities, SparkQuestionnaire, SparkUserAuth, SparkUtilities, TaxonomyFilter, TaxonomySlug, Video

**Comment by jackmcdade** [comment]
I don't think that's supported syntax right there. Try this...it's untested, but _maybe_ it'll work:

```
{{ if ({questionnaire:questions :l_id="lesson_id" } && {user_auth:is_done_with_course :l_id="lesson_id}" }) }}
```

**Comment by ScottHarrisonDev** [comment]
Thanks for the prompt reply Jack, unfortunately that gives the same results (10 for first condition and NULL for second condition).

**Comment by jackmcdade** [comment]
Okay yeah, I don't think Antlers supports multiple conditions with tags with variables as parameters.

**Comment by jackmcdade** [comment]
For these extra complex type of conditions, we usually just write a more simple tag method that does the condition, since it looks like you've got an addon going here. Something like...

```
{{ questionnaire:if_user_is_done id="{q_id}" }
  // do the stuff
{{ questionnaire:if_user_is_done }}
```

**Comment by jasonvarga** [comment]
Can't you just do the auth tag? Make that tag return false if the questionnaire doesn't exist.

**Comment by ScottHarrisonDev** [comment]
Thanks @jackmcdade and @jasonvarga, those both sound like more elegant solutions, I'll test it out and change to one of those methods. 

Just to give some more context for clarity. Each lesson can have an optional set of questions but we only want to show these questions if there are questions associated with this lesson (first condition checks this) and if the user has completed this lesson already we don't want them to see the questions again, only the lesson content (second condition checks this).

**Comment by jackmcdade** [comment]
Cool, so many even something like `{{ questionanaire:should_show }}` and work out all various logic under the hood.
