### ISSUE TITLE
Right-click spelling corrections not working with Redactor

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [statamic/v2-hub#1457]
When using Redactor fields, it appears that if you have a spelling error saved in your content, then you use the browsers right-click menu to correct the error, and save the page, the correction wont be saved.

Manually typing the correction in works fine.

Somehow the text that the browser inserts from the right-click spelling menu isnt compatible/correct? 

Tested in Chrome and Safari on OSX

**Comment by jackmcdade** [comment]
Unfortunately that's a side effect of how the third party redactor library works. Nothing we can do to fix it :(
