### ISSUE TITLE
System > Settings > Redactor Settings YAML not updating in CP

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [statamic/v2-hub#1458]
When editing the YAML field in the CP for System > Settings > Redactor Settings, if you add/remove any indexes in the array of buttons (eg deleting `- html` or `- link`), and then save, the field doesnt seem to update.

Tested in Safari and Chrome on OSX

**Comment by rockethouse** [comment]
+1 I'm also seeing duplicates of buttons appearing in the editor... and the lines i've removed are not removing from the editor?

![image](https://user-images.githubusercontent.com/5466694/26958210-7bb58f06-4d08-11e7-9892-1763abb039a0.png)

```redactor:
  -
    name: Standard
    settings:
      buttons:
        - alignment
        - formatting
        - link
        - html

**Comment by jasonvarga** [comment]
Get around this for now my making a new configuration.
ie. Don't adjust `Standard` or `Basic`, make another one.

**Comment by rockethouse** [comment]
Ok no worries thanks

Cheers,

On Sat, Jun 17, 2017 at 3:58 AM, Jason Varga <notifications@github.com> wrote:
Get around this for now my making a new configuration.
ie. Don't adjust Standard or Basic , make another one.
