### ISSUE TITLE
Publishing/unpublishing makes stache mess up sometimes

### ISSUE THREAD

**Issue by Rias500** [statamic/v2-hub#1460]
### Expected behaviour
Stache doesn't mess up

### Actual behaviour
Stache messes up and throws an error comparable to this:

```
Cannot add [collections/social_map/_francais-107.html] to Stache repository [entries]. File at [collections/social_map/francais-107.html] already exists in repository [entries/social_map] with an ID of [5d9e128a-6957-4e64-81fd-d4dce5e1975b].
```

### Steps to reproduce
Can't reproduce it consistently but it happens once every few days and then the whole control panel locks up and the client complains. Maybe just a way to not have it crash completely would solve a lot already.

**Comment by jasonvarga** [comment]
Add `ensure_unique_ids: false` to `system.yaml` to prevent those checks.
You might run into other errors, though.

**Comment by JesseLeite** [comment]
Closing this issue in favor of #2007
