### ISSUE TITLE
Two locales: Missing translation for cp.passwords on login page

### ISSUE THREAD

**Issue by macbruker** [statamic/v2-hub#1461]
![Screenshot of login page](https://user-images.githubusercontent.com/1032194/27010070-7238fe82-4e9c-11e7-8856-5b804fdfaab5.png)

### Expected behaviour
Label should read _Password_ or the appropriate translation

### Actual behaviour
Label reads 'cp.passwords'

### Steps to reproduce
1. Add an additional locale
2. Set _English_ as the second locale
3. Load Login Page

### Server Details

**Operating System**: Mac OS X

**Web Server:** MAMP Pro

**PHP Version:** 7.0.12

**Statamic Version:** 2.5.10

**Updated from an older Statamic or fresh install:** Tested on upgraded and fresh install

**List of installed addons:** _No addons_

I have tried to test this thoroughly, so I hope this is correctly reported.

**Comment by ebeauchamps** [comment]
if you add  `locale: en` in `cp.yaml` the login will always be displayed in English

Then you can add `locale: xx` in each user own file, definig xx as the locale that specific user must see in the CP

**Comment by PeterEmil** [comment]
I got this behavior as well. It disappears when you duplicate `cp.php` in the `site/lang` folder and put that in its own language-folder.
