### ISSUE TITLE
Upload huge images break asset browser

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1462]
### Expected behaviour
Upload a huge image (6000 x 6000 px) - even if a thumb can't be made, the asset browser should still load and be usable.

### Actual behaviour
The asset browser will not enter the folder the image is in - uploading one large image will lock out the entire folder until the image is deleted via FTP or similar, which the client cannot do.

Breaks just on local Valet/Mac setup and also on multiple live sites - 2.5.10

**Comment by ebeauchamps** [comment]
Dup of #1439 ?

**Comment by dannyuk1982** [comment]
Yes might be - although that looks like it's addressing the image resizing itself - on this I am proposing it handles the event that the image will no resize because it is too big. Clients often upload ridiculously large images straight from digital photos, the problem is - once they have, they can't even go in to delete it and upload a smaller one - it's just broken then.

**Comment by jasonvarga** [comment]
It's still a duplicate. We need to gracefully deal with a memory somehow.
