### ISSUE TITLE
Hide field display labels when used in Replicator

### ISSUE THREAD

**Issue by rockethouse** [statamic/v2-hub#1465]
When creating a Set in a Replicator field that only has ONE sub field... you'd most likely label the Set the same as the field... in my case here "Content". 

I think there should be an option to hide the label in this case, as it looks odd with "Content" twice.

![image](https://user-images.githubusercontent.com/5466694/27112827-8e1613ac-50f8-11e7-8944-0f84d7a8a3c9.png)

**Comment by jasonvarga** [comment]
You can get around this now by adding `display: ' '` (that's one space) to the field.

**Comment by rockethouse** [comment]
Ah great thanks!

Cheers,

On Sat, Jun 17, 2017 at 3:44 AM, Jason Varga <notifications@github.com> wrote:
You can get around this now by adding display: ' ' (that's one space) to the field.
