### ISSUE TITLE
FR: Add 'honeypot'-function to Workshop

### ISSUE THREAD

**Issue by subpixelch** [statamic/v2-hub#1466]
### Expected behaviour
If creating a entry in a collection with workshop there should be a SPAM-preventing mechanism like honeypot for Form-Submissions

### Actual behaviour
There's none – and a lot's of SPAM...

**Operating System**:
LINUX

**Web Server:**
Ubuntu 16.01

**PHP Version:**
7.1

**Statamic Version:**
2.5.10

**List of installed addons:**
Workshop

**Comment by jackmcdade** [comment]
You can create one by adding hidden field and setting the validation rule for it as empty :)
