### ISSUE TITLE
FR: Slugify file names on upload

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1471]
Users are bad at naming files.

Bad files names cause problems. (Particularly with images that can end up going through Glide.)

Slugifying filenames of CP uploaded assets would be great.

**Comment by jackmcdade** [comment]
Done for 2.6.

**Comment by jasonvarga** [comment]
![screen shot 2017-06-19 at 5 19 53 pm](https://user-images.githubusercontent.com/105211/27306421-88bdc1c4-5513-11e7-9f89-0ff5d353bab7.png)
