### ISSUE TITLE
Error when moving assets to a different folder

### ISSUE THREAD

**Issue by sebszocinski** [statamic/v2-hub#1472]
### Actual behaviour
I saw this error message:
![image](https://user-images.githubusercontent.com/5466694/27313921-bc8249c0-55af-11e7-83e7-b6888b097bc5.png)

And the error in Console was this:

```
FatalThrowableError in AssetContainer.php line 419:
Cannot unset string offsets
```

### Steps to reproduce
1.  Try to move an asset from either the Assets page or when editing an asset field
2. In my case I was moving it from the parent Main Assets container to a folder inside that container.

### Server Details

**Operating System**: OSX as well as Ubuntu (Staging)

**Web Server:** Valet as well as Nginx

**PHP Version:** 7

**Statamic Version:** 2.5.10

**Updated from an older Statamic or fresh install:** Updated from 2.5.8

**List of installed addons:** 
Colorpicker
+ A few custom basic ones that don't touch any of the assets stuff.

### Logs
If any logs (browser, server, or Statamic) are appropriate...
<details>
```
FatalThrowableError in AssetContainer.php line 419:
Cannot unset string offsets
```
</details>

**Comment by wesort** [comment]
Still not fixed in v2.7.1

**Comment by jackmcdade** [comment]
Since we're unable to recreate this and haven't received any more info, I'm going to close this issue. If you or anyone else has more information leading to the identification and elimination of this oddity, please reopen with said knowledge!

**Comment by sebszocinski** [comment]
Forgot all about this...
I'm pretty sure the bug causing this was in `site/content/assets/main.yaml`.
If your assets is empty and looks like this `assets: ` it will break... it needs to be like this: `assets: []`

**Comment by jasonvarga** [comment]
Ah that sounds familiar. I believe that was fixed around March.

**Comment by sebszocinski** [comment]
👍
