### ISSUE TITLE
ErrorException when accessing CP after upgrading to v2.5.11

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#1477]
Seeing this error after upgrading to v2.5.11. Only happens on staging and production when trying to access the CP (local works fine).

![image_uploaded_from_ios](https://user-images.githubusercontent.com/5065331/27395730-1460e8f2-56b1-11e7-95c0-952038d232b1.jpg)

**Comment by aryehraber** [comment]
Just found this on SO while Google-ing the error: https://stackoverflow.com/questions/41043616/taskqueue-php-error-laravel-5-forge

**Comment by jasonvarga** [comment]
Are you doing anything out of the ordinary for deployment? Git ignoring the `statamic` or `vendor` folder, etc?

**Comment by jasonvarga** [comment]
Oh interesting. Guzzle was updated in the last update. We'll check that out. Thanks.

**Comment by aryehraber** [comment]
That may be it, will report back!

**Comment by aryehraber** [comment]
@jasonvarga: Yep, that was it. I had a non-standard `.gitignore` file that was ignoring the `vendor/` folder. False alarm!

**Comment by jasonvarga** [comment]
🤘
