### ISSUE TITLE
Slow page load triggers page leave alert in control panel

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1480]
### Expected behaviour
Changing the locale should not trigger the alert if no changes were made.

### Actual behaviour
Changing the locale does trigger the alert

#1092 

### Steps to reproduce
1. Edit a page on a multilanguage site
2. Switch the locale without changing any content

### Server Details
**Statamic Version:** 2.5.11

**Comment by rrelmy** [comment]
I tried to narrow down the issue can came to this piece of code in `publish.js`

If I increase the delay it does not happen 😕 
``` js
        // Add the watcher after a small delay.
        // Give things enough time to stop initially modifying the data.
        setTimeout(() => {
            this.$watch('formData', function () {
                this.$dispatch('changesMade', true);
            }, { deep: true });
        }, 1000);
```

**Comment by rrelmy** [comment]
The main aggressor seems to be a assets field which loads slowly.

Is there maybe a way to suppress the changesMade event until the fieldtype is initialized?

**Comment by jasonvarga** [comment]
This has been fixed, right?
