### ISSUE TITLE
php please make:theme generated package.json version upgrade?

### ISSUE THREAD

**Issue by deanwhillier** [statamic/v2-hub#1481]
### Expected behaviour
`php please make:theme` could possibly use a newer version of lavavel-elixir in the `package.json` file.

### Actual behaviour
The generated package.json file includes an older version of laravel-elixir. I assumed the `^` would mean grab the latest version higher than this, but it seems to stick in the `3.*` version range. I was not getting a CSS/SASS sourcemap file generated when running gulp on this version.

**Generated package.json file:**
``` json
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.9.0",
    "laravel-elixir": "^3.2.8"
  }
}
```

**Updated package.json file:**
```json
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.9.0",
    "laravel-elixir": "^6.0.0-15",
    "laravel-elixir-browserify-official": "^0.1.3",
    "laravel-elixir-browsersync-official": "^1.0.0"
  }
}
```

Now CSS/SASS sourcemaps are generating as expected.

### Steps to reproduce
1.  run `php please make:theme`
2.  add some css/sass
3.  run gulp

### Server Details

**Operating System**: macOS /w MAMP Pro

**Web Server:** apache

**PHP Version:** 7.1.1

**Statamic Version:** 5.2.11

**Updated from an older Statamic or fresh install:** Fresh install of 5.2.10, updated to 5.2.11 last week

**List of installed addons:** Colorpicker, Sitemap

### Logs
If any logs (browser, server, or Statamic) are appropriate...

n/a

**Comment by edalzell** [comment]
@deanwhillier they made an elixir change recently, is this still the case?

**Comment by deanwhillier** [comment]
Looks like it, here's the new generated `package.json` file contents:

``` json
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.9.0",
    "laravel-elixir": "^6.0.0-15"
  }
}
```

The other two dev dependencies in my `package.json` file are because I was adding those to my `gulpfile.js`, so they don't need to be in by default.
