### ISSUE TITLE
Limit modifier doesn't work on list stored in global

### ISSUE THREAD

**Issue by gmcz** [statamic/v2-hub#1482]
### Expected behaviour
Output should be vales of list, limited according to the value passed in the limit modifier.

### Actual behaviour
Output is something like "callback_blocks_3c3b7c7a7...".

### Steps to reproduce
1. Create a list in a named global fieldset
2. Attempt to limit the output of that list with the `limit` modifier

### Server Details

**Statamic Version:** 2.5.11

**Comment by gmcz** [comment]
For anyone else with this issue: I'm using CSS's _nth-child_ psudeoselector to `display: none;` these items. Here's [CSS-Tricks useful :nth Tester](https://css-tricks.com/examples/nth-child-tester/), because math.

**Comment by jackmcdade** [comment]
What's your template code?

**Comment by gmcz** [comment]
Here's the template: (it's actually a _partial_)

```
<ul>
    {{ globalfieldset.list limit="3" }}
    <li>{{ value }}</li>
    {{ /globalfieldset.list }}
</ul>

<ul>
    {{ globalfieldset.list offset="3" limit="3" }}
    <li>{{ value }}</li>
    {{ /globalfieldset.list }}
</ul>
```

**Comment by jackmcdade** [comment]
Can you use colons instead of periods? E.g.

```
<ul>
    {{ globalfieldset:list limit="3" }}
    <li>{{ value }}</li>
    {{ /globalfieldset:list }}
</ul>
```

**Comment by gmcz** [comment]
I just gave that a shot and it results in the same "callback_blocks..." output.

**Comment by jackmcdade** [comment]
Ok, looking into it. (You should not use periods btw, just get in the habit of using colons :)

**Comment by gmcz** [comment]
Will do! Thanks, Jack. Again: it's not a showstopper because this is a little list and css can hide it for me. However, this probably isn't how you want it to work. :)
