### ISSUE TITLE
Show page list in CP even if there is only one page

### ISSUE THREAD

**Issue by rockethouse** [statamic/v2-hub#1483]
### Expected behaviour
To see the list of the one page "Home".

### Actual behaviour
You are taken to this screen explaining what Pages are and there is a button to "Edit Homepage" but this is confusing to my clients. I also sometimes disable creating new pages so this screen really isn't helpful. It should just list the single page like normal.

![image](https://user-images.githubusercontent.com/5466694/27619331-b14f0f5a-5c00-11e7-8b44-e1d8fcfba314.png)

### Suggested Solution
Can we just make this optional? to be able to show a single page.

**Comment by aryehraber** [comment]
Duplicate FR (#891) -- I'd also like to see this implemented!
