### ISSUE TITLE
nginx configuration

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1486]
The sample nginx configuration contains following `try_files` directive

``` nginx
    location / {
        try_files $uri $uri/ /static/$uri /static/$uri/index.html /static/ $uri /index.php?$query_string;
    }
```
| rule | notes |
|---|---|
| `/static/` | This will break all sites not in a static cache if there is a index.html inside the static directory |
| `$uri` | the second one can be removed |

---

I think the [nginx localization sample](https://docs.statamic.com/localization#nginx) could be simplified to

``` nginx
    location /fr/ {
        try_files $uri $uri/ /fr/index.php?$query_string;
    }
```

That looks simpler and is consistent with the main rules used in the sample configuration

**Comment by gmcz** [comment]
c.f. https://lodge.statamic.com/questions/2736-configuring-reverse-proxy-on-nginx-for-static-pages
