### ISSUE TITLE
Antlers: variable fallbacks with single quotes do not support umlauts 🐲

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1487]
### Expected behaviour
``` twig
{{ page:title or 'Späck' }}
```
should output the title or «Späck»

### Actual behaviour
```
callback_blocks_23e706618059d1f926a15aa70cd4a60f
```

| Code | Notes |
|---|---|
| `{{ title or 'Späck' }}` | Works if title exists, does not fallback to `Über` if not  |
| `{{ page.title or 'Späck' }}` | Does not work  |
| `{{ page:title or 'Späck' }}` | Does not work  |

### Workaround
Just use double quotes …
---
Extract the string to a template variable and use it as fallback

``` yaml
---
fallback: Späck
---
{{ page:title or fallback }}
```

### Steps to reproduce
1.  Use an umlaut like `äöüàéèëï` or any other in a variable fallback

### Server Details
**PHP Version:** 7.1  
**Statamic Version:** 2.5.11

**Comment by rrelmy** [comment]
It does not need to be a umlaut a `$` is enough to trigger the issue

Lovely regex doing this work
``` regex
/\{\{\s*(\b(?!if|unless\s)[a-zA-Z0-9_][|a-zA-Z\-\+\*%\#\^\@\/,0-9_\.(\s.*)?'\:]*(?:\s*or\s*(?:\b(?!if|unless\s)[a-zA-Z0-9_][|a-zA-Z\-\+\*%\#\^\@\/,0-9_\.(\s.*)?'\:]*|".*?"))*)\s*\}\}/m
```

**Comment by rrelmy** [comment]
🤦 it works with double quote

**Comment by jasonvarga** [comment]
What a rollercoaster!  🎢
