### ISSUE TITLE
Textareas should render block scalar yaml.

### ISSUE THREAD

**Issue by codyspring** [statamic/v2-hub#1489]
### Expected behaviour
yaml data stored using a block scalar (> >- >+ | |- |+) should render on templates.

### Actual behaviour
It displays correctly in the control panel but displays nothing when being used in template files.

### Steps to reproduce
1. Create a fieldset / collection with one of the properties being a textarea.
2. Create a yaml data file for an entry and store the field like:
```YAML
test: >
  This is a sweet multi-line yaml example string
  that will hopefully lead to an even sweeter fix.
```
3. Use the variable in a template.

### Server Details

**Operating System**: OSX and Ubuntu

**Web Server**: Apache and NGINX

**PHP Version**: 7

**Statamic Version**: 2.5.11

**Updated from an older Statamic or fresh install**: Updated regularly from 2.5

**List of installed addons**: None.

### Logs
None

**Comment by jackmcdade** [comment]
I do this all the time without issue. Can you post a full entry, unmodified, for me to test with?

**Comment by codyspring** [comment]
For sure, would it be possible to send it to you privately?

**Comment by edalzell** [comment]
@codyspring his email address is jack@statamic.com

**Comment by codyspring** [comment]
@jackmcdade Sent you an email.

@edalzell Thank you!

**Comment by edalzell** [comment]
@codyspring is this still an issue?

**Comment by codyspring** [comment]
Truthfully I'm not sure. I couldn't get around the issue so I changed my data structure.

**Comment by edalzell** [comment]
can you just close this then @codyspring? If you see it again, just re-open?

**Comment by codyspring** [comment]
Done. :)
