### ISSUE TITLE
Creating a user group without roles does not work

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1490]
### Expected behaviour
It should work

### Actual behaviour
`ErrorException in UserGroupFactory.php line 31:
Invalid argument supplied for foreach()`

### Steps to reproduce
1.  Create a user group without roles
2.  Click save
3.  Boom

**Comment by edalzell** [comment]
I can't reproduce this in 2.6.3 @rrelmy can you confirm?

**Comment by rrelmy** [comment]
This has been fixed in statamic 2.5.2
