### ISSUE TITLE
FR: Replicator option to set default open/close state

### ISSUE THREAD

**Issue by deanwhillier** [statamic/v2-hub#1492]
### Expected behaviour
It would be great to have an option, when configuring a replicator fieldset, to specify if the sets should be expanded or collapsed by default when editing a page the replicator fieldset is used in.

### Actual behaviour
Sets are always open by default. If there are several sets, each with several fields of their own, the page can get very long and difficult to visualize without first collapsing all sets. I've even had situations where Chrome has difficulty scrolling on slower computers with all the sets open.

**Comment by deanwhillier** [comment]
Perhaps even treat sets like accordions, where expanding one will collapse the currently open one at the same level.

**Comment by jasonvarga** [comment]
In an upcoming release, Replicator sets will act like an accordion by default. One set will be open at a time. Unless you choose "expand all", then multiple can be open at a time. Choose "collapse all" to go back to accordion mode. Also, your preference will be remembered across all Replicator fields on the site.

While not exactly what you've requested, we believe it solves the same problem.

**Comment by deanwhillier** [comment]
That sounds great, thanks for the update!
