### ISSUE TITLE
FR: CP page in edit mode. Batch repeated suggestion requests for the same data to prevent multiple redundant calls to the server.

### ISSUE THREAD

**Issue by deanwhillier** [statamic/v2-hub#1494]
### Expected behaviour
In the CP, when using a replicator field with a set that has a suggestion field of some kind (like a list of all pages on the site), using that one set multiple times on a single page in edit mode would only fire off a single request to the server to populate all the fields requiring the same data when subsequently going back in to edit the page.

### Actual behaviour
It seems that each suggestion field currently acts independently of all other suggestion fields, even if they are to have exactly the same data returned and as a result, multiple calls are made to the server when editing a page for the exact same data set. All these requests can take quite a while to complete, and can mean needing to wait quite a while before being able to fully edit a larger page. This can also contribute to errors like #1493.

### Steps to reproduce
1.  Create a page with a replicator fieldset, adding several of the same set that contains a `Pages` field that returns all pages on the site (make sure there are a few dozen pages that need to be returned). 
2.  Save the page
3.  Open the dev tools inspector, select the `Network` tab and filter to XHR requests only.
4. Go back into editing the page and watch the `suggestion` XHR requests pile up. Inspect the requests and returned data.

### Server Details

**Operating System**: maxOS Sierra

**Web Server:** Apache (MAMP Pro 4.1.1)

**PHP Version:** 7.1.1

**Statamic Version:** 2.5.11

**Updated from an older Statamic or fresh install:** 2.5.10

**List of installed addons:** Colorpicker, Duplicate, RedactorPlugins, sections, Sitemap

**Comment by jackmcdade** [comment]
We do this now. 👍
