### ISSUE TITLE
username with period "." breaks user editor in /cp/users

### ISSUE THREAD

**Issue by deonthomasgy** [statamic/v2-hub#1495]
`php please make:user deon.thomas`

go to `/cp/users` ; try to edit the user and the page will break!

**Comment by jasonvarga** [comment]
Thanks for the report, Deon.

Until we fix it, you can just make a user without a period in it. :)

**Comment by deonthomasgy** [comment]
that was my plan :)

**Comment by edalzell** [comment]
I can't reproduce this in 2.6.3, can you confirm @deonthomasgy?

**Comment by JesseLeite** [comment]
Still cannot reproduce this one.  Feel free to re-open if you find it's still an issue!
