### ISSUE TITLE
FR: "Partitioned" pagination

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#1497]
Challenge: I'm wondering if anyone has figured out a way to do what I'm calling "partitioned" pagination... ?

The idea is this: I have a collection of newsletter articles, where their front matter contains fields (among others) like so:

```
...
nl_issue_volume: 9
nl_issue_number: 5
nl_issue_article_number: 4
nl_issue_article_total: 4
...
```

The above says that this particular article comes from newsletter volume 9, issue #5 and is the 4th of 4 articles in that issue.

I want to paginate based on that last value--4 in this case, but it's not always 4. In fact, I tallied them all up, and there are 12 issues with only 3 articles, most (24) have 4 articles, but some have 6 or 7, and just coincidentally, none have 5.

```
12 nl_issue_article_total: 3
24 nl_issue_article_total: 4
18 nl_issue_article_total: 6
14 nl_issue_article_total: 7
```

So my goal is to have all of the articles for a particular issue on the same page, so that paging forward and back through the collection would page you from one complete issue to the next complete issue. Hence, "partitioned" pagination, because the size of the pagination count changes from one, er, subset to the next.

Anybody got this figured out?  

FWIW, I've also discovered a similar use-case here: https://github.com/statamic/v2-hub/issues/793 

So date-partitioning would likely work, as on the field:
```
nl_issue_date: 2017-05-25
```

and the pitfall/objection of "what if the pagination limit is less than the partition (date) size/count should I think be decided in favor of the partition. That is, if `nl_issue_article_total: 7` but pagination is set to 5, the 7 should win, with no pagination after 5.

But I'll bet it's a lot more complicated, so I'm hoping there's some "better way"™ that you'll figure out. I don't think the general need is all that unusual.

**Comment by jackmcdade** [comment]
No plans to add this in v2 at this point.
