### ISSUE TITLE
Link to asset from Redactor creates empty link

### ISSUE THREAD

**Issue by bengilman** [statamic/v2-hub#1499]
### Expected behaviour
Select some text in a Redactor field, click the 'Assets' icon to select a PDF and link selected text to that PDF.

### Actual behaviour
Link is not created, instead an empty <a href="[url]"></a> is created at the very start of the Redactor HTML code.

### Steps to reproduce
1.  Open a Redactor field
2.  Select text to link
3.  Click Assets/Image icon in Redactor toolbar
4.  Find asset that isn't an image and select.
5.  Click 'Select'
6.  Observe that link hasn't been created correctly.

This isn't 100% applicable, in that often it works the first time but not subsequently.

**Comment by bengilman** [comment]
I believe this might be happening because the selected text gets unselected when you interact with the 'Assets' modal.

**Comment by bengilman** [comment]
Can't recreate it on a site updated to latest version so I think we're good - thanks!

**Comment by jackmcdade** [comment]
Great!
