### ISSUE TITLE
Multiple partial variables with the same name throws ugly error

### ISSUE THREAD

**Issue by humanjpg** [statamic/v2-hub#1500]
### Expected behaviour

When inadvertently adding two or more variables with the same name to a partial, it throws a fatal error which doesn't really help to locate the source of the problem.

I would expect the page to load, and perhaps an alert to be flagged in a log somewhere ideally showing where exactly the error occurs and in which template/partial.

### Actual behaviour
```
Whoops, looks like something went wrong.

1/1
ErrorException in Arr.php line 242:
Illegal offset type in isset or empty
```

### Steps to reproduce
1. Create a partial
2. Add a variable to it e.g. `variable_one="chicken"`
3. Add a second variable to it with the same name e.g. `variable_one="peanut"`
4. Kick back with a beer and enjoy that error message.

Not a major deal, but enriching the error messages in general with a clear indication of the source of the problem would be helpful.

✌️

**Comment by jasonvarga** [comment]
Did you use the colon prefix syntax? `:var_one="chicken"` ?

**Comment by jasonvarga** [comment]
We're going to politely _not_ address this issue.

Just don't use the same parameter twice.

Hit me up on Slack if you need to discuss it further.
