### ISSUE TITLE
inline asset manager cuts off bottom assets' dropdowns

### ISSUE THREAD

**Issue by beckysoll** [statamic/v2-hub#1502]
### Expected behaviour
To see the dropdowns

### Actual behaviour
bottom one or two dropdowns are not visible as they drop outside of their parent container (.asset-selector .asset-browser-content)

### Steps to reproduce
Edit a page or entry with a markdown field, click on the "Add Asset" link at the bottom of the field, attept to view the dropdown from the bottom two assets listed, checked in both firefox and chrome on mac.

### To fix
`.asset-selector .asset-browser-content { overflow: visible...` seems to do the trick

**Comment by jasonvarga** [comment]
I think that change would render the dialog unscrollable.

**Comment by beckysoll** [comment]
Aaah yeah, I didn't have a long enough list of assets to see that. looks like a bit of bottom padding on asset-browser-content would do it (6em seems to work). I'm sure there are many css solutions, it would just be ideal if those menus were consistently usable.

**Comment by jackmcdade** [comment]
Fixed for next release.
