### ISSUE TITLE
Free trial badge is shown in dev, regardless of valid license.

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#1503]
My install is still showing a "free trial" warning notice though I entered my valid statamic 2 license key.
I deleted the cache files
Any idea?
thanks

**Comment by jasonvarga** [comment]
It's gonna show that as long as you are on a dev site. I think we'll change that behavior for the future release.

Once you move to a public domain it should go away.

**Comment by ebeauchamps** [comment]
ok

**Comment by jasonvarga** [comment]
You can leave this open.
