### ISSUE TITLE
Empty Assets Title field shows filename instead of nothing

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1504]
**Steps to reproduce**

Use an assets:field tag loop - below is from untouched (except these changes) S2 2.5.11 install, Gallery template:

```
<div class="gallery-images">
{{ assets:images }}
<img src="{{ url }}" />
{{ title }}
{{ /assets:images }}
</div>
```

**Expected behaviour**

The 'title' field here outputs the filename which is ugly. I want to use the 'title' field for Captions throughout the site but can't if its outputting the filenames if empty. I can work around it by making clients put a title on every single image they upload but thats very unfriendly.

Using an IF block around it DOES NOT work - e.g:

```
<div class="gallery-images">
{{ assets:images }}
<img src="{{ url }}" />
{{ if title }}
{{ title }}
{{ /if }}
{{ /assets:images }}
</div>
```

**Actual behaviour**

Outputs filename instead of blank if empty

===

Server configuration

Operating system: Linux

Web server: Apache

PHP version: 5.6

Statamic version: 2.5.11 and 2.6

**Comment by jasonvarga** [comment]
Can you use a different field name? Perhaps `caption`?

Add it to your asset.yaml fieldset.

`title` is special since as you've noticed it falls back to the filenames.

**Comment by anthubbard** [comment]
Ohh I didn't know I could add custom fields to an asset that is amazing! Thanks Jason. Damn.
