### ISSUE TITLE
Form file upload is required when using multiple file option

### ISSUE THREAD

**Issue by beeldr** [statamic/v2-hub#1505]
### Expected behaviour
Should work like with single files

### Actual behaviour
I want users to be able to upload a few images but it is not required, works fine when using fieldtype "file" an validate: image but when using "files" and validate: image it automatically becomes required.

### Steps to reproduce
1.  add form field 
  upload:
    display: Uploads
    type: files
    destination: form-uploads/
    validate: image

2.  add input field
<input type="file" name="uploads[]" />
3.  Post form without uploads

### Server Details

**Operating System**:

**Web Server:**
CentOS 6
**PHP Version:**
5.5.21
**Statamic Version:**

**Updated from an older Statamic or fresh install:**
fresh 2.5.10

**Comment by edalzell** [comment]
ATM Statamic doesn't valid arrays of things @beeldr, so just remove the validation as it wouldn't check it anyway
