### ISSUE TITLE
2.6.0 saving addon settings is broken

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1507]
`[2017-07-19 15:14:58] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function input() on null in C:\projects\subpixel\statamic\core\Http\Controllers\AddonsController.php:174`

The `AddonsController` got its own `__constructor` but does not call its parents constructor, therefor the `$this->request` is not initialized

## Workaround
Replace the current constructor with this
``` php
    public function __construct(Request $request, AddonRepository $addonRepo)
    {
        parent::__construct($request);

        $this->addonRepo = $addonRepo;
    }
```
and add `use Illuminate\Http\Request;` to the imports

**Comment by jasonvarga** [comment]
Or just `parent::__construct(request());` for the moment, and then don't worry about adding arguments or imports.

**Comment by rrelmy** [comment]
@jasonvarga it is not the only controller with this pattern, maybe you need to fix the others too

Of course that is a easier workaround

**Comment by jasonvarga** [comment]
Which others?

**Comment by rrelmy** [comment]
Only `FieldtypesController` but it has no usage of `$this->request` in it

**Comment by jasonvarga** [comment]
Cool then we're good. Will be fixed in the next release.
