### ISSUE TITLE
Images are being slugified with file extension added to file name

### ISSUE THREAD

**Issue by beckysoll** [statamic/v2-hub#1509]
### Expected behaviour
Uploading an image that is already slugified shouldn't change anything about the filename.

### Actual behaviour
The file extension is being added to the end of the name. Underscores are also converting to dashes.

### Steps to reproduce
1. upload an image named image_dude.png
2. you'll see the image becomes image-dudepng.png

### Server Details

**Operating System**: MacOS 10.12.5

**Web Server:** Apache

**PHP Version:** 5.6.2.1 (prod) and 7.0.8 (locally)

**Statamic Version:** 2.6

**Updated from an older Statamic or fresh install:** updated

**Comment by lukeagsmith** [comment]
I can confirm this is happening too (macOS with Valet).

For us, this stops us updating our clients to 2.6 as, even if they upload sensible filenames, it appends the extension to the name and we don't want them to end up with a bunch of those in their assets.

Is there a fix we could put in place before 2.6.1 so we can get 2.6 rolled out?

I also support not converting underscores to dashes.

**Comment by beckysoll** [comment]
I should also add, it made existing paths, referenced in content, to images that had already been uploaded prior to 2.6 invalid, as they had underscores which had been changed to dashes.

**Comment by jasonvarga** [comment]
I don't understand your last comment, @beckysoll
How would it affect images that have been already uploaded?

**Comment by beckysoll** [comment]
@jasonvarga the file name changed, the underscore that had been in the filename prior to upgrade got changed to a dash, but the reference to it in the page content referred to the old filename (i wouldn't expect that part to automatically update, i just also wouldn't expect existing image filenames to change)

**Comment by jasonvarga** [comment]
So you re-uploaded a file you uploaded on 2.5 through the Assets section (not a fieldtype) ?

**Comment by jasonvarga** [comment]
Chatted with Becky in Slack.

Issue there is that there was a file uploaded in 2.5 that was unaffected by the slugified changes.
The image was deleted and re-uploaded in an attempt to replace it. In 2.6 the filename ends up slightly different, thus throwing off the content.

**Comment by jasonvarga** [comment]
In 2.6.1, the filename will not add the extension, and will leave underscores intact.

@lukeagsmith Here's the patch:

https://gist.github.com/jasonvarga/996caf5f9a1199eba88fc4c5200ea2d9

**Comment by lukeagsmith** [comment]
The fix works well, thank you.

For my tastes I would also like to see the filenames be lowercased as part of the slugification.

How do others feel about that?
