### ISSUE TITLE
The Lodge is blocked

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#1511]
I can't get into [the cosy Lodge](http://lodge.statamic.com/) – apparently a script prevents the site from working properly.

Firefox as well as Chrome load infinitely before offering to stop the script – when I do I cannot Login or Post, of course.

It's probably a quick fix that will make us welcome in the lodge again. (:

**Comment by jasonvarga** [comment]
Still?

**Comment by andypillip** [comment]
Now it works (:

Thanks a bunch – if you did something ^.^

**Comment by jasonvarga** [comment]
We deployed something on that site recently. Maybe you accessed it while the javascript was being deployed? ¯\_(ツ)_/¯ Works now!

**Comment by andypillip** [comment]
I'm sorry, I was too quick – the detail view of a question still has the issue.

**Comment by jasonvarga** [comment]
Can you give any more info? Seems fine over here.

**Comment by andypillip** [comment]
ok weird – it seems to be my own question only: https://lodge.statamic.com/questions/2791-cache-bust-external-css-and-js-in-v1

**Comment by andypillip** [comment]
@jasonvarga sorry but if my question has the issue, probably others have, too…

So the last fix might not have solved it, right?

**Comment by andypillip** [comment]
@jasonvarga I just realized that it must have to do with code tags in the question.

If I remove any code, the scripts runs fine.

**Comment by rrelmy** [comment]
I can confirm that this issue has some weird blocking issue :-)
