### ISSUE TITLE
Cannot create new taxonomy term in 2.6

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1513]
### Expected behaviour
Go to 'tags' under content in CP and create a tag. Tag should be created.

### Actual behaviour
Go to 'tags' under content in CP and create a tag - get error 'unauthorised'.

### Steps to reproduce
1. Open vanilla installation of 2.5 and go to 'tags' under content in the CP. Create a tag successfully. 2. Upgrade to 2.6 and clear cache and make sure perms are good
3. Go to 'tags' under content in the CP - cannot create a tag now, it just returns 'unauthorised'.

### Note
Terms are still created if created via an entry.

### Server Details

**Operating System**: OSX

**Web Server:** Apache

**PHP Version:** 5.6

**Statamic Version:** 2.6

**Updated from an older Statamic or fresh install:** Updated

**Comment by jasonvarga** [comment]
`statamic/core/Http/Controllers/PublishTaxonomyController.php` line 137

Change `extra.taxonomy` to `extra.group`.

**Comment by warkior** [comment]
Possibly related to this... we have a site recently upgraded to 2.6.1 and a couple taxonomy terms that are listed on an article but don't have physical files. They show up in the list of terms to edit for that taxonomy, but when I edit and try to save one, I get an "Unauthorized" error.
