### ISSUE TITLE
FR: Native way to collapse whitespace

### ISSUE THREAD

**Issue by MerlinBB** [statamic/v2-hub#1519]
Hey, not sure if this is a bug, feature request or I've just misunderstood the docs but here goes....

### Expected behaviour
Using `trim` on a replicator or asset field would generate HTML with no whitespace.

### Actual behaviour
HTML has whitespace.

### Steps to reproduce
```
{{ gallery | trim }}
        {{ assets:image | trim }}
        <img src="{{ glide:id width="400" height="200" }}" alt="{{ description }}" class="gallery-tile">
        {{ /assets:image }}
{{ /gallery }}
```
The intention is that the above will yield the same output as the below, but this is not the case.
```
{{ gallery }}{{ assets:image }}<img src="{{ glide:id width="400" height="200" }}" alt="{{ description }}" class="gallery-tile">{{ /assets:image }}{{ /gallery }}
```

### Server Details

**Operating System**: MacOS 10.12.5

**Web Server:** MAMP Pro

**PHP Version:** 7.0.15

**Statamic Version:** 2.5.11

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:** CookieConsent, Spock

### Use Case
This is particularly useful when relying on `display:inline-block;` for layout as white space is taken into account. Example styling:

```
.gallery-tile {
    width: 33.333%;
    margin: 0;
    display: inline-block;
    vertical-align: top;
}
```

Being able to `trim` blocks of code like this would allow you to author code in a more readable format.

**Comment by jasonvarga** [comment]
Hey there, a few things to note:

1. To apply a modifier to an array (tag pair), you should use the parameter syntax. `{{ gallery trim="true" }} {{ /gallery }}`, or use the pipe syntax on the closing tag (which is lame, so don't do that) eg. `{{ gallery |  trim }} {{ /gallery | trim }}`.
2. The `trim` modifier in your snippet is applying to the value of `gallery`, not the contents of the tag pair.

What you're probably looking for is another tag that wraps the whole thing, which strips out line breaks.

Here's one: https://github.com/marbles/statamic-spaceless

**Comment by MerlinBB** [comment]
Hey Jason, 

Thanks for getting back to me (and sorry for slow reply)... Cool the `spaceless` addon does the job perfect. I'd +1 the idea of having this built in as an antlers modifier in future though :)
