### ISSUE TITLE
Collection sort does not fallback on localized values 🇨🇭

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1520]
### Expected behaviour
`{{ collection sort="title" }}` should fallback to the default title if the localization does not have a title.

### Actual behaviour
It does not fallback to the default and sorts based on a lot of `null` values 

### Steps to reproduce
1. Create a  localized collection
2. Do not add localized titles
3. Try to output them sorted in the secondary locale

### Server Details
**Statamic Version:** 2.6.1

### Fix with hacking the core
`Statamic\Data\DataCollection->getSortableValues` uses `$a->get(` changing it to `getWithDefaultLocale` fixes the issue.

``` patch
Index: statamic/core/Data/DataCollection.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- statamic/core/Data/DataCollection.php	(revision aa7d324133c9a67a886e5c2b6648e770d58f49f6)
+++ statamic/core/Data/DataCollection.php	(revision )
@@ -77,8 +77,8 @@
     {
         $method = Str::camel($sort);
 
-        $one = (method_exists($a, $method)) ? call_user_func([$a, $method]) : $a->get($sort);
-        $two = (method_exists($b, $method)) ? call_user_func([$b, $method]) : $b->get($sort);
+        $one = (method_exists($a, $method)) ? call_user_func([$a, $method]) : $a->getWithDefaultLocale($sort);
+        $two = (method_exists($b, $method)) ? call_user_func([$b, $method]) : $b->getWithDefaultLocale($sort);
 
         return [$this->normalizeSortableValue($one), $this->normalizeSortableValue($two)];
     }

```

**Comment by subpixelch** [comment]
@jasonvarga fixed in next release? :-) low hanging fruit

**Comment by jasonvarga** [comment]
Done! Thanks for bumping this, and for the fix.
