### ISSUE TITLE
Antler old variable is not sanitized

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1521]
Not directly a feature request. I totally understand that could only be done in v3 or later
Or, it could be a setting that we can opt-in to  (thanks aryeh for the input) :-)

### Expected behaviour
Variable output through should be escaped unless otherwise stated.
Because nobody can write XSS proof code.

I assumed that behaviour because most other template language do it too.
Blade, Mustache, Twig (not sure about the default but in drupal for example) etc.

### Actual behaviour
~`{{ get:q }}` leads to XSS~ _Update: not since 2.1.19_
`{{ old:myvar }}` in form leads to XSS

It took me quite some time to realise this behaviour.
And I think most people are not knowing it 

### Steps to reproduce
1.  Create a form with an `{{ old }}` variable
2.  Submit the form with some XSS content like `"><h1>Oops`

**Comment by jasonvarga** [comment]
Adding `{{ get:q }}` to my template and visiting `?q=<script>alert(%27I%20am%20evil%27);</script>` outputs `/?q=<script>alert(%27I%20am%20evil%27);</script>`

What version are you on?

**Comment by rrelmy** [comment]
My bad, I tried to simplify the reproduction without testing it …
Indeed the `get`, `post` and `get_post` variables are sanitized by default since statamic 2.1.19.

At the time of opening the issue I had a form with the `old` variable which is not sanitized.
And remembered old times before 2.1.19

The documentation gives examples which are prone to XSS attacks
https://docs.statamic.com/tags/form-create
https://docs.statamic.com/tags/user-login_form
https://docs.statamic.com/tags/user-register_form
