### ISSUE TITLE
FR: Extend the wrap modifier to also take a class name

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#1522]
The [wrap modifier](https://docs.statamic.com/modifiers/wrap) is great and saves templates from a LOT of if statements, however just being able to pass in a tag doesn't always cut it. It'd be great if `wrap` took second param for a class name.

*Example*
```php
// Before
{{ if quote }}
    <p class="quote">{{ quote }}</p>
{{ /if }}

// After
{{ quote | wrap:p:quote }}
```

It'd only require a small change to the current tag:
```php
public function wrap($value, $params)
{
    $tag = array_get($params, 0);

    if ($class = array_get($params, 1)) {
        return "<$tag class='$class'>$value</$tag>";
    }

    return "<$tag>$value</$tag>";
}
```

The argument could be made that other attributes should then also be supported such as an `id`, however since this modifier exists solely for convenience I believe classes are more widely used than any other attribute.

**Comment by jasonvarga** [comment]
How about an Emmet-esque solution?

```
{{ quote | wrap:p.quote.pull-right }}
```

**Comment by aryehraber** [comment]
Yeah totes, even better!
