### ISSUE TITLE
New AJAX Save means flash cannot be seen

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1523]
Now entries/pages save via AJAX (really good!) the flash at the top showing if an entry/page has been saved can't be seen if you are a) using "save and continue" and b) scrolled down a bit.

This means the user has no idea if the entry/page has saved or not.

**Comment by lukeagsmith** [comment]
Just had a client email me about this very thing thinking the page isn't saving.

**Comment by anthubbard** [comment]
Technically the save button goes slightly lighter coloured whilst its saving then back to full colour when it's saved.

However it would be good to have some kind of icon / feedback to state the page has saved.

**Comment by jasonvarga** [comment]
Don't you get scrolled back to the top of the page?

**Comment by dannyuk1982** [comment]
Nope. Which is a good thing as that would be annoying if you were just saving and then continuing working

**Comment by anthubbard** [comment]
Agreed, I definitely wouldn't want to be scrolled to the top of the page and most of the time this doesn't happen - however occasionally it does happen to me, but only probably 1 in 30 odd saves.

Personally just something like a little green tick icon in the top right hand corner of the page when the ajax save request comes back successful would be great.

**Comment by jasonvarga** [comment]
I misunderstood guys, sorry. You only get scrolled up when there's an error.

The alerts will float over the top of the page regardless of scroll position, in the next release.
