### ISSUE TITLE
FR: Sort fieldsets by title instead of handle

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1526]
### Expected behaviour
The list of fieldsets should be sorted alphabetically

### Actual behaviour
Not sorted by title
![image](https://user-images.githubusercontent.com/442683/28621859-a31f8734-7212-11e7-8a59-8a2e428201b3.png)

### Affected places
 - Fieldset overview
 - Fieldset select suggestions

### Server Details
**Statamic Version:** 2.6.1

**Comment by lukeagsmith** [comment]
+1
