### ISSUE TITLE
Entering 0 in a field that saves as an array doesn't save the value

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1530]
Example: enter `0` into a text field inside a grid and hit save. The entry saves but the field with `0` won't be present.

**Statamic Version:**
2.6.1

**Comment by jasonvarga** [comment]
This is because it's falsey.

Where are you using the zero?
Where you're outputting it, can you treat null values as zeroes? Or do you need an explicit difference?

**Comment by lukeagsmith** [comment]
It's showing properties of products as numbers so putting `0` in the CP should output as 0 in the template.

There are 5 of these so would have to add the check into the template 5 times, but also the client got confused that the `0`s they were entering were disappearing when they went back to edit the entry again.

**Comment by jasonvarga** [comment]
I think you'll need to work around it for now.

Perhaps you can add it in the field instructions rather than just verbally explaining to your client.
`Leave blank for zero`.

Then in your template do `{{ the_value or '0' }}`
