### ISSUE TITLE
Can't use a modifier in a condition with spaces in the value

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1531]
With an array `something`, this

`{{ if (something | contains:Something) }}` works

But these don't

`{{ if (something | contains:"Something") }}`
`{{ if (something | contains:"Something else") }}`

**Comment by jackmcdade** [comment]
As expected. Those aren't valid syntax. Try this instead:

```
{{ if (something contains="Something else") }}
```

**Comment by dannyuk1982** [comment]
Ah ok, @jasonvarga advised that on slack.

Your suggestion throws

```
FatalThrowableError in Parser.php(1232) : eval()'d code line 135:
Parse error: syntax error, unexpected '='
```

**Comment by jackmcdade** [comment]
Rats. I'm on the go and typed that blind. What about simply `{{ if something contains="Something else" }}` ?

**Comment by dannyuk1982** [comment]
Nope, same parse error - I have been on this over an hour now, I have tried everything and every combination, `{`, `(`, nothing, even some weird syntax jrc9 came up with that isn't a syntax at all, haha. 

The only thing that doesn't throw a parse error is using the `|` syntax, but it always returns `false` even when it should match

**Comment by jackmcdade** [comment]
If you're gonna do it that way, leave the quotes out. It's very literal. E.g. ` {{ if something | contains:Something else }}`

**Comment by dannyuk1982** [comment]
Aha - that actually works, although it looks like it shouldn't!

**Comment by jackmcdade** [comment]
Indeed. lol
