### ISSUE TITLE
FR - Replicator 'create new set' after *this* set button

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1532]
I miss this from v1 and so do my clients.

In v1 there was a button in the top right hand corner of the replicator set next to the drag handle etc that allowed you to choose a replicator set to appear directly after *this* one. 

My clients sometimes use 15 - 20 sets per page or more and the pages can be incredibly long and its very painful dragging a set all the way from the bottom when you want to add something new to a page.

Please.

:)

Ant

**Comment by lukeagsmith** [comment]
+1

This would be a nice addition.

**Comment by dannyuk1982** [comment]
+1 too, they also really, really need labels on there
