### ISSUE TITLE
FR: addon command class should extend AbstractCommand

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1533]
### Expected behaviour
Partyline to just work and nice helpers like `checkInfo`

### Actual behaviour
We have to setup Partyline with `\Partyline::bind($this);` and can not access the helpers inside the `AbstractCommand`

### Server Details

**Statamic Version:** 2.6.1

**Comment by jasonvarga** [comment]
2.6.3 will automatically bind Partyline and give you access to those helpers.
