### ISSUE TITLE
Cannot update Taxonomy items

### ISSUE THREAD

**Issue by danielgormly** [statamic/v2-hub#1537]
### Expected behaviour
The New Taxonomy page loads correctly and I can add a new taxonomy item.

### Actual behaviour
A get request to `/cp/fieldsets//get?locale=en` fails to resolve when the `cp/taxonomies/terms/<name>/create` page loads, presumably because of the 2 `/`s. The loading bar spins indefinitely and attempting to save a new taxonomy item fails.

### Steps to reproduce
1.  Create new taxonomy
2.  Click Content > Taxonomy name (e.g. tags)
3.  Click Create Tag

### Server Details

**Operating System**: Ubuntu

**Web Server:** Nginx

**PHP Version:** 7

**Statamic Version:** 2.5.11, 2.6.1

**Updated from an older Statamic or fresh install:** Fresh install of 2.5.11 and updated to 2.6.1 manually

**List of installed addons:** None

### Logs
If any logs (browser, server, or Statamic) are appropriate...
<details>
```
Chrome: Latest stable
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8000/cp/fieldsets//get?locale=en
Uncaught (in promise) 
```
</details>

**Comment by jasonvarga** [comment]
Can you view the source of that page, search for `<publish title="Create a New Tag"` and tell me what's in its `fieldset-name` attribute?

**Comment by danielgormly** [comment]
Thanks I see what is happening now. I had a blank fieldset stored `statamic/site/settings/fieldsets/.yaml` for some reason. I think my Taxonomy was using the `.yml` file as its field-set reference instead of a null value. My issue is now resolved but I didn't manually create that `.yml` file which was causing my problems. Anyway maybe it's an edge case bug but maybe it might be worth ignoring the .yml file and disallowing field-sets with null names.

**Comment by danielgormly** [comment]
To describe the exact conditions:
1. Blank file at `/site/settings/fieldsets/.yaml`
2. Selected the blank option for fieldset in the Taxonomy edit menu.
3. In `/site/content/taxonomies/<taxonomy-name>.yml`, the field-set reference is ""

**Comment by jasonvarga** [comment]
Thanks for the info! I'm gonna close this one down.
