### ISSUE TITLE
Save and continue -- error?

### ISSUE THREAD

**Issue by cschweda** [statamic/v2-hub#1545]
I create a page, then hit 'Save and Continue'.

Brand new page, so it saves fine. Do a quick preview -- all is well.

I keep editing it, but when I hit 'Save and Continue' a second time -- I receive an error: "Page already exists."

Weird.

Then: hit 'Save'.

Error: 'Page already exists."

Essentially, once I hit 'Save and Continue' -- it saves, but I can't continue because all subsequent saves (or save-and-continues) tell me that the page already exists.

Is this a feature or a bug?

BTW -- running latest version: 2.63.

**Comment by anthubbard** [comment]
Bug. See here > https://github.com/statamic/v2-hub/issues/1514 @jasonvarga please fix, my clients are annoyed ;(

**Comment by cschweda** [comment]
Thanks. Yes -- I'm having a difficult time explaining to client to **not** save and continue until this is fixed.

Clients, of course, go ahead and save and continue -- and then lose content.

This one's a show-stopper. :(

**Comment by jackmcdade** [comment]
Will get it fixed ASAP

**Comment by anthubbard** [comment]
Thanks guys, love your work. It's fun working with really responsive devs. Makes our life so much easier and its very re-assuring.
