### ISSUE TITLE
Fieldsets don't show in CP after updating to 2.6.3

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1547]
### Expected behaviour
See the list of fieldsets

### Actual behaviour
CP shows create first fieldset page

### Steps to reproduce
1.  Upgrade to 2.6.3
2.  Click on fieldsets under configure in the CP

### Server Details

**Operating System**:
macOS Sierra

**Web Server:**
Valet

**PHP Version:**
7.1

**Statamic Version:**
2.6.3

**Updated from an older Statamic or fresh install:**
Upgraded from 2.5.9

**Comment by rrelmy** [comment]
I can not reproduce this in 2.6.3

**Comment by lukeagsmith** [comment]
Error in logs:

```
[2017-08-12 18:43:39] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function path() on null in /Users/luke/sites/foo.com/local/storage/framework/views/ca5e4dcfbe0571b9402ce2410f7e3589:3
```

**Comment by jasonvarga** [comment]
Any other details you can provide? What's in your fieldsets directory?

**Comment by lukeagsmith** [comment]
A lot!

![screen shot 2017-08-14 at 16 12 27](https://user-images.githubusercontent.com/16148258/29278021-6a43003c-810b-11e7-916e-fb2dd8d306b1.png)

**Comment by rrelmy** [comment]
I can reproduce it, it logs no error. The posted error is from something else.

It must be an error on the frontend side, the ajax call returns all the fieldsets.
To reproduce I just duplicated all my fieldsets by copying them.
![image](https://user-images.githubusercontent.com/442683/29278609-8c1d9bea-8115-11e7-95e8-d705db7dd7a1.png)

Note sure what the real problem is

**Comment by jasonvarga** [comment]
Luke sent me his fieldsets. I'll get it. Thanks!

**Comment by rrelmy** [comment]
It breaks if you have more than 16 fieldsets.
Has nothing todo with the pagination size

**Comment by rrelmy** [comment]
The Ajax response is an object instead of an array I wonder how this happens 😄

**Comment by rrelmy** [comment]
@lukeagsmith You can add following method in `FieldsetController` to temporarily fix it until they officially fix it

``` patch
Index: statamic/core/Http/Controllers/FieldsetController.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- statamic/core/Http/Controllers/FieldsetController.php	(date 1502657489000)
+++ statamic/core/Http/Controllers/FieldsetController.php	(revision )
@@ -46,7 +46,7 @@
                 'uuid'     => $fieldset->name(), // keeping this here temporarily, just in case.
                 'edit_url' => $fieldset->editUrl()
             ];
-        })->filter()->all();
+        })->filter()->values()->all();
 
         return ['columns' => ['title'], 'items' => $fieldsets];
     }

```

**Comment by jasonvarga** [comment]
Thanks Remy.
