### ISSUE TITLE
Replicator field with markdown loses markdown text visibility on close / expand

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1553]
In a replicator field with markdown in it if you close that field then expand it again the markdown text doesn't show until you click into the markdown text box. Bug or feature?

**Comment by jasonvarga** [comment]
Can you explain this in more detail? Maybe upload a gif of the behavior? I can't replicate (ha) this behavior.

**Comment by anthubbard** [comment]
Yeah ok - you have to move the replicator set. So close the set visibility then move it somewhere else in the set and then re-open - the markdown field looks like it's empty, you have to click on it to then see your text again. See if you can replicate (:) that. If not, GIF coming your way

**Comment by jasonvarga** [comment]
Replicated. It's to do with CodeMirror (the plugin that's powering the markdown field).

https://stackoverflow.com/questions/8349571/codemirror-editor-is-not-loading-content-until-clicked

It's kind of a perfect storm of an edge case. You gotta hide it, rearrange it, then show it (like you described). Thanks for the info.

**Comment by anthubbard** [comment]
Thanks man. Your release schedule is amazing &#128077;
