### ISSUE TITLE
FR: Ability to duplicate a collection entry or page

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1554]
I have a client who creates event entries on their website and every entry has a fair bit of information to enter but every entry is basically identical (with just different details) - so it would be much faster for them to duplicate an existing entry and then change the details rather than having to build each entry out.

**Comment by edalzell** [comment]
@anthubbard: https://github.com/dannyuk1982/statamic-Duplicate

**Comment by anthubbard** [comment]
You are the freaking man. Thanks!

Ant
