### ISSUE TITLE
Invalid credentials error, can only be fixed by clearing cache

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1558]
There is some kind of cache issue (I assume) that causes the CP to randomly logout for no reason and return an error 'Invalid Credentials' when trying to log back in. The user cannot log back into the CP until the cache is cleared.

**That makes this a show stopper - because clients cannot clear the cache and therefore will be locked out of their own CP for no apparent reason. They will then have to contact the dev and we'll have to apologise and clear the cache etc etc.**

I'm in the middle of upgrading 15 client sites to V2 with another 20ish to go after that. This would be a huge issue with 30 clients logging into their CP's regularly.

The biggest problem is I cannot reproduce it, it just seems to happen randomly, and there are no logs of any kind created when the error occurs. 

This may be related to https://github.com/statamic/v2-hub/issues/1048 but that issue is quite old and hasn't been updated for a long time, which is odd for such a show stopping bug.

### Steps to reproduce
Cannot reliably reproduce but it has occurred multiple times on 4 different sites (at least 15 times). This is fine whilst in dev and with the ability to clear cache from bash but not for a client who relies on the CP.

### Server Details

**Operating System**: OSX / Linux

**Web Server:** Apache

**PHP Version:** 5.6

**Statamic Version:** 2.6.1

**Updated from an older Statamic or fresh install:** Update

**List of installed addons:**

**Comment by jackmcdade** [comment]
Does it happen in 2.6.4? There were some caching issues we fixed in 2.6.2+ that might do it for you!

**Comment by jasonvarga** [comment]
Does this happen locally or just on production? What kind of server?
Can you send me a zip of your site? support@statamic.com

**Comment by jasonvarga** [comment]
Does this happen when you are doing something like submitting a page? Or just when navigating around?

**Comment by anthubbard** [comment]
It has happened to me whilst:

- saving a page
- just scrolling within a page
- adding an asset
- adding or moving a replicator set

It's occurred in both dev and production environments.

Ant

**Comment by jasonvarga** [comment]
You scrolled a page and got redirected to the login screen without clicking anything?

**Comment by jasonvarga** [comment]
Likely fixed in 2.6.2
