### ISSUE TITLE
User gets logged out when trying to edit specific pages or globals

### ISSUE THREAD

**Issue by peda** [statamic/v2-hub#1560]
### Expected behaviour
When a user (with admin permissions) does access a page or globals and want's to edit them, he should stay logged in and be able to edit them. 

### Actual behaviour
In ~60-70% of the cases the user gets redirected to the login screen with the the error message "session expired"

There is nothing in the PHP error logs and nothing in the Statamic logs

### Steps to reproduce
1.  This issue does occur on one specific live customer website (I can provide a bundle of the entire website - just let me know whom I should email it to)

### Server Details

**Operating System**: CentOS release 6.9 (Final)

**Web Server:** Apache/2.2.15 

**PHP Version:** PHP 5.6.31

**Statamic Version:** 2.6.4

**Updated from an older Statamic or fresh install:** Updated from older version

**List of installed addons:**

### Logs
nothing gets logged ...

**Comment by peda** [comment]
It might be related to the Stache - as enabling "update Stache on every request" seems to fix this issue, but that's obviously no solution for a production website

**Comment by jasonvarga** [comment]
Would you consider this a large site? About how many pages, entries, etc?

**Comment by jasonvarga** [comment]
Please email a zip of the site to support@statamic.com

**Comment by peda** [comment]
I would consider it a small to medium sized site with 37 pages and 32 entries

I'm right now uploading the zipped website to wetransfer and will send it to you in a few minutes - please be aware that "update stache on every request" is disabled at the moment. Once I re-enable this problem keeps happening again.

Clearing all caches didn't help either.

**Comment by anthubbard** [comment]
This has happened to me also, a lot, and almost always on large pages with heaps of replicator and asset sets (20 +). I was wondering if it were a cache / memory issue... It could also be related to https://github.com/statamic/v2-hub/issues/1558

**Comment by peda** [comment]
@jasonvarga just wanted to let you know that the wetransfer link I sent you is about to expire on 25th August

**Comment by benjamin** [comment]
@jasonvarga Did this get fixed/released - because I'm seeing the exact same thing on a site running v2.8.3. Let me know what info you need to help debug it...

**Comment by markdavies** [comment]
@jasonvarga I'm also seeing this a lot, any update on when we'll see a fix?

**Comment by benjamin** [comment]
Yeh, happens so frequently that it pretty much makes the control panel unusable for editing content.

**Comment by markdavies** [comment]
For us we've discovered that it's whenever we hit our front end, we get logged out of the back end. 

We think it's because we're running Statamic in a sub directory of a Laravel site, maybe the sessions are conflicting?

**Comment by benjamin** [comment]
Thanks @markdavies but that's definitely not the issue we're having - Statamic is running all by itself on my server and the frontend is "essentially" just static html/js.

**Comment by peda** [comment]
@benjamin in some cases when I had this issue it was a corrupt page *.md file - so when this issue does occur and can not be (temporarily) resolved by clearing the cache - have a look at the latest modifications to your pages (and collections and taxonomies). If clearing the cache does help, then it's most likely related to a caching issue (like the one I reported a while ago)
