### ISSUE TITLE
Collection tag throws error when using pagination and no entries and no limit set

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1564]
As it says, if there is a collection with no entries, and with pagination set, and no limit set on the loop it throws an error:

```
ErrorException in CollectionTags.php line 489:
Division by zero
```

This isn't so much a bug, as a need to update the docs and specify that limit="x" is required when using pagination.

On 1.6.4 but probably earlier versions also.

**Comment by pinkahd** [comment]
This issue still occurs in Statamic version 2.8.8
