### ISSUE TITLE
Mailer is ignoring any PhpMailer settings, especially SMTP (v1)

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#1568]
See also my comment in the Lodge: [Raven not sending email](https://lodge.statamic.com/questions/2061-raven-not-sending-email#reply-2)

Take a look at this code from *_app/core/email/phpmailer.php*, please:

```php
    public function __construct($attributes)  
    {
      $this->mailer = $this->createMailer();
      $this->attributes = $attributes;

    …

    private function createMailer()
    {
        $this->mailer = new PHPMailer(true);

        if ($this->attributes['smtp']) {
            $this->smtp();
        } elseif (array_get($this->attributes, 'sendmail')) {
            $this->mailer->isSendmail();
        } else {
            $this->mailer->isMail();
        }
```

_createMailer()_ is checking for smtp and sendmail settings – but the constructor is only passing the settings AFTER calling that function.

Hence, no SMTP or Sendmail are possible.

Thanks for caring (:

**Comment by andypillip** [comment]
Unfortunately this is not the only bug.

In line 68 `$this->mailer->$method($value);` will call f.e. `PHPMailer::host()`, which doesn't exist, it's properties instead.

**Comment by andypillip** [comment]
Last but not least the `username` and `password` settings will be ineffective, if one doesn't set

```YAML
smtp:
  auth: true
```

**Comment by jasonvarga** [comment]
We appreciate the report and fix. Can you please post it to that thread on the Lodge? This repo is for v2.

**Comment by andypillip** [comment]
@jasonvarga just did
https://lodge.statamic.com/questions/2061-raven-not-sending-email#reply-2
