### ISSUE TITLE
Control panel not working when installing in a subdirectory

### ISSUE THREAD

**Issue by mrleblanc101** [statamic/v2-hub#1569]
### Expected behaviour

The installer should be working when the website is inside of a subdirectory. Both the installer and the control panel should then be styled properly so they can be usable.

### Actual behaviour

Hi,

I tried installing Statamic in ~/Sites/statamic-project/ using macOS built-in web server. I got the public site working at this following url [http://localhost/~USERNAME/statamic-project/](http://localhost/~USERNAME/statamic-project/) by following the installing instruction on the website inside subdirectory without difficulty . 

Now I went to the installer url and since the sever was compatible I followed with the next step but that's where things stop working. The page is unstyled and not working as expected. In the "Progress" section I have "{{ step.label }}" and right under it some text says I should delete this file since I completed the installation (which I haven't started yet). It seems like none of the assets are loaded because Chrome console shows a lot of "404 Not found" [http://localhost/~USERNAME/statamic-project/index.php/_resources/cp/js/cp.js?v=2.6.6](http://localhost/~USERNAME/statamic-project/index.php/_resources/cp/js/cp.js?v=2.6.6) but I know I got URL rewriting working because otherwise I wouldn't be able to navigate the public site. 

I tried to access the control panel by creating a user with '''php please make:user''' and it worked but the control panel is completely unstyled too. I tried about everything I could find in the lodge like making sure I have trailing slash in my .htaccess, index.php and system.yaml, or moving my website to /Library/WebServer/Documents and using the URL [http://localhost/statamic-project](http://localhost/statamic-project) instead after having adjusted the above files value. 

I also joined the Statamic-v2 slack channel where Erin Dalzell (emd) faced the same issue when using Statamic inside of a subdirectory using a different web server (Valet) so we figured that it must be a Statamic bug and not one from our configuration. Here's a screenshot of what's actually happening [http://imgur.com/a/EwYos](http://imgur.com/a/EwYos).

### Steps to reproduce
1.  Unzip Statamic in a subdirectory of your web server
2.  Adjust the URL in the .htaccess, index.php and settings.yaml accordingly 
3.  Launch the Statamic installer
4. Click next after the server config validation
5. No step 5, that's where it stops working

### Server Details

**Operating System**:
macOS 10.13 beta 7
**Web Server:**
Apache 2.4.27
**PHP Version:**
7.1.7
**Statamic Version:**
Statamic 2.6.6 (latest)
**Updated from an older Statamic or fresh install:**
fresh
**List of installed addons:**
none

### Logs
If any logs (browser, server, or Statamic) are appropriate...
[http://imgur.com/a/EwYos](http://imgur.com/a/EwYos)

**Comment by jackmcdade** [comment]
Should be working now. 👍
