### ISSUE TITLE
Proper documentation for folder.yaml

### ISSUE THREAD

**Issue by rockethouse** [statamic/v2-hub#1570]
Just a quick one... can we get some proper documentation for the folder.yaml file in terms of what options we have for controlling ordering and sorting as well as columns and if any of this can be extended via an addon?

For eg I want to order by number (I worked that out by trial and error) but I also want to set it to default sorting descending, so highest number first... something like `order: number-descending` would work a treat.

**Comment by jasonvarga** [comment]
Can you please open this at https://github.com/statamic/docs/issues ?
