### ISSUE TITLE
Sneak Peek Cursor Jumps

### ISSUE THREAD

**Issue by warkior** [statamic/v2-hub#1573]
### Expected behaviour
When editing the content of an article using the left-hand pane in "sneak peek" view, the cursor should remain where it is placed and allow adding or modifying text at that location.

### Actual behaviour
Instead, after the page is first loaded, when you click in the page content box and type a character, the cursor jumps down a few paragraphs and adds (or removes) the character there instead. After this, when clicking and editing again it works fine.

### Steps to reproduce
1.  Use the CP to open the editing view for an entry.
2.  Click "Sneak Peek" to view the page with the left side editing area.
3.  Scroll down in the left sidebar to the content box. Click somewhere in the middle of the existing content text.
4. Type a character.
5. Watch your cursor jump further down in the content and add the character.

### Server Details

**Operating System**:
Ubuntu

**Web Server:**
Nginx

**PHP Version:**
7.1

**Statamic Version:**
2.6.4

**Updated from an older Statamic or fresh install:**
Updated

**Comment by jasonvarga** [comment]
What fieldtype? Markdown?

**Comment by warkior** [comment]
Yes. It's a markdown field.

**Comment by warkior** [comment]
@jasonvarga - I just upgraded on of our sites to 2.6.8 and can confirm that the issue still exists.

**Comment by warkior** [comment]
@jasonvarga - This issue still exists on 2.7.1

**Comment by jackmcdade** [comment]
When we can get it fixed we'll close the issue.
