### ISSUE TITLE
Allow Redis host to be configurable through environment

### ISSUE THREAD

**Issue by jackwakefield** [statamic/v2-hub#1578]
The Redis configuration in `statamic/config/database.php` is currently hardcoded as
``` 
'redis' => [

    'cluster' => false,

    'default' => [
        'host'     => '127.0.0.1',
        'port'     => 6379,
        'database' => 0,
    ],

]
```

This is an issue when the Redis server is located anywhere but localhost, for example when the Redis server is hosted within a separate Docker container.

### Server Details

**Operating System**: CentOS 6.9

**Web Server:** Apache 2.4

**PHP Version:** 7.1.7

**Statamic Version:** 2.6.8

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:** Custom project-specific addons

**Comment by jackwakefield** [comment]
A patch for this could be

```diff
diff --git a/statamic/config/database.php b/statamic/config/database.php
--- a/statamic/config/database.php
+++ b/statamic/config/database.php
@@ -115,9 +115,9 @@ return [
         'cluster' => false,

         'default' => [
-            'host'     => '127.0.0.1',
-            'port'     => 6379,
-            'database' => 0,
+            'host'     => env('REDIS_HOST', '127.0.0.1'),
+            'port'     => env('REDIS_PORT', 6379),
+            'database' => env('REDIS_DATABASE', 0),
         ],

     ],
```

**Comment by jasonvarga** [comment]
What Statamic version are you on?

**Comment by madsem** [comment]
This should be reopened, it's not possible to configure a cluster, which is how AWS Elasticache often is set up. Currently having exactly this issue, Statamic is supposed to connect to an existing Redis cluster on Elasticache...

**Comment by madsem** [comment]
FYI, something like this would allow connecting to a remote Redis cluster like Elasticache (tested):

```php
'redis' => [

        'cluster' => false,
        'client'   => 'predis',
        'options'  => [
            'cluster' => 'redis',
        ],
        'default' => [
            'host'     => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port'     => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DATABASE', 0),
        ],

    ],
```

But it seems currently this is only doable by hacking the core config? Or is there another way?

**Comment by madsem** [comment]
Okay actually, I found a better way for v2, and v3 will be freely configurable anyways.
So anyone who is searching for this, just make a small addon ServiceProviderand override the container settings for `database.redis`:
```php
<?php

namespace Statamic\Addons\RedisClusterConfigurator;

use Statamic\Extend\ServiceProvider;

class RedisClusterConfiguratorServiceProvider extends ServiceProvider
{

    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        $redisConfig = config('database.redis');
        $redisConfig['client'] = 'predis';
        $redisConfig['options']['cluster'] = 'redis';

        // override config with cluster setting
        config(['database.redis' => $redisConfig]);
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```
