### ISSUE TITLE
Regression: Saving routes in CP creates string instead of array. Will cause error on template routes

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1581]
### Expected behaviour
Don't break my site

### Actual behaviour
Breaking my site :-)

Saving the route settings in the cp will add strings to the yaml file instead of nothing or a empty array
``` yaml
vanity: ""
```

There is an array_key_exists expects param 2 to be array, string given error inside StatamicController on line 344.

### Steps to reproduce
1.  Save empty vanitiy routes in CP
2.  Visit a template mounted via route
3.  See an error

### Server Details
**Statamic Version:** 2.6.8

**Comment by jasonvarga** [comment]
Knew that change was too good to be true.

**Comment by lukeagsmith** [comment]
Just bumped into this one too!
