### ISSUE TITLE
Commas don't get removed from sanitised filenames on upload

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1584]
### Expected behaviour

`silly, client filename.docx` = `silly-client-filename.docx`

### Actual behaviour

`silly, client filename.docx` = `silly,-client-filename.docx`

**Statamic Version:**
2.6.8

**Comment by dannyuk1982** [comment]
What is the problem with keeping commas?

**Comment by lukeagsmith** [comment]
Neatness, portability, best-practice, sanity!

https://support.apple.com/en-gb/HT202808
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_282

I guess for all the same reasons they get stripped out of slugs.

**Comment by jackmcdade** [comment]
They should now!
