### ISSUE TITLE
Client getting "Your session has expired" upon logging in.

### ISSUE THREAD

**Issue by arvdsn** [statamic/v2-hub#1591]
### Actual behaviour
In both IE and Chrome, client is getting "Your session has expired". This does not happen for me, in any browser and it is hosted remotely for both of us so circumstances should be the same.

We've also tried with and without cache, and php please cache clean was run during every settings change.

### Steps to reproduce
1.  Log in to /cp/
2.  ...
3.  No profit.

### Server Details

**Operating System**:
>Ubuntu 16.04.3 LTS

**Web Server:**
>Server version: Apache/2.4.18 (Ubuntu)
>Server built:   2017-07-27T14:34:01

**PHP Version:**
>PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
>Copyright (c) 1997-2017 The PHP Group
>Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
>   with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**Statamic Version:**
>Statamic 2.6.6

**Updated from an older Statamic or fresh install:**
Updated from old version.

**List of installed addons:**
>Bluebird 1.0 (Is not listed as installed in /cp/, but works it seems)
>Disqus 1.0

### Logs
Nothing in any logs except the following below which might be related.

<details>
```
[2017-09-08 08:21:30] production.ERROR: ErrorException: unserialize(): Error at offset 2 of 69622 bytes in /rootpath/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:78
```</details>

**Comment by arvdsn** [comment]
Updating 2.6.8 seems to have resolve the issue, not sure why though. Could also be that we removed everything and did a git pull to host. Maybe there was some missing file in the statamic folder.

**Comment by arvdsn** [comment]
This issue is now back. Same server, only difference is we are using 2.6.8.

**Comment by jasonvarga** [comment]
Are you accessing the site from both www and non-www?

**Comment by arvdsn** [comment]
When testing it with the client now it seems that non-www works. Is there an apparent cause for this?
