### ISSUE TITLE
FR: Separate pagination size setting for Assets and Collections

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/v2-hub#1592]
To help with some of the [limitations](https://github.com/statamic/v2-hub/issues/1207) of pagination, it would be useful to set the pagination size separately for Assets and Collection lists. 

I’d like to have a longer list of collection entries, so it can be reordered still, but loading a longer list causes speed issues in the assets. Having two separate settings would help get us closer.

**Comment by jackmcdade** [comment]
Will likely be a part of v3.
