### ISSUE TITLE
get_content throws error when `from` param can't be found

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#1598]
### Expected behaviour
When a page can't be found using the `from` param, `get_content` should fail silently just like when the fields/variables between the tag pair can't be found.

### Actual behaviour
A fatal error is thrown:

```
FatalThrowableError in GetContentTags.php line 45:
Call to a member function in() on null
```

### Steps to reproduce
This snippet will fail when `segment_1` isn't an actual standalone page:

```
{{ get_content from="/{segment_1}" }}
    // Do stuff and things
{{ /get_content }}
```

### Temp. solution
```php
$this->collection = collect_content(
    Helper::explodeOptions($locations)
)->map(function ($from) use ($locale) {
    return ($content = $this->getContent($from))
        ? $content->in($locale) : null;
})->filter();
```

**Comment by alehandrof** [comment]
Relatedly, it would be helpful if there's a `no_results` variable so that I can check in the template if it's failed and do appropriate things. Shall I open a separate FR for this?
