### ISSUE TITLE
S3 assets cannot be cached by image manipulation

### ISSUE THREAD

**Issue by jackwakefield** [statamic/v2-hub#1599]
### Expected behaviour
Enabling both ["Serving Cached Images Directly"](https://docs.statamic.com/tags/glide#serving-cached-images) and [Amazon S3](https://docs.statamic.com/assets#asset-container-drivers) should cache manipulated images to be served directly.

### Actual behaviour
The image isn't generated, a log entry is added with:
```[2017-09-14 23:46:23] dev.ERROR: File not found at path: https:/xxxxx.s3.eu-west-2.amazonaws.com/xxxxx.jpg```

I've narrowed this down to `StaticUrlBuilder::generatePath()`, I've added a crude fix for this which checks whether the item type is `url` and instead calling `ImageGenerator::generateByUrl()`.

There is a similar issue with the `GlideTags::generateImage`, I've fixed this with the following

```diff --git a/statamic/bundles/Glide/GlideTags.php b/statamic/bundles/Glide/GlideTags.php
--- a/statamic/bundles/Glide/GlideTags.php
+++ b/statamic/bundles/Glide/GlideTags.php
@@ -79,9 +79,15 @@ class GlideTags extends Tags
     {
         $params = $this->getGlideParams($item);
 
-        return (Str::isUrl($item))
-            ? $this->getGenerator()->generateByPath($item, $params)
-            : $this->getGenerator()->generateByAsset(Asset::find($item), $params);
+        if (Str::isUrl($item)) {
+            if (!URL::isExternalUrl($item) || strpos($item, '/') === 0) {
+                return $this->getGenerator()->generateByPath($item, $params);
+            }
+
+            return $this->getGenerator()->generateByUrl($item, $params);
+        }
+
+        return $this->getGenerator()->generateByAsset(Asset::find($item), $params);
     }
 
     /**
```
### Steps to reproduce
1.  Configure cached images - https://docs.statamic.com/tags/glide#serving-cached-images
2.  Configure S3 - https://docs.statamic.com/assets#asset-container-drivers
3.  Use the `glide(:generate)` tag

**Operating System**: CentOS 6.9

**Web Server:** Apache 2.4

**PHP Version:** 7.1.7

**Statamic Version:** 2.6.8

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:** Custom project-specific addons

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
