### ISSUE TITLE
FR (kinda): Statamic source code on Github

### ISSUE THREAD

**Issue by jackwakefield** [statamic/v2-hub#1601]
I believe it would be of great benefit to host the source for Statamic on GitHub. This will allow for pull requests to be submitted by the community for and alongside issues being reported, and make forks much easier to maintain across updates.

I understand the project requires a license to run, with the code available before purchasing a license, and there may be business-cases for keeping the source code away from GitHub, but I'm interested in opening up an discussion around that.

**Comment by codyspring** [comment]
I'd be interested in this as well. It's got a free download/trial period for development. Having the ability to directly contribute to the codebase would be wonderful. Craft takes this approach: https://github.com/craftcms/cms

**Comment by jasonvarga** [comment]
It's going to be opened up for v3. 👍
