### ISSUE TITLE
Sneak Peek in secondary locale doesn't work

### ISSUE THREAD

**Issue by subpixelch** [statamic/v2-hub#1602]
### Expected behaviour
Preview of pages in different locale than main should show up.

### Actual behaviour
Tell us what happened instead

The spinning wheel of death:
<img width="672" alt="personen___statamic" src="https://user-images.githubusercontent.com/5087726/30485704-8f5d8388-9a2e-11e7-90c0-e3ef2f0a8bf5.png">

### Steps to reproduce
1.  Try to preview the second locale in your CP
2.  ... 
3.  ...
4.  ...
5.  ...
6.  ...
7.  ...
23683.  ...
53468733.  ...
99989734331. ... still spinning??

### Server Details: Valet Mac
**PHP Version:** 7.1
**Statamic Version:** 2.6.8

**Comment by jasonvarga** [comment]
I hope you didn't actually wait until 99989734331 :)

**Comment by jasonvarga** [comment]
Any errors or more details you can provide? This seems to work on my end.
