### ISSUE TITLE
Sections don't display in secondary locale

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#1605]
### Expected behaviour
Section fieldtypes are displayed for secondary locales.

### Actual behaviour
Sections aren't displayed, unless `localizable: true` is set.

### Steps to reproduce
1. Create an additional locale.
2. Add a section to a fieldset.
3. Edit that page in secondary locale.
4. See that section is missing.
5. Add `localizable: true` to the section's settings.
6. See that section appears.

### Server Details

**Operating System**: Alpine Linux 3.6.2

**Web Server:** nginx 1.12.1

**PHP Version:** 7.1.5

**Statamic Version:** 2.6.8

**Updated from an older Statamic or fresh install:** fresh

**Comment by FrittenKeeZ** [comment]
Then again, it might be weird having sections showing for fields not being translatable.

**Comment by jasonvarga** [comment]
By design. If you have a section then non-localizable fields, then another section - you'd end up with an empty section.
