### ISSUE TITLE
Send form email notifications based on form field values.

### ISSUE THREAD

**Issue by codyspring** [statamic/v2-hub#1607]
It would be nice if we could send form email notifications based on input values in a form. Specifically, I'm looking at something like a department select field that routes the email accordingly.

**Comment by gmcz** [comment]
I think you can use antlers if tags in your form yaml.

**Comment by codyspring** [comment]
@gmcz Could you explain what you mean by that?

**Comment by gmcz** [comment]
‘to: {{ if department == sales }} sales@email.com{{elseif department == management }}manager@email.com{{ else }}general@email.com{{ /if }}’

I’m 99% sure I did this on a project.

**Comment by codyspring** [comment]
That would be awesome. I'll test this asap and report back. Thanks for the tip!
