### ISSUE TITLE
Form submissions with assets uploaded to S3 can't be accessed via CP

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#1608]
### Expected behaviour
A form submission's asset (URL) should be clickable when viewed via the CP.

### Actual behaviour
The name of the file is shown but isn't a link to the actual URL where the file exists (this _does_ work as expected when using local assets).

Note that when viewing the submission's actual yaml file, the full S3 URL is present meaning somewhere along the way it gets stripped to just the file name.

**Comment by jasonvarga** [comment]
How did you upload the file to S3? Is it an asset/assets field?

**Comment by aryehraber** [comment]
Yeah, it's an `asset` field:
```
fields:
  cv:
    type: asset
    container: main
    folder: cv
    display: CV
```

After submitting the form on the front-end, the data gets saved like so:
```
cv: >
  https://s3.amazonaws.com/***/cv/Screen-Shot-2017-10-02-at-18.21.40.png

```

In the CP it looks like (_the filename is not a link_):
<img width="548" alt="screen shot 2017-10-02 at 18 26 11" src="https://user-images.githubusercontent.com/5065331/31087940-3775b914-a79f-11e7-8130-ccb77fe701dc.png">

**Comment by jasonvarga** [comment]
How are you getting the URL of the image once you upload it to S3?

**Comment by aryehraber** [comment]
Oh sorry, maybe I wasn't clear... It's in the form submission's `yaml` file. I truncated the data before but this is the full submission:

```
name: Test
email: test@test.com
phone: "0124324325435"
cv: >
  https://s3.amazonaws.com/***/cv/Screen-Shot-2017-10-02-at-18.21.40.png
message: testing...
```

I should also note that it outputs fine in the email that is fired off after a submission (custom template).

**Comment by jasonvarga** [comment]
My bad, haha, I forgot that we automatically send it to S3 for you. 😊 

Anyway, this seems to work just fine for me.

What I noticed is that you can access the same file from: https://bucketname.s3.amazonaws.com/file.jpg and https://s3.amazonaws.com/bucketname/file.jpg

Technical details aside, in my tests, Statamic seems to use the subdomain version, but your yaml has the subdirectory version.

Can you show me whats in your `site/assets/main.yaml`? (Without your S3 credentials of course)

**Comment by aryehraber** [comment]
Haha, no worries.

Sure, here it is:
```
title: S3
driver: s3
key: ***
secret: ***
bucket: cdn.companyname.com
path: /marketing
region: us-east-1
```

**Comment by jasonvarga** [comment]
Do you have other asset containers?

**Comment by aryehraber** [comment]
The site used to have a local asset container but I removed it after creating this new one for S3, so now there's just this one.

**Comment by jasonvarga** [comment]
Talked more in Slack. The issue was the leading slash in `path` resulting in a double slash in the container URL, which screwed something up down the road.

Temporary fix was to change `path: /marketing` to `path: marketing` but a real fix is pending release.

**Comment by coldfuzion** [comment]
What about for private containers that are below statamic root?
