### ISSUE TITLE
Taxonomies not being validated

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#1610]
### Expected behaviour
Specifying `validate: required` on `taxonomies` enforces those fields to be filled out.

### Actual behaviour
Empty fields are allowed.

### Steps to reproduce
1. Add `validate: required` to `taxonomies`.
2. Save without filling the fields.
3. See that the entry is saved without errors.

### Server Details

**Operating System**: Alpine Linux 3.6.2

**Web Server:** nginx 1.12.1

**PHP Version:** 7.1.5

**Statamic Version:** 2.6.9

**Updated from an older Statamic or fresh install:** 2.6.8

**Comment by aerni90** [comment]
Would be great if taxonomies could be validated!
