### ISSUE TITLE
Stache is rebuilt when switching between console and browser

### ISSUE THREAD

**Issue by warkior** [statamic/v2-hub#1611]
### Expected behaviour
I would assume, that once the stache has been built, it should remain "valid" regardless of whether being access via browser call or commandline.

### Actual behaviour
After running `php please clear:cache`: When I run `php please list` on the site, it loads very slowly (large site) while it builds the stache files. Subsequent runs of `list` seem to be fast again, presumably using the pre-built stache. 

Then, when I load a web page the first time, the stache files are DELETED and rebuilt, along with several other cache files. Then, then after it’s built, subsequent loads of the website are fast.

However, if I go back and run `php please list` again, the stache files are once again DELETED and rebuilt, taking quite a while the first time.

This pattern can continue to repeat with each switch.

### Steps to reproduce
1.  `php please clear:cache` [deletes stache files]
2.  `php please list` [slow first time while building stache]
3.  `php please list` [fast on subsequent tries]
4. View site in browser [slow. deletes stache and rebuilds]
5. Reload site in browser [fast since it now uses the stache again]
6. `php please list` [slow. deletes stache and rebuilds]

**Statamic Version:**
2.6.9

**Updated from an older Statamic or fresh install:**
Updated

**Comment by warkior** [comment]
This issue still seems to exist in statamic 2.7.1. The fix mentioned to me originally by @jasonvarga  (I think) was to modify line 236 of statamic/core/Providers/StacheServiceProvider.php and comment out the line that reads: `Config::set('system.ensure_unique_ids', false);`

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
