### ISSUE TITLE
Unable to create taxonomy if only using a field set with no fields

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#1615]
### Expected behaviour
Create new taxonomy records that just have the default title field (and slug).

### Actual behaviour
After entering a value in the title field and tabbing or clicking on the slug field the value disappears from the title field.

### Steps to reproduce
See above.

### Server Details
Statamic 2.6.9, happens in multiple environments.

### Logs
None.

**Comment by aerni90** [comment]
Same problem here. Would really appreciate a fix.
