### ISSUE TITLE
Failed ajax form requests return error messages without related fields

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#1617]
### Expected behaviour
Performing an ajax form submission that fails, you get a list of error messages for each failed field validation.

### Actual behaviour
All error messages are merged in an array, without any relation to their fields.

### Steps to reproduce
1. Submit a form through ajax which will fail.
2. See that the response errors only contain the error messages.
3. Cry about not knowing which fields failed validation.

### Server Details

**Operating System**: Alpine Linux 3.6.2

**Web Server:** nginx 1.12.1

**PHP Version:** 7.1.5

**Statamic Version:** 2.6.9

**Updated from an older Statamic or fresh install:** 2.6.8

### Possible fix
Looking at `Statamic\Addons\Form\FormListener` line 113 could be changed from `'errors' => (new MessageBag($errors))->all()` to `'errors' => $errors`.

**Comment by FrittenKeeZ** [comment]
@jasonvarga have you had a chance to look at this?

**Comment by marsvogel** [comment]
I have the same Problem. I'm getting an array without any related field names instead an object. The possible fix from @FrittenKeeZ does the trick for me.

**Comment by marsvogel** [comment]
@jasonvarga have you had a chance to look at this? Right now I'm applying my Hotfix after every statamic upgrade 🙈

![image](https://user-images.githubusercontent.com/263284/42223539-491351b6-7ed8-11e8-9f89-e010e14e8b1c.png)

**Comment by FrittenKeeZ** [comment]
This is still pretty relevant.

**Comment by marsvogel** [comment]
@jasonvarga have you had a chance to look at this?

**Comment by rrelmy** [comment]
We also have this problem.

I think a simple workaround could be to change the visibility of the methods in the `FormListener` from `private` to `protected` to be able to overwrite them. Even if this is exposing internal API structure …

**Comment by sameerpanjwani** [comment]
Having the same issue, the fix by @FrittenKeeZ works but would be good to have it as a permanent fix.

**Comment by jasonvarga** [comment]
Um. 😊 This will be in the next release.

Although instead of changing `errors`, I'll add what you need into a new variable called `field_errors`. Otherwise we'd be breaking anyone relying on how it currently works.

**Comment by FrittenKeeZ** [comment]
@jasonvarga that's quite alright :)
