### ISSUE TITLE
New CP issue in Safari

### ISSUE THREAD

**Issue by rockethouse** [statamic/v2-hub#1620]
![image](https://user-images.githubusercontent.com/5466694/31747974-9d0c6aaa-b4b7-11e7-9ca5-1c2a99a1ccca.png)

**Comment by mikegraham00** [comment]
I had the same issue in Chrome and it was a browser version issue. I was stuck on an old version that didn't recognize display: grid. Manually updated and it looks perfect now.

**Comment by jackmcdade** [comment]
Ah yes, that makes sense. @rockethouse what version of Safari are you running?

**Comment by rockethouse** [comment]
10.0.2 here...

![image](https://user-images.githubusercontent.com/5466694/32198202-0f2c6140-be17-11e7-9dfb-3b34a4f161d9.png)

Guess that solves it, I just hope all my clients have updated :|

**Comment by jackmcdade** [comment]
Closing this as an unsupported browser version bug.
