### ISSUE TITLE
Conditionals fail with Suggest field as dependency

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#1622]
### Expected behaviour
Conditional fields doesn't work with `Suggest` as dependency.

### Actual behaviour
Only `not null` work for `show_when` and `hide_when` when a `Suggest` is a dependency.

### Steps to reproduce
1. Create a `Suggest` field with a few options.
2. Have another field with `show_when` dependency on a specific option for the `Suggest`field.
3. See that the field is never shown when the option is selected.

### Server Details

**Operating System**: Alpine Linux 3.6.2

**Web Server:** nginx 1.12.1

**PHP Version:** 7.1.5

**Statamic Version:** 2.7.0

**Updated from an older Statamic or fresh install:** 2.6.9

**Comment by jasonvarga** [comment]
Use a custom rule for now.

https://docs.statamic.com/fieldsets#custom-conditional-logic

**Comment by FrittenKeeZ** [comment]
Is this really the best way to do it with custom rules? It doesn't quite look right.
```js
Statamic.conditions.ctaIsDeal = function (fields) {
    if (fields.cta_type === null || typeof fields.cta_type[0] !== 'string') {
        return false;
    }

    return fields.cta_type[0] === 'deal';
};
```

**Comment by jasonvarga** [comment]
You probably don't need to check if it's a string but yeah that'll work.
