### ISSUE TITLE
Querystring lost on page reload when cache is being built

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1625]
### Expected behaviour
The page reloads with any querystring preserved.

### Actual behaviour
Querystring get chopped off.

### Steps to reproduce
1.  Load a URL with a querystring when the cache is being built
2.  Watch as page reloads and without querystring

**Statamic Version:**
2.7

### User experience note
The reload is pretty odd because on a long cache build it happens a lot of times in quick succession and can be confusing as to what is going on.

Is there a way the page can just load slower until the cache is built and at the very least only do one redirect?

**Comment by jasonvarga** [comment]
Fixed for next release.

Regarding your note, we use a redirect rather than a delay for a reason. If your cache takes a long time to build, its possible the waiting request will time out and result in an error.
