### ISSUE TITLE
FR: ability to exclude templates from template field type

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1627]
Don't want all templates to be choosable in the field type. A parameter that allow one to exclude, would be great.

**Comment by beckysoll** [comment]
Second!

**Comment by jasonvarga** [comment]
Is this really necessary? Cant you just have a select field with some hardcoded template names as options since you're hardcoding stuff anyway?

**Comment by beckysoll** [comment]
Necessary might be a stretch but I think it would be helpful. Depending on the type of site and it's structure it could be beneficial to be able to say show all templates but this one, vs show this one and show that one...

**Comment by jackmcdade** [comment]
As useful as this might be for a few people, adding additional logic to a super simple like feature will make it weight a lot more in terms of technical debt. If/when we rework some areas of the control panel, we'll need to make allowances for it, keep it top of mind, adjust documentation...

It might just be the weight of 175 open feature requests, but I don't plan to add this one at this time. Could be a nice little addon.
