### ISSUE TITLE
Creating new field in new form via CP fails.

### ISSUE THREAD

**Issue by thinkingcap** [statamic/v2-hub#1628]
### Expected behaviour
Creating a new form via CP, after creating new form click the new field button, field modal should be shown.

### Actual behaviour
Modal does not appear.

### Steps to reproduce
1.  Create new form via CP and press save.
2.  Create new field for new form - this fails.

### Server Details

Tested on 
OSX, PHP 7.1.10
Ubuntu 16.04, PHP 7.1.10

**Statamic Version:**
2.7.0
**Updated from an older Statamic or fresh install:**
Updated from 2.6.9
**List of installed addons:**
Placid
Powertools
SiteMap

### Logs

<details>
```
jabbascripts.js?v=2.7.0:8 Uncaught TypeError: Cannot read property 'length' of undefined
    at VueComponent.addField (jabbascripts.js?v=2.7.0:8)
    at HTMLButtonElement.<anonymous> (johnny-deps.js?v=2.7.0:5)
```
</details>

**Comment by thinkingcap** [comment]
If you don't save the form immediately after creating you can add fields.

**Comment by jcohlmeyer** [comment]
I told @jackmcdade on Slack and he said is fixed for next release!
