### ISSUE TITLE
Unable to delete bottom/last asset in Assets in CP

### ISSUE THREAD

**Issue by rickysalsberry** [statamic/v2-hub#1630]
### Actual behaviour
Unable to delete bottom/last asset in Assets in CP

### Steps to reproduce
1.  Edit assets, either through Assets tab or directly through modal
2. Try to delete with the ••• icon
3. Last asset in list's edit/delete panel is cut off, can't delete file
4. See video: 
[statamic2-7-1_bug.mov.zip](https://github.com/statamic/v2-hub/files/1405391/statamic2-7-1_bug.mov.zip)

### Server Details

**Operating System**: Mac OS 10.12.6, Chrome v 61.0.3163.100

**Web Server:** Local

**PHP Version:** 7.1.8

**Statamic Version:** 2.7.1

**Updated from an older Statamic or fresh install:** Fresh

**Comment by dannyuk1982** [comment]
This bug makes it almost impossible at some viewport sizes to do anything with the last item as the menu is inaccessible, and selecting it then shunts the list up/down because of the buttons to the top

**Comment by sheldonkotyk** [comment]
Still an issue for me in 2.8

using Safari.

<img width="361" alt="screen shot 2018-01-14 at 14 38 18" src="https://user-images.githubusercontent.com/622598/34920464-b7e9f444-f938-11e7-9330-d001415dd309.png">

**Comment by jasonvarga** [comment]
If the issue hasn't been closed, there's no reason to assume it's been fixed. You don't need to re-report it.

**Comment by sheldonkotyk** [comment]
Weird. It said that you had closed it.
