### ISSUE TITLE
Control panel, Assets-container crops last item edit-menu

### ISSUE THREAD

**Issue by esonesson** [statamic/v2-hub#1631]
Browsing assets in the control panel, clicking the three dots on the last item. The part of the menu that overflows the container gets cropped. See attached screenshot.

When removing overflow: hidden on .asset-browser.card it's visible.

**Statamic Version:**
2.7.1

**Updated from an older Statamic or fresh install:**
Fresh install

**List of installed addons:**
None

<img width="667" alt="skarmavbild 2017-10-23 kl 10 43 24" src="https://user-images.githubusercontent.com/5310711/31886861-5c1f4584-b7f6-11e7-9e59-edd0b1c581ef.png">

**Comment by jasonvarga** [comment]
This was opened in the previous issue ;) #1630

**Comment by dannyuk1982** [comment]
@jasonvarga this is happening again in 2.7.2
