### ISSUE TITLE
Replicator preview configuration

### ISSUE THREAD

**Issue by maxfahl** [statamic/v2-hub#1633]
## Feature request

First of, **thank you** for the wonderful addition to the replicator fieldtype. It was a mess for us before 2.7.0 when we weren't able to differentiate them from each other.

As much as I love this feature, sometimes it gets messy when displaying a preview from every single field inside the field set. It would be super useful to be able to tell the replicator field configuration what sub fields should be used in the preview from each field set.

As an example, we have a field set which preview is as follows:

`Full Trailer / #000 / Right / #000 / true / desktop-mobile`

We would love to be able to just keep the values from the field title "Full Trailer" and the field visibility (desktop-mobile). The result would then be:

`Full Trailer / desktop-mobile`

**Comment by jasonvarga** [comment]
Pretty cool request!

**Comment by wesort** [comment]
+1

Can we see the image thumbnails too though please: #260

**Comment by jackmcdade** [comment]
That's already pending release.

**Comment by maxfahl** [comment]
Wooooop! :)
