### ISSUE TITLE
Images not visible when opened in asset folder

### ISSUE THREAD

**Issue by beeldr** [statamic/v2-hub#1635]
### Expected behaviour
Tell us what you assumed would happen, as optimistically as possible. We're here to help/ :)
If it's just "it should work", you can remove this section.

### Actual behaviour
When i open an image to add a focal point in the assets folder the image wont show, local on my mac running php 7.1.0 and online on the server running 5.5.21. Executed clear cache/stache/glide/ housekeeping but nothing seems to fix it 

### Steps to reproduce
1.  Upload an image
2.  Try to add a focal point
3.  Fail miserably 

### Server Details

**Operating System**:
MacOS HS 
**Web Server:**
 centos 6
**PHP Version:**
5.5.21 and 7.1.0
**Statamic Version:**
2.7.1
**Updated from an older Statamic or fresh install:**
2.5.8

**Comment by jasonvarga** [comment]
What do you mean it won't show? Where exactly?

**Comment by beeldr** [comment]
![schermafbeelding 2017-11-01 om 14 02 16](https://user-images.githubusercontent.com/24385708/32275927-6618e5ea-bf0d-11e7-92fb-8f5328222b60.png)
When you double click an image in the assets folder

**Comment by jasonvarga** [comment]
Any errors?

**Comment by beeldr** [comment]
Nope, thats the weird thing, at least not visible. Tried it with the debug bar turned on but no luck

**Comment by jasonvarga** [comment]
Errors in the console? Errors in your logs? 404ing network requests?

**Comment by beeldr** [comment]
Derp forgot to check that, had a wrong url set for the images container. Its weird though that you can only change the url by editing the yaml file and not through the control panel, it just wont save that way.

Thanks for your insight <3

**Comment by jasonvarga** [comment]
We'll check that out. Thanks for the updates!
