### ISSUE TITLE
Timezone modifier not parsing variable passed as parameter

### ISSUE THREAD

**Issue by danletson** [statamic/v2-hub#1637]
### Expected behaviour

I have a content type called "Live Events" where each entry represents a promotional event. Each entry has a variable called `event_day`, which is a standard Statamic date, and a variable called `event_timezone` which is a PHP-appropriate timezone string.   

My test event has the following yaml data:

```
event_day: 2017-11-01
event_timezone: America/Los_Angeles
```

Within an entry template, I have the following Antlers markup:

```
{{ event_day format="r" }}<br>
{{ event_day timezone="{event_timezone}" format="r" }}<br>
{{ event_day timezone="America/Los_Angeles" format="r" }}
```

I would expect this to produce:

```
Wed, 01 Nov 2017 00:00:00 +0000
Tue, 31 Oct 2017 17:00:00 -0700
Tue, 31 Oct 2017 17:00:00 -0700
```
with the timezone adjustment happening in the same way via a hard-coded string or a variable value.

### Actual behaviour

Instead, the actual output is:

```
Wed, 01 Nov 2017 00:00:00 +0000
Wed, 01 Nov 2017 00:00:00 +0000
Tue, 31 Oct 2017 17:00:00 -0700
```

Additionally, 

```
{{ event_day timezone="{{event_timezone}}" format="r" }}
```

outputs

```
Tue, 31 Oct 2017 17:00:00 -0700
```

It seems as though the template parser is not parsing the variable being passed to the timezone modifier, even though it is a valid PHP timezone string, unless the variable inside the modifier is also wrapped in double antlers.

### Server Details

**Operating System**:
OSX El Capitan 10.11.6

**Web Server:**
Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.1 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

**PHP Version:**
7.1.1

**Statamic Version:**
2.7.1

**Updated from an older Statamic or fresh install:**
Updated from 2.6.9 install

**List of installed addons:**
Duplicate
Fetch
Getdem
GTM
Location
PowerTools
Spock

### Logs
If any logs (browser, server, or Statamic) are appropriate...
<details>
```
[22:17:29] LOG.notice: Error in [timezone] modifier: Unknown or bad timezone ({ event_timezone })
notice```
</details>

**Comment by jackmcdade** [comment]
If your data is `event_day: 2017-11-01`, there isn't a timestamp, so it'll default to midnight. If you set `allow_time` on the [date fieldtype](https://docs.statamic.com/fieldtypes/date) it'll add it and be carried through.

Feel free to reopen if you find otherwise!
