### ISSUE TITLE
subpages can't be localized

### ISSUE THREAD

**Issue by 4kets** [statamic/v2-hub#1638]
### Expected behaviour
Subpages should be in other languages too!

### Actual behaviour
English version: everything works, every page is found.
French version: home page works fine, the subpages can't be found.

### Steps to reproduce
1.  followed the docs.
2.  we changed the rewriteBase in french .htaccess  

### Server Details

**Operating System**:
windows 10

**Web Server:**
homestead

**PHP Version:**
7.10.0

**Statamic Version:**
2.7

**Updated from an older Statamic or fresh install:**
fresh install

**List of installed addons:**
Google Analytics
Google Tagmanager
Location

### Logs
If any logs (browser, server, or Statamic) are appropriate...
<details>
```
Paste em here
```
</details>

**Comment by jasonvarga** [comment]
It definitely works. Can you send us an email at support@statamic.com with some more detail about your site? Maybe even zip your site and send it along.
