### ISSUE TITLE
Only group collections in CP after 5

### ISSUE THREAD

**Issue by rockethouse** [statamic/v2-hub#1640]
Not sure if this has already been asked or not, but I feel like collections should only group under a Collections menu tab if there is say 5 or more... less then that I feel it should show all of them in the top level like it does if there is only 1.

Can this at least be an option so we can choose? So many clients forget the term Collections and keep asking me "Where are the <collection> in the CP?" or "How do I edit <collection>" etc and can never find it.

**Comment by jasonvarga** [comment]
I don't think we'll implement this, however, you could do it with an addon. I've added a method in 2.7.2 that'll let you remove an existing item.

https://docs.statamic.com/addons/control-panel

You could listen for when the nav is created, then modify it.
Remove the existing collections item group, and add your own.

Something like this:

``` php
class CollectionWangjanglerListener extends Listener
{
    public $events = [
        'cp.nav.created' => 'wangjangle'
    ];

    public function wangjangle($nav)
    {
        $nav->remove('content.collections'); // this method is available from 2.7.2

        $nav->addTo('content', function ($item) {
            $item->add(Nav::item('Blog')->route('entries.show', 'blog')->icon('book'));
            $item->add(Nav::item('Events')->route('entries.show', 'events')->icon('calendar'));
        });
    }
}
```

![image](https://user-images.githubusercontent.com/105211/32276967-4458fa42-bee7-11e7-9bdd-10aa054d874c.png)
