### ISSUE TITLE
Translations (2.7): getting html entities instead of accented characters

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#1643]
### Expected behaviour
When Creating, Editing, Saving, Deleting and Managing "things" (i.e. Blog entries), the green confirmation box that flashes at the top of the screen in the CP should contain messages in my language (as set in settings/cp.yaml for example).

Inside my language file, I have this:
```
// Things
    'thing_created' => ':thing créé.',
    'thing_updated' => ':thing mis à jour.',
    'thing_deleted' => ':thing supprimé.',
    'thing_configure' => 'Configurer :thing',
    'thing_saved' => ':thing enregistré.',
    'thing_editing' => 'Modification de :thing',
```

### Actual behaviour
1. `:thing` is never displayed with its translated (localized) form (i.e. I get the US "Entry" instead of the French "Article")
2. all accented characters are rendered (displayed) as html entities instead of accented characters: I get "Entry cr& eacute;& eacute;" instead of "Article créé" (EDIT: I just put a space inside to have it displayed here without the accented characters...)
### Steps to reproduce
1. Put the French language folder in your site/lang folder
2. define French as your main locale for the cp
3. Create, Edit or Delete any entry

**Comment by jaggy** [comment]
@ebeauchamps are the accented characters still rendering incorrectly?

**Comment by ebeauchamps** [comment]
Hi @jaggy ; Do you mean in 2.7.2? Do I need to download and install a new build? because this issue is still present in my 2.7.2 install on localhost (MAMP/PHP 7.0)

**Comment by jaggy** [comment]
Huh, can you send me a screenshot of the message render problem? Thanks! 👍

**Comment by ebeauchamps** [comment]
oops.......I was on 2.7.1
I upgraded...and there isn't any more "green flash box" at the top of the screen now (am I correct?)
So I guess I can now close this issue? Thanks for your time.

**Comment by ebeauchamps** [comment]
(note to self: time to trim the language file I guess)
