### ISSUE TITLE
Bug: Replicator tooltip positioning is off

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#1649]
### Expected behaviour
Instruction tooltip should appear with replicator type button.

### Actual behaviour
The tooltip appears above the replicator sets.

![screenshot 2017-11-08 11 16 03](https://user-images.githubusercontent.com/414211/32559929-5334d7ae-c476-11e7-91d5-63d45e161cd7.png)

### Steps to reproduce
1.  Add replicator sets
2.  Hover over replicator type button

### Server Details

**Statamic Version:**
2.7.2

**Updated from an older Statamic or fresh install:**
Yes

**List of installed addons:**
None

### Logs
If any logs (browser, server, or Statamic) are appropriate...
<details>
```
Paste em here
```
</details>

**Comment by jackmcdade** [comment]
Working as intended in 2.9.x. 🏄
