### ISSUE TITLE
New flash notifcation can be covered

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1650]
Looks like there is a z-index issue with Redactor in some cases and you get this:

![screen shot 2017-11-08 at 17 36 33](https://user-images.githubusercontent.com/7669885/32564386-098c3710-c4ac-11e7-9217-5789964850f2.png)

**Comment by jackmcdade** [comment]
:joy:

**Comment by jasonvarga** [comment]
`z-index: ∞`
