### ISSUE TITLE
Redactor code view background has no contrast

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#1653]
### Expected behaviour
When one switches to the code view in Redactor, the background should be black.

Expected code view:
![redactor-should-be](https://user-images.githubusercontent.com/3920126/32634501-e9a8bfb0-c5a3-11e7-984c-0313b970d20f.png)

### Actual behaviour
The text colour changes to light, but the background doesn't change to dark. There isn't enough contrast to read the content.

Normal view:
![redactor normal](https://user-images.githubusercontent.com/3920126/32634496-e4f28578-c5a3-11e7-9288-b9889f045247.png)

Code view:
![redactor-code-currently](https://user-images.githubusercontent.com/3920126/32634510-ef64b86e-c5a3-11e7-8e0e-9a9f45355bb3.png)

### Server Details

**Operating System**:
Linux
**Web Server:**
Apache
**PHP Version:**
7.0
**Statamic Version:**
2.7.2

**Comment by ebeauchamps** [comment]
Cannot you change anything in [Redactor settings](https://docs.statamic.com/fieldtypes/redactor)  ?

**Comment by wesort** [comment]
I don't think it's caused by my settings. It's present on all four sites running v2.7.0+, and not an issue on v2.6.9 (I downgraded and tested).

BTW: I know I could fix this on my installs with the `override.css`, but that's an unnecessary hack.

**Comment by jackmcdade** [comment]
I cannot recreate this with a standalone Redactor field. Are you referring to Redactors INSIDE Replicators?
