### ISSUE TITLE
Search Index needs to be manually updated after changing search settings, even when auto index is turned on

### ISSUE THREAD

**Issue by beckysoll** [statamic/v2-hub#1656]
### Expected behaviour
If auto index is turned on, I'd expect the search index to be updated when changing/updating the search settings from within the CP.

### Actual behaviour
Index is not updated, search results get wonky. Even had my global set somehow showup. Running `php please search:update` fixes things consistently.

### Steps to reproduce
1.  Go to /cp/settings/search
2.  Add or remove some searchable fields
3.  Try to search the frontend of the site

### Server Details

Search page hasn't been made live yet so i've only tested this locally: Mac / MAMP Pro

**PHP Version:** 7.1.8

**Statamic Version:** 2.7.2

**Updated from an older Statamic or fresh install:** Updated, started at 2.6.8

**List of installed addons:**
none

**Comment by jackmcdade** [comment]
Fixed for next release.
