### ISSUE TITLE
Cloudinary Integration for Assets

### ISSUE THREAD

**Issue by KimKJDesigns** [statamic/v2-hub#1657]
I would love to see Cloudinary (www.cloudinary.com) integrated as an asset storage option. It has a pretty good api, any image manipulation can be done remotely, served via cdn, they have a free plan which is great for most applications.

I’ve found that any tool that I require my clients to upload images, I ensure that those images are optimised, file type and responsive. It benefits both myself and my clients. I can see this application serving the Statamic community greatly too.

**Comment by subpixelch** [comment]
I'd ask cloudinary to make an addon for statamic. Imgix did one as well... it's in their interest to spread their service in every CMS....

**Comment by KimKJDesigns** [comment]
I’ve been in contact with Cloudinary, looks like I’m building an add-on myself. Fun!

**Comment by stevieg83** [comment]
@KimKJDesigns did you end up building this addon?

**Comment by aerni90** [comment]
@KimKJDesigns Did you end up building this addon? Or how do you work with Cloudinary now?
