### ISSUE TITLE
FR: allow fieldsets in addons

### ISSUE THREAD

**Issue by peda** [statamic/v2-hub#1660]
### Expected behaviour
For some addons (i.e. SEO or e-commerce) the affected objects need to have certain fields. Therefore it would be great if I could ship a fieldset with my addon which can then be included as a `partial` in the fieldsets. I've seen that in some places there is some code in place for `addon.addonname.fieldsetname` - it would be nice if this could be extended.

### Actual behaviour
Addon at the moment only allows a single fieldset called `settings.yaml`

### Steps to reproduce
N/A

### Server Details

**Statamic Version:** 2.7.2

**Comment by jasonvarga** [comment]
This is possible since 2.10. Take a look at how SEO Pro does it. It inserts fields (actually a whole tab).
