### ISSUE TITLE
Selector is only partially clickable

### ISSUE THREAD

**Issue by philipboomy** [statamic/v2-hub#1661]
### Expected behaviour
Expand selector/dropdown

### Actual behaviour
Nothing

### Steps to reproduce
1.  Click the bottom part of a select field

See screenshot here: https://cl.ly/0P3w391k400o
The bottom bit is not clickable 

### Server Details

**Operating System**:

**Web Server:**

**PHP Version:**

**Statamic Version:**
2.7.2
**Updated from an older Statamic or fresh install:**
Updated from 2.7.1
**List of installed addons:**

### Logs
If any logs (browser, server, or Statamic) are appropriate...
<details>
```
Paste em here
```
</details>

**Comment by jackmcdade** [comment]
Looks like this was a Firefox specific bug. It has been squashed for next release.
