### ISSUE TITLE
Exclude current page from collection

### ISSUE THREAD

**Issue by beeldr** [statamic/v2-hub#1662]
I have a website with projects, id like to show other projects with the same taxonomy at the bottom of a project but i cant seem to filter out the current page. it's weird to show the project you're at in the "also check out" section. 

Right now i've got the next line of code that does everything i want except the above.
{{ collection from="projects"  limit="6" taxonomy:categories="{ categories }{ slug }{ /categories }" as="posts"  }}

I've tried https://www.benfurfie.co.uk/blog/exclude-current-entry-from-collection-list-in-statamic but no luck so far.

**Comment by jasonvarga** [comment]
Try changing it to `:taxonomy:categories="categories" :url:not="url"`

**Comment by beeldr** [comment]
I completely missed the "Specifying a variable name by prefixing with a colon" section on the taxonomies page, I was struggling with this for hours so thank you!
