### ISSUE TITLE
Ability to set height of redactor in yaml like you can for textarea

### ISSUE THREAD

**Issue by ulysses** [statamic/v2-hub#1665]
### Expected behaviour
Set the height of redactor in the yaml like you can with textarea. 

### Actual behaviour
height: 100 (or whatever) doesn't change redactor height

### Steps to reproduce
1.  Add redactor to yaml type
2.  Add a height (eg, height: 100)
3.  Nothing! :(

**Comment by jasonvarga** [comment]
Add `minHeight` and/or `maxHeight` to the [redactor settings](https://docs.statamic.com/fieldtypes/redactor#configuration).

```
settings:
  minHeight: 100
  maxHeight: 200
```

(Hint: set minHeight and maxHeight to the same value to make it non-expandable)
