### ISSUE TITLE
Not quite empty taxonomy borks Statamic

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1672]
### Expected behaviour
Statamic just ignores empty strings

### Actual behaviour
Error around taxonomy has no path. Sorry deleted the logs.

### Steps to reproduce
1. add:
```
tags:
  - ""
``` 
2.  Visit your taxonomies in the CP

**Comment by jasonvarga** [comment]
How did it get there like that?

**Comment by edalzell** [comment]
Bad coding on my part. I was converting Categories into Tags and somehow, somewhere those ended up in many many MANY files.

**Comment by jasonvarga** [comment]
I think I'm gonna just let this one go. If you know your converter is doing a weird, not-supported thing, fix it :)

**Comment by jasonvarga** [comment]
An error seems like an decent result if someone manually adds an empty string.

**Comment by edalzell** [comment]
That's debatable. I'd argue that an empty string should be treated the same as nothing, and just move on, instead of erroring.

**Comment by jasonvarga** [comment]
It's not nothing. It's an empty string where you are trying to put taxonomy terms. It's like you've gone the extra mile to break the system.

**Comment by edalzell** [comment]
https://media.giphy.com/media/ZgYa2Lte5odC8/giphy.gif
