### ISSUE TITLE
Collection lastModified throws an Exception

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1673]
Calling `Collection::whereHandle('blog')->lastModified()` throws `Call to undefined method Statamic\Data\Entries\Entry::getLastModified()`

Not sure you actually want the last modified file date...maybe the date of the entry?

I hacked this in:
```
            $modified = $entry->date();
```

Into Collection.php, line 98.

**Comment by jasonvarga** [comment]
We want the date of the most recently modified entry in that collection. It's a bug though (obviously). Will get that cleared up.
