### ISSUE TITLE
No Title When Inserting File into Redactor Field and Link Placement Not Correct

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#1674]
When you insert a PDF into a Redactor field you get this:

`<p><a href="/assets/adkmercy.org-2017.pdf"></a></p>`

It looks hidden unless you look at code view as it has no title for the link.  It should be:

`<p><a href="/assets/adkmercy.org-2017.pdf">**TITLE or FILENAME fallback**</a></p>`

Also, when you insert a file or image into a Redactor field they should insert where your cursor is.  Mine is inserting at top of document every time:

```
<p>**<img src="/assets/img/IMG_1991.JPG" alt="">**Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>**IMAGE SHOULD BE HERE WHERE CURSOR IS**</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.<br></p>
```

**Comment by jasonvarga** [comment]
The empty link is fixed for next release.

I can't replicate the wandering link though. What browser are you using? Can you show a gif/screencast of the behavior?

**Comment by bgarrant** [comment]
I was using latest Chrome and Safari. I will try to get a screencast

**Comment by bgarrant** [comment]
Any ETA on next release? I have a client with this issue

**Comment by jackmcdade** [comment]
A matter of days.

**Comment by bgarrant** [comment]
No matter where I have cursor or text selected it inserts an amply link at start of content. Tested in Chrome and Safari for Mac. 

```
<p><a href="/assets/files/Aging-in-Place-Guide-couples-final-2.5.13.pdf"></a>Mercy Care’s mission is implemented through three interrelated strategies:
</p>
<ol>
	<li>Direct Service to Elders. Mercy Care will work to enhance the fullness of the lives of elders by responding to their needs in a holistic manner through its Friendship Volunteer, Caregiver Advocate, and Parish Nurse Programs.</li>
	<li>Community Empowerment. Mercy Care will encourage each community to develop facilities, programs, policies, and practices that support a fullness of life of elders in the community. Mercy Care will serve as a catalyst for systemic change and facilitator and convener for such community development. </li>
	<li>Education and Advocacy. Through its educational forum program and other outreach activities, Mercy Care will seek to promote an understanding of the aspirations and challenges in the lives of elders.</li>
</ol>
```

**Comment by bgarrant** [comment]
No matter where I have cursor or text selected it inserts an amply link at start or end of content in Redactor. Tested in Chrome and Safari for Mac.

`<p><a href="/assets/files/Aging-in-Place-Guide-couples-final-2.5.13.pdf"></a>Mercy Care’s mission is implemented through three interrelated strategies:
</p>
<ol>
	<li>Direct Service to Elders. Mercy Care will work to enhance the fullness of the lives of elders by responding to their needs in a holistic manner through its Friendship Volunteer, Caregiver Advocate, and Parish Nurse Programs.</li>
	<li>Community Empowerment. Mercy Care will encourage each community to develop facilities, programs, policies, and practices that support a fullness of life of elders in the community. Mercy Care will serve as a catalyst for systemic change and facilitator and convener for such community development. </li>
	<li>Education and Advocacy. Through its educational forum program and other outreach activities, Mercy Care will seek to promote an understanding of the aspirations and challenges in the lives of elders.</li>
</ol>`

**Comment by bgarrant** [comment]
Screencasts

[screencasts.zip](https://github.com/statamic/v2-hub/files/1602290/screencasts.zip)

**Comment by bgarrant** [comment]
@jasonvarga has this fixed for next release.
