### ISSUE TITLE
Localization array deletion inheriting content

### ISSUE THREAD

**Issue by iboxifoo** [statamic/v2-hub#1677]
### Expected behaviour
Default locale content has array fieldtype. User in non-default locale deletes entire array from content, presumably to delete its content from non-default locale. No content should be shown from array in non-default locale.

### Actual behaviour
Deleting array entirely removes reference to array entirely in non-default locale which means default locale content is displayed instead of no content.

Looks like deleting array content from non-default locale should leave empty array in content file e.g.
```
fieldtype: []
```

### Steps to reproduce
1.  Create array fieldtype. Populate with content in default locale.
2.  Delete fieldtype's content entirely in non-default locale.

### Server Details

**Operating System**:
MacOS 10.13

**Web Server:**
Laravel Valet

**PHP Version:**
7.1.12

**Statamic Version:**
2.7.2

**Updated from an older Statamic or fresh install:**
Updated

**Comment by jasonvarga** [comment]
That's kinda just how it works. If a localized version doesn't have a variable, the data cascades from the default locale.

A potential solution for right now is to make your own array fieldtype which extends the native one. In it's `process` method, you can return `false`. (Empty arrays, nulls, and empty strings get stripped out of YAML. Literal `false` values will stay there)
