### ISSUE TITLE
`migrate:rollback` throws Exception

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1684]
### Expected behaviour
`php please migrate:rollback` works

### Actual behaviour
```
[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'CreateTables' not found      
```

### Steps to reproduce
1.  Create a migration 
2.  Run migration
3.  Rollback migration

### Server Details

**Statamic Version:**
2.7.2

**Comment by jcohlmeyer** [comment]
I have also seen this issue, I am pretty sure it was working in **2.7.1**

**Comment by jasonvarga** [comment]
Works fine here. More details?

**Comment by edalzell** [comment]
What information would be helpful Jason? I can send you my site?

**Comment by jasonvarga** [comment]
Sure, yeah email it to us.

**Comment by edalzell** [comment]
Emailed Dropbox link (it was 286M!!).

**Comment by jasonvarga** [comment]
Ah you need to dump the autoloader. It's done automatically when you `make:migration`.

`cd statamic && composer dump-autoload`

Not really sure of a good way to solve this for v2 right now.
In v3 it'll be more standard Laravel and will be a non-issue.

**Comment by edalzell** [comment]
I need to do this every time I do a migration? Or just this once to clean it up?

**Comment by jasonvarga** [comment]
Once. It's run automatically when you make a migration.

**Comment by edalzell** [comment]
That worked, thanks.
