### ISSUE TITLE
Have the possibility to register new extensions for templates, layouts and partials

### ISSUE THREAD

**Issue by smcyr** [statamic/v2-hub#1687]
### Expected behaviour
I would like to be able to have .antlers or another name for template extensions instead of .html to be able to have syntax highlighting in my IDE without overriding the html syntax.

### Actual behaviour
Statamic only recognise .php, .html and .blade.php.

Thank you.

**Comment by jackmcdade** [comment]
Perhaps in v3, but we won't be changing this behavior in v2. The Antlers syntax packages for Sublime and Atom both extend the HTML syntax so they don't override anything.

**Comment by jasonvarga** [comment]
v3 will use `.antlers.html`

**Comment by smcyr** [comment]
Thank you! Hoping someone will develop a PHPStorm plugin
