### ISSUE TITLE
Hardcoded paths in Statamic\Extend\Management\AddonRepository#classes

### ISSUE THREAD

**Issue by rexfordkelly** [statamic/v2-hub#1688]
### Expected behaviour

When one updates the $statamic variable in index.php, it should carry through to all reference points.

### Actual behaviour
As it stands now, If you rename the statamic folder ( an edge case, I guess ) and update the $statamic variable to reflect this, it breaks.

I traced it down to a hard coded regex in Statamic\Extend\Management\AddonRepository on line 47

I was able to patch that issue with

```

public function classes(){
    return $this->files->filter(function ($path) {
         return Str::endsWith($path, '.php');
    })->map(function ($path) {
         $class = preg_replace("/^(site\/addons|" . basename(RELATIVE_APP) . "\/bundles)/", '', $path);
         $class = str_replace(['/', '.php'], ['\\', ''], $class);
         return 'Statamic\Addons' . $class;
    })->values();
}

```
However, it appears more work would need to be done in order to solve it for all Contextual paths, such as site, addons, bundles etc.

### Steps to reproduce
1.  Fresh install Statamic  2.7.2 - the amazing.
2.  change statamic folder to statamic_app
3.  update index.php $statamic variable to reflect the new folder new
4.  browse site, and bang!

### Server Details
**Statamic Version:**
          2.7.2

**Updated from an older Statamic or fresh install:**
nope, was a fresh install

**List of installed addons:**
none

**Comment by peimn** [comment]
In file: **core/Extend/Management/AddonRepository.php** the name of the folder is hard coded so I changed them manually but this error claims: 
<img width="981" alt="screen shot 2017-12-23 at 5 10 10 pm" src="https://user-images.githubusercontent.com/5695187/34319976-29af2e8c-e804-11e7-9a6a-ed7c07c8d490.png">

**Comment by jackmcdade** [comment]
Why is it important to be able to change the Statamic folder? We never intended for anyone to do this. If you’re worried about security, you can move it.
