### ISSUE TITLE
ErrorException: A non-numeric value encountered

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1689]
### Steps to reproduce
1.  Fill in contact form on default installation of Statamic but let Fav Number be empty
2.  Go to /forms and open Contact me
3.  Error appears

<img width="982" alt="screen shot 2017-12-23 at 1 46 45 pm" src="https://user-images.githubusercontent.com/5695187/34318911-68505312-e7e8-11e7-8d2c-c9009078c2c2.png">

### Server Details

**Operating System**: macos

**Web Server:** nginx

**PHP Version:** 7.1

**Statamic Version:** 2.7.2

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:**

### Logs
If any logs (browser, server, or Statamic) are appropriate...
<details>
```

```
</details>

**Comment by peimn** [comment]
Solution:
/core/Forms/Metrics/SumMetric.php (L 14):
return (int)$submission->get($field);

/core/Forms/Metrics/AverageMetric.php (L 14):
return (int)$submission->get($field);

**Comment by jackmcdade** [comment]
Fixed for next release.
