### ISSUE TITLE
FR: Asset->save() should return $this

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1692]
I'd like to be able to do this code:
```
        return $asset_container
            ->createAsset($asset_path)
            ->set('title', $name)
            ->save();
```

But `save()` does not return `$this`.

**Comment by FrittenKeeZ** [comment]
Just wait for v3 and use `tap()` https://laravel.com/docs/5.5/helpers#method-tap :)

**Comment by jasonvarga** [comment]
We backported tap into Statamic v2. Go ahead and use it.

**Comment by edalzell** [comment]
gonna close this because there's a decent work-around
