### ISSUE TITLE
FR: GDPR compliance for EU websites

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1696]
As part of the GDPR which all EU countries will have to follow (website owners and any websites serving people from the EU) from May a lot of companies will not want personal information held on the website.

Contact forms are an issue at the moment as just storing a name is problematic in some cases - there seems to be:

a) no way to not have the contact form not store entries (i.e. just email them)

b) no way to mass delete form entries

One of these needs to be implemented really in order for sites to be compliant.

Hopefully something can be implemented or a workaround found, as this will literally be a dealbreaker for people in the EU.

**Comment by FrittenKeeZ** [comment]
There seems to be a conflict of interest regarding storing form submissions.
We're investigating this with lawyers, as you essentially eliminate proof fx. that a user signed up for a newsletter. Where does it stop? Will you have to delete the server log entry for the form submission as well? Should all your purchases be deleted from an ecommerce site, rendering their accountant unable to compare them with their income? Seems to me like a mekka for fraud...

**Comment by jasonvarga** [comment]
Regardless of the GDPR situation, items `a` and `b` are still reasonable requests. 👍

**Comment by jasonvarga** [comment]
Ability to not save submissions will be in the next release. I [opened another issue for bulk deleting](https://github.com/statamic/v2-hub/issues/1748) for you so I can close this one.

**Comment by dannyuk1982** [comment]
You are a great man @jasonvarga, bards and minstrels will sing of your name, and also Nikki Flores.
