### ISSUE TITLE
Please create a search URL for docs like /?q=SEARCH+TERM

### ISSUE THREAD

**Issue by gmcz** [statamic/v2-hub#1700]
I would like to be able to search the docs without going to the website and clicking the search icon (I.e. I'd like to use Alfred on Mac) but I can't do that unless there's a URL where I can stick the term and get results. Is there one somewhere? If not, please consider adding it.

**Comment by jackmcdade** [comment]
For sure, would be helpful indeed and it's on the roadmap. Closing this issue though as that's a doc thing and this is for core 👍
