### ISSUE TITLE
FR: rename Bard to Brad

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1702]
I really like the new `Bard` but feel it would just be better being called `Brad`, this would also have better compliance with the latest EU directives. 

I have sourced a suitable image for updating any promo videos etc.

<img width="726" alt="brad" src="https://user-images.githubusercontent.com/7669885/34827489-39f457d6-f6d2-11e7-8303-4f7ff7978ed8.png">

**Operating System**:
MacOS

**Web Server:**
Valet

**PHP Version:**
7.1

**Statamic Version:**
2.8

**Comment by jackmcdade** [comment]
lol

**Comment by jackmcdade** [comment]
Reconsidering this. It’s growing on me.

**Comment by jasonvarga** [comment]
I thought you wanted to call it `Sanderson`

**Comment by ebeauchamps** [comment]
HappyBrad ;-))

**Comment by gmcz** [comment]
assets:asset
bard:brad
