### ISSUE TITLE
Drag and Drop in Bard doesn't work

### ISSUE THREAD

**Issue by aerni90** [statamic/v2-hub#1703]
### Expected behaviour
Working Drag and Drop for any block within Bard.

### Actual behaviour
Drag and Drop doesn't work when adding a block that's a assets fieldtype. However it works when the fieldtype has max_files: 1. As well it works when I add an instruction. I then can drag and drop the block grabbing the instruction.

### Steps to reproduce
1.  Create a Bard fieldtype
2.  Create a set with a the assets fieldtype
3.  Add the block in Bard and try to drag and drop.

### Server Details

**Operating System**:
macOS 10.12.6

**Web Server:**
Laravel Valet

**PHP Version:**
7.1

**Statamic Version:**
2.8

**Updated from an older Statamic or fresh install:**
Updated from version previous to 2.8

**List of installed addons:**
CharField
LaravelMix
PowerTools
Spock
Tel

**Comment by jasonvarga** [comment]
Can you give more details? It works fine here, unless I'm misunderstanding what you're describing.

**Comment by aerni90** [comment]
Watch this video:
[https://drive.google.com/file/d/1Ou8gi2QSG_jukfY1WCyIfyMzuAty-0tx/view](url)

1. Block: Can't drag and drop at all.
2. Block: Can drag and drop on instructions.
3. Block: Drag and drop works. Field has max_files: 1 defined.
