### ISSUE TITLE
FR: An idea for Bard

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1710]
The Bard is cool. It could be even coolest if we could define some styles for blocks to be applied after collapsing. Imagine a block like an image that we want to be aligned to left or right in theme, so we can show that style right in the editor. 
Or a _quote_ block or some advanced previews like _slideshows_, in this case, it needs to trigger some user-defined scripts too.
An approach to this would be defining a preview template in settings of the block. Through this, it would leverage shortcodes functionality in Bard. ✌️.

**Comment by jasonvarga** [comment]
Why not use Live Preview while you edit and you can see how it _actually_ looks in real time?

**Comment by peimn** [comment]
Live preview is awesome too. We can have both. Developers could make very useful and beautiful blocks 😉.

**Comment by jasonvarga** [comment]
I appreciate the idea, but I don't see it happening. We have a lot of styling in place that depends on elements being in certain positions, like where you click between sets to add new paragraphs, etc.

You're free to add something to your override.css file if you like.
