### ISSUE TITLE
FR: Enable other fieldtypes in the Table fieldtype

### ISSUE THREAD

**Issue by markzegarelli** [statamic/v2-hub#1713]
I love the flexibility of the the Table fieldtype, but I also need to be able to add different types of content to each cell.

For example, I want to enable my writers to be able to use a set fieldtype to create tables, but the tables they need to write are not standardized enough to create a Grid for each one. There would be too many.

Ideally, we'd be able to create a few Sets, just like Bard. For example:

- An Asset set with an Asset field type, Radio Buttons for asset type, and a Text field for alt-tag.
- A Code Snippet set with a Markdown editor, and dropdown  box for language selection.

**Comment by edalzell** [comment]
Isn't that what Replicator/Bard is for @markzegarelli?

**Comment by jackmcdade** [comment]
Unfortunately this won't be possible. The Table fieldtype isn't meta-level and is only designed to work with simple strings.
