### ISSUE TITLE
CP: when only one global set is defined, "manage sets" is unavailable

### ISSUE THREAD

**Issue by vladdu** [statamic/v2-hub#1715]
### Actual behaviour
When only one global set is defined, when navigating to 'Globals', I get to the global set's page, with no way to get back to the "manage global sets" page. Adding another set (via the file system) restores the proper functionality.

### Server Details

**Statamic Version:** 2.8.0

**Comment by jasonvarga** [comment]
That's intended. It works the same way when you have one collection, taxonomy, or asset container.

**Comment by jackmcdade** [comment]
You can always manage your Global sets down in the **Configure** area of the sidenav.

**Comment by vladdu** [comment]
> You can always manage your Global sets down in the Configure area of the sidenav.

Obviously, I didn't find that. I don't think it's obvious that editing these can be done from two different places and the UI is slightly different.

**Comment by jackmcdade** [comment]
That's the primary place to manage the sets. The "Create a Set" in the content area is essentially a "first run" shortcut. 

Now you know! 😁

**Comment by vladdu** [comment]
Yes, now I know! I hope I won't forget until next time....
