### ISSUE TITLE
Title and translation issue

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1727]
<img width="531" alt="screen shot 2018-01-17 at 5 50 14 am" src="https://user-images.githubusercontent.com/5695187/35022316-929544a0-fb4a-11e7-8ab6-10b311b6248c.png">
<img width="497" alt="screen shot 2018-01-17 at 5 49 55 am" src="https://user-images.githubusercontent.com/5695187/35022317-92cefeb6-fb4a-11e7-8391-16996bc63731.png">

----
Statamic: 2.8.0

**Comment by peimn** [comment]
Also in 2.8.2

**Comment by edalzell** [comment]
No need to comment again, if the issue is still open, it hasn't been fixed.
