### ISSUE TITLE
I expect a congratulation page after update! 😅

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1728]
<img width="555" alt="screen shot 2018-01-17 at 5 55 23 am" src="https://user-images.githubusercontent.com/5695187/35022426-3af11e30-fb4b-11e7-8681-efdcecf6493c.png">

**Comment by jasonvarga** [comment]
Haha 😂 

How'd you get to that url?

**Comment by jasonvarga** [comment]
Actually based on your [other issue](https://github.com/statamic/v2-hub/issues/1732) it sounds like you have some sort of Javascript issue.

**Comment by peimn** [comment]
I did nothing, even haven't touched any file of Statamic. After upgrading Statamic it took me to that page.
About the other issue, also I haven't edited any file of installed Statamic.
