### ISSUE TITLE
Document custom form error messages

### ISSUE THREAD

**Issue by gmcz** [statamic/v2-hub#1729]
The documents for form errors (https://docs.statamic.com/tags/form-errors) do not mention how to save custom error messages. Perhaps this is actually a FR, but I have a memory of doing this in the past. (Perhaps it was back with Raven!)

**Comment by jackmcdade** [comment]
This issue has been inactive and in need of more information for a while now. Feel free to reopen and we'd be more than happy to take another look if you have more info that can help!
