### ISSUE TITLE
Mousetrap is not defined

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1732]
Every time I do hard-refresh in chrome I got some errors:
<img width="419" alt="screen shot 2018-01-18 at 4 50 08 pm" src="https://user-images.githubusercontent.com/5695187/35100125-da71e3a2-fc6f-11e7-8199-50a77a61f5fd.png">
----
<img width="381" alt="screen shot 2018-01-18 at 4 54 17 pm" src="https://user-images.githubusercontent.com/5695187/35100264-68d58e50-fc70-11e7-8673-8a4b660f2963.png">
---
<img width="425" alt="screen shot 2018-01-18 at 4 56 34 pm" src="https://user-images.githubusercontent.com/5695187/35100299-9970befe-fc70-11e7-9c8d-392ccf648892.png">
---
why does this happen?

---
Statamic: 2.8.0
os: macOS HS
server: nginx
php: 7.1

**Comment by peimn** [comment]
I think it is because of how resources loaded indirectly via the index.php.

**Comment by jasonvarga** [comment]
Never seen that before. Do you have any more info? Can you try re-updating Statamic, clearing your browser cache, etc?

**Comment by peimn** [comment]
<img width="1256" alt="screen shot 2018-01-23 at 5 49 23 am" src="https://user-images.githubusercontent.com/5695187/35254836-40c4fd3a-0001-11e8-892e-6f4d372cb5df.png">

Do hard refreshing (⌘+⇧+R) in cp for 3, 4 or 5 times (while developer tools window is open), you will see errors appearing.

**Comment by peimn** [comment]
And notice that after repeating hard-refresh for 3, 4 or more times

**Comment by jasonvarga** [comment]
No, I don't, that's why I asked those other questions.

**Comment by peimn** [comment]
Actually how I met this issue is about adding some styles to CP. After adding some custom CSS rules, I did a hard refresh to clear cache and reload assets. But after a few tries, I notice that the js files did not load correctly.

**Comment by peimn** [comment]
After that, I did a fresh install to test on untouched Statamic. There also issue appeared.

**Comment by jasonvarga** [comment]
What kind of server are you running?

**Comment by peimn** [comment]
I am using Nginx, with the config that comes alongside Statamic files.

**Comment by jackmcdade** [comment]
Closing this issue as it's relate to server config and not something we can fix on the core side.
