### ISSUE TITLE
Background overlay colour picker in Bard not working in Safari 11.0.2

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#1733]
### Expected behaviour
Seeing a default black color in this field when visiting an entry of the demo theme for the Bard fieldtype. And having the ability to change the color

### Actual behaviour
No color. Field appears as a simple Text field in Safari 11.0.2 Mac OS X 12.6 SIERRA

![capture d ecran 2018-01-18 a 20 50 38](https://user-images.githubusercontent.com/1823359/35118164-46207dfe-fc91-11e7-8a76-25278eb1f6a3.png)

Works OK in Chrome 61.0.3163.100

Sorry Safari, you are the new IE!

**Comment by jackmcdade** [comment]
It's an issue with the setup for the Bard Storyteller theme (an issue on that repo would be better). It's been fixed in 0.2.1.
