### ISSUE TITLE
Security issue: other users can change username of main admin!

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1734]
Other users, those have editing ability, can change the username of main admin.
Please check that.

--- St: 2.8.1

**Comment by peimn** [comment]
If we imagine a hierarchy of users (by their abilities), the low-level users must not be able to edit top users, even not be able to view the data of top-level users.

**Comment by jasonvarga** [comment]
There's no such thing as a "main admin". If you give someone permission to edit users, you have permission to edit users. If you don't trust someone with that sort of permission, don't give it to them.

**Comment by peimn** [comment]
Why a user could be able to edit another user while that another user defined this user?!
And simply can disable that user from accessing its account.

**Comment by jasonvarga** [comment]
A user can edit their own account without the 'edit users' permission.
If you give them the 'edit users' permission, they can... edit users.
