### ISSUE TITLE
Bard: Using the character "-" in the middle of text creates a line item

### ISSUE THREAD

**Issue by okse** [statamic/v2-hub#1736]
Statamic 2.8.2:

### Expected behaviour
Giving me the "-" character as part of the text :)

### Actual behaviour
The entire line turns in to a list item when I put "-" and then hit space. Regardless of where in the text I am. I'd expect a line to become a list item if I do this at the start of a line.
![2018-01-20_19-05-09](https://user-images.githubusercontent.com/17156984/35186466-0197586c-fe15-11e7-9293-b691ea6c10e0.gif)

### Steps to reproduce
1.  Bard fieldtype
2.  Add text
3.  Add a "-" followed by a space in the middle of some text

**Comment by jackmcdade** [comment]
Fixed for next release!
