### ISSUE TITLE
Bard: Visually difficult to reorder table items within a fieldset in a Bard field

### ISSUE THREAD

**Issue by okse** [statamic/v2-hub#1737]
Statamic 2.8.2:

### Expected behaviour
Want to be able visibly see where I drop the items in a table field when reordering by drag an drop.

### Actual behaviour
When trying to drag an item in the table (that's part of a set within a Bard field), it visually drags the entire set. The field is possible to drag and drop, but it's difficult to see when you're where you want to drop it :)

![2018-01-20_19-10-51](https://user-images.githubusercontent.com/17156984/35186533-08e7b0fc-fe16-11e7-98be-2fb286c8e30a.gif)
_(Note that I on the second try managed to move it.)_

**Comment by aerni90** [comment]
Same issue here #1703
