### ISSUE TITLE
replicator_preview: false gets stripped out when saving fieldset in cp

### ISSUE THREAD

**Issue by beckysoll** [statamic/v2-hub#1744]
### Expected behaviour
Since the option has be manually added in the fieldset's yaml file, i'd expect it to stay there regardless of what future edits i make in the CP to that fieldset

### Actual behaviour
I've added `replicator_preview: false` manually to a number of hidden fields in my fieldset. When i go back into the fieldset to continue editing it within the CP, and save it, it strips out all instances of `replicator_preview: false`.

### Steps to reproduce
1.  open a fieldset in your text editor, add `replicator_preview: false` to one of the fields (doesn't seem to matter which type), save it.
2.  open the same fieldset within the cp, refresh it first if you already have it open in a tab, add or edit a field, save it
3.  take a look at the fieldset again in your text editor, `replicator_preview: false` has disappeared
4. I've tested this with both top level fields and fields in sets in a bard, behaves the same regardless.

### Server Details

**Operating System:** macOS High Sierra 10.13.2 (working locally)

**Browser:** Firefox 57.0.4, Chrome 63.0.3239.132 

**Web Server:** Apache (via mamp pro)

**PHP Version:** 7.1.8

**Statamic Version:** 2.8.3

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:** None

**Comment by jackmcdade** [comment]
Looks like this is working as expected now. Feel free to reopen if it rears its head!
