### ISSUE TITLE
Bard text field doesn't allow typing after finishing a list

### ISSUE THREAD

**Issue by cubistcastle** [statamic/v2-hub#1745]
### Expected behaviour
When creating a list (ordered or unordered) in a bard text field, hitting return twice should start a new paragraph line.

### Actual behaviour
Hitting return twice advances the cursor out of list mode to what looks like a paragraph, but typing results in nothing.

### Steps to reproduce
1.  create a list with a bullet or asterisk convention 
2.  hit return for a new line (resulting in an empty bullet)
3.  hit return/ new line again. Empty bullet is removed, cursor goes to next line but typing is disabled

### Server Details

**Operating System**:
MacOS10.12.6

**Web Server:**
nginx/1.13.6

**PHP Version:**
7.2

**Statamic Version:**
2.8.3

**Updated from an older Statamic or fresh install:**
fresh
**List of installed addons:**
nope

**Comment by jackmcdade** [comment]
What browser/version? I can't recreate this.

**Comment by cubistcastle** [comment]
Looks like all is well now. Thanks for checking!
