### ISSUE TITLE
Missing margin-bottom on Replicator field title

### ISSUE THREAD

**Issue by aerni90** [statamic/v2-hub#1746]
### Expected behaviour
The title of a Replicator field should have a "margin-bottom: 8px" like all the other titles.

### Actual behaviour
The "margin-bottom: 8px" gets overwritten with "margin-bottom: 0px".

<img width="1411" alt="bildschirmfoto 2018-01-23 um 08 58 37" src="https://user-images.githubusercontent.com/23167701/35264276-66619448-001c-11e8-9b73-923acf76425c.png">

**Comment by jackmcdade** [comment]
Fixed for next release.
