### ISSUE TITLE
Form submission via AJAX on a statically cache page (file cache)

### ISSUE THREAD

**Issue by maxfahl** [statamic/v2-hub#1747]
I'm submitting a form with axios like this:

```typescript
let data = new FormData(this.formEl);
axios.post(this.formEl.action, data);
```
Usually it gets submitted and listed under form submission in the control panel, but sometimes it doesn't. I can't really figure out why it sometimes fails. Today I figured that it may have something to do with that we're using static file caching for the page with the form in it. When I delete the static cache for this page the form submits as expected, but after a while it stops working again. Usually we can do a couple of successful submissions before the form stops working again. This seems very random.

Do any of you know why this could fail when using the static file cache?

### Steps to reproduce
1.  Add a form to a page
2.  Cache that page statically with the file cache
3.  Submit the form via AJAX (I'm using the axios library form NPM)

### Server Details

**Operating System**: Linux n14 4.9.36mtv22

**Web Server:** Apache

**PHP Version:** 5.6.21

**Statamic Version:** 2.8.2

**Updated from an older Statamic or fresh install:** Continuous updates, recently updated from 2.7.3

**List of installed addons:**

Duplicate 1.5.2
Google Analytics 1.0.4
RedactorPlugins 1.0.1
Sitemap 1.0

**Comment by jasonvarga** [comment]
If you're using static caching on the form page, I would think it would work only _once_ then break. Are you positive it's working more than once?

**Comment by maxfahl** [comment]
That was how I expected it to work as well. The weird thing is that it is still working ATM and the page has clearly been cached in the static directory as blocks_.html.

The action path for the form is "/!/Form/create", and that is not cached, isn't it that that recieves the POST and creates the submission? Why does the static cache of my page (the one containing the form) interfere with the POST?

Would it help with a link to our site to investigate?

**Comment by jasonvarga** [comment]
Have you disabled CSRF for /!/Form/create ? You may want to do that.
We can pick this up over email if you want to send us a link to the site. support@statamic.com

**Comment by maxfahl** [comment]
I sent you an email with more information. I can update this issue late on if someone else wants to know how to fix this.

**Comment by maxfahl** [comment]
I now have a better understanding of what's happening if anyone else stumbles upon this.

The CSRF token (_token input field) is bound to the session you're assigned by the server when using the site. The form submission action checks that this token matches your current session, if it doesn't, the action aborts.

When using the static file cache for your site, the _token field of your form will be hard coded into a value that matches the first visitor to that page (the visit that creates the static cache). This specific user can now submit the form how many times he wants to before the cache expires since it is his token that is in place. If anyone else but that user tries to emit the form it will not work since the token does not match the new user's session.

I managed to solve my problem by disabling the CSRF check for the path that takes the form submission post call by adding this to `site/settings/system.yaml `:

```yaml
csrf_exclude:
  - /!/Form/create
```
