### ISSUE TITLE
Blank line at beginning of bard field nearly impossible to remove

### ISSUE THREAD

**Issue by beckysoll** [statamic/v2-hub#1751]
### Expected behaviour
There should be some way to remove a blank line at the beginning of the field that has been saved in the md as an empty or pre-exisitng text block.

### Actual behaviour
a `<br>` seems to get saved in the extra line, then if you delete the html from the code view and save, or save and continue and then refresh, you end up with a blank text set that you cannot delete, and refreshing/saving again you end up with 'undefined' within the text block. trying to delete undefined does nothing. After you go through all of this, it doesn't seem like the plus sign that would allow you to delete it ever pops up.

I've found two ways to get around this but neither are great:
1. delete the set from the .md file itself
2. keep dragging other types of sets up, above the blank line, until it joins with another existing text block. then you can delete it. That can be tricky and messy, depending on how much content you have within the field.

### Steps to reproduce
1.  edit a bard field
2.  place cursor at the top so a new line appears
3.  save, delete the <br> that appears in the code for that line, save again.

### Server Details

Operating System: macOS High Sierra 10.13.2 (working locally)

Browser: Firefox 57.0.4, Chrome 63.0.3239.132

Web Server: Apache (via mamp pro)

PHP Version: 7.1.8

Statamic Version: 2.8.3

Updated from an older Statamic or fresh install: Updated

List of installed addons: None

**Comment by aerni90** [comment]
Same issue here.

**Comment by jackmcdade** [comment]
Click the (+) and there's an option to delete the text block. We ran into this too :)

**Comment by aerni90** [comment]
@jackmcdade Yes there's the (+) and the delete option. But the empty line can't be deleted. It just doesn't go away …

**Comment by beckysoll** [comment]
Yeah when I reported this the plus sign delete definitely wouldn't work, I tried it over and over. Of course now I can't replicate, but i've changed the page a lot so i'm not sure what the scenario was exactly that lead to that happening. But i'm 100% sure the plus sign delete didn't make it go away :-\

**Comment by jackmcdade** [comment]
I'll reopen until we test/confirm/resolve.

**Comment by jackmcdade** [comment]
This is definitely working correctly in all browsers from all my tests.
