### ISSUE TITLE
Can't reorder sets in replicator field

### ISSUE THREAD

**Issue by cibgraphics** [statamic/v2-hub#1752]
### Expected behaviour
Sets should be able to be reordered using the reorder icon on the right of the set listing.

### Actual behaviour
Clicking and dragging on the reorder button does nothing

### Steps to reproduce
1.  Create a new replicator field
2.  Create multiple sets
3.  Using the reorder icon, click and drag the set

### Server Details

**Operating System**: OSX 10.11.6

**Web Server:** MAMP

**PHP Version:** 5.5.10

**Statamic Version:** 2.8.3

**Updated from an older Statamic or fresh install:** Older Statamic

**List of installed addons:** None

### Logs
If any logs (browser, server, or Statamic) are appropriate...
<details>
```
Paste em here
```
</details>

**Comment by jackmcdade** [comment]
Works like a champion in 2.9.x now. 💪
