### ISSUE TITLE
Multiple env settings in asset container YAML are ignored

### ISSUE THREAD

**Issue by markdavies** [statamic/v2-hub#1769]
### Expected behaviour
When setting more than one env value in an asset container yaml file, all env values should be parsed properly

### Actual behaviour
Only the first env value that is found is parsed before being handed to the yaml parser. 

### Steps to reproduce
1.  Create a new asset container yaml file, say for S3
2.  Set the `key`, `secret`, and `bucket` to all use an .env value (we need all three as the `extendWithS3Driver` method will explicitly parse `key` and `secret` later.
3.  Asset management breaks when Statamic tries to use literal strings to retrieve assets from, or send assets to S3.

This update to the `assetContainers` method in `Statamic\Providers\FilesystemServiceProvider` should solve the issue:

        private function assetContainers()
        {

            return collect(
                Folder::disk('content')->getFilesByType('assets', 'yaml')
            )->map(function ($path) {

                $data = File::disk('content')->get($path);

                while($data != Parse::env($data)) {
                    $data = Parse::env($data);
                }

                return [
                    'id'   => substr($path, 7, -5),
                    'data' => YAML::parse($data)
                ];

            })->pluck('data', 'id');
        }

**Comment by rdarcy1** [comment]
Thanks for this, took me a long time to figure out why my asset yaml files weren't parsing env values correctly. Seems like quite an important issue to solve for people who don't want their API credentials stored in the codebase.

**Comment by madsem** [comment]
ok it actually works now, I just had to provision my VM again so that the new env catches on, sooowwy
