### ISSUE TITLE
Bard Settings - 'allow_source' can't be set to false or is removed when saving the fieldset

### ISSUE THREAD

**Issue by krausste** [statamic/v2-hub#1771]
### Expected behaviour
The **allow_source** setting with value _false_ stays in the fieldset's yaml when saving a fieldset via the Statamic backend.

### Actual behaviour
If the **allow_source** setting is changed to _false_ (by manually editing the fieldset's yaml file), this **allow_source** setting is removed when saving this fieldset via the Statamic backend.

### Steps to reproduce
1.  Edit a fieldset's yaml file manually and add the allow_source setting with value false to any bard fieldtype (see: https://docs.statamic.com/fieldtypes/bard#settings) - the setting gets successfully applied
2.  Open this fieldset in the Statamic backend
3.  Press save

### Server Details

**Statamic Version:** 2.8.3
**Doc:** https://docs.statamic.com/fieldtypes/bard#settings

**Comment by jackmcdade** [comment]
Fixed for next release.
