### ISSUE TITLE
Fatal error on empty search + grey screen showing on live site with debugging turned off 

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1774]
On a website I have, if you go to the 'search' page with no query string OR try to search with an empty search form (same thing) it fatal errors and throws the grey screen of death. I have debug turned off for my live ENV so no detailed error shows - it just is a grey screen with text 'whoops something went wrong’. 

PhilipBoomy also replicated the same error in his site.

So:

1. please don't fatal error my site with an empty search
2. please don't show grey screen of death on my live website when I have debug: false in my live ENV

Thanks 👍 

Ant

===

### Server Details

**Operating System**: OS X some version

**Web Server:** Apache

**PHP Version:** No idea

**Statamic Version:** 2.8.3

**Updated from an older Statamic or fresh install:** Update

**Comment by peimn** [comment]
Also in #1707, I have noticed that the search does not work in other locales than EN. This is because the search method, first of all, tries to manipulate search term to ensure there are not any unwanted characters. As result, empty search terms fall into error too.
