### ISSUE TITLE
Multibyte search queries fail

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1780]
In default installation, I did many search and they all returned without result!
<img width="701" alt="screen shot 2018-02-15 at 12 29 52 pm" src="https://user-images.githubusercontent.com/5695187/36248306-4d40825c-124c-11e8-8cca-fcedfe4956dd.png">

**Comment by jackmcdade** [comment]
Did you try kicking off the search index with `php please search:update`?

**Comment by peimn** [comment]
Why in the default installation that is not updated?!

**Comment by peimn** [comment]
search for other than Latin and it is not working:
<img width="443" alt="screen shot 2018-02-15 at 5 30 28 pm" src="https://user-images.githubusercontent.com/5695187/36260271-1377ae86-1276-11e8-8139-6bc2277fd5fb.png">

**Comment by jackmcdade** [comment]
It's working for me - did you update the search index?

**Comment by peimn** [comment]
It is not about index, I think it does not work on multibyte characters:

<img width="1277" alt="screen shot 2018-02-16 at 8 24 01 pm" src="https://user-images.githubusercontent.com/5695187/36319207-6ca83836-1357-11e8-89be-c77f09ba2881.png">

**Comment by peimn** [comment]
Error appears in 2.8.4 too

**Comment by jackmcdade** [comment]
Fixed for next release.
