### ISSUE TITLE
translation: missing string in 2.8.4

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#1781]
Related to #1705 

A small chunk isn't translatable yet: "Valid URL". Note that "Valid path" has been translated OK prior to 2.8.3

![capture d ecran 2018-02-16 a 21 00 40](https://user-images.githubusercontent.com/1823359/36326752-84a48eee-135c-11e8-88ce-ef703054cfb8.png)

The issue about the control of the URL not being valid isn't corrected in 2.8.4, too:

![capture d ecran 2018-02-16 a 21 02 57](https://user-images.githubusercontent.com/1823359/36326840-d05ea3a6-135c-11e8-9b45-97eabede384f.png)

**Comment by jackmcdade** [comment]
Will get that sorted, thanks!

**Comment by ebeauchamps** [comment]
You bet! and thanks for making such a nice tool!
