### ISSUE TITLE
update fails using CP, but successful using command line

### ISSUE THREAD

**Issue by PeterEmil** [statamic/v2-hub#1783]
### Expected behaviour
Successful update Statamic with add-on from within the CP to the latest version.

### Actual behaviour - using CP
Installation fails with message "couldn't update dependencies add-on"

### Steps to reproduce
1.  Go to updater & click update

### Actual behaviour - using command line
Installation finishes without a hiccup.

### Steps to reproduce
1.  Fire up Terminal
2. cd into Statamic root folder
3. `php please update:statamic`

### Resulting log while update runs:
```
arwen:silbersee-statamic arwen$ php please update:statamic

Determining the latest version of Statamic...
Latest version is 2.8.5

Updating from Statamic 2.8.3 to 2.8.5

Backing up...
Creating a zip file...
Adding files to the zip...
Writing the zip to disk...
[✓] Backup saved to local/temp/backup/statamic-2.8.3-1518954563.zip

Getting a copy of Statamic...
Using previously downloaded zip detected at local/temp/updates/statamic-2.8.5.zip.
Extracting the zip into a temporary location...
[✓] Extraction complete.

Updating dependencies...
[✓] Dependencies updated.

Swapping files...
Deleting old files...
 5441/5441 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
Copying new files...
 5444/5444 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

[✓] Statamic has been successfully updated to 2.8.5!


Cleaning up...
[✓] All clean.
arwen:silbersee-statamic arwen$
```

### Server Details

**Operating System**: Mac OS X 10.13.4

**Web Server:** ningx

**PHP Version:** 7.1.11

**Statamic Version:** 2.8.5

**Updated from an older Statamic or fresh install:** 2.8.3

**List of installed addons:** mailchimp

**Comment by edalzell** [comment]
Ya I believe this is the PHP timeout kicking in, which doesn't exist on the command line

**Comment by PeterEmil** [comment]
Okay - I'll close this issue. Will update solely from the command line :)

**Comment by jackmcdade** [comment]
Not sure why this is opened without an explanation, but if you're seeing the issue again take a look at increasing the php max_execution_time: <https://docs.oseems.com/general/application/php/increase-max-execution-time>

**Comment by PeterEmil** [comment]
I'm sorry Jack, wanted to explain but then I got through on my local install using `php please` - always good to ask things politely ;)
Just opened a question on the lodge because of a similar issue on the live staging server. I'll check your link and see if that'll fix the issue.
