### ISSUE TITLE
Pasting text into Bard breaks formatting

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#1786]
### Expected behaviour
Pasting a text with paragraphs into Bard works as expected.

### Actual behaviour
Things literally blows for two reasons: auto link is enabled and pasting isn't forcing plain text.
Paragraphs will be mixed with `<div>`s instead of `<p>`s and auto linker will hijack random text pieces and turn them into links, when the editor update its contents.

Tried and tested several ways with this text:
*Hos os finder du ideelle faciliteter til alle former for konferencer, møder og udstillinger.
Vi ligger med kort afstand til Roskilde by og kun ca 30 min. fra København, så det er let for dine deltagere at komme til og fra mødet eller konferencen.

Da vi har masser af dejlige udendørs områder, er der rig mulighed for at udfordre deltagerne eller teamet i en række anderledes, sjove og spændende aktiviteter. Der er bl.a. mulighed for Walk & Talk ved Roskilde Fjord, Firma picnic, Ice- and mindbreakers, Shake a drink, Grillarrangement, Petrispil, Øl- og vinsmagning, Fægtning, Stomp, Billiard og dartturnering m.m.*

### Steps to reproduce
1. Paste the above text (between *) into Bard and press enter.
2. See it turn `udstillinger. Vi` into a link (it shouldn't) and encapsulating everything in `<div>`s. 
3. Cry a lot trying to correct the errors.
4. Give up and write the text manually.

### Server Details

**Statamic Version:** 2.8.5

### Solution

Return MediumEditor to its default settings by removing `autoLink` and `paste` options from `initMedium()` in `BardText.vue`.
This will correctly paste text and wrap it in paragraphs, and not turning text pieces into links.

**Comment by jackmcdade** [comment]
I've added support for all relevant MediumEditor options so you can customize the behavior to suit your needs. Will be in the next update. If you need a build before that release (likely the end of this week or sometime next), just let me know.
