### ISSUE TITLE
Use secure flag for XSRF-TOKEN and secure + httponly for the laravel_session

### ISSUE THREAD

**Issue by bnorton** [statamic/v2-hub#1790]
Currently these two cookies are not marked as `Secure`.

Since the Secure flag is not set on the cookies, the browser will subsequently send it over an unencrypted channel (plain HTTP) if such a request is made. This leaves the session token open to capture and hijack.

If the laravel_session cookie does not really need to be accessible from JavaScript then it should be marked as `httponly`

Proposed solution: allow configuration of the these flags  🎉

**Comment by jasonvarga** [comment]
Add `SESSION_SECURE=true` to your `.env`

**Comment by bnorton** [comment]
@jasonvarga Thanks for the info -- hope this "googles" now for others
