### ISSUE TITLE
Routes do not appear

### ISSUE THREAD

**Issue by sembogaarts** [statamic/v2-hub#1792]
### Actual behaviour
I just updated my website from version 2.8.5 to 2.8.6. After the update, my routes at /cp/settings/routes do not appear.

### Steps to reproduce
1.  Upgrade from version 2.8.5 to 2.8.6
2.  Goto /cp/settings/routes

### Server Details

**Operating System**:
macOS High Sierra 10.13.2 

**Web Server:**
nginx/1.12.1

**PHP Version:**
PHP 7.1.8

**Statamic Version:**
2.8.6

**Updated from an older Statamic or fresh install:**
Update from 2.8.5

**Comment by jackmcdade** [comment]
Fixed for next release!
