### ISSUE TITLE
Value of yaml fields not shown 

### ISSUE THREAD

**Issue by krausste** [statamic/v2-hub#1794]
### Expected behaviour
The value of the YAML field should be displayed.

### Actual behaviour
YAML field is empty even though a value exists.

### Steps to reproduce
1.  Navigate to Configure->Settings 
2.  Look at the YAML values for Filesystem or Redactor Settings

### Server Details

**Statamic Version:** 2.8.6

**Updated from an older Statamic or fresh install:** 2.8.5

![statamic 2 8 6 - empty yaml fields](https://user-images.githubusercontent.com/5039360/36481441-23df0b54-1710-11e8-9120-29b2f50c6854.png)

**Comment by jackmcdade** [comment]
Fixed for next release!
