### ISSUE TITLE
Consider setting a cursor when an empty bard field ist clicked

### ISSUE THREAD

**Issue by eike-hass** [statamic/v2-hub#1795]
### Expected behaviour
When the gray area around the editable section of a Bard field is clicked the textarea should be focused so that a cursor is set.

### Actual behaviour
It is quite hard to click the editable area in an empty bard field to get startet writing.  

### Steps to reproduce
1.  Click on the outer gray area on a bard field
2.  notice you see no cursor

**Comment by eike-hass** [comment]
So the fix works great vetically! but horizontally it is still not ideal

**Comment by jackmcdade** [comment]
Horizontal is much trickier with the buttons and controls. This was the best I could do on short notice without building a whole click event tracking solution. How critical is the 40px horizontal gap?

**Comment by eike-hass** [comment]
Not that important. I think the vertical fix helps a lot already. We will monitor how the users react to the present iteration. 
Should we reopen this issue for the horizontal behavior or move the discussion to a new issue?
