### ISSUE TITLE
Form submission data doesn't get sanitized while being viewed in the CP

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#1796]
### Expected behaviour
A form submission with a code snippet won't execute while being viewed in the CP.

### Actual behaviour
A form submission with a code snippet _does_ execute in the CP.

### Steps to reproduce
Formset:
```
fields:
  name:
    display: Full Name
  message:
    display: Message
```

Submission:
```
name: John Doe
message: |
  <script>
    alert('boom')
  </script>
```

### Note

Had a 'real world' issue this morning where a visitor had submitted the following snippet (not with malicious intent) which caused the browser to redirect (and 404) whenever the form listing page was accessed. The `comments` field was added as a column, so was also getting executed there.

```
comments: |
  ...

  <!DOCTYPE html>
  <html>
  <meta http-equiv="Refresh" content="0; URL=/ui/login.jsf"/>
  <body></body>
  </html>
```

**Comment by jackmcdade** [comment]
Hey nice catch. Curious that didn't get sanitized on the submission itself though. Very strange indeed. Fixed for next release!

**Comment by jasonvarga** [comment]
@aryehraber What Statamic version was this using?

**Comment by aryehraber** [comment]
@jasonvarga Pretty sure this was on latest _at the time_ (so may well be a minor version or 2 ago)

**Comment by jasonvarga** [comment]
If you submit that HTML, does it still get saved to the YAML file unsanitized?

**Comment by aryehraber** [comment]
Will try and test this week and get back to you!
