### ISSUE TITLE
FR: Allow getConfig to traverse nested settings using dot-notation

### ISSUE THREAD

**Issue by simonhamp** [statamic/v2-hub#1803]
### Expected behaviour
Nested config would be accessible via dot-notation in an add-on using `$this->getConfig('example.setting.key', 'bar')` for:

```yaml
example:
  setting:
    key: foo
```

### Actual behaviour
`null` is returned.

### Steps to reproduce
1.  See above
2.  Have a KitKat
3. Throw your rubbish in the trash

### Server Details

**Operating System**: Mac OS

**Web Server:** Laravel Valet

**PHP Version:** 7.1

**Statamic Version:** 2.8.7

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** Spock, OAuthBridge

### Suggestion
Instead of direct array access, consider using `array_has($config, $key)` and `array_get($config, $key)` to use Laravel's built-in dot-notation array accessors in `Statamic\Extend\Extensible::getConfig()`, on L:256 and L:257 respectively.

**Comment by jackmcdade** [comment]
Try using colons are a delimiter instead. :)

**Comment by simonhamp** [comment]
@jackmcdade do you mean `$this->getConfig('example:setting:key')`?

If so, that still returns `null` for me... :(

**Comment by jackmcdade** [comment]
Ah you're right. Added for next release 👍

**Comment by simonhamp** [comment]
Awesome. Which method should I use then in readiness: dot-separated or colon-separated?

**Comment by jasonvarga** [comment]
Go for dots.
