### ISSUE TITLE
Bard: Unable to rearrange sets within the bard field in CP

### ISSUE THREAD

**Issue by itsHall** [statamic/v2-hub#1814]
When trying to rearrange sets either in the Fieldsets page of the CP or on the Collections > Product > Page the rearrange option simply won't work.

![bard issue](https://user-images.githubusercontent.com/571529/36794797-58ca108e-1c6f-11e8-86f1-c6336ba2e5f8.gif)

### Steps to reproduce
1.  Add a Bard to a Fieldset (we used a collection page's Fieldset)
2.  Add at least 2 Sets
3.  In each set create a Field (we created a Redactor in one and Text in the other)
4. Try to rearrange the Sets

We are also having an occasional issue where buttons in the Fieldset interface won't work (add set, close window, rearrange, delete, etc.)

### Server Details

**Operating System**:
MacOS High Sierra v10.3.3

**Web Server:**
Nginx

**PHP Version:** 
PHP 7.1.13

**Statamic Version:** 
2.8.7

**Updated from an older Statamic or fresh install:** 
Updated

**List of installed addons:**
Favicon v1
Recaptcha v2

**Comment by jackmcdade** [comment]
Fixed for next release.
