### ISSUE TITLE
FR: Preserve image filenames after glide modifications and caching 

### ISSUE THREAD

**Issue by gmcz** [statamic/v2-hub#1819]
It'd be really great if I could both serve cached images which have been modified by Glide, as well as preserve their filenames (or at least let me overwrite them with the filename parameter). 

The problem with the status quo is that you must choose between speed performance, and syntactic performance both of which can be important for user and search experience.

Related: https://github.com/peda/statamic-glide-vanity-url does a good job in un-cahced mode.

**Comment by jasonvarga** [comment]
Not really, no. This would require a change to the Glide library itself.

**Comment by gmcz** [comment]
Ok, I'll go open an issue over there and refer to this one.

**Comment by jackmcdade** [comment]
This just fundamentally isn't possible with Glide. Will close this down. 👋
