### ISSUE TITLE
Misunderstanding

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1821]
Here I have some misunderstanding:
`'thumbnail_max_width' => 'Max image width for thumbnails',
    'thumbnail_max_width_instruct' => 'Images wider than this will not have thumbnails generated.',

    'thumbnail_max_height' => 'Max image height for thumbnails',
    'thumbnail_max_height_instruct' => 'Images taller than this will not have thumbnails generated.',`

In the first sentence, I was thinking that 'Max image width' is for thumbnail itself and thumbnail will be generated in this width! The second sentence says that this width mentions original images.

And also, I think it is common that we won't generate thumbnails for images smaller than requested width...

**Comment by jackmcdade** [comment]
Can you think of a better way to phrase it? We couldn't really, hence the additional information in the very next line. Feel free to reopen if you have a 🔥 idea!
