### ISSUE TITLE
FR: Add ability to copy an asset's absolute URL from "Assets" section

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#1822]
Perhaps I'm missing something, but it seems this isn't currently possible.

### Expected behaviour
I would like to be able to upload a file and then grab the full URL to share with others. 

### Actual behaviour
I need to manually put the full URL together using the base url + '/assets/' + the folder/file path.

**Comment by wesort** [comment]
This was added in v2.10.3. 

![link-to-absolute-url](https://user-images.githubusercontent.com/3920126/43640655-9b9b629a-9718-11e8-9768-2ba16d4ed880.png)
