### ISSUE TITLE
Glide in a controller doesn't resize images

### ISSUE THREAD

**Issue by bgauslin** [statamic/v2-hub#1828]
### Expected behaviour

`$asset->manipulate($params)` resizes an image per the parameters passed to it.

### Actual behaviour

Generated images aren't resized.

### Steps to reproduce

1. Create a controller with a method that will resize a 1200 x 900 image.

2. Set parameters to resize the image to 400 x 300:

```
$params = [
  'width' => 400,
  'height' => 300,
  'fit' => 'crop',
];
```

3. Resize the image via `manipulate()` as [per the docs](https://docs.statamic.com/addons/api/asset#manipulate)

```
$asset = Asset::find($file);
return $asset->manipulate($params);
```

4. The image is still 1200 x 900.

5. Clear caches and delete all generated images.

6. Call the method that resizes the images.

7. The newly generated image is again 1200 x 900.

### Server Details

**Operating System**: macOS 10.13.3

**Web Server:** Apache2

**PHP Version:** 5.6.26

**Statamic Version:** 2.8.7

**Updated from an older Statamic or fresh install:** fresh install

**List of installed addons:** none

### Logs

N/A

**Comment by jasonvarga** [comment]
It just generates a URL, it doesn't actually generate the image.

It will generate the image if you have `image_manipulation_cached: true` in `assets.yaml`. Do you have that set?

**Comment by bgauslin** [comment]
Yes, I have that in assets.yaml.

I'm using Statamic as a headless CMS, with all data available via JSON responses, and the images are generated the moment I make a JSON request.

I've tested this by deleting all generated images manually, visiting the URL that serves JSON (which includes URLs to images that are processed by Glide), and then a new batch of images shows up.

Glide works fine in Antlers templates with 'content_type: json' in yaml and content files, but not when I use controllers to render the responses.

**Comment by el-schneider** [comment]
I just ran into the same Issue. `image_manipulation_cached: true` didn't help me.

**Comment by jasonvarga** [comment]
Are you passing `width` and `height` into the array? It should be `w` and `h`.

**Comment by axelferdinand** [comment]
@bgauslin Did you get this working? I'm trying to accomplish the exact same thing here now...
