### ISSUE TITLE
FR: tooltip for replicator set's add button

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1832]
In Statamic V1 there we can add instruction as a tooltip to replicator set's button.
In V2 I expect this feature too. And it would be great to be able to add rich content like images to the tooltip.

**Comment by jasonvarga** [comment]
This actually already exists.
Although there's a bug in the tooltip library we use that incorrectly positions the tooltips when the page is scrolled.

It's fixed for next release!
