### ISSUE TITLE
FR: Pass any attribute to a {{ form:create }} tag ...

### ISSUE THREAD

**Issue by subpixelch** [statamic/v2-hub#1836]
The `attr` tag inside `{{ form }}` should pass through **anything**, like:

`{{ form:create in='partner' attr='style="display: none;" ' }}`
or
`{{ form:create in='partner' attr='my-data="anything" ' }}`

### Expected behaviour
`{{ form:create in='partner' attr='style:"display: none;"' }}`

should output:

`<form method="POST" action="/!/Form/create" style="display:none;">`

### Actual behaviour
It outputs:

`<form method="POST" action="/!/Form/create" style="" display"="">`

### Steps to reproduce
1.  Make a form
2.  render in Browser
3.  ... voila

### Server Details

**Operating System**: MacOS latest

**Web Server:** Nginx / Valet

**PHP Version:** 7.2

**Statamic Version:** 2.8.8

**Comment by jackmcdade** [comment]
At that point it's easier to just write the form action yourself `e.g. action="/!/Form/Whatever"` and then write your own HTML :)
