### ISSUE TITLE
FR: Add grid rows by hitting `return` key

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1844]
While I was working on grid fieldtype, I thought this feature would be very useful and no need to repeatedly click add row button.

**Comment by jackmcdade** [comment]
The function of the `return` key varies greatly depending on the fieldtype that you're in, _inside_ the grid. If we were to override it, many fields like Markdown, Redactor, Textarea, Tags, and all Relate fields would stop functioning properly.

We would definitely need to think of a different, unused shortcut.

**Comment by peimn** [comment]
Yes indeed, I had a vision of that problem too. But I thought it would be easy as like to say I am on Grid element so the return would add new row...
What about shortcut like `shift+return`?

**Comment by jackmcdade** [comment]
At this point it's too convoluted to add in our v2 grid implementation. Perhaps in v3.
