### ISSUE TITLE
FR: Merge addon composer repositories array

### ISSUE THREAD

**Issue by simonhamp** [statamic/v2-hub#1850]
### Expected behaviour
When upgrading, I expected the upgrade to succeed.

<img width="988" alt="screen shot 2018-03-21 at 13 33 58" src="https://user-images.githubusercontent.com/31628/37713096-bbae9cde-2d0d-11e8-8857-cf5437b93d39.png">

### Actual behaviour
The upgrade failed.

### Steps to reproduce
Attempt an upgrade from within the CP

### Server Details

**Operating System**:
Mac

**Web Server:**
Valet Plus

**PHP Version:**
7.1.12

**Statamic Version:**
2.8.7

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**
statamic/oauth-bridge

### Logs
None

**Comment by jackmcdade** [comment]
Does your server have `composer` installed?

**Comment by simonhamp** [comment]
Yep composer is installed and working as intended.

It seems that if I remove all of the add-ons and attempt the upgrade it all works. I haven't been able to narrow down if it's a specific add-on that's causing the problem though.

**Comment by simonhamp** [comment]
After further investigation on this, it appears to be because one of our custom add-ons references some private packages.

The problem stems from us needing to append the repository references for these packages to our `composer.json` repositories array, e.g.

```json
    "repositories" : [
        {
            "type": "path",
            "url": "../site/addons/*",
            "options": {
                "symlink": false
            }
        },
        {
            "type": "git",
            "url": "git@github.com:vendor/custom-package.git"
        }
    ],
```

How can we achieve that during the update process?

Ideally it would be great if the add-on `composer.json` could define these somehow and they get pulled in and merged into the finalised `statamic/composer.json`.

**Comment by simonhamp** [comment]
@jackmcdade @jasonvarga any thoughts on this?

We have a workaround in place, so it's not urgent, but it would be sweeter than a banana split if it could all be handled in the upgrade process

🍌

**Comment by jasonvarga** [comment]
Hey Simon, right now we just merge in `requires` from any addon composer files. We'll need to support also merging in `repositories`. For now you could manually add your repositories to `statamic/composer.json`

**Comment by simonhamp** [comment]
Sure, that's our workaround. Will continue with that until this gets sorted. Happy for you to close this off or leave open as you see fit 👍

**Comment by jasonvarga** [comment]
I've renamed it the title and marked it as a feature request. I'll leave it open!

**Comment by jackmcdade** [comment]
Statamic v3 will be all different/standard Laravel style. Will close this down :)
