### ISSUE TITLE
Can't drag/drop Asset Files in a Bard Field

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#1854]
### Expected behaviour
To be able to drag/drop File Assets in a Bard field to change order.  To also be able to see the title or filename when in Grid view.

### Actual behaviour
Setup an Asset field in Bard.  Upload a few PDFs.  You cant drag/drop files, and in Grid View the filename is missing.

### Server Details

**Operating System**: OSX

**Web Server:** Laravel Valet

**PHP Version:** 7.1

**Statamic Version:** 2.8.8

**Updated from an older Statamic or fresh install:** Fresh

**Comment by aerni90** [comment]
I really need this to work as well.

**Comment by jackmcdade** [comment]
Fixed for next release, which will be today. 👍
