### ISSUE TITLE
Testing Environment: Most `Statamic\API` classes won't return data

### ISSUE THREAD

**Issue by marsvogel** [statamic/v2-hub#1855]
### Expected behaviour
While running `please test`, classes in the `Statamic\API` namespace should return something, when calling appropriate methods like `::all()` or `::find()`.

### Actual behaviour
Most classes in the `Statamic\API` namespace return nothing while running the test suite. You can however write content.

*Not Working*

- `Statamic\API\Term`
- `Statamic\API\Page`
- `Statamic\API\Asset`
- `Statamic\API\Entry`
- `Statamic\API\GlobalSet`
- `Statamic\API\Collection`

*Working*

- `Statamic\API\Taxonomy`

### Steps to reproduce

Basically create a fresh install and try some `Statamic\API` classes in tests.

```bash
statamic new testing # omit user creation
cd testing/statamic && composer install && cd .. # enable testing
php please make:test StatamicApi # see [Logs and Files]
php please test site/tests/StatamicApiTest # see [Logs and Files]
```

### Server Details

**Operating System**: macOS 10.13.3 (High Sierra) with Laravel Valet 2.0.8

**Web Server:** nginx/1.12.1

**PHP Version:** PHP 7.1.10

**Statamic Version:** 2.8.8

**Updated from an older Statamic or fresh install:** fresh install

**List of installed addons:** no addons installed

### Logs and Files

<details>
<summary>Test file <code>testing/site/tests/StatamicApiTest.php</code></summary>

```php
<?php

use Statamic\API\Term;
use Statamic\API\Page;
use Statamic\API\Asset;
use Statamic\API\Entry;
use Statamic\API\Taxonomy;
use Statamic\API\GlobalSet;
use Statamic\API\Collection;
use Statamic\Testing\TestCase;

class StatamicApiTest extends TestCase
{
    /** @test */
    public function should_have_any_entries()
    {
        $this->assertGreaterThan(0, Entry::all()->count());
    }

    /** @test */
    public function should_have_any_assets()
    {
        $this->assertGreaterThan(0, Asset::all()->count());
    }

    /** @test */
    public function should_have_any_collections()
    {
        $this->assertGreaterThan(0, Collection::all()->count());
    }

    /** @test */
    public function should_have_any_terms()
    {
        $this->assertGreaterThan(0, Term::all()->count());
    }

    /** @test */
    public function should_have_any_globals()
    {
        $this->assertGreaterThan(0, GlobalSet::all()->count());
    }

    /** @test */
    public function should_have_any_pages()
    {
        $this->assertGreaterThan(0, Page::all()->count());
    }

    /** @test */
    public function should_have_any_taxonomies()
    {
        $this->assertGreaterThan(0, Taxonomy::all()->count());
    }
}

```

</details>

<details>
<summary>Output of <code>php please test site/tests/StatamicApiTest</code></summary>

```bash

PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

FFFFFF.                                                             7 / 7 (100%)

Time: 1.13 seconds, Memory: 20.00MB

There were 6 failures:

1) StatamicApiTest::should_have_any_entries
Failed asserting that 0 is greater than 0.

/Users/christopher/Desktop/testing/site/tests/StatamicApiTest.php:17

2) StatamicApiTest::should_have_any_assets
Failed asserting that 0 is greater than 0.

/Users/christopher/Desktop/testing/site/tests/StatamicApiTest.php:23

3) StatamicApiTest::should_have_any_collections
Failed asserting that 0 is greater than 0.

/Users/christopher/Desktop/testing/site/tests/StatamicApiTest.php:29

4) StatamicApiTest::should_have_any_terms
Failed asserting that 0 is greater than 0.

/Users/christopher/Desktop/testing/site/tests/StatamicApiTest.php:35

5) StatamicApiTest::should_have_any_globals
Failed asserting that 0 is greater than 0.

/Users/christopher/Desktop/testing/site/tests/StatamicApiTest.php:41

6) StatamicApiTest::should_have_any_pages
Failed asserting that 0 is greater than 0.

/Users/christopher/Desktop/testing/site/tests/StatamicApiTest.php:47

FAILURES!
Tests: 7, Assertions: 7, Failures: 6.

```

</details>

**Comment by marsvogel** [comment]
I stumbled apon this issue while developing an addon for statamic. While trying to track this issue down I figured out, that a fresh install of statamic has this issue to. I also tried to tinker with the various environments and `bootstrap/` files, but I didn't get some useful informations out of this adventure. If it is useful for you, I can write a more elaborate test suite and share the results with you.

**Comment by jasonvarga** [comment]
The stache is empty in tests. We use a fake version of it. It doesn't read from your real content.
This was mainly done so our internal tests would be faster, wouldn't read from the filesystem each time, and wouldn't be affected by the Redwood sample content. 

However when _saving_ stuff, it does actually write to disk, so there's a bit of an overlap between the fake-ness and real-ness of it. 

In the example test you posted in this issue, are these what you're actually wanting to test? Or just examples to show that its not working how you expect?

**Comment by jackmcdade** [comment]
Since we're unable to recreate this and haven't received any more info, I'm going to close this issue. Feel free to reopen if you're back into it!

**Comment by simonhamp** [comment]
How can we fake some specific content where functionality relies upon the actual content?
