### ISSUE TITLE
FR: Default option for Radio Fieldtype

### ISSUE THREAD

**Issue by aerni90** [statamic/v2-hub#1859]
### Expected behaviour
Being able to set a default, preselected option for the Radio Fieldtype the same way it's already possible with the Select Fieldtype.

**Comment by jackmcdade** [comment]
It's already possible. Just set the default value.

![image](https://user-images.githubusercontent.com/44739/38104432-182752a4-3357-11e8-92ea-84b3a00ea326.png)
