### ISSUE TITLE
Add `bard_preview` param to hide preview text

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#1862]
<img width="777" alt="screenshot 2018-03-30 22 10 55" src="https://user-images.githubusercontent.com/414211/38158682-5b189422-3467-11e8-80af-e93fe85e776b.png">

**Comment by jasonvarga** [comment]
You can add `replicator_preview: false` to the fields. (Bard is basically Replicator)

**Comment by mikemartin** [comment]
It didn’t seem to work when I tried.

**Comment by jasonvarga** [comment]
You have to add it to each field, not the set.

**Comment by mikemartin** [comment]
@jasonvarga Got it. Thx!
