### ISSUE TITLE
Browser's "Previous" May Fail in CP Taxonomy Preview Page?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#1864]
YYMV, but here's what I'm seeing in Statamic 2.8.10 (as updated (from 2.8.8) via the CP updater):

1) In the default download site (Redwood), log in to the CP.
      Displays "Dashboard" page. (OK)
      
2) In the sidebar on the left, select "Tags".
      Displays "Tags" page. (OK)

3) From the tags displayed, select the last one, "winter".
      Displays "winter" page. (OK)

4) In the upper right, tap the "Live Preview" button.
      Preview area on right shows "winter" page with 2 page summaries (OK):
         a) Paperwork and Snowshoeing
         b) My First Day

5) Tap on the first headline to select "Paperwork and Snowshoeing"
      Preview pane changes to show the "Paperwork and Snowshoeing" page. (OK)

6) In the BROWSER controls, select the "Back" or "<" (Show the previous page) command
      OOPS: Infinite page-loading spinner appears in preview area.

7) "CURE": Select "Back" or "<" (Show the previous page) again.
      Preview pane gone; we're back on the "Tags" page.

   (FWIW, if in step 3) you pick "coffee", then etc., Safari works, but Firefox still spins forever.)
🤷‍♂️ 
-----
EXPECTED BEHAVIOR:

6) In the BROWSER controls, select "Back" or "<" (Show the previous page) command
      Preview pane returns to "winter" page with 2 page summaries:
         a) Paperwork and Snowshoeing
         b) My First Day

-----
mac OS High Sierra 10.13.4
Safari 11.1
Firefox Quantum 64.0.2 (64-bit)
Statamic 2.8.10 (as updated (from 2.8.8) via the CP updater)

**Comment by iDGS** [comment]
Clearly not a show-stopper, but I wanted to be faithful to report the behavior in case it might have other unknown-to-me implications.

**Comment by jackmcdade** [comment]
I don't know how to follow this one. Any work flow that requires using the Back button in a scenario the relies on sessions and caches is prone to a glitch now and then. Unless this becomes a showstopper, I'm going to go ahead and close it. Thanks!
