### ISSUE TITLE
Partial Page Cache filename bug

### ISSUE THREAD

**Issue by warkior** [statamic/v2-hub#1873]
### Expected behaviour
When I wrap areas of a template in `{{ cache }}` tags, I expect it to cache that specific area of the template for that specific page.

### Actual behaviour
Option 1: cache with no defined scope…
This causes all pages that use the same template to display the same content. So, whichever article was cached first, that’s the one that is displayed across all pages using the same template.

Option 2: cache with page scope…
This causes the cache to repeat itself. So if you have multiple places on the template that you are trying to cache, it replicates the first one.

### Steps to reproduce
1.  Create a template
2.  Set up multiple pages to use the same template
3.  Wrap some dynamic or slow content in `{{ cache }}` tags.
4. See the same content on both pages that use the template.
5. Wrap more than one section of content in `{{ cache scope="page" }}` tags.
6. See that piece of content reproduced multiple times on the page.

### Server Details

**Statamic Version:** 2.8.10

**Updated from an older Statamic or fresh install:** Updated

**Comment by jasonvarga** [comment]
Maybe I'm not understanding the issue.

> Option 1: cache with no defined scope…
> This causes all pages that use the same template to display the same content. 

This is expected. Are you saying it's not working correctly?

> Option 2: cache with page scope…
> This causes the cache to repeat itself

Repeat where?

**Comment by warkior** [comment]
If I have a single `{{ cache scope="page" }}` area on the template, then it seems to work. Things are fast, and different pages using the same template seem to keep their proper unique caches. BUT for example, I have a form in the middle of the page, so I want to have a partial cache at the top, and another at the bottom, while leaving the form uncached. The result of trying to do this is that when I view the page, the top partial cache is repeated in the bottom partial cache, instead of the bottom being cached separately.

**Comment by jasonvarga** [comment]
🤔

Can you try something, just to test...

Split your page into partials. So your page probably looks like this:

```
{{ cache scope="page" }}
   part one
{{ /cache }}

{{ cache scope="page" }}
   part two
{{ /cache }}
```

Change it to this:

```
{{ partial:part_one }}
{{ partial:part_two }}
```

```
# partials/part_one.html
{{ cache scope="page" }}
   part one
{{ /cache }}
```

```
# partials/part_one.html
{{ cache scope="page" }}
   part two
{{ /cache }}
```

**Comment by warkior** [comment]
Hey Jason. I tried this almost verbatim, and my page ended up displaying `part one part one`.
https://s.warkior.com/template_partials_2077D110.png

**Comment by warkior** [comment]
@jasonvarga I may have a possible cause... and also relates to a different potential bug...

In line 23 of /statamic/bundles/Cache/CacheTags.php you have:
`$hash = ($this->get('scope', 'site') === 'page') ? md5(URL::getCurrent(), $this->content) : md5($this->content);`

This creates cached file paths that look like this...
`b"troves:0÷G9Õ…+\x00\x01kQ*­ñÙ\x15"`

This basically returns a md5 hash and the second parameter you pass to it configures it to return it's results in binary. So it returns the same hash for any url, but in binary.

I think what you meant to do was this:
`$hash = ($this->get('scope', 'site') === 'page') ? md5(URL::getCurrent() . $this->content) : md5($this->content);`

This results in hashes that look like:
`"troves:57e3c99bca0c3599419519b23bba216f"`

So, page scoped hashes include the url and content.

**Comment by warkior** [comment]
Incidentally, the other bug I mentioned is that sometimes the cache doesn't want to save to the disk due to the strange binary file name.

**Comment by jasonvarga** [comment]
> I think what you meant to do was this:

Yup, that should definitely _not_ be a comma.

Does changing that to a `.` fix your issue or is it still there?

**Comment by warkior** [comment]
Yep. Fixes the issues.
