### ISSUE TITLE
Environment called "testing" created - site returns a 404 if "en" is not the default locale

### ISSUE THREAD

**Issue by goellner** [statamic/v2-hub#1876]
### Expected behaviour

Statamic should use the settings from "testing.yaml" and should not overwrite other settings.

### Actual behaviour
Which it does, but I think it is changing the default locale to "en", which breaks the site.

### Steps to reproduce
1. set default locale to be anything but "en"
1.  create ".env" file with "APP_ENV=testing"
2. create environment settings file "site/settings/environments/testing.yaml"
3. visit website.

### Server Details

**Operating System**:
MacOS / Linux
**Web Server:**
Apache
**PHP Version:**
7.2
**Statamic Version:**
2.8.10
**Updated from an older Statamic or fresh install:**
Updated

### Suggestions
I guess this behaviour is relate to unit tests and other testing stuff. Anyways it should stated in the docs, when using "testing" as an environment, that the site may break.

**Comment by jasonvarga** [comment]
Call it something else. `testing` is for running tests.

We'll document it.
