### ISSUE TITLE
cp uses incorrect urls when using 'valet share'

### ISSUE THREAD

**Issue by lardnicus** [statamic/v2-hub#1882]
### Expected behaviour
using 'valet' automatically generates urls like http://myfoldername.localhost/
running 'valet share' on a site generates a url like http://1234example.ngrok.io
this url can be placed in site > settings > system.yaml

locales:
 en:
   full: en_US
   name: English
   url: http://1234example.ngrok.io

site is expected to use the url specified in the settings.

### Actual behaviour
site works to a certain extent, however some urls in the Statamic control panel are replaced with the default valet url (eg http://myfoldername.localhost/)

this url is not in any of the project files (fresh install and I also performed a full folder search).

### Steps to reproduce
1.  download a fresh copy of statamic v2
2.  use laravel valet
3.  start 'valet share' and then try to navigate to a blog post in the Statamic control panel

### Server Details

**Operating System**:
MacOS 10.13.3

**Web Server:**
laravel valet

**PHP Version:**
php71

**Statamic Version:**
latest

**Updated from an older Statamic or fresh install:**
fresh install

**List of installed addons:**
non

### Logs
not applicable

**Comment by jasonvarga** [comment]
This will be fixed in 2.9 - what you'd need to do is place the ngrok url  in your system.yaml locales array (like you demonstrated)
