### ISSUE TITLE
FR: Show non-localized fields for non-primary languages

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#1883]
It can be confusing at times editing content for non-primary languages, when a lot of fields disappear and change the layout of the remaining fields.

I instead suggest that non-localized fields are always shown when editing non-primary languages and marked as locked/disabled/readonly, so full content information is preserved at all times.

We've had feedback from clients being confused when editing content for non-primary languages, as a lot of fields suddenly are "missing".

**Comment by jasonvarga** [comment]
100% agree.
