### ISSUE TITLE
content pages are not search through

### ISSUE THREAD

**Issue by 4kets** [statamic/v2-hub#1884]
### Expected behaviour
Tell us what you assumed would happen, as optimistically as possible. We're here to help/ :)
If it's just "it should work", you can remove this section.

search through all content to get find every page/collection containing "word

### Actual behaviour
Tell us what happened instead"

returns only the search results where "word" is contained in collections

**Comment by jackmcdade** [comment]
You need to tell Statamic what fields to index and search. Here are the docs: <https://docs.statamic.com/search#indexing>

**Comment by 4kets** [comment]
i did that
![image](https://user-images.githubusercontent.com/20043831/38681387-d6a114ce-3e68-11e8-838d-2f576d54068d.png)

**Comment by jackmcdade** [comment]
That should work. Can you show your search template code?

**Comment by 4kets** [comment]
![image](https://user-images.githubusercontent.com/20043831/38682904-8364f3b2-3e6c-11e8-9917-334e8180d9a3.png)

**Comment by jackmcdade** [comment]
Hm, looks pretty 👌 to me. Can you try running `php please search:update` from the command line and trying again?

**Comment by 4kets** [comment]
nope it works for the content in collections but in pages it says no-results

**Comment by 4kets** [comment]
Update it still does not work but if i search pages then it works. If i search text on a page it doesn't . collection i can find everything.

**Comment by 4kets** [comment]
i have solved it you have to set the blocks in the searchable array

i mean this 
![image](https://user-images.githubusercontent.com/20043831/38769348-b5f76558-4001-11e8-8f4e-294d55ea9060.png)

so my searchable array is 
![image](https://user-images.githubusercontent.com/20043831/38769353-c58267ac-4001-11e8-93f8-a2dce6e40c0a.png)

**Comment by jackmcdade** [comment]
Yes exactly, I'm sorry I wasn't more clear in my very first reply :) All the field names you want to search need to be explicitly defined.
