### ISSUE TITLE
Bug: Antlers Parser: Conditionals inside variables not working

### ISSUE THREAD

**Issue by peda** [statamic/v2-hub#1885]
### Expected behaviour
When using Antlers syntax inside variables (aka content fields) then I do expect the entire syntax to work and not certain things only. 

This would be super useful for clients as they can do simple conditions inside the content withing requiring programming work.

### Actual behaviour
While tags do work in variables, conditionals do not work (neither the `if` `else` syntax nor the `or` variant)

### Steps to reproduce
1.  Create a page with multiple fields
2.  Write into the `content` field `{{ variable1 or variable2 }}`
3.  Output the content field in the template using `{{ content }}`
4.  If `variable1` is set everything seems to work fine
5.  If `variable1` is not set, but `variable2` is set, then nothing is shown
6.  Same thing happens when using `{{ if variable1 }}{{ variable1 }}{{ else }}{{ variable2 }}{{ /if }}`

### Server Details

**Operating System**: CentOS

**Web Server:** Apache 2

**PHP Version:** 7.0

**Statamic Version:** 2.8.10

**Updated from an older Statamic or fresh install:** update

**List of installed addons:** N/A

### Logs
No logs ...

**Comment by goellner** [comment]
+1

**Comment by jasonvarga** [comment]
@goellner Please use the reactions, not +1's.

Are you guys saying you're putting Antlers templating _inside_ other variables? In your markdown files?

**Comment by peda** [comment]
Yes, we are using Antlers templating inside other variables (in our markdown files) - this is working perfectly fine for tags, modifiers and so on, but not for conditionals.

**Comment by jasonvarga** [comment]
I have a page like this:

```
---
foo: Hello
bar: World
---
{{ foo or bar }}

{{ if foo }}{{ foo }}{{ else }}{{ bar }}{{ /if }}
```

and a template like this:

```
{{ content }}
```

This renders `Hello Hello`.

If I get rid of `foo` from the front-matter, it renders `World World`.

This seems like what you're describing isn't working - but it is working fine here.

Can you show what you're _actually_ doing and where it's breaking?
We can continue in support@statamic.com if you don't want to post your data publicly.

**Comment by peda** [comment]
Our thing is a more complex sample but we were able to reproduce it with a simple sample:

We have a page like this:
```
textarea: '{{ text or markdown }} '
markdown: My Markdown Content
fieldset: kitchen
template: asdf
title: asdf
id: 0463bc55-a630-4808-ba0c-531c008f342c
```

and a template like this:
```
{{ textarea }}
```

This outputs nothing but if I do add `text: zzz` to the page, it outputs `zzz`

**Comment by peda** [comment]
If I try it inside the `content` variable like in your sample, then it's working - but if it's in another named page variable, then it isn't working.

**Comment by jasonvarga** [comment]
Only the `content` variable gets explicitly parsed, which is why it's working there.

I'm actually surprised that Tags work, but hey, we'll see what we can do.
