### ISSUE TITLE
FR: Add condition support for User tag

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#1892]
### Expected behaviour
Using the route `/user/{first_name}-{last_name}`, it would be useful if you could specify the user with a condition. For example:

```
{{ user :first_name:is="first_name" :last_name:is="last_name" }}
{{ /user }}
```

## Workaround

I've found a workaround using the Users tag, which I guess works because it's returning an array.

```
{{ users :first_name:is="first_name" :last_name:is="last_name" limit="1" }}
{{ /users }}
```

**Comment by jackmcdade** [comment]
The  {{ user }} tag is meant to be used with the current user, not to search/filter from all users. The {{ users }} tag solution would be the preferred solution. 👍

**Comment by mikemartin** [comment]
@jackmcdade is my workaround a reasonable solution? How might you have done it?

**Comment by jackmcdade** [comment]
I would do it the way you did it.
