### ISSUE TITLE
FR: Upgrade PHPUnit to latest version

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1894]
Was writing an addon with a dependency on https://packagist.org/packages/sebastian/diff.

Problem is that due to PHPUnit version, `diff` is locked at 1.4.3, whereas the most current version is 3.0.

Consequence is that I have stopped writing the addon (one that stored the content changes so you could see the audit trail of changes).

I understand this is unlikely in the 2.x series, writing this as a note for something that's possible for v3 perhaps.

**Comment by jasonvarga** [comment]
Like you mentioned, unlikely for v2. But 100% likely for v3 because it's already in there.
