### ISSUE TITLE
List Field in Bard not adjusting for mobile view

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#1896]
The link field when used in Bard is not adjusting for mobile.  I have not had a chance to test other fields yet.

![screen shot 2018-04-23 at 10 58 05 am](https://user-images.githubusercontent.com/2436728/39135091-2aec9f1e-46e6-11e8-82bc-7bc1706dfb0e.png)

**Comment by jasonvarga** [comment]
Putting this here for our own reference:
This happens when the preview text is longer than the width, and the `white-space: nowrap` rule prevents it from wrapping.

It'll happen regardless of what fields you have in your Bard sets.
