### ISSUE TITLE
Image Conditional Not Working when 3 conditions

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#1898]
`{{ alt or filename }}` works `{{ title or filename }}` works but `{{ title or alt or filename }}` fails

It skips `alt` when used in `<p>{{ title or alt or filename }}</p>`

**Comment by jackmcdade** [comment]
This is because if title is not set, we use `filename` in place. This is a CP-driven convention for the asset tile grids. We could probably decouple it though

**Comment by bgarrant** [comment]
So basically we should use `{{ alt or title }}` and it would cover them all?

**Comment by jackmcdade** [comment]
Just hang tight, I’m changing the title behavior :)

**Comment by bgarrant** [comment]
Thanks.  Keep me posted.
