### ISSUE TITLE
Control Panel Rendering Issues on Mobile Devices 

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#1906]
A couple clients have mentioned it is hard to edit with Statamic on phones. Many area of the CP have this layout issue including also forms area. A few examples. 

![4ba732d1-1475-4e29-8a0a-66c7a3cacaeb](https://user-images.githubusercontent.com/2436728/39421961-67dec200-4c39-11e8-9450-0c0fb7f98b74.png)
![3c7fc260-579e-4cd4-821e-8fc0602853c0](https://user-images.githubusercontent.com/2436728/39421962-67f32420-4c39-11e8-87c0-cb5eda7bc18e.png)
![9bf4f328-9895-40bd-a602-7ee1551ee014](https://user-images.githubusercontent.com/2436728/39422263-a1f18fd0-4c3a-11e8-8acf-53187d4b751b.png)
![ba6351e7-ad87-42ab-bcdf-225f89e891f0](https://user-images.githubusercontent.com/2436728/39422797-de4d4396-4c3c-11e8-90aa-971a3e5b43ba.png)

Images Taken on iPhone 7

**Comment by bgarrant** [comment]
I have several clients that need to make edits from mobile devices. Can this one get fixed fairly quickly?

**Comment by bgarrant** [comment]
Does this have anything to do with https://github.com/statamic/v2-hub/issues/1896

**Comment by sebszocinski** [comment]
Here are a few more bugs i've noticed to add to this.

![image uploaded from ios 3](https://user-images.githubusercontent.com/5466694/39497004-46ca429e-4de0-11e8-9f34-4e0f10c8b3fe.png)
![image uploaded from ios 1](https://user-images.githubusercontent.com/5466694/39497005-47058bc4-4de0-11e8-9091-3a58cc61e479.png)
![image uploaded from ios](https://user-images.githubusercontent.com/5466694/39497006-47434e3c-4de0-11e8-8f49-cc03650ad10b.png)

**Comment by bgarrant** [comment]
It is important we get the user experience as good on mobile as it is on all other devices. We have had two clients ask why it looks like this on mobile phones. Please fix this as soon as possible. Thanks.

**Comment by sebszocinski** [comment]
I've just mocked up a quick idea for how I think the Pages / Collections list view should look, fixing the jumbled buttons:

![statamic-mobile-ui](https://user-images.githubusercontent.com/5466694/39497660-8c49de08-4de3-11e8-9bb8-66cb0e19ac72.gif)

**Comment by bgarrant** [comment]
I like that idea

**Comment by bgarrant** [comment]
I think Bard would have a much smaller padding on mobile devices. 

![05da2aac-6536-4c4c-8bf0-2795c048aec7](https://user-images.githubusercontent.com/2436728/39497969-9d18eb7c-4d73-11e8-8a5a-baf8fbe65268.png)
