### ISSUE TITLE
BUG: Ignored segments in routes.yaml are not always ignored - Fix provided

### ISSUE THREAD

**Issue by ASochat** [statamic/v2-hub#1907]
Ignored segments in routes.yaml are not always ignored, because of an error in the code:

Line 273 of StatamicController.php (parseUrl function), you're doing 
`$remove_segments = array_intersect_key($ignore, $segments);` 
while it should be:
 `$remove_segments = array_intersect($ignore, $segments);`
A fix would be welcome :))

Thanks a lot!

**Comment by jasonvarga** [comment]
How are you using the `ignore` array in `routes.yaml`?

**Comment by ASochat** [comment]
Like this:

`ignore:
  - airbnb
  - classic
  - absence
  - invest`

**Comment by jasonvarga** [comment]
Can you give an example of a URL you hitting that isn't working correctly?

**Comment by ASochat** [comment]
With the example above, `foo.com/en/airbnb` works but  `foo.com/en/classic` doesn't, actually the segment isn't ignored in the URL before its rank in the "ignore section" in routes.yaml: classic just works if it's n°2 or more in the URL, like `foo.com/en/something/classic`. It continues like this after: `foo.com/en/something/someother/absence` works whereas `foo.com/en/something/absence`does not, and so on...

**Comment by jasonvarga** [comment]
Thank you, that's perfect. 👍
Fixed for next release.

**Comment by ASochat** [comment]
Thank you Jason :)
