### ISSUE TITLE
multiple url trailing slashes still loads page on Nginx

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#1908]
`domain.com/page///////` should either:

1. 301 redirect to `domain.com/page` 
2. chuck a 404

Possible rule to fix:

`rewrite ^/(.*)/$ /$1 permanent;`

(caveat: I believe `return 301 ...` is more efficient in Nginx but not sure of the best syntax for this)

**Comment by lukeagsmith** [comment]
Just confirming it's not just my server setup:

<https://statamic.com/why//////////>

😜

**Comment by jackmcdade** [comment]
This is a server config thing, not a Statamic issue. Thanks for the heads up tho, I suppose. :)

**Comment by lukeagsmith** [comment]
I'm not sure I agree with that. Surely that is not a valid URL and Statamic should chuck a 404?

The 301 redirect was just a suggestion of how to handle it.

Maybe at the very least worthy of an update to the sample `nginx.conf`?

**Comment by jasonvarga** [comment]
You just demonstrated that it happens on statamic.com - which is not a Statamic site.

**Comment by lukeagsmith** [comment]
Ha!

(interesting that some of the assets don't load unless you go to the proper url)

I notice they force the trailing slashing if you just go to <https://www.google.com/intl/en/about>

Statamic `sample.htaccess` has this:
