### ISSUE TITLE
FR: ImageMagick as default

### ISSUE THREAD

**Issue by steveooo9** [statamic/v2-hub#1914]
When using Statamic 2.8, GD is preselected instead of ImageMagick. Because ImageMagick is much better in performance and generally it's installed at a lot of environments, I would propose to make this the default one instead of GD. Maybe some logic like: If ImageMagick selected but not installed, use GD.

**Comment by jackmcdade** [comment]
It's better in many circumstances but not all, and is less readily installed than GD, so for now and until that changes, it will remain the default. It's not feasible to run a check like that to establish a default.

**Comment by steveooo9** [comment]
@jackmcdade Okay, seems legit!
