### ISSUE TITLE
FR: Add "display" value to Bard set with only one item

### ISSUE THREAD

**Issue by goellner** [statamic/v2-hub#1917]
**Is your feature request related to a problem? Please describe.**
When creating a Bard set with only one item (e.g. assets fieldtype), there is no visual feedback, what the set does. For example I have multiple sets with only the assets fieldtype in it, but they are creating all kinds of different content. Single image, three images in a row, a slider, a a gallery...

After adding them with the (+) button, the user can't tell for what component it is.

**Describe the solution you'd like**
Output the "display" value on top of the simplified set.

**Describe alternatives you've considered**
Added a "section" to my set. There is a CSS bug, when doing so. And the "display" value is printed out two times.

**Additional context**

![bildschirmfoto 2018-05-08 um 13 49 54](https://user-images.githubusercontent.com/3986748/39758639-b9e8050a-52d0-11e8-979b-2ec4df05aac4.png)

![bildschirmfoto 2018-05-08 um 14 51 44](https://user-images.githubusercontent.com/3986748/39758648-c0fe7982-52d0-11e8-81e7-52f539b29da2.png)

**Comment by jasonvarga** [comment]
We re-style asset-only sets to be a bit sleeker, but I can see why this would be an issue in your case.

You could (at least, temporarily) add a hidden field to each of your asset-only sets. Nothing extra should get saved, and the custom styling will be ignored because there are two fields in the set.

**Comment by goellner** [comment]
How can I create a dummy / hidden field? `show_when` only works on top level fields.

**Comment by jasonvarga** [comment]
There's a fieldtype of `type: hidden`.

```
the_image_set:
  fields:
    asset_field:
      type: asset
    hidden_field:
      type: hidden
```
