### ISSUE TITLE
Better User Permissions for Segmenting Entries and Assets

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#1919]
When we have a site with multiple authors, we need a better way to segment their entries and assets.  Sometimes we have a site where authors do not need to see other authors entries and assets, so the following would help a lot.  Taken from Craft User Groups:

![screen shot 2018-05-13 at 8 02 30 am](https://user-images.githubusercontent.com/2436728/39967109-089121ee-5684-11e8-963f-bd5a2c3eecbd.png)

When making Assets, it would be great to create a specific user folder for each author.  So when we create the asset source, we could append `{username}` to it.

**Comment by dannyuk1982** [comment]
This would allow the CP to be used for multiple users, with content sandboxed. At the moment there is no practical or dynamic way to do this. The CP works well for one user, but as soon as more are added it doesn't so well, there are workarounds such as making a collection per user, but this does not scale well and feels hacky.

**Comment by bgarrant** [comment]
For Assets, we should be able to setup an asset container with variable `images/{{ username }}` and when the user tries to upload files and it matches the username it will auto create that folder for them.

**Comment by jackmcdade** [comment]
@bgarrant that's a very separate request.

**Comment by bgarrant** [comment]
It is just same segmenting for users, but I can surely make a new ticket for that part.  It is in the first post at the bottom.

**Comment by jackmcdade** [comment]
Will be revisiting this in v3.
