### ISSUE TITLE
Dynamic Entry Titles in Collections

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#1920]
Being able to disable the need for the manual entry of Collection Entry Titles would be great.  It would be nice to be able to set them up dynamically like this:

`Post made by {username} on {date}`

This would mean when the Collections would need a toggle to either use a manual typed Title or a Dynamic one.  Kind of like they do it in Craft:

![screen shot 2018-05-13 at 8 07 23 am](https://user-images.githubusercontent.com/2436728/39967169-c03b49aa-5684-11e8-9c6a-88520229e485.png)

**Comment by jackmcdade** [comment]
It's a good idea. One we would like to tackle in v3.
