### ISSUE TITLE
`{{ env:[foo] }}` Environment tag variables aren't being affected by modifiers when used on the `/cp`

### ISSUE THREAD

**Issue by mike-zarandona** [statamic/v2-hub#1922]
**Describe the bug**
When using the environmental variable tag `{{ env:[foo] }}` in the context of the `/cp`, modifiers don't seem to have any effect on the output.  I found this issue using the CP widget type _template_.

**To Reproduce**
1. Add a variable to the `.env` file such as `deploy_start_rev=e1ab0212136840e9d51323de618ff0b4e859cdd9`
2. Create a new template to be used as a CP widget, which includes the tag `{{ env:deploy_start_rev | length }}`
3. In `cp.yaml` add this new template as a widget; verify the widget is showing on the CP dashboard
4. Notice that any string modifiers used on this variable yield the same unchanged value which exists in the `.env` file

**Expected behavior**
I would expect the modifiers to modify 😄 

**Screenshots**
Nah.

**Environment details (please complete the following information):**
 - Statamic Version:  **2.8.18**
 - Fresh Install or Upgrade:  **Upgrade**
 - OS: **macOS 10.13.4**
 - Browser: **Chrome latest**
 - Web Server: **Valet**
 - PHP Version: **7.2.4**
 - Addons installed:  **Logbook, MinifyHTML, sitemap, Spock**

**Additional context**
Thanks gents!

**Comment by jasonvarga** [comment]
Modifiers are only supported on variables, not Tags.
The env tag is a tag, therefore modifiers will not work.

Luckily in your case, there is a workaround.

Template widgets will pass anything in the YAML into your template.

```
  -
    type: template
    template: your_template
    deploy_start_rev: "{env:deploy_start_rev}"
```

Now `deploy_start_rev` is available, so you can do `{{ deploy_start_rev | length }}`
