### ISSUE TITLE
Save and add another / back to collection / back to pages

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/v2-hub#1923]
**Is your feature request related to a problem? Please describe.**
When I'm editing an entry and I go to the save button, I then need to go to the menu on the left to go back and publish a new entry

**Describe the solution you'd like**
In the `Save` dropdown, I'd like an option to `Save and add another` which would bring up another edit screen for an entry/page as well as, `Save and back to pages` or `Save and back to collection` depending on the current page/entry context.

**Comment by jackmcdade** [comment]
Was added several releases back 😎

**Comment by 1stevengrant** [comment]
![](https://media.giphy.com/media/l41m4C4WVwYFNFbd6/giphy.gif)
