### ISSUE TITLE
Non-unicode filenames causing RuntimeException

### ISSUE THREAD

**Issue by eapo** [statamic/v2-hub#1926]
**Describe the bug**
`php please` responds with 
```
[RuntimeException]
  SplFileInfo::getType(): Lstat failed for C:\xampp\htdocs/site/users\·ußΘlkasd.yaml
```
in case of non-unicode usernames, and because in some cases we prefer to allow non-unicode usernames (default in statamic v2) better to extend the file creation method.

**To Reproduce**
1. Go to '/register' with default `login_type: username` setting
2. Click on 'Register' after providing non-unicode username
3. Run `php please`

**Expected behavior**
Have no unicode filenames created

**Screenshots**
![image](https://user-images.githubusercontent.com/4000929/40314396-4a48d7de-5d10-11e8-8b32-fa01eea92d9b.png)

**Environment details (please complete the following information):**
 - Statamic Version 2.8.12
 - Fresh Install
 - OS: Windows
 - Web Server: Apache
 - PHP Version: [eg. 7.2]

**Comment by jasonvarga** [comment]
Thanks. Obvioulsly the workaround for now is to _not_ use unicode characters.

**Comment by jcohlmeyer** [comment]
This may be similar to this issue? https://github.com/statamic/v2-hub/issues/1813

**Comment by jasonvarga** [comment]
Seems fine actually. Maybe its Windows specific? In any case, I'm closing this. Feel free to reopen if this is absolutely a showstopper.
