### ISSUE TITLE
'statamic update` didn't run housekeeping tasks

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1928]
**Describe the bug**
I ran `statamic update` on a 2.8.11 site and the 2.9 specific housekeeping tasks did not run.

**To Reproduce**
1. have a 2.8.11 site
2. `statamic update`

**Expected behavior**
2.9 specific housekeeping tasks were run.

**Environment details (please complete the following information):**
 - 2.8.11
 - Upgrade
 - OS: [e.g. macOS 10.12.6, Ubuntu 16.04]

**Comment by jasonvarga** [comment]
Fixed for 2.9.1.

Since it fixes the updater, it will only appear fixed when upgrading _from_ 2.9.1.

This fixes both `php please update` and `statamic update` (the latter just calls the former)
