### ISSUE TITLE
Not able to create entries in collections with date-sorting 

### ISSUE THREAD

**Issue by Figedi** [statamic/v2-hub#1929]
**Describe the bug**
Since the update to statamic 2.9.0, I cannot create entries in collections which are sorted by date
**To Reproduce**
1. Create a collection with date sorting
2. Create an entry in that collection and click publish
3. Validation error occurs

**Expected behavior**
In 2.8.12 the behaviour did not occur. As a user, I want to be able to create entries with dates.

**Environment details (please complete the following information):**
 - Statamic Version 2.9.0
 - Upgrade
 - OS: Ubuntu 16.04
 - Browser: Chrome
 - Web Server: Nginx
 - PHP Version: 7.0
 - Addons installed:

**Additional context**
Upon further inspection, the sidebars content in the http-payload seems to be partly missing)
- a date-time in extra
- slug is null (although set)

**Comment by beckysoll** [comment]
Having the same issue here, happy to provide more info if needed.

**Comment by jasonvarga** [comment]
No need for more reports. We're on it. Thanks peeps 👍

**Comment by jasonvarga** [comment]
Fixed for next release. Will probably be tomorrow!
