### ISSUE TITLE
Redwood .tiles .item display: flex;

### ISSUE THREAD

**Issue by eapo** [statamic/v2-hub#1931]
**Describe the bug**
`themes\redwood\css\redwood.css` have an unnecessary and really annoying _(spent an hour to debug)_ `display: flex; display: -ms-flexbox;` property for `.tiles .item` and even for `.tiles .item .image`.

Because of this every `.tiles .item` is working as [CSS Flexbox (Flexible Box)](https://www.w3schools.com/csS/css3_flexbox.asp) and all of the children have flexible property. This is unnecessary, because the `.tiles` already have the `display: flex; display: -ms-flexbox;` property, and just this need to be a `flex-container`.

**To Reproduce**
1. Add more elements inside the `.item` in the `themes\redwood\templates\things.html`
2. Go to ˙/things˙ and
4. See the problem

**Screenshots**
![image](https://user-images.githubusercontent.com/4000929/40333484-93764834-5d50-11e8-8f16-f04e5c42089c.png)

**Environment details (please complete the following information):**
 - Statamic Version 2.8.12
 - Fresh Install
 - OS: Windows
 - Web Server: Apache
 - PHP Version: [eg. 7.2]

**Comment by jackmcdade** [comment]
They need flex to vertically align the caption overlay on hover. if you want to add extra content and change the layout, you're more than welcome to customize the CSS to your needs!
