### ISSUE TITLE
After login_type: email error: "username field is required"

### ISSUE THREAD

**Issue by eapo** [statamic/v2-hub#1932]
**Describe the bug**
> The username field is required.
after setting `login_type: email` and changing the login form as follows
`<input type="text" name="email" value="{{ old:email }}" class="form-control" />`

**To Reproduce**
1. Change `login_type: email`
2. Change `<input type="text" name="username" value="{{ old:username }}" class="form-control" />` to `<input type="text" name="email" value="{{ old:email }}" class="form-control" />` in template's `/login.html`
3. And `/login` with email

**Environment details (please complete the following information):**
 - Statamic Version 2.9
 - Fresh Install
 - OS: Windows
 - Web Server: Apache
 - PHP Version: [eg. 7.2]

**Comment by eapo** [comment]
`<input type="text" name="username" value="{{ old:email }}" class="form-control" />` solved the problem, but feels like a **workaround**.

**Comment by jasonvarga** [comment]
If you change the login type, you don't even have to change the login form. Just leave it as username. The email is now your username.

**Comment by eapo** [comment]
Yes, but because at least need to change the `<label>` to _Email_ not obvious to don't change these to. And no documentation about it. Looks a small thing, but i lost a lot f time because of it.
