### ISSUE TITLE
2.9.X Asset field gets stuck loading when included via a partial fieldset.

### ISSUE THREAD

**Issue by benfurfie** [statamic/v2-hub#1936]
**Describe the bug**
The asset field gets stuck loading when included via a partial fieldset.

**To Reproduce**
1. Create a fieldset.
2. Create an assets field.
4. Save it.
5. Create a new fieldset.
6. Include that first fieldset into the new one as a partial field.
7. Create a new page with that fieldset.
8. You should see the field name appear, with the ajax gif below it.

**Expected behavior**
It should return an upload box.

**Screenshots**
![assets_bug](https://user-images.githubusercontent.com/10786699/40356806-1c5135ae-5db2-11e8-8a8e-b82a954af4d4.png)

**Environment details (please complete the following information):**
 - Statamic Version [e.g. 2.9.1]
 - Fresh Install and Upgrade:
 - OS: MacOS 10.13.4
 - Browser: Chrome, Firefox, Safari
 - Web Server: Valet
 - PHP Version: 7.1
 - Addons installed: None

**Comment by bgarrant** [comment]
Great. Keep me posted.

**Comment by efoken** [comment]
@jackmcdade Any solution in sight? 😈

**Comment by bgarrant** [comment]
We need this fix badly. 5 client sites experiencing it when using asset field in Bard

**Comment by benfurfie** [comment]
Can you not downgrade until it's fixed @bgarrant?

**Comment by bgarrant** [comment]
I just went back to 2.8.12 for now yes.

**Comment by jasonvarga** [comment]
We are working on it.
I believe you can workaround it by not using a partial. Just copy/paste your fields into the appropriate places.

**Comment by bgarrant** [comment]
That is exactly what I did on a site. Thx. 

Bryan Garrant
