### ISSUE TITLE
Field titles do not show on grids

### ISSUE THREAD

**Issue by TeriyakiBomb** [statamic/v2-hub#1939]
**Describe the bug**
When editing a fieldset in 2.9.1 Field titles and handles do not show on grid fields. It only shows the field type.

**To Reproduce**
1. Go to a fieldset
2. Click on the arrow on a grid to expose the fields

**Expected behavior**
To see the Field title and handle displayed in the same way as it's parent

**Screenshots**
![screen shot 2018-05-22 at 11 22 03](https://user-images.githubusercontent.com/12913978/40365931-bf665d1c-5dcd-11e8-889f-d80326009c42.png)

**Environment details:**
 - Statamic  2.9.1
 - Upgrade
 - OS: macOS
 - Browser: safari
 - Web Server: Nginx

**Comment by jackmcdade** [comment]
Confirmed. Working on it.

**Comment by jackmcdade** [comment]
Fixed. Will be in the next update!
