### ISSUE TITLE
Embed Statamic more in Redactor

### ISSUE THREAD

**Issue by steveooo9** [statamic/v2-hub#1942]
**Is your feature request related to a problem? Please describe.**
When inserting a link into Redactor, there isn't a way to select links of pages or collections that exist in Statamic. Also if some URL changes, these link references aren't updated and we get dead links.

**Describe the solution you'd like**
Hook into the Redactor logic to get Statamic's asset browser when trying to insert a image and add some link browser to simply add pages to Redactor's "Insert link". See Craft CMS how they make make Redactor things more Statamic-like by embedding some Statamic logic to Redacotr.

**Comment by jackmcdade** [comment]
You already can hook into the Asset browser by setting the `container` id on the field's settings.

![image](https://user-images.githubusercontent.com/44739/40431388-56084828-5e75-11e8-8e73-0baa16815f36.png)


![image](https://user-images.githubusercontent.com/44739/40431357-4473ffa8-5e75-11e8-8fa6-43f9b40daae2.png)

As for the hardcoded page/collection link, that's a global feature we want to tackle but has pretty large implications (feature request here: #1039) . As that would not be unique to Redactor, I'll close this issue. Thanks!
