### ISSUE TITLE
Swapping between username and email-login with php please convert:email-login deletes all users

### ISSUE THREAD

**Issue by danfascia** [statamic/v2-hub#1944]
**Describe the bug**
When I try to switch between using a username and an email address as login identity `php please convert:email-login` deletes all users .yaml files.

**Expected behavior**
Should swap between username and email account login mode without any destructive changes and should still show full fieldset in control panel

**Environment details (please complete the following information):**
 - Statamic Version 2.9.1
 - Fresh Install
 - OS: OSX
 - Browser: Chrome
 - Web Server: Valet
 - PHP Version: 7.2
 - Addons installed: Charge, Workshop, VideoEmbed

**Comment by jasonvarga** [comment]
Works fine here. Can you give any more details? What was the output in your terminal when you ran the command?

**Comment by danfascia** [comment]
<img width="491" alt="users -bash 109x36 2018-05-22 19-52-17" src="https://user-images.githubusercontent.com/8407708/40383806-a7ed8986-5df9-11e8-8fb8-e2590df6cf48.png">

There is a demo with only 1 user which it just wipes, as shown by the lack of result on the `ls` commands

**Comment by jasonvarga** [comment]
What was the file's filename and contents before it got deleted?

**Comment by danfascia** [comment]
email@address.com.yaml

It contained the dataset corresponding to the basic user.yaml fieldset and each field contained something.

**Comment by jasonvarga** [comment]
Before it got deleted the filename was already an email address?

**Comment by danfascia** [comment]
Yes

**Comment by jasonvarga** [comment]
Why are you running the command then?

**Comment by danfascia** [comment]
I ran it because I thought it might sort out my missing fields in the control panel when I was working in email-login mode, and instead it deleted all my users.

I appreciate (now) that the intended behaviour is a one-time conversion of usernames > email addresses but it's a pretty bad behaviour for it to remove all users without warning regardless.

**Comment by jasonvarga** [comment]
Fixed for next release.
