### ISSUE TITLE
Swapping to email-login mode stops using the user fieldset

### ISSUE THREAD

**Issue by danfascia** [statamic/v2-hub#1945]
**Describe the bug**
When I swap to email-login mode using either the control panel setting or `php please convert:email-login` the user.yaml fieldset no longer displays any fields in the edit user control panel.

**To Reproduce**
1. Fresh install
2. Start off in default username mode
3. Change to email-login using either settings or `php please convert:email-login`
4. Try to edit a user in the control panel, all other fields will be missing

**Expected behavior**
Email should be used in lieu of the username but all other fields should remain untouched and should remain editable and visible in the user edit area of the control panel

**Environment details (please complete the following information):**
 - Statamic Version 2.9.1
 - Fresh Install
 - OS: OSX
 - Browser: Chrome
 - Web Server: Valet
 - PHP Version: 7.2
 - Addons installed: Charge, VideoEmbed, Workshop

**Comment by jasonvarga** [comment]
Whatever is affecting your previous issue #1944 will likely be the solution to this one.

**Comment by jasonvarga** [comment]
It was unrelated, my apologies. Fixed for next release.
