### ISSUE TITLE
The title and slug of taxonomies are not localizable anymore

### ISSUE THREAD

**Issue by eddiesigner** [statamic/v2-hub#1946]
**Describe the bug**
My website supports english and spanish, being english the default language, before to upgrade to the version 2.9.0 from 2.8.12 I was able to translate the title and slug of taxonomies from the control panel but now I can't because the dropdown to select the language is missing, it appears only for collections and pages.

I know there are [some notes about it on the documentation](https://docs.statamic.com/taxonomies#localization) but that was done automatically before, doing it by hand is not a suitable solution at least in my case because I don't manage the content (a non-programmer person does that) and of course they calling me every time to add a new taxonomy term is not a good situation.

**To Reproduce**
1. Go to 'Taxonomies'.
2. Click on some taxonomy.
3. Create a new term.

**Expected behavior**
I would expect to see the language dropdown to choose the language and then be able to add the title and slug using that locale.

**Screenshots**
I am able to choose a language on collections and pages:
![screenshot-2018-5-22 nuevo producto statamic](https://user-images.githubusercontent.com/1477503/40387612-8839e418-5e0d-11e8-89b0-f787220c5c1c.png)

But it doesn't work for taxonomies:
![screenshot-2018-5-22 crear un nuevo categoria statamic](https://user-images.githubusercontent.com/1477503/40387644-99a871e2-5e0d-11e8-8c61-5ef08e134c6f.png)

**Environment details (please complete the following information):**
 - Statamic Version 2,9.1 (I updated the version hoping for a fix)
 - Fresh Install or Upgrade: Upgrade
 - OS: macOS High Sierra 10.13.4
 - Browser: Firefox Quantum
 - Web Server: Apache
 - PHP Version: 7.1.10
 - Addons installed: None

**Additional context**
I hope you guys can help me since the website is for a store and the taxonomies in both languages are a main part of the project, thanks in advance! 👍🏼

**Comment by FrittenKeeZ** [comment]
I can confirm this bug.
