### ISSUE TITLE
Make relatives urls default

### ISSUE THREAD

**Issue by steveooo9** [statamic/v2-hub#1947]
**Describe the solution you'd like**
Well, in the docs is say's that it would be good to use `/` instead of `mydomain.com/` as URLs because when changing domains, you don't have an issue.

On the installer when you add a locale and a URL for that ("Settings"), on default, you have `mydomain.com/` instead of `/`.

Also, are there other places I don't know where such absolute vs. relative URL/path thing exists and where I have to look out for?

**Comment by jasonvarga** [comment]
You can still use `/` if you want. Go for it!

Most of the time when there are URLs being manipulated, we'll use what you've defined in system.yaml.

If something requires an absolute URL but you've only defined a relative one, we'll do our best to infer it from the request. However, when you've got fancy things like load balancers set up, sometimes it ends up with the wrong URL. It's best to define the actual URL yourself in these cases.

So, relative is fine, but absolute will sort out some edge cases.
