### ISSUE TITLE
Revert comment block headline cosmetics in `sample.htaccess`?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#1949]
No biggie, but in {{S}} 2.9.2 `sample.htaccess` it seems all the comment block headlines are now in Title/Mixed case, e.g., `Static Caching Proxy` below:
```
# ------------------------------------------------------------------------------
# Static Caching Proxy
#
# Enable these rules when using static html caching
# to bypass Statamic when a given URL has a cached copy.
# ------------------------------------------------------------------------------
```
Compare the above with ye olde way, below, where it was an upper-case headline:
```
# ------------------------------------------------------------------------------
# STATIC CACHING PROXY
#
# Enable these rules when using static html caching
# to bypass Statamic when a given URL has a cached copy.
# ------------------------------------------------------------------------------
```
YMMV, but I find it a lot easier to visually scan down through the comments when the block headlines are in ALL UPPER CASE (SIC), and stood out better from the rest of the text, like ye olde way.

**Comment by jasonvarga** [comment]
We didn't like our htaccess files shouting at us.

Feel free to manually add shouting to yours. 😱
