### ISSUE TITLE
Two Meta tab on content edit page after custom field added

### ISSUE THREAD

**Issue by eapo** [statamic/v2-hub#1950]
**Describe the bug**
On https://laravel.dev/cp/fieldsets/post new _tab_ with Section Name/Handle: _Meta_ is handled properly, on https://laravel.dev/cp/collections/entries/blog/blogpost.. doesn't

**To Reproduce**
1. On https://laravel.dev/cp/fieldsets/post new _tab_ added with the Section Name/Handle: _Meta_
2. New _field_ added
3. https://laravel.dev/cp/collections/entries/blog/blogpost.. have two _Meta_ tab

**Expected behavior**
Have the new field on the basic _Meta_ tab

**Screenshots**
![chrome legacy window 22may2018 230827](https://user-images.githubusercontent.com/4000929/40393272-a525dfc4-5e16-11e8-833a-75ba8735ce89.jpg)
![chrome legacy window 22may2018 230943](https://user-images.githubusercontent.com/4000929/40393286-b21b4980-5e16-11e8-9203-51859acf8f0c.jpg)

Statamic Version 2.9.1
OS: Windows
Web Server: Apache
PHP Version: 7.1

**Comment by jasonvarga** [comment]
Call it `sidebar` instead of meta.
