### ISSUE TITLE
FR: Label of the field type "Collection" could be clickable

### ISSUE THREAD

**Issue by FR6** [statamic/v2-hub#1952]
**Is your feature request related to a problem? Please describe.**
Going to the collection require multiple clicks and remembering the collection name.

**Describe the solution you'd like**
The label could be clickable to go directly to the collection listing (with a target blank).

**Additional context**
![image](https://user-images.githubusercontent.com/286685/40398087-2743ff94-5e04-11e8-88eb-8dc7332a28ec.png)

**Comment by jasonvarga** [comment]
You can add links to your field instructions.

``` yaml
instructions: '<a href="/cp/collections/entries/blog" target="_blank">Go to blog</a>'
```
