### ISSUE TITLE
Username gone from Edit Profile after login_type set "email"

### ISSUE THREAD

**Issue by eapo** [statamic/v2-hub#1953]
**Describe the bug**
On the `/cp/fieldsets/user` page `username` field still exist after `login_type: email`, but not on `/cp/users/e@permaculture.hu`

**To Reproduce**
1. Set `login_type: email`
2. Go to `/cp/fieldsets/user` 
3. and `/cp/users/registered@member`
4. See the difference

**Expected behavior**
Because we still need the username field on  the side, better to have it on profile by default.

**Screenshots**
![chrome legacy window 23may2018 54434](https://user-images.githubusercontent.com/4000929/40403868-92d0c164-5e4c-11e8-9eb6-c0c73825ef78.jpg)
<sup title=".field-width-selector > .field-width-label {\n    font-size: 2.2em;\n    font-weight: bold;\n    text-indent: -2em;\n	display: none;\n}\n.field-width-selector:hover > .field-width-label {\n	display: block;\n}">yes, there is a `helpers/cp/override.css` hack ;)</sup>
![chrome legacy window 23may2018 54141](https://user-images.githubusercontent.com/4000929/40404217-89022c7a-5e4e-11e8-8873-3b98b146d1c8.jpg)

**Environment details (please complete the following information):**
Statamic Version 2.9.2
OS: Windows
Web Server: Apache
PHP Version: eg. 7.1

**Comment by jasonvarga** [comment]
The `username` field gets explicitly removed from the publish page if you have login type set to email. That's intended. Just don't add a username field to your fieldset.
