### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by fbuka** [statamic/v2-hub#1955]
**Describe the bug**
Creating a Bard fieldype from control panel causes error rendering the page edit mode associated with the fieldset.

To get rid of the error I had to delete remove the setting` sets: null` which seems to be causing the error.

But this prevents me editing fieldsets in the control panel as saving it will re-add the `sets: null` to a bard fieldtype that has no sets

**To Reproduce**
1. Go to 'control panel fieldset'
2. Edit a 'fieldset that has a bard fieldtype without  sets'
3. Save 
4. In the control panel go to the page using the fieldtype

<img width="1000" alt="screen shot 2018-05-23 at 08 51 25" src="https://user-images.githubusercontent.com/33101172/40410809-8be5e3f6-5e66-11e8-914d-3ef99cbd79b0.png">

**Environment details **
 - Statamic Version [e.g. 2.9.2]
 - Upgrade:
 - macOS 10.12.6
 - PHP Version: 7.1

**Comment by steveallinson** [comment]
Just come across this after latest upgrade (2.9.2). When adding a Bard fieldtype to a fieldset there is no option in the settings dialogue to actually add sets. This results in `sets:null` being saved and the above exception.

Manually adding the sets to the fielset yaml via your code editor is the only way around this right now.

**Comment by fbuka** [comment]
@steveallinson 

Is `sets` mandatory in order to use Bard fieldtype? I wanted to use to as not many of my users know markdown and prefer to set specific buttons that relate to the content.

For your problem, you can add sets ford bard by hovering over the right side.
You will have options to add sets  **+**  icon 

![bard](https://user-images.githubusercontent.com/33101172/40413448-bf8e583a-5e6d-11e8-80ae-d53e18b05552.png)

**Comment by steveallinson** [comment]
@fbuka 

Thanks you're absolutely right. I didn't even notice the extra controls - very nice. Although there doesn't seem to be a way to remove sets once added (unless I'm missing something again!).

In answer to your query, yes I'm pretty sure I've used Bard fields with no `sets` previously so it appears that this is a bug in the latest version unfortunately.

**Comment by fbuka** [comment]
Hover over the `set`  you want to remove and in same location as the bard there's an `X` icon to remove

**Comment by steveallinson** [comment]
@fbuka

I can see an `x` icon to remove a single field from a set, plus an `x` icon to remove the entire Bard field, but no way to actually remove a set. If I remove all the fields from a set I'm left with an empty set showing the set name and 'instructions...', but no actual way to remove it. TBH it's not a huge issue as I can just remove it from the yaml, but appears to be a minor user experience bug more than anything.

I've not tried it on a fresh install so maybe it's just my setup. Thanks for your help anyway.

**Comment by fbuka** [comment]
@jasonvarga  @jackmcdade any help regarding this issue, pointing me to the right direction would be great

**Comment by jasonvarga** [comment]
For now, just manually remove `sets: null`. We'll look into these issues, thanks.

**Comment by fbuka** [comment]
ok thanks for now, will use this method
