### ISSUE TITLE
Please add title to Editing Formset page

### ISSUE THREAD

**Issue by beckysoll** [statamic/v2-hub#1959]
**Is your feature request related to a problem? Please describe.**
This is hardly dire straits, but it gets confusing when you have a bunch of cp tabs open.. currently all that shows up is '| Statamic'

**Describe the solution you'd like**
`Editing: Contact Form | Statamic` would work well or `Formset: Contact Form | Statamic` or even just `Contact Form` would be helpful

**Describe alternatives you've considered**
Learning my lesson and not having 8500 tabs open

**Comment by jasonvarga** [comment]
With only 8499 tabs, this is fine, right?
