### ISSUE TITLE
Better name site/helpers/cp/*

### ISSUE THREAD

**Issue by steveooo9** [statamic/v2-hub#1960]
**Is your feature request related to a problem? Please describe.**
The problem is my OCD. I am sorry.
The issue is that there is a `overwrite.css` and a `scripts.js`. This naming doesn't really match.

**Describe the solution you'd like**
2 ideas:
1. Use `overwrite.css` and `overwrite.js`
2. Use `styles.css` and `scripts.js`

I prefer 1st because 2nd is redundant. The file extension says what it is ("*scripts* dot Java*Script*")

**Describe alternatives you've considered**
Go to see a doctor to make my OCD less painful.

**Would you be willing to sponsor this feature?**
I rather would not.

**Comment by jasonvarga** [comment]
If we change that then we have to have everyone either change their filenames, or support having multiple filenames, which it extra maintenance for no real benefit.

If you want to add a css file named something else, use the [cp.add_to_head](https://docs.statamic.com/addons/events#cpaddtohead) event and inject it manually.

**Comment by steveooo9** [comment]
@jasonvarga Ok. Maybe an option for v3?
