### ISSUE TITLE
Blocking cookies prevents CP login

### ISSUE THREAD

**Issue by jamiedumont** [statamic/v2-hub#1961]
**Describe the bug**
Not so much a "bug", more a "behaviour-that-might-become-a-bug-one-day". At present, using a browser that is blocking cookies (using Safari, but I believe Firefox allows the same) stops a user being able to log in to the control panel but repeatedly reloading the login page, sometimes with a "Session expired" error.

There's talk of browsers blocking cookies by default in the future (and potentially being required by law to do so), and some people are already opting in to it. 

**To Reproduce**
1.  Block cookies (In Safari: Preferences > Privacy > check "Block all cookies"
2. Try logging in to the control panel

**Expected behavior**
Obviously cookies are required for login at present, that's fine. Perhaps a more explicit error message might help people work out what's going on. GitHub for example presents a "You need cookies enabled to log in to GitHub" message instead of a generic error.

**Environment details (please complete the following information):**
 - Statamic Version: 2.9.2

**Happy for you guys to delete/archive/ignore/whatever this as I know it's not a pressing issue. Though I'd bring it to your attention all the same.**

**Comment by jackmcdade** [comment]
At this time, cookies are required for essential functionality.
