### ISSUE TITLE
Saving fieldset in CP that uses a Bard field without 'sets' causes error

### ISSUE THREAD

**Issue by jamiedumont** [statamic/v2-hub#1962]
**Describe the bug**
When a Bard field is configured without sets, the collection and fieldset can be loaded in the Control Panel. However, when the fieldset is saved, the CP adds `sets: null` to the field, which causes the error on the fieldset config page, and in the any collections using the fieldset.

**To Reproduce**
1. Create a fieldset that uses a Bard field, without any sets defined using the editor.
2. Create a collection using that fieldset
3. At this stage, everything should work.
4. Now open the fieldset config in the CP. Change nothing and save it. The fieldset in your editor should now have `sets: null` added.
5. Reloading the fieldset config, or adding an entry to the associated collection causes a "foreach()" error.

**Expected behavior**
The CP save doesn't add `sets: null` to the fieldset.

**Environment details (please complete the following information):**
 - Statamic Version: 2.9.2
 - Upgrade:
 - OS: macOS 10.13.4
 - Browser: Safari
 - Web Server: Valet
 - PHP Version: 7.1
 - Addons installed: Charge, Spock, PowerTools

**Comment by Krzemo** [comment]
adding `sets: null` manually doesnt fix it. Adding `sets: []` does.

**Comment by edalzell** [comment]
I think this is fixed in the recent version, 2.9.4
