### ISSUE TITLE
Better entry ordering and dates

### ISSUE THREAD

**Issue by TeriyakiBomb** [statamic/v2-hub#1963]
So currently when you save an entry in collection if the collections *folder.yaml* has `'order: date` statamic prepends the entry name with a date string. This works kinda fine but I'd love to see entry date and time stored directly in the entry, rather than the file name. 

The same goes for  entry order. It'd be nice to be in a world where you didn't have to choose between the two. Plus switching once you have content causes issues.

You could have dated entries, displayed in the CP in a set order and entry names are more human readable.

**Comment by jasonvarga** [comment]
Having the dates in the filename makes them ordered correctly in the filesystem.

You could leave the collection as alphabetical and then just manually add a date field.
