### ISSUE TITLE
Entries with an accented first letter not ordered alphabetically

### ISSUE THREAD

**Issue by binoclard** [statamic/v2-hub#1964]
**Describe the bug**
If an Entry title begins with an accented letter (happens in French…), it is not ordered correctly alphabetically, neither in the CP list, nor via templating.

**To Reproduce**
1. Create an Entry with an accented first letter
2. Save
3. Try to find your Entry 
4. Note that it is not where it should be

**Expected behavior**
Entries should imho be ordered alphabetically, regardless of diacritics.

**Comment by jasonvarga** [comment]
Which character are you using?

**Comment by binoclard** [comment]
I noticed the problem with the word "Équitation", so É (I would think the most used accented first letter in French).

**Comment by jackmcdade** [comment]
What version of Statamic are you running? I can't recreate this.

![image](https://user-images.githubusercontent.com/44739/40922280-d2097d3e-67df-11e8-8bef-a0fdf6d96366.png)

**Comment by binoclard** [comment]
Yeah, sorry, I should have been more accurate. :-/
I suppose it was 2.9.2.

Meanwhile, I ditched the accent and moved on. 

I have just tried in 2.9.6, and the word _Équitation_, with either capital or lower-case accented É/é, is pushed at the bottom of the list, but _Equitation_ without accent is not.

<img width="273" alt="capture d ecran 2018-06-04 a 17 19 34" src="https://user-images.githubusercontent.com/31567381/40926464-90d82440-681c-11e8-8a7e-887bfda274a8.png">
<img width="333" alt="capture d ecran 2018-06-04 a 17 20 09" src="https://user-images.githubusercontent.com/31567381/40926466-90f52a5e-681c-11e8-9202-ee5a01eb1adb.png">
<img width="323" alt="capture d ecran 2018-06-04 a 17 20 27" src="https://user-images.githubusercontent.com/31567381/40926467-91126466-681c-11e8-935e-38587c8be615.png">

**Comment by jasonvarga** [comment]
Can you try to install the Intl PHP extension?

**Comment by binoclard** [comment]
I'll go and do some reading about that, and try, and let you know ^__^

**Comment by binoclard** [comment]
So… the Intl installation was a bit chaotic/epic/tragic, but thanks to @emd I have a working computer again… and the accent problem is gone indeed.

**Comment by jackmcdade** [comment]
😅 

Anything we could have done on our end to make it less tragic?

**Comment by binoclard** [comment]
Nope. Apparently something was broken with brew/php/valet; the solution was to uninstall-reinstall Valet, but instead I lost myself in esoteric procedures way out of my league. All my fault. And Valet's ;-)

**Comment by binoclard** [comment]
But you really should hire @emd, though ^__^

**Comment by jackmcdade** [comment]
Can't afford him 😂lol

**Comment by edalzell** [comment]
Wrong handle...it's @edalzell.

And yes, I'm too expensive.
