### ISSUE TITLE
Workshop doesn't provide validation errors when editing an existing entry

### ISSUE THREAD

**Issue by mpavey0** [statamic/v2-hub#1969]
**Describe the bug**
In the browser, when I submit a form to edit an existing entry, if there are validation errors, my changes are correctly not persisted. However, `{{ errors }}` is empty, so I can't show the user what went wrong.

**To Reproduce**
**Setup**

0. Install Workshop
1. Create a collection e.g. `ideas` with a fieldset `ideas`
2. Assign some validation rules e.g. `title` is `required`
3. Create a route to edit an entry e.g. `/ideas/{slug}/edit`
4. Assign a template to that route e.g. `ideas/edit`
5. In the template, use the Workshop tag to create the edit form:
```html
{{ workshop:entry:edit collection="ideas" url="/ideas/{slug}" }}
    {{ partial:ideas/edit }}
{{ /workshop:entry:edit }}
```

6. In the partial, output: i) a loop displaying the contents of `{{ error }}` (cf. example below), and ii) an HTML form with the existing entry values prepopulated.

```html
{{ if errors }}
	<div class="error-head">
		<ul>
			{{ errors }}
			<li>{{ value }}</li>
			{{ /errors }}
		</ul>
	</div>
{{ /if }}
```

**Testing**
1. Create an idea e.g. slug `new-idea`
2. Go to the edit idea screen, e.g. visit `/ideas/new-idea/edit`
3. Change the form so that the input fails validation — for example, delete the title
4. Click Submit

**Expected behavior**
System should display errors at top of screen, because the `errors` variable is an array containing relevant error messages (and the template includes a section to display them).

**Screenshots**
N/A

**Environment details (please complete the following information):**
 - Statamic Version 2.9.2
 - Fresh Install or Upgrade: upgrade (originally 2.8.12)
 - OS: macOS 10.13.4
 - Browser: Firefox
 - Web Server: Valet
 - PHP Version: 7.2
 - Addons installed: Workshop, custom add-ons

**Additional context**
Errors are correctly displayed when using Workshop to create an entry.

This may conceivably be related to #1142.

**Comment by jasonvarga** [comment]
Hi Michael.

Can you please show your partial? You are talking about errors not working but have not shown how you are using it.

**Comment by mpavey0** [comment]
Of course, here's the relevant section (I'll edit the original message to include it too):
```html
{{ if errors }}
	<div class="error-head">
		<ul>
			{{ errors }}
			<li>{{ value }}</li>
			{{ /errors }}
		</ul>
	</div>
{{ /if }}
```

**Comment by jasonvarga** [comment]
Also, try changing line 241 of WorkshopController.php to `return back()->withInput()->withErrors($validator, 'workshop');`

**Comment by mpavey0** [comment]
That seems to work. Thanks!
