### ISSUE TITLE
2.9.3: minor UI glitch with Safari 11.1 in Fieldset builder

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#1971]
**Describe the bug**
When hovering slowly off and on the 2 buttons (Add a Field and Quick Add) located at the bottom of the screen, a black rectangle appears shortly under the buttons.

Sometimes, the rectangle appears as coming from the left side of the screen and then goes to the top...weird.

![fieldsetbuilder](https://user-images.githubusercontent.com/1823359/40567725-e35833c0-6076-11e8-9a95-e885684f6a61.gif)

![fieldsetbuilder2](https://user-images.githubusercontent.com/1823359/40567726-e4f543f8-6076-11e8-9251-e8be68c9f124.gif)

**To Reproduce**
Go to the fieldset builder (i.e. Kitchen fieldset) using Safari Desktop 11.1

**Expected behavior**
Just as nice as Chrome!

**Environment details (please complete the following information):**
 - Statamic Version 2.9.3
 - Safari 11.1
- Mac OS X 12.6

**Comment by jackmcdade** [comment]
I tried to recreate this for an amount of time that would have looked like I lost my marbles, had someone been looking over my shoulder. For the life of me... no idea how that's happening to you. If you or anyone else has more information leading to the identification and elimination of this oddity, please let me know!

**Comment by ebeauchamps** [comment]
no problem, it's minor (I am on a 2011 iMac, so perhaps a performance problem with the latest Safari)
