### ISSUE TITLE
Image Focus doesn't go to where mouse is clicked

### ISSUE THREAD

**Issue by TomS-** [statamic/v2-hub#1976]
**Describe the bug**
On Chrome, I haven't tested any other browsers. When setting the focus point on an image, the alignment circle does not match where you've clicked. I've found the further to the right or bottom you click, the bigger the distance.

**To Reproduce**
1. Create an assets field
2. Select an image
3. Click to set the focus point
4. Notice that it does not align with where you clicked
5. Click further to the right to see it have even less accuracy. 

**Expected behavior**
The center of the focus point should be where you clicked.

**Environment details (please complete the following information):**
 - Statamic Version 2.9.4

**Comment by jasonvarga** [comment]
Works fine in Chrome for me. Can you give any more details? Does it do it for all images?

**Comment by TomS-** [comment]
Might be worth mentioning that the images are inside replicators. That may have something to do with it.

**Comment by TomS-** [comment]
The issue is with portrait images. Portrait images are not accurate when setting focus point.

**Comment by TomS-** [comment]
The width of the image needs to be smaller than 330px - I resize the images to exact size before uploading not to fill up the server.

**Comment by jackmcdade** [comment]
Ah, there it is. It's the width.
