### ISSUE TITLE
  [ErrorException]  Undefined index: en  after updating from 2.8.12 to 2.9.4

### ISSUE THREAD

**Issue by beeldr** [statamic/v2-hub#1978]
**Describe the bug**
Any "PHP please" command produces the following error after updating from 2.8.12 to 2.9.4:

```
php please update:housekeeping
                       
  [ErrorException]     
  Undefined index: en
```

I have this issue on alle sites I've upgraded lately, all my websites are on "nl" locale, as well in the index.php as in the system yaml file

**To Reproduce**
update from 2.8.12 to 2.9.4

**Expected behavior**
No error messages. 

**Environment details (please complete the following information):**
 - Statamic Version [e.g. 2.9.4]
 - Upgrade: from 2.8.12
 - OS: [e.g. macOS 10.13.4, and Plesk ONYX 17.8.11 on centos 7]
 - Browser: chrome
 - Web Server: apache 
 - PHP Version: 7.1.18
 - Addons installed: Seo , Apage

**Log file error**
[2018-05-29 12:39:16] production.ERROR: ErrorException: Undefined index: en in /var/www/vhosts/website.com/httpdocs/statamic/core/Providers/AppServiceProvider.php:174
Stack trace:
#0 /var/www/vhosts/website.com/httpdocs/statamic/core/Providers/AppServiceProvider.php(174): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/vhosts...', 174, Array)
#1 /var/www/vhosts/website.com/httpdocs/statamic/core/Providers/AppServiceProvider.php(31): Statamic\Providers\AppServiceProvider->forceRootUrl()
#2 [internal function]: Statamic\Providers\AppServiceProvider->boot()
#3 /var/www/vhosts/website.com/httpdocs/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#4 /var/www/vhosts/website.com/httpdocs/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#5 /var/www/vhosts/website.com/httpdocs/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(Statamic\Providers\AppServiceProvider))
#6 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Statamic\Providers\AppServiceProvider), 14)
#7 /var/www/vhosts/website.com/httpdocs/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure))
#8 /var/www/vhosts/website.com/httpdocs/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#9 /var/www/vhosts/website.com/httpdocs/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Statamic\Application))
#10 /var/www/vhosts/website.com/httpdocs/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(208): Illuminate\Foundation\Application->bootstrapWith(Array)
#11 /var/www/vhosts/website.com/httpdocs/statamic/core/Console/Kernel.php(75): Illuminate\Foundation\Console\Kernel->bootstrap()
#12 /var/www/vhosts/website.com/httpdocs/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Statamic\Console\Kernel->bootstrap()
#13 /var/www/vhosts/website.com/httpdocs/please(48): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}  

**System yaml**
```
locales:
  nl:
    full: nl_NL
    name: Nederlands
    url: https://website.com
timezone: UTC
date_format: F jS, Y
default_extension: md
filesystems:
  content:
    driver: local
    root: site/content
  storage:
    driver: local
    root: site/storage
  users:
    driver: local
    root: site/users
  themes:
    driver: local
    root: site/themes
    url: /site/themes
```

**Comment by jasonvarga** [comment]
Change `$locale = 'en'` to `'nl'` inside `please`.

(In the future, please surround stack traces in code blocks)
