### ISSUE TITLE
Configure->Fieldsets: Editing sets with replicator and custom fieldtypes not possible anymore

### ISSUE THREAD

**Issue by krausste** [statamic/v2-hub#1979]
**Describe the bug**
When choosing a custom (own addons) replicator fieldtype it is not possible anymore to configure the sets via the fieldset configurator.

**To Reproduce**
1. Go to Configure->Fieldsets
2. Edit an existing fieldset or create a new one
3. Click on 'Add New Field'
4. Select a custom replicator fieldtype (definition would be to have 'sets' within meta.yaml->fieldtype_fields)

**Expected behavior**
'Toggle Sets' button should be available and the sets can be configured.

**Screenshots**
![screen shot 2018-05-29 at 14 18 10](https://user-images.githubusercontent.com/5039360/40658330-3c930f88-634b-11e8-91e5-4e3f093c720e.png)

**Environment details (please complete the following information):**
 - Statamic Version [e.g. 2.9.4]
 - Addons installed: Using our own addon

**Additional context**
fieldset-builder/Sections/Field.vue
From my understanding the computed property 'isReplicatorField' should check against 'sets' being available.
```
isReplicatorField() {
    return ['replicator', 'bard'].includes(this.field.type);
}, 
```

**Comment by jackmcdade** [comment]
Are you saying you have your own custom/modified version of `Replicator`, or using your custom fieldtypes _inside_ a regular Replicator field?

**Comment by krausste** [comment]
Hi Jack, yes we kind of have a custom fieldtype version of Bard.
So, the Sets would need to be configured inside this custom Bard fieldtype.
But I could also imagine other custom fieldtypes working with sets. So, it might make sence anyway to check against a sets being a part of a fieldtype.
Thank you!

**Comment by jackmcdade** [comment]
This issue has been inactive and in need of more information for a while now. Feel free to reopen and we'd be more than happy to take another look if you have more info that can help!
