### ISSUE TITLE
Datepicker should default to date format from CP settings

### ISSUE THREAD

**Issue by goellner** [statamic/v2-hub#1980]
**Is your feature request related to a problem? Please describe.**
The date fieldtype has a predefined date format and can't be localized .

**Describe the solution you'd like**
Use same date format as `cp.yaml`or `system.yaml`. Not sure which one is the right one 🤣

**Comment by jasonvarga** [comment]
You can add `format: whatever` to your field if you need it a particular format.
https://docs.statamic.com/fieldtypes/date#settings

**Comment by goellner** [comment]
I was referring to the displayed value in the cp. The datepicker field always displays in its predefined format, but it could be the same setting as in `cp.yaml`.
