### ISSUE TITLE
Workshop treats checkbox inputs with multiple values as a single value

### ISSUE THREAD

**Issue by mpavey0** [statamic/v2-hub#1982]
**Describe the bug**
Workshop appears not to be equipped to handle checkbox fields with multiple values. Consider this HTML:
```html
<input name="choice" value="first">
<input name="choice" value="second">
<input name="choice" value="third">
<input name="choice" value="fourth">
```

 In particular:
1. A validation rule `between:1,3`, designed to ensure at least one value and no more than three are selected, is triggered when two values are selected
2. The `old` variable contains just a single string for `choice`, instead of an array with all selected values.

**To Reproduce**
1. Send to the browser a form containing the HTML snippet above
2. Select two options, `first` and `third`
3. Click Submit

System displays the default error message for `between`:
> The fields.track must be between 1 and 3 characters.

`old['track']` is a string containing the value `third`.

**Expected behavior**
- `old['track']` to be an array with values `first` and `third`
- No validation error message displayed when two boxes are checked.

**Screenshots**
N/A

**Environment details (please complete the following information):**
 - Statamic Version 2.9.2
 - Fresh Install or Upgrade: upgrade from 2.8.12
 - OS: macOS 10.13.4
 - Browser: Safari
 - Web Server: Valet
 - PHP Version: 7.2
 - Addons installed: Workshop, custom add-ons

**Additional context**
In the backend this field type works fine, including the validation.

**Comment by jasonvarga** [comment]
You should be using `name="choice[]"` with brackets in order to submit an array.

**Comment by mpavey0** [comment]
Aha! Thanks @jasonvarga, that works. Perhaps this could be referenced in the Workshop documentation? (I do seem to remember it being mentioned somewhere in the general Statamic documentation.) I was following the [spec on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox).

**Comment by jasonvarga** [comment]
Added a troubleshooting section to the docs.
