### ISSUE TITLE
Collection:next doesn't work with locales

### ISSUE THREAD

**Issue by louis-schandeler** [statamic/v2-hub#1983]
**Describe the bug**
I use the tag collection:next in my website but when i switch the language of my website, the collection:next displays the default locale content and not the translated language.

**To Reproduce**
```
{{ collection:next in="event" as="posts" limit="1" wrap="true" sort="event_date:desc" }}
{{ posts }}
{{ partial:card-next }}
{{ /posts }}
{{ /collection:next }}
```

**Comment by jasonvarga** [comment]
Fixed for next release.

You can patch this in `statamic/bundles/Collection/CollectionTags.php` at line 630.
Change to:

```
$this->collection = Entry::whereCollection($collection)->localize($this->get('locale', site_locale()))->values();
```

**Comment by louis-schandeler** [comment]
Thank you Jason. 

But I find an other problem. I always have the first entry of the collection. Do you have a fast trick to resolve this ?

Thanks in advance

**Comment by louis-schandeler** [comment]
Because the language prefix (/fr, /it, ...) was missing and the foreach defining the current index wasn't working.
