### ISSUE TITLE
Give option of prefill for fieldsets

### ISSUE THREAD

**Issue by steveooo9** [statamic/v2-hub#1985]
**Is your feature request related to a problem? Please describe.**
It's related to a problem: Some of our clients oftentimes aren't really in to building content and setting a lot of options. So having the option of prefilling content ("use a template") would be an option for our clients to not add stuff (oftentimes complicated) but more replace content.

**Describe the solution you'd like**
So we thought of having a way to have different "prefills/templates" (terminology is debatable) for 1 fieldset. We would create some prefills so for our clients following workflow is there:

1. Client wants to create a new entry
2. Selects fieldset and then a prefill for this fieldset
3. Entry opens with some text and things prefilled (e.g. we would add things like "TODO: Insert beautiful poem here")
4. Our client just replaces these prefilled text snippets and they are good to go.

**Describe alternatives you've considered**
Nothing right now. Maybe some ideas, @jackmcdade ?

This feature would mean that even the most technically-foreign clients could add content. Oftentimes when we have some layout in an older CMS of us, client's wouldn't even know what a "column" is and why you can set 6/12 as width. Even that these are some complex things, with this feature, it would be usable and you could create similar content very fast.

**Comment by jackmcdade** [comment]
I wouldn't want to support this as a native/core feature. I nominate this as Addon material, and if any hooks/events are necessary to facilitate it, we will oblige the best we can.

**Comment by steveooo9** [comment]
@jackmcdade Ok. Seems reasonable... I will give my best 👍

**Comment by edalzell** [comment]
For this to work in an addon @jackmcdade we'd need an event like the fieldtype `preProcess` I think. Maybe `EntryPreProcess`? It would receive the fieldset being created and maybe the content type or content slug? Like `type` is Page and `fieldset` is foo?

Neat idea though

**Comment by jasonvarga** [comment]
Cant you just give your fields default values?

```
fields:
  something:
    type: text
    default: Replace me.
```

**Comment by steveooo9** [comment]
I would need some default values for replicator and such. Don't know if this is the best way.
