### ISSUE TITLE
Is this a bug? start_time: 'aN:00'

### ISSUE THREAD

**Issue by steveooo9** [statamic/v2-hub#1986]
In some entries, I have a Date field that has `start_time: 'aN:00'`. I don't understand the `aN` part. Is this a bug or is it intented this way?

**Comment by jasonvarga** [comment]
How did it get there?  Do you use git? Maybe you can see when it was introduced.

**Comment by steveooo9** [comment]
Sorry, I didn't had Git installed at this time. (Is just a test project), but it came from 2.9.2 and I upgraded to 2.9.4

**Comment by jasonvarga** [comment]
If you save an entry that uses one of those fields, does it consistently save it that way?

**Comment by jackmcdade** [comment]
This issue has been inactive and in need of more information for a while now. Feel free to reopen and we'd be more than happy to take another look if you have more info that can help!
