### ISSUE TITLE
New conditionals: is_email and is_url

### ISSUE THREAD

**Issue by chris-79** [statamic/v2-hub#1988]
**Is your feature request related to a problem? Please describe.**
It's pretty annoying to always create a new regex to determine if a string is an email address or is a URL. The Macros feature doesn't offer this as a shortcut, either

**Describe the solution you'd like**
It'd be _sUpEr AwEsOmE_ if the conditionals `is_email` and `is_url` would be able to do the job

**Describe alternatives you've considered**
Tried using Macros, to no avail

**Additional context**
Reference for Email regex:  [emailregex.com](https://emailregex.com)

Example usage in a template:

```handlebars
{{ if (registration_method | is_email) }}
  <a href="mailto:{{ registration_method }}">
    Register via Email
  </a>
{{ elseif (registration_method | is_url) }}
  <a href="{{ registration_method }}">
    Open Registration Form
  </a>
{{ /if }}
```

**Would you be willing to sponsor this feature?**
Couldn't do it from my personal budget

**Comment by jasonvarga** [comment]
`php please make:modifiers-helper` and add these:

```
    public function isEmail($value)
    {
        return filter_var($value, FILTER_VALIDATE_EMAIL) !== false;
    }

    public function isUrl($value)
    {
        return filter_var($value, FILTER_VALIDATE_URL) !== false;
    }
```

However, they're so simple I've added them to the next release anyway.

**Comment by chris-79** [comment]
**_AWESOME!!_**  Your Rock, bro!
