### ISSUE TITLE
minor glitch with Safari 11.1 in the fieldset builder

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#1990]
**Describe the bug**
Visiting the HOME fieldset for the Redwood theme, and especially the content field. Then clicking on the Extras tab. Look on the right side

![capture d ecran 2018-05-31 21 52 31](https://user-images.githubusercontent.com/1823359/40805009-3c76c30e-651d-11e8-8083-63cb2a3e48b6.png)

**Environment details (please complete the following information):**
 - Statamic Version 2.9.5
 - Fresh Install or Upgrade: fresh
 
 - Browser: Safari 11.1

**Comment by ebeauchamps** [comment]
oups sorry about the title update...

**Comment by jackmcdade** [comment]
Do you have OSX's "Always show scrollbar" feature enabled? If so, I don't think there's much I can do to fix this on the CSS side.

![image](https://user-images.githubusercontent.com/44739/40851657-211161ea-6596-11e8-82a7-68e09df5f138.png)

**Comment by jackmcdade** [comment]
Closing as I cannot recreate it without the OSX setting, and cannot fix it with. 🤷‍♂️

**Comment by ebeauchamps** [comment]
Hello Jack. No I don't: this setting is set to "Automatically based on mouse or trackpad"
