### ISSUE TITLE
2.9.5: English key displayed even though it is translated? (fieldset builder)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#1991]
**Describe the bug**
In the fieldset builder, when editing a field that has the Extras tab (i.e. a content markdown field), the following keys are displayed in English though they are included in my localized cp.php file:
Restrict to Folder
Prevent navigation to other asset folders or containers.

![capture d ecran 2018-05-31 21 59 02](https://user-images.githubusercontent.com/1823359/40805218-dc7129b2-651d-11e8-8fcb-f0a48161a6f9.png)

**Expected behavior**
Keys are displayed in my locale

**Environment details (please complete the following information):**
 - Statamic Version 2.9.5
 - Fresh Install or Upgrade: fresh

**Comment by ebeauchamps** [comment]
FWIW these 2 strings are translated for some field types (assets...), and not for 2 other field types:
  - markdown
  - redactor

**Comment by jasonvarga** [comment]
Do you have them translated for each fieldtype? Its the same keys and values but in different files.

**Comment by ebeauchamps** [comment]
Sorry, this hasn't been corrected at all with 2.9.6 for both markdown and redactor field type

**Comment by jasonvarga** [comment]
Do you have `fr/fieldtypes/markdown.php` with a `restrict_assets` value?

**Comment by ebeauchamps** [comment]
ok Jason, getting it.....I am slow. Thanks for directing me to the right direction.

**Comment by ebeauchamps** [comment]
OK: differences between the English files and the French ones => correcting right now (I still had the old keys without the "assets" part)
