### ISSUE TITLE
V3 custom URLs 

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/v2-hub#1992]
I have site right now in another CMS where the urls, regardless of the page hierarchy are only 1 level deep.

This makes it super easy for advertising and easy for publishers to create new pages with short urls without having to dig into redirects etc.

I would love to have that option within Statamic whereby the URL structure can be set by the entry type.

My aim is to move this site to Statamic by the end of year and I could go the vanity URL approach in the meantime but having that out of the gate would be sweet.

**Comment by jasonvarga** [comment]
How does this differ from an entry?

**Comment by 1stevengrant** [comment]
It doesn't really, like you could obviously have everything sitting at the root level but visually, for the publisher, it's easier for them to see that, for example `Team` `Careers` are sub pages of `About` even if their urls aren't `/about/team` or `/about/careers`

This is the site I'm talking about

https://harvestglasgow.org/

`About` and `Connect` both have the tree structure within the control panel and still able to use the native CMS tags as well.

I guess that would be the other hindrance right now is that navigation would need to be built up as a global or something, rather than automatically.

**Comment by jasonvarga** [comment]
Gotcha. 👍
