### ISSUE TITLE
Updating from the CP: "cannot delete the statamic folder" - install failed

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#1996]
**Describe the bug**
I have been getting this behavior since 2.9.1:
I cannot upgrade from within the CP
I always get the same error message
Files are downloaded and unzipped

My current statamic folder has 777 permissions
![capture d ecran 2018-06-01 23 16 44](https://user-images.githubusercontent.com/1823359/40863925-f664a810-65f1-11e8-98f2-78ad08766bec.png)

The unzipped statamic folder has peculiar permissions and I cannot change them (I am on Mamp)
![capture d ecran 2018-06-01 23 16 59](https://user-images.githubusercontent.com/1823359/40863927-f8582642-65f1-11e8-9af8-9933b1a2d037.png)

**Environment details (please complete the following information):**
 - Statamic Version 2.9.5 => 2.9.6
 - Fresh Install or Upgrade: upgrade
 - OS: 10.12.6
 - Browser: both
 - Web Server: Apache
 - PHP Version: 7.1.8 mamp
 - Addons installed: Powertools

**Additional context**
same since 2.9.1

**Comment by ebeauchamps** [comment]
Yes it exists with a full Statamic folder and editable permissions. Although I cannot try again because I fiddled with my install and with php please in order to manually update to 2.9.6.  However I can try with a base install of 2.8.12 and then upgrade to 2.9.x gradually?

**Comment by ebeauchamps** [comment]
I am running MAMP servers as UNIX users. If I run them under my user account I don't get anything (blank screens everywhere). This has been my basic setup for years.

**Comment by jasonvarga** [comment]
Does going from 2.8.11 to 2.8.12 work?

**Comment by ebeauchamps** [comment]
hum..I can do a 2.7.1 => 2.8.12 upgrade

**Comment by ebeauchamps** [comment]
No dice. Probably a problem in MAMP......I don't understand

**Comment by jasonvarga** [comment]
So 2.7.1 to 2.8.12 didn't work either?

**Comment by ebeauchamps** [comment]
no.....

**Comment by jasonvarga** [comment]
Then it's not a problem with 2.9

Try to delete everything in `local/temp` and make sure its 777.

**Comment by ebeauchamps** [comment]
ok last try

**Comment by ebeauchamps** [comment]
ah...TEMP is not created with the right permissions

**Comment by jasonvarga** [comment]
Right, I suggested to delete everything _in_ temp, but not the directory itself.

**Comment by ebeauchamps** [comment]
No way. I put back a TEMP folder with 777 permissions and with "me" as the Owner, but all 3 subfolders have "_www" as the owner and I get the same message (upgrading from 2.71 to 2.8.12). I don't want to kill your time. I will try to re-install MAMP

**Comment by jasonvarga** [comment]
Sounds like something to do with your MAMP setup. I'm going to close this, but let us know how you go.

**Comment by ebeauchamps** [comment]
All set up. Something in my MAMP setup probably. I upgraded from 2.7.1 to 2.8.12 and then to 2.9.6 in a breeze. Thanks for your valuable time!
