### ISSUE TITLE
contact form not getting through errors field

### ISSUE THREAD

**Issue by 4kets** [statamic/v2-hub#1997]
**Describe the bug**
I have a contact field with an errors block. In the errors block there is a variable for the user to rewrite the error message:

`{{ if {form:errors} }}
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
             <span aria-hidden="true">&times;</span>
         </button>
         {{ error_message }}
    </div>
{{ /if }}`

But when i don't fill in the form and press submit its reloaded and i dont get the errors block
here is the full start of my form:set

```
{{ form:set formset="contact" }}
    {{ if {form:errors} }}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ error_message }}
         </div>
     {{ /if }}
     {{ if {form:success} }}
          <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
               </button>
                {{ success_message }}
            </div>
     {{ /if }}
    {{ form:create redirect="/contact#bedankt" error_redirect="/contact#bedankt" }}
         form
    {{ /form:create }}
{{ /form:set }}
```

I have also tried it with the first version but no luck either

```
{{ form:create redirect="/contact#bedankt" error_redirect="/contact#bedankt" }}
    {{ if errors }}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ error_message }}
         </div>
     {{ /if }}
     {{ if success }}
          <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
               </button>
                {{ success_message }}
            </div>
     {{ /if }}
     form
{{ /form:create }}
```

**Environment details (please complete the following information):**
 - Statamic Version [e.g. 2.8.12] 2.9.6
 - Fresh Install or Upgrade: upgrade now but when we started on this project it was a fresh install
 - OS: [e.g. macOS 10.12.6, Ubuntu 16.04] windows 10
 - Browser: [e.g. chrome, safari] chrome
 - Web Server: [eg. Apache, Nginx, Valet] windows server
 - PHP Version: [eg. 7.1] php 7.1.9
 - Addons installed:
Cachemanager

**Comment by jackmcdade** [comment]
Do you have validation rules that would trigger an error? E.g. Required, etc. If so, can you share your formset so we can see if the issue is on our end vs yours?

**Comment by 4kets** [comment]
I found out that it was a server issue that we now have fixed thanks anyway

**Comment by jasonvarga** [comment]
Thanks for letting us know!
