### ISSUE TITLE
Taxonomy name prepended when assigning to an article

### ISSUE THREAD

**Issue by rgruyters** [statamic/v2-hub#2000]
**Describe the bug**
When editing an article and want to assign an existing tag to it, it will prepend the taxonomy name to the tag.

**To Reproduce**
Steps to reproduce the behavior in standard installation of Statamic 2.9.6:
1. Go to CP
2. Click on Collections
3. Click on Blogs
4. Open an article
5. Open tab META
6. Under Tags assign an existing tag
7. Save
8. Go to Tags
9. The assigned tag is renamed and has the words "tags/" in front of it

**Expected behavior**
Expected behaviour should be that behind the existing tag the count should be increased. 

**Screenshots**
https://robin.grtrs.nl/s/dc8G3QmKPKWWWs2

**Environment details (please complete the following information):**
 - Statamic Version 2.9.6
 - Fresh Install or Upgrade: Fresh Install
 - OS: macOS 10.13.4
 - Browser: Firefox and Safari
 - Web Server: Valet in dev and NGINX in production
 - PHP Version: 7.0.x
 - Addons installed: None

**Additional context**
I have downgraded as far to version 2.9.3 and the issue isn't there. Issue started since version 2.9.4.

**Comment by jasonvarga** [comment]
@rgruyters Confirmed, thanks!
