### ISSUE TITLE
Add An Option to make Fields Hidden in Control Panel

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#2002]
The new fieldset editor is amazing.  It would be great if we could make a field greyed (hidden) in the CP.  The  reason would be if you make a lot of site like I do, you could easily copy one site to another and disable/enabled fields as needed.  We already have everything needed to add this option to the Visibility tab.

![screen shot 2018-06-04 at 11 37 47 am](https://user-images.githubusercontent.com/2436728/40927164-0b259fa6-67ec-11e8-9a22-92dc355c5e9a.png)

All we need is one more option in the dropdown for `Always Hide`.

**Comment by jasonvarga** [comment]
Thanks for the feature request!

Two things:

- Please use the feature request issue template. Don't just clear it out and go rogue.
- Are you wanting to hide a field that you need in the data, or do you just want to get rid of it? You say that you want to enable/disable fields.

**Comment by bgarrant** [comment]
Just want to toggle some on and off for certain sites, but they would still show in the CP, but maybe look a bit diff just so you can tell what ones are hidden

**Comment by jasonvarga** [comment]
What would toggling off do? What's the purpose of having a field if you don't want to do anything with it?

**Comment by bgarrant** [comment]
so if this site did not need Social Media yet, I could set the Visibility to `hidden` and then turn it back on later if needed.  It would maybe just fade out the field a bit or something

![screen shot 2018-06-04 at 11 48 21 am](https://user-images.githubusercontent.com/2436728/40927658-45c075b8-67ed-11e8-9886-3c990acfc388.png)

**Comment by bgarrant** [comment]
Or maybe on right side have an icon for `hidden` or something.  Just any way really to know it is hidden would be fine

**Comment by jasonvarga** [comment]
Can't you just add the fields when they _are_ needed? You say you are copying from site to site. Just copy it when the time is right.

Or put them in their own fieldset that you don't ever reference, and bring them in as a partial when you need them?

**Comment by bgarrant** [comment]
I can surely do that yes,.  I just thought the `hidden` option in the CP would be handy for non-YAML confident devs as you could do in through the CP when needed.  I have a site now that may or may not use Google Analytics for example.  Just saves recreating fields later I guess or having to touch the YAML for new users.  It was just an idea really. Not a big deal

**Comment by jasonvarga** [comment]
A new user (or a user that doesn't touch YAML files) would not be copying fieldsets from other sites since the only way to do that would be to touch YAML files.

I've heard people request hidden fields, but those would still actually save data, they'd just be visually hidden.

What you're requesting sounds more like "unneeded fields". I think I'm going to respectfully say no thanks to this, in favor of [the partial suggestion above](https://github.com/statamic/v2-hub/issues/2002#issuecomment-394405023), or simply commenting out fields in YAML, but I appreciate the feedback.

**Comment by bgarrant** [comment]
Sounds good.  "Unneeded fields' is a better term yes.  It was just an idea based on my needs and something another dev was looking for who clones a lot of sites.  No worries.  I do not mind the YAML myself.
