### ISSUE TITLE
Grid Fieldtype keeps displaying as a Set (not Table) in other sections than `main`

### ISSUE THREAD

**Issue by efoken** [statamic/v2-hub#2003]
**Describe the bug**
The Grid fieldtype always displays as a "Set" if used in other sections than the `main` section. Regardless of which Display Mode I select in the Fieldtype Extras – "Table" or "Set", it keeps displaying as "Set".

**To Reproduce**
1. Create a fieldset with two sections `main` and `options`.
2. Create some fields
3. Create a Grid fieldtype in the `options` section with Display Mode "Table"
4. Create a page with your fieldset and go to options Tab

**Expected behavior**
The selected Display Mode should be respected in my `options` section.

**Environment details (please complete the following information):**
 - Statamic Version 2.9.6
 - Fresh Install or Upgrade: Updated
 - OS: macOS
 - Browser: Chrome
 - Web Server: Valet
 - PHP Version: 7.2.6

**Screenshots**
<img width="1048" alt="bildschirmfoto 2018-06-05 um 11 18 18" src="https://user-images.githubusercontent.com/522446/40966982-3ce52bda-68b2-11e8-9db7-5a68667c2102.png">

**Comment by jasonvarga** [comment]
It turns into the stacked mode when the parent element's width is narrow enough regardless of what mode you select.
Although, your screenshot shows that its wider than I would have thought would trigger the change.

Does it change if you resize your browser width?

**Comment by efoken** [comment]
My browser windows is exactly 1280px wide. And when I drag the `metadata` over to the `main` section – it works as expected.

But you're right, if I change my window size, just 1px smaller **or** larger, it swaps to Table display mode.

**Comment by jasonvarga** [comment]
Cool, thanks for the info!
