### ISSUE TITLE
Taxonomy field is empty when editing entry.

### ISSUE THREAD

**Issue by philipboomy** [statamic/v2-hub#2011]
**Describe the bug**
The taxonomy tag disappear after save of entry. If you edit the entry and check the sidebar/meta tab the taxonomy is gone. It is showing in the entry.md file though.

tags:
  - tagname

**To Reproduce**
1. Create entry, enter a taxonomy and click save
2. Edit the same entry and go to sidebar/meta tab and see that taxonomy field is empty.

**Expected behavior**
That the field would contain the tag

**Screenshots**
https://cl.ly/2v3C1i3U1f0U

**Environment details (please complete the following information):**
 - Statamic Version: 2.9.7
 - Upgrade from 2.9.6
 - macOS 10.12.6
 - Browser: Firefox
 - Web Server: Valet
 - PHP Version: 7.2
 - Addons installed: None

**Additional context**
I mentioned it here #2000 thinking it was related to same problem since it was working when the prepend was happening.

**Comment by jackmcdade** [comment]
Confirmed. Working on a fix.

**Comment by jasonvarga** [comment]
You can fix this temporarily by changing line 19 of `statamic/core/Data/Processor.php` to 
```
$this->fieldtypes = collect($fieldset->withTaxonomies()->fieldtypes())->keyBy(function ($fieldtype) {
```
