### ISSUE TITLE
Bug: Markdown Cheatsheet icon

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#2012]
**Describe the bug**
Appears that the Markdown Cheatsheet svg icon is not being masked or styled correctly.

**Screenshots**
<img width="279" alt="screenshot 2018-06-09 15 26 14" src="https://user-images.githubusercontent.com/414211/41195353-96eaf6a6-6bf9-11e8-83a7-9957298b4fad.png">

**Environment details (please complete the following information):**
 - Statamic Version 2.9.8

**Comment by jackmcdade** [comment]
Hmm, I can't recreate this in Chrome, Safari, or Firefox, as a standalone field, or in a Replicator (which it looks like here). Try clearing your browser cache and seeing if it goes away?
