### ISSUE TITLE
Possible Bug: Grid Table display mode appears stacked in Replicator

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#2013]
**Describe the bug**
Some of my Grids that used Table mode are now appearing stacked. Is this the expected behaviour or is it a bug?

**Screenshots**
Before update:
<img width="833" alt="screenshot 2018-06-09 15 35 42" src="https://user-images.githubusercontent.com/414211/41195413-31fee4a8-6bfb-11e8-83dc-5aa694b1447b.png">

<img width="814" alt="screenshot 2018-06-09 15 44 46" src="https://user-images.githubusercontent.com/414211/41195488-2313b83c-6bfc-11e8-9a70-d0a97c5e13aa.png">

After 2.9.8 update:
<img width="820" alt="screenshot 2018-06-09 15 35 29" src="https://user-images.githubusercontent.com/414211/41195415-3d40bd1e-6bfb-11e8-8bcb-31fb6fbbfe97.png">
<img width="823" alt="screenshot 2018-06-09 15 45 00" src="https://user-images.githubusercontent.com/414211/41195490-2996827a-6bfc-11e8-963e-15ac5437ea57.png">

**Environment details (please complete the following information):**
 - Statamic Version 2.9.8

**Comment by mikemartin** [comment]
Appears related to #2003 and #2010. Just noticed that on load (with browser 1440px wide) the grid field appears stacked, but when I resize the window the table view appears and works as expected.

**Comment by krausste** [comment]
I can confirm this issue.
But there is another important step to reproduce this issue. The affected set needs to be collapsed before page load.

**Comment by mikemartin** [comment]
I just upgraded to 2.10.4 and it seems like this issue has returned. The table mode grid inside a replicator appears in stack mode initially, but on window resize it switches back to table mode.

The initial window size is 1440px.

<img width="1552" alt="screenshot 2018-09-12 15 29 37" src="https://user-images.githubusercontent.com/414211/45404044-b7d4cf80-b6a0-11e8-9cef-a061fcf5e95d.png">

**Comment by edalzell** [comment]
What mode do you have set in the fieldset?
