### ISSUE TITLE
Question: Is taxonomy migration required after 2.9 update?

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#2014]
I'm still trying to understand the recent changes to how taxonomies are added to fieldsets. Personally, I really liked the old way of quickly toggling taxonomies on/off for each of my collection fieldsets. It seems that after upgrading to 2.9, those taxonomy settings are not maintained and we've been left with a situation where we must manually update our fieldsets so the desired taxonomies appear for my collection entries. Below I've posted a fieldset example **before** the update, **after** the update/housekeeping and the **manual updates** required to get the expected result.

Can you confirm if this is the intended migration path? Should I expect to do this for all of my collection fieldsets when upgrading to 2.9? Should we consider adding some of these manual changes to housekeeping to make the upgrade easier?

Thanks for your help guys!

----

**2.8.10 Blog Post Fieldset**
Tags taxonomy appears in sidebar. Class taxonomy is not shown.

https://gist.github.com/mikemartin/d5ac9194bea365e9030d0952d94b7618.

**After 2.9.8 upgrade and housekeeping**
After the update, my Tags taxonomy which is used by **events** and **blog posts** is moved to the bottom of fieldset, and is no longer shown in the sidebar. Also, my **Class** taxonomy appears for all collection entries when it is only intended for Users. 

https://gist.github.com/mikemartin/c9ce505b97a6cbb4a918b17b8ae030d8

**Manual Migration**
In order to move my Tags taxonomy into the sidebar and hide the Class taxonomy, it seems that I have to migrate my fieldset to use a `main` and `sidebar` section.

https://gist.github.com/mikemartin/46034b968e0f3ad97d36c8e2dfd12a28

**Comment by jackmcdade** [comment]
The migration isn't required, it should still work without doing it. Just run `php please update:housekeeping` to adjust those fieldsets if you want.
