### ISSUE TITLE
Login form not showing on IE and Firefox <= V50  in version 2.9.8

### ISSUE THREAD

**Issue by manogi** [statamic/v2-hub#2015]
**Describe the bug**
When navigating to /cp on IE 11, the login form does not load, it stays an empty white rectangle.

**To Reproduce**
Go to /cp in an new, empty installation of statamic (happened to me in all my installations, thought, does not have to be empty or new).

**Expected behavior**
The Login form should appear.

**Screenshots**

![image](https://user-images.githubusercontent.com/1419634/41229782-92b27264-6d7d-11e8-96e3-78d4cb01bddf.png)

**Environment details (please complete the following information):**
 - Statamic Version: 2.9.8
 - Fresh Install or Upgrade: Both
 - OS: Windows 10
 - Browser: IE 11
 - Web Server: nginx on ubuntu, also on valet and nginx
 - PHP Version: 7.2
 - Addons installed: none

**Additional context**
I testet on Browserstack because my client had the problem on his IE.

**Comment by manogi** [comment]
Some more information:
I had to downgrade to 2.8.12 to make the bug go away, so it seems to have been introduced in 2.9.0

And: I hate IE - I'd have no problems with you just putting up a sign "Does not work with obsolete browsers like IE" on the login form instead of fixing the bug ;-)

**Comment by lukeagsmith** [comment]
I've just had a client report the login page not working in IE too.

NB Title of this needs changing from "now" to "not"

**Comment by jackmcdade** [comment]
The Statamic CP doesn't officially support IE. We'll be adding a "Try Google Chrome" message on this one and moving on. My apologies for that being more clear.

**Comment by lukeagsmith** [comment]
Oh, wow, I didn't know that. That's a big thing for some of our education and corporate clients.

Does that include Edge as well?

**Comment by manogi** [comment]
I would like to add that Firefox 50 and below have the same Problem (see Screenshot from Browserstack including Error Console):

![image](https://user-images.githubusercontent.com/1419634/41404462-937648d2-6fc7-11e8-8d78-7303fac49e41.png)

**Comment by jackmcdade** [comment]
We only support Evergreen Browser versions, so I'll be closing this down.
