### ISSUE TITLE
Error when creating first entry in a collection ordered by number

### ISSUE THREAD

**Issue by nathobson** [statamic/v2-hub#2019]
**Describe the bug**
When creating a new collection, ordered by number, creating the first entry through the control panel throws an error `Call to a member function order() on null /home/vagrant/statamic/base/statamic/core/CP/Publish/EntryPublisher.php#166z`

**To Reproduce**
1. Go to Content -> Collections -> Create Collection within the CP
2. Fill out collection details but ensure Select Order is set to Number
3. Go to Collections -> New Collection Name -> Create Entry
4. Add a title and publish
5. See error

**Expected behavior**
The first entry is created successfully

**Screenshot**
![screen shot 2018-06-14 at 10 49 47](https://user-images.githubusercontent.com/6664210/41405278-532db64e-6fc1-11e8-83c1-e2a1ffc77179.png) 

**Environment details (please complete the following information):**
 - Statamic Version 2.9.8
 - Recently upgraded
 - OS: macOS 10.13.4
 - Browser: Chrome
 - Web Server: Nginx
 - PHP Version: 7.2
 - Addons installed: None

**Additional context**
If the first entry is created by manually saving a .md file with a filename such as `1.test.md`, subsequent entries save as expected through the CP.

**Comment by jackmcdade** [comment]
Nice catch. Fixed for next release.

**Comment by wotta** [comment]
Nice catch I also encountered this ( thought it was an error in a package ).
So decided to fix it in the code, only to see that is was core code.

Glad you guys caught it real quick 👍
