### ISSUE TITLE
Reference to .env var in system.yaml for use_https doesn't obey false setting

### ISSUE THREAD

**Issue by Krzemo** [statamic/v2-hub#2021]
**Description**
site/settings/system.yaml doesn't allow to make use_https: .env dependant. It seems like when using {env:USE_HTTPS} reference it checks if there is anything set with empty() more then ===true.
What is strange is that it works ok (stops forcing https) when use_https: false is literally set in system.yaml but it fails to stop forcing HTTPS when use_https: {env:USE_HTTPS} and in .env USE_HTTPS=false.

**To Reproduce**
1. Go to .env
2. Add USE_HTTPS=false
3. Go to site/settings/system.yaml
4. Add use_https: {env:USE_HTTPS}
5. Go to /cp

All link in left side menu are HTTPSed.

**Expected behavior**
I would expect to be able to set use_https: per .env

**Environment details (please complete the following information):**
 - Statamic Version 2.9.8
 - Upgrade:
 - macOS 10.13.5
 - Brower: not applicable
 - Web Server: Nginx (through brew)
 - PHP Version: 7.2.4
 - Addons installed: MobileDetect, Spock

**Comment by jasonvarga** [comment]
In `statamic/core/API/Parse.php` just before line 90, add this:

```
        if ($val === $matches[0]) {
            return env($matches[1]);
        }
```

Does that fix your issue?

**Comment by Krzemo** [comment]
Im afraid it doesnt...
<img width="441" alt="obraz" src="https://user-images.githubusercontent.com/1293123/41484240-5b3cf2f2-70dc-11e8-801e-f60c9564a9f0.png">

<img width="475" alt="obraz" src="https://user-images.githubusercontent.com/1293123/41484255-6bb78246-70dc-11e8-8e31-1ecc7cc49a31.png">

<img width="678" alt="obraz" src="https://user-images.githubusercontent.com/1293123/41484276-7adcfd28-70dc-11e8-92f6-f91b2191e962.png">

<img width="503" alt="obraz" src="https://user-images.githubusercontent.com/1293123/41484303-9b5c0c6a-70dc-11e8-9214-cd89dacb7246.png">

**Comment by jasonvarga** [comment]
You need to wrap your env in quotes otherwise it is technically a YAML array.

`use_https: '{env:USE_HTTPS}'`

**Comment by Krzemo** [comment]
Tx! My bad.

**Comment by jasonvarga** [comment]
(Leave this open for now, we'll close it when we ship the fixed code) 👍

**Comment by Krzemo** [comment]
im afraid there is no issue there - i made myself an a..
on the other hand strong typed check is always a good idea...

**Comment by jasonvarga** [comment]
I think there was an issue. Before you added the snippet of code I sent, `use_https` would be evaluated as `"1"` instead of `true`

**Comment by Krzemo** [comment]
AFAIK there is "not much" diff between 1 and true in PHP - thus my strong typing comment ...

**Comment by jasonvarga** [comment]
Ah sure. Before the change, `true` would be "1"` and `false` would be `""`.
Depending on the situation they would probably work fine.

This change would just make things more explicit.

Anyway, fixed (or improved?) for next release.
