### ISSUE TITLE
Assets uploaded inside folder are duplicated

### ISSUE THREAD

**Issue by RomainFrancony** [statamic/v2-hub#2029]
**Describe the bug**
Assets uploaded inside folder is being duplicated

**To Reproduce**
1. Go to a content with an Assets field (ex: Gallery page on fresh install)
2. Click on 'Browse assets' on the assets field
3. Create a new directory (you will now be inside the created folder)
4. Upload a new file with drag and drop (not with the upload button)
5. Your file is uploaded inside the created folder as expected
6. Go back to the container root folder and see the file also present here

**Expected behavior**
File should not be duplicated when uploaded to a folder

**Environment details**
 - Statamic Version 2.9.8
 - Fresh Install
 - OS: macOS 10.12.6
 - Browser: chrome, safari
 - Web Server: Apache
 - PHP Version: 7.1.12
 - Addons installed: none

**Additional context**
Uploading the file with the 'Upload' button works as expected.
Uploading a file via the 'Assets' page ('Upload' button and 'drag and drop') works as expected

**Comment by JesseLeite** [comment]
Hmm, can't reproduce 🤔  What am I doing wrong?

![screen capture on 2018-06-26 at 17-23-11](https://user-images.githubusercontent.com/5187394/41940193-f67da0e0-7965-11e8-8494-ab2a6a946e37.gif)

**Comment by RomainFrancony** [comment]
Well I don't known, I did the exact same thing and it got duplicated (sorry for the potato quality)

![Bug](https://user-images.githubusercontent.com/22396965/41992369-8a9469d4-7a48-11e8-86f6-cd2e2133a24d.gif)
