### ISSUE TITLE
Bug: taxonomies route returns a 404 for other languages if more than one taxonomy

### ISSUE THREAD

**Issue by ASochat** [statamic/v2-hub#2030]
**Describe the bug**
I have two languages (EN and FR) on my website and 3 taxonomies, with different tags in it
- dossiers-categories (rules, ...)
- tips-categories (advice, ...)
- blog-categories (people, ...)

Each tag is translated in FR, with a different slug, for example [Rules, /rules] -> [Réglementation, /reglementation] and [Advice, /advice] -> [Conseils, /conseils]
For each one, I set {slug} as the route URL, with a defined template, so for example both  /fr/reglementation and /fr/conseils should return a page contaning all the FR articles with the given tag, but instead, only the newest works whereas the other returns a 404. 
For example, if I change something for the tag "Advice", only /fr/conseils will work, and /fr/rules returns a 404

**To Reproduce**
1. Go to Taxonomies
2. If you already have 1 taxonomy (call it "foo1-tags"), Create another taxonomy 'foo2-tags'
3. Route to foo2-tags/{slug}
4. Create a new foo2 tag called 'foo2'
5. Go to french (or any other) locale and change the french slug of 'foo' for 'foo2-fr'
6. Try to reach the URLs "/fr/foo2-tags/foo2-fr" and "fr/foo1-tags/foo1-fr"

**Expected behavior**
Both URLs should work
The french URL "/fr/foo2-tags/foo2-fr" (the newest) works but the URL "/fr/foo1-tags/foo1-fr" (related to the first taxonomy) returns a 404.
Only the latest modified URL works in each case
All the english URL ("en/foo2-tags/foo2" and "en/foo1-tags/foo1") work fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/25055180/41603609-a227ea06-73dd-11e8-8fb9-3a89f2ebdf30.png)

**Environment details (please complete the following information):**
 - Statamic Version: 2.8.12
 - OS: macOS 10.13.4
 - Browser: chrome
 - Web Server: Nginx
 - PHP Version: 7.2

**Comment by wautersj** [comment]
The Statamic support is horrible... 
No responses on the github issues, and no responses on emails send through their contact form.

I confirm this nasty issue. It really needs a closer look.

**Comment by jasonvarga** [comment]
Sorry for the lack of communication here - this issue should be fixed in 2.11.15, please let us know.

**Comment by jackmcdade** [comment]
@wautersj I scoured our support inbox looking for an email from you but didn't see any. I want to make sure there isn't an issue somewhere, would you mind sending us a follow up in the same way you did before?

**Comment by wautersj** [comment]
I've done some testing, and I can confirm the problem isn't occurring anymore.
+1, this is very much appreciated, well done! 👍

**Comment by wautersj** [comment]
> @wautersj I scoured our support inbox looking for an email from you but didn't see any. I want to make sure there isn't an issue somewhere, would you mind sending us a follow up in the same way you did before?

I think I submitted my message at: https://statamic.com/support
