### ISSUE TITLE
Asset URLs have the site root twice

### ISSUE THREAD

**Issue by wratke** [statamic/v2-hub#2032]
I'm using Statamic in a folder (http://localhost/site_folder) and it's working well, but the URLs for all of the images (even the images that came with the initial installation) look like this: http://localhost/site_folder/site_folder/path/to/image.jpg. The thumbnails show up in the Asset section of of the control panel, but the images aren't displayed when I go to edit them.**Describe the bug**

I removed the code that adds the siteroot if the hosting is local from the absoluteUrl method in the Asset.php file and now it works for as expected. I haven't tested it in production yet.

**Comment by jasonvarga** [comment]
What's `site/settings/system.yaml`'s `locales` array?

What's `index.php`'s `$site_root` variable?

How are you hosting the site?

**Comment by wratke** [comment]
The locales array looks like this:

locales:
  en:
    full: en_US
    name: English
    url: 'http://localhost/ninesixteen_cms/'

The site root is set to this:

$site_root = '/ninesixteen_cms/';

I'm hosting it locally with Ampps.

**Comment by jasonvarga** [comment]
That looks fine. How about the `site/content/assets/[your container].yaml` file?

**Comment by wratke** [comment]
I have two containers (it was also doing the same thing with the default Main container which I didn't modify at all).

I have Grid Images:

path: grid_images
url: grid_images
title: 'Grid Images'
fieldset: grid_images

and Core Services:
path: core_services
url: core_services
title: 'Core Services'

**Comment by wratke** [comment]
This is what I removed from the absoluteUrl method in the statamic/core/Assets/Asset.php file in order to get working on my local setup:

if ($this->driver() === 'local') {
     $url = URL::prependSiteRoot($url);
}

**Comment by jasonvarga** [comment]
Yup, that'll do it.
This only happened if you had an absolute url defined in system.yaml.

Thanks for your help, it'll be in the next release.

**Comment by JesseLeite** [comment]
Just new'ed up statamic app in sub-folder, and hosting with Homestead.  Followed [the instructions here](https://docs.statamic.com/knowledge-base/subdirectory-installation), and threw this in the redwood homepage template:

```
{{ assets container="main" }}
    <pre>Url: {{ link :to="url" }}<br>Permalink: {{ permalink }}</pre>
{{ /assets }}
```

Which gives me this:

<img width="1326" alt="screen shot 2018-06-26 at 4 28 10 pm" src="https://user-images.githubusercontent.com/5187394/41937301-f6eb37c0-795d-11e8-9eb6-a45227360786.png">

And serving those permalinks works fine 🤔

**Comment by JesseLeite** [comment]
Oh ignore that last comment, I see!
