### ISSUE TITLE
Slug in browser address bar doesn't get updated

### ISSUE THREAD

**Issue by goellner** [statamic/v2-hub#2033]
**Describe the bug**
When editing an entry's slug with "Save & Continue" enabled, the slug in the browser url doesn't get updated. 

**To Reproduce**
1. Go to any entry
2. Change the slug
3. Set save button to "Save & Contintue"
4. See old slug in browser address bar

**Expected behavior**
Slug should get updated

**Environment details (please complete the following information):**
 - Statamic Version 2.9.8

**Comment by jackmcdade** [comment]
I totally get why it should work this way, but we don't have plans to change foundational workflows in v2. Will likely be addressed in v3 :)
