### ISSUE TITLE
Bug duplicating field into a sort of array if no field type is set  

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#2035]
**Describe the bug**
Clear and concise is not Ant's strength. But here goes.

If you have a field that for some stupid reason you forget to set the 'type', it defaults to text, but in 2.9.8 if you save this field it replicates itself x 5 in a semi-array (or at least it does for me). 

So this is my field:
```
  item_heading:
    display: Item Text Heading
    instructions: 'The main heading on the page'
```
Instead of just saving a regular text field in my .md file it saves this:
```
0: item_heading:What We Do
1: item_heading:What We Do
2: item_heading:What We Do
3: item_heading:What We Do
4: item_heading:What We Do
5: item_heading:What We Do
```
Every time I save it again it adds 5:
```
0: item_heading:What We Do
1: item_heading:What We Do
2: item_heading:What We Do
3: item_heading:What We Do
4: item_heading:What We Do
5: item_heading:What We Do
6: item_heading:What We Do
7: item_heading:What We Do
8: item_heading:What We Do
9: item_heading:What We Do
10: item_heading:What We Do
```

I didn't mean to forget to add the 'type' and have now fixed it, but still bug should probably be fixed.

**Additional context**

It's probably just Ant.

**Comment by jasonvarga** [comment]
Closing because this is an old issue. If you still need assistance, let us know.
