### ISSUE TITLE
Serve assets from above webroot publicly 

### ISSUE THREAD

**Issue by eddyloewen** [statamic/v2-hub#2036]
**Is your feature request related to a problem? Please describe.**
I'm trying to move everything related to content outside of the webroot. The only problem is that whenever I move the assets folder outside - the assets aren't publicly accessible. I'm not sure if this should work and I'm just doing it wrong or if it's maybe a bug?

**Describe the solution you'd like**
If it is not possible currently - I would like to be able to specify it via configuration whether an asset container is private or not (no matter where it is located)

**Comment by jasonvarga** [comment]
If a file is outside of the webroot, you will not be able to access it through the browser.

The same reason that you are moving files out of the webroot for security is why you cannot access them directly through a URL.

**Comment by eddyloewen** [comment]
It is not for security. I want to be able to have the content and assets in a different git repository and I really don't want to use git submodules
