### ISSUE TITLE
Strip underscore from asset filename when uploaded

### ISSUE THREAD

**Issue by sebszocinski** [statamic/v2-hub#2038]
For some reason unbeknown I often receive photos from professional photographers where they put an underscore in front of the filename which causes formatting issues inside Statamic yaml files.

![image](https://user-images.githubusercontent.com/5466694/41899099-bdb60798-796a-11e8-83d9-6cdef4e9c6e1.png)

Simple feature request... and could possibly cause issues somewhere along the line... can we just strip any underscores from the start of an image filename?

**Comment by jasonvarga** [comment]
There's nothing invalid about an underscore in a filename. Its just your syntax highlighter not handling that for whatever reason.

Closing this in favor of #2027
