### ISSUE TITLE
Assets isn't showing Thumbnails inside a Grid

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#2049]
**Describe the bug**
Probably just Ant™ but Assets isn't showing Thumbnails for me inside a Grid...

**Screenshots**
https://snag.gy/grQRMs.jpg

**Environment details (please complete the following information):**
2.9.12

**Additional context**
Probably just Ant™

**Comment by jasonvarga** [comment]
Can you provide any more details?
Any 404ing requests? What do you have saved for that field in your markdown file?

**Comment by jackmcdade** [comment]
Alas, I cannot recreate this. Feel free to reopen if it's happening in 2.10.7+ and you have more info. 👍
