### ISSUE TITLE
Mobile view of cp > Users > does not display well 

### ISSUE THREAD

**Issue by Burgopak** [statamic/v2-hub#2054]
**Describe the bug**
Mobile view of cp > Users > does not display well on a mobile the data runs off the screen!

**To Reproduce**
1. View in mobile
2. Go to dashboard
3. Click on users
3. See the mess/error

**Expected behavior**
A nice neat view of all the users of the system.

**Screenshots**

**Environment details (please complete the following information):**
 - Statamic Version 2.8.12
 - Fresh Install:
 - iPhone 6
 - Browser: iPhone 6 Safari
 - Web Server: Apache
 - PHP Version: 7.1
 - Addons installed: Mailchimp, spaceless, spock, cookie consent

**Additional context**

**Comment by jackmcdade** [comment]
If you upgrade to 2.9.x it'll be much better.
