### ISSUE TITLE
FR: Trigger an event for page not found response

### ISSUE THREAD

**Issue by taeo** [statamic/v2-hub#2056]
**Is your feature request related to a problem? Please describe.**
It isn't a problem, it's related to a limitation. I would like to build an addon or two that have the ability to know when a 404 page crops up. With said knowledge (access) I can do many helpful things such as, but not limited to:
* Perform custom 301 redirects that wouldn't be possible on the server-side
* Add custom data to the 404 page based on the request uri _(i.e. "You might be looking for X, Y, or Z")_
* Easily capture logs of missing pages
* And more...

**Describe the solution you'd like**
I want an event to be signaled when a 404 page is triggered so that I can listen to it and make good decisions about what to do with this new found knowledge.

**Describe alternatives you've considered**
* Using front matter redirect _(404 header is already sent)_
* Using `redirect` tag in `404.html` template _(404 header is already sent)_
* Hacking routes in bad ways such as `/*`

**Additional context**
This feature can be added by simply adding `event('response.page_not_found', $this->response);` right before `return $this->response;` in the `StatamicController.php` notFoundResponse method, like so:

```php
    private function notFoundResponse($url)
    {

        $this->loadKeyVars();

        $template = Str::removeLeft(Path::assemble(Config::get('theming.error_template_folder'), '404'), '/');

        $route = new ExceptionRoute($url, [
            'response_code' => 404,
            'template' => $template
        ]);

        $this->response->setContent($this->view->render($route));
        $this->response->setStatusCode(404);

        $this->setUpDebugBar();

        event('response.page_not_found', $this->response); // <- Right in here!!!!

        return $this->response;
    }
```

**Would you be willing to sponsor this feature?**
Sure, why not. I got $5 on it.

**Comment by jasonvarga** [comment]
I've made the `response.created` event (that's fired on non-404 requests) get fired for 404 responses, too.

You can do `if ($request->getStatusCode() === '404')` in your listener.
