### ISSUE TITLE
Unable to access fonts.googleapis.com from China in CP

### ISSUE THREAD

**Issue by efoken** [statamic/v2-hub#2058]
**Describe the bug**
We are about to launch our first **large** Statamic project for one of our customers. They have about 70% of visitors from China and of course some writers (CP users) from China. 

In CP in `head.blade.php` there is a Google Fonts stylesheet hardcoded which cannot be accessed by users from China. I would suggest to remove Goolge Fonts completely – and considering German DSGVO, it's better not to use Google Fonts at all...

**To Reproduce**
Visit the CP in China 🙂

**Expected behavior**
Replace Google Fonts with self-hosted font.

**Environment details (please complete the following information):**
 - Statamic Version 2.9.8
 - Fresh Install or Upgrade: Fresh Install
 - OS: Windows 10, iOS
 - Browser: Chrome, Edge, iOS Safari
 - Web Server: Nginx
 - PHP Version: 7.2.7

**Comment by jackmcdade** [comment]
Removed in [2.10](https://statamic.com/changelog#2.10.0), just for you!
