### ISSUE TITLE
Workshop: Add ability to Edit Entry for Page without needing to change Required Asset field

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#2060]
Using latest Statamic 2.9.8 and Workshop 1.1.0, when you create an Edit form with a required Asset field you cant update without having to upload the asset again or a new one.  If you want to keep the same Asset and make the field required, how can we do this?  Sometimes you just need to update a text field and not the Asset field, so this would be very helpful.

**Comment by jasonvarga** [comment]
Please re-post this on https://github.com/statamic/workshop and use the issue template. Don't just discard it.
