### ISSUE TITLE
Can't define debug or caching settings in env files

### ISSUE THREAD

**Issue by sebszocinski** [statamic/v2-hub#2064]
As previously mentioned in #2048 which has been closed and marked fixed, i'm still having this issue.

I've noticed it when trying to set Debug or Stache settings in my env files. However it works fine for Locales in `system.yaml`, just not for `debug.yaml` or `caching.yaml`

I have this setting in `debug.yaml`:
```
debug: "{env‌:APP_DEBUG}"
debug_bar: "{env‌:APP_DEBUG_BAR}"
```

and in my `.env` file I have:
```
APP_ENV=dev
APP_DEBUG=true
APP_DEBUG_BAR=false
```

But this is what my CP debug page looks like. (Note the Debug bar is also showing)...

![image](https://user-images.githubusercontent.com/5466694/42855661-b84d2f3a-8a80-11e8-92cb-5b080f807abf.png)

However in `system.yaml` I have:
```
locales:
  en:
    name: English
    full: en_AU
    url: "{env:EN_URL}"
```

and in my `.env`:
```
EN_URL="http://statamic-base.test"
```

and in the CP:
![image](https://user-images.githubusercontent.com/5466694/42855714-f640d83c-8a80-11e8-8ade-c07d735e0580.png)

Which is fine and working!!

What am I doing wrong with Debug and Caching?? Or is this a bug?

**Comment by jasonvarga** [comment]
Do you have anything in `site/settings/environments/`?

**Comment by sebszocinski** [comment]
Nope not using those

Cheers,

SEB SZOCINSKI
— Web Developer

tel. +61 422 044 127

Apt 1 — 2 East Tce
Adelaide, SA
Australia 5000

ROCKETHOUSE.COM.AU


On Thu, Jul 19, 2018 at 12:12 AM, Jason Varga <notifications@github.com> wrote:
Do you have anything in site/settings/environments/ ?

**Comment by jasonvarga** [comment]
Are you sure? Adding a setting in one of those replicates this issue exactly as you've described.

**Comment by sebszocinski** [comment]
yep 100%, we used to use that method but recently switched to `.env` files only.

Could it be stuck somewhere in thinking that its still looking for an `environment` folder in settings?

![image](https://user-images.githubusercontent.com/5466694/42913825-3b499d8c-8b36-11e8-83d2-f7daeb2e96e7.png)

**Comment by sebszocinski** [comment]
My issue was the invisible character thingy... [as mentioned and resolved here](https://statamic.com/forum/2967-debug-settings-in-env) 

If anyone else comes across this issue, this is a handy tool: https://www.textmagic.com/free-tools/unicode-detector

![image](https://user-images.githubusercontent.com/5466694/43501048-c83f0928-9592-11e8-8c9d-0f3a5bb947cc.png)
