### ISSUE TITLE
Tags displaying too large inside Grid

### ISSUE THREAD

**Issue by efoken** [statamic/v2-hub#2065]
**Describe the bug**
When using tags inside a grid, the height and line-height is too large.

**To Reproduce**
1. Build a fieldset with a Tags inside a Grid
2. Create an entry with this fieldset
3. Add Options in Grid and add a few tags.
1. See that tags are too large

**Screenshots**
<img width="631" alt="bildschirmfoto 2018-07-18 um 07 40 00" src="https://user-images.githubusercontent.com/522446/42861989-d14efbda-8a5d-11e8-85db-ae351e691dfd.png">

**Environment details (please complete the following information):**
 - Statamic Version 2.10.0
 - Fresh Install or Upgrade: Upgrade
 - OS: macOS
 - Browser: Chrome
 - Web Server: Valet
 - PHP Version: 7.2

**Comment by dannyuk1982** [comment]
Same for me with a suggest field.

Additionally if they go over onto 2 lines you can never see past one line.

It's a new thing with 2.10.0

<img width="951" alt="screen shot 2018-07-18 at 08 49 04" src="https://user-images.githubusercontent.com/7669885/42867563-e332b486-8a67-11e8-8a60-d984fb40b1fd.png">
