### ISSUE TITLE
Fieldset other than default.yaml not being saved for a page

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#2069]
**To Reproduce**
1. Create a new page, choose a fieldset other than default
2. Enter data and save it
3. Open it again, it is using the default fieldset

The yaml for that page lists 
```
fieldset: null
```

**Environment details (please complete the following information):**
 - Statamic Version 2.10.0

**Comment by dannyuk1982** [comment]
I am getting this in 2.9.8 too

**Comment by jasonvarga** [comment]
Duplicate of #2068, essentially.

**Comment by dannyuk1982** [comment]
Ah yes, I hadn't thought they would be related
