### ISSUE TITLE
Relate syntax broken from 2.8.10 to 2.10.0

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#2070]
**Describe the bug**
Upgrading from 2.8.10 to 2.10.0 causes an exception regarding usage of relate tag:
```
InvalidArgumentException in Stringy.php line 41:
Passed object must have a __toString method
```

**To Reproduce**
1. Use the relate tag in this format: `{{ relate :taxonomy="term:id"  }}`.
2. See that the above exception occurs.

**Expected behavior**
Valid `relate` syntax from earlier versions should work when upgrading.

**Screenshots**
Screenshot of stack trace.
![relate-index-exception](https://user-images.githubusercontent.com/1186125/42877511-36a36954-8a8a-11e8-838e-06ec79c4b720.png)

**Environment details (please complete the following information):**
 - Statamic Version: 2.10.0
 - Fresh Install or Upgrade: Upgrade from 2.8.10
 - OS: Alpine Linux 3.7
 - Browser: Irrelevant
 - Web Server: Nginx
 - PHP Version: 7.1
 - Addons installed: Irrelevant

**Additional context**
Git diff of the code changes causing this problem.
```diff
iff --git a/statamic/bundles/Relate/RelateTags.php b/statamic/bundles/Relate/RelateTags.php
index fe5e794..a8639e7 100644
--- a/statamic/bundles/Relate/RelateTags.php
+++ b/statamic/bundles/Relate/RelateTags.php
@@ -19,6 +19,16 @@ class RelateTags extends CollectionTags
     {
         $var = explode(':', $this->tag, 2)[1];

+        return $this->collect($var);
+    }
+
+    public function index()
+    {
+        return $this->collect($this->get('field'));
+    }
+
+    private function collect($var)
+    {
         $this->collection = collect_content();

         $values = Helper::ensureArray(array_get($this->context, $var, []));
```

If we're using the relate tag incorrectly, please update the docs with the correct syntax.

**Comment by jasonvarga** [comment]
What does `{{ term:id }}` output on its own?

**Comment by jasonvarga** [comment]
What field are you attempting to relate?

`{{ relate:you_need_a_field_here :taxonomy="..." }}`

**Comment by FrittenKeeZ** [comment]
Here's a bit more context.
```html
{{ taxonomy:regions sort="sequence|count:desc" scope="region" filter="pages" filter-pages="page-hotel" }}
    <li class="nav-item region">
        <h3 class="nav-headline">{{ region:title }}</h3>
        <ul class="nav-items hotels">
            {{ relate :taxonomy="region:id" sort="title" }}
                <li class="nav-item">
                    <a class="nav-link {{ if {hotels:segment :current="uri"} }}active{{ /if }}" href="{{ permalink }}">{{ headline }}</a>
                </li>
            {{ /relate }}
        </ul>
    </li>
{{ /taxonomy:regions }}
```
I'm trying to relate a taxonomy term from regions.

**Comment by jasonvarga** [comment]
But what is being related? What are you looping over with that `relate` tag?

**Comment by FrittenKeeZ** [comment]
I'm looping over all entities which has the region taxonomy term assigned.

**Comment by jasonvarga** [comment]
The taxonomy:regions tag is looping through all the terms in the regions taxonomy.

Then you want to loop over the entries using the relate tag? Use a `collection` tag pair instead.

I'm not sure how the relate tag without a field defined was ever working.

**Comment by FrittenKeeZ** [comment]
If you comment out the code changes I wrote it the top, maybe you can figure out why it worked?
So how would I use the `collection` tag pair?

**Comment by FrittenKeeZ** [comment]
I still don't know how to get this to work again.
I've tried using the `pages` tag, but that doesn't work either.
`{{ pages from="/" depth="2" :taxonomy="region:id" sort="order|title" }}`
It doesn't filter anything regarding the region term...

**Comment by jasonvarga** [comment]
I think I see what's happening now.

The way you had it before, it wasn't even really calling the `relate` tag, it was using the `collection` tag since relate extends it.

Try just literally changing `relate` to `collection` in your template. Does that work?

```
        <ul class="nav-items hotels">
            {{ collection :taxonomy="region:id" sort="title" }}
                <li class="nav-item">
                    <a class="nav-link {{ if {hotels:segment :current="uri"} }}active{{ /if }}" href="{{ permalink }}">{{ headline }}</a>
                </li>
            {{ /collection }}
        </ul>
```

**Comment by FrittenKeeZ** [comment]
Thanks @jasonvarga! It works now :)
