### ISSUE TITLE
Brad is missing save and close icons for anchor extension

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#2071]
**Describe the bug**
After upgrading to 2.10.0, the anchor extension in Bard is missing the save and close icons.

**To Reproduce**
1. Setup a Bard fieldtype.
2. Add an anchor to some text.
3. See that the icons are missing.

**Expected behavior**
The icons should be present after upgrading to 2.10.0.

**Screenshots**
Before upgrading:
![screen shot 2018-07-18 at 3 31 10 pm](https://user-images.githubusercontent.com/1186125/42885158-8994e726-8aa0-11e8-9e9e-ef512b43681a.jpg)

After upgrading:
![screen shot 2018-07-18 at 4 16 02 pm](https://user-images.githubusercontent.com/1186125/42885168-8f321f00-8aa0-11e8-96b8-a1abc1467c0a.jpg)

**Environment details (please complete the following information):**
 - Statamic Version: 2.10.0
 - Fresh Install or Upgrade: Upgrade from 2.8.10
 - OS: Alpine Linux 3.7
 - Browser: All
 - Web Server: Nginx
 - PHP Version: 7.1
 - Addons installed: None conflicting.

**Additional context**
Installing the FontAwesome addon will "fix" the issue.

**Comment by dannyuk1982** [comment]
Nice to see the correct spelling in the subject at least
