### ISSUE TITLE
FR: Make Brad and Reg le Cator look the same

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#2072]
At the moment using Brad is nice, and using Reg is nice too. Reg feels older than Brad, that's OK he is, it's not a big deal until you see him standing next to Brad. Then you realise that Brad is more dashing and sleek. 

Some clients looking at both might be confused in the way they handle links so differently, or how their typographic tools are from different decades. 

It would be nice if Reg had a make over so that his UI was the same as Brad's, so it doesn't feel like a CP page is a hack of two different things.

--

Priority level: 0.001 (but above anything for Erin)

Niceness to have: like printing out that photo of Jason on the about page, as a bespoke wallpaper and getting a matching duvet set made.

**Comment by jackmcdade** [comment]
I have no idea what you're talking about.

**Comment by dannyuk1982** [comment]
How about these old snaps of Brad and Reg trying on a new link?

<img width="817" alt="screen shot 2018-07-18 at 16 36 32" src="https://user-images.githubusercontent.com/7669885/42892086-d554e8de-8aa8-11e8-84d4-e2014da6a85f.png">
<img width="828" alt="screen shot 2018-07-18 at 16 36 54" src="https://user-images.githubusercontent.com/7669885/42892087-d5721c7e-8aa8-11e8-839d-e0f8c5c8fd77.png">

**Comment by jasonvarga** [comment]
Danny, you're on time out. Go sit in the corner.

**Comment by jackmcdade** [comment]
Oh, Redactor and Bard. Got it. Yeah, ain't gonna happen, not in v2 at least. Would take a huge amount of effort to override third party tools for minimal gain. I don't disagree it would be nice if it was uniform. Just, you know. Maybe v3.

**Comment by dannyuk1982** [comment]
Well it was Replicator actually... Redactor would be like Ralph Proctor or something equally bad.

**Comment by jackmcdade** [comment]
But it wasn't replicator. That's a screenshot of Redactor.

**Comment by dannyuk1982** [comment]
It's in a Replicator. Aha!

**Comment by jackmcdade** [comment]
Redactor has the same UI no matter where you put it 😬

**Comment by dannyuk1982** [comment]
Fine, I've edited it.

ETA on the Jason wallpaper and matching duvet?

**Comment by jackmcdade** [comment]
![image](https://user-images.githubusercontent.com/44739/42892564-20086bd6-8a80-11e8-9e14-b993d82f3b6a.png)
Shipped!
