### ISSUE TITLE
Redirect route not removing subdir

### ISSUE THREAD

**Issue by fewclicksGmbH** [statamic/v2-hub#2078]
**Describe the bug**
We had a problem with a permanent redirect, resulting in a double subdir prepended to the url (en/en).

**To Reproduce**
1. Setup a multilingual site using url to resolve the language (/en)
Using locales like this. (Maybe it was our fault not to use `/en/` as the url.)
```
locales:
  de:
    full: de_DE
    name: Deutsch
    url: /
  en:
    full: en_US
    name: English
    url: /en
```
2. Add a valid redirect in the routes.yaml
Example:
```
redirect:
  /test: /test/123
```
3. Now try to access `example.test/en/test`
4. This should result in a redirect to `example.test/en/en/test`

**Expected behavior**
A correct redirect to `example.test/en/test`

**Additional context**
I trimmed the error down to `Statamic\API\URL`  Line 241.
Here you want to ensure that both `$url` and `$siteUrl` end with an trailing slash. But on the `$url` you do a `ensureLeft` instead of a `ensureRight`. Resulting in `$url` being `/en` and `$siteUrl` being `/en/` and then the `Str::startsWith($url, $siteUrl)` fails.
`$url = Str::ensureRight($url, '/');` results in a correct behaivor.
I hope this is a correct finding and you can fix this fast.

**Comment by jasonvarga** [comment]
Thanks for the suggested fix!

What I'd suggest instead is to use `/en/` instead, with the trailing slash.

We're expecting that slash all over the place, so we'll look at better ways to enforce that internally.
