### ISSUE TITLE
'You are using unlicensed software. More details' - for addon

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#2079]
I get this message on an old site:

`You are using unlicensed software. More details`

<img width="403" alt="screen shot 2018-07-25 at 17 39 40" src="https://user-images.githubusercontent.com/7669885/43215111-36e22eb0-9033-11e8-94a7-0fb2770fa36c.png">

The `video` add on is an old one and was/is free - this shouldn't be happening as now it appears to the client that the whole site is pirated.

**Comment by jcohlmeyer** [comment]
There is a new addon that is charging $1 with the same namespace that is the most likely cause of this issue, that being said this is still quite a big issue.

**Comment by dannyuk1982** [comment]
That does appear to be the case, unfortunately I have the video addon by Alex Duner on several sites - which predates any support in core or the marketplace – and now they all appear that Statamic is not licensed to clients, which looks very bad on me. 

What happens if I have an addon, say one that pulls events from Eventbrite on several sites, and then someone makes a $1 version in Marketplace with the same name, do I then need to alter the addon I made for private use on all the sites that have it? This seems a bit of an oversight if Marketplace addons can affect any other addon made in the past.

**Comment by jasonvarga** [comment]
Closing this for now, the issue has been alleviated for the moment. We'll track this better internally.
