### ISSUE TITLE
Reordering pages and save error

### ISSUE THREAD

**Issue by mirill1** [statamic/v2-hub#2081]
Description:
I reorder the pages in the cp. After I clicked the save button there comes a exception.

1. Reorder pages via drag and drop
2. Click on save
3. Look in the console for the error

Error message:
Argument 2 passed to Statamic\Events\Data\PageMoved::__construct() must be an instance of Statamic\Events\Data\string, string given, called in /var/www/html/statamic/core/Data/Pages/PageTreeReorderer.php on line 42 and defined' in /var/www/html/statamic/core/Events/Data/PageMoved.php:31

Details:
 - Statamic Version 2.10.2
 - Fresh Install or Upgrade:
 - OS: macOS 10.12.6
 - Browser: chrome, safari
 - Web Server: Apache
 - PHP Version: 5.6.27

**Comment by mirill1** [comment]
Yes, it happens on every save.
I deleted all pages and created new pages, same problem.

**Comment by nevoxx** [comment]
Statamic\Events\Data\PageMoved::__construct() seems to use php 7 type hints, which cause an error when using php 5. Did the requirements for the php version change? the documentation says php >= 5.5.9 at https://docs.statamic.com/installing
 
`public function __construct(Page $page, string $oldPath, string $newPath)`

**Comment by jasonvarga** [comment]
That's a mistake, we'll sort that out. Thanks!

**Comment by nevoxx** [comment]
Same thing in `Statamic\Events\Data\SettingsSaved`:

`public function __construct(string $path, array $data)`

**Comment by jasonvarga** [comment]
Yep, we'll adjust all those new events we added in 2.10, thanks for pointing that out.

**Comment by nevoxx** [comment]
thanks. much appreciated
