### ISSUE TITLE
Asset pages in CP don't cache images

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#2082]
**Is your feature request related to a problem? Please describe.**
When navigating around the assets pages of the CP the images reload on each visit. This is slows down user activity. This is especially true when doing a bulk assets activity like adding alt-text.

**Describe the solution you'd like**
Images to be cached by the browser.

**Comment by jackmcdade** [comment]
Do you have devtools open? If so, it clears the browser cache each request. The thumbnails should cache fine with it closed.

**Comment by wesort** [comment]
The issue is the same with Dev Tools open or closed. 

Even without Dev Tools open navigating in and out of folders takes a few extra seconds as the images visually populate the list. For example, a folder (with 15# images, each ~200-700KB, on a 50Mbps internet connection) is taking 4-5 seconds to load. (NB: The front-end web page containing those same images loads in an instant due to the browser cache.) This is after previously visiting the page in CP only seconds before and having already run `php please assets:generate-presets`. Also, I've noticed that my Gravatar image _**is**_ being cached.

**Comment by jasonvarga** [comment]
This is because of #1386 where we were a little aggressive, also caching thumbnails.
Fixed for next release!
