### ISSUE TITLE
The search input on the control panel doesn't work well

### ISSUE THREAD

**Issue by eddiesigner** [statamic/v2-hub#2083]
**Describe the bug**
I have a collection of products with more than 300 items and when I try to search for some of them using the search input I don't get results even if they are part of the list.

The issue is that sometimes it works well and other times it doesn't.

**To Reproduce**
1. Go to Collections
2. Click on Products
3. The collection has a product called **Whiskey**
4. Search for the product called **Whiskey**
5. No results

**Expected behavior**
I would expect to see as result the product called **Whiskey**

**Screenshots**
Collection list before the search:
![group](https://user-images.githubusercontent.com/1477503/43283488-5869806a-9119-11e8-848e-bd75b50615e5.png)

No results:
![screenshot_2018s-07-26 panel de control vimaliving](https://user-images.githubusercontent.com/1477503/43283504-5f7081d8-9119-11e8-948c-30e7e9433eb9.png)

**Environment details (please complete the following information):**
 - Statamic Version: 2.10.2
 - Fresh Install or Upgrade: Upgrade
 - OS: macOS 10.13.6
 - Browser: Firefox
 - Web Server: Nginx
 - PHP Version: 7.1.10
 - Addons installed: None

**Additional context**
Also when you search for some items with a similar name some of them are excluded from the results. For example, if you have these items:

- Product 1
- Product 2
- Product 3
- Product 4
- Product 5

And you search for: **Product**

You get:

- Product 1
- Product 2
- Product 5

**Comment by jasonvarga** [comment]
Do you have a search index set up for that collection? What do you see in `local/storage/search`?

**Comment by eddiesigner** [comment]
Yes, I have but the problem was I completely forgot about this command:

`php please search:update collections/blog`

Thanks anyway!
