### ISSUE TITLE
Reusing Amazon S3 asset driver for Digital Ocean Spaces

### ISSUE THREAD

**Issue by nathobson** [statamic/v2-hub#2085]
**Is your feature request related to a problem? Please describe.**
The [Digital Ocean Spaces](https://www.digitalocean.com/products/spaces/) API is completely compatible with those of S3. However, the only thing stopping us being able to use Spaces is that the S3 regions are locked down within a select box and would be prepended to `amazonaws.com` rather than `digitaloceanspaces.com`. [The Flysystem website](https://flysystem.thephpleague.com/docs/adapter/digitalocean-spaces/) explains that you should use the S3 adaptor for Spaces.

**Describe the solution you'd like**
In an ideal world, there would be a 3rd option for `Digital Ocean Spaces` when following the Container wizard (under Driver). This should be able to duplicate all of the internals from the current Amazon S3 wizard. The only difference would be a different set of end points, which are currently:

1. New York: nyc3.digitaloceanspaces.com
2. Amsterdam: ams3.digitaloceanspaces.com
3. Singapore: sgp1.digitaloceanspaces.com

**Describe alternatives you've considered**
Adding the additional endpoints to the S3 screen, although this doesn't seem particularly intuitive.

**But why?!**
Spaces is a nice alternative to S3 as the costing is completely transparent and fixed. $5/month = 250GB storage, 1TB outbound transfer and no cost for inbound. This is much more appealing to a agency managing many sites as the cost is predictable.

I also believe many Statamic users host their site with Digital Ocean, so it makes sense to be able to keep a single provider for hosting and storage.

I'd be happy to provide Spaces for testing or I believe you can get a free 2 month trial.

**Comment by jasonvarga** [comment]
Hi! While the UI doesn't let you choose Digital Ocean options, you can still just create the YAML file and it works just fine.

```
title: Digital Ocean
driver: s3
key: your-spaces-key
secret: your-spaces-secret
bucket: your-space-name
region: nyc3
endpoint: https://nyc3.digitaloceanspaces.com
```
