### ISSUE TITLE
Specify that the global smartypants setting only works in "content"

### ISSUE THREAD

**Issue by vladdu** [statamic/v2-hub#2088]
The instructions for the smartypants setting don't say where it applies (i.e. only in content). I thought it would apply in rendering regular tags too.

Suggested change:
```
'smartypants_instruct' => 'Enable to automatically convert typographic elements (like quotes and dashes). Only works in content; in tags use the "smartypants" modifier.',
```

Version 2.10.2

**Comment by jackmcdade** [comment]
It only works _in conjunction with Markdown_. :)
