### ISSUE TITLE
Bard: Cursor jumps to top on paste

### ISSUE THREAD

**Issue by eike-hass** [statamic/v2-hub#2095]
**Describe the bug**
When pasting text in a Bard field the cursor jumps to the beginning of the field.

**To Reproduce**
See the behavior in the attached gif

**Expected behavior**
I think it would be resonable to have the cursor jump behind the pasted content

**Screenshots**
![pastebug](https://user-images.githubusercontent.com/3441319/43536419-d9584538-95bc-11e8-8da8-d5e19e990e32.gif)

**Environment details (please complete the following information):**
 - seems to affect Statamic Version 2.9.X and 2.10.X
 - definitely latest Chrome on Windows and Mac (we will check other browsers and report back)

**Comment by jackmcdade** [comment]
100% agree with your reasonable expectation, and we've been annoyed by this one too. Working on a fix, but haven't sorted it out yet.

**Comment by jasonvarga** [comment]
Fixed for 2.10.3!
