### ISSUE TITLE
Root of assets folder in CP still has ".." folder

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#2098]
**Describe the bug**
When at root of Assets there is a `..` folder icon (go up one directory level). Clicking this shows all of the assets in the container and the folders are still present too. This is unexpected and confusing.

_FWIW, I think that `..` convention is lost on many CP users from the client side. The feedback I've had is most don't know what this does and find it confusing as they're not command line users._

**To Reproduce**
1. Go to `/cp/assets/browse/main`
2. Click on `..` folder 
3. This changes url to `/cp/assets/browse/main/null`
4. All assets are now displayed regardless of what folders they're in. 

**Expected behavior**
For either:
a. That `..` folder not to exist when at root.
b. That `..` folder to be renamed "All assets" and for the folders to disappear once on "All assets" view
c. For that `..` folder to be removed completely and replaced with breadcrumbs 

**Environment details (please complete the following information):**
 - Statamic Version [e.g. 2.10.3]
 - Fresh Install or Upgrade: Upgrade from v.2.10.2
 - OS: Linux
 - Browser: Chrome
 - Web Server: Nginx over Apache (Webfaction)
 - PHP Version: 7.2
 - Addons installed: Logbook

**Comment by jasonvarga** [comment]
Weird, we don't see the `..` in the root folder.

![image](https://user-images.githubusercontent.com/105211/43645673-a2af791c-9700-11e8-8221-95e118074e68.png)

Anything special about your site? Are you running in a subdirectory?

**Comment by simonhamp** [comment]
I see this too, in Grid view. List view is fine

**Comment by simonhamp** [comment]
It's worth noting that this allows a user to circumvent the "Restrict to folder" option on the Asset fieldtype as they can then see images from folders other than the one that the field is restricted to.

**Comment by wesort** [comment]
I believe I'm running a pretty standard setup and I'm seeing this across multiple sites. 

List view does show the `..` folder if you switch from thumbnail or force the URL at `/cp/assets/browse/main/null`

@jasonvarga I've just granted you access to a repo for my own site. Please don't push to master (obvs!)

**Comment by simonhamp** [comment]
Can confirm: switching to grid view, clicking the `..` folder and then switching back to list view and the `..` folder shows there too.

**Comment by jackmcdade** [comment]
Ah ha! It's the grid mode that does it. Good catch!
