### ISSUE TITLE
Queue worker prevents the Stache being built

### ISSUE THREAD

**Issue by jackwakefield** [statamic/v2-hub#2099]
**Describe the bug**
Setting up a Statamic project to use Laravel's queue worker with a fresh install fails to build the Stache when visiting the website.

**To Reproduce**
1. Run the queue worker with the `--daemon` option, e.g.
```bash
php please queue:work --sleep=1 --tries=3 --daemon
```
2. Visit the home page
3. See a blank page which refreshes until the queue worker process is killed

**Expected behavior**
The queue worker and website play nicely together.

**Environment details (please complete the following information):**
 - Statamic Version 2.10.3
 - Fresh Install or Upgrade: Fresh Install
 - OS: ArchLinux (also tested with an Ubuntu container)
 - Browser: Chrome
 - Web Server: Apache
 - PHP Version: 7.2
 - Addons installed: None

**Comment by jackmcdade** [comment]
Closing in favor of duplicate, but more detailed #2159.
