### ISSUE TITLE
Error updating Statamic

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#2100]
**Describe the bug**
Updated Statamic from 2.10.2 to 2.10.3 and got an error:
```
  [Symfony\Component\Process\Exception\ProcessTimedOutException]                                                          
  The process "/usr/local/Cellar/php/7.2.8/bin/php please update:housekeeping --from=2.10.2" exceeded the timeout of 60   
  seconds.    
```

**To Reproduce**
1. Run `statamic updater`

**Expected behavior**
No error

**Environment details (please complete the following information):**
 - 2.10.2
 - OS: macOS 10.13.6
 - Web Server: Valet
 - PHP Version: 7.2

**Comment by jcohlmeyer** [comment]
I got this issue as well with `2.10.2` to `2.10.3` update on `Ubuntu` with `PHP 7.1` via the CLI command `php please update:statamic`

**Comment by FrittenKeeZ** [comment]
I had to clear cache before housekeeping would run.

**Comment by edalzell** [comment]
a manual update works fine though, including the updating of housekeeping.
