### ISSUE TITLE
Impossible to localize asset fields

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#2103]
**Describe the bug**
Adding `localizable: true` to asset `alt` and `title` fields does nothing.
I can't see any way to change to language for assets.

**To Reproduce**
1. Add `localizable: true` to asset fields.
2. Try to set `alt` and `title` for a different language than default.

**Expected behavior**
You can change the language for assets and set `alt` and `title` tags for different languages.

**Environment details (please complete the following information):**
 - Statamic Version: 2.10.2
 - Fresh Install or Upgrade: Upgrade
 - OS: Alpine Linux 3.7
 - Web Server: Nginx
 - PHP Version: 7.1

**Comment by jasonvarga** [comment]
Assets are not currently localizable.

**Comment by FrittenKeeZ** [comment]
@jasonvarga I noticed `title` isn't outputted for alternate locales when calling `$asset->in($locale)->toArray()` - all other variables are pulled from default correctly.

**Comment by jasonvarga** [comment]
We don't support localizing assets yet. Don't attempt it :)
