### ISSUE TITLE
Infinite loading in the CP after attempting to edit a blog post

### ISSUE THREAD

**Issue by nebulousGirl** [statamic/v2-hub#2105]
**Describe the bug**
Whenever I visit a blog post on my local install in the CP, the system starts to hang. When I reload the page, Statamic seems to get hung up and reloads infinitely without displaying anything.

When looking at the Network tab, I can see AJAX calls returning 503 errors with a "The cache is being updated. Please wait and try again." message.

**Environment details (please complete the following information):**
 - Statamic Version [e.g. 2.8.12]
 - Fresh Install or Upgrade:
 - OS: Windows 10
 - Browser: Firefox
 - Web Server: Apache
 - PHP Version: 7.1
 - Addons installed: None

**Comment by edalzell** [comment]
What version of Statamic?

**Comment by nebulousGirl** [comment]
Latest I think 2.10.3.

Reinstalling from scratch seems to have resolved the issue, but it makes me a bit wary of using Statamic. If it happens again on a live website, it would mean trouble.

But I really want to use Statamic, I love how the management system has been built. I find it easy to understand, yet incredibly powerful.

Is there some kind of explanation as to what could have happened?

**Comment by jasonvarga** [comment]
Do you have a large site? Roughly how many pages/entries are in there?

**Comment by nebulousGirl** [comment]
Just playing around the default website Redwood. Got the issue again this morning. Seems to be only when I start editing blog posts.

Here are the 2 ajax requests failing:
http://domain.d3v/cp/addons/suggest/suggestions
http://domain.d3v/cp/assets/get

**Comment by nebulousGirl** [comment]
Restarting the server resolves the problem.

It seems that any blog post containing an asset triggers the problem. I seem to be missing the assets files. I get broken image icons on the frontend's homepage.

**Comment by nebulousGirl** [comment]
Found the problem when checking the broken images on the frontend. Exif was not enabled on my dev server.

I see that it's not listed as a requirement on the installation page: https://docs.statamic.com/installing

And I think it was not verified during installation.

**Comment by nebulousGirl** [comment]
Nevermind I still have the infinite loading issue in the cp. 

It occurs most often on this Ajax request:
**http://domain.d3v/cp/assets/get**

**Comment by jackmcdade** [comment]
Are you still having issues, and are you on the latest version of Statamic?

**Comment by jackmcdade** [comment]
This issue has been inactive and in need of more information for a while now. Feel free to reopen and we'd be more than happy to take another look if you have more info that can help!
