### ISSUE TITLE
Assets Editor Bug

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#2118]
**Describe the bug**
When you open the Assets Editor and change something (like focal point) - when you press save it produces an error where the right hand side of the modal that has the assets fields (title, alt text etc) shows raw HTML doc content - see this gist for the full output: https://gist.github.com/anthubbard/c7888bd2e03f6fea5c878b0d8ec9e01b

**To Reproduce**
1. Open an Image in Assets Editor
2. Change focal point
3. Save

**Expected behavior**
Don't do this please

**Screenshots**
![screen shot 2018-08-12 at 10 56 54 am](https://user-images.githubusercontent.com/5089177/43997487-9f6f0972-9e1f-11e8-99b9-29707ceb081c.png)

**Environment details (please complete the following information):**
 - Statamic Version 2.10.3
 - Fresh Install or Upgrade: Upgrade
 - OS: OSX running Valet
 - Browser: Chrome
 - Web Server: Valet
 - PHP Version: 7.2
 - Addons installed:

**Additional context**
Possibly just Ant™ but I doubt it this time

**Comment by jackmcdade** [comment]
What’s the error message from the Ajax call in your dev tools?

**Comment by anthubbard** [comment]
This is an error in the console, no idea if related to Ajax call...

Failed to load resource: the server responded with a status of 500 (Internal Server Error) http://coppercrosssocks.localhost/cp/assets/main/images/pages/pexels-photo-221210.jpeg

**Comment by jasonvarga** [comment]
When you hit save, it does an ajax call. There's an error, and what you're seeing is the HTML for that error page. You can look at the error in your devtool's network tab, or probably even better, look at the error in your log file.

**Comment by anthubbard** [comment]
This is from my log with nothing else - all I did was recreate that error and it logged this:
https://gist.github.com/anthubbard/62d4905ad792cbb172b619acb5a48bde

**Comment by jasonvarga** [comment]
What's in `site/content/assets/main.yaml`?

**Comment by anthubbard** [comment]
Nothing, it's not saving the change...
```
title: Main Assets
path: assets
fieldset: site-assets
url: /assets
assets:
```

**Comment by jasonvarga** [comment]
Remove the `assets:` line and try again.

**Comment by anthubbard** [comment]
You're a genius? Yes that worked...

**Comment by jasonvarga** [comment]
Did you have asset data in there at one point but removed it by hand? `assets:` like that is an empty string, so when Statamic goes to tack another item onto the array... its not an array, so it wigs out.

**Comment by anthubbard** [comment]
ahh got it, yeah i remove that by hand every time I duplicate a site I'll make sure I remove the `assets:` every time now. Wow, turns out it still was just Ant™

 ¯\_(ツ)_/¯
