### ISSUE TITLE
show more button for collections

### ISSUE THREAD

**Issue by 4kets** [statamic/v2-hub#2119]
I dont know if there is an alternative to this.

**Describe the solution you'd like**
For a collection when i limit it to 5, i want instead of the paginate function a button saying show more. And when pressed that it loads one more.

**Comment by jackmcdade** [comment]
That would be an ajax call (which you can certainly do yourself) but is not something we would support as a core feature.

You can do regular and prev/next pagination like this though: <https://docs.statamic.com/tags/collection#pagination>
