### ISSUE TITLE
Asset Variable Conditional with Asset Tag Pair Fails on Collection Entry

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#2122]
**Describe the bug**
I am trying to run a conditional in an asset field just to check for existence of the asset `{{ title }}` field.  It works fine on all pages other than my event detail (collection entry). `{{ if title }}` is coming back true no matter what I do.  It seems to be looking at the entry title and not the asset title.  I tried using scope but not sure how to work that with asset pair.  

**To Reproduce**
```
{{ asset:event_image }}
<div class="imatron mb-3" style="background: url({{ glide:url preset='header' }}) center / cover no-repeat;">
{{ if title }}
<div class="grid-container">
  <div class="grid-x grid-padding-x">
    <div class="small-12 cell text-right">
      <p class="label bold green mt-1 mr-1">{{ title }}</p>
    </div>
  </div>
</div>
{{ /if }}
</div>
{{ /asset:event_image }}
```

**Expected behavior**
`{[ if title }}` should return false if no Asset Title is set. Works fine on pages, fails on collection entry.

**Screenshots**

**Environment details (please complete the following information):**
 - Statamic Version [2.10.3]
 - Workshop 1.1.1:
 - Spock 2.0.1
 - Recaptcha 2.3
 - Browser: [all]
 - Web Server: [Valet]
 - PHP Version: [7.1]
 - Addons installed:

**Additional context**

**Comment by bgarrant** [comment]
I played around with scope also and still can't get this to work.

**Comment by jackmcdade** [comment]
How about not using `asset:`? You're simply dealing with the cascade here.

```
<div class="imatron mb-3" style="background: url({{ glide:event_image preset='header' }}) center / cover no-repeat;">
{{ if event_image | get:title }}
<div class="grid-container">
  <div class="grid-x grid-padding-x">
    <div class="small-12 cell text-right">
      <p class="label bold green mt-1 mr-1">{{ event_image | get:title }}</p>
    </div>
  </div>
</div>
{{ /if }}
</div>
```

**Comment by bgarrant** [comment]
I figured that was it Jack.  Thanks for your help.  This works great!
