### ISSUE TITLE
S3 Assets Metadata

### ISSUE THREAD

**Issue by makkinga** [statamic/v2-hub#2123]
**Describe the bug**
To be able to score 100/100 in Google's PageSpeed Insights I need to be able to add metadata like a cache-control or an Expires header to the assets.

**Expected behavior**
I would like to be able to add to my `/site/content/assets/main.yaml` something like:
```
options: 
  CacheControl: max-age=31536000
```

**Environment details:**
 - Statamic Version: 2.10.3
 - Fresh Install

**Additional context**
The constructor of `AwsS3Adapter` already expects an array of these options.
I found that simply adding `$config['options'] ?? []` as the last param on line 312 of `/statamic/core/Providers/FilesystemServiceProvider.php` does the trick.

**Comment by jackmcdade** [comment]
You can set that stuff on the server level. It's much cleaner :)

**Comment by madsem** [comment]
@jackmcdade actually, when using S3 setting the headers server-side won't do anything. And if on top of that you're using Cloudfront as a CDN, which by default uses the headers S3 passes along, you end up with no Cache-Control etc headers at all, and Pagespeed gives you bad bad ratings :)

I'm also looking for a way atm how I can tell Statamic to upload everything to S3 by default with the above headers. Is there a way to override the ServiceProvider somehow, or an even cleaner way of doing this?

**Comment by joshhornby** [comment]
@jackmcdade Is there any chance this can be reviewed?

**Comment by jasonvarga** [comment]
Added support for `options` for next release.

**Comment by jasonvarga** [comment]
Oh but adding cache control to the options won't affect existing files on s3. You'll have to go and add those headers through the s3 dashboard. (It can be done in bulk)
