### ISSUE TITLE
setlocale doesn't work on Windows

### ISSUE THREAD

**Issue by vladdu** [statamic/v2-hub#2128]
This is basically a PHP problem, but with an easy workaround in Statamic. Please consider implementing it.

Calling setlocale('sv_SE') only works after the second time. On win10, the call to setlocale('Swedish_Sweden.UTF-8') succeeds from the first try, but having to enter both locale strings when most people don't use windows feels like messier than the workaround of making the call twice in AppServiceProvider.

**Comment by jasonvarga** [comment]
What do you mean "it doesn't work". What's not working? What's in your `locales` array in `system.yaml`?

**Comment by vladdu** [comment]
Sorry, I had described this on Slack and just didn't think that I should do it again here.

If using 'sv_SE' as locale string, the first call to setlocale() returns false (i.e. it fails and the locale remains the original one 'C'), but the second one succeeds and sets the locale.

The Windows locale string looks like 'Swedish_Sweden.UTF-8' and that one works as it should, but if Statamic would have to use both, it all becomes complicated.

So I was wondering if you would have something against implementing the workaround of calling setlocale() twice in AppServiceProvider. It should not create problems on Linux, Unix or OSX.

**Comment by jasonvarga** [comment]
What's in your `locales` array in `system.yaml`?

**Comment by vladdu** [comment]
```
locales:
  sv:
    full: sv_SE
    name: Svenska
    url: /

```

**Comment by jasonvarga** [comment]
Why not put `full: Swedish_Sweden.UTF-8` ?

**Comment by vladdu** [comment]
Because what happens when I deploy to production? More precisely, it is easy to miss it. It could possibly a value be in .env, but I think I tried and it didn't work (don't remember exactly right now).

**Comment by jasonvarga** [comment]
Try the env again. The `full` needs to be whatever is installed on your system.


`full: '{env:SWEDISH_FULL_LOCALE}'`

`SWEDISH_FULL_LOCALE="Swedish_Sweden.UTF-8"`

**Comment by vladdu** [comment]
That worked, thanks! I don't understand why it didn't when I tried it, the only thing I can guess is that I forgot the quotes around the value. 

I will have to make sure I don't overwrite my .env file.

Sorry for the noise.
