### ISSUE TITLE
Generate Asset User folder to Lock Down Assets per User

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#2137]
For Assets, it would be great to setup an asset container with variable images/{{ username }} and when the user tries to upload files and it matches the username it will auto create that folder for them and lock down the files to that user.  I have done this in Craft.

Then we could just setup the Asset contain to upload and delete permissions and they would be locked in per user:

Permissions

![screen shot 2018-08-24 at 12 10 29 pm](https://user-images.githubusercontent.com/2436728/44595405-d1b47e00-a796-11e8-90ab-cb241d897996.png)

Asset Container

![screen shot 2018-08-24 at 12 12 18 pm](https://user-images.githubusercontent.com/2436728/44595455-fa3c7800-a796-11e8-805f-f914905a3e13.png)

**Comment by bgarrant** [comment]
All we do is give them access to that one Asset container in a Role and the rest is automated every time a new user is created.  Pretty slick if we can do it.

**Comment by jackmcdade** [comment]
Will be revisiting this in v3.
