### ISSUE TITLE
FR: 'title' field with different names

### ISSUE THREAD

**Issue by vladdu** [statamic/v2-hub#2138]
For some collections, it is not meaningful to have a "title" field. Maybe it should be "name" or something else. I don't refer to the display name, but to the name of the field to be used in templates.

I propose that the title field is no longer special. Any text field should be possible to mark as "title" (so that the CP manages it like before). In case none is, the current behaviour can be preserved.

**Comment by lukeagsmith** [comment]
You can already name the title field whatever you like and place anywhere is the flow of your fields.

Does this not cover what you need?

**Comment by vladdu** [comment]
You can give it a different display name, but the name still has to be 'title', otherwise how does the CP know to use it when listing the items? So the theme developer has to remember that for this collection, title is name and for that one, title is something else. (In truth, right now I can't come up with another example than 'name')

**Comment by jackmcdade** [comment]
Won't maie this breaking change in v2, but rethinking it for v3.
