### ISSUE TITLE
ErrorException in YAML.php line 68: Array to string conversion

### ISSUE THREAD

**Issue by MattRogowski** [statamic/v2-hub#2140]
**Describe the bug**
When trying to save a collection entry I get the following error:

`ErrorException in YAML.php line 68: Array to string conversion`

I was going through adding posts from my old site, the first 14 were fine, upon adding the 15th I inserted an image in my Bard field, and it errored with the above when trying to save the post. I now can't save any of the other 14 posts either.

**To Reproduce**
All I can give for this is the abive ^

**Expected behavior**
For my post to save :(

**Screenshots**
Can provide the full stack trace if it'd be beneficial

**Environment details (please complete the following information):**
 - Statamic Version: 2.10.4
 - Was a fresh install
- Running on macOS 10.13.3, PHP 7.1

**Additional context**
Nothing additional to add

**Comment by fourstacks** [comment]
I'm getting the same error with a Bard field.  In my case I had no other entries.  To start with my Bard field had one set (single_image) with one field (assets field locked to a single image).  In this configuration, trying to save a new entry or edit an existing one results in the error above.  This occurs whether or not an image is actually inserted into the Bard field.

If the set containing the image field is removed from the bard field configuration the entry saves correctly.

**Comment by fourstacks** [comment]
OK, sorted this one out I think. @MattRogowski, is your bard field called 'content' by any chance?  Mine was and as soon as I changed that to something else ('article' in this instance) the bard field behaved as expected.  Not that surprising really seeing as the Bard field docs tell you not to call your bard field 'content'!

**Comment by MattRogowski** [comment]
@fourstacks So it does! I hadn't noticed that and do believe mine was also called this, and it worked when I renamed mine too.

So, fair enough that it shouldn't be called this, however I'd say it'd be more user friendly to handle this correctly when trying to name the field, i.e. some sort of validation, rather than letting it go through to a PHP error.

**Comment by jackmcdade** [comment]
Not _technically_ a bug here. Not much we can do at this point in v2 around the reserved keyword `content`.
