### ISSUE TITLE
FR: Have `format` and `format_localized` use the same format strings

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#2141]
**Describe the solution you'd like**
`format` uses [these](http://php.net/manual/en/function.date.php) strings while `format_localized` use [different](http://php.net/strftime).

This is confusing for users.

**Comment by vladdu** [comment]
I agree that it is confusing, but those are the formats that PHP's respective funtions use, as the {s} docs also note. I have no idea why the formats are different, but I suppose that a PHP developer should know about them? I think that strftime() is a superset of date(), so maybe only one should be used?

**Comment by jackmcdade** [comment]
Unfortunately there is no way to do that. They're both on the language level with completely different formatting engines and no known adapter between syntaxes. It just is what it is. Yay programming!
