### ISSUE TITLE
JSON output 'FatalErrorException in Container.php line 978:'

### ISSUE THREAD

**Issue by humanjpg** [statamic/v2-hub#2142]
**Describe the bug**
I have a layout and template that spit out JSON. This worked on older versions (can't specify which ones).

```
1/1
FatalErrorException in Local.php line 118:
Maximum execution time of 30 seconds exceeded
in Local.php line 118
```

**To Reproduce**
1. Setup a complex JSON template like this...
```
{{ cache }}

{{ collection:films show_future="true" limit="{ limit }" offset="{ offset }" as="posts" hidden:aint="true" }}
[
{{ posts scope="film" }}
  {
    "id": {{ index }},
    "name": "{{ title }}",
    "outline": "{{ description|safe_truncate:150:... }}",
    "rating": {{ if rating }}"{{ theme:partial src="film/parts/rating" }}"{{ else }}null{{ /if }},
    "year": {{ if year }}{{ year }}{{ else }}null{{ /if }},
    "slug": "{{ slug }}",
    "availability": "{{ if unavailable }}unavailable{{ else }}available{{ /if }}",
    "link": "{{ if unavailable }}{{ url }}{{ else }}{{ link }}?ref=rocumentaries{{ /if }}",
    "url": "{{ url }}",
    "cta": "{{ if unavailable }}Read More{{ else }}Watch Now{{ /if }}",
    "runtime": {{ if length }}{{ length }}{{ else }}null{{ /if }},
    "img": "{{ if cover }}{{ assets:cover }}{{ glide:cover src='{id}' width='250' height='150' fit='crop' quality='80' }}{{ /assets:cover }}{{ else }}{{ sources }}{{ if first }}{{ theme:partial src='film/parts/image' identifier='{ identifier }' film_slug="{ film:slug }" height='350' width='250' fit='crop' quality='80' }}{{ /if }}{{ /sources }}{{ /if }}",
    "genre": [{{ if genres }}{{ relate:genres scope="genres" }}"{{ title }}"{{ theme:partial src="filter/comma" }}{{ /relate:genres }}{{ /if }}],
    "sourceSlug": {{ relate:sources }}{{ if first }}"{{ slug }}"{{ /if }}{{ /relate:sources }},
    "sources": [{{ if sources }}{{ relate:sources }}"{{ title }}"{{ theme:partial src="filter/comma" }}{{ /relate:sources }}{{ /if }}]
  }{{ theme:partial src="filter/comma" }}
{{ /posts }}
]
{{ /collection:films }}

{{ /cache }}
```

(Tried removing the `{{ cache }}` tag, but that just reported the same error at `Arr.php line 63:`)

2. Point a route towards it in `routes.yaml`

```
  /data.json:
    layout: json
    content_type: json
    title: data
```

(Getting the same issue using `content_type: application/javascript` too)

**Expected behavior**
It should output a JSON feed of all the properties specified in the `films` collection

**Environment details (please complete the following information):**
 - Statamic Version 2.10.4, but didn't work on 2.8.3 either
 - OS: Mac OSX 10.13.2
 - Browser: Chrome
 - Web Server: MAMP Apache 4.0.6
 - PHP Version: 7.0.12
 - Addons installed: `CollectionMatch` and `Taxonomy`

**Comment by simonhamp** [comment]
I doubt this is internet connection related, especially if this is all running locally.

It feels like there’s just a lot going on here and it’s taking way longer than the standard script timeout is allowing.

What value are you using for `{ limit }`? And how many records are you expecting for this to loop over and generate JSON for?

Side note: this really looks like the kind of thing that would be better handled in PHP rather than in Antlers, IMHO. Would it be possible to refactor it into an add-on or a [site helper](https://docs.statamic.com/addons/site-helpers)

**Comment by humanjpg** [comment]
Hey @simonhamp, 

Thanks for getting back to me.

The only reason I suspected the internet connection might have an effect, is that I'm gliding external URLs to produce the image thumbnails.

It's a super temperamental piece of code, and I'd love to have it rewritten as an add-on. But that's not something that I'd be able to do sadly :(

The limit is set to `9999` but there are just under 300 items in the collection. Do you think I should set the limit much lower? Or would that not have an impact?

I've actually just run it again this morning and it appears to be working again on older and the latest version of Statamic, so perhaps the net connection did have something to do with it? Or maybe it managed to run once and then save in the cache. 

Regardless it would be good improve it.

**Comment by simonhamp** [comment]
I didn't spot the Glide tags when I looked last night, but if they're fetching external URLs then I'd say it's that for sure.

Although you'd have more control over it if you could write this in pure PHP, I'd guess you'd still have problems from time to time and you'd be better off breaking some of this up rather than trying to do everything all at once in the `{{ collection }}` loop.

Is there any way you can process those images separately and then create this JSON from local resources?

**Comment by humanjpg** [comment]
Hey again,

Thanks for responding again — really appreciate your help.

I'd love to be able to break it up, but I don't know if there's a way to run the glide tags separately and inject them into the JSON, as the JS plugin I'm using then grabs all of the films from the JSON object, so they all have to be in there.

I mean, I'm sure there are a hundred ways of doing it in PHP, but I can't think of a way to do it within Antlers :)

My net connection is more stable now and it's started happening again. I tried commenting out the glide tags and some of the other complex relate tags, and that seemed to help.

---

For full transparency, the deeper problems are:

1. The fact I can't write PHP :(
2. And the fact I'm using a JS plugin (https://github.com/jiren/filter.js) to filter the collection, rather than writing something from scratch / using Statamic + the Algolia driver (which would be way to expensive to justify on a non-monetised side project!)

---

Here it is in production, by the way:

https://rocumentaries.com/filter
https://rocumentaries.com/data.json

**Comment by simonhamp** [comment]
Pop this in a file called `Controller.php` in your `site/helpers` folder:

```
<?php

namespace Statamic\SiteHelpers;

use Statamic\API\Term;
use Statamic\API\Entry;
use Stringy\StaticStringy as Stringy;
use Statamic\Imaging\GlideImageManipulator;
use Statamic\Extend\Controller as AbstractController;

class JsonController extends AbstractController
{
    public function data()
    {
        $offset = request()->get('offset');
        $limit = request()->get('limit');

        $entries = Entry::whereCollection('blog')
            ->entries()
            ->removeUnpublished()
            ->conditions(['hidden:aint' => true])
            ->slice($offset, $limit);

        $items = [];

        /** @var \Statamic\Data\Entries\Entry $entry */
        foreach ($entries as $entry) {;
            // Build the cover image
            /** @var GlideImageManipulator $glide */
            $glide = app(GlideImageManipulator::class);

            $cover = $entry->get('cover')
                ? $glide->item($entry->get('cover'))->width(250)->height(150)->fit('crop')->quality(80)->build()
                : null; // TODO: Figure out the fallback if there is no 'cover' asset

            // Get the genre titles
            $genres = [];

            if ($entry->has('genres')) {
                foreach ($entry->get('genres') as $genre) {
                    $genres[] = Term::whereSlug($genre, 'genres')->get('title');
                }
            }

            // Get the source titles
            $sources = [];

            if ($entry->has('sources')) {
                foreach ($entry->get('sources') as $source) {
                    $sources[] = Term::whereSlug($source, 'sources')->get('title');
                }
            }

            // Build each item
            $items[] = [
               'id' => $entry->id(),
               'name' => $entry->get('title'),
               'outline' => Stringy::safeTruncate($entry->get('description'), 150),
               'rating' => $entry->get('rating'),
               'year' => $entry->get('year'),
               'slug' => $entry->slug(),
               'availability' => $entry->get('unavailable') ? 'unavailable' : 'available',
               'link' => $entry->get('unavailable') ? $entry->url() : $entry->get('link') . '?ref=rocumentaries',
               'url' => $entry->url(),
               'cta' => $entry->get('unavailable') ? 'Read More' : 'Watch Now',
               'runtime' => $entry->get('length'),
               'img' => $cover,
               'genre' => $genres,
               'sourceSlug' => $entry->get('sources') ? Term::whereSlug($entry->get('sources')[0], 'sources')->get('slug') : null,
               'sources' => $sources,
            ];
        }

        return response()->json($items);
    }
}

```

Then add this route in your `site/settings/routes.yaml` under the `routes:` key:

```
routes:
  /data.json: JsonController@data
```

That's the beginnings of your PHP-only solution.

**Comment by humanjpg** [comment]
Wow! Thank you so much, Simon!!

Just taking it for a spin now. It's currently it's only echoing out:

`[ ]`

When I add a value into `$items` where it's declared on line 24, e.g. `$items = ['Hello world']` that echoes out `['Hello world']`.

But when I test changing the value of `'id' = $entry->id(),` to `'id' => 1,` it still echoes out `[ ]`.
 
So presumably, it's something to do with the `$items` not being pushed into the array?

---

(Super conscious of your time, so absolutely feel free to ignore this. You've already been unbelievably helpful!)

**Comment by simonhamp** [comment]
My bad! Change the following line:

```
// Change from...
$entries = Entry::whereCollection('blog')

// To...
$entries = Entry::whereCollection('films')
```

Leftovers from my testing!

**Comment by humanjpg** [comment]
Amazing! That worked :)

The final thing I need to do, is replicate everything and stick the whole JSON object in a JavaScript variable in another file `var movies`. 

(After wrestling with `filter.js` for a long time, I've concluded it works in mysterious ways. The only way I've managed to make it work is using the JSON (data.json) for streaming and loads the JSON on the page in a `<script>` tag and storing it within an object. Crazy, I know.)

I've setup another file `JsController.php` and at the end am trying to do this:

```
$jsonItems = response()->json($items);
return 'var movies = ' . $jsonItems;
```

Unsurprisingly, that didn't work lol. It's returning the JSON but with the header:

```
HTTP/1.0 200 OK
--
  | Cache-Control: no-cache
  | Content-Type:  application/json
```

Which I can't seem to get rid of using `$jsonItems = response()->json($items, 200, [], JSON_UNESCAPED_UNICODE);`

---

And then the last thing I should need is how to add the page to the cache, as the `{{ cache }}` tags I think were helping the JS handle the massive JSON object. 

Honestly please ignore all of this if you're busy / it's complex.

**Comment by simonhamp** [comment]
That sounds quite wild. I’m not familiar with `filter.js`, but I’d be quite surprised if it couldn’t take JSON data directly. That’s usually one of the main goals of such front-end filtering tools. I’ll see if I can get a handle on filter.js.

I won’t go into why your attempt won’t work (for now). Basically to get it to output into a variable in script tags in the rendered HTML you’ll need a template tag that will fetch the same contents that we’re sending back from that `data.json` endpoint. But I’m not sure it’s worth the trouble yet.

Caching shouldn’t be necessary at this point. Let’s worry about that when you’re serving hundreds of requests per minute :) it could cause more trouble than it’s worth at the moment.

Before you move forward with all of this though, the JsonController I made isn’t complete. It really needs to address the case where you’re fetching remote images and passing them through Glide. To sort that out, I really need to see the contents of the partial you’re using to handle that. Depending on your config, it might not be any more stable than your template approach.

**Comment by jackmcdade** [comment]
Closing as this isn't a bug or feature request. Hope it's all sorted though!
