### ISSUE TITLE
How to call collection fieldtype in template file?

### ISSUE THREAD

**Issue by 4kets** [statamic/v2-hub#2143]
The title probably already said it but:

When i set a collection field in the cp, how can i dynamically call the collection in the template file?

screenshots
![image](https://user-images.githubusercontent.com/20043831/44724458-0ac05b80-aad3-11e8-8318-f066c94cfe2b.png)

![image](https://user-images.githubusercontent.com/20043831/44724474-157af080-aad3-11e8-8003-54c639445ee1.png)

is there something like {{ collection }} so that when i change dropdown in the cp it also changes in the template file?

**Comment by jasonvarga** [comment]
`{{ collection :from="foo" }}`

Where `foo` is the field in your screenshot.

The first example on https://docs.statamic.com/tags/collection

**Comment by 4kets** [comment]
I tried that but when i change the dropdown to a different collection it just keeps foo.

**Comment by jasonvarga** [comment]
Did you put a `:` before `from`? That makes it evaluate the parameter.

**Comment by 4kets** [comment]
okey itried that but now when i reload the page i get this:
![image](https://user-images.githubusercontent.com/20043831/44725449-93d89200-aad5-11e8-882e-4c8d428848ae.png)

**Comment by jasonvarga** [comment]
What's your whole template?

**Comment by 4kets** [comment]
i tried to do it whit copying the if type=="" block like i did with "toekomst" i copied it from collection_autos but when i do that i get this error preg_replace(): Compilation failed: regular expression is too large at offset 37755

**Comment by jasonvarga** [comment]
Exactly, the error is saying it's too large. Make a partial for each block in your template.

```
{{ blocks }}
  {{ if type=="about" }}
    {{ partial:blocks/about }}
  {{ /if }}
  {{ if type=="diensten" }}
    {{ partial:blocks/diensten }}
  {{ /if }}
  etc.
{{ /blocks }}
```

or even simpler:

```
{{ blocks }}
  {{ partial src="blocks/{type}" }}
{{ /blocks }}
```

**Comment by 4kets** [comment]
Aah like that. I did not know templates files had a limit, ill will be working with partials now then. thank you
