### ISSUE TITLE
Allow User Roles to limit access to add-ons

### ISSUE THREAD

**Issue by danielfowler** [statamic/v2-hub#2145]
**Is your feature request related to a problem? Please describe.**
I am new to user roles, but I just created one for a user who only has access to edit blog entries. Upon saving, they can see one of my 4 add-ons and click into it, and edit things. Maybe that's a bug on the add-on config, but it also begs a feature request to be able to decide what add-ons, if any, a user role has the ability to manage.

**Describe the solution you'd like**
To be able to decide what add-ons, if any, a user role has the ability to manage.

**Describe alternatives you've considered**
All add-ons hidden/blocked by default except for Super Admin

**Would you be willing to sponsor this feature?**
Meh.

**Comment by jackmcdade** [comment]
Will revisit for v3.
