### ISSUE TITLE
Save Shortcut doesn't work on every page

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/v2-hub#2156]
**Description**
Save shortcut via CMD/CTRL + S doesn't work on every site.

**To Reproduce**
Steps to reproduce the behavior (only on example):
1. Go to 'Settings->Fieldsets'
2. Choose a fieldset
3. Try to save via the shortcut

**Expected behavior**
The shortcut should work on every site in which a save button is present

**Environment details (please complete the following information):**
 - Statamic Version 2.10.4
 - Fresh Install or Upgrade: Fresh
 - OS: Windows 10 1804 / macOS
 - Browser: Chrome/Safari
 - Web Server: Apache/Valet
 - PHP Version: 7.2
 - Addons installed:

**Comment by jackmcdade** [comment]
We know but we can't really fix it in v2. It will be fixed in v3.

https://statamic.slack.com/archives/C6BGDNVDG/p1535727740000100?thread_ts=1535696402.000100&cid=C6BGDNVDG
