### ISSUE TITLE
Installer - no folders in writable permissions list

### ISSUE THREAD

**Issue by struyfv** [statamic/v2-hub#2164]
**Describe the bug**
No folders in the permissions list.

**To Reproduce**

When I go to /installer.php and the sever looks compatible, I click on the blue button to go the the next step. I get the next message: 'The following directories need to be writable:' But no list of directories...

How can I proceed?

Statamic V2
Fresh Install or Upgrade: Install
PHP Version: 7.0.10

**Comment by jackmcdade** [comment]
Just skip it and go manual. It's more fun anyway :) Installer is totally optional. <https://docs.statamic.com/installing#permissions>
