### ISSUE TITLE
Stale Login prompt in Redwood After Conversion to EMail Logins

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#2166]
**Describe the bug**
After doing a `php please convert:email-login` on the default Redwood install of 2.10.4, I notice that the user's frontend login prompt is still "Username" (which doesn't work) rather than "EMail" (which does).

**To Reproduce**
1. Install default Statamic 2.10.4
2. Add a user or two
3. From terminal in root directory, do `php please convert:email-login`
4. Go to Redwood home page
5. Click on "LOG IN" in banner menu
6. Observe prompt is for "Username", not "EMail address"

**Expected behavior**
Expected it would say "EMail address"

**Screenshots**

![redwoodloginpage-sqz](https://user-images.githubusercontent.com/1248937/45270573-d783b200-b46c-11e8-884d-149f0d414650.jpeg)

**Environment details (please complete the following information):**
 - Statamic Version: 2.10.4
 - Fresh Install or Upgrade: Fresh install
 - OS: macOS 10.13.6
 - Browser: any
 - Web Server: Apache/2.4.34 (Unix)
 - PHP Version: PHP 7.2.9
 - Addons installed: none (default install)

**Additional context**

Could be that this is one of those "exercise left to the reader" kind of things, where once you do a conversion from Usernames to EMail Addresses, the dev is expected to comb their code for such references. In which case, OK. However, I thought I'd point this out in case it was supposed to happen auto-magically. (Which I kinda doubt.)

**Comment by jasonvarga** [comment]
We don't update your templates. This is indeed an "exercise left to the reader" thing.
