### ISSUE TITLE
FR: Content Workflow / Split "Save Post" and "Publish Post" Permissions

### ISSUE THREAD

**Issue by peterhicks** [statamic/v2-hub#2167]
**Is your feature request related to a problem? Please describe.**
When working on sites with multiple contributors, it is often important to have varying levels of access when creating and publishing content, so that some users can contribute content but not publish it without it first being reviewed by an editor; whereas other users can publish directly, as now. This functionality should be permission-based so that it can be applied to specific user groups and to specific content types.

**Describe the solution you'd like**
This is a problem that could be solved in multiple ways, with different levels of work involved.

At its most basic, a split permission system like Craft's would solve the problem, which would involve splitting the current "publish post" permission into two – "create post" and "publish post." "Create post" would allow users to create and save posts as drafts, whereas "publish post" would be dependent on the first, and add the ability to mark a post as published.

However, a more intuitive method would be to introduce a complete workflow for publishing posts on top of the above functionality, where "authors" (defined by a permission) get two options when creating a post – "save draft" and "submit for review." The former function would work exactly as it does now, but the latter would be a new status that would mark the post as completed and ready for editorial attention. This could open up some powerful functionality, such as being able to filter posts in the CP that are ready to publish, or even potentially sending notifications to editors once a new post has been published on the dashboard. 

Once a post is marked as submitted for review, "editors" (also defined by a permission) could approve or reject the post, with or without edits – if it is approved, it is either published or scheduled for publication, in the same way that publishing or scheduling a post is done now. If it is rejected, the post  returns to a draft status.

(More advanced functionality, although beyond the scope of this feature request, might be to allow authors to review changes that editors have made to their posts; send the authors a notification when their post is approved/published or rejected/sent back to draft status; and providing a widget for draft, published and upcoming posts in either list or calendar form)

**Describe alternatives you've considered**
After asking in the Statamic Slack channel, it was suggested that implementing multiple content types (for example, "posts" and "post drafts") and a custom button to migrate posts between them could work, although it would require custom add-on development and would quickly become difficult to manage with large numbers of content types. 

**Additional context**
This feature is less meaningful to sites with one user, or multiple "equal" users, but is vital to any site with a clear separation between those who create content and those who publish it, such as in many news and other journalistic organisations, or where content needs to be vetted before going live (such as corporate or enterprise environments). It also allows for the concept of a user who can submit content but is not otherwise trusted, which is a good way to reduce the area for attack if an author's account is compromised.

**Would you be willing to sponsor this feature?**
I probably wouldn't be able to afford to fully sponsor this feature, but I would be open to partially sponsoring it within my means, or at least discussing what such a feature would cost to sponsor.

**Comment by jackmcdade** [comment]
I do understand the value of this, but at this time in the lifecycle for v2 we will not be adding it. Will revisit in v3 with our plans for more granular permissions.
