### ISSUE TITLE
Support disabling cache tags

### ISSUE THREAD

**Issue by alehandrof** [statamic/v2-hub#2181]
I would like to disable cache tags via the config.

I tweaked `statamic/bundles/Cache/CacheTags.php` to allow cache tags to be disabled. It was giving me all sorts of headaches in development.

There was already a placeholder `isEnabled()` function. All it needed to do, for my current purposes, was this:

```
private function isEnabled()
{
    if (! Config::get('caching.cache_tags_disabled')) {
        return true;
    }
}
```

This would need to some changes in the docs and the CP as well, to cover the use of the `cache_tags_disabled` option.

**Comment by rrelmy** [comment]
This has been implemented some time ago.

https://docs.statamic.com/caching#frag-off
