### ISSUE TITLE
Support for Fieldset folders

### ISSUE THREAD

**Issue by aerni90** [statamic/v2-hub#2183]
**Describe the bug**
I work with a lot of fieldset partials organized in subfolders within ```settings/fieldsets```. This works as expected when working directly with the fieldset yaml files. However, fieldsets organized in subfolders don't show up in the control panel. (E.g. when choosing a partial fieldtype in the fieldset builder and trying to add a fieldset as a partial)

**Expected behavior**
It would be great if all fieldsets would show up in the control panel. No matter if they are stored in subfolders or not. Maybe even with a hint in what subfolder they are stored in.

**Environment details:**
Statamic Version 2.10.5

**Comment by jackmcdade** [comment]
This is something we're exploring in v3, but is not supported in v2.
