### ISSUE TITLE
Bard transforms spaces to &nbsp;s when pasting behind them

### ISSUE THREAD

**Issue by sauerbraten** [statamic/v2-hub#2186]
**Describe the bug**
Bard transforms a simple space into a &nbsp; entity when you paste text after the space. "foo " becomes "foo&nbsp;foo" in the DOM when you paste "foo" behind "foo".

**To Reproduce**
1. In an empty Bard field, type "foo"
2. Copy the "foo"
3. Place the cursor behind "foo", hit space, then `Cmd`-`v`
4. Inspect the space between the foos

**Expected behavior**
The space character should not be modified by pasting behind it. The expected outcome is "foo foo" in the DOM.

**Environment details (please complete the following information):**
 - Statamic Version: 2.10.4
 - OS: macOS 10.12.6
 - Browser: Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
Works correctly in Firefox 62.0.

**Comment by jackmcdade** [comment]
This is just `contenteditable` behavior we cannot change, unfortunately.
