### ISSUE TITLE
Using Redis for both cache and session will randomly logout users

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#2190]
**Describe the bug**
Users will randomly be logged out when using the CP with cache and session over Redis.

**To Reproduce**
1. Set session and cache drivers to `redis`.
2. Login with a user.
3. Clear cache and refresh page until user is logged out.

**Expected behavior**
Cache shouldn't affect session data in Redis.

**Environment details (please complete the following information):**
 - Statamic Version: 2.10.5
 - Fresh Install or Upgrade: 2.8.7 -> 2.10.5
 - OS: Alpine Linux 3.8
 - Web Server: nginx
 - PHP Version: 7.2

**Additional context**
Similar fix has been implemented in Laravel 5.7: https://github.com/laravel/laravel/commit/c3b99e971cd9d8213ada259b9f624a8f70ddd57b

**Comment by FrittenKeeZ** [comment]
Switching to the above solution didn't solve everything regarding users being logged out.
Our client has approx. 10 editors active at the same time, so that might affect something as well?

**Comment by FrittenKeeZ** [comment]
Follow up: don't have other sites' cache on the same database as your sessions, as they will be dropped when the database is flushed. The above mentioned fix is still valid for everyone using Redis for sessions.

**Comment by jasonvarga** [comment]
Closing this because of your workaround, and v3 can use Laravel 5.7.
