### ISSUE TITLE
Users fieldset doesn't match CP template

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#2193]
**Describe the bug**
I added a field to the users fieldset but the layout doesn't match the template that is being displayed in the CP.

This is on Statamic 2.10.4.

Fieldset
<img width="1064" alt="user-fieldset" src="https://user-images.githubusercontent.com/1793867/46580137-f36e6b00-c9ba-11e8-9b05-9292af20cad8.png">

CP Template
<img width="1117" alt="user-cp-template" src="https://user-images.githubusercontent.com/1793867/46580144-0c771c00-c9bb-11e8-8ad3-2c515fcd1659.png">

Notice the timezone field in both screenshots, in fieldset it is set to 33% but in the CP template it is showing full width.

**Comment by jackmcdade** [comment]
That's because partials inline the fields _inside_ them. You'd need to set the width on the timezone field inside the timezone partial to accomplish that.
