### ISSUE TITLE
Edited field definition in CP, entry would not display

### ISSUE THREAD

**Issue by deepsurface** [statamic/v2-hub#220]
I created a fieldset with multiple fields through the CP, **entered some data**, and then redefined some of the fields. Specifically, I renamed a grid field in a replicator and added another row to the grid. When I returned to the entry, the spinner animation appeared and kept spinning, probably because some of the data I entered no longer matched the fieldtype definition.

I deleted the data directly from the .md file that was no longer matched to the defined fields and the spinner disappeared.

**Comment by jasonvarga** [comment]
Closing this because it's pretty old. Just say so if you need it reopened.
