### ISSUE TITLE
Field summary breaks when it contains HTML code

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#2202]
Statamic 2.10.7.

Here is the preview of the field in the control panel.

<img width="812" alt="screen shot 2018-10-18 at 4 26 17 pm" src="https://user-images.githubusercontent.com/1793867/47194321-9942a380-d2f2-11e8-803e-088d68aca197.png">

Here are the values in the field (it is a redactor field).

<img width="811" alt="screen shot 2018-10-18 at 4 26 29 pm" src="https://user-images.githubusercontent.com/1793867/47194325-9e9fee00-d2f2-11e8-944f-78f48b551a16.png">

**Comment by jackmcdade** [comment]
If you enable code inspection on that Redactor field, what does your markup look like? I have a hunch here...

**Comment by thestepafter** [comment]
Sorry for the delay, I went in another direction on this so I'm no longer encountering it.
