### ISSUE TITLE
Updates to excluded files made more prominent in changelog

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#2214]
Occasionally, there are changes to Statamic that don't flow through in the automated CP update workflow. What comes to mind are changes to `.htaccess` (or the equivalent with Nginx and IIS) that are helpful or necessary but require manual updates. I'm sure other changes occur to other files too but none come to mind. The problem exists in that these can be missed through human error and that it's a slightly time and download consuming.

**Describe the solution you'd like**
**A**. Could any changes of this kind be made more explicit in the changelog? Ideally, a direct link to the new file (ie `sample.htacess` on GitHub) could be included to speed up the route to copy-n-pasting in the changes. 

**B**. (_NB: in addition to A above_) Is Statamic able to bring in a new file to the correct location (root in the case of `.htaccess`)? If so, could something like `sample-v2.10.7.htaccess` be created?

**Describe alternatives you've considered**
Currently, I go to Statamic.com > Sign-in > Account > Downloads and grab the .zip of the latest build > unzip that > find and open the file > copy-n-paste.

**Comment by jackmcdade** [comment]
We could certainly look at improving the changelog to help with those "best practices" things. 👍 None of those types of changes are _ever_ required though. That would be a breaking change, and would be deferred to major updates (v3).
