### ISSUE TITLE
Cache rebuild command: please rebuild:cache

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#2218]
When deploying changes we need to rebuild the cache when the new container spawns in AWS. Right now we have no control over what triggers the rebuild after calling `please clear:cache`, which often ends in corrupted cache due to multiple users hitting a random page either on the frontend or in Control Panel. When the corruption occurs, they users can't log into CP and the frontend is throwing a fatal error.

**Comment by jasonvarga** [comment]
you could do `php please clear:cache && php please`

**Comment by jackmcdade** [comment]
Closing because 👆 is a super simple solution.

**Comment by FrittenKeeZ** [comment]
Something's not behaving right, even with the above commands.
@jasonvarga with the site content archive I sent you, try to do the following:
1. Run `php please clear:cache && php please > /dev/null 2>&1` - will take about 50 sec
2. Run `php please` - it should appear almost instantly
3. Go to CP and load `/cp/pages` - this will take about 40 sec before pages are shown
4. Run `php please` again - this time it takes about 30 sec

Continuously reloading `/cp/pages` and running `php please` seems to force separate cache rebuild every time, as if the cli and webserver doesn't cache everything properly.
