### ISSUE TITLE
Adding any plugin to redactor duplicates Assets button repeatedly on each redactor fieldtype in the same fieldset

### ISSUE THREAD

**Issue by peimann** [statamic/v2-hub#2219]
**Describe the bug**
I used redactor plugins to extend it, but when I add plugins it causes adding more Assets button to the toolbar. First I thought it is about plugins, but when I removed them the extra assets buttons didn't go! I found out when I add any line to plugins section in redactor settings it causes the issue...

**To Reproduce**
1. Go to 'site/settings/system.yaml'
2. On 'Redactor Settings'
3. Add any line for plugins section for your desired settings (which you chose for your redactor field type), like: 
```yaml
plugins:
  - nothing
```
(save)
4. Go to the page that you are using the redactor field type (at least twice) in its fieldset...
5. You will see the second editor has 2 Assets buttons, third one 3 buttons, 4th one 4 buttons, ...

**Expected behavior**
It has not to duplicate buttons

**Screenshots**
<img width="1048" alt="screen shot 2018-10-26 at 10 53 46 pm" src="https://user-images.githubusercontent.com/40042952/47598701-d8d15580-d9ac-11e8-8cc7-1c68f846e0b5.png">

**Environment details (please complete the following information):**
 - Statamic Version 2.10.7
 - Fresh Install or Upgrade: Fresh
 - OS: macOS 10.14
 - Browser: chrome
 - Web Server: Nginx
 - PHP Version: 7.2
 - Addons installed: nothing OR RedactorPlugins (That has not affect on issue)

**Comment by jasonvarga** [comment]
Neat bug. Fixed for next release.
