### ISSUE TITLE
Redactor's Assets button doesn't work in fullscreen

### ISSUE THREAD

**Issue by peimann** [statamic/v2-hub#2220]
**Describe the bug**
When editing in fullscreen the assets button doesn't work

**To Reproduce**
1. Install RedactorPlugins for Statamic V2 from the marketplace
1.  Use Redactor field type in a fieldset and add plugin fullscreen to its settings 
2. Click on 'fullscreen button
3. Click on Assets button
4. See the error in Console

**Expected behavior**
Assets button should work in fullscreen too

**Screenshots**
![screen shot 2018-10-27 at 9 10 08 pm](https://user-images.githubusercontent.com/40042952/47607490-871cdf80-da2d-11e8-9d57-179740d640b9.png)

**Environment details (please complete the following information):**
 - Statamic Version 2.10.7
 - Fresh Install or Upgrade: Fresh
 - OS: macOS 10.14
 - Browser: Chrome
 - Web Server: Nginx
 - PHP Version: 7.2
 - Addons installed: RedactorPlugins

**Comment by jasonvarga** [comment]
I managed to fix the error, however since Redactor's fullscreen plugin puts itself right before </body>, it sits over the top of the asset selector. There's not a great way around it.

We might revisit this in v3.
