### ISSUE TITLE
Unable to login to cp on iPad with safari

### ISSUE THREAD

**Issue by Hiltsje** [statamic/v2-hub#2221]
When I go to www.website.com/cp on my iPad the page doesn't show the login form. 
Which prohibits users to login to the control panel.

I have tested it on an iPad 2 with IOS 9.3.5 with safari.
It is Statamic version 2.10.7.
PHP version 7.2

![img_0005](https://user-images.githubusercontent.com/13380053/47619210-a292f380-dadc-11e8-8c58-bfe08aa54d80.PNG)

**Comment by jackmcdade** [comment]
I can't recreate this. Do you have any addons installed that might be throwing some kind of js error?

**Comment by jackmcdade** [comment]
This issue has been inactive and in need of more information for a while now. Feel free to reopen and we'd be more than happy to take another look if you have more info that can help!
