### ISSUE TITLE
FR: Or Option in Where Modifier

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/v2-hub#2222]
**Is your feature request related to a problem? Please describe.**
I would like to show multiple types but not all types in a replicator loop.

**Describe the solution you'd like**
I would like the `where` modifier to be expanded to include an `or` such as `{{ replicator_field where='type:text|type:image' }}`

**Describe alternatives you've considered**
A `where_not` modifier would also be good in some cases.

**Additional context**
Getting some but not all types of content in a index list of a collection that has entries with replicators.

**Comment by jcohlmeyer** [comment]
Of course I could use an `{{ if type ...` but I like the `where` better ...

**Comment by jackmcdade** [comment]
This absolutely should be a construct of the `{{ if }}` conditional logic, if only for performance reasons. I don't plan to add more complexity to the `where` the modifier.
