### ISSUE TITLE
Reordering pages should lock other overview actions

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#2230]
**Describe the bug**
During page reordering it's possible to create/delete/duplicate a page, which will void the reordering and do the other action instead. This can fx. lead to pages unintentionally being deleted, as you might think the reordering has been saved before deletion.

**To Reproduce**
1. Go to pages overview.
2. Reorder pages - fx. move children from one page to another. 
3. Initiate delete action on the page the children was moved from.
4. See that the child pages have been removed with their original parent.

**Expected behavior**
Initiating page reordering should prevent any other overview action, until the reordering is saved or the reordering is aborted (by reloading or similar).

**Environment details (please complete the following information):**
 - Statamic Version: 2.10.7

**Comment by jackmcdade** [comment]
Good call. Added for next release.
