### ISSUE TITLE
reorder button disapears when there is a second page in collections

### ISSUE THREAD

**Issue by 4kets** [statamic/v2-hub#2232]
**Describe the bug**
I have order:numeric on the collection but when i have so many entries that the second page comes around then the reorder button goes away. Can i set my entries all on the same page so that the reorder button stays active?

**Comment by jackmcdade** [comment]
The only way around that at this time is to increase your pagination size in the system settings.

![image](https://user-images.githubusercontent.com/44739/47922777-3fafac80-de8e-11e8-9972-bb4f5dcf90ca.png)

**Comment by 4kets** [comment]
ow like that thank you

**Comment by 4kets** [comment]
After i did that the reorder button still does not appear
