### ISSUE TITLE
Long URLs throw an exception with static caching enabled

### ISSUE THREAD

**Issue by jackwakefield** [statamic/v2-hub#2233]
**Describe the bug**
An evildoer ran a vulnerability scanner against one of our Statamic websites with file-based static caching enabled.

This caused requests with exceptionally long URLs to throw an exception when being cached.

**To Reproduce**
1. Enable static caching
```yaml
static_caching_enabled: true
static_caching_type: file
```
2. Visit a very long URL where either:
- the file path of the cached file exceeds `getconf PATH_MAX .`
- the file name of the cached file exceeds `getconf NAME_MAX .`

**Environment details (please complete the following information):**
 - Statamic Version 2.10.7
 - Fresh Install or Upgrade: Upgrade
 - OS: CentOS 7
 - Browser: Chrome
 - Web Server: Nginx
 - PHP Version: 7.2
 - Addons installed: a lot, mostly custom

**Additional context**
```
ErrorException: fopen(/var/www/name/releases/20181102112439/statamic/../static/products/..._a=default1111111111111%20UNION%20SELECT%20CHAR%2845%2C120%2C49%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C50%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C51%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C52%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C53%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C54%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C55%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C56%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C57%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C49%2C48%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C49%2C49%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C49%2C50%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C49%2C51%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C49%2C52%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C49%2C53%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C49%2C54%2C45%2C81%2C45%29%2CCHAR%2845%2C120%2C49%2C55%2C45%2C81%2C45%29%20--%20%20%2F%2A.html): failed to open stream: File name too long
#7 core/StaticCaching/Writer.php(34): handleError
#6 vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): handleError
#5 vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(0): fopen
#4 core/StaticCaching/Writer.php(34): write
#3 core/StaticCaching/FileCacher.php(46): cachePage
#2 core/StaticCaching/Middleware/Cache.php(62): terminate
#1 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): terminate
#0 /var/www/name/releases/20181102112439/index.php(160): null
```

**Comment by jackmcdade** [comment]
Does that crazy super long URL include query params?

**Comment by jackwakefield** [comment]
It does indeed, the URL was similar to
`/products/category/product?variation=default1111111111111%20UNION%20SELECT...`

**Comment by jackmcdade** [comment]
Yeah, honestly I don't think there's anything we can do about it. If the filename is too long for the system to handle, it's too long for the system to handle. Maybe you can try updating your conf to increase that length, but otherwise i think you'll need to turn off static file caching, or ignore query string parameters and build your logic into some JS or something.

**Comment by jackwakefield** [comment]
Taking inspiration from the `@mkdir` above we fixed this with the following, but our custom patch list is growing

**Comment by jackwakefield** [comment]
I could be wrong, and I usually am in the don't-trust-at-face-value world of built-in PHP functions, but `fopen` [should return](https://secure.php.net/manual/en/function.fopen.php) `false` on any error, that error is then thrown as a warning.

Depending on the PHP settings, and if `fopen` isn't suppressed, that could be treated as an error and stop execution, or continue.

If it continue without bailing in the case of `statamic/core/StaticCaching/Writer.php`, it'll hit

```php
if (! flock($handle, LOCK_EX | LOCK_NB)) {
    return false;
}
```

Which would be evaluated as `flock(false, LOCK_EX | LOCK_NB)`.

With the code in the above comment it'll suppress warning/error and then bail by checking if `$handle` is false.

But I also understand the warning/error could be needed to debug an issue. On the other hand, an option to supress would be nice to prevent us needing to patch after updates (as we had roughly 3k Sentry reports this morning :crying_cat_face:).

**Comment by pxwee5** [comment]
This can be easily be fixed by having regex ignore in `caching.yaml` where you can ignore certain url using regex. For example if the request url contains `utm_medium` then don't static cache it, or have a setting to stop caching if url is longer than certain character.

**Comment by rizkysyazuli** [comment]
is this a breaking effect on my site or simply just a warning? Sentry categorizes this as a warning, not an error. What should i do?

I suppose, I can live without static caching. There are other caching strategies we can implement.
