### ISSUE TITLE
Internal link of pages is not possible with Statamic version 2.11

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#2238]
**Describe the bug**
We have spent a week developing code that makes it possible for an editor to create internal page links within Bard. With the new release 2.11 a lot of other reported issues were fixed, but this [extension](https://statamic.com/marketplace/addons/anchor-extension), which has been downloaded by the Statamic dev. community 220+ times, is nullified with version 2.11.
Our biggest issue with this, is that we weren't warned about this breaking change, so we never got a chance to update the extension before 2.11 was released, and now we're stuck on 2.10.7 with the bugs it has.

**To Reproduce**
As you mention in the [changelog](https://statamic.com/changelog#2.11.0):
> Third-party Bard+MediumEditor extensions will need to be rewritten as Scribe plugins (if they aren't already built-in as a new feature).

**Expected behavior**
This functionality should be implemented and maintained in core, as it is functionality expected to exist in any modern CMS.

**Screenshots**
![Anchor Extension](https://user-images.githubusercontent.com/30860678/48200950-fa452080-e360-11e8-84a7-31b934c1b19a.png)

**Environment details (please complete the following information):**
 - Statamic Version: 2.11.2
 - Addons installed: Anchor Extension

**Additional context**
We spent around USD 6,500 developing this feature, so we're not very keen on seeing this being swept away.

**Comment by jackmcdade** [comment]
@FrittenKeeZ, I totally understand and empathize with the situation. I wish we could have had the luxury of an advanced notice on the Bard item, and in hindsight a 2.10.8 + 2.11.0 might have been a good way to soften the breaking change, I wish I had thought of it.

I'll keep the explanation brief -- basically, `MediumEditor` was completely unstable and unfixable, causing data loss for writers in high-profile situations. We had to replace it with something better, and until we had finished and tested with [Scribe](https://github.com/guardian/scribe), we didn't know if that would actually cut it, and if we'd have to start over again with something even more complex, like ProseMirror. Once we confirmed with the affected users it was a satisfactory solution, we immediately shipped it.

Anyway, we're more than willing to take care of this for you. We caused the problem, and we'll provide the solution. We're forking the addon updating it so you keep on rolling. 👍
