### ISSUE TITLE
Localized slug gets deleted while saving a Page

### ISSUE THREAD

**Issue by goldnead** [statamic/v2-hub#2244]
Might be related: https://github.com/statamic/v2-hub/issues/2243 
**Describe the bug**
I have a Page with 6 different locales. Base locale is german.
Slugs of pages can be localized but on re-saving them the localized slug gets deleted and the page defaults on the slug of the base language

**To Reproduce**
1. Install Fresh Statamic (2.11.2)
2. Add a second locale in your system.yaml
3. Edit Slug of the additional locale on an existing page
4. check for updates in the actual File
5. save another time
6. slug gets removed, cp displays the localized slug. Slug removal only gets visible on page-reload

**Expected behavior**
The localized slug must not be deleted if you save the page more than once.

**Environment details (please complete the following information):**
 - Statamic Version 2.11.2
 - Fresh Install
 - OS: Ubuntu 16.04
 - Browser: Chrome
 - Web Server: Nginx
 - PHP Version: 7.1
 - Addons installed: none

**Additional context**
I tested this with different base locales. Makes no difference if you base locale is english or something else.

**Comment by jasonvarga** [comment]
Inside `statamic/core/Data/Pages/Page.php` change line 115 to:

```
if ($slug !== URL::slug($this->defaultUri())) {
```

Let me know if this solves the issue for you.

**Comment by goldnead** [comment]
@jasonvarga I can confirm it does. Thank you!
Would be nice if that fix could be in the next update so those changes won't be overriden if I update.

**Comment by jasonvarga** [comment]
It's in the next update, I just wanted a sanity check before releasing :)
