### ISSUE TITLE
Static site generation in v2

### ISSUE THREAD

**Issue by keenanpayne** [statamic/v2-hub#2246]
**Describe the solution you'd like**
A straightforward and performant way to generate HTML pages from a website that is using Statamic as an underlying CMS. Generation could be accomplished through a command line interface or maybe the Statamic control panel. 

**Describe alternatives you've considered**
We are currently doing this at Asana, but we handle it by making concurrent cURL requests to a server that contains a copy of our website. These requests are made using a large number of EC2 instances. This works fine, but it adds a lot of infrastructural overhead which is more expensive. It is also not very performant for how large our website is and it is currently a bottleneck in quick website deployments. 

**Additional context**
I see this feature as "coming soon" on your website (https://docs.statamic.com/caching#static-generator), so I hate to request a feature that might already be in development. However, I'm curious what the status of static site generation is for Statamic v2 and if it is something that is currently under active development. 

**Would you be willing to sponsor this feature?**
Possibly. I'm not sure what the status of this feature is so I'm not sure if it needs to be sponsored. We are very invested in Statamic at the moment, so perhaps if it is not under active development, I can talk with people here about possible sponsorship.

**Comment by keenanpayne** [comment]
That makes sense - thank you for the response! 

Is there any publically available timeline for Statamic v3 at the moment?

**Comment by jackmcdade** [comment]
<https://v3.statamic.com/faq/when>
