### ISSUE TITLE
CP: the JS variable Statamic.fieldtypeDefaults is always empty (easy to fix)

### ISSUE THREAD

**Issue by marsvogel** [statamic/v2-hub#2249]
**Describe the bug**

In control panel the JS variable Statamic.fieldtypeDefaults is always empty due to a missing inherited variable by reference from the parent scope in `\Statamic\Http\ViewComposers\FieldtypeJsComposer::fieldtypeJs`

Just stumbled upon this, while code diving. In this method there is an _array_ `$defaults` defined outside the scope of an anonymous function. This array gets its assignments in this _anonymous function_ but is _not inherited by reference_. Which leads to an always empty array outside the anonymous function.

Affected Line: statamic/core/Http/ViewComposers/FieldtypeJsComposer.php:38

**Current**
```php
$str = collect($this->repo->fieldtypes()->files())->map(function ($path) {
```

**Should be this**
```php
$str = collect($this->repo->fieldtypes()->files())->map(function ($path) use (&$defaults) {
```

**Environment details**
 - Statamic Version 2.11.2

**Comment by jasonvarga** [comment]
Good catch, thanks!
