### ISSUE TITLE
Using API inside Addon Tests doesn't work as expected

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#2252]
**Describe the bug**
For an Addon Test, I need Statamic's API to create a Collection to test against. Running the code below seems to create an actual Collection in my local project, but is then unable to read it and returns `null`. From what I've understood this is because everything should be tested in memory, which is fine, but then the created Collection should also be placed in memory.

**To Reproduce**

*Simplified Test:*

```php
<?php

use Statamic\API\Collection;
use Statamic\Testing\TestCase;

class ExampleTest extends TestCase
{
    /** @test */
    function can_fetch_a_collection()
    {
        Collection::create('test')->save();

        $this->assertNotNull(Collection::whereHandle('test'));
    }
}
```

**Environment details:**
 - Statamic Version [e.g. 2.11.2]
 - Fresh Install
 - macOS 10.14.1
 - Valet
 - PHP Version: 7.1

**Comment by jasonvarga** [comment]
Actually when I told you to do this in Discord the other day, I was wrong.

In our tests when we want to put something in the cache, we would do it manually.

```
        $collection = \Statamic\API\Collection::create('blog');
        $collection->data(['order' => 'date', 'template' => 'blog/post']);
        $this->app->make(Stache::class)
            ->repo('collections')
            ->setPath('blog', 'collections/blog/folder.yaml')
            ->setItem('blog', $collection);
```

I was thinking of v3, where it's been fixed. Pretty difficult to backport what I've done, though.

**Comment by aryehraber** [comment]
Doh! I misread your snippet... Thanks!

**Comment by jasonvarga** [comment]
Closing because it's solved in v3.

In v3, you'll be able to add a trait to your test class and it'll just disable saving stuff.

```
class MyTestCase extends TestCase {
  use PreventSavingStacheItemsToDisk;

  function test_thing() {
    ...
    $entry->save(); // It won't write anything.
  }
}
```

**Comment by aryehraber** [comment]
Noice, that'll make things much easier!

Your Collection snippet seems to be working, but am not sure how to now "save" entries to that collection. Trying this but unsurprisingly not working as I don't know what I'm doing...  😕 

```php
$entry = Entry::create('post-1')
    ->collection('blog')
    ->date('2018-01-01')
    ->get();

$this->app->make(Stache::class)
    ->repo('entries::blog')
    ->setPath('post-1', 'collections/blog/2018-01-01.post-1.md')
    ->setItem('post-1', $entry);
```
