### ISSUE TITLE
Bard: Pasting lists from other applications should work

### ISSUE THREAD

**Issue by sauerbraten** [statamic/v2-hub#2253]
**Is your feature request related to a problem? Please describe.**
Our end users sometimes paste lists from MS Word into a Bard field. This results in one paragraph per list item, and depending on the browser each paragraph has the list item prefix (e.g. a dot) at the beginning. It would be nice if lists in pasted would be properly formatted as lists after doing so.

**Describe the solution you'd like**
Bard automatically detects list-like paste content and converts it to a `<ul>` or `<ol>`.

**Describe alternatives you've considered**
Until this feature exists, our users will just have to manually combine the resulting paragraphs into one list again.

**Comment by jackmcdade** [comment]
I think the pasting is about as good as we can make it. It'll be better in v3, as you're now aware :)
