### ISSUE TITLE
**Security issue** User password output in clear text in debug mode

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#2264]
**Describe the bug**
A client emailed me my username and password that they had seen in the output of an error page in the format:

`'username' => 'netnak', 'password' => '[my password here]'`

The password was in plain text and not the hash.

Debug mode probably shouldn't have been on, but I don't think passwords should ever make it to screen unencrypted.

**To Reproduce**
It was a bad cache build that just happens sometimes so can't reproduce!  I think the error was about a null array - fixed by clearing cache.

**Comment by jasonvarga** [comment]
Turn off debug mode in production.

**Comment by lukeagsmith** [comment]
Sure. Done. My bad.

But are you happy that this ever outputs?

It means anyone with permissions to toggle that mode can potentially expose passwords which doesn't feel right.

**Comment by jasonvarga** [comment]
Where is it being output? In array of POST data? Sounds about right to me. You typed it, you already know what it is. You're the only one that's going to see that error.

**Comment by lukeagsmith** [comment]
As the the original message "My client emailed me my username and password"!

If I had typed it ok, but it was output in a debug message when they were trying to load a page. No POSTing involved by me or them.

**Comment by jackmcdade** [comment]
Okay, let's work through this. What kind of error output was it? From a tag? A full stop exception? Some tag or something?

**Comment by jasonvarga** [comment]
Sorry, I misread. I assumed you meant the client saw their own password.

We'd like to see the whole stack trace. Perhaps you could find it in your logs.

Try doing a search for `'username' => 'netnak', 'password'`

If you find it, you can obviously redact your password.

**Comment by lukeagsmith** [comment]
Ok, so searching for the password the client sent me gave me a result.

But it turns out not to be my login password! (Apologies, I use a password generator for random passwords so didn't recognise it.)

The password they sent me was the SMTP password from `email.yaml` which has the same username as my login.

Very sorry for the misinformation and good news that unencrypted passwords aren't showing up.

It does make me feel that this info should never get to screen though, would it be feasible to start encrypting the SMTP password?

**Comment by jasonvarga** [comment]
This sort of stuff only appears when you have debug mode enabled. Disable debugging on production and it won’t be there.
