### ISSUE TITLE
Variables like Twig's {% set %} in Antlers

### ISSUE THREAD

**Issue by patrickhoehn** [statamic/v2-hub#2275]
It would be really great if Antlers would feature something like Twigs' `{% set foo = 'bar' %}` to set variables.

I came across some situations where I really missed this functionality and had to spend hours or even days to find a workaround to get what I need

**Comment by jasonvarga** [comment]
Here's a port of the `var` addon from Statamic v1. https://gist.github.com/jasonvarga/75a18bd64e84110a535adfa21f7ccf41

We may revisit this in v3.
