### ISSUE TITLE
Replicator to always show summary

### ISSUE THREAD

**Issue by pxwee5** [statamic/v2-hub#2277]
**Is your feature request related to a problem? Please describe.**
I'd like the replicator to always show summary even when expanded. 

**Describe the solution you'd like**
Just don't hide it even when the replicator item is expanded. If there's a need to differentiate expanded and hidden items, use a + or - button instead.

**Comment by jasonvarga** [comment]
That's a lot of extra clutter on screen. The summaries are there so you know what's in the set at a glance without expanding it. When it's expanded, you can just look at the fields.
