### ISSUE TITLE
Statamic-CLI Breaks when using Redis

### ISSUE THREAD

**Issue by madsem** [statamic/v2-hub#2279]
**Describe the bug**
Cannot run any "php please" commands while redis is running on my local machine inside VM.
When trying to ru ```php please``` commands on my host, it thorws error, but from within the VM I can run the commands.

on my host machine:
Error is thrown:

```bash
[Predis\Connection\ConnectionException]    
  Connection refused [tcp://127.0.0.1:6379] 
```

inside Vagrant:
```bash
vagrant@klever:/vagrant/saratoga$ php please clear:static
Your static page cache is now so very, very empty.
```

But Statamic site is working as expected, and redis also has all the cached data, as expected.
``` bash
127.0.0.1:6379> keys *
 1) "laravel:stache::keys"
 2) "laravel:stache::pagestructure/data"
 3) "laravel:stache::timestamps"
 4) "laravel:stache::assetcontainers/data"
 5) "laravel:stache::users/data"
 6) "laravel:stache::taxonomies/data"
 7) "laravel:stache::config"
 8) "laravel:stache::globals/data"
 9) "laravel:stache::meta"
10) "laravel:stache::usergroups/data"
11) "laravel:stache::pages/data"
12) "laravel:stache::collections/data"
13) "laravel:stache::entries/things/data"
14) "laravel:stache::entries/blog/data"
```

My .env:
```text
APP_ENV=dev

CACHE_DRIVER=redis
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
```

**Expected behavior**
To be able to run ```php please``` commands on my host machine as usual.

**Environment details (please complete the following information):**
 - Statamic Version: 2.11.2
 - OS: Ubuntu 16.04
 - Statamic CLI Tool 1.0.3
 - Web Server: NGINX 1.11
 - PHP Version: 7.2
- Statamic fresh install, only changed to "Bootup" theme
- Vagrant 2.1.2

**Comment by jasonvarga** [comment]
That's just how Vagrant works.

If you run `php` from your host, it's running your host's php instance. 127.0.0.1 from your host is _not_ your Vagrant's 127.0.0.1.

Take a look at this. https://www.calebwoods.com/2015/05/05/vagrant-guest-commands/

**Comment by madsem** [comment]
lol! yeah... it all makes sense now, thanks Jason. Also for the link, this is a really neat way of being able to run it from my host.
