### ISSUE TITLE
While cache is disabled, it might still read from the static folder

### ISSUE THREAD

**Issue by sweebee** [statamic/v2-hub#2281]
**Describe the bug**
If you disable all the cache and do a php please cache:clear, it doesn't do anything with the static generated html files in the static folder. When viewing your site, it still renders the static files even when disabled the cache.

**To Reproduce**
enable static cache, view some pages, disable static cache and change something on the page with the CP, it still shows the cached page untill you clear the static folder

**Expected behavior**
clear the static folder when clearing cache or don't use these files when static cache is disabled

**Environment details (please complete the following information):**
 - Statamic Version 2.11.1
 - Browser: Chrome
 - Web Server: Apache
 - PHP Version: 7.1

**Comment by wanze** [comment]
There is the `php please clear:static` command to clear the static cache.

Note: If you are using the `file` cache type, you should run this command _before_ disabling the cache or the static HTML files won't get deleted and the reverse proxy still displays a cached version. Reason is that the command does only clear the files of the current active `Cacher` service. If the cache is disabled, this is an instance of `Statamic\StaticCaching\ApplicationCacher`, with the cache type set to `file` it would be `Statamic\StaticCaching\FileCacher`.

**Comment by jackmcdade** [comment]
That is expected behavior. `clear:static` is the command you're looking for. Simply disabling the cache shouldn't trigger a full static wipe - if your site is very large that could be an expensive operation.
