### ISSUE TITLE
YAML Front Matter not properly detected and showing in plain text since it's using PHP_EOL to check for line breaks

### ISSUE THREAD

**Issue by chielteuben** [statamic/v2-hub#2282]
I'd like to point you to `statamic\core\API\Parse.php` line `61` (within the `frontMatter` method):  

This is the current line of code used to check if a template contains Front Matter:  
`if (Str::startsWith($string, "---".PHP_EOL)) {`  
  
The problem is that PHP_EOL is not sufficient to check for line breaks since it's not so much related to the current platform but related to the editor the file was created with.  
  
This results in templates simply showing Front Matter in plain text to the client when a file was created with an editor that uses CRLF for linebreaks and is served from a Linux server and the same thing happens when the file uses LF for linebreaks and is served from a Windows server.  
We have to check for all variations of line breaks.  
  
Using something like this instead would solve the issue:  
`if (preg_match('/^---(?>\r\n|\n|\r)/', $string)) {`

**Comment by edalzell** [comment]
This is why I couldn't get YAML front matter to work on my Windows 10 machine

**Comment by chielteuben** [comment]
I would like to add that this is also a security risk since it could expose sensitive information to the client.  
An obvious example is when using protect to protect content. This would be completely ignored in the previously described scenarios and simply give the user access to the content (it would also show the passwords when using the password scheme and the allowed ip_addresses when using the ip_address scheme).
