### ISSUE TITLE
Addon Asset URLs aren't generated correctly using $this->js->url()/tag()

### ISSUE THREAD

**Issue by madsem** [statamic/v2-hub#2285]
**Describe the bug**
Using ```return $this->js->url('jquery.rateyo.min.js');``` in my AddonTags.php,
results in a wrong url on the site: ```/_resources/addons/Ratings/js/jquery.rateyo.min.js```

My addon assets are located in: ```site/addons/Addon/resources/assets/js/jquery.rateyo.min.js```
The same happens for css files, and also using the tag() method.

**Expected behavior**
Receive a url / tag like: ```site/addons/Addon/resources/assets/js/jquery.rateyo.min.js```

**Screenshots**
![screen shot 2018-12-06 at 2 22 41 pm](https://user-images.githubusercontent.com/3166991/49586795-6e73e380-f962-11e8-9186-5f577a9d0d96.png)

**Environment details (please complete the following information):**
 - Statamic Version 2.11.3
 - Fresh Install
 - OS: Ubuntu 16.04
 - Web Server: NGINX 1.11
 - PHP Version: 7.2

**Comment by jackmcdade** [comment]
That's the correct URL - since the `site` directory can be placed above webroot, all asset URLs need to be routed through index.php (using the `_resources` route) to make sure they're rendered.

**Comment by madsem** [comment]
I’m sorry, but they aren’t rendering, getting 404’s for these files on a fresh install.

Are there additional steps required for addons to move the assets to another location? Because the way described above returns not found.

Also tried other plugins from the marketplace like Highlighting, same result with a 404.

What am I missing then? :)

**Comment by madsem** [comment]
Ok, tracked it down to a faulty Nginx config :) my bad! Sorry about the fuss

**Comment by jackmcdade** [comment]
Woo! Glad you're set.
