### ISSUE TITLE
More features for partial fieldsets

### ISSUE THREAD

**Issue by patrickhoehn** [statamic/v2-hub#2307]
I like using partial field sets and nesting them. For example having one field set for defining buttons with internal, external links or links to a collection entry and use that in other field sets, so if I have to make changes, I just have to make them once.

My first wish here is having the possibility to exclude fields from the selected partial. Maybe, if the field set does not require external links, I can load my links field set with a partial and have a way to hide the external link field there.

The second is making conditionals work in nested field sets (partials, bard, replicator) so I can structure my field sets more user friendly. Some field sets are ending up in a mess with a lot unused fields which I would hide if they weren't nested.

I understand, that it won't happen for v2, but maybe in v3?

**Comment by jackmcdade** [comment]
Some of it definitely, and other bits of it, perhaps v3!
