### ISSUE TITLE
FR: Relate max_items should not enforce a select menu

### ISSUE THREAD

**Issue by madsem** [statamic/v2-hub#2310]
**Is your feature request related to a problem? Please describe.**
I can already see that I/my writers will be highly frustrated when having to scroll through a select field with hundreds+ of entries.

##### What where, why?
Because the `Relate` field type, forces a select field on the user when max_items = 1.

**Describe the solution you'd like**
Oftentimes I imagine that only one relation is supposed to be created, for example when writing a review about a product... So a select field makes not much sense when there is a collection of hundreds, potentially thousands of products.

So the best solution IMHO would be to simply not enforce a select field.
Either remove this entirely or make it optional through `mode: select`

**Describe alternatives you've considered**
Labeling the tag version of the field with "Please, please select only a single one".
But I'm pretty sure that non-technical folk won't really listen to my plea.

**Comment by jasonvarga** [comment]
It's a select, yes, but you can type into it to search for items.

![](https://d.pr/i/KfEybr+)

Does the search not work for you?

**Comment by madsem** [comment]
I’ve solved this by creating a true auto suggest field type that only delivers suggestions from server based on term.

When writing this, I didn’t realize that the Relate field loads everything on pageload and builds it’s suggestions client side.
