### ISSUE TITLE
form:submissions sort is case-sensitive

### ISSUE THREAD

**Issue by BriceG-D** [statamic/v2-hub#2316]
{{ form:submissions in="anmeldung"  as='entry' }}
{{ entry sort="company-name:asc|company-location:asc"}}
{{ company-name }}
 {{ /entry }}
{{ /form:submissions }}

the strings are sorted but case-sensitive which is wrong imo

**Environment details (please complete the following information):**
 - Statamic 2.11.2

**Comment by jasonvarga** [comment]
Instead of sorting the `entry` array, sort on the tag itself.

The submission tag supports the mult-var pipe syntax, the one used on standard variables does not.

```
{{ form:submissions in="anmeldung" as='entry' sort="company-name:asc|company-location:asc" }}
  {{ entry }}
    {{ company-name }}
  {{ /entry }}
{{ /form:submissions }}
```

However there's an error that will occur when you do that, which is fixed for 2.11.11.
