### ISSUE TITLE
FR: Abstract image manipulation to not be Glide exclusive

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#2321]
**Is your feature request related to a problem? Please describe.**
Having 3000+ images puts a lot of stress on a server, when it has to generate image presets.

**Describe the solution you'd like**
An abstraction of image manipulation provider, to allow for use of external services like Imgix, Cloudinary or Cloudimage.

**Describe alternatives you've considered**
It's quite possible to build an addon which uses one of the above mentioned services instead of Glide in the frontend, but Control Panel will still use Glide which seem counter intuitive if you pay a lot of money for an external service.

**Additional context**
Combined with S3 storage, this would result in all image handling is done externally, thus freeing up the server to do other tasks.

**Would you be willing to sponsor this feature?**
We are already planning to make an addon, once we've decided which external service offers the best solution for us.

**Comment by jackmcdade** [comment]
An abstracted image manipulation library feature would be a large amount of work for no additional benefit until there were at least two implementations. As it stands right now, Imgix already has a Statamic addon, and I haven't looked at Cloudinary or Cloudimage. We will revisit this in v3, but at this time we will not be adding this in v2 as a native feature.

**Comment by FrittenKeeZ** [comment]
That's totally fine, but then it would at least be nice to turn off image preset auto-generation on upload, so you won't get bloated Glide assets you don't need and only takes up valuable space.

Regarding the Imgix addon, it hasn't been updated in several years and doesn't support image presets, so I'd have to build that anyway.

**Comment by jackmcdade** [comment]
@FrittenKeeZ if you open a FR for disabling preset-autogeneration, I think we can accommodate it. Alternatively, your addon could have it's own preset definition setting instead of piggybacking on the native behavior.

**Comment by jasonvarga** [comment]
@FrittenKeeZ You can rebind it to a dummy class to prevent it happening.

```php
<?php

namespace Statamic\Addons\PreventGeneratingPresets;

use Statamic\Extend\ServiceProvider;
use Statamic\Listeners\GeneratePresetImageManipulations;

class PreventGeneratingPresetsServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->app->bind(GeneratePresetImageManipulations::class, PreventGeneratingPresets::class);
    }
}
```

``` php
<?php

namespace Statamic\Addons\PreventGeneratingPresets;

class PreventGeneratingPresets
{
    public function handle()
    {
        // Don't.
    }
}
```
