### ISSUE TITLE
FR: Option to turn off image present auto-generation

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#2322]
**Is your feature request related to a problem? Please describe.**
If you have 3000+ images and 6 image presets, but don't use all presets for every image, you end up using a lot more storage than necessary.

**Describe the solution you'd like**
An option to turn off image preset auto-generation, so an image preset is only created when needed.

**Describe alternatives you've considered**
A small addon which disables preset auto-generation.

**Comment by jasonvarga** [comment]
Workaround outlined in https://github.com/statamic/v2-hub/issues/2321#issuecomment-451973872

**Comment by jasonvarga** [comment]
Also, added an option to 2.11.4.

Add `image_manipulation_presets_generate_on_upload: false` to assets.yaml
