### ISSUE TITLE
Using re-order on a numerical collection produces inverted results if collection's default sort isn't ASC

### ISSUE THREAD

**Issue by timichango** [statamic/v2-hub#2324]
**Describe the bug**
I have a numerically-ordered collection. In folder.yaml, I've got `sort_dir: desc` applied. 

When re-ordering using the `reorder` interface in CP — now that my default sort is inverted — the `reorder` interface doesn't produce the results you'd expect, since it doesn't appear to take into account the sort that's already applied. 

Put another way: if my &#35;<span></span>14 entry  (out of 14 entries) is shown in the top position, thanks to the desc. sort, and then I click `reorder`, doing any reordering (or, actually, no reordering at all), and then clicking 'save order', causes the reorder behaviour to effectively invert the currently displayed order, re-saving each entry with the correspondingly inverted number in sequence — *&#35;<span></span>14 becomes &#35;<span></span>1*, and so-on. 

If I subsequently click re-order again (with the `desc` default sort), and re-save the order, it once again inverts. Ad-infinitum.

**To Reproduce**

0. Add `sort_dir: desc` to the folder.yaml for a numerically ordered collection
1. Go to the **cp** view for that collection
2. Click on reorder
3. Click on save order
4. Watch with wonder as the sequence of entries gets inverted before thine eye-orbs
5. Click on reorder again / click on save order again / behold another inversion of reality

**Expected behavior**
Seems that the 're-order' interface assumes that whatever's in visual position 1,2,3,etc. should get the order number 1,2,3,etc. — rather than getting an order number based on its relative numerical sequence to the adjacent entries, and/or the sort being displayed. Ideally, reordering should be context-sensitive to the order/sort that's displayed when `reorder` is invoked, and make ordering adjustments **relative** to that state, rather than in an ascending numerical order based on absolute visual position (eg. if the current sort is `desc`, then reordering enumeration should reflect this).

At present, having a descending default order for a numerical collection makes reordering extremely difficult (or at least requires some significant reording acrobatics on the part of the user).

**Screenshots**
n/a

**Environment details (please complete the following information):**
 - Statamic Version **2.11.4**
 - Fresh Install or Upgrade: **upgrade from 2.11.3**
 - OS: **macOS 10.13.6**
 - Browser: **chrome**
 - Web Server: **valet**
 - PHP Version: **PHP 7.2**
 - Addons installed: **Spock, CacheManager, Sally**

**Additional context**
This issue makes me wonder if the same/similar behaviour is reproducible with `pages` as well — but I haven't explored this yet.

**Comment by timichango** [comment]
Accidentally closed — now repoened.

**Comment by timichango** [comment]
Further observations: this isn't relegated to happening with an overridden default sort, it seems — if I comment out my `desc` sorting parameter in `folder.yaml`, refresh, and then manually invert the order sort to `desc` (I've got an `order` column set in `folder.yaml`), then click **reorder**, then **save order**, the same behaviour is observed. 

Similarly, sorting by `title`, and then enacting the same **reorder/save order** routine, causes the entries to all wind up enumerated alphabetically, in whatever sort direction (`asc`/`desc`) the `title` sort was applied. Which is mildly bonkers.

**Comment by jasonvarga** [comment]
For next release, when you click "reorder", the items will first be sorted by the order key so you will see the real order. Sorting by column headers will be disabled while in reorder mode.
