### ISSUE TITLE
Adjusting Slugify treatment of apostrophes

### ISSUE THREAD

**Issue by Samus4145** [statamic/v2-hub#2332]
**Is your feature request related to a problem? Please describe.**

Looking to have a global setting for the site to ensure that the slug created from the title ignores apostrophes instead of adding an additional hyphen.

Example: Joe's Apartment should be joes-apartment instead of joe-s-apartment

**Describe the solution you'd like**
Add a global option to have specific characters ignored on slug creation

**Comment by jasonvarga** [comment]
I wonder why it does that. Seems like a weird decision. 🤔

**Comment by Samus4145** [comment]
Right? Same with periods, so if the title is Worms W.M.D. it adds hyphens instead of just removing the character in the slug, "worms-w-m-d" Gross!

**Comment by jackmcdade** [comment]
Nice one. Updated for next release.

**Comment by jackmcdade** [comment]
Leaving the periods though - they're 100% valid in a URL. E.g. `changelog/statamic-2.11.7`.

**Comment by Samus4145** [comment]
That works!
