### ISSUE TITLE
Separate fieldsets (yield from subfolder in fieldsets dir)

### ISSUE THREAD

**Issue by alexanderhofstaetter** [statamic/v2-hub#2333]
**Is your feature request related to a problem? Please describe.**
I have to many fieldsets in my installation. I wand to _group_ / _separate_ / _tag_ them somehow to have a better overview and get a chaos. I want to archieve a separation between global, entry and page fieldsets.

**Describe the solution you'd like**
I would love to see a system for separating my fieldsets. The simplest way would be to store them in sub directories in die `fieldsets` dir. All fieldsets (no matter which subfolder) will be shown in the ControlPanel UI but are separated in the underlying system.

Taking all `yaml` files in alle subdirectories would not required much changes in my eyes.

**Comment by jasonvarga** [comment]
In v3 you will be able to place fieldsets in whatever subdirectories you like.
