### ISSUE TITLE
Glide tag parameters does not work with modifiers

### ISSUE THREAD

**Issue by dorra** [statamic/v2-hub#2334]
**Describe the bug**
The glide tag does not process parameters which are altered by modifiers. Like {200 | add: 10}

**To Reproduce**
`{{ glide:image width="300" height="{200 | add: 10}" fit="crop" filter="sepia" }}
`

**Expected behavior**
`/img/assets/food/bacon.jpg?w=300&h=210&fit=crop&filt=sepia&s=3982hf983f2mf90r23
`

**Bug:**
`/img/assets/food/bacon.jpg?w=300&h=&fit=crop&filt=sepia&s=3982hf983f2mf90r23
`

**Comment by jackmcdade** [comment]
Modifiers inside parameters are not a supported feature. It's not a Glide-only thing.
