### ISSUE TITLE
[BUG] Collection Fieldtype allows selection of unpublished Entries

### ISSUE THREAD

**Issue by goldnead** [statamic/v2-hub#2335]
**Describe the bug**
The Collection Fieldtype allows the user to select any kind fo entry. Entries, that are marked as unpublished/drafts are shown which breaks any normal relation tags because drafts are automatically excluded.

**To Reproduce**
1. Save a collection Entry as draft
2. create a collection Fieldtype which is assigned to the Collection in which the draft is located
3. try to select the draft in the CP.

**Expected behavior**
Drafts should automatically be excluded from any relational fieldtype.

**Environment details (please complete the following information):**
 - Statamic Version [e.g. 2.11.6]
 - Fresh Install
 - OS: Ubuntu 16.04
 - Browser: chrome
 - Web Server: Nginx on laravel homestead
 - PHP Version:7.1

**Comment by jasonvarga** [comment]
What's broken? Drafts are not displayed by default, but if you want them to be shown, add `show_unpublished="true"` to your `relate` tag.

I don't see why you should be stopped from selecting draft entries.

**Comment by goldnead** [comment]
Well but I don't want to show drafts in my `relate` tag. I'm sorry if my problem wasn't clear enough.
If I limit the fieldtype so that the user can only select 4 entries - in this example it's a set of featured articles which expects exactly 4 items - and the user selects an unpublished entry the featured-article module would be broken because there are only 3 valid entries to be shown.
Maybe it's not exactly an issue that unpublished entries can be selected but in the relate fieldtype those are displayed the same way so the user can't see if the entry is published or not.

If I think about it it's maybe more of a feature request than a bug. It would be nice if drafts would have an indicator or would be greyed out to see that they are actually not published.

<img width="1626" alt="bildschirmfoto 2019-01-24 um 10 27 34" src="https://user-images.githubusercontent.com/1313348/51668711-1c932580-1fc3-11e9-8889-2db748cfcbb0.png">
