### ISSUE TITLE
User unable to change password in control panel

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#2338]
**Describe the bug**

**To Reproduce**
1. Login as a user with access to the Control Panel but not access to View Users. 
2. Try to change password and get an access denied message.

**Expected behavior**
Expect to be able to reset password.

**Screenshots**
<img width="1125" alt="access-denied-user-password-reset" src="https://user-images.githubusercontent.com/1793867/51629214-1a5d9800-1eeb-11e9-9022-3ec971d0a53c.png">

**Environment details (please complete the following information):**
 - Statamic Version: 2.11.6
 - Fresh Install or Upgrade: Upgrade
 - OS: Ubuntu and OSX
 - Browser: Various
 - Web Server: Various
 - PHP Version: Various
 - Addons installed: N/A

**Additional context**
N/A

**Comment by jasonvarga** [comment]
Just to clarify, the password **is** being updated.

But, it was trying to redirect you to the users index, which if you didn't have permission to view users, you'd get the access denied error for that.

Fixed for next release. It'll just keep you on the same page.

**Comment by thestepafter** [comment]
Wonderful, thank you!
