### ISSUE TITLE
`Search::update` isn't the same as updating from CLI

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#2341]
**Describe the bug**
`Search::update` does **not** update all the indexes.

**To Reproduce**
1. Install PowerTools
2. Click Update Search Index
3. Try a search

**Expected behaviour**
Search now works.

**Additional context**
The CLI calls this code:
```
        foreach ($this->getIndexes() as $index) {
            $this->line("Updating <comment>{$index}</comment> index...");
            foreach (Config::getLocales() as $locale) {
                Search::in($index, $locale)->update();
            }
        }
```

Whereas `Search::update()` is only:
```
       $this->index($index, $locale)->update();
```

where the index and locale are both null.

I believe the default behaviour should be to update all indexes.

**Comment by jasonvarga** [comment]
Any methods called on Search:: will apply to the default index.

If you run the `search:update` command, it will only update the default index. You have to add `--all` to update them all.

You can update your code to the following to update all indexes.

```
Search::indexes()->each(function ($index) {
  $index->update();
});
```
