### ISSUE TITLE
{{ theme }} tag 'absolute' attribute doesn't appear to work

### ISSUE THREAD

**Issue by simonhamp** [statamic/v2-hub#2342]
**Describe the bug**
I'm overriding the reset password email template in my theme and am trying to use a reference to a theme file (e.g. the logo) by using the following, assuming that this will interpret an **absolute** URI into the `<img>` tag.

```html
<img src="{{ theme:images src="logo.png" absolute="true" }}">
```

However, the URL in the compiled view contains only a relative URI.

I see this in statamic/bundles/Theme/ThemeTags.php:198:
```php
if (! $this->getBool('absolute')) {
    $url = URL::makeRelative($url);
}
```

But the URL is already relative.

**Expected behavior**
An **absolute** URI.

**Environment details (please complete the following information):**
 - Statamic Version: 2.11.9
 - Upgrade
 - OS: macOS 10.14.2
 - Web Server: Valet
 - PHP Version: 7.3

**Additional notes**
I can fix it by patching it with the following code (haven't checked if this side-effects anything else yet):

```php
if ($this->getBool('absolute')) {
    $url = URL::makeAbsolute($url);
} else {
    $url = URL::makeRelative($url);
}
```

**Comment by hmalaud** [comment]
Sorry to comment on a closed issue, but it seems to have broken relative paths: now `{{ theme:asset }}` always outputs the absolute path (https://.../site/themes/{theme}), and forcing the parameter `absolute="false"` does not seem to work either.

**Comment by EnricoSottile** [comment]
I have the same issue

**Comment by notasausage** [comment]
Yes, I'm seeing this too. Using `{{ theme:asset src="images/wave.gif" }}` outputs a full, absolute URL to the image rather than a relative one. Same with `{{ theme:images src='wave.gif' }}` and if I try adding in the `absolute='false'` parameter.

**Comment by sebszocinski** [comment]
This is still broken in v2.11.14

**Comment by williamjulianvicary** [comment]
This is still broken in v2.11.20.

The prepend is being added to all URLs:
```        
$url = URL::prependSiteUrl(
            $url,
            $this->get('locale', default_locale()),
            false
        );
```

Then it's checking whether it should be made absolute:
```
        if ($this->getBool('absolute')) {
            $url = URL::makeAbsolute($url);
        }
```

At no point is there (currently) an option to make this relative.

Edit: If you're finding you need your assets to be relative, and not absolute - modify the locales settings to remove the absolute URL, for example (site/settings/system.yaml):
```
locales:
  en:
    full: en_US
    name: English
    url: /
```
