### ISSUE TITLE
FR: allow sqlite db location to be set in .env.

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#2343]
**Is your feature request related to a problem? Please describe.**
Making an addon that uses a local sqlite db. Statamic will only "find" the db if it's in a hardcoded location, namely `'database' => storage_path().'/database.sqlite',`

**Describe the solution you'd like**
I'd like to be able to set the location, as the `local` directory is outside the `site` folder and often wiped.

**Describe alternatives you've considered**
Made a Service Provider and hacked this in:
```
        app('config')->set(
            'database.connections.sqlite.database',
            Path::assemble(site_storage_path(), 'database.sqlite')
        );
```

**Would you be willing to sponsor this feature?**
Nope

**Comment by jasonvarga** [comment]
That's a good workaround for v2. 👍 In v3 you can just edit the config.
