### ISSUE TITLE
Conditional logic on a grid fieldset (global)

### ISSUE THREAD

**Issue by alexanderhofstaetter** [statamic/v2-hub#2349]
**Describe the bug**
I wanted to use a [condition](https://docs.statamic.com/conditions) while in the loop of an grid fieldset in a global.

```
{{ footer_settings:social_media id_slug:is='facebook' }}
    {{ text }}
{{ /footer_settings:social_media }}`
```

I dont know if its not supposed to work or if its a bug. However, i would like to use a condition on an array tag. Or maybe there is another possibility to retrieve a grid element by the value of one containing field.

**Comment by jasonvarga** [comment]
Try the where modifier. https://docs.statamic.com/modifiers/where

The conditions you tried to use are for the collection tag.
