### ISSUE TITLE
Installer does not work

### ISSUE THREAD

**Issue by dslpp056193** [statamic/v2-hub#2351]
**Screenshots**
![image](https://user-images.githubusercontent.com/11080873/52657374-6e5b0b80-2ef0-11e9-9734-a6d5a7dc1c84.png)
![image](https://user-images.githubusercontent.com/11080873/52657391-79ae3700-2ef0-11e9-9aac-7045d04f4e2c.png)

**To Reproduce**
1. Just unzip in domain folder

**Environment details (please complete the following information):**
 - Statamic Version [e.g. 2.8.12]
 - Fresh Install or Upgrade:
 - OS: windows 10
 - Web Server: Apache PHP 7 Nginx 1.12
 - PHP Version: 7.1 x64

**Comment by jackmcdade** [comment]
It looks like you don't have your mod rewrite setup. Are you using Apache or Nginx (you can't be using both).

**Comment by dslpp056193** [comment]
I use openserver:
![image](https://user-images.githubusercontent.com/11080873/52659637-ac0e6300-2ef5-11e9-8686-8dbe7a1e7bb0.png)
And all works fine at front page, all images loads (it says that .htaccess is working):
![image](https://user-images.githubusercontent.com/11080873/52659713-dfe98880-2ef5-11e9-8ecf-257a0d8adef5.png)

**Comment by jackmcdade** [comment]
`.htaccess` might be working but `mod_rewrite` may still be disabled. Once you get that working, the rest should follow.
