### ISSUE TITLE
CP search feature doesn't search all fields

### ISSUE THREAD

**Issue by lardnicus** [statamic/v2-hub#2352]
CP search in collections doesn't seem to search anything except titles.

1. Go to the CP area for a collection with multiple fields
2. Enter text that is found in one or more entries, but not in the title field

**Expected behavior**
A list of items in the collection that contain the search text

**Environment details (please complete the following information):**
 - Statamic Version 2.11.9
 - Fresh Install or Upgrade: fresh
 - Addons installed: none

**Additional context**
I've tried adding additional fields to the columns: option in the folder.yaml, which lets me filter but not search.

There is a potential additional consideration in the form of collections within the entries, ie: to display a collection in the columns: of folder.yaml, you put something like  - artist.title to get the title. It would be nice to be able to search those as well (or at the very least, anything that is specified in the columns)

**Comment by jasonvarga** [comment]
If you create a search index for that collection, it'll use that, which includes all the fields you mark as searchable.

https://docs.statamic.com/search#collection-indexes

If you don't have an index, it just does a basic search on the titles.
