### ISSUE TITLE
FR: Ability to change default environment setting

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#2355]
**Is your feature request related to a problem? Please describe.**
Ideally we would be able to change the default environment from `production` to something else. For example, I have 10 people on my team and until we create a `.env` everyone is working in `production`. Because of this `production` has become our default `development` environment even though it is called `production`. This means that we have had to use `live` as our `production` environment name.

**Describe the solution you'd like**
The ability to change the default environment in the control panel.

**Describe alternatives you've considered**
We use `live` for our `production` environment and `production` as our development environment name.

**Would you be willing to sponsor this feature?**
It depends on the cost.

**Comment by jackmcdade** [comment]
This is not best practice. Every developer should set their `.env` file as part of the onboarding process for the project. `production` is the standard default (e.g. unset) environment, and I don't want to change this behavior, it would throw thousands of people (and sites) off.

**Comment by thestepafter** [comment]
I'm not asking you to change the standard behavior, just asking for a way to control the behavior in the control panel or even just a YAML file.

You can still default to production, just give a way to override it. Just because it's standard behavior doesn't mean everyone is going to follow it. This is a way to prevent issues occurring because if someone doesn't setup the .env and makes a change Spock is going to fire and a bunch of other negative things could happen

Assuming production by default is just asking for problems when someone downloads a project and starts working in it.

**Comment by jackmcdade** [comment]
Fair enough! I get it now. Here's all you'll need to do to change the default environment in the next Statamic update:

![image](https://user-images.githubusercontent.com/44739/53183622-a5ed4600-35c9-11e9-8725-4f6245334bcc.png)

**Comment by thestepafter** [comment]
This is wonderful, thank you!
