### ISSUE TITLE
[BUG] CP Navigation doesn't show active state correctly

### ISSUE THREAD

**Issue by goldnead** [statamic/v2-hub#2356]
**Describe the bug**
On our setup, a strange issue is occuring since we did our latest major statamic update from 2.8.11 to 2.11.9:
Navigation-Elements won't get an active state on visiting Pages in the Control-Panel which makes navigating through the CMS tricky since subnavigation isn't shown either. I did some digging and found a possible cause for that error and reported it in a [thread in the statamic lodge](https://statamic.com/forum/3808-cp-settings-menu-not-expanding).

**To Reproduce**
Well, that's the tricky part...
Our setup is very specific. Our client already had a setup running so the site we were developing uses a CDN (CloudFront). CloudFront manages the domain requests and also securing them via ssl. The request to our server though isn't made through a secured (i assume), because a dump of the `$_SERVER` var shows, that https isn't turned on although the site is requested via https through the browser.
I know that doesn't seem like the best setup, since the Requests the CDN makes aren't secured but hosting and DNS/CDN-Stuff is managed by an other party.

I found out that the helper function `nav_is()` which is located in the file `statamic/bootstrap/helpers' is responsible for checking the active state of a navigation item.

The absolute paths in the navigation are correctly set via https-protocol but the code in line 474 does return the same path without https:
```
$current = URL::makeAbsolute(URL::getCurrentWithQueryString());
```

I think the `URL` helper class makes use of the internal `$_SERVER` variables which aren't set correctly in our setup.

**Expected behavior**
Navigation should work as ecpected.

**Screenshots**
<img width="734" alt="bildschirmfoto 2019-02-21 um 10 59 20" src="https://user-images.githubusercontent.com/1313348/53160610-97525f00-35c8-11e9-8cff-b0c59754df64.png">

**Environment details (please complete the following information):**
 - Statamic Version 2.11.9
 - Upgrade from 2.8.11
 - OS: CentOS Linux 7 (Core)
 - Browser: all
 - Web Server: Apache
 - PHP Version: 7.0.33

**Additional context**
I think worth mentioning is that navigating did work before we did the update. Before we updated to 2.8.11 the same lin (474) did look like this:
```
$current = URL::getCurrent();
```
which totally worked with our setup.

I could think of two possible solutions:

1. Revert that change
2. Wrap the helper function in something like:
```
if (! function_exists('nav_is')) {
// helper function here
}
```
so we have the option to override that function.

**Comment by jasonvarga** [comment]
What do you have set for the `url` in your `system.yaml`'s `locales` array? Put the full https url in there and you should be good.

**Comment by goldnead** [comment]
What a bummer! That fixed ist!
Thanks very much for your quick reply!
