### ISSUE TITLE
Bard: Pasting from Google Docs strips all formatting

### ISSUE THREAD

**Issue by peterhicks** [statamic/v2-hub#2357]
**Describe the bug**
If you copy text from Google Docs into Bard, any formatting (bold, italic, underline, etcetera) is lost and the text is pasted as plaintext. It looks like this is due to the way in which text is copied from Google Docs, as inspecting the clipboard reveals that it's copied as HTML with inline styling, like so (indentation and line breaks added for readability):

```html
<meta charset="utf-8" />
<meta charset="utf-8" />
<b style="font-weight:normal;" id="docs-internal-guid-1c0971b8-7fff-aa41-bf6c-cac693b88c1c">
    <span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">
        Foo 
    </span>
    <span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">
        bar
    </span>
</b>
```

It is possible to reproduce this behaviour in the Scribe editor demo as well, so this is likely an issue with that library rather than Bard itself.

**To Reproduce**
1. Open Google Docs and create a new document. 
2. In that document, write and format some text, such as foo **bar**.
3. Copy that text, and paste it into a Bard  instance within Statamic.
4. Observe that the formatting is not preserved.

**Expected behavior**
The text should be pasted into Statamic with all formatting intact.

**Screenshots**
![Pasting from Google Docs into Bard demonstation](https://user-images.githubusercontent.com/10166921/53185079-36418000-35f6-11e9-8bf5-3a17da480a85.gif)

**Environment details (please complete the following information):**
 - Statamic Version: 2.11.9
 - Fresh Install or Upgrade: Fresh install
 - OS: macOS 10.14.2
 - Browser: Chrome 71.0.3578, Safari 12.0.2
 - Web Server: Valet
 - PHP Version: 7.2.15
 - Addons installed: None

**Comment by jasonvarga** [comment]
Solved in the new Bard that will be in Statamic v3. Unfortunately I don't think this fix can make it back to the Bard in Statamic 2.
