### ISSUE TITLE
Issue with non stacked grid columns when some columns are set to less than 100 width

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#2358]
**Describe the bug**
I have a grid inside a replicator with non stacked columns. I have an col with assets then 2 text cols. The 2 text columns have width 50. The column with assets doesn't display properly and overlays over the text columns.

**Expected behavior**
The column with assets should display properly.

**Screenshots**
This is with grid mode **not** stacked and text col widths at 50:
https://snag.gy/Qe0KW4.jpg

This is with grid mode **not** stacked and text col widths at 100:
https://snag.gy/C8Kz9w.jpg

This is with grid mode stacked and text col widths at 50:
https://snag.gy/bZchPO.jpg

**Environment details (please complete the following information):**
 - Statamic Version [e.g. 2.11.9]
 - Fresh Install or Upgrade: Upgrade
 - OS: [e.g. macOS 10.12.6, Ubuntu 16.04] OSX
 - Browser: [e.g. chrome, safari] Chrome
 - Web Server: [eg. Apache, Nginx, Valet] Valet
 - PHP Version: [eg. 7.1]
 - Addons installed: 

**Additional context**
It's probably just Ant™

**Comment by jasonvarga** [comment]
The widths are percentages.

2 text fields with 50% each will take up the whole row, leaving no space for your asset field.
