### ISSUE TITLE
Can't iterate through taxonomy

### ISSUE THREAD

**Issue by NA-Dev** [statamic/v2-hub#2360]
**Describe the bug**
When I try to iterate through all taxonomy terms, only the first term is shown. I also can't filter the taxonomy by title at all, nothing is returned.

**To Reproduce**
1. Create a taxonomy called "countries" with a fieldset containting "title", "title-es", and "title-fr".
2. Create four countries; France, United States, and Peru, Great Britain.
3. Create "Event" collection with taxonomy field in fieldset.
4. Save Event entries with countries tagged.
5. Iterate through the taxonomy in a template and output "title" for each.

**Expected behavior**
Four country titles display.

**Actual behavior**
If I have no Event collection entries, no countries display. If I create one "United States" and one France event in collection, only "United States" displays.
If I iterate through the collection using {{ collection:events }}, only the first result displays there too.

**Environment details (please complete the following information):**
 - Statamic Version 2.11.9
 - Upgrade from 2.11.6:
 - OS: macOS 10.14.3
 - Browser: Chrome
 - Web Server: Valet plus
 - PHP Version: 7.2
 - Addons installed: none

**Additional context**
``
{{ taxonomy:countries }}
    {{title}}
{{ /taxonomy:countries }}
``

**Comment by jasonvarga** [comment]
Seems to be working as intended here.

Make sure you have named the field in your entries the same as your taxonomy.

For example, if your taxonomy is named `countries` (which is what you've reported) then the field inside the entries must also be `countries`. Not `country`, which I'm guessing might be the issue here.
