### ISSUE TITLE
Custom Validators that use a Facade can't be tested

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#2364]
**Describe the bug**
If you bind a class AND use a Facade in a custom validation, it's not used.

**To Reproduce**

My issue is this, I have a test for a custom validation:
```
     public function test_invalid_token_fails()
     {
         $validator = app('validator')->make(['token' => 'invalid-token'], ['token' => 'valid_token']);
         $this->assertTrue($validator->fails());
     }
```

My custom validation is in my service provider's boot method:
```
        Validator::extend(
            'valid_token',
            function ($attribute, $value, $parameters, $validator) {
                return Gateway::validToken($value);
            },
            'The :attribute is invalid.'
        );
```

as you can see, it uses a Facade

```
class Gateway extends Facade
{
    public static function getFacadeAccessor()
    {
        return PaymentGateway::class;
    }
}
```

in my test's setUp method, I do this:
```
        $this->app->instance(PaymentGateway::class, new FakePaymentGateway);
however, in my service provider I have this:
    public function register()
    {
        $this->app->bind(PaymentGateway::class, function () {
            return new StripePaymentGateway(env('STRIPE_SECRET_KEY'));
        });
    }
```

when I run the test, it uses the StripePaymentGateway NOT FakePaymentGateway

**Expected behavior**
`FakePaymentGateway` is used

**Environment details (please complete the following information):**
 - Statamic Version: 2.11.9
 - Fresh Install

**Comment by jasonvarga** [comment]
After you use `$this->app->instance(PaymentGateway::class, new FakePaymentGateway);` try adding `Facade::clearResolvedInstance(PaymentGateway::class)`

**Comment by edalzell** [comment]
Darn, that didn't work.

**Comment by edalzell** [comment]
I wasn't importing `PaymentGateway` in my test.
