### ISSUE TITLE
Symlinks are ignored for settings-yaml-files

### ISSUE THREAD

**Issue by ymakhloufi** [statamic/v2-hub#2366]
**Describe the bug**
when using a symlink for any settings yaml file, statamic will not parse that file, because it uses Laravel's Filesystem's files() method which does not return symlinks (it checks fir filetype($file) === "file" instead of is_file($file) which allows symlinks.

While this might be intended behavior on Laravel's side, it prevents us from symlinking any Statmic settings yaml files. 

**To Reproduce**
1. rename e.g. system.yaml to system.yaml.bak
2. symlink the file: `ln -s system.yaml.bak system.yaml`
3. this settings file will be entirely ignored any replaced with the defaults.

**Expected behavior**
Statamic should follow symlinks to their source and read the file - no matter where the actual file is

**Environment details (please complete the following information):**
 - Statamic Version [e.g. 2.11.2]
 - Fresh Install or Upgrade: Not sure - I inherited the system
 - OS: Amazon Linux (CentOS-ish)
 - Browser: Any
 - Web Server: Apache 2.4 with prefork-mpm
 - PHP Version: 7.2

**Suggested solution**
replace Line 129-131 of statamic/core/Bootstrap/UpdateConfiguration (the first three lines of the loadSiteConfig() method) like so:

**before**

        $files = collect($this->filesystem->files(settings_path()))->filter(function ($file) {
            return pathinfo($file)['extension'] === 'yaml';
        })->all();

**after**

        $files = collect(glob(settings_path() . '/*') ?: [])->filter(function ($file) {
            return is_file($file) && pathinfo($file)['extension'] === 'yaml';
        })->all();

**Comment by jackmcdade** [comment]
We can't support symlinks because Flysystem doesn't support them - and unfortunately this would break other features that rely on Flysystem. :(

**Comment by ymakhloufi** [comment]
Sorry for re-opening this ticket, but updating Statamic is so painful when you need to maintain a hack like this...

There's no need to drop Flysystem in Statamic in general. It is literally just in this particular place in the code where it could be replaced with the snippet I provided above. It is currently the only blocker from having Statamic deployed to a load-balanced environment. 

Would there be any negative implications in this particular part of the code that I might have missed? We've been running this in production like it since June and haven't had any issues so far...

**Comment by ymakhloufi** [comment]
Sorry for re-opening this ticket, but updating Statamic is so painful when you need to maintain a hack like this...

There's no need to drop Flysystem in Statamic in general. It is literally just in this particular place in the code where it could be replaced with the snippet I provided above. It is currently the only blocker from having Statamic deployed to a load-balanced environment.

@jackmcdade Would there be any negative implications in this particular part of the code that I might have missed? We've been running it in production like this since June and haven't had any issues so far...
