### ISSUE TITLE
Filtering a collection using multiple parameters with variables

### ISSUE THREAD

**Issue by JonKaric** [statamic/v2-hub#2367]
Added as a feature request, as not sure if it's a bug or if it's intended.

**Is your feature request related to a problem? Please describe.**
The docs say the following on [this](https://docs.statamic.com/conditions#example) page: > If you want narrow your results further you can repeat conditions as many times as needed.

Problems occur when you start adding multiple variables, eg: 
`{{ collection:things url:isnt="{ myurl }"  url:isnt="{ mysecondurl }" }}`

Works if: You hardcode strings 
Works if: You have one variable `url:isnt="{ url }"`
Doesn't work if: You add multiple variables 

**Describe the solution you'd like**
A custom filter would do the trick, but I think it would benefit people to have this function out of the box for quick implementation. My use case: Hiding posts that they've already viewed from 'related posts' for better ux, by using `{{session }}` variables.  

**Additional context**
https://discordapp.com/channels/489818810157891584/489831949196591105/552961543399014401

**Comment by jasonvarga** [comment]
That line in the docs could be rewritten for clarity.

You can repeat conditions where the _condition_ is just the `isnt` in your example.
You can't repeat entire statements like `url:isnt`.

`something:isnt` and `something_else:isnt` would work fine.

You should instead try to use an array-type condition.

```
---
these:
  - /url-one
  - /url-two
---

{{ collection:things :url:doesnt_contain="these" }}
```
