### ISSUE TITLE
bug in fieldset with 2 section

### ISSUE THREAD

**Issue by 4kets** [statamic/v2-hub#2372]
**Describe the bug**
In a fieldset when i have 2 section both the section have a replicator with some types and fields in them. after reloading the first sections works normally, but the second section does this: 
![image](https://user-images.githubusercontent.com/20043831/54990862-02be9080-4fbc-11e9-9a65-0f03794f981b.png)
it gets rid of the display name and field name the field still works but i just cant see the text when i want to edit the fieldset

**To Reproduce**
1. Go to fieldsets
2. Click on a fieldset
3. make 2 sections
4. place in both sections a replicator and some fields in the replicator
5. save
6. reload and click on section 2

**Screenshots**
![image](https://user-images.githubusercontent.com/20043831/54991062-6d6fcc00-4fbc-11e9-94f9-9c2ceb78630b.png)
![image](https://user-images.githubusercontent.com/20043831/54991078-7791ca80-4fbc-11e9-8136-010320f7e4ae.png)

**Environment details (please complete the following information):**
 - Statamic Version: 2.11.9
 - Fresh Install or Upgrade: Fresh install
 - OS: windows 10
 - Browser: Chrome
 - Web Server: Apache or nginx
 - PHP Version: latest

**Comment by jsblair9** [comment]
I can confirm this one as well. 

The fieldset that is saved however is valid and will work... just the CP vue component seems to be 🐛y

**Comment by helloDanuk** [comment]
Same here.

If you click the 'Toggle Sets' icon off and on again, the text reappears.
