### ISSUE TITLE
German Umlaute and taxonomy slugs

### ISSUE THREAD

**Issue by alexanderhofstaetter** [statamic/v2-hub#2373]
**Describe the bug**
When a Taxonomy with an German "Umlaut" (ä, ö, ü) is added the automatically generated slug converts ö to o, ä to a, .. the correct version would be ö -> oe, ü -> ue, ä -> ae.

There is a big difference!

**To Reproduce**
Add an taxonomy via the Control Panel

**Comment by jackmcdade** [comment]
Have you set the site's locale to German? The behavior changes based on what locale the site is set to.

**Comment by alexanderhofstaetter** [comment]
Yes I have. I found out why it was not working

**`site/settings/system.yaml`:**
```
locales:
  de:
    name: Deutsch
    full: 'de_AT.utf8'
    url: 'https://example.com/'
```
I changed from de_AT.utf8 to de_DE.utf8 and now it works. However, de_AT is a valid locale and it should work for the Austrian too. It think it would be the same problem with the swiss locale `de_CH`.

**Comment by jackmcdade** [comment]
We use <https://github.com/pid/speakingurl> which does the locales by ISO 639-1 Codes. `de_AT.utf8` is not a valid code in that list. Here's the list:

- 'ar' // Arabic
- 'az' // Azerbaijani*
- 'cs' // Czech
- 'de' // German
- 'dv' // Divehi
- 'en' // English
- 'es' // Spanish
- 'fa' // Persian
- 'fi' // Finnish
- 'fr' // French
- 'ge' // Georgian
- 'gr' // Greek*
- 'hu' // Hungarian
- 'it' // Italian
- 'lt' // Lithuanian*
- 'lv' // Latvian
- 'my' // Burmese
- 'mk' // Macedonian*
- 'nl' // Dutch
- 'pl' // Polish
- 'pt' // Portuguese
- 'ro' // Romanian
- 'ru' // Russian
- 'sv' // Swedish
- 'sk' // Slovak
- 'sr' // Serbian*
- 'tr' // Turkish
- 'uk' // Ukranian
- 'vn' // Vietnamese

**Comment by alexanderhofstaetter** [comment]
I think you will never find this locales on the system installed. At the beginning i tried with default `de` locale string. However, several PHP functions did not work correctly (e.g. strftime). I needed to set the correct locale which is installed on the system. Which ist something more complex than just `de`.

**On my CentOS Server**:
```
-bash-4.2$ locale -a | grep de
de_AT
de_AT@euro
de_AT.iso88591
de_AT.iso885915@euro
de_AT.utf8
de_BE
de_BE@euro
de_BE.iso88591
de_BE.iso885915@euro
de_BE.utf8
de_CH
de_CH.iso88591
de_CH.utf8
de_DE
de_DE@euro
de_DE.iso88591
de_DE.iso885915@euro
de_DE.utf8
de_LU
de_LU@euro
de_LU.iso88591
de_LU.iso885915@euro
de_LU.utf8
deutsch
```

**On a default Ubuntu 18.04 installation**:
```
root@alma:~/data# locale -a
C
C.UTF-8
en_US.utf8
POSIX
```

So for the site to work probably in all languages these locale settings need to be the same. Escpecially the one which is passed to PHP.

**Comment by helloDanuk** [comment]
I have `de_CH` in my `site/settings/system.yaml`. When creating a new term via the Statamic main menu on the left _(Taxonomy → Create XY)_ the german Umlaute in the slug are converting right: ä to ae, ö to oe and ü to ue.

But when adding a new term directly in a collection entry the Umlaute converts wrong: ä to a, ö to o and ü to u.

<img width="1426" alt="Bildschirmfoto 2019-04-05 um 23 05 08" src="https://user-images.githubusercontent.com/8265902/55657403-646fcd80-57fa-11e9-803d-c754622518e9.png">

<img width="394" alt="Bildschirmfoto 2019-04-05 um 23 07 12" src="https://user-images.githubusercontent.com/8265902/55657497-b3b5fe00-57fa-11e9-9863-06459394cd29.png">

Running Statamic 2.11.10
PHP 7.2.10
MAMP
macOS 10.14.4
Chrome

**Comment by alexanderhofstaetter** [comment]
Its exaxtly the same behaviour for me.
