### ISSUE TITLE
[BUG] When texarea field is saved with a starting space, there is a ParseException

### ISSUE THREAD

**Issue by Neophen** [statamic/v2-hub#2382]
**Describe the bug**
If the text has a starting space it breaks the parsing for e.g.:
```
description: |
<space><space><space>PURPOSE:
<space><space>The John and Sharon Cady Blom 
```

Where <space> is an actual space.

When `type: textarea` is saved with a starting space this exception is thrown:
```
ParseException in Parser.php line 444:
Unable to parse at line 4 (near " The Frieda Wall Endowed Scholarship will be established in 2013 to provide financial aid to students").
```

**To Reproduce**
1. create a fieldset with `type: textarea`
2. save an entry with a starting space (you can copy paste text bellow):
```
 PURPOSE:
The John and Sharon Cady Blom 
```
3. note the parse exception.

**Expected behavior**
the parser should not break.

**Environment details (please complete the following information):**
 - Statamic Version 2.11.6
 - OS: macOS 10.14.1 (18B75)
 - Browser: chrome
 - Web Server: Valet
 - PHP Version 7.2.8

**Comment by jasonvarga** [comment]
This seems to be an issue with the Symfony YAML parser.
Although I'm not sure what the correct behavior should be.

Do you actually need that space? What if we just trimmed off extra space? That would fix the error but you'd lose the space if it was intentional.

**Comment by jackmcdade** [comment]
This issue has been inactive and in need of more information for a while now. Feel free to reopen and we'd be more than happy to take another look if you have more info that can help!

**Comment by Neophen** [comment]
Yeah it's ok i'm now trimming the spaces :)
