### ISSUE TITLE
[FR] Automatically increment slug when saving a duplicate

### ISSUE THREAD

**Issue by benfurfie** [statamic/v2-hub#2387]
**Describe the bug**
In a collection, when adding an entry with the same title, the slug will result in a conflict. In theory, the DuplicateEntryController should be triggered in this instance to auto increment the entry, but it isn't happening. Instead, you are presented with an error that the 'Slug already exists'.

**To Reproduce**
1. Create a collection.
2. Create an entry and save.
3. Create another entry with the same title and attempt to save.
4. You will be presented with the error.

**Expected behavior**
As per the defined behaviour of the DuplicateEntryController, when you attempt step 3, Statamic should check if the slug exists, and if it does, increment it.

**Screenshots**
![statamic-duplicate-entry-bug](https://user-images.githubusercontent.com/10786699/56818052-be364700-683e-11e9-908b-efd81386c3d5.gif)

**Environment details (please complete the following information):**
 - Statamic Version: 2.11.10
 - Fresh Install or Upgrade: Fresh
 - OS: [e.g. macOS 10.12.6, Ubuntu 16.04] macOS 10.14.1
 - Browser: All
 - Web Server: Valet
 - PHP Version: 7.2
 - Addons installed:

- AardvarkSeo
- AllTheThings
- CacheCrashie
- History
- Impersonator
- Mix
- PowerTools
- Spock
- Svg
- Tel

**Additional context**
https://discordapp.com/channels/489818810157891584/489831949196591105/571340790433972251

**Comment by lardnicus** [comment]
Is there a way to roll this back or turn this off? If we are using unique slugs as part of a specific or preexisting url, sometimes it's very useful to know if the slug exists already so we can be sure to change the link anywhere that links to it

**Comment by jasonvarga** [comment]
This is being rolled back for next release.

We thought about it some more. The original behavior (the validation error) is fine, not a bug.

Think about doing the equivalent actions in Mac's Finder.
- Rename a file to the same as another, you would get an error saying you can't do that. Consistent with the validation error.
- Duplicate a file, it adds ` copy`, `copy 2`, etc. Consistent with how our "Duplicate" feature works.
