### ISSUE TITLE
Error not showing in login template

### ISSUE THREAD

**Issue by vitor-ao** [statamic/v2-hub#2388]
**Describe the bug**
No error message is shown on the login template when using the wrong credentials.

**To Reproduce**
1. Create a form (can be copied from https://docs.statamic.com/tags/user-login_form)
2. Login with an existing user but write the wrong passsword
3. The error does not show up when returning to the form

**Expected behavior**
The login form should show a "incorrect credentials" error (as is on v2.11.10)
![chrome_NP93R2tW2n](https://user-images.githubusercontent.com/38264224/56868725-24150100-69ee-11e9-9851-d2be2a62c440.png)

**Screenshots**
![firefox_VSCEv5TFeI](https://user-images.githubusercontent.com/38264224/56868700-c08ad380-69ed-11e9-8c4c-9625633860c1.png)

**Environment details (please complete the following information):**
 - Statamic Version 2.11.12 [Upgrade]
 - OS: Windows 10 
 - Browser: Any
 - Web Server: Apache
 - PHP Version: 7.3.2
 - Addons installed:

**Additional context**
This bug does not exist on version 2.11.10

**Comment by mar627** [comment]
Hi @vitor-ao do you receive the same error message as I do `field field` when trying to login without entering a password? https://github.com/statamic/v2-hub/issues/2383#issuecomment-488733222

**Comment by vitor-ao** [comment]
My website uses [jQuery Validate](https://jqueryvalidation.org/) so I can't  login without a password, but i've disabled it to test and i get the error that the password field is required. Seems to be the same bug report you've added @mar627

**Comment by mar627** [comment]
Well that's good then! The devs can fill two needs with one deed. I'll mark this as a duplicate/reference for mine seeing as yours hasn't been closed. Cheers
