### ISSUE TITLE
Update v2's Glide, which now supports the WebP format

### ISSUE THREAD

**Issue by jeffmckeand** [statamic/v2-hub#2396]
**Is your feature request related to a problem? Please describe.**
No; just something new.

**Describe the solution you'd like**
Glide now supports the WebP format (see https://glide.thephpleague.com/1.0/api/encode/#format-fm). Hooray! Can we get Glide updated in Statamic v2 core?

**Would you be willing to sponsor this feature?**
Perhaps. Whatcha thinking?

**Comment by pxwee5** [comment]
@jackmcdade 
Currently Statamic is still on `"league/glide": "^1.1"`
Latest is `"league/glide": "1.5"`

**Comment by andrewjireland** [comment]
After much wasted time, I found out this morning that Webp support wasn't added until v1.4. This would be a massive help if this can be updated!

**Comment by jackmcdade** [comment]
Easy enough, coming in next update! 👍
