### ISSUE TITLE
FR: Variable that is only available in Live Preview

### ISSUE THREAD

**Issue by macbruker** [statamic/v2-hub#2397]
I have this **collapse/expand** block on my site. When I am editing with _Live Preview_, my **collapse/expand** block is displayed in its default collapsed state, with no possibility to expand it and see the content inside. Clicking to trigger expanding, seems to be prevented in some way.

It would be handy with a variable like `{{ preview }}` or something similar, that returns _true_ if a page is viewed in _Live Preview_. That way, I can make sure that the **collapse/expand** block is always expanded when using _Live Preview_.

**Comment by madsem** [comment]
similar issue, trying to find a way to detect live preview as well. This should be included somehow. 
For me I'm trying to prevent adsense from being included in live preview which is really against adsense policies (don't shows adsense in frames). With many editors working ad impressions can quickly go in the thousands...

**Comment by madsem** [comment]
ah okay solved it @macbruker, there already is a way to check.
You have to check if $_POST['preview'] isset and is not 1.

In Antlers just like this:
```php
{{ if ! post:preview }}
blah
{{ /if }}
```

**Comment by macbruker** [comment]
That is awesome! 
Thank you for sharing your findings 🙂
