### ISSUE TITLE
Caching config breaks filesystems.disks

### ISSUE THREAD

**Issue by oniryx** [statamic/v2-hub#2407]
**Describe the bug**

Running statamic without laravel config cached is working.
Caching the config `php please config:cache` generated an error where the local filesystems couldn't be found

**To Reproduce**

From a freshly setup statamic on the console do the following

1. `php please` 
2. everything is working ok 
3. `php please config:cache` 
4. `php please`
5. See error

**Expected behavior**

The listing of all the commnands

**Screenshots**
![Screenshot 2019-06-07 at 11 54 03](https://user-images.githubusercontent.com/738697/59105707-6ce4a180-892c-11e9-83c6-9d0d58c251e3.png)

**Environment details (please complete the following information):**
 - Statamic Version 2.11.12
 - Fresh Install:
 - OS: macOS 
 - PHP Version: 7.1

**Suggested fix**

```
diff --git a/statamic/core/Providers/FilesystemServiceProvider.php b/statamic/core/Providers/FilesystemServiceProvider.php
index 9d92fbc..ac96b31 100644
--- a/statamic/core/Providers/FilesystemServiceProvider.php
+++ b/statamic/core/Providers/FilesystemServiceProvider.php
@@ -332,6 +332,11 @@ class FilesystemServiceProvider extends ServiceProvider
      */
     private function mergeIntoLaravel()
     {
-        $this->config->set('filesystems.disks', $this->disks);
+        $this->config->set('filesystems.disks',
+            array_merge(
+                $this->config->get('filesystems.disks'),
+                $this->disks
+            )
+        );
     }
 }
```

**Comment by jackmcdade** [comment]
We don't support caching the config Laravel style - Statamic has it's own caching system. It's not so much a bug as just something you need to know and...not do. 😁
