### ISSUE TITLE
Saving routes from the cp

### ISSUE THREAD

**Issue by freshface** [statamic/v2-hub#2410]
**Describe the bug**
When saving the routes the yaml file is not correct and gives on error on the frontend.
It adds single quotes to the empty ```{  }```

After saving:

```
routes: '{  }'
redirect: '{  }'
vanity: '{  }'
```

As it should be:

```
routes: {  }
redirect: {  }
vanity: {  }
```

**To Reproduce**
1. Save the routes from the CP

**Additional context**
Error:

<img width="1000" alt="Screenshot 2019-06-12 at 22 38 51" src="https://user-images.githubusercontent.com/103913/59384641-ed5b3600-8d62-11e9-8d40-404dac187960.png">

**Comment by robdekort** [comment]
Yes, this is a pretty annoying bug. You'll encounter it soon when you just start with Statamic and then you don't know what to do.

**Comment by jackmcdade** [comment]
What version are you on? I can't recreate this in 2.11.12.

**Comment by robdekort** [comment]
Same version! Is this helpful? https://cvws.icloud-content.com/B/ASX0jVeRHO65M9igDAsmz7KG7_VwAZqi8WjGNBjPMq78olFMRCp32slN/statamic-saving-routes-from-the-cp.mov?o=AgDJ0-0Ipptb-gYEPIiLjuhpbnW7kjnZKjAecqoDJ6Pi&v=1&x=3&a=CAogoW8oDUtHbRio78yevedLqNDQd3LK91wknOtkwHWNniYSHRCGhuDJuS0Ypv2WyrktIgEAUgSG7_VwWgR32slN&e=1561644613&k=rQ9_2uUwRgOsq2e7dAl5lg&fl=&r=dafb35cc-c866-4fd9-bcd4-b167e9b66138-1&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=18&s=E62UqCoqrU35gRKSQswAqLaZNyI&cd=i

**Comment by jackmcdade** [comment]
Ahh, very helpful, thank you. You need to load the form with a `null` routes field. Got it. 👍

**Comment by robdekort** [comment]
Cool!
