### ISSUE TITLE
Collection:count from="*" returns Zero

### ISSUE THREAD

**Issue by Rovaski** [statamic/v2-hub#2412]
**Describe the bug**
{{ collection:count from="*" }} returns zero.. 
{{ collection:count from="someCollection|anotherCollection" }} also returns zero.

**Expected behavior**
Expected collection count to return number of entries from either all "*" or the specific pipe delimited collections. 
Also expected to retain the ability to use all modifiers such as filtering with things like author:is="Barfoo" or title:contains="Foo", and return the correct count of entries matching that criteria. 

**Environment details (please complete the following information):**
 - Statamic Version, 2.11.12
 - Fresh Install or Upgrade: Fresh install
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Web Server: Apache
 - PHP Version: 7.3? Not at computer, unsure but definitely greater than 7.1.
 - Addons installed: Spock

**Comment by jackmcdade** [comment]
We can take a look, but honestly collection:count is kinda superfluous since we added aliasing. You can do this:

```
{{ collection from="someCollection|anotherCollection" author:is="Barfoo as="entries }}
    {{ entries | count }}
{{ /collection }}
```

Give that a shot!

**Comment by Rovaski** [comment]
That works perfectly. Thanks.
