### ISSUE TITLE
CP Updater page date format

### ISSUE THREAD

**Issue by BurgrLada** [statamic/v2-hub#2419]
In the control panel, I would love to have the power over the date displayed under the `Updater` tab. It would make sense if this format would follow `cp.yaml`, where there actually is `date_format` input.
The format is hardcoded, see file `statamic/resources/views/updater/index.blade.php`, line 26:
```
<h5 class="date">{{ trans('cp.released_on_date', ['date' => Carbon::parse($release->created_at)->format('F jS, Y')]) }}</h5>
```

**Comment by jasonvarga** [comment]
That date format is a design choice, and using the default cp date_format looks strange.

For next release, the date will be localized though, so the English month names will be translated (I'm guessing this may be a reason you wanted to customize it)

**Comment by ebeauchamps** [comment]
The date doesn't look as it is localized for me:

![Capture d'écran 2019-08-18 21 00 45](https://user-images.githubusercontent.com/1823359/63229005-c0f8e580-c1fb-11e9-9083-28e86a13c564.png)

**Comment by jasonvarga** [comment]
What’s the locales in your system.yaml?

**Comment by ebeauchamps** [comment]
![Capture d'écran 2019-08-18 21 06 59](https://user-images.githubusercontent.com/1823359/63229042-277e0380-c1fc-11e9-8b4e-a3f1644cd45d.png)

**Comment by jasonvarga** [comment]
Try change fr to fr_FR

**Comment by ebeauchamps** [comment]
not working sir

**Comment by jasonvarga** [comment]
Ok I will get back to you :)

**Comment by ebeauchamps** [comment]
sure! no urge for me.
