### ISSUE TITLE
Child list missing on Statamic navigation

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/v2-hub#2452]
I've had a couple sites where the sub navigation list in the Statamic sidebar doesn’t show. (see screeshot, the Settings menu should show.) I’ve noticed in the last few versions up to the current `2.11.15`

<img width="648" alt="Screen Shot 2019-10-08 at 4 29 44 PM" src="https://user-images.githubusercontent.com/113216/66432201-80dc0500-e9eb-11e9-952a-bfe39c7333bf.png">

**Comment by jasonvarga** [comment]
This is generally when your urls in settings/system.yaml are relative and it has difficulty working out the full url from the server for whatever reason. (Proxy, etc)

To fix this, make the urls full, eg. http://mysite.com/

**Comment by jeremydouglas** [comment]
Yes, this is a little weird. I get the menus on my local env with this environment file:

```
settings:
  caching:
    static_caching_enabled: false
  debug:
    debug: true
    debug_bar: true
  system:
    locales:
      en:
        url: "http://pool-doctors.test"
```

But not on my staging server with this in the environment file:

```
settings:
  caching:
    static_caching_enabled: false
  debug:
    debug: true
    debug_bar: false
  system:
    locales:
      en:
        url: "http://pld.compasscreative.dev"
```

I'll be able to test in a production environment shortly.

**Comment by jeremydouglas** [comment]
Sub menu is working on production, I'll not worry about this further.
