### ISSUE TITLE
Entries are not saved

### ISSUE THREAD

**Issue by rcknr** [statamic/v2-hub#2455]
**Describe the bug**
Out of the sudden any collection entry change is no longer persisted. I've checked permissions, logs. There's no error message.

**To Reproduce**
Have no clue.

**Expected behavior**
Obviously, saving data, however, an error message would be great to have a clue what's happening.

**Environment details (please complete the following information):**
 - Statamic Version - 2.11.15
 - Fresh Install or Upgrade: Upgrade
 - OS: macOS 10.14.6
 - Browser: chrome
 - Web Server: Valet
 - PHP Version: 7.1
 - Addons installed: Charge, Laravel Mix, OAuthBridge

**Additional context**
The same project seem to work fine in a production environment (saves entries properly).

**Comment by rcknr** [comment]
More details: collections could be renamed, entries could be deleted, however, editing, duplicating and creating new ones does not work.

**Comment by rcknr** [comment]
I am overwhelmed with the response to my issue report! In any case, I was able to sort my problem out. The culprit was enabling event module in Debugbar in combination with this bit from `statamic/core/Data/Content/Content.php`:
```
// If any listener responses return null, the content shouldn't be saved.
if (in_array(null, $responses, true)) {
    return $this;
}
```
Should I say it's extremely frustrating when there's no feedback for this?

**Comment by jasonvarga** [comment]
Hi! Sorry for the lack of response.

Unfortunately I can't replicate this issue. Any more details would be helpful if this is still a problem for you.
