### ISSUE TITLE
Console error when no formatting options selected in Bard

### ISSUE THREAD

**Issue by andyfitch** [statamic/v2-hub#2457]
**Describe the bug**
1. Error in console:
scribe-plugin-toolbar.js:27 Uncaught (in promise) TypeError: Cannot read property 'querySelectorAll' of undefined
2. Unable to type in field - text is removed on blur event

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a bard to a fieldset
2. Edit the bard
3. Click the 'Extras' tab
4. Deselect all options in the black formatting bar, save
5. Exit the fieldsets area of Statamic, enter a page where the Bard is used
6. Try to type in fields in that Bard

**Expected behaviour**
Should be able to type in fields, save content without console error

**Screenshots**
<img width="838" alt="Screenshot 2019-10-29 at 16 19 20" src="https://user-images.githubusercontent.com/265406/67787093-e27e1500-fa67-11e9-9700-e1dca752c578.png">
Videos of cause & symptoms: [Archive.zip](https://github.com/statamic/v2-hub/files/3784643/Archive.zip)

**Environment details (please complete the following information):**
 - Statamic Version 2.11.3
 - Fresh Install
 - OS: macOS 10.14.5
 - Browser: Chrome
 - Web Server: Valet+
 - PHP Version: 7.1.32
 - Addons installed:
Custom Database addon built in-house

**Comment by jackmcdade** [comment]
Is this a common thing people do often? Turn off all the features? If so, we can look into it, but otherwise this is resolved in v3 with the new bard :) Feel free to reopen!
