### ISSUE TITLE
Bard won't allow drop and drag reordering

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#2459]
Using this fieldset
```
      brad:
        type: bard
```
creates a generic Brad, the docs say:

>Drag and Drop Reordering: Want to rearrange your post layout? Move the images around? Bring your TL;DR from the bottom up to the top? Just drag those blocks around.

But in reality nothing can be dragged. Does something else need specifying?

Also doesn't work with other sets specified, i.e. images

**Environment details (please complete the following information):**
 - Statamic Version 2.11.15
 - Fresh Install:
 - OS: MacOS
 - Browser: Chrome
 - Web Server: Valet
 - PHP Version: 7.3.11

**Comment by jasonvarga** [comment]
You can drag sets. You have none.

**Comment by dannyuk1982** [comment]
OK thanks, so if you just have text outside a set you can't move that? 

I also had sets (which were single images) in but couldn't get it to work, when the set is just one image it appears there is no "handle" to move it as it just displays the image and the name (not draggable). 

It seems like you need a set that creates some UI around it in order to be able to drag.

**Comment by jackmcdade** [comment]
Correct. All the text in between sets (or up to your first set, or all the text if you have no sets) is essentially, 1 set.
