### ISSUE TITLE
Non commercial addons market as commercial

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#2475]
**Describe the bug**
Recently some of our addons where flagged as commercial requiring a license key because an addon with the same name (`events`) has been released on the marketplace as a commercial addon.

Our customers are scared by the warning and its some work to rename our own addons.

**To Reproduce**
1. Create a custom addon named `Events`
2. CP shows a red bar with the license key warning

**Expected behavior**
Our addons should not be flagged as commercial by accident.

I am aware that fixing this easiy might not be possible …

**Comment by jasonvarga** [comment]
Please send me a DM on discord, or email support@statamic.com

**Comment by jasonvarga** [comment]
Solved offline!
