### ISSUE TITLE
setting the default locale url different to "/" ruins control panel

### ISSUE THREAD

**Issue by verybigelephants** [statamic/v2-hub#2527]
**Describe the bug**
I would like to prefix all urls by my locale slug. For example, english would be on a domain.com/en/... and all the austrian articles would be on domain.com/at/...  i do not wish to have domain.com/ urls and would redirect them to the default locale if someone navigated to "/". however, when i set this,  all the links generated in control panel stop working, because they generate /en/cp, while cp still works on url /cp.

setting "$control_panel" to 'sk/cp' doesn't work neither, as then the control panel generates links like /sk/sk/cp.

**To Reproduce**
1.  Fresh statamic install
2. set two locales:
    sk sk_SK Slovak http://my-dev-website.test/sk
    en en_US English http://my-dev-website.test/en
3. refresh and ruin links in your control panel

**Expected behavior**
A working control panel that generates correct control panel links, regardless of default locale's root url

**Environment details (please complete the following information):**
 - Statamic Version 2.11.20
 - Fresh Install 
 - unix ubunty virtual , my local windows 10 machine, all of them
 - Browser: desn't matter
 - Web Server: Apache, Nginx
 - PHP Version: 7.1, 7.2, 7.4.5
 - Addons installed: none

**Comment by jasonvarga** [comment]
At the moment you cannot have _only_ subdirectory based sites. The default needs to be the root.

This may be possible in v3, but not v2 unfortunately.

**Comment by verybigelephants** [comment]
could this be tagged as a feature request then?
