### ISSUE TITLE
 Assets not uploading to s3 or anywhere in local.

### ISSUE THREAD

**Issue by janejanejane** [statamic/v2-hub#2540]
**Describe the bug**
Assets not uploading to s3 or anywhere in local.
The network tab indicates a success in upload.

**To Reproduce**

```
// inside Control Panel page
fields:
    video:
      type: assets
      display: Video URL
      container: videos
```

``` 
// /videos.yaml
key: **
secret: **
bucket: **
path: content/videos
region: us-west-2
title: Videos
driver: s3
url: /content/videos
```

**Screenshots**
When creating inside the assets folder, no error is logged and no file uploaded.

<img width="875" alt="Screen Shot 2021-07-21 at 3 49 41 PM" src="https://user-images.githubusercontent.com/1129555/126428187-1f9938aa-6a8d-4b79-9675-54e47177cad8.png">

When creating in s3 manually, files are shown in assets folder.
<img width="902" alt="Screen Shot 2021-07-21 at 3 54 13 PM" src="https://user-images.githubusercontent.com/1129555/126428429-94199c37-9034-4ba5-b47d-93640021e2b7.png">
<img width="775" alt="Screen Shot 2021-07-21 at 3 54 03 PM" src="https://user-images.githubusercontent.com/1129555/126428476-ab562ff4-05a5-4fe1-be2b-eaf22cdbff3e.png">

**Expected behavior**
Files should have been uploaded to s3.

**Environment details (please complete the following information):**
 - Statamic Version 2.11.21
 - Fresh Install or Upgrade: upgrade from 2.11.13 but even in 2.11.13, s3 upload didn't work.
 - OS: macOS 11.2.3
 - Browser: Chrome
 - Web Server: Valet
 - PHP Version: 7.3.27

**Additional context**
Error logged when creating **New Folder** using Statamic assets interface (removed company details):
```
ERROR: exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "https://**.us-west-2.amazonaws.com/content/videos/test/"; AWS HTTP error: Client error: `PUT https://**.us-west-2.amazonaws.com/content/videos/test/` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>** (truncated...)
 AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>**</RequestId><HostId>**</HostId></Error>'

GuzzleHttp\Exception\ClientException: Client error: `PUT https://**.us-west-2.amazonaws.com/content/videos/test/` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>
```

Setting the action to **"s3:*"** uploads the file. But this is too relaxed. 
What is the recommended actions for the bucket?

**Comment by kentaro00** [comment]
I encountered this problem as well, but I've found through trial and error that for a minimally-granted IAM policy, in order to successfully upload a file you need at least:

```
{
  "Effect": "Allow",
    "Action": [
      "s3:PutObject",
      "s3:PutObjectAcl"
     ]
...
}
```

Hope that helps

**Comment by janejanejane** [comment]
Thanks @kentaro00 . It worked. 👍
