### ISSUE TITLE
Collection: Iterate over children

### ISSUE THREAD

**Issue by Sennik** [statamic/v2-hub#2542]
Historically I always had all content related to a website hierarchically stored in one database and iterated over child sections to populate my navigation structure. I know I can do that by creating seperate collections an/or nav's but I like to continue the old way when possible (My customers are used to this approach).

I really like the possibility to use collections directly in navigation structures.

Is it possible to iterate over child sections in the following example?

![2021-10-12 10_52_24-Pagina's ‹ Collecties ‹ Backpage](https://user-images.githubusercontent.com/5636394/136925281-05cc0c0d-89b0-45ba-a16b-2c08f69deaf7.png)

I want to iterate over 'Main menu' for the Navbar en over Footer menu for the Footer navigation. In this example footer Menu has two columns with each 2 links.

**Comment by jasonvarga** [comment]
Please open an issue or discussion in the v3 repo. This is the v2 repo.

https://github.com/statamic/cms
