### ISSUE TITLE
Reorder button for entries in a collection does nothing

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#264]
Collections with `order: number` set in the collection `folder.yaml` have a reorder button in the CP. Clicking this changes the action buttons to Save and Cancel however no reordering is possible. 

Is is possible to have the same UI as reordering on pages (far left column has dots to 'grab' and move)?

**Comment by seanwash** [comment]
Not to +1 or anything, But I just experienced this as well for two collections. Here's a quick screencap of reordering and saving: http://cl.ly/3r3y2o0F3r2q
