### ISSUE TITLE
Redactor link 'open in new window' checkbox missing

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#265]
In a Redactor field, use link button to open modal to insert URL and checkbox to "open in new window" but the actual checkbox is missing.

Statamic V2
![v2 - checkbox missing](https://cloud.githubusercontent.com/assets/3920126/11918307/619f692a-a723-11e5-8ce9-4f5ab71603aa.png)

Statamic V1
![v1 - checkbox present](https://cloud.githubusercontent.com/assets/3920126/11918300/1aea40a4-a723-11e5-9756-fbcc3c355cd7.png)

**Comment by jasonvarga** [comment]
Bug is back. Alright.

![](http://stream1.gifsoup.com/view3/1159550/everybody-backstreets-back-o.gif)

**Comment by PhilippeGauthier** [comment]
Looks like the `opacity` and `left` styles are hiding it. Maybe targeted unintentionally? :
```
.daterange [type=checkbox].dr-input, .form-control[type=checkbox], .markdown-fieldtype [type=checkbox].CodeMirror, [type=checkbox].environment-field, [type=checkbox].redactor-editor, input[type=checkbox], input[type=checkbox].slug:focus, input[type=checkbox].slug:hover, textarea[type=checkbox], trix-editor[type=checkbox] {
    opacity: 0;
    position: absolute;
    left: -9999px;
```

**Comment by steenkamp-adnet** [comment]
This issue still exists - will there be a fix implemented in a future release?

![screen shot 2016-08-16 at 10 34 01 am](https://cloud.githubusercontent.com/assets/10518660/17709427/e1572388-639d-11e6-9d02-d71476fa9882.jpg)

Thanks!

**Comment by lesaff** [comment]
I've incorporated a css fix to this issue in my [RedactorPlugins](https://github.com/lesaff/statamicv2-redactorplugins) addon. In case anyone need this right now.

**Comment by dannyuk1982** [comment]
Add this at the end of /statamic/resources/dist/css/cp.css

```#redactor-modal input[type=checkbox] { opacity: 1 !important; left: 0 !important; position: relative !important; }```

**Comment by dannyuk1982** [comment]
Any ETA on this? Seems a very quick fix but it's quite a major problem when using the CP to create external links.
