### ISSUE TITLE
remove_left modifier not functioning

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#271]
This should work [according to docs](http://docs.talonsbeard.com/docs/modifiers#-remove_left)  but it does not:
`{{ twitter | remove_left:@ }}`

Workaround: `{{ twitter | reverse | backspace:1 | reverse }}`

**Comment by alexroper** [comment]
I'm having the same problem removing a hash symbol (`#`).

For example...

`{{ jump_link | remove_left:# }}`

... doesn't work, but this does...

`{{ jump_link remove_left="#" }}`

Does Statamic confuse this is being part of a code comment? `{{# #}}`
