### ISSUE TITLE
Unable to access assets containers via cp

### ISSUE THREAD

**Issue by cdransf** [statamic/v2-hub#278]
Whenever I attempt to create or access an assets container via the control panel the page in the control panel simply loads a spinner and does not load the container. This is true of directories where permissions are set to `777` and `755`.

**Comment by jasonvarga** [comment]
Pretty old thread so I'm closing this down. Let us know if you continue to see this problem on the current version.

**Comment by dddom** [comment]
I had a similar issue but after manually changing files and folders in the pages directory. `php please cache:clear` seems to fix it, it's a caching issue.
