### ISSUE TITLE
`$site_root` config doesn't seem to do anything

### ISSUE THREAD

**Issue by paulstraw** [statamic/v2-hub#298]
I was trying to set up a subfolder install, but editing `$site_root` in `index.php` didn't seem to do anything. According to its description, it seems like it's supposed to be the replacement for v1's `_config/settings.yaml` `_site_root` key.

**Comment by jasonvarga** [comment]
Closing this down. For now, subfolder installations aren't supported.

**Comment by paulstraw** [comment]
Totally fair. Sorry I wasn't able to test again sooner. 😱

**Comment by jasonvarga** [comment]
It's okay, it only took us 3 months to give you an answer.

![](http://gif-finder.com/wp-content/uploads/2016/01/Anchorman-2-The-Legend-Continue-Ron-Burgundy-Will-Ferrell-Sorry-Gif.gif)
