### ISSUE TITLE
Better error handling for entry with no template; better docs for entry–template glue

### ISSUE THREAD

**Issue by ldstevens** [statamic/v2-hub#309]
Bit of a story behind this one, which was fleshed out in the Slack channel: https://statamic.slack.com/archives/beta/p1452208126009804 .

I get the difference between pages & collections, and here I'm referring to entries in collections (e.g. a blog). I had the demo site /blog/ template dir in my site, and the demo entries were working there.

And I dug around and found that entries were using the /blog/post.html template by default, just by comparing markup.

So I created newcollection , with an entry newentry, and a template dir newcollection, with an index.html, and was (obviously) getting 404s. I added a post.html; still 404s (from memory). Didn't know how to associate entries with the templates. [I wasn't 100% assuming collection names & template dir names had to be the same.] I dug into routes, and added a route new collection: /newcollection/{slug} , and then got the system error: 

"FatalErrorException in EntriesTags.php line 35: Call to a member function entries() on a non-object / in EntriesTags.php line 35”. 

I expected a warning “Looks like your entry doesn’t have a template specified” or something.

Then I was confused for ages :smile: 

Then I eventually found support Q&A from Jack about needing to specify a template in the entry; and I eventually saw the default templates in the theme settings.

Then I discussed things with Jason in Slack and [he said](https://statamic.slack.com/archives/beta/p1452209880009865):

in `site/content/collections/blog/folder.yaml` we are overriding the `template`

...and that was the missing link to understanding the demo site behavior :) 

So, coming from EE land I'm more used to having "here is all my content, completely independent of my templates" and "here are my templates, completely independent of my content", and then you add the glue in the templates. I realise this ​_can_​ be true of statamic too (i.e. similar {{ entries }}  stuff I guess), but when there's (i) entry-level template setting; (ii) default theme template settings; (iii) collection folder template overrides; and (iv) configurable routes, it makes it pretty confusing for a newb to figure out where the magic happens.

I think a nice trail guide explaining all the relationships/glue here between entries and templates would do the trick :+1: . (Your docs are otherwise lovely, btw!)

**Comment by jasonvarga** [comment]
Closing this down. I opened [an issue on the docs repo](https://github.com/statamic/docs/issues/27).
