### ISSUE TITLE
Replicator fields not being validated

### ISSUE THREAD

**Issue by macbruker** [statamic/v2-hub#345]
I'm trying to get validation rules to work for two text fields in a schedule. 

These are the variants I have tested in the field builder so far. 

```
validate: 'date_format:"HH:MM"'
validate: date_format:HH:MM
```

I also tested editing the yaml file directly to format validation rule like this:

```
validate:
  date_format: "HH:MM"
```

Page editing and saving works, and no validation message is triggered.

**Comment by ndf3** [comment]
Is this issue still open? I'm trying to get validation rules to work for grids and also no validation message is triggered.

**Comment by OlivierVanEester** [comment]
Any news on this one?

**Comment by edalzell** [comment]
If it's still open, it still exists.

**Comment by jackmcdade** [comment]
This turned out to be pretty much an impossibility with our vue.js 1x architecture in v2. It'll be a v3 feature :)
