### ISSUE TITLE
Renaming form field in CP break form CP

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#365]
I have a form field with the following values in the control panel:

Display Text: comment
Field Name: comment
Validation Rules: required

When I change the display text and field name to message and save the associated form .yaml columns aren't updated to reflect the change.

```
columns:
  - name
  - email
  - comment
```

This breaks the form in the cp and I'm unable to click on any of the fields to edit them.

If I change the comment value to message in the columns section then everything works again.

**Comment by andregoldstein** [comment]
I'm having a similar issue. I've renamed a field in the CP (from subject to enquiry_type) but in the table view of submissions it it still showing Subject as a heading and in the configure screen it won't update to show the new options.
