### ISSUE TITLE
Zero-padded numbers have leading zeros stripped

### ISSUE THREAD

**Issue by ldstevens** [statamic/v2-hub#378]
I have a text field where I want to enter numbers padded with leading zeros, e.g. 001, 002, 003. 

If I enter `001` via the CP and hit "Save & Continue", the value is saved as `001`, but the CP shows `1`, and a subsequent save changes the value to `1`. 

The difficulty here seems to be because YAML is parsing it as an integer (when reading it back in, I assume), and stripping the leading zeros, whereas I'm expecting it to be treated as a string.

The ambiguity that a text field can be a string or integer seems like something worth clarifying, but I'm not sure how much you can do if it's an inherent part of YAML. Perhaps a flag to "Always treat as string" means the value will always be quoted when saved via the CP, e.g. `'001'`, or make that the default behavior, and introduce a separate, explicit integer field?

For now I'm just leaving it as an integer, and adding the zero padding in the templates, e.g. to get 01 `{{ if variable < 10 }}0{{ /if }}{{ variable }}`. 

Not a big deal, but just thought I'd mention it!

**Comment by jasonvarga** [comment]
Doesn't appear to be an issue anymore. Reopen if that's the case.
