### ISSUE TITLE
Statamic goes 💀 if a collections .md files do not have an order prefix

### ISSUE THREAD

**Issue by than** [statamic/v2-hub#380]
Should fail gracefully and log an error.

https://statamic.slack.com/archives/beta/p1453931976000979

https://statamic.slack.com/archives/beta/p1453933040001044
# beta14

**Comment by edalzell** [comment]
@than, does this still happen? If not, can you close?

**Comment by jasonvarga** [comment]
Doesn't appear to be an issue anymore. Although, I can't see what's in the slack links.
