### ISSUE TITLE
Modifiers inside tag parameters

### ISSUE THREAD

**Issue by jeffmeier** [statamic/v2-hub#404]
I can't seem to get modifiers to work within single braces.

`{{ theme:partial src="{ type | dashify }" }}` doesn't work (doesn't output anything). I did some testing, but I don't know enough to be thorough about it. I can confirm that `{{ type | dashify }}` works correctly though. And `{{ theme:partial src="{ type }" }}` works well if I just change the name of my partials to have underscores instead of hyphens.

**Comment by jasonvarga** [comment]
Using double curlies will work, although I feel like this is something that won't work in every situation. So, here be dragons, basically.

```
{{ theme:partial src="{{ type | dashify }}" }}
```
