### ISSUE TITLE
Importer: Please wait...

### ISSUE THREAD

**Issue by axelferdinand** [statamic/v2-hub#427]
Installed the exporter addon in latest version of Statamic 1 (v1.11.1), and the export gave me a JSON output. Hurray!

Installed a fresh copy of Statamic v2 (v.16 beta) and pasted the content of the export, and hit the button. After 10 mins, still nothing has happened, and not a single file is created in either assets or site/content/pages or site/content/collections.

Please wait...

**Comment by jasonvarga** [comment]
Closing as I believe this has been addressed. Let us know if that's not the case.
