### ISSUE TITLE
Log file created with tomorrow's date

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#458]
### Steps to reproduce
1. Make Statamic generate an error, and therefore an error log
2. Look at the file name
### Expected behaviour

Filename should have todays date
### Actual behaviour

![logs 2016-02-19 20-31-40](https://cloud.githubusercontent.com/assets/6069653/13194459/eed1ba88-d747-11e5-8081-7ce9b1e9a75f.png)

**Comment by edalzell** [comment]
Looks fine right now.

**Comment by edalzell** [comment]
Happening on my live site

**Comment by edalzell** [comment]
Regarding #927, if I set the `timezone` in my settings, the actually message is timestamped correctly but the file is created incorrectly.

**Comment by edalzell** [comment]
I don't have the `timezone` set in my `system.yaml` and your boot loader uses that:
```
        // Set the timezone. Override Laravel's config, and set in PHP
        config(['app.timezone' => Config::get('system.timezone')]);
        date_default_timezone_set(config('app.timezone'));
```

**Comment by edalzell** [comment]
This still occurs for me...

**Comment by jackmcdade** [comment]
Alrighty.

**Comment by edalzell** [comment]
See name of file and screenshot.

[statamic-2017-02-02.log.zip](https://github.com/statamic/v2-hub/files/746827/statamic-2017-02-02.log.zip)

**Comment by edalzell** [comment]
![system yaml - v2 - sitesv2 2017-02-01 20-38-05](https://cloud.githubusercontent.com/assets/6069653/22537297/5fda5068-e8be-11e6-82d8-f72b7736da68.png)

**Comment by edalzell** [comment]
OK more debugging:

```
   protected function registerStreamHandler($config)
    {
        dd(date_default_timezone_get());
```

Produces `UTC`. So this is being called either *before* the boot loader that sets it, or, default timezone gets reset by the time it's called here.

**Comment by edalzell** [comment]
Yup, Logging is done in `app.php`, line 68:

```
$app->configureMonologUsing(function($monolog) {
    new Statamic\Logging\LoggingHandler($monolog);
});
```

Which I suspect is *before* this gets called:

```
class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     */
    public function boot()
    {
        // Set the site's locale
        site_locale(LOCALE);

        // Set the timezone. Override Laravel's config, and set in PHP
        config(['app.timezone' => Config::get('system.timezone')]);
        date_default_timezone_set(config('app.timezone'));
```

**Comment by edalzell** [comment]
Just move this code:
```
       // Set the timezone. Override Laravel's config, and set in PHP
        config(['app.timezone' => Config::get('system.timezone')]);
        date_default_timezone_set(config('app.timezone'));
```

To app.php.

**Comment by jackmcdade** [comment]
Unfortunately I spoke too soon. It's not working yet...

**Comment by jasonvarga** [comment]
I could never replicate the behavior of the future logs, but at the location in @edalzell 's [comment](https://github.com/statamic/v2-hub/issues/458#issuecomment-276867735), the right timezone is now reflected.

**Comment by edalzell** [comment]
for you @jasonvarga, you'd have to have no log file and try it after 7pm your time I think, in order to get the next days date.
