### ISSUE TITLE
RFE: Can We Keep a Record of User Actions?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#479]
A client (large volunteer organization) would like to know when users log in and out, as a way of getting a feel for which of their volunteers/members are more active. (Or _in_active.)

A simple log file scroll containing Date-time, UserID/Email, and Action (In/Out) ought to be sufficient.

---

More generally, It would be mighty nice to have the option of loggin _all_ major user actions. Not browsing, of course, but things like who posted a blog article when, who deleted such-and-so's account. Those could be handy things to know, eh?

With an on/off switch set by the Site Admin...  etc.,...

You get the idea. :-)

**Comment by lesaff** [comment]
Update on this. Currently logging 
- login
- logout
- failed login
- published entry (page, collection, taxonomy, global, user)

There are more events that I want to track but still waiting for them events to be added to the core.

![screen shot 2016-07-14 at 11 49 06 am](https://cloud.githubusercontent.com/assets/1151181/16843837/3a13596e-49b9-11e6-85ab-5ddceeec8cfe.png)
