### ISSUE TITLE
Multilang setup: Assets not outputed in second locale version

### ISSUE THREAD

**Issue by subpixelch** [statamic/v2-hub#485]
### Steps to reproduce
1. Statamic multilanguage setup: First local: DE / Second local: EN (setup as described [here](https://gist.github.com/jasonvarga/05a6332924717e0db64f/revisions) )
2. Pages with text + assets (Images)

### Expected behaviour
xxx.com -> shows the text (local DE) and images ( ```{{ image_var|url }}``` )
xxx.com/en -> shows the text (local EN) and images (same as above)

### Actual behaviour
xxx.com -> perfect

![image](https://cloud.githubusercontent.com/assets/5087726/13358111/ef7e4a08-dcad-11e5-8e31-cb3e7a00b9fd.png)

![image](https://cloud.githubusercontent.com/assets/5087726/13358154/22505412-dcae-11e5-9a06-b762852e2b28.png)

xxx.com/en -> shows the text (local EN) but **not the images** ( ```{{ image_var|url }}``` doesn't get rendered at all ```<img src="">```-> if it's only an ID ```{{ image_var }}``` it get's outputed ```<img src="id">```)

![image](https://cloud.githubusercontent.com/assets/5087726/13358094/e0b59a8a-dcad-11e5-8ff8-99eb34752d7c.png)

![image](https://cloud.githubusercontent.com/assets/5087726/13358165/33e39072-dcae-11e5-9fa5-9e69777eafad.png)

### Server configuration
**Operating system**: Ubuntu 14.04 x64

**Web server:** Apache with Nginx as Reverse Proxy (Serverpilot-Setup)

**PHP version:** 7.0.0

**Statamic version:** b17

**Updated from an older Statamic or fresh install:** Fresh install

**List of installed addons:** none

#### Web server error log
```
nothing, no error is outputed
```

#### Statamic error log (`/local/storage/logs/statamic.log`)
```
nothing, no error is outputed
```

#### Browser log
```
nothing, no error is outputed
```

**Comment by ItsMeAra** [comment]
mentioned this in slack but thought I'd put it here too. Hoping this gets resolved soon as it essentially makes multi language support not possible. 


When viewing a blog post on a /de/ locale url I'm running into the following issues with loading images:

<img src="{{ intro_image | url }}" class="intro-image">
compiles to:
<img src="effa7c0e-27a4-403f-a8d3-f0ecddcc94d0" class="intro-image">

it doesn't seem to supply a path or anything, it just returns the image ID. it works as it should in normal english version, with the full path to the correct image.


<img src="{{ glide:intro_image width='140' height='140' fit='crop' filename='bacon.jpg' }}" width="140" height="140" class="small-image">
compiles to:
<img src="/de/img/id/effa7c0e-27a4-403f-a8d3-f0ecddcc94d0/bacon.jpg?w=140&amp;h=140&amp;fit=crop&amp;s=4999bcaaa0845b950d720ca41afc2e93" width="140" height="140" class="small-image">

Same issue i was having with the CSS path, it adds '/de/' at the beginning of the image path, so it's linking to an image that is not there. Is there a way i can get around this without having to enter the correct paths manually? 

This is all on the same page, running the default redwood theme and content.

**Comment by lesaff** [comment]
I also use Server Pilot . My current workaround is to symlink assets to each locale folder.

**Comment by ItsMeAra** [comment]
I tried to go down the symlink route but couldn't get things to work correctly.
