### ISSUE TITLE
Page duplicates in the cp when dragging onto the home page

### ISSUE THREAD

**Issue by stevieg83** [statamic/v2-hub#500]
### Steps to reproduce
1. create a page
2. drag that page onto the home page
3. notice dupe page appears
4. refresh and its gone

http://d.pr/i/11Zic

### Expected behaviour
I'd expect nothing to happen

### Actual behaviour
Ultimately nothing, other than the cp display what looks like another page but it doesn't actually exist

### Server configuration
El Capitan

**Web server:**
Apache
**PHP version:**
7.0.0
**Statamic version:**
beta.19
**Updated from an older Statamic or fresh install:**
updated
**List of installed addons:**

**Comment by stevieg83** [comment]
looks like this has resolved

**Comment by jasonvarga** [comment]
Gotta love when issues close themselves.
