### ISSUE TITLE
Cannot edit pages that are drag-droppable on touch

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#517]
In Pages it seems that rows that have drag-drop re-ordering prevents the links on that row from being selected (home page which can't be reordered works fine):
- tapping on the page name doesn't go into the edit screen
- tapping the child-page arrow doesn't expand/collapse child pages
- tapping the link doesn't load a preview
- tapping on the 3 dots doesn't show the create/delete menu

Drag-drop works great though!

**Comment by jackmcdade** [comment]
This was fixed a few releases ago. 👍
