### ISSUE TITLE
Password reset returns invalid code message

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#521]
When clicking the password reset link via email, it returns an invalid code message.

![screen shot 2016-03-07 at 1 20 33 pm](https://cloud.githubusercontent.com/assets/1151181/13577210/b69e492e-e467-11e5-8ad2-409078fb8b58.png)

**Comment by deepsurface** [comment]
Seeing this too. Perhaps this is a separate issue, but If I use the "copy reset link", it contains an example.com domain. If I change it to the accurate domain after pasting, I get the Invalid code error.

**Comment by jasonvarga** [comment]
If your locales are set up correct in the first place, does it work for you? Settings > System. (That's where the example.com is coming from.)

**Comment by lesaff** [comment]
Just tested on v2.0.0 and it works fine. The original issue was on the b19 or b20.

**Comment by deepsurface** [comment]
@jasonvarga Fixing the site name in Locales did correct the URL, but I still get an invalid code message when following the link.

**Comment by jasonvarga** [comment]
Are your users writable? Did the user get a `_reset_code` added to their file?

**Comment by deepsurface** [comment]
Yes.

**Comment by jasonvarga** [comment]
Closing as this is so old. Let us know if it happens again.
