### ISSUE TITLE
Ability to use dates as conditions

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#522]
### Steps to reproduce
1. have date fields you want to use in your collection conditions
### Expected behaviour

Can use things like `is_before`, `is_between`, etc
### Actual behaviour

Can't

Maybe a smaller step towards #520?

**Comment by jackmcdade** [comment]
You've always been able to do `since` and `until`. Is that what you mean?

**Comment by jasonvarga** [comment]
I think since and until only use the date of the entry. He wants to use arbitrary fields.

**Comment by jackmcdade** [comment]
You can do stuff like this for now:

```
{{ collection:blog as="entries" }}
  {{ entries is_before="before_date_var" is_after="after_date_var" }}
    ...stuff...
  {{ /entries }}
{{ /collection:blog }}

**Comment by edalzell** [comment]
That's the entry date @jackmcdade, I'd like to use arbitrary date fields *in* the entry

**Comment by jackmcdade** [comment]
Nevermind me.
