### ISSUE TITLE
Settings set in .env or environments should still show its values

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#527]
When settings are set from `environments` or `.env`, currently you get a message that says 
`Managed externally by your environment`

I think the value for each field should also be visible even though it's not editable.

What do you think?

![screen shot 2016-03-09 at 9 40 20 am](https://cloud.githubusercontent.com/assets/1151181/13636965/181b5466-e5db-11e5-863e-547298743f37.png)

**Comment by jackmcdade** [comment]
In general, the reason this is hidden is for security. Therefore, if it's too secure to add to your repo, it stands to reason it's best to not show it at all.
