### ISSUE TITLE
Replicator fieldtype functionality

### ISSUE THREAD

**Issue by Burans** [statamic/v2-hub#543]
### Actual behaviour

You can currently add new sets at the bottom of the replicator and reorder them. This works fine if you only have couple of sets but gets painful if you have dozens and you want to add a new ones somewhere in the middle / at the top.
### Expected behaviour

It would be nice to have an option to add new sets directly between two existing ones.

**Comment by anthubbard** [comment]
Yep. Please do this.

**Comment by jasonvarga** [comment]
Added in 2.6.3

**Comment by anthubbard** [comment]
&#128525;
