### ISSUE TITLE
Improve OldTags.php so that it can look up array values with a single tag

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#553]
The Old Tag doesn't work with array values when using a single tag, but it easily could.

``` php
<?php

namespace Statamic\Addons\Old;

use Statamic\Extend\Tags;

class OldTags extends Tags
{
    public function __call($method, $args)
    {
        return array_get(old(), substr($this->tag, 4));
    }
}
```

---

Right now, it's possible to look up array values by looping over the array, but that gets messy when using in a tag.
#### Currently works

``` html
{{ old:arr }}
  {{ my_var }}
{{ /old:arr }}

{{ addon attr="value:{old:arr}{my_var}{/old:arr}" }}
```
#### With above code

``` html
{{ old:arr:my_var }}
{{ addon attr="value:{old:arr:my_var}" }}
```

**Comment by jasonvarga** [comment]
Old data is now just an array in the context since 2.6.4. The tag has been removed.
Should be easier to work with now.
