### ISSUE TITLE
Allow all/most Statamic config to be editable in .env file

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#557]
Proposed `.env` file
https://gist.github.com/lesaff/53aab531ee643767dae6

Edited `config` files
https://s3-us-west-2.amazonaws.com/adnet-s3/download/config.zip

**Comment by jackmcdade** [comment]
That feels way more complicated than it needs to be. I'd like to cater to the 85% of use cases.

**Comment by lesaff** [comment]
I just want to be able to edit most of Statamic configuration from `.env` file. If you guys have a cleaner/simpler idea, that's even better. 👍

**Comment by jackmcdade** [comment]
Have your own default `.env` you drop in?

**Comment by jackmcdade** [comment]
No i mean you just drop your .env file in. We ship with a sample, you have to make your own anyway.

**Comment by jasonvarga** [comment]
I think the feature request is that we make the config values editable in `.env`, not to actually ship his `.env` with Statamic. Right?

**Comment by jackmcdade** [comment]
Ah that would make more sense, but totally escaped me. Wanna confirm rudy, and chance the title?

**Comment by lesaff** [comment]
@jasonvarga is correct. Let me update the title. Thx for clarifying

**Comment by lesaff** [comment]
To add to this discussion. Here's a use-case scenario that we're (Adnet) actually facing:

We use `redis` to store/manage our `session` and `cache` for all of our v2 sites. We have to update `statamic/config/cache.php` and `statamic/config/session.php` manually so that we can change the cache-key prefix to prevent sites from sharing cache data from redis.

Thx

**Comment by jackmcdade** [comment]
We don't have plans to change configs further in v2 as they're getting an overhaul in v3. You set ENV vars and use them in your config settings, so at least in that way the option _is_ there.
