### ISSUE TITLE
Content::entryExists() keeps returning true if collection is not empty

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#559]
### Steps to reproduce
1. See screen cap below

![debug](https://cloud.githubusercontent.com/assets/1151181/13989910/11435a32-f0f1-11e5-95f6-4db97627bd91.gif)
### Expected behaviour

Should return `false` when parsed entry from input is not found in the collection
### Actual behaviour

Keeps returning `true`
### Current workaround

```
// Check the haystack
if (is_array(Content::entryRaw($slug, $collection))) {
    $haystack = Content::entryRaw($slug, $collection);
} else {
    $haystack = Content::entryRaw($slug, $collection)->toArray();
}

// Check if entry already exist
if (in_array($slug, $haystack) == false) {
    $this->createEntry($title, $slug, $summary, $entry);
}
```

**Comment by jasonvarga** [comment]
Appears to be fixed.
