### ISSUE TITLE
FR: Conditional field type

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#562]
Would it be possible to have a conditional field type, where based on selection, a set of field type(s) can be displayed or hidden.

In example below, if user selects `Mailchimp`, only Mailchimp section should be displayed and hide the rest, and vice versa.

![screen shot 2016-03-29 at 12 12 54 pm](https://cloud.githubusercontent.com/assets/1151181/14113089/d4751b2a-f5a7-11e5-9e0d-6486a26dc65a.png)

**Comment by Rafache** [comment]
Great feature !

**Comment by Rafache** [comment]
Is it possible to do it via an addon ? maybe a vueJs custom script ?

**Comment by cujojp** [comment]
+1 This would be fantastic!

**Comment by ndf3** [comment]
+1

**Comment by edalzell** [comment]
@Rafache I have done this in my own addons by building my own fieldtype. It's just tough to make generic.

**Comment by rockethouse** [comment]
+1 This is a must, only just realised it doesn't exist and I need it!

**Comment by Synergy23** [comment]
+1 crying out for this. Probably one of the best features in ACF.
