### ISSUE TITLE
Section field type used inside Partial is not flush

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#565]
When using a Partial, you might want to add a Section title. But when Sections are used inside partials they are not flush with the panel's edge.
 
![screenshot 2016-03-30 12 29 16](https://cloud.githubusercontent.com/assets/414211/14154872/c63abfc0-f673-11e5-91b3-69415fe35388.png)

### Steps to reproduce
1. Create a partial with Section fieldtype
2. Add partial to Fieldset
3. View fieldset on edit page screen

**Comment by aryehshai** [comment]
@mikemartin: Which Statamic version are you on? I had the same problem in B20, but the 2.0 release version fixed this for me. cc/ @jasonvarga
