### ISSUE TITLE
CP sidebar should show logged-in username, not just "My Account"

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#566]
Down at the bottom left of the CP sidebar, if there's no user photo (for whatever reason) you get the broken image icon (or the generic Gravitar icon—I've seen both)—which is OK. However, you're also left guessing as to who you're logged in as. Not such a good thing.

Now, you might think: "Och, dis vill neffer haapen."

Wanna bet? ;-)

And, yes, "My Account" is a link you can follow to find out who you are, but why not just show me?

**Comment by jackmcdade** [comment]
Because some names are really long, and "My Account" is easily translated.
