### ISSUE TITLE
Double 'title' field in CP

### ISSUE THREAD

**Issue by aryehshai** [statamic/v2-hub#568]
Since upgrading to v2.0 I'm seeing a double `title` field in the CP.

FYI: a clean install doesn't seem to have the issue, only my upgraded site.

<img width="326" alt="screen shot 2016-04-02 at 01 37 32" src="https://cloud.githubusercontent.com/assets/5065331/14222649/67c8d11e-f873-11e5-871f-7de3b124602a.png">

**Statamic version:**
Statamic 2.0
**Updated from an older Statamic or fresh install:**
Updated

**Comment by jasonvarga** [comment]
For anyone with the same problem, this is when you have a partial. Working on it.

**Comment by jasonvarga** [comment]
Hey @aryehshai when you said a clean install doesnt have the same issue, are you using the same fieldset on both sites?

**Comment by aryehshai** [comment]
At the time of writing that, I didn't know it was linked to Partials. The clean install was just using the theme and data Statamic ships with, i.e. not using a Partial.

**Comment by jasonvarga** [comment]
That's what I thought. Just checking!
