### ISSUE TITLE
favicon.ico shows as broken image in assets

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#569]
### Steps to reproduce

Upload a favicon.ico to your assets.
### Expected behaviour

A thumbnail of the favicon.ico should show. That or if the asset ends in .ico just show a blank image or other generic thumbnail.
### Server configuration

**Operating system**:
OSX, Linux, Homestead

**Web server:**
nginx

**PHP version:**
7+

**Statamic version:**
2.0

**Updated from an older Statamic or fresh install:**
Fresh.

**List of installed addons:**
None.
#### Web server error log

```
Nothing in the log file.
```
#### Statamic error log (`/local/storage/logs/statamic.log`)

```
Nothing in the log file.
```
#### Browser log

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://statamic-site-template.local:8000/resources/cp/img/filetypes/ico.png Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by lesaff** [comment]
Best practice for `favicon` is to be stored either on the root of your site (this is where browsers look for it by default, or in the `theme` folder.

**Comment by jasonvarga** [comment]
We have a bunch of file-type icons. We didn't have an `ico` one. We'll need to either add one, or add a catch-all. :+1:
