### ISSUE TITLE
Fatal error: Call to a member function permissions() on null

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#571]
### Steps to reproduce
1. Open custom addon view
2. Leave it until session expired
3. Refresh the page

### Expected behaviour
It should redirect back to the login page to re-authenticate.

### Actual behaviour
Fatal error: Call to a member function permissions() on null.

<img width="977" alt="screen shot 2016-04-03 at 6 52 52 pm" src="https://cloud.githubusercontent.com/assets/1151181/14235236/8df3f718-f9ce-11e5-87d8-b605f76bb819.png">

I have the full stack if needed

**Comment by jasonvarga** [comment]
Dupe of #150
