### ISSUE TITLE
CSS classes on fields and fieldsets in CP

### ISSUE THREAD

**Issue by okse** [statamic/v2-hub#575]
We want to customize the design on some of the fields and fieldsets in the control panel. It would be nice to have some CSS classes (typically named after the handle) to help us do that :)

**Comment by jackmcdade** [comment]
I hear ya (not a bad idea either) but could you mind sharing why a particular element needs customizing? Maybe it's something that should be core?

**Comment by stevieg83** [comment]
There's been times for me where elements get bunched together with no padding/margin. 

In those cases it's been when I've set width of partial and then specific widths of the fields within the partial.

**Comment by jackmcdade** [comment]
Sounds like a bug - if we get details we can fix that :)

**Comment by okse** [comment]
It's for simple, custom adjustments. For instance we've got a fieldset that's image left and text right, where it would be good to actually have the image part on the left side and the text part on the right side.

Also for simple changes like slightly different background color on specific fields to easier identify them when editing a page.

This also reminds me that it would be great to have a CSS class on the buttons in the replicator button group (to separate by color, add icons etc.).

By the way, not related, but I can't get the "Width" thing to work in a replicator set (or in fieldsets, I haven't wrapped my head properly around where the issue is). On top level fields it seems to work fine, but in replicators/fieldsets it respects the width, but the elements stack over/under instead of next to each other. Should I submit a new issue on that, maybe? ;)

**Comment by jasonvarga** [comment]
Each field is already wrapped in a `<div class="name_of_fieldtype-fieldtype" />`. eg. `markdown-fieldtype`.

But yeah we can do that.

**Comment by andregoldstein** [comment]
Not sure if it's related @jasonvarga but think there is a margin issue inside replicators. See attached:

![screen shot 2016-08-17 at 11 05 39](https://cloud.githubusercontent.com/assets/7061578/17730771/acef9832-646a-11e6-8674-c4d432921ed7.png)

**Comment by jackmcdade** [comment]
Fixed for next release.

**Comment by jackmcdade** [comment]
This is all pretty much sorted at this point.
