### ISSUE TITLE
Immortal Ghost of Widget Past?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#577]
### Steps to reproduce
1. Default 2.0.0 install.
2. Open CP, observe dashboard shows two widget summaries for Blog and Things collections.
3. Navigate to `/cp/collections` and tap `Manage Collections`.
4. Delete “Things” collection.
5. Return to `/cp/dashboard`

### Expected behaviour
Widget whatnot should be smarter, and not display a header for a non-existent collection.

### Actual behaviour
 Observe “Recent Entries” header for deleted collection is still there. NB.  `php please cache:clear` does not resolve this. (BTW, US English spelling is “behavior,” without the “u”; although without YOU, where would we be?! ;-)

**Comment by jasonvarga** [comment]
Go to Settings > Control Panel and remove the widget.

**Comment by iDGS** [comment]
Like this?
```
- 
  type: collection
  collection: things
  limit: 0
  width: 0
```

(Naw, I know what you mean. :-) 

FWIW, the docs' references to “dashboard” are kinda oblique. The Dashboard is a super-nice feature, which IMHO deserves it's own intro/overview somewhere. (Now seems to be only found under Forms or Widgets.)  Just sayin’...
