### ISSUE TITLE
Remembering collapsed state when editing page/entry in CP

### ISSUE THREAD

**Issue by okse** [statamic/v2-hub#578]
We have a fieldset where part of the page is a 'Related Magento products' replicator. This takes up quite a bit of screen space on the top of a page and I prefer to collapse the products. It would be nice if it remembered to stay collapsed the next time I opened the page. Medium annoyance – no biggie.

![image](https://cloud.githubusercontent.com/assets/17156984/14276248/f8536f12-fb1d-11e5-96f3-c0a3844c7548.png)

PS: You can see in the screenshot the width/column issue on fields/fieldsets/replicator I mentioned in #575 .
PPS: I don't think I have permission to add labels on these issues?

**Comment by lukeagsmith** [comment]
+1

Also remembering the collapsed state in other places such as the pages list would be a nice improvement too.
