### ISSUE TITLE
Date/time fields get squeezed on sneak peek mode

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#582]
### Steps to reproduce
1. Open any page/entry with date and time
2. Click on sneak peek button

![screen shot 2016-04-05 at 2 38 08 pm](https://cloud.githubusercontent.com/assets/1151181/14291963/49481666-fb3c-11e5-8530-1651fdd92324.png)

### Expected behaviour
Perhaps the time field should drop under the date field? 

### Actual behaviour
See screenshot

**Comment by jackmcdade** [comment]
Looks sexy.
