### ISSUE TITLE
RFE: Set Cookies Timeout Expiration (etc.) via `.env`

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#584]
### Request For Enhancement:

User/customer wants the login timeout to be a month. O-kaaaaay... At present (v2.0.0) I think it's set for half an hour (?) and the only place to change that cookie lifetime stuff is \*gasp\* inside the _system_ itself!  Per Rudy’s comment on Slack:

> @idgs, in the `statamic/config/session.php` line 32, if you change it to
``` 
'lifetime' => env('SESSION_LIFETIME', 120),
'expire_on_close' => env('SESSION_EXPIRE_ON_CLOSE', false),
```
you can then access them from your `.env`

Me, I'm desperately allergic to that kind of solution, as I'd have to keep modifying the source code with every update.

_MUUUUCH_ better if you gents do it, ja? And give us a spiffy example in the docs? :-)

Plus I've been told there's more stuff stuffed away in yon system that would likewise be nice to access via said `.env` method. (Pretty please?)

**Comment by jasonvarga** [comment]
Will be in 2.0.1
