### ISSUE TITLE
Cannot run Vue components in the addon (except in the fieldtype)

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#586]
### Steps to reproduce
1. Create a simple widget addon (just for simplicity purpose, can be any addon with cp page)
2. Add js to the bottom of the cp page (for now, this is the only way to do it https://github.com/statamic/v2-hub/issues/544)
3. Instantiate `Vue.component('your-component', yourComponent);`. Do something like `alert()` or something that gives you instant feedback
4. Add the appropriate tag to your widget blade view

### Expected behaviour
Alert window should pop up

### Actual behaviour
CP strips out all `v-` and ignore the newly added component

### Server configuration
**Operating system**: El Capitan [latest]

**Web server:** MAMP Pro 3.5

**PHP version:** 7.x

**Statamic version:** 2.0.0

**Updated from an older Statamic or fresh install:** updated from b20

**List of installed addons:**
a bunch of custom-made addons

**Notes**
No JS error

**Comment by lesaff** [comment]
I found out why my addon vue component wasn't parsed by the cp. Initially, I loaded my addon js after `jabbascripts`. Turns out, it has to be loaded before `jabbascripts`

Not sure whether I should close this or leave it for others?

**Comment by lesaff** [comment]
my `scripts.blade.php` looks like this now
```
<script src="{{ cp_resource_url('js/johnny-deps.js') }}?v={{ STATAMIC_VERSION }}"></script>
<script src="{{ cp_resource_url('js/cp.js') }}?v={{ STATAMIC_VERSION }}"></script>
{!! $fieldtype_js !!}
{!! $layout_foot !!}
<script src="{{ cp_resource_url('js/jabbascripts.js') }}?v={{ STATAMIC_VERSION }}"></script>
```

**Comment by jasonvarga** [comment]
For the next release, any `YourAddon/resources/assets/js/scripts.js` will get added to the cp automatically. No need for any events.

Write JS directly into there, or adjust your build process to output that file. If it exists, it'll get loaded.
