### ISSUE TITLE
Fatal error clicking on the Pages submenu with another locale set in index.php

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#587]
### Steps to reproduce
1. In /statamic/resources/lang/ , I put a `fr` folder alongside the `en` folder
2. I modified the index.php file found at the root of my site in order to put `$locale = 'fr';`
3. I logged into the CP
4. I clicked on the Pages submenu

### Expected behaviour
not a fatal error, just as when you click on the Collections submenu

### Actual behaviour
Fatal error

### Server configuration
MAMP PRO 3.5

PHP 7.0.0

2.0.0

Fresh install

#### Statamic error log (`/local/storage/logs/statamic.log`)
```
[2016-04-06 19:33:56] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to a member function hasEntries() on null in /Users/efb/Sites/statamic2/statamic/core/Http/Controllers/PagesController.php:31
```

**Comment by jasonvarga** [comment]
Did you clear your cache after you changed the locale? `php please clear:cache`

**Comment by ebeauchamps** [comment]
Yes,I think so, I reproduced this error after clearing the cache

**Comment by jasonvarga** [comment]
Ok, thanks

**Comment by ebeauchamps** [comment]
Cannot reproduce this in 2.1.13
Furthermore, there is no need to  change the locale in index.php: just change it in the user file by adding `locale: fr` for example. Don't forget to create a `lang` folder in `site` and to put your own translation for the cp there (for example: `site/lang/fr`)
