### ISSUE TITLE
FR: Possibility to make "Save and continue" the default, instead of "Save"

### ISSUE THREAD

**Issue by eminos** [statamic/v2-hub#590]

**Comment by kretzm** [comment]
+1 to this.

Rather the "save" functionality be the same as the "save and continue" functionality. It's very annoying to save your work then to be taken out of that page. If there is no autosave feature then I would expect to click on "save" which would then asynchronously save my current work and let me continue editing (as mentioned by eminos in #591).

**Comment by lesaff** [comment]
There is the `Cmd-S for OSX or Ctrl-S for Windows` keyboard shortcut that is available in the CP. It's equivalent to save and continue. 

I agree, Auto-save is a good feature to have.

**Comment by jeremydouglas** [comment]
Woo! I have high hopes for "save and continue" to be the default for editing entries.

**Comment by stevieg83** [comment]
would be great to see 'save and add another' as well

**Comment by jasonvarga** [comment]
In the next release (2.5.5), your most recent "save" or "save and continue" selection will be treated as the default.

So click save and continue once, then the button will change.
Also, cmd+s has always saved and continued.

**Comment by stevieg83** [comment]
@jasonvarga are we going back in time?

**Comment by jasonvarga** [comment]
D'oh.

![](https://www.appliancesonline.com.au/academy/wp-content/uploads/2016/05/homer-toaster-gif.gif)
