### ISSUE TITLE
Unusable on Windows IIS: Assets

### ISSUE THREAD

**Issue by sunkist** [statamic/v2-hub#595]
Assets essentially unusable on a fresh install of the Trial Version of Statamic v2 on Windows Server 2012 R2 with PHP and file permissions properly configured.

When one browses to the Gallery Page it causes an exception. The problem appears to be the file path of the image and possibly the use of "/" instead of "\" for the Windows OS.

![gallery-error](https://cloud.githubusercontent.com/assets/2044049/14395664/f4513afe-fda0-11e5-8f6b-057fcdc2c4b3.png)

Uploading an image via the control panel doesn't work either. I suspect this is related to the directory paths, etc. When you upload an asset it just spins and spins and never completes the actual upload.

![file-uploads-not-working](https://cloud.githubusercontent.com/assets/2044049/14395713/4b687208-fda1-11e5-8386-bab330f42418.png)

These are show stoppers.

**Comment by steffendb** [comment]
Same issue running WAMP.

**Comment by burriet** [comment]
same issue using xammp

**Comment by coolki** [comment]
Same issue using MAMP Pro for Windows (7 & 10).

**Comment by jackmcdade** [comment]
Fixes for Windows coming ASAP. It's a global Windows thing.

**Comment by coolki** [comment]
Awesome, thanks @jackmcdade - p.s. Almost saved enough to buy a replacement Macbook ;) lol

**Comment by jackmcdade** [comment]
lol now there's a great bug fix ;)

**Comment by coolki** [comment]
@jasonvarga I can confirm that this is now fixed! Many thanks for all the hard work :)
