### ISSUE TITLE
Unusable on Windows IIS: Updater Error

### ISSUE THREAD

**Issue by sunkist** [statamic/v2-hub#596]
Updater essentially unusable on a fresh install of the Trial Version of Statamic v2 on Windows Server 2012 R2 with PHP and file permissions properly configured.

Click on the Update Link and one receive this error.

![updater-error](https://cloud.githubusercontent.com/assets/2044049/14395983/00c1987c-fda3-11e5-9e51-735d69a2235b.png)

I looked up error 60 and it says:

CURLE_SSL_CACERT (60)
Peer certificate cannot be authenticated with known CA certificates.

I'm not sure if this a configuration error or bug, but updater really needs to work.

**Comment by steffendb** [comment]
I had this problem. Running WAMP. Googled it and found a solution in the comment section [here](https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate).

**Comment by Sven0188**

> I had the exact same but on Windows & xampp. My solution was as simple as: Follow this link: http://curl.haxx.se/ca/cacert.pem Copy the entire page and save it in a: "cacert.pem" Then in your php.ini file insert or edit the following line: curl.cainfo = "[pathtothisfile]\cacert.pem"

**Comment by jackmcdade** [comment]
@sunkist did you try @steffendb's suggestion?
