### ISSUE TITLE
Using varying widths on different fieldtypes inside a replicator messes up layout

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#597]
Title is a little confusing, but I think these screenshots will help understand the issue:

Messed up layout:
![wrong](https://cloud.githubusercontent.com/assets/5065331/14405697/5389432e-fe94-11e5-991e-b357a32816c7.jpg)

It seems this is happening because each fieldtype is wrapped in a `col-md-x` that differs in height from it's siblings. This doesn't happen outside of a replicator because there seems to be some different wrapping going on using flexbox instead of columns.

I tweaked the DOM and wrapped each set of columns (that added up to 12) inside their own `row`. This fixed the issue:

Expected layout:
![correct](https://cloud.githubusercontent.com/assets/5065331/14405700/6dc4ca24-fe94-11e5-9ac9-c6afe42d10c6.jpg)

![dom](https://cloud.githubusercontent.com/assets/5065331/14405726/323d5c9a-fe95-11e5-9975-f0cea5e7b278.jpg)

**Comment by jackmcdade** [comment]
Yeah, don't do that. :) For the duration of 2.x, it will be grid based like this.
