### ISSUE TITLE
Can't delete anything but pages from CP (403 error)

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#598]
### Steps to reproduce
1. Create an entry in a collection/taxonomy/assets
2. Try to delete via CP
3. Get a 403 forbidden error
### Notes
- Only happens on the production server.
- I've triple checked the permissions — all files & folders are on `777`.
- Pages delete without a problem, it only happens to other types of content (collection entries, taxonomies, assets)
### Server configuration

**Operating system**:
Linux
**Web server:**
Apache
**PHP version:**
5.5.34
**Statamic version:**
2.0.1
**Updated from an older Statamic or fresh install:**
Updated
#### Browser log

```
Request Method:DELETE
Status Code:403 Forbidden
```

**Comment by jackmcdade** [comment]
Is this still an issue?

**Comment by aryehraber** [comment]
Can't recreate anymore. Thanks for checking!

**Comment by shabbarabbas** [comment]
I am having same issue what is the resolution ?
