### ISSUE TITLE
Focus the username field of the form on the login page

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#599]
### Steps to reproduce
1. Go to the login page at http://yourwebsite.com/cp/auth/login.
2. It would be awesome if the username field had the cursor already in it.

### Expected behaviour
See above.

### Actual behaviour
No cursor. :(

### Server configuration
**Operating system**:
All.

**Web server:**
All.

**PHP version:**
All.

**Statamic version:**
Bleeding edge.

**Updated from an older Statamic or fresh install:**
Both.

**List of installed addons:**
None.

#### Web server error log
```
N/A.
```

#### Statamic error log (`/local/storage/logs/statamic.log`)
```
N/A.
```

#### Browser log
```
N/A.
```

**Comment by edalzell** [comment]
Related to #136?

**Comment by thestepafter** [comment]
From a technical perspective it is similar functionality but I don't believe it is related.

**Comment by eminos** [comment]
The first comment of #592 . Kind of related issue too.
