### ISSUE TITLE
Could not find files to load the `numberFormat` modifier.

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#600]
### Steps to reproduce
1. Use `number_format` modifier

### Expected behaviour
Should format the variable 

### Actual behaviour
Getting a notice error

```dev NOTICE Could not find files to load the `numberFormat` modifier.```

**Comment by jackmcdade** [comment]
There is no numberFormat modifier. Is that an addon of yours?

**Comment by jackmcdade** [comment]
Was actually `format_number`. Docs updated.
