### ISSUE TITLE
FR: Add ability to scan assets folder and generate ID for manually added files

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#602]
It would be great if asset manager can scan `assets` folder and generate ID for manually added files.

**Comment by deanwhillier** [comment]
I second that! Perhaps have some kind of 'incoming' folder that files can be dropped in and then the CP could present an interface for importing them as if they were uploaded directly.

**Comment by jackmcdade** [comment]
Never closed this. Oops. Enjoy the `Sync Assets` button!
