### ISSUE TITLE
Asset fields with null values causes error & loading spinner

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#603]
### Steps to reproduce
1. In the CP, save a page / entry / global with an asset fieldtype with nothing set
2. Reload that page / entry / global and that asset field will have a loading spinner 
3. User cannot 

### Expected behaviour
The standard asset picker should be available. 

FYI, use case: Two asset fields to allow users to add icons to external links for social media, etc: 
- one for SVGs 
- one for a PNG fallback (which they *may* not use)

### Actual behaviour
content file:
```
external_links:
  -
    link_icon_svg: 8ed18e74-e078-4bd5-a038-b0705b435bc7
    link_icon_png: null
```

loading icon

![asset-loading-but-nothing-there](https://cloud.githubusercontent.com/assets/3920126/14567499/3f6940a0-032c-11e6-8dcc-1f5190b97a31.png)

### Server configuration
**Operating system**:
Linux
**Web server:**
Apache
**PHP version:**
5.6
**Statamic version:**
2.0.1

#### Browser log
```
ErrorException in LocalizedAssetCache.php line 127:
explode() expects parameter 2 to be string, array given
```

**Comment by andypillip** [comment]
Actually I do get the same error message in the frontend even when uploading images that do get displayed properly in the CP.

**Comment by andypillip** [comment]
This might be related to #703

**Comment by jasonvarga** [comment]
I believe this is fixed for the next release. (Maybe already is). I can't replicate. Reopen if you need to.
