### ISSUE TITLE
Assets to be slugified on upload

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#604]
Feature request for assets with non-url-friendly filenames to be renamed when uploaded by users.

ie: `Screen Shot 2016.04.16.png` becomes `screen-shot-2016-04-16.png`

### Workaround
Tell users to name files appropriately (a-z, 0-9, hyphens, underscores)

**Comment by lesaff** [comment]
This is a duplicate of https://github.com/statamic/v2-hub/issues/74

**Comment by wesort** [comment]
Oops. Doubly bad as I commented the other issue too.
