### ISSUE TITLE
Better "Statamic site coming soon" message

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#605]
### Steps to reproduce
1. no license key
2. no domain entered in account page

### Expected behaviour
Page should indicate steps to remedy. Maybe figure out which part is missing and let the user know?

### Actual behaviour
"Statamic site coming soon" message

**Comment by danielfowler** [comment]
The darndest thing. I'm getting the same message on http://cast98.com but it _was_ working earlier today. Somehow uploading more files has made it disappear, having a hard time troubleshooting it.

**Comment by jackmcdade** [comment]
@danielfowler did you somehow override your license key?

**Comment by jasonvarga** [comment]
@danielfowler Did it work on the live site earlier today? Or only locally?

**Comment by danielfowler** [comment]
Winner winner, @jackmcdade 

I had indeed uploaded an old license key with a recent push. Gracias.
