### ISSUE TITLE
FR: Form output filenames as (human readable) timestamps?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#607]
It's been a while, but AFAICR, Raven allowed me to format form output file names something like so:

```
2014-05-18-908-02.yaml
```

The benefit of a file name like that being, I could just glance inside the output folder and immediately see what's recent or new.

v2's form stuff rocks, but... 

Even though via experiments I can deduce its current output filenames (being something like `1460948604.yaml`) are "timestamp-ish" (to coin a phrase)—it's not hardly as handy a file name format for us humans.

So, I'm wondering if we could please have some kind of a

```
Format form output file names as: [_______]
```

 option? For flexibility, maybe use the same loverly date-time codes we employ elsewhere: [http://php.net/manual/en/function.date.php)[http://php.net/manual/en/function.date.php]

Then folks could roll their own! Me, I lean towards

```
{{ now timezone="America/New_York" format="Y-m-d--H-i--s" }}-nn
```

for file names like

```
2016-04-18--07-26--58-nn.yaml
```

where it's more clearly be a date, a time, and perhaps some necessary gobbledegook at the end (i.e., that trailing `-nn` represents something you figure out to avoid collisions due to sub-second race conditions), as opposed to the current it's-all-gobbledegook-to-me convention.

Pretty please? :-)

**Comment by jackmcdade** [comment]
No plans to support this at this time as it would be a pretty messy backwards compatibility challenge.
