### ISSUE TITLE
Can't leave min/max rows blank on Grid fieldtype

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#609]
### Steps to reproduce
1. Create a fieldset with a Grid. Don't enter min or max rows.
2. Try to create a(n) page/entry.
3. Receive error.

The fieldset will have:

```yaml
max_rows: null
min_rows: null
```

### Expected behaviour
Statamic should create the content file.

### Actual behaviour
Received an error that said something along the lines of "argument 2 must be an array, null given" and mentioned Grid and `Form::CreateFactory()`(?).

Now that I set min and max rows to try and fix the issue, I can't replicate when setting them back to `null`, so I can't provide the log, sorry..

### Server configuration
**Operating system**: OS X

**Web server:** [ubuntu/trusty64](https://github.com/thefriendlybeasts/vagrant-statamic)

**PHP version:** 5

**Statamic version:** 2.0.1

**Updated from an older Statamic or fresh install:** From 2.0.0 (and some betas (maybe alphas?) before that)

**List of installed addons:** Fawn

**Comment by jackmcdade** [comment]
Can't recreate. Still an issue?
