### ISSUE TITLE
Form spam protection request

### ISSUE THREAD

**Issue by deepsurface** [statamic/v2-hub#614]
I would like to see some type of spam prevention solution for forms built in to version 2.

After updating to V2, my form spam has increased significantly. It has gone from one every few months to about one a day. I would rather not inflict this on my clients with forms. Honeypot for Raven in V1 must have been more successful than I realized.

Forcing visitors to deal with Captcha or reCaptcha is something I'm loathe to do and it would be great to have an invisible solution like honeypot available in this version.

**Comment by lesaff** [comment]
We use Ajax for our v2 form and implemented our own honeypot. 

In your form
```
<input type="text" style="display:none;visibility:hidden" id="honeypot" name="honeypot" />
```

In your JS (I am using JQuery but you can get by without, just need to refactor it to vanilla JS)
```
var honeypot = $('#honeypot').val();

form.submit(function(e){
    e.preventDefault();

    if (honeypot == '' || honeypot == null) {

        $.ajax({
            type: 'POST',
            url: '/!/Form/create',
            data: form.serialize(),
            success: function(data) {
                // Do whatever you need to do
            }
        });
    }
 });
```

**Comment by jasonvarga** [comment]
I saw you mention the spam problem in the Slack room and wondered why updating to v2 alone would become an issue.

Sounds like you used Honeypot in v1, but not in v2. Is that right?

**Comment by deepsurface** [comment]
That's right. I didn't try it because I didn't see a mention of honeypot or spam in the new docs. Does it still work in V2?

**Comment by jasonvarga** [comment]
Nope. We'll be adding that.

**Comment by deepsurface** [comment]
Thanks, Rudy. Didn't realize it was that easy.

Sounds good, Jason.
