### ISSUE TITLE
FR: Add Setting for Default "Published" State of New Entries and Pages

### ISSUE THREAD

**Issue by markzegarelli** [statamic/v2-hub#615]
Currently, all new entries and pages default to `Published` on save. It would be great to have this configurable in the Collection or in the Fieldset. 

My team will have several writers and we want to ensure that content is not automatically published before it's been reviewed.

**Comment by cschweda** [comment]
+1

This feature would be great to have.

**Comment by bacheson** [comment]
this is literally killing my project...I have to create hundreds of empty files with published: false to make this work...fix pretty please

**Comment by jasonvarga** [comment]
This feature request is for the toggle in the editor to default to the off state.
Right now you can just manually toggle it before you hit save. I'm not following what your specific problem is, @bacheson

**Comment by bacheson** [comment]
I have hundreds of collection items for ~10 collections....I also have 7 languages....so you are asking me to click almost 1,000 times to set things up

**Comment by jasonvarga** [comment]
I guess I'm not understanding why if you already have hundreds of items, would you need to retroactively unpublish them. What does setting things up mean?

**Comment by bacheson** [comment]
Sorry let me give you a more detailed example. I have converted my site to Statamic in english-only.

I have ~15 pages

I have ~8 collections; here are the main ones:
blog (80 items)
feature (50 items)
testimonial (50 items)

Now that everything is ready to go I need to convert several main pages of the site to 6 other languages. I'd like to disable everything else for now. This means all the collection items above must have published=false set. Doing this in the cp would take hundreds of clicks.

**Comment by jackmcdade** [comment]
Since the publish state is reflected by a filename starting with an underscore (e.g. `_2017-12-01.oh-hai-mark.md`) you can use a batch file renaming tool like [Name Mangler](https://manytricks.com/namemangler/) to do it for you, and it shouldn't take more than a few clicks.

**Comment by jasonvarga** [comment]
I think I understand. You want to create an additional locale but you don't want the English versions to cascade over? You only want them to show up once you add content?

**Comment by bacheson** [comment]
yes exactly...i thought about creating a bash script to do this I just wanted to avoid burning an hour or two making sure it worked properly

**Comment by goldnead** [comment]
+1 for this one. Any workaround yet?

**Comment by rchlfryn** [comment]
+1

**Comment by bickle66** [comment]
Any progress on this FR? It's a bit strange that the default state ISN'T a draft. From a publishing flow perspective.

**Comment by edalzell** [comment]
I just got bit by this when I did a save and continue to save my progress. It got picked up by my publish scripts and pushed to twitter and Facebook before is was ready.

**Comment by jasonvarga** [comment]
Added for next release (2.10.3)

For entries: add `default_status: draft` to a collection's `folder.yaml`

For pages: add it to a `folder.yaml` at any page directory and it will cascade down to its child pages.
eg. `site/content/pages/folder.yaml` will affect all pages. 
`site/content/pages/about/folder.yaml` will only affect creating pages in `/about/*`
