### ISSUE TITLE
Fieldtypes with dynamically loading data doesn't save if you hit save before they load.

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#617]
### Steps to reproduce
1. Upload an asset to content.
2. Save.

This is because I'm sometimes faster than the img upload.

**Comment by jasonvarga** [comment]
Slow down :)

**Comment by jasonvarga** [comment]
That was sarcasm. We'll need to disable the save button until everything has finished uploading.

**Comment by miktirr** [comment]
Statamic 2.5.2:

If an entry is saved before a taxonomy field has loaded, weird stuff gets saved. Looks like a some kind of mashup of the term and the taxonomy.

<img width="869" alt="screen shot 2017-02-02 at 10 04 41" src="https://cloud.githubusercontent.com/assets/6806359/22558600/f341a492-e976-11e6-8c35-bc612c9245d6.png">

**Comment by jackmcdade** [comment]
@miktirr That's on purpose. If you're using a Taxonomy field as a regular content field (instead of a Taxonomy field, that's how it works. Use it in combination with the Relate tag for best results.

**Comment by miktirr** [comment]
No sure I follow completely, but my point was that the `taxonomy/term` gets saved weirdly. On line 25 there is not `langcategories/ranska` but `rangcategories/ranska`. It looks like the new string gets written in the middle of the old string.

Both of those taxonomies are in the fieldset’s taxonomies array in the yaml:

```
title: Julkaisu
taxonomies:
  langcategories:
    max_items: 1
    create: false
  series:
    max_items: 1
    create: false
```

But to be fair I’m basically intentionally trying to break stuff. This happens only when an entry is opened and saved very quickly; I open an entry and save as soon as I can without any intention to do actual edits.

**Comment by curtisblackwell** [comment]
@miktirr your issue is unrelated to this issue. You may want to create a new issue or a support request on [the lodge](http://lodge.statamic.com/).

**Comment by jackmcdade** [comment]
Don't see us reworking this as things are a bit different already for v3. Will close this down.
