### ISSUE TITLE
FR: Change assets structure a smidge

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#618]
The way assets work now, content and structure get mixed into a single file, which makes it a huge pain to *not* track content in the repo.

As of now, to do anything with assets in the CP, you need the following structure for each container:

```files
site/settings/storage/assets/UUID/
| -- container.yaml
|-- folder.yaml
```

On top of that, if a container has any folders within it, we ge:

```files
site/settings/storage/assets/UUID/
| -- some_folder/
| -- | -- folder.yaml
| -- container.yaml
|-- folder.yaml
```

`folder.yaml` contains both a setting required for the AJAX requests to succeed (`title`) and a listing of all the content in the container. If the concerns were separated here, then Statamic wouldn't dictate our workflows as strongly here.

The `title` could remain in `folder.yaml` alongside any future settings; Assets' UUIDs and paths could go in a new file, like an `assets.yaml`.

**Comment by jasonvarga** [comment]
Help me understand why you want it changed. Why wouldn't you want to track them?

**Comment by curtisblackwell** [comment]
A big part is just preference. I don't keep content in the repo. Probably the biggest reason for this is that I don't want to wade through a bunch of content commits when I have to look through the history.

**Comment by jackmcdade** [comment]
We're gonna change these more than a smidge. Gonna close this issue because. Because.
