### ISSUE TITLE
Make a Fieldtype's Vue template readonly and it doesn't adhere to width settings

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#619]
### Steps to reproduce
1. Create a fieldtype and in the template have something like `<input type="text" v-model="username" readonly/>`
2. View the field in the CP

### Expected behaviour
It adheres to width setting in fieldset

### Actual behaviour
If set to 100% it doesn't span the whole page.

**Comment by jasonvarga** [comment]
Add class="form-control" to the input. 

The fieldtype is 100% but the actual text field isn't.
