### ISSUE TITLE
FR: Form needs a `redirect_error` parameter

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#625]
The `redirect` parameter ([https://docs.statamic.com/reference/tags/form-create](https://docs.statamic.com/reference/tags/form-create)) works well for *successful* form submissions, allowing me to fragment-url my way back to the top of a form that's far down on a long page, and show the success message without forcing the user to scroll, scroll, scroll. E.g.,
```
{{ form:create attr="class:contact" redirect="/contact#my_form" }}
```

is fabulous! However,... There's as yet no way I know to get the same functionality upon *errors*.

Here's what it would look like if specified in the old Raven-ish way:
```
{{ form:create attr="class:contact" redirect="/contact#my_form" error_return="/contact#my_form"}}
```

Call it "error_return" or "redirect_error" or whatever suits you best, but I really, really need the functionality. Pretty please?

**Comment by iDGS** [comment]
I should explain *why* I think this is such a big deal. It's because of the user interaction, or non-interaction that can result.

Here's the broken, as-is way things work now:
1) User enters things into form way down on a page, and clicks `submit`
2) User is delivered to the top of the PAGE (no form in sight).
3) User thinks "okey-dokey, I guess that worked" and goes on their merry way.
(NB. No form data submitted; UX fail)

vs.

Here's a better interaction model I'm hoping for:
1) User enters things into form way down on a page, and clicks `submit`
2) User is delivered (e.g.,) to the top of the FORM, where there's an error message.
(NB. we cannot currently do this, because we lack the `redirect_error` parameter.)
3) User thinks "Oops, I better fix that," does what's necessary, and re-clicks `submit` 
4) User is again delivered to the top of the FORM, where there's now an *confirmation* message.
(NB. We can do this part, because we *do* have the `redirect` parameter.)
5) User thinks "okey-dokey, I guess that worked" and goes on their way.
(NB. UX success! Form data submitted)

I've called it a FR for Feature Request, but in terms of UX, it's more of a bug that needs to be fixed.

**Comment by jackmcdade** [comment]
You can stop now, we'll add it, it's okay.

**Comment by iDGS** [comment]
Cool. Thanks!
