### ISSUE TITLE
FR: Make Form Field Contents Sortable in CP

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#626]
`/cp/forms/myformname` shows a bunch of forms summarized one form per row. The default order is ascending on the first column, which is a kind of built-in date field. 

IMHO, the most recently submitted forms are likely to be of the most interest. However, those are appended as new rows to the _bottom_ of the table.

It would be great to be able to sort the collected form values by any column, ascending or descending, same as one can do on the Users CP pane (`/cp/users`).

It was kind of disappointing that it wasn't possible.

**Comment by jackmcdade** [comment]
Please try to make your PRs more positive. They all bum me out. Also? I've been drinking.

**Comment by iDGS** [comment]
Cheers! Wish I could share a glass! 

https://www.thewhiskyexchange.com/p/11509/dalmore-selene-1951-58-year-old

(I imagine at $30,619.24 a bottle, that there's some fairly good stuff!)

**Comment by edalzell** [comment]
This has been done I think, right @iDGS @jackmcdade ?
