### ISSUE TITLE
Incorrect links to Addons' settings

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#627]
### Steps to reproduce
1. Visit `/cp/configure/addons` with an addon installed that has a `settings.yaml`.
2. Click on the addon's name.
3. 404.

### Expected behaviour
Should end up at `/cp/addons/ADDON/settings`.

### Actual behaviour
End up at `/cp/configure/cp/addons/ADDON/settings`.

**Comment by lesaff** [comment]
I cannot reproduce. All my addons' settings links work fine.
