### ISSUE TITLE
php please clear:cache errors

### ISSUE THREAD

**Issue by pmeissner** [statamic/v2-hub#628]
### Steps to reproduce
1. run `php please clear:cache`

### Expected behaviour
Clear cache

### Actual behaviour
Get error "PHP Parse error:  syntax error, unexpected '[' in /Users/phil/Sites/platinumlakemanagement/statamic/bootstrap/helpers.php on line 65
 
Parse error: syntax error, unexpected '[' in /Users/phil/Sites/platinumlakemanagement/statamic/bootstrap/helpers.php on line 65
"

### Server configuration
**Web server:**
MAMP PRO
**PHP version:**
7.0.0
**Statamic version:**
2.0.2
**Updated from an older Statamic or fresh install:**
Updated

**Comment by lesaff** [comment]
I can't reproduce. Try the following and see if you also get the same error or not
```
php please view:clear
php please cache:clear
```

**Comment by pmeissner** [comment]
Forehead smack. Reading through some Slack conversations, I realized that commands run through terminal are using the OS's version of PHP (5.3.28)— not MAMPS. Using [this](http://stackoverflow.com/questions/4145667/how-to-override-the-path-of-php-to-use-the-mamp-path) to alias to MAMPs php fixed up everything.
