### ISSUE TITLE
Feature Request: Additional Methods for Storage in Addons

### ISSUE THREAD

**Issue by jesseschutt** [statamic/v2-hub#629]
Would it be possible to get some addition helper methods available in addons for retrieving all .yaml files in a directory and for deleting a .yaml file?

We have access to getting individual files through `storage->get(key)` but not direct access for retrieving all or deleting files.

Thanks!

**Comment by edalzell** [comment]
Here's the code needed to delete a serialized storage object.

ContextualStorage.php:
``
    public function deleteSerialized($key)
    {
        Storage::deleteSerialized($this->contextualize($key));
    }
```

Storage.php
```
    public static function deleteSerialized($key)
    {
        self::delete(Str::ensureRight($key, '.php'));
    }
```

Code would be very similar for JSON and YAML.

@jasonvarga, any chance this can be fit into 2.2 or 2.2.1?
