### ISSUE TITLE
fieldtype.js should only load when it's being called

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#631]
### Steps to reproduce
1. Create a new addon, doesn't have to be anything, as long as it has `fieldtype.js`
2. Load your CP

### Expected behaviour
`fieldtype.js` should only load when it's being called, for example in the `/cp/pages/edit/*` or `/cp/collections/entries/*` or any other pages that require that particular custom fieldtype.

### Actual behaviour
`fieldtype.js` gets loaded right away even in the cp login page.

**Comment by jasonvarga** [comment]
Are you seeing an error?

**Comment by edalzell** [comment]
ya, I had an error when my fieldtype wasn't checking for a null current user.

**Comment by lesaff** [comment]
Not for me, but my `fieldtype.js` is about 150kb, so I really don't want it to load all the time unless it has to.

**Comment by jasonvarga** [comment]
It gets cached. Don't think its a big deal. Fieldtype code is loaded everywhere in the CP because they can be used anywhere.

They shouldnt get loaded on the login page though, which is Erin's issue.
