### ISSUE TITLE
2.0.2 broke the addon blade template include

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#634]
Prior to 2.0.2, I was able to use `@include()` in my addon views template to refer to another template/partials in the current folder. With 2.0.2, it throws an error and it looks like it defaults the views folder back to the `statamic/resources/views` rather than the addon specific resources folder.

**Comment by jasonvarga** [comment]
Fixed in dev.

From 2.0.3, you should do this:

```
# in controllers
$this->view('foo'); // YourAddon/resources/views/foo.blade.php

# in views
@include('YourAddon::foo') // YourAddon/resources/views/foo.blade.php
@include('foo') // statamic/resources/views/foo.blade.php
```

**Comment by madsem** [comment]
Would be nice to add this to the documentation, I almost bashed my head in on why @include('partial') wasn't working in my addon :P

**Comment by edalzell** [comment]
@madsem please make a PR to the docs for this

**Comment by peschee** [comment]
```
@include('foo') // statamic/resources/views/foo.blade.php
```

Does not seem to work in the latest statamic version `2.11.19`.

```
@include('YourAddon::foo') // YourAddon/resources/views/foo.blade.php
```

Works just fine.
