### ISSUE TITLE
Updater fails

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#636]
### Steps to reproduce
1. have a custom addon (Pinboard, in my case) that has dependencies
2. Do an update

### Expected behaviour
Upgrade should succeed

### Actual behaviour
Updater can't clean up, gets stuck trying to delete a soft linked directory in the `vendor` ('edalzell' in my case)

### Server configuration
**Operating system**:
Mac OS X 10.11.4

**Web server:**
Apache 2.6

**PHP version:**
7.0.3

**Statamic version:**
2.0.2

**Updated from an older Statamic or fresh install:**
Update

**List of installed addons:**
Pinboard

**Comment by jasonvarga** [comment]
Don't freak out, but I found a fix for this.
