### ISSUE TITLE
Issues with addons with multi-word names

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#637]
I created an addon using `please make:addon` (so the file/class names should all be correct). When editing settings in the CP:

- The name displays incorrectly (as though it was one word all lowercase).
- The settings will save to file (though probably also named incorrectly), but the saved values don't display in the CP.

Running Statamic 2.0.3

**Comment by curtisblackwell** [comment]
Sent an email with an attachment for debugging help. The subject is "Github issue #637," and it's from curtis@lionsmouth.digital.

**Comment by curtisblackwell** [comment]
Also just tried `$this->getConfig('my_var');` and it only works if I rename the generated settings file to `two_words.yaml` instead of `twowords.yaml`.

**Comment by jasonvarga** [comment]
I don't know where you sent the email.

Seems like this issue is just "make sure multi-word addons work everywhere".

It should either be `MultiWord` or `multi_word` depending on whether we're expecting StudlyCase or snake_case. It should never be `multiword`.

**Comment by curtisblackwell** [comment]
I sent it to gentlemen@.

**Comment by jackmcdade** [comment]
I can't recreate this. As long as I use `CamelCase` or `snake_case` for the name of the addon, everything is created correctly.

**Comment by jsblair9** [comment]
I just recreated it... ¯\_(ツ)_/¯

**Comment by jasonvarga** [comment]
What's the addon called? You can send it to gentlemen@ if you want.

**Comment by curtisblackwell** [comment]
MonarchPublisher. Just sent you an email.

**Comment by jackmcdade** [comment]
This is what was generated. It looks 100% correct to me. Can you review and see what's different?
[MonarchPublisher.zip](https://github.com/statamic/v2-hub/files/247733/MonarchPublisher.zip)

**Comment by curtisblackwell** [comment]
My generated files look fine, too. It's when you start using it that you see problems.

> When editing settings in the CP:
>
> - The name displays incorrectly (as though it was one word all lowercase).
> - The settings will save to file (though probably also named incorrectly), but the saved values don't display in the CP.

**Comment by jackmcdade** [comment]
![Nevermind](http://i.imgur.com/PgWwsOE.gif)
