### ISSUE TITLE
Redwood Theme embeds don't show in safari

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/v2-hub#639]
### Steps to reproduce
1. Add flickr or instagram image to blog post
2. Ensure not pulling from cache
3. View page

### Expected behaviour
Image should show up

### Actual behaviour
Image is called but css is keeping it from showing up in Safari. Disabling css will show image every time. Seems to work fine in Chrome. Could be the a href?

Hard refresh on the page will usually show the image, sometimes it takes 2.

### Server configuration
Ubuntu 14.04
Nignx
PHP 7
2.0.3

**Comment by sheldonkotyk** [comment]
<img width="783" alt="screen shot 2016-04-27 at 00 24 09" src="https://cloud.githubusercontent.com/assets/622598/14844741/7941ca50-0c0e-11e6-9039-a84f2ffecb30.png">
<img width="757" alt="screen shot 2016-04-27 at 00 24 21" src="https://cloud.githubusercontent.com/assets/622598/14844744/7cb56d2c-0c0e-11e6-9a67-6530b729c8a4.png">

**Comment by jackmcdade** [comment]
Are you putting the image in `{{ content }}` or some other method?

**Comment by sheldonkotyk** [comment]
Content

**Comment by jackmcdade** [comment]
Okay, testing.

**Comment by jackmcdade** [comment]
Hmm, i just added this to a post and everything worked fine:

```
![Photo](http://c1.staticflickr.com/2/1579/26566617432_e2b53b2c85_c.jpg)
```

Can you post the contents of a that content file? And have you made any customizations or included any JavaScript plugins or anything?

**Comment by sheldonkotyk** [comment]
```---
title: "It's freaking cold here."
authors:
  - 63596322-8b7a-417c-9f18-98c53c1c9cc5
id: e4cc2147-989f-44eb-8e83-6b1adb05a624
---
[![A BC snowmans life is sad and short.](http://farm8.staticflickr.com/7035/6697987059_f57bca8443.jpg)](http://www.flickr.com/photos/sheldonkotyk/6697987059/ "A BC snowmans life is sad and short. by Sheldon, on Flickr")```

**Comment by sheldonkotyk** [comment]
I've tried with my customized theme (changed the menu and a few tweaks) and with a stock redwood.

**Comment by jackmcdade** [comment]
Ah okay I see the snag. You're wrapping the image in a link - which seems to collide with the built in `zoom` feature on Safari. I can tinker to see if it's fixable, but since you don't want to zoom on click anyway, you might want to edit or remove the following line from the theme's `jabbascripts.js` file and recompile the js with `gulp`.

```
$('article.content img').attr('data-action', 'zoom');
```

**Comment by sheldonkotyk** [comment]
OK, the link is required in flickr's terms. Comes with the embed. :)

**Comment by jackmcdade** [comment]
Ahh okay gotcha. You can tweak that js to exclude image inside `a` link tags and voila, you're off and running.

**Comment by sheldonkotyk** [comment]
Not sure if you want me to close this or if you plan on making changes to redwood for others needing embedded stuff.

**Comment by sheldonkotyk** [comment]
interesting, I've removed the zoom interaction line and the images aren't showing again...
