### ISSUE TITLE
Can't sort inner entries array using `sort` modifier when using group by date

### ISSUE THREAD

**Issue by jasonvarga** [statamic/v2-hub#641]
cc @hmalaud

**Comment by jackmcdade** [comment]
If you don't name the inner entries `{{ entries }}` it'll work. The `{{ entries }}` wins in a battle against a var of the same name. Undecided if this is a bug, or working as intended. Will need some more thoughts around the greater implications.

**Comment by jackmcdade** [comment]
This issue is a bit stale so we're closing it for now. If it rears its head again, please feel free to reopen and ping us!
