### ISSUE TITLE
Form Fields Builder Add Field Button Broken

### ISSUE THREAD

**Issue by garethredfern** [statamic/v2-hub#645]
### Steps to reproduce
1. Create a form in the cp
2. Click on the add field button at the bottom of the page.

### Expected behaviour
Field added.

### Actual behaviour
Nada.

### Console Logs
I get a `16jabbascripts.js?v=2.0.3:4 Uncaught TypeError: Cannot read property 'length' of undefined` in the JS console when I click on the add field button.

**Comment by garethredfern** [comment]
Once you add a field in the yaml file the button then works in the CP.

**Comment by jackmcdade** [comment]
Can't recreate. Are there any other steps?
