### ISSUE TITLE
Form Redirect URL

### ISSUE THREAD

**Issue by garethredfern** [statamic/v2-hub#646]
### Steps to reproduce
1. Create a form with no parameters other than the `in` parameter
2. Submit the form on the front end

### Expected behaviour
The form should redirect to the same page if no redirect parameter added.

### Actual behaviour
Form sends you to `/index.php/!/Form/create` with a Whoops warning page, it does create an entry successfully though.

**Comment by garethredfern** [comment]
User error sorted via screenhero with Jack

**Comment by itsHall** [comment]
What was the user error? I'm facing the same problem now D: @jackmcdade

**Comment by jasonvarga** [comment]
What's the error?

**Comment by itsHall** [comment]
@jasonvarga it happens when trying to use this contact form: https://instantlettering.com/contact it is the exact same scenario as this issue.

**Comment by jasonvarga** [comment]
Right, but the "whoops" page just says something went wrong. The actual error isn't shown. It will be in your log file.
