### ISSUE TITLE
ServiceProvider created with inconsistent class name

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#651]
### Steps to reproduce
Create a new provider through `please make:provider AddonName`

### Actual behaviour
File name created with the following name convention `AddonNameProvider.php`
The actual class name is `class AddonNameServiceProvider`

This was also reported by @warkior through the Slack channel.

**Comment by lesaff** [comment]
This is related to #652

**Comment by jasonvarga** [comment]
Fixed for next release.
