### ISSUE TITLE
FR: Allow a collection’s table columns to be customised

### ISSUE THREAD

**Issue by pryley** [statamic/v2-hub#653]
e.g.
![image](https://cloud.githubusercontent.com/assets/134939/14955915/11787bbc-104b-11e6-8de1-ac5e9cf97a10.png)

**Comment by lesaff** [comment]
Need to add this to the documentation.

**Comment by jasonvarga** [comment]
Ah yes.

Add the following to your `site/content/collections/your_collection/folder.yaml`:

```
columns:
  - title
  - slug
  - some_field
  - etc
```
