### ISSUE TITLE
FR: Heading keyboard shortcuts for Markdown field

### ISSUE THREAD

**Issue by pryley** [statamic/v2-hub#654]
i.e. 

h1 = ⌘+1
h2 = ⌘+2
h3 = ⌘+3

etc.

**Comment by jasonvarga** [comment]
Those shortcuts will change tabs in a number of browsers.

**Comment by pryley** [comment]
What about something like `⌘+⇧+1` or the ability to set custom shortcuts?

**Comment by jasonvarga** [comment]
Sorry, didn't mean to dismiss your suggestion. It's a good one, probably just not that particular set of shortcuts. We'll figure something out. I like it. (We have shortcuts for bold, italic, etc)

**Comment by pryley** [comment]
I know I use those ones ;)

Here are the keyboard shortcuts that WordPress editor uses: https://codex.wordpress.org/Keyboard_Shortcuts

Perhaps mapping some of those...?
