### ISSUE TITLE
FR: php please deploy:staging

### ISSUE THREAD

**Issue by pryley** [statamic/v2-hub#655]
It would be really nice to have a please command for [Deployer](https://github.com/deployphp/deployer/) 

e.g. 
`php please deploy:check-server`
`php please deploy:staging`
`php please deploy:production`
`php please push:staging`
`php please pull:production`
etc.

**Comment by jackmcdade** [comment]
Wouldn't be something we'd add to the core, but could be accomplished with an Addon.
