### ISSUE TITLE
Ternary parsing in Antlers

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#658]
Would be cool to be able to do stuff like this:

```
{{ my_var === "val" ? "hey" : "bye" }}
{{ my_var === "val" ? some_var : other_var }}
```

**Comment by jasonvarga** [comment]
This is @jackmcdade 's oldest feature request to date.

**Comment by curtisblackwell** [comment]
I take it that means it's complicated?

**Comment by jasonvarga** [comment]
Yup.

**Comment by manogi** [comment]
+1 
(twig and blade can do it... hehe...)

**Comment by jackmcdade** [comment]
Just so you all know, I really, really want this too :) It's very hard to add to where the parser is at, and do attempt to add it every so often. Someday...yes someday we will have it.

**Comment by edalzell** [comment]
that parser code is ...um...super fancy. I can understand why it would be difficult.

**Comment by jackmcdade** [comment]
Won't happen in v2, but we _are_ adding a new `yes_no` modifier in 2.11 that serves this exact purpose 👍 .
