### ISSUE TITLE
Sneak preview loading icon shows all the time when previewed site doesn't have a background color

### ISSUE THREAD

**Issue by seanwash** [statamic/v2-hub#659]
I admit that this is not super important, just thought I'd note it.
### Steps to reproduce
1. Preview a theme that doesn't have a bg color set in the css
### Expected behaviour

The loading spinner is not visible when content has loaded
### Actual behaviour

It is visible http://cl.ly/2c3o1V2O101A

**Comment by jasonvarga** [comment]
Bummer. That was a good way to show the loader until the page actually loaded.

**Comment by seanwash** [comment]
I know :( I felt bad filing this because that's what I would have done.

**Comment by jasonvarga** [comment]
![](https://s-media-cache-ak0.pinimg.com/236x/0d/00/5c/0d005c851b6d51d165b4cc819971ab17.jpg)
