### ISSUE TITLE
Addon settings fieldset labels not working on above root set up

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#660]
### Steps to reproduce
1. Create an addon with settings
### Expected behaviour

Fieldset labels is working fine on local OS X with MAMP Pro
### Actual behaviour

Once deployed to Ubuntu server, fieldset labels are not read

<img width="1086" alt="screen shot 2016-05-02 at 9 45 03 pm" src="https://cloud.githubusercontent.com/assets/1151181/14972132/a41e5734-10af-11e6-90bb-b0aaa216844f.png">

<img width="1083" alt="screen shot 2016-05-02 at 9 45 21 pm" src="https://cloud.githubusercontent.com/assets/1151181/14972135/a8cf1ec6-10af-11e6-8a68-10dbf89ad761.png">

**Comment by lesaff** [comment]
Does this have something to do with case-sensitive OS (Linux) not picking up the right filename?

**Comment by jackmcdade** [comment]
Seems like it to me, what's the name of your addon?

**Comment by lesaff** [comment]
`Mailer`

**Comment by lesaff** [comment]
More information on this issue. It works fine when v2 is installed below web root.

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
