### ISSUE TITLE
Using a get variable in a condition

### ISSUE THREAD

**Issue by garethredfern** [statamic/v2-hub#662]
### Steps to reproduce
1. Create a get variable in the URL example: `?message=test`
2. In your template create a conditional `{{ if {get:message} == "test" }}testing{{ /if }}`
3. View the template 

### Expected behaviour
If the get variable is present in the uri then the message "testing" should appear.

### Actual behaviour
Using  `{{ if {get:message} == "test" }}testing{{ /if }}` displays nothing (condition does not pass).
Using:  `{{ if get:message == "test" }}testing{{ /if }}` without the single brackets round the variable works.

I would have expected to have to use single brackets like you do with other conditional stuff e.g.

`{{ if {form:success} }}success{{ /if }}`

**Comment by jasonvarga** [comment]
`get:x` is a variable, so you don't need the brackets. Only need brackets when its a Tag.

https://docs.statamic.com/reference/variables#global:get
