### ISSUE TITLE
Installer doesn't set user to be super

### ISSUE THREAD

**Issue by garethredfern** [statamic/v2-hub#663]
### Steps to reproduce
1. Wiped site with the please command
2. Ran the installer
3. New user created via the installer

### Expected behaviour
It would appear that the new user needs to be set as super to access the admin panel.

### Actual behaviour
The new user isn't set as super so you get an error message saying that you don't have access.

**Comment by jasonvarga** [comment]
Good one. The installer adds the user to a role with super permissions, but since you wiped the site first, the role doesn't exist.

**Comment by edalzell** [comment]
Related, you can't create a super user from the Add User section of the CP
