### ISSUE TITLE
Helper text checkbox field type

### ISSUE THREAD

**Issue by garethredfern** [statamic/v2-hub#667]
When a user is upgrading, the `checkbox` fieldtype is deprecated, it is now  `checkboxes` could we add some helper text like we do with the file field `Fieldtype [checkbox] does not exist. Try [checkboxes].`

**Comment by jackmcdade** [comment]
Or Alias to Toggle perhaps?

**Comment by jackmcdade** [comment]
This one got a bit old. At this point, I think it's safe to close.
