### ISSUE TITLE
Upgrade breakes Statamic (file permissions)

### ISSUE THREAD

**Issue by eminos** [statamic/v2-hub#668]
### Steps to reproduce
1. Set correct file permissions for the environment (suphp) 755 for directories and 644 for files.
2. Upgrade existing Statamic installation
3. File permissions of Statamic files are changed (I guess after unzipping the zip-file the original file permission from the zip file are kept)
4. Site breaks.

Error(s) in log file after upgrade:
`
[2016-05-05 10:25:17] production.ERROR: exception 'ErrorException' with message 'file_put_contents(/home/astivia/public_html/local/storage/framework/cache//a1/04/a10401782973f6e2cc19be95e0175b26): failed to open stream: Permission denied' in /home/astivia/public_html/statamic/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:81
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/home/astivia/p...', 81, Array)
#1 /home/astivia/public_html/statamic/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(81): file_put_contents('/home/astivia/p...', '9999999999s:247...', 0)
#2 /home/astivia/public_html/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(102): Illuminate\Filesystem\Filesystem->put('/home/astivia/p...', '9999999999s:247...')
#3 /home/astivia/public_html/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(157): Illuminate\Cache\FileStore->put('stache/content/...', 'a:5:{s:27:"taxo...', 0)
#4 /home/astivia/public_html/statamic/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(184): Illuminate\Cache\FileStore->forever('stache/content/...', 'a:5:{s:27:"taxo...')
#5 [internal function]: Illuminate\Cache\Repository->forever('stache/content/...', 'a:5:{s:27:"taxo...')
...
`

This is what I run to set the correct file permissions and make the site work again:
find * -type d -exec chmod 755 {} \;
find * -type f -exec chmod 644 {} \;
php please clear:cache

### Server configuration
**Operating system**: CloudLinux 6 (CentOS 6) / cPanel

**Web server:** Apache 2.4

**PHP version:** 5.5

**Statamic version:** 2.0.3

**Updated from an older Statamic or fresh install:** Updated

**Comment by jackmcdade** [comment]
We’ve found permissions to be way more stable at `777`.

**Comment by eminos** [comment]
I'm pretty sure that doesn't work with suphp (which is why it brakes Statamic).

https://www.google.se/search?q=suphp+file+permissions

Maybe the solution is to read the environment and if it's suphp apply the correct file permissions.

**Comment by jackmcdade** [comment]
What host are you on? Isn't suPHP abandoned?

**Comment by eminos** [comment]
I'm running my own cPanel server on CloudLinux. Latest versions.
Have been running it professionally for 6+ years with no issues with multiple CMS's.

https://documentation.cpanel.net/display/EA/Apache+Module%3A+SuPHP
https://cloudlinux.com/mod-lsapi

CloudLinux is having a webinar in a couple hours, I will try to ask them about suphp's status and if there is a better alternative nowadays.

**Comment by eminos** [comment]
suphp is default on cPanel servers.

https://documentation.cpanel.net/display/EA/Apache+PHP+Request+Handling

**Comment by eminos** [comment]
I was trying to reproduce a file permission error with a test.php file and test folder, but I couldn't get an error. All file permission variations seem to work. So I'm not really sure where the issue is.
Three things are obvious though.
- It's a file permissions error (according to logs)
- Statamic upgrade brakes the site
- Reseting the file permission to environment default fixes the site
