### ISSUE TITLE
2.0.4 breaks addon resources redirection

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#670]
### Steps to reproduce
1. Update to 2.0.4
2. Open CP with your addon installed

### Expected behaviour
Addon that uses `$this->css->url()` or `$this->js->url()` should be able to see those css/js working on the cp

### Actual behaviour
You get `Resource not found` when you try to visit the css/js link directly.

#### Browser log
```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://v2.dev/resources/addons/Sections/js/scripts.js 
```

**Comment by nils-holger** [comment]
Jason said: "We know about the 404s in Valet. We're working on a fix. For now, you can hack in a fix by opening `statamic/core/Http/ResourceServer/Server.php` to line 138 and change the `4 +` to `3 +`."

It worked for me.

**Comment by lesaff** [comment]
I don't use Valet, but it is a related issue. 
Changing line 150 from `5` to `4` fixed it.  
Thx
