### ISSUE TITLE
Giving CP access but no access to edit pages stops a user logging in

### ISSUE THREAD

**Issue by garethredfern** [statamic/v2-hub#672]
### Steps to reproduce
1. Create a role with CP access but no access to edit pages.
2. Login as user
### Expected behaviour

The user should still be able to login but not see the pages menu in the CP.
### Actual behaviour

User is denied access and can not login.

**Comment by jasonvarga** [comment]
If the `cp.yaml` setting for `start_page` is `pages`, then when they log in they get taken to the pages area, for which they don't have access.

I'd change that setting to `dashboard`.

**Comment by aryehraber** [comment]
I was about to open an issue for this same reason.

I'm currently working on a site where a particular User Role only has access to 1 particular Collection -- basically they can only edit Events. There is no dashboard to direct them to using `start_page`.

I've edited the core slightly with the following to get around my problem, but would be great if there was support for this natively: `statamic/core/Http/Middleware/CP/StartPage.php`

```php
public function handle($request, Closure $next)
{
    $start = Config::get('cp.start_page');

    if ($start === 'pages') {
        return redirect()->route('pages');
    } elseif ($start === 'collections') {
        return redirect()->route('collections');
    }

    return redirect()->route('dashboard');
}
```
