### ISSUE TITLE
Set url for S3 buckets

### ISSUE THREAD

**Issue by tyvdh** [statamic/v2-hub#674]
I'm using imgIX for all my S3 image collection assets but the url delivered when dragging and dropping images in the CP is obviously an amazon url. Would REALLY love if I could set it to be something else. Amazon assets are typically passed through a CDN anyway so this likely would be something a lot of folks would get mileage out of.

**Comment by lesaff** [comment]
You can do a macro that appends custom url to your s3

```
cdn:
  ensure_left: https://cdn.domain.tld/
```
usage
```
{{ path | cdn }}
```

**Comment by jackmcdade** [comment]
Duplicate of #524
