### ISSUE TITLE
Bugs in {{ get_values }} introduced in 2.0.4

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#675]
In working on #657, a couple new bugs were introduced.

```
ErrorException in GetValueTags.php line 23:
Undefined variable: filters
```

The call to undefined `$filters` is: `unset($filters['from']);`

Simply removing this is no good either, b/c the returned data will be `null`.

My hotfix:

**:21-23**

``` php
if ($from = $this->get('from')) {
    $content = Content::get($from);
}
```

**:31-33**

``` php
$filters = $this->parameters;
unset($filters['from']);
if ($filters) {
```

**Comment by edalzell** [comment]
@curtisblackwell this still exist?

**Comment by curtisblackwell** [comment]
@edalzell ¯\\_(ツ)\_/¯ I doubt it.

**Comment by edalzell** [comment]
Can you close then?
