### ISSUE TITLE
asset:field sometimes returns last image in a folder, not first

### ISSUE THREAD

**Issue by ldstevens** [statamic/v2-hub#676]
I have a template which lists entries. Each entry has an asset field with a bunch of upload images, e.g. image-1.jpeg to image-9.jpeg. Images are listed in the CP entry edit form in the desired way, i.e. from 1-9. 

I've been using the single {{ asset:field }} tag to return the first image from the asset field as a hero image. 

However, occasionally on my dev server the _last_ image would appear instead, i.e. image-9.jpeg not image-1.jpeg. A refresh usually fixed the problem. Unfortunately it's happening on my webfaction production server too, which is kind of embarrassing when the last image in the set appears as the hero for an entry. The production version has stricter caching enabled though:

```
stache_always_update: false
static_caching_enabled: true
static_caching_length: 3600
static_caching_type: cache
```

It's currently not happening for the entry template itself. 

I can't reproduce reliably unfortunately. If it's too hard to solve, I'd love a `limit` parameter on the {{ assets }} tag as per #633 .

Happy to provide any info that helps. 

Clearing the application cache has no effect.

The template chunk which specifies the image is:

```
<img src="{{ asset:slide }}{{ url }}{{ /asset:slide }}" alt="">
```
### Server configuration

**Operating system**: Unknown (Webfaction)

**Web server:** Apache 

**PHP version:** 7.0 production, 5.5.31 dev

**Statamic version:** 2.0.4

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:** None

**Comment by ldstevens** [comment]
I updated my home.html template from:

```
{{ collection:articles as="entries" }}
{{ entries }}

	{{ partial:articles-list }}

{{ /entries }}
{{ /collection:articles }}
```

to

```
{{ collection:articles }}

	{{ partial:articles-list }}

{{ /collection:articles }}
```
... and now {{ asset:field }} is returning the first image again. However I guess (!) this may just be chance/unrealted, as it was only popping up now and then on my dev server too, so it may just be that this time it worked for some reason (race condition?).

**Comment by aryehshai** [comment]
I have the same issue (both on dev and live) just after clearing the cache (`php please clear:cache`). I seem to reliable solve this by running `php please clear:glide` directly after.

**Comment by jasonvarga** [comment]
Just checking, you guys have a list of asset ids in a field, right?

**Comment by aryehshai** [comment]
Yeah, I have an array of images and I grab the first image using:
`{{ asset:images }}{{ glide:id square="600" fit="contain" quality="90" }}{{ /asset:images }}`

**Comment by ldstevens** [comment]
Yep. Example field contents:
```
images:
  - 952f53de-bd57-4284-be77-5d46d9c2d13f
  - 9e3291cf-62e2-4de1-b4f4-dd95c69999f7
  - 41502d14-d3d7-4d4d-91da-b0f022245316
  - f56e339f-a836-4e17-8cd7-323636186e36
  - a9ac27f7-b95b-4104-a966-3e4fa8a41924
  - bd7263ed-b968-436e-b06f-10e64047b4f1
  - fcb11546-3bd4-4a32-b16c-77095a09ae92
  - 2092b0ce-b7f8-41d3-9d51-0592e73b9c95
  - 70613d81-c8a1-4991-9d96-c57dc9ac1611
```

Example fieldset:
```
  images:
    display: Entry Images
    type: assets
    container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
    folder: entryimages
```
Using local storage driver. Pretty vanilla. I'm not using Glide for this, FWIW.

**Comment by edalzell** [comment]
@aryehraber @ldstevens this still a problem?

**Comment by aryehraber** [comment]
@edalzell Nope, don't recall this happening in a long time.
