### ISSUE TITLE
Tag `nav:exists` only outputs 1

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#678]
### Steps to reproduce
1. Create a layout, template or partial that uses a `nav:exists` block, contents don't matter
2. Create subpages for a page
3. Visit that page

### Expected behaviour
The contents of the `nav:exists` block should be output.

### Actual behaviour
Only `1` is output.

### Server configuration
**Operating system**: F22 Linux, 64-bit

**Web server:** `PHP -S`

**PHP version:** 5.6.20

**Statamic version:** 2.0.3

**Updated from an older Statamic or fresh install:** Fresh install

**List of installed addons:** None

### Logs

Logs are empty.

**Comment by andypillip** [comment]
Actually the following line works then:
```
{{ if {nav:exists} }}
{{ /if }}
```

Maybe the documentation should be updated?

**Comment by jasonvarga** [comment]
You're absolutely right. I ported it incorrectly. jason--

The way you just explained is how it works now, but the way it worked in v1 is how it should work.

**Comment by andypillip** [comment]
@jasonvarga thanks for your quick reply.

So you'll change the implementation? Then I'll leave the documentation alone (:

**Comment by jasonvarga** [comment]
Yeah I'll change the implementation and the docs.

**Comment by jasonvarga** [comment]
Fixed for next release. Thanks again!
