### ISSUE TITLE
Call to a member function toArray() on null for collection entries

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#679]
### Steps to reproduce
1. Add a collection _posts_ and some entries, one with `slug: post1`
2. Define the _collection-route_ as `posts: /news/{slug}`
3. Call that route for one entry `/news/post1`
### Expected behaviour

The entry should be presented in some (which would that be, actually?) template.
### Actual behaviour

```
FatalErrorException in Content.php line 173:
Call to a member function toArray() on null
```
### Server configuration

**Operating system**: Fedora 23, 64 bit

**Web server:** `PHP -S statamic/server.php` 

**PHP version:** 5.6.20

**Statamic version:** 2.0.3

**Updated from an older Statamic or fresh install:** Just unwrapped it

**List of installed addons:** None
### Logs

Statamic's log contains the very same error.

**Comment by jasonvarga** [comment]
Are you literally adding `slug: post1` to the front matter? Or are you just explaining to us that's what the slug is?

**Comment by andypillip** [comment]
@jasonvarga Just explaining that I'd enter `post1` in CP.

Where are slugs stored?

**Comment by jasonvarga** [comment]
In the filename. eg `site/content/collections/news/2015-02-01.slug.md`

**Comment by andypillip** [comment]
I just verified that I also have that issue when hosting through Apache and _mod_rewrite_. Normal pages work, though.

**Comment by jackmcdade** [comment]
I don't believe this is still an issue. Please reopen if you have evidence otherwise!
