### ISSUE TITLE
Feature to clone/copy/duplicate content

### ISSUE THREAD

**Issue by serieseight** [statamic/v2-hub#681]
Would be great to be able to clone pages or entries

**Comment by dannyuk1982** [comment]
Before submitting that FR just then I searched for `copy` and `duplicate`, didn't think of looking for `clone`, maybe the title could be edited?

**Comment by jasonvarga** [comment]
@dannyuk1982 has made a great addon that adds this functionality.

https://github.com/dannyuk1982/statamic-Duplicate
