### ISSUE TITLE
Notes on a Clean Install of 2.0.4 while Offline

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#683]
I discovered a few things that might be of interest when I had occasion to do a clean install of 2.0.4 into `localhost` on my laptop while entirely offline. AFAICR...

1. Although I entered a valid license key, the install insisted my key was invalid. Better might be if it just informed me it couldn't validate my license while offline, and defaulted more gracefully into Trial Mode. (Yes, it was in Trial Mode. The point here being it would be nicer if it didn't scold me by presuming I'm an offender.)

2. The Gravitar icon was a broken image. Small thing, but why not default to e.g., either a copy of the default Gravitar icon you've maybe stashed away somewhere as a data URI ([https://css-tricks.com/data-uris/](https://css-tricks.com/data-uris/)), or perhaps ye olde stag avatar under such circumstances?

3. Upon later regaining my online connection, it was still in Trial Mode. I had to intervene and manually `Save` the CP pane with the license key I'd already entered in order to get blessed. I dunno. Kinda thought it would do that automatically.

4. `git status` after the `Save` in step 3, above, shows `site/settings/system.yaml` has been modified. (All well and good.) However, some of the things that `git diff HEAD site/settings/system.yaml` revealed were additions I would not have expected to depend on having an online connection. E.g.,
```
+date_format: F jS, Y
+default_extension: md
+filesystems:
+  content:
+    driver: local
+    root: site/content
+  storage:
+    driver: local
+    root: site/storage
+  users:
+    driver: local
+    root: site/users
+  themes:
+    driver: local
+    root: site/themes
+    url: /site/themes
```

and
```
+redactor:
+  - 
+    name: Standard
+    settings:
+      buttons:
+        - formatting
+        - bold
+        - italic
+        - unorderedlist
+        - orderedlist
+        - html
+  - 
+    name: Basic
+    settings:
+      buttons:
+        - bold
+        - italic
+timezone: UTC
+send_powered_by_header: true
```

None of this is earth-shaking stuff. I just thought you might be interested to know.

**Comment by iDGS** [comment]
Oh, yeah—and...

5. on `http://localhost/things` there were no pictures. (b/c all amazon links)

**Comment by jackmcdade** [comment]
I get ya on the points, but TBH it's just a demo **web**site. Trial mode validation and Gravatar might justify changes but the others are kinda just how they work.

**Comment by jasonvarga** [comment]
Point 4, where it added all those settings has nothing to do with an internet connection. When you save your settings, it'll add everything.

**Comment by iDGS** [comment]
Yep. Perfectly reasonable. I simply felt obliged to report my discoveries. :-)
