### ISSUE TITLE
FR: Add additional cp events

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#687]
Would be great if we can listen to the following events. I've marked the ones that are already available.
- [x] user logged in (auth.login)
- [x] user logged out (auth.logout)
- [ ] user failed login
- [x] user creation (user.registered)
- [x] user modification (cp.user.published)
- [ ] user deletion
- [x] entry creation/published (cp.published, cp.entry.published)
- [ ] entry unpublished
- [ ] entry deletion
- [x] page creation/published (cp.published, cp.page.published)
- [ ] page unpublished
- [ ] page deletion
- [ ] asset creation
- [ ] asset deletion
- [x] taxonomy creation/published (cp.published, cp.term.published)
- [ ] taxonomy deletion
- [x] globals creation (cp.globals.published)

Thx

**Comment by jackmcdade** [comment]
Most if not all or more of these have been added over the past many releases.
