### ISSUE TITLE
Unable to force/set default fieldset for folder of pages

### ISSUE THREAD

**Issue by gmcz** [statamic/v2-hub#693]
### Steps to reproduce
1. Create page with subpages.
2. Place `folder.yaml` with `fieldset: fieldsest-for-folder` in the folder for the parent page
3. Create new subpage in that folder from the CP
### Expected behavior

Create a subpage using the default fieldset chosen in `folder.yaml`. No option to choose a different fieldset in the CP.
### Actual behavior

You are prompted to "Choose a Page Type".
### Server configuration

**Operating system**: 
OS X, MAMP

**Web server:** 
Apache

**PHP version:**
7

**Statamic version:** 
2.0.5

**Updated from an older Statamic or fresh install:**
Updated from 2.0.4

**List of installed addons:** 
None.

**Comment by GMCz** [comment]
Also tried variations such as:

```
_fieldset:
default_fieldset:
_default_fieldset:
```

**Comment by jasonvarga** [comment]
None will work. It'll be `fieldset: whatever` when it does. Down with underscores!

**Comment by GMCz** [comment]
I figured! I left `fieldset:` in my `folder.yaml`. Figured I should just document the other things I tried in case someone else has the bright idea to poke around... save them the wasted time.

**Comment by mhayes14** [comment]
I would also like to force the fieldset (and template) for sub-pages of a certain directly. I've tried creating a `folder.yaml` file with the `fieldset` property as described in this issue but it doesn't seem to be working.

Does this feature exist?
