### ISSUE TITLE
FR: Make crop_focal available as assets tag output

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#695]
It would be nice to be able to use the focal point data when using assets as a background image.

Some thing like
```
{{ assets:image }}
    <div style="background:url('{{ url }}') no-repeat {{ crop_focal }};"></div>
{{ /assets:image }}
```

**Comment by jasonvarga** [comment]
`{{ focus }}` is available, but it's in the form of `x-y`. I'm sure you can still use that somehow.

```
style="background: url('{{ url }}') no-repeat {{ focus replace="-|% " }}%
```

A little messy, but it can work.

**Comment by lesaff** [comment]
I can work with that, thx

**Comment by mikemartin** [comment]
@jasonvarga 
Another use case for this is cropping before resize. 
http://glide.thephpleague.com/1.0/api/crop/#crop-crop

Example:
`<img src="{{ glide:id crop="510,290,{focus-x},{focus-y}" }}">`

I've tried `{{ focus replace="-|," }}` but I don't think a modifier will work inside the glide tag.
