### ISSUE TITLE
Taxonomy terms not localizable

### ISSUE THREAD

**Issue by frankmichel** [statamic/v2-hub#701]
### Steps to reproduce
1. edit a taxonomy term by going to /cp/taxonomies/terms/tags/coffee
2. choose another locale
3. Route [taxonomy.localize] not defined

### Fix
I fixed by updating the **PublishController.php** on lines:
[389] changed `taxonomy.localize` to `term.localize`
[395] changed `taxonomy.show` to `term.show`

**Comment by jasonvarga** [comment]
Thanks!
