### ISSUE TITLE
If you delete an image from assets, it causes an infinite loading spinner in CP

### ISSUE THREAD

**Issue by humanjpg** [statamic/v2-hub#703]
### Steps to reproduce
1. Setup a post with an asset field
2. Create an entry, add an asset to it and save
3. Delete the asset from the CP
4. Go back to the entry and rotate your eyeballs until you feel dizzy (don't do this)

### Expected behaviour
Should display error to the following effect: 'Image not found' with two options:
`Delete` and `Select another`

### Actual behaviour
Aforementioned eyeball rotation

Also a bit annoying as you might have an image accompanied by other text fields, with no way of escaping the spinner and replacing the image. Can obviously just delete it from the `.md` file, but a button in the CP would be easier. Should perhaps fail after a certain number of attempts?

Noticed it also happens with empty images and empty arrays (which might of course just be life) :
`image: `
`image: [ ]`

### Server configuration
**Operating system**: OSX

**Web server:** Apache (MAMP)

**PHP version:** 5.6.1.0

**Statamic version:** 2.0.5

**Updated from an older Statamic or fresh install:** Manual Ghetto Upgrade

**List of installed addons:** Useragent (but unrelated)

### Browser Logs
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
undefined:1 Uncaught (in promise) XMLHttpRequest
```

**Comment by trevorgehman** [comment]
Noticed this happening as well.
