### ISSUE TITLE
Array Sort Flags

### ISSUE THREAD

**Issue by intrepidws** [statamic/v2-hub#706]
Would be helpful if we could provide sort flags (per http://php.net/manual/en/function.sort.php) to the array `sort` modifier (https://docs.statamic.com/reference/modifiers#array:sort).

Or maybe another version of that modifier that would sort the below list with 'Teledyne Relays' ahead of 'TRAK Microwave' and 'TRM Microwave' rather than after (ignoring the case, in other words). This is the current output from the array `sort` modifier:
- American Technical Ceramics
- CTT
- Cobham
- Linx Technologies
- Lorch Microwave
- MegaPhase
- Mitsubishi Electric
- TRAK Microwave
- TRM Microwave
- Teledyne Relays
- Universal Switching Corporation

**Comment by jasonvarga** [comment]
That's kinda dumb hey. We'll have to work out a nice way to enable this. Good find!

**Comment by jasonvarga** [comment]
Looks like this has been addressed in 2.5.11
