### ISSUE TITLE
FR: Make the Algolia index configurable

### ISSUE THREAD

**Issue by markzegarelli** [statamic/v2-hub#707]
When using the Algolia search driver, content is indexed to the Default index.

It would be great to have this configurable for instances which require multiple search indicies. For example, a staging server would post content to a `staging` index, Production -> `production`.

Ideally, this could be handled with env variables.

**Comment by jasonvarga** [comment]
It can. 

`Settings > Search > Default Index` in the CP, or `default_index: whatever` in `site/settings/search.yaml`.

If you want to use an environment variable, just do `default_index: '{env:DEFAULT_SEARCH_INDEX}'` (call it whatever you want). It'll read that from your `.env` file.

**Comment by markzegarelli** [comment]
wow. no idea how I missed that. Anyway, thanks for the explainer.
