### ISSUE TITLE
Variables in routes/mounted collections should be slugifyable

### ISSUE THREAD

**Issue by subpixelch** [statamic/v2-hub#709]
### Steps to reproduce
1. Mount a collection in the Routes-Section
   `ref: /ref/{year}/{month}/{standort}/{slug}`
   `Example: www.domain.ch/ref/2016/05/mööööhlin/slug`
2. User a modifier in the URL in the Routes-Section
   `ref: /ref/{year}/{month}/{standort|slugify}/{slug}` 
   `Example: www.domain.ch/ref/2016/05/moeoeoeoehlin/slug`
3. Look at the generated URL from this collection
### Expected behaviour

The variable `{standort|slugify}` generated mount-point URL should be slugified
`Example: www.domain.ch/ref/2016/05/moeoeoeoehlin/slug`
### Actual behaviour

... it is not. It outputs this:
`www.domain.ch/ref/2016/05/mööööhlin%20|%20slugify/slug`
### Server configuration

Linux

**Web server:**
Ubuntu 14.04

**PHP version:**
7.0.0

**Statamic version:**
2.0.5

**Updated from an older Statamic or fresh install:**
Updated from 2.0.3

**List of installed addons:**
none

**Comment by rrelmy** [comment]
If you are willing to hack the core the following changes inside `statamic/core/Data/Content/UrlBuilder.php` will implement the feature:

````
        preg_match_all('/{\s*([a-zA-Z0-9_\-]+)(?:\s*\|\s*([a-zA-Z0-9_\-]+))?\s*}/', $route_url, $matches);
        $url = $route_url;

        foreach ($matches[1] as $key => $variable) {
            $modifier = $matches[2][$key];
            if ($value = $this->content->get($variable)) {
                if ($modifier === 'slugify') {
                    $value = slugify($value);
                }

                $value = rawurlencode($value);
````

Then you can use routes like that `referenzen: '/referenzen/{hauptdienstleistung|slugify}/{ort|slugify}/{slug}'`

Do not forget to clear the cache!
