### ISSUE TITLE
FR: Add list mode option when opening asset manager modal window

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#711]
Right now, when selecting assets from the Asset Manager modal window, we see these giant document icons in grid mode. There should also be an option to view in list mode, which is nicer when you have many files to select.

![screen shot 2016-05-27 at 10 28 40 am](https://cloud.githubusercontent.com/assets/1151181/15609339/d731d46c-23f5-11e6-9873-448c5991f964.png)

**Comment by jasonvarga** [comment]
Already done for 2.0.6

**Comment by lesaff** [comment]
Too quick, Thx 👍
