### ISSUE TITLE
Broken asset document icon image after selecting asset from the manager

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#712]
### Steps to reproduce
1. Select an asset from asset manager modal window (see anim gif below)
### Expected behaviour

Selected document should appear with its related document icon image
### Actual behaviour

Broken image
### Server configuration

**Operating system**: El Capitan Latest

**Web server:** Valet

**PHP version:** 7.x

**Statamic version:** 2.0.5

**Updated from an older Statamic or fresh install:** Update

![asset-undefined](https://cloud.githubusercontent.com/assets/1151181/15609728/1dc9840e-23f8-11e6-9f22-ca2bc1799375.gif)

**Comment by jaggy** [comment]
@lesaff, does this still happen?
