### ISSUE TITLE
Broken link on developer mode page

### ISSUE THREAD

**Issue by johnmeilleur** [statamic/v2-hub#713]
### Steps to reproduce
1. Install Statamic on a non-dev domain (do not run installer)
2. Go to CP and get developer mode page
![image](https://cloud.githubusercontent.com/assets/1945088/15610167/206fdb66-23e1-11e6-8205-f8b9a4634c15.png)
3. Click on Learn more about developer mode.

### Expected behaviour
Page should have content?

### Actual behaviour
404 page

### Server configuration
Statamic v2.0.5
Fresh install

**Comment by jasonvarga** [comment]
We were optimistic when we updated that screen, haha. Coming soon.
