### ISSUE TITLE
Email sender errors when form includes array field

### ISSUE THREAD

**Issue by colinmeinke** [statamic/v2-hub#720]
When sending a form that includes array data email sender errors:

`[2016-05-30 17:53:32] production.ERROR: exception 'ErrorException' with message 'Array to string conversion' in /Users/colin/Dropbox/projects/cardconnect/statamic/core/Email/Sender.php:144`

This is that method, which does not expect a field to include array data so throws when it tries to print an array as a string:

```
    private function getAutomagicEmail()
    {
        $html = '';
        $text = '';

        foreach ($this->message->data() as $key => $value) {
            $html .= "<strong>" . $key . "</strong>: " . $value . "<br><br>\n";
            $text .= $key . ": " . $value . "\n";
        }

        return [$html, $text];
    }
```

**Comment by baybara-pavel** [comment]
Just one string can solve this issue, but this is core Statamic component, and any updates broke this again :(
```
private function getAutomagicEmail()
    {
        $html = '';
        $text = '';

        foreach ($this->message->data() as $key => $value) {
            $value = is_array($value) ? implode(', ', $value) : $value;
            $html .= "<strong>" . $key . "</strong>: " . $value . "<br><br>\n";
            $text .= $key . ": " . $value . "\n";
        }

        return [$html, $text];
    }
```

**Comment by rrelmy** [comment]
Just having the same problem :-(
