### ISSUE TITLE
Partial field in replicator and grid

### ISSUE THREAD

**Issue by okse** [statamic/v2-hub#723]
It would be awesome, and I would very much appreciate the possibility of using a partial field in a replicator. Thank you :)

**Comment by thestepafter** [comment]
Are there any plans to add this in the next version?

**Comment by rrelmy** [comment]
This would be very useful!

**Comment by wesort** [comment]
+1 for this from me too.

**Comment by kevnk** [comment]
+1

**Comment by rickysalsberry** [comment]
+1, was surprised this didn't work

**Comment by mmintel** [comment]
mh are there any plans on this? i think this feature decides whether i am going to buy a license or not..

**Comment by jackmcdade** [comment]
@mmintel it boils down to a little copy and pasting whether you're going to use the whole CMS or not?

**Comment by mmintel** [comment]
that means no there are no plans? :D 
if think you should be careful about buying a software if there is a bug like that which exists for more than a year and is still not updated in the docs, so i don't know what else doesn't work but is not mentioned anywhere. And if I would like to copy and paste my code I would not really need a CMS at all. But that was not my question..

**Comment by jackmcdade** [comment]
It's not a bug though, it's just not a feature we've added yet because it's actually very complex to implement. I WANT to do it, i just don't know if we CAN do it without having to rewrite a large chunk of the fieldtype logic.

**Comment by mmintel** [comment]
But yes I want to make heavy use of that feature and for me its very important to move this into small files instead of having one file which will be really big for my case. Maybe you should remove this from the docs if it doesn't exist and is not planned to be added at the moment.

**Comment by jackmcdade** [comment]
Partials _do_ exist, they're just for root level fieldset stuff. We'll look into it again.

**Comment by mmintel** [comment]
I mean there is a code example in the replicator field documentation, you should remove the code example that uses a partial, just to avoid more confusion.

**Comment by jackmcdade** [comment]
That documentation is for `template partials`, not fieldset partials. Totally different, though I do see how someone might mix those up. We really should have called CP partials "includes" or "imports".

**Comment by mmintel** [comment]
Okay I am confused. I try this code:
```
{{ relate:components }}
  {{ modules }}
    {{ type }}
    {{ partial src="sets/{type}" }}
  {{ /modules }}
{{ /relate:components }}
```

**Comment by jackmcdade** [comment]
Wait, is this issue about Fieldset partials or Template partials? Now _I'm_ confused!

**Comment by thestepafter** [comment]
Partials in replicators would definitely be a big benefit since cutting and pasting code is prone to error and field set files can get rather large. This would also help with creating more modular field sets where you want a field set based on a specific set of data but you also want some common fields included. For example, events, news, blog posts, all have common date elements of when you want to schedule them to be posted, start and end date, etc. It would be nice to be able to add this on the fly in a replicator instead of having separate field definitions for the same thing.

**Comment by mmintel** [comment]
Mh everything I want to do is using the replicator field type like the docs recommend it. I want to move my "if-else" statements into small template partials. Of course I want to use the variables of the replicator field in my partial, otherwise it would not make sense to use it like that?

**Comment by thestepafter** [comment]
@mmintel You can do this then, just pass the values from the replicator to the partials like this:

`{{ partial:list header="Favorite Animals" :items="animals" }}`

Then you can reference the value of header and items in the partial template file.

I do this extensively with my templates.

**Comment by mmintel** [comment]
For me that doesn't work..

I have this code in my template:
```
{{ relate:components }}
  {{ modules }}
    {{ if type == 'title'}}
      This is the title
      {{ partial:title }}
    {{ elseif type == 'subtitle'}}
      {{ partial:subtitle }}
    {{ /if }}
  {{ /modules }}
{{ /relate:components }}
```

And this here is my project structure:
![2017-08-15_screenshot](https://user-images.githubusercontent.com/4574612/29318767-bb6f6fe2-81d1-11e7-98dd-f9cddd010ca7.png)

The message "This is the title" is displayed, the partial is not visible.

**Comment by jackmcdade** [comment]
Can you take this to [Slack](http://slack.statamic.com) or the [Lodge](https://lodge.statamic.com) for some support? Happy to help, but this isn't related to this particular Issue :)

**Comment by jasonvarga** [comment]
@mmintel You have your `partials` directory inside the `templates` directory. It should be one level up.

```
/themes/yourtheme/
|-- partials
|    |-- subtitle.html
|-- templates
```

However, this Github issue is concerning partial _fieldtypes_ inside of grid and replicator _fieldtypes_.

**Comment by mmintel** [comment]
alright, sorry that I used wrong issue, i thought thats exactly the same problem. really confusing with partials, but now I am at least happy that my problem was solved and I can continue using this CMS :D
