### ISSUE TITLE
Deleted asset folder keeps reappearing in CP

### ISSUE THREAD

**Issue by jszobody** [statamic/v2-hub#727]
### Steps to reproduce
1. Go to Assets in CP, create a folder
2. Delete the folder in CP
3. Refresh browser, folder reappears in list
4. `php please clear:cache` fixes it
### Expected behaviour

Deleted folder should stay dead. We ain't north of the wall!
### Actual behaviour

Total wight behavior
### Server configuration

**Operating system**: OSX
**Web server:** Caddy (Laravel Valet)
**PHP version:** 5.6
**Statamic version:** 2.0.7
**Updated from an older Statamic or fresh install:** Updated from fresh 2.0.5 
**List of installed addons:** Only one, homebuilt
### Logs

Suffice it to say there are no errors in any of the logs that I'm seeing. The ajax call to delete the folder works, receives a `HTTP 200` response. The folder really is deleted from my machine. It's just a caching issue from what I see.

**Comment by jasonvarga** [comment]
Confirmed
