### ISSUE TITLE
Image assets with a prefix of img don't generate previews

### ISSUE THREAD

**Issue by stevieg83** [statamic/v2-hub#729]
### Steps to reproduce
1. have an image asset named `img01.jpg` as an example
2. sync assets
3. view the assets
4. thumbnail doesn't display
### Expected behaviour

Thumbnail should display
### Actual behaviour

Server generates a 500 error
### Server configuration

**Operating system**:
OSX
**Web server:**
MAMP
**PHP version:**
7.0.0
**Statamic version:**
2.0.7
**Updated from an older Statamic or fresh install:**
Updated from old
**List of installed addons:**
none

**Comment by jasonvarga** [comment]
Looks like a bug with Glide. I submitted a PR bugfix, so we'll see if it makes it for 2.5. If not, probably not long after.

**Comment by edalzell** [comment]
It's been merged, perhaps the next point release? https://github.com/thephpleague/glide/pull/171
