### ISSUE TITLE
FR: Number fieldtype

### ISSUE THREAD

**Issue by igregson** [statamic/v2-hub#737]
Basic but useful.

**Comment by jademcquade** [comment]
Yeah the example of collecting mobile phone numbers where the leading 0 isn't stripped out and is present in form reporting in the CP would be a good bonus e.g. 07924564928

**Comment by stevieg83** [comment]
not sure why you'd want a phone number to be a number field?

**Comment by igregson** [comment]
Even if not the best fit for a phone number this would still be incredibly useful. The UX of putting numbers into a text field just doesn't seem right.

**Comment by jackmcdade** [comment]
You can use a text field with `type: mode`.

```
fields:
  phone:
    type: text
    mode: number
```
