### ISSUE TITLE
Assets manager should have the option to convert filenames to web-friendly format

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#74]
Essentially slugify the filename, all lowercase.

**Comment by jasonvarga** [comment]
Where are you finding this a problem?

**Comment by lesaff** [comment]
We try to enforce all uploads to web-friendly format so that clients don't upload files with spaces or weird characters. More of a policy than a problem.

**Comment by jasonvarga** [comment]
Okay. 2.0.6 will url encode asset URLs (like when you do `{{ url }}`) Technically a filename is allowed to have spaces.

**Comment by mikemartin** [comment]
The asset field does not seem to be upload filenames with spaces in v2.0.9.
[See Video](https://www.dropbox.com/s/j5qtfww4s64d76e/Images%20not%20saving.mov?dl=0)
