### ISSUE TITLE
Grid row does not like asset field set to null

### ISSUE THREAD

**Issue by stevieg83** [statamic/v2-hub#740]
### Steps to reproduce
1. create a grid field
2. create an asset field inside the grid
3. create a text field inside the grid
4. add a new row in an entry - add text but no image
5. 

### Expected behaviour
When no image is present, I should be able to upload a new image or select an existing image

### Actual behaviour
save the entry and the asset field shows loading gif with no option to upload a file or choose existing

### Server configuration
**Operating system**: El Capitan

**Web server:**
Apache

**PHP version:**
5.6.10
**Statamic version:**
2.0.7
**Updated from an older Statamic or fresh install:**
fresh
**List of installed addons:**
na

**Comment by jackmcdade** [comment]
Fixed in dev.

**Comment by stevieg83** [comment]
👍
