### ISSUE TITLE
Assets: certain PDF files not uploading

### ISSUE THREAD

**Issue by serieseight** [statamic/v2-hub#741]
### Steps to reproduce
1. Download PDF Attached: http://cdn.cardconnect.com/docs/collateral/cardconnect-investor-presentation-2016.pdf
2. Try Upload it to assets
3. Does not upload
### Expected behaviour

It Should upload
### Actual behaviour

It does not upload 
### Server configuration

**Operating system**: 

**Web server:** Linux

**PHP version:** 7.0

**Statamic version:** 2.0.7

Also have updated php.ini file upload size in `/etc/php/7.0/fpm/php.ini` & does not work on my local machine either.

**Comment by lesaff** [comment]
I noticed the same behaviour as well. Certain PDF files are not uploaded/accepted by the asset manager.

**Comment by stevieg83** [comment]
how was the PDF generated? I know that ultimately it shouldn't matter but I've seen instances in the past where XSS tools reject some PDF uploads.

**Comment by serieseight** [comment]
@stevieg83 No idea, should accept any pdf as the client would be uploading it.

**Comment by lesaff** [comment]
Some are generated by Microsoft Powerpoint (via save to PDF). I even tried to re-save it using Adobe Acrobat and still no luck. I wonder if the uploader checks the file headers?

**Comment by serieseight** [comment]
Could you download the PDF I have attached above and check the file headers there?

**Comment by stevieg83** [comment]
I agree - it should but what I've said *could* be why it's not.

**Comment by jackmcdade** [comment]
What's your `post_max_size` set to?
I had issues with the PDF until i bumped up both `upload_max_filesize` ​_and_​  `post_max_size`
then it worked.

**Comment by serieseight** [comment]
@jackmcdade bumped it to `post_max_size = 15M` + `upload_max_filesize = 50M`

**Comment by jasonvarga** [comment]
Are you saying that fixed it, or not?

**Comment by serieseight** [comment]
@jasonvarga I tried this before posting the issue up and it did't solve it, Also made sure to restart nginx

**Comment by jackmcdade** [comment]
Did you confirm with a `phpinfo()` that the value is set as expected?

**Comment by edalzell** [comment]
in 2.1.14, the PDF mentioned at the top by @serieseight works now.
![browsing assets statamic 2016-10-07 09-02-39](https://cloud.githubusercontent.com/assets/6069653/19197060/d4263526-8c6c-11e6-86a3-9261016eec8d.png)

**Comment by jackmcdade** [comment]
This issue is a bit stale so we're closing it for now. If it rears its head again, please feel free to reopen and ping us!
