### ISSUE TITLE
FR: Please add choose button after creating a folder in assets manager modal

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#745]
Please add 'Browse File' button after creating a folder in assets manager modal
Please disable 'select' button if there is no image in the folder...

<img width="1128" alt="screen shot 2016-06-09 at 9 02 55 pm" src="https://cloud.githubusercontent.com/assets/5695187/15937819/ab83ac9c-2e85-11e6-8d7e-7a012f79f980.png">

**Comment by jasonvarga** [comment]
This will be pretty much irrelevant in 2.5
