### ISSUE TITLE
I can choose more than max allowed files in assets manager

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#747]
![screen shot 2016-06-09 at 9 13 45 pm](https://cloud.githubusercontent.com/assets/5695187/15938269/bdb3ae9c-2e87-11e6-94ae-eb5d01cbe18f.jpg)

**Statamic version:** 2.0.7

**Comment by jasonvarga** [comment]
What happens after you click select?

**Comment by peimn** [comment]
It selects the first one.
But its confusing that I can choose more than one.
