### ISSUE TITLE
Pressing the cmd+s key combination does not save a fieldset

### ISSUE THREAD

**Issue by pryley** [statamic/v2-hub#751]
`cmd+s` works everywhere in the CP except when editing fieldsets.

**Comment by edalzell** [comment]
Is this still true @pryley?

**Comment by pryley** [comment]
Yep, still true on v2.5.5

CMD+S on a page:
![image](https://cloud.githubusercontent.com/assets/134939/23784127/8b629ac6-0536-11e7-9974-859df44f4a27.png)

CMD+S on a fieldset:
![image](https://cloud.githubusercontent.com/assets/134939/23784146/a59d9a8a-0536-11e7-9534-efe1b04329b8.png)
