### ISSUE TITLE
Relate dropdown doesn't reset label variables when sorted

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#758]
### Steps to reproduce
1. Create some pages
2. Create a fieldset _foo_ with field _foo_ of type `text`
3. Create one page of that fieldset and enter "Na" in _foo_
4. Create another fieldset _bar_ with a `pages` field, set `label: {foo}, sort: "foo:asc"`
5. Open the Create Page dialog and choose type _bar_
### Expected behaviour

The dropdown lists one _Na_ first, then a lot of empty options.
### Actual behaviour

The dropdown only lists _Na_ a lot of times.
### Server configuration

**Operating system**: Fedora 22 64-bit

**Web server:** php -S

**PHP version:** 5.6.20

**Statamic version:** 2.0.7

**Updated from an older Statamic or fresh install:** Fresh fieldset.

**List of installed addons:** None

**Comment by andypillip** [comment]
A consequence is also that `label: {{ foo or "no foo" }}` will not work.

**Comment by edalzell** [comment]
@andypillip does this still happen?

**Comment by andypillip** [comment]
Apparently it's fixed, just updated to 2.5.8.

Thanks.
