### ISSUE TITLE
FR: Locale filter

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#759]
Right now it's not possible to filter with locales, which is absolutely necessary for multilingual websites.

It's a bad user experience to get mixed contents of two languages.
Not showing anything than showing a foreign language would be better.

Right now statamic doesn't offer any filter-option for that, f.e. `{{ collection:jobs locale:is="{{ locale }}" }}` will not work.

Also the `nav` Tags would need that filter.

**Comment by jasonvarga** [comment]
It should use the locale data of whatever you're in. Keep in mind that if you haven't localized a field, it falls back to the default locale. Maybe that's what you're seeing?

**Comment by andypillip** [comment]
thx Jason.

> it falls back to the default locale

That's what I consider a bad user experience: Mixed languages on one site.

So it should be at least possible to deactivate that function by filtering to the current language exclusively.

**Comment by jasonvarga** [comment]
Okay so the 'solution' is to just make sure you have everything translated.

Are you asking for a way to show _only_ entries that have been translated into the specified locale?

**Comment by andypillip** [comment]
@jasonvarga yes, that's what I'm asking for.

**Comment by jasonvarga** [comment]
Ok cool, just checking. We can make that happen.

**Comment by andypillip** [comment]
@jasonvarga that'd be cool.

Related: How it possible to provide a language switch, that switches the current page?

**Comment by jasonvarga** [comment]
In the next release you'll be able to do `{{ collection locale="only fr" }}`, for example.

**Comment by andypillip** [comment]
@jasonvarga nice, so ```"only { locale }"``` will filter to the current locale?

When is the next release expected?

**Comment by jasonvarga** [comment]
Next release is coming very soon.

The nav tag is a little different, so you will still get the fallbacks.

**Comment by andypillip** [comment]
@jasonvarga this doesn't seem to work with 2.5.9?

I tried `{{ collection:posts locale="only {locale}" }}` as well as `{{ collection:posts locale="only en" }}`. Default locale is _DE_.

I created a new post from CP and didn't provide a translation. Also I checked that in the _posts/en/_ folder there was no file for that post.

There's no file in _en_, yet the post gets listed.

Thanks for checking.
