### ISSUE TITLE
FR: Additional conditional - match a string inside a given array or string

### ISSUE THREAD

**Issue by chris-79** [statamic/v2-hub#760]
Suggested function name: `in`

### Why?

To connect collections together based on `slug` or `title` or similar.

### Example

Find entries in a "recurring-events" collection whose `slug` is in an array called `event-series` in a "calendar-events" collection:
`{{ collection:recurring-events slug:in="{ event-series }" }}`

**Comment by jackmcdade** [comment]
I _think_ you're coming at this backwards. In the conditions, you want to filter based on the data inside it (the condition) with data from your current context (the param). You should be able to do this:

```
{{ collection:recurring-events event-series:contains="{slug}" }}`
```

**Comment by chris-79** [comment]
(I ended up using IDs instead of slugs)

The entries in the `calendar-events` collection contain arrays like:
```
series:
  - 820aea27-1925-44a0-8819-ac12f4a9e0a7
  - 6594680e-3a94-4e54-a4ad-aa031995af66
```

… Where those IDs match IDs for the collection `recurring-events`.

This works for now:

```
{{ if series }}
  {{ collection:recurring-events }}
    {{ if (id | in_array:series) }}
```

Would be nice, though, if `in_array` was available at the tag level, like, say…

```
{{ if series }}
  {{ collection:recurring-events id:in_array="{ series }" }}
```

But I have my workaround, so ¯\\\_(ツ)_/¯
