### ISSUE TITLE
Form File does not output Asset URL in Html Email Template

### ISSUE THREAD

**Issue by serieseight** [statamic/v2-hub#762]
Form File does not output Asset URL in Html Email Template, It does output the ID of the asset but does not output a URL for that file in an email.

Spoke to @jasonvarga about this one ✊

**Comment by serieseight** [comment]
Any updates on this one?

**Comment by serieseight** [comment]
Any bumps on this?

**Comment by edalzell** [comment]
@serieseight can this be closed now that assets use paths?
