### ISSUE TITLE
FR: Allow Addons To Prevent Forms From Saving

### ISSUE THREAD

**Issue by warkior** [statamic/v2-hub#765]
It would be helpful in certain circumstances to be able to have an addon block the save method on specific forms. Here's a possible solution...

http://s.warkior.com/FormListener_php_1D1362E0.png

With this strategy, addons could listen for the `Form.submission.allow-save` event, and return false, if they wish to prevent the save.

**Comment by warkior** [comment]
The solution as code:
```php

        if($this->allowedToSave($submission))
            $submission->save();

        // Emit an event after the submission has been created.
        $this->emitEvent('submission.created', $submission);

        return $this->formSuccess($params, $submission);
    }

    private function allowedToSave($submission)
    {
        $allowSaveResponses = $this->emitEvent('submission.allow-save', $submission);
        if(!empty($allowSaveResponses) && is_array($allowSaveResponses))
            foreach($allowSaveResponses as $response)
                if(!$response)
                    return false;
        return true;
    }
```

**Comment by warkior** [comment]
An alternative solution (which might be more elegant) would be to include an "isStorable" field on the Submission object, which could then be modified by the addon if necessary. This would avoid the need for another event to be handled.

Something like this...
```php
        // Allow addons to prevent the submission of the form, return
        // their own errors, and modify the submission.
        list($errors, $submission) = $this->runCreatingEvent($submission);

        if ($errors) {
            return $error_redirect->withInput()->withErrors($errors, 'form.'.$formset);
        }

        // Don't save if the submission is not storable.
        if( $submission->isStorable )
        {
            $submission->save();
        }

        // Emit an event after the submission has been created.
        $this->emitEvent('submission.created', $submission);
```

**Comment by jasonvarga** [comment]
In what situation would you want to prevent saving?

**Comment by edalzell** [comment]
@jasonvarga, I think it's because he had to create his own form due to [this](https://github.com/statamic/v2-hub/issues/440)

**Comment by warkior** [comment]
@jasonvarga @edalzell - That's one situation. Another would be the creation of forms which are handled by third party processing. Just for one example, a mailing list subscribe. Someone might design a form to collect name and email, and have the results processed by an addon which sends to the mailing list API, but there would be no need to save the (potentially thousands) of simple name/email form submissions to the local filesystem. Another example might be a situation where the webmaster might wish to save site related settings without also storing the results in a form submission. I'm sure there are other situations in which this functionality would be handy as well.

**Comment by jasonvarga** [comment]
If you're doing that honestly it might just be simpler to write your own form handler.

If the data isn't being saved for Statamic to use, you aren't gaining much by using the built in Forms feature.

Just make a regular html form, post to `/!/MyAddon/handle`, listen for that in a listener class, and do whatever processing you need.

**Comment by warkior** [comment]
@jasonvarga - That's helpful, thanks. I didn't know that I could do that. Is there documentation somewhere on that process? (submitting form data directly to an addon listener)

**Comment by jasonvarga** [comment]
You know what, I don't think there is. I can't see anything documented for the event route.

In a nutshell: Any request to `/!/foo/bar` will emit a `foo.bar` event.

Convention is to do `/!/MyAddon/foo` then in your [event listener](https://docs.statamic.com/addons/anatomy/event-listeners), do this:

```
public $events = [
  'MyAddon.foo' => 'doSomethingWithFoo'
];

public function doSomethingWithFoo()
{
   //
}
```

**Comment by warkior** [comment]
Awesome. That's very helpful to know. Thank you!

**Comment by warkior** [comment]
In this case no change to the existing form processing needs to be made. Closing the issue.
