### ISSUE TITLE
FR: Make home page use title data in control panel

### ISSUE THREAD

**Issue by macbruker** [statamic/v2-hub#766]
All pages use `title` in the tree view exept for the **Home** page.
I think it's a good idea to have the **Home** page follow the same logic as the rest of the pages.

**Comment by GMCz** [comment]
Or, if you Gentlemen think it's important to treat it differently, show the `title` in a less prominent way right after Home... maybe something like this:

> **Home** - _This is the actual title of the page_

or with an icon?

> 🏠 **This is the actual title of the page**

**Comment by macbruker** [comment]
Nice addition! I like the icon idea :)

For some of the sites I work on, english isn't the primary language. In those cases an icon and a `title` would be great.

**Comment by thestepafter** [comment]
+1

**Comment by jasonvarga** [comment]
![image](https://cloud.githubusercontent.com/assets/105211/16974191/1bc55bb2-4e08-11e6-9d6c-46c8c27cfbda.png)
