### ISSUE TITLE
Localizable Toggle reverts to previous state on save in the CP

### ISSUE THREAD

**Issue by ItsMeAra** [statamic/v2-hub#767]
### Steps to reproduce
1. Login to CP
2. Click on 'Fieldsets' under 'Configure' in the sidebar.
3. Select any Fieldset
4. Click on the localizable toggle to change it's value (on -> off, or off -> on)
5. Click save.
### Expected behaviour

Pressing save should save the changed value of the toggle, not revert it.
### Actual behaviour

Notice the page refreshed after save, and the toggle went back to it's original state and did not save.

<img src="https://cloud.githubusercontent.com/assets/308142/16156950/55b45316-346b-11e6-87ef-ca59e2c14947.gif" width="230"/>
### Server configuration

**Operating system**:  OS X El Capitan 10.11.5

**Web server:** MAMP

**PHP version:** 7.0.0

**Statamic version:** 2.0.9

**Updated from an older Statamic or fresh install:** Fresh install

**List of installed addons:**
- CacheManager 1.0.1 (but had this issue with or without this plugin)
#### Web server error log

```
nothing in logs
```
#### Statamic error log (`/local/storage/logs/statamic.log`)

```
 Marker - Jun 17, 2016, 9:05:29 AM
[2016-06-17 16:05:37] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.  
```

**Comment by ItsMeAra** [comment]
There is a workaround for now...

1. Click Edit/pencil icon of a field 
2. Click on the toggle in the popup here http://drop.itsmeara.com/15nel/4s6EK64k 
3. Close
4. Then save

Notice it saves correctly...

**Comment by ItsMeAra** [comment]
Just a note that this is still happening in the latest 2.1.0

**Comment by smcyr** [comment]
The same happens for me too.

**Comment by jasonvarga** [comment]
Cool, we didn't attempt to fix it, so it should still be broken.
