### ISSUE TITLE
FR: Ability to customize CP copy "Create Entry" in Collections

### ISSUE THREAD

**Issue by gmcz** [statamic/v2-hub#769]
As in V1, it would be nice to be able to customize how the CP refers to entries in collections. (For example, I'd like this to say "Add Project" or "New Project" rather than "Create Entry". (I'd be ok with "Create Project" too, if that gets this added to the core faster. 😁

**The offending button:**
<img width="126" alt="screen shot 2016-06-20 at 3 11 37 pm" src="https://cloud.githubusercontent.com/assets/869452/16207071/5357ce3c-36f9-11e6-962b-fd32f3632c2f.png">

**Comment by jackmcdade** [comment]
Be nice to that button. It's hardly an "offender" ;)

**Comment by GMCz** [comment]
It's true... I do like this little fella. Nice button.

**Comment by jackmcdade** [comment]
You've been able to do this for a while now with the `create_title` option. 🤘
