### ISSUE TITLE
FR: Add ability to customize "Add Row" button in Grid fields

### ISSUE THREAD

**Issue by mikegraham00** [statamic/v2-hub#774]
Would be just super duper if you could change the "Row" text in the Grid field Add Row button. Users don't always think of them as rows. Sometimes they're items. Or doohickeys.

You get the idea..

**Comment by PhilippeGauthier** [comment]
See very bottom of the Grid documentation.
https://docs.statamic.com/reference/fieldtypes/grid

**Comment by mikegraham00** [comment]
How did I miss that? Thanks!!

**Comment by mikegraham00** [comment]
Would be perfect if it were an option when creating/editing Grid fieldtype in the CP.
...or did I miss that too?

**Comment by PhilippeGauthier** [comment]
I think he meant the option to edit the `add_row` field, not creating the grid.
![screen shot 2016-06-23 at 5 15 43 pm](https://cloud.githubusercontent.com/assets/4649619/16324290/dc183cdc-3967-11e6-8308-8fc0d5462061.png)

**Comment by jackmcdade** [comment]
You can actually do this now by setting the `add_row` setting in the YAML file directly. Will add the option in the CP in the next release.
