### ISSUE TITLE
FR: Ability to use multiple collections in a collection fieldtype

### ISSUE THREAD

**Issue by PhilippeGauthier** [statamic/v2-hub#776]
### Steps to reproduce
1. Add multiple collections to a collection fieldtype
2. Same could be done for taxonomies I'm guessing
### Expected behaviour

my_collection_field:
&nbsp;&nbsp;type: collection
&nbsp;&nbsp;collection: cats | dogs
&nbsp;&nbsp;display: Associate your cat AND dog posts to this post
### Actual behaviour

No cats or dogs

```
```

**Comment by jasonvarga** [comment]
You may use the array syntax

```
my_collection_field:
  type: collection
  collection: [cats, dogs]
```
