### ISSUE TITLE
Listener should have `getParam` helpers

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#780]
Listeners should have the `getParam` helpers that Tags do, to get the params from the URL.

**Comment by jackmcdade** [comment]
`$this->request->get()` should do the trick.

**Comment by edalzell** [comment]
well ya, but I was thinking some consistency....

**Comment by jackmcdade** [comment]
Nothing else gets from the URL so there's nothing to be consistent with really.

**Comment by jasonvarga** [comment]
A listener is associated with an event, not a URL. `$this->getParam` doesn't make sense there.

It just so happens that the event you're concerned with is triggered by a URL.
