### ISSUE TITLE
Addon JS resources don't work

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#781]
### Steps to reproduce
1. use `$this->js->tag('your_js_file')` to include an addon's JS file
2. see if resource is loaded

### Expected behaviour
JS file should be loaded

### Actual behaviour
Resource Not Found

This is a bug in `core/Http/ResourceServer/Server.php`, line 155. Need to be changed to:
```
            $this->base_path = realpath(__DIR__.'/../../../../site/addons/'.$this->addon);
```

**Comment by jasonvarga** [comment]
Put your js in `resources/assets/js`
