### ISSUE TITLE
FR: move locale folder in another directory because it is deleted when upgrading

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#783]
Currently, any locale folder is located in `statamic/resources/lang`

When upgrading statamic, the statamic folder is swapped for a clean one, therefore we are losing any locale folder other than the `en` folder.

Therefore, any locale folder except for `en`should be located in a user dedicated directory that is not swapped when upgrading (/site/settings/ or just /site/ or perhaps /local/)

This is critical for me.

**Comment by jasonvarga** [comment]
The initial idea was for us to take your translations and add them to the core. We know this is something that is taking longer than expected to implement, so what might be a better idea in the meantime is for us to check a different location _first_ (like in `site/settings`) then check the core translations. This would allow you to provide your own translation files that won't get deleted on update.

It would also have the benefit of you being able to override translations if they do ever get added to the core.

Thanks for your patience.

**Comment by ebeauchamps** [comment]
Thanks Jason. I like the second idea. I could help if you wish.

**Comment by ebeauchamps** [comment]
This one has ben solved. There now is a `lang` folder located in the `site` folder
