### ISSUE TITLE
FR: Allow access to content within Form {{errors}} array.

### ISSUE THREAD

**Issue by markzegarelli** [statamic/v2-hub#792]
### Steps to reproduce
1. Add a Form
2. Add an {{errors}} block at the top.
3. Submit a form with an error.
### Expected behaviour

I should be able to use something like `{{value:handle}}` to get the handle of the field with the error. I could use this to add an error class to the specific field. For example `company`.
### Actual behaviour

A simple string is output. For example: `The Company field is required.`
### Server configuration

**Statamic version:**
2.0.11

**Comment by mikegraham00** [comment]
Seconding this FR. Something similar was possible in V1, if I recall correctly.
