### ISSUE TITLE
FR: ability to preview and open an asset from the assets screen.

### ISSUE THREAD

**Issue by netnak** [statamic/v2-hub#795]
When browsing assets there is no way to open an asset.

A client flagged this to me relating to images and I was sure I had seen a way to get a full view of the image from the thumbnail. I went back and checked and what I had remembered was the ability to view an image as an modal overlay when an image is selected in a page/entry, however this same interaction is not available from asset thumbnails.

It would be great to add this.

**Comment by jackmcdade** [comment]
When editing content (using the Assets fieldtype) you can click an image to zoom in, and if you're in the Asset Manager, you can double click. Tada!
