### ISSUE TITLE
Can't add a collection if you've already got exactly one

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#797]
### Steps to reproduce
1. have only one collection in a site
2. go create another via the CP

### Expected behaviour
Should be able to add another collection

### Actual behaviour
Because there is only one, Statamic takes you to it, w/o offering the choice to create a new collection like you get if you have >1 collection

**Comment by jackmcdade** [comment]
That's just a helper. The real place is here: `/cp/configure/content/collections`

![image](https://cloud.githubusercontent.com/assets/44739/16662878/a8b2892a-4447-11e6-91b2-5276b4b11890.png)
