### ISSUE TITLE
Fail more gracefully when glide can't find an image

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#800]
### Steps to reproduce
1. Create a template using a glide tag that tries to read a non-existent image.

### Expected behaviour
Return a broken image link

### Actual behaviour
> Exception in GlideUrlBuilder.php line 335:
> Cannot build a Glide URL without a path or asset ID.

**Comment by jasonvarga** [comment]
Whats the difference? Does not returning a 404 affect something?

**Comment by curtisblackwell** [comment]
Right now, I get the Laravel exception page. A 404 would be great.

**Comment by jasonvarga** [comment]
Thought you were referring to the actual URL itself. Sure no problem.

**Comment by GMCz** [comment]
For what it's worth, I'd prefer not to get a 404 but just to get a broken image, or nothing, or anything other than stopping the page from otherwise rendering.

**Comment by jasonvarga** [comment]
I'm sure he meant a 404 on the image, not the page with the tag. Anyway it's fixed for next release. It'll log the error and output nothing.
