### ISSUE TITLE
getAddonClassName returns null when called in the ServiceProvider boot function

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#803]
### Steps to reproduce
1. Write an addon that uses ServiceProvider
2. Call `$this->getAddonClassName()` from the `boot()` function
### Expected behaviour

It should return the addon's class name
### Actual behaviour

It returns `null`. The rest of addon helpers return expected values.
### Server configuration

**Operating system**: El Capitan [latest]

**Web server:** MAMP Pro

**PHP version:** 7.0.x

**Statamic version:** 2.0.11

**Updated from an older Statamic or fresh install:** Updated

**Comment by edalzell** [comment]
This works for me, on 2.5.4, can it be closed @lesaff?
