### ISSUE TITLE
Shared view in ServiceProvider is not scoped to its addon container

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#804]
### Steps to reproduce
1. Create an addon with ServiceProvider
2. Share a view in the `boot()` function

### Expected behaviour
Shared variables should be scoped in its addon container

### Actual behaviour
Shared variables are available globally

**Comment by jasonvarga** [comment]
Please share a code example.

**Comment by lesaff** [comment]
This is by `boot()` function in all of my addon's ServiceProvider
```
public function boot()
{

    // Global addon variables
    $addon = [
        'timezone'    => Config::get('system')['timezone'],
        'title'       => $this->getMeta()['name'],
        'version'     => $this->getMeta()['version'],
        'addon_name'  => strtolower($this->getAddonName()),
        'cp_path'     => CP_ROUTE
    ];

    view()->share('addon', $addon);
}
```
When I use `{{ $addon['addon_name'] }}` in my blade template, it reads values from my other addon. Currently my workaround is to uniquely name the key so that it doesn't interfere with other addons.

**Comment by jasonvarga** [comment]
view()->share() is designed to share data with all views. Use a view composer instead.

https://laravel.com/docs/5.2/views#view-composers

**Comment by lesaff** [comment]
Noted. Thanks.
