### ISSUE TITLE
Localization trans() namespace is not working on above-root installation

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#805]
### Steps to reproduce
1. Run a v2 site with above-root installation
2. Run an addon that uses `$this->trans()` 
### Expected behaviour

Text/string should be displayed per `addons/<addon_name>/resources/lang/en/filename.php`
### Actual behaviour

`trans('filename.some_key')` returns as is `addons.<addon_name>::filename.some_key`
### Note

This issue does not replicate on a standard install (not above-root)
### Server configuration

**Operating system**: Ubuntu Trusty 64 (14.04 TLS)

**Web server:** Apache 2.4x

**PHP version:** 7.0.8

**Statamic version:** 2.0.11

**Updated from an older Statamic or fresh install:** Updated

**Comment by warkior** [comment]
I've experienced this issue as well. A quick and dirty fix was to just add the following line to statamic/core/Providers/AddonServiceProvider.php on line 116, just before the end…

```
$path = '../' . $path;  // This is the new line that makes addon translations work for me...
$this->loadTranslationsFrom($path, $namespace);
```
This fix will likely be overwritten the next time we upgrade the platform. Perhaps future versions could detect the proper location of the addons folder and use that as part of the $path variable.
