### ISSUE TITLE
CP: Can't click through to form entry's detail view

### ISSUE THREAD

**Issue by aryehdesigns** [statamic/v2-hub#809]
### Steps to reproduce
1. In CP, go to Form index page (listing all entries)
2. Try to click date to open an entry

### Expected behaviour
Opens the entry's detail view showing all data for that entry.

### Actual behaviour
Date isn't a link -- it is wrapped in `<a>` tags, but doesn't have an `href`.

Going to `/cp/forms/[form_name]/submission/[submission_id]` works as expected.

Happens both locally as well as in production.

Weirdly, my other Statamic v2 project doesn't have this issue, so I don't really get why this is happening...

**Comment by kimoxlund** [comment]
Same thing is happening for me. Lots of changes were made to the forms in 2.0.8 and it looks like that's when the issue was introduced. Downgrading to 2.0.7 fixed it for me.
