### ISSUE TITLE
Pokémon found in slug throwing errors

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#810]
### Steps to reproduce
1.  Add the word 'pokémon' to any page slug using the CP
2. 💥 💥 💥 
### Expected behaviour

The slug field should remove special characters on publish to prevent errors.
### Actual behaviour

Blog listing and post throw an error.

**Comment by jasonvarga** [comment]
a wild bug appears

**Comment by edalzell** [comment]
I get a 404 now when I do this, different issue?

**Comment by jackmcdade** [comment]
No longer an issue!

**Comment by aerni90** [comment]
@jackmcdade This is still a problem. A client of mine added manually a "é" to the slug. After that, the whole page went down. No more Back End, no more Front End. The Front End says "Whoops, looks like something went wrong". Here's the error log.
[error.log](https://github.com/statamic/v2-hub/files/1779979/error.log)
