### ISSUE TITLE
If conditional for scoped asset doesn't work

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#815]
### Steps to reproduce
`{{ asset:product:image }}` is working to reference a scoped asset. `{{ if asset:product:image }}` does not work though and nothing is displayed inside of the if conditional.

![conditional-scoped-asset](https://cloud.githubusercontent.com/assets/1793867/16895134/c5c932ae-4b39-11e6-9349-9666a2c6b1e5.gif)

### Expected behaviour
The conditional should evaluate to true if `asset:product:image` exists.

### Actual behaviour
The conditional never evaluates to true, even when the variable is set.

### Server configuration
Linux, all software is the latest version, new install, no addons.

#### Web server error log
none.

#### Statamic error log (`/local/storage/logs/statamic.log`)
none.

#### Browser log
none.

**Comment by jackmcdade** [comment]
You can do {{ if product:image }}. Asset is a Tag, so you'd have to wrap that bit in single variables.
