### ISSUE TITLE
Add reply-to option for form emails to prevent failed emails

### ISSUE THREAD

**Issue by trevorgehman** [statamic/v2-hub#817]
So, currently you can only specify the `from` and `to` fields when setting up form options. For contact forms, typically you want to just be able to reply to those emails.

What I've seen suggested is to change the `from` field to be: `from: "{{ email }}"`, but this is actually bad practice and will cause issues for certain domains, one common example being yahoo.com.

Due to the sender policy of yahoo.com, you'll likely run into delivery issues. For instance, Mailgun will refuse to deliver it:

> Unauthenticated email from yahoo.com is not accepted due to domain's 5.7.1 DMARC policy. Please contact administrator of yahoo.com domain if 5.7.1 this was a legitimate mail. Please visit 5.7.1 https://support.google.com/mail/answer/2451690 to learn about DMARC 5.7.1 initiative.

I've seen this issue countless times in other form implementations. The solution is simple: keep the `from` email address set to your domain, and just add a `reply-to` field with the user-submitted email address.

**Comment by trevorgehman** [comment]
Looks like this should be a very simple addition:

Just add this line to the `SendEmail` method of `Statamic\Addons\Forms\FormListener`:

    if ($reply_to = array_get($config, 'reply_to')) {
            $email->replyTo($reply_to);
        }

**Comment by thestepafter** [comment]
Thanks @trevorgehman. I'm hoping that they put this into the core because I would rather not hack the core files.

**Comment by trevorgehman** [comment]
@thestepafter Yes that is what needs to happen. Should be a simple addition, and IMO it belongs in the core. 

If I get word that this won't be added, then creating a custom addon should be simple enough.

**Comment by jasonvarga** [comment]
It will be.
