### ISSUE TITLE
FR: Tabs on entry forms

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/v2-hub#818]
While it's possible that you can group fields with a `section` field type - I'd love to see a `tab` fieldtype that separates content via JS tabs to reduce the length of the publish field. 

Most common case I have personally is where I have legacy content from another platform and while it's useful to have against the entry, I don't necessarily want it to be visible for newly published entries.

Having that in its own tab would make for a cleaner UX in my mind.

**Comment by lesaff** [comment]
Tabs would be nice indeed. I made a small addon to use `section` to create accordion navigation. I know it's not tabs but it somehow clean up the entry form a bit.
https://github.com/lesaff/statamic-sections

**Comment by andregoldstein** [comment]
Tabs would be great, would definitely make for an easier admin experience for things like SEO on each page.

Addon looks great Rudy @lesaff !

**Comment by lesaff** [comment]
Updated my addon to convert sections to tabs.

**Comment by jackmcdade** [comment]
Added in 2.9.0. 🤘
