### ISSUE TITLE
Cannot edit collection entries in IE 10

### ISSUE THREAD

**Issue by jswhetstone** [statamic/v2-hub#820]
### Steps to reproduce
1. Create a collection with entries in it
2. Open an entry for editing in the control panel using IE 10
### Expected behaviour

I should be able to view and edit all fields of my entry.
### Actual behaviour

Title and Slug fields are empty, as if creating a new entry.
### Server configuration

**Operating system**:
Linux
**Web server:**
Apache

**PHP version:**
5.6

**Statamic version:**
2.0.11

**Updated from an older Statamic or fresh install:**
Updated various times from 2.0.0 beta.

**Comment by jackmcdade** [comment]
I don't believe this is still an issue. Please reopen if you have evidence otherwise!
