### ISSUE TITLE
Feature Request: Ability to set the redactor textarea height in the CP

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#821]
I have a customer that is just using the content field and it is difficult to edit their long blog post in a redactor textarea that is so slim. Can we get a setting that allows us to increase the height of the textarea?

![slim-redactor-textarea](https://cloud.githubusercontent.com/assets/1793867/16973210/f24ce316-4dff-11e6-8dcf-818b485afef5.gif)

**Comment by stevieg83** [comment]
can configure that within the settings https://docs.statamic.com/reference/fieldtypes/redactor

**Comment by thestepafter** [comment]
I tried adding the following to the settings but it didn't change the height of the redactor field.

```
minHeight: 600
buttons:
  - formatting
  - bold
  - italic
  - alignment
  - unorderedlist
  - orderedlist
  - html
```
