### ISSUE TITLE
FR: ability to move assets to different folders in the CP

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/v2-hub#823]
Following discussion on Slack the other day around asset management, it would be great if a file or group of files could be selected in the control panel and then moved to another location within Assets.

**Comment by GMCz** [comment]
I assume this is on the roadmap... the sort of thing that having assets with unique ids enables.

**Comment by jasonvarga** [comment]
Absolutely. Similar to https://github.com/statamic/v2-hub/issues/699
