### ISSUE TITLE
Special character in slug causes reorder error

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#824]
### Steps to reproduce
1. Create an entry with a non-standard latin character ( ü in this case )
### Expected behaviour

Entry should be re-orderable.
### Actual behaviour

Entry has no reorder button, and content filename has odd (encoded?) elements and surrounded by quotes.

![slug-bug-special-character](https://cloud.githubusercontent.com/assets/3920126/17064855/98415abc-5036-11e6-833c-a8774b93ea04.png)
### Temp Workaround

Remove offending character from slug field.
### Server configuration

**Operating system**:
Working live on Linux server
**Web server:**
Apache
**PHP version:**
5.6
**Statamic version:**
2.0.11

**Comment by edalzell** [comment]
this still happen @wesort?

**Comment by wesort** [comment]
Nope, this seems fixed now. 

Perhaps the improvements to slugs (v 2.1.12 fix on #312) or (v2.5.4 "slug validation") helped this?

**Comment by edalzell** [comment]
Can you close it then?
