### ISSUE TITLE
Feature Request: Improved Replicator CP UX Ideas

### ISSUE THREAD

**Issue by humanjpg** [statamic/v2-hub#825]
**4 things**​ I think could take the current (very useful) replicator fieldtype to the next level and improve the UX in the CP. The solutions here are just suggestions to illustrate what I think is missing...
1. A ​**‘Collapse All’**​ button / link to minimise all of the open subfields within the replicator.
2. When you hover between the subfields, it would be cool if perhaps a line appeared between the fields, with a little dropdown tooltip on the right allowing you to add another field between the field. Or even an 'Insert Field' button in the middle.
3. It would also be good if the user could perhaps label each fieldtype, so that when you’re looking at a collapsed stack, you can see what each field contains.
4. Finally, it would be useful if you could change the fieldtype from a dropdown after the field had been added. Say if I have 20 subfields, and I want to change field number 3 from a _text_ field to an _image_ field for example (and I don’t care about losing the data within it), it would be great if I could just switch the fieldtype there.

Cheers

---
## Scamps

​Please _ignore the UI_ and the exact UX in these examples - I did them in 5 seconds just to help explain what I mean. Consider them super rough scamps.

**Field Labels** 
<img width="983" alt="field labels" src="https://cloud.githubusercontent.com/assets/9616783/17137932/bc53d16c-5335-11e6-8316-ff79851862f8.png">
(Obviously would be better if the content label was in a light grey so it was distinct from the actual field label.)

**Insert Field Example - State I**
![insert field a1](https://cloud.githubusercontent.com/assets/9616783/17137933/bc54c0f4-5335-11e6-8cd3-020d6c8270b8.png)

**Insert Field Example - State II**
![insert field a2](https://cloud.githubusercontent.com/assets/9616783/17137934/bc5dbf74-5335-11e6-92f8-9926fa3fe7ab.png)

**Comment by lukeagsmith** [comment]
I think all of these are good suggestions.

Each address something I have bumped into with long replicator fields.

For item 3, perhaps a field from the block could be specified in the YAML who's value would be appended to the label when collapsed.

**Comment by jackmcdade** [comment]
Partially implemented in `2.1.3` :)

**Comment by dannyuk1982** [comment]
all great ideas

**Comment by humanjpg** [comment]
@jackmcdade Just checked this out now. Thanks so much - finding **Collapse All** useful already!
