### ISSUE TITLE
Addon scripts.js included, but serves an error message

### ISSUE THREAD

**Issue by obventio56** [statamic/v2-hub#826]
### Steps to reproduce
1. Create addon with addon tool
2. Create scripts.js file under resources/assets/js
3. Access any of the addon's views
### Expected behaviour

The scripts.js file should be included.
### Actual behaviour

It is included but the server serves an error file instead of the script.
### Server configuration

**Operating system**:
Yosemite 10.10.5

**Web server:**
CLI

**PHP version:**
7.0.8

**Statamic version:**
2.0.11

**Updated from an older Statamic or fresh install:**
Fresh Install

**List of installed addons:**
Only the addon produced
#### Web server error log

``````
<br />
<b>Fatal error</b>:  Uncaught Illuminate\Contracts\Filesystem\FileNotFoundException: File does not exist at path /Users/heathermowers/Desktop/GatherContentAddon/site/addons/Jackal/resources/assets/ in /Users/heathermowers/Desktop/GatherContentAddon/statamic/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:40
Stack trace:
#0 /Users/heathermowers/Desktop/GatherContentAddon/statamic/core/Http/ResourceServer/Server.php(174): Illuminate\Filesystem\Filesystem-&gt;get('/Users/heatherm...')
#1 /Users/heathermowers/Desktop/GatherContentAddon/statamic/bootstrap/start.php(51): Statamic\Http\ResourceServer\Server-&gt;serve()
#2 /Users/heathermowers/Desktop/GatherContentAddon/index.php(138): require_once('/Users/heatherm...')
#3 /Users/heathermowers/Desktop/GatherContentAddon/statamic/server.php(21): require_once('/Users/heatherm...')
#4 {main}
  thrown in <b>/Users/heathermowers/Desktop/GatherContentAddon/statamic/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php</b> on line <b>40</b><br />```


#### Browser log
``````

js:

fieldtype.js:1 Uncaught SyntaxError: Unexpected token <
scripts.js:1 Uncaught SyntaxError: Unexpected token <

```
```

**Comment by jasonvarga** [comment]
PHP CLI server isn't supported properly. Have you tried something like Valet?

**Comment by Battleriskopoly** [comment]
Yes and it worked. Sorry!

**Comment by edalzell** [comment]
@Battleriskopoly can you please close this?

**Comment by edalzell** [comment]
@jasonvarga this can be closed.
