### ISSUE TITLE
Locale Switch Tag

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#831]
I'm confused how it's possible that this is not possible:
I just want to provide a **language navigation**, a very basic need on multi-lingual websites.

Like:
View this site in
- German
- Russian
- Klingon 

My [question in the lodge](https://lodge.statamic.com/questions/2381-languagelocales-navigation-or-switch) is still quite lonely. So I'm assuming I didn't miss anything.

My issue #759 is related, my question there also unanswered.

**Comment by jasonvarga** [comment]
There's no tag to do that. But nothing is stopping you from hardcoding the links.

```
<a href="http://de.mysite.com">German</a>
<a href="http://ru.mysite.com">Russian</a>
etc
```

**Comment by andypillip** [comment]
@jasonvarga yes, but those links suck.

When you switch language, you should stay on the page you're currently on.

That's established as a de-facto-standard, no? So I'd need the current page's URL for German. Is that possible?

For that, of course, it would need more logic – at least it needs to be possible to iterate or check for locales of the current page.

**Comment by jasonvarga** [comment]
Sure thing. You said "view this site in", not "view this page in".

Just saying it doesn't exist yet. Not saying it can't be created.

**Comment by jackmcdade** [comment]
This should be its own tag. Edited to the title for clarity.

**Comment by lesaff** [comment]
Shamelessly forked from Jason's
https://github.com/lesaff/Statamic-Language-Switcher

**Comment by jasonvarga** [comment]
That one is close but it probably doesn't take into account localized slugs and stuff. I can probably whip this together fairly quickly.

**Comment by mwesten** [comment]
This might do the trick ?:
https://github.com/mwesten/Statamic-Language-Switcher

**Comment by andypillip** [comment]
@mwesten perfect, thanks very much!

I'll test next week, I guess.

**Comment by jasonvarga** [comment]
This is doable now in 2.7 using the [locales tag](https://docs.statamic.com/tags/locales).
