### ISSUE TITLE
Markdown field inside replicator does not remove whitespace

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#832]
### Steps to reproduce
1. Add replicator field with a markdown set
2. Insert 2 spaces before content

![content bug](https://cloud.githubusercontent.com/assets/414211/17383634/d29acb7c-598b-11e6-9141-c6647c934357.gif)
### Expected behaviour

Whitespace should be removed to prevent indentation.
### Actual behaviour

Markdown content becomes indented, causing a yaml parse error.

**Comment by edalzell** [comment]
@mikemartin I'm trying to reproduce, does this still happen?

**Comment by mikemartin** [comment]
@edalzell This appears to be fixed since 2.1.19. Thanks for checking.
