### ISSUE TITLE
FR: Adding pagination to collection entries

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#833]
Currently, collection entries display all records without any pagination. It would be nice if this can be added to the settings and set number of records per page and display the pagination.

**Comment by chris-79** [comment]
In a couple collections of ours, we have _so. many. entries._ Would **love** to have this feature!

**Comment by humanjpg** [comment]
Any ETA on this? 

I have 160+ entries in one of my collections and the CP page is now taking > 15 seconds to load ☹️

**Comment by jasonvarga** [comment]
It's in 2.2
