### ISSUE TITLE
Long title is not truncated properly, breaking the viewport

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#837]
### Steps to reproduce
1. Create a collection/page entry with a really long title
2. save and edit the page/entry

### Expected behaviour
Title at the top of the entry page should be truncated and suffixed with ellipsis

### Actual behaviour
Long title displayed and adding horizontal scrollbar to the page

### Server configuration
**Operating system**: El Capitan [latest]

**Web server:** Valet 1.1.12

**PHP version:** 7.0.8

**Statamic version:** 2.1.1

**Updated from an older Statamic or fresh install:** Update

**Browser & version:** Chrome 52.x

![long-title](https://cloud.githubusercontent.com/assets/1151181/17438986/1aae3252-5afc-11e6-8d1c-8184aa422818.gif)

**Comment by jackmcdade** [comment]
Make the title shorter. 🙃
