### ISSUE TITLE
Pages fieldset not saved when publishing a new page

### ISSUE THREAD

**Issue by CreateSean** [statamic/v2-hub#839]
### Steps to reproduce
1. publish a page
   ![capture1](https://cloud.githubusercontent.com/assets/6899490/17447049/5ecb04f6-5b1a-11e6-8202-1021b655d93e.JPG)
   ![capture2](https://cloud.githubusercontent.com/assets/6899490/17447053/66f34a8a-5b1a-11e6-8320-595d5d5bd1b5.JPG)
2. edit page - fieldset is incorrect
   ![capture3](https://cloud.githubusercontent.com/assets/6899490/17447059/6d0f155c-5b1a-11e6-996f-acdbcc337e50.JPG)
3. check index.md does not include fieldset 
   title: test again
   id: d3c229bd-4cda-4b64-939a-11c23a86e95c

Adding fieldset manually works, but not good for the client
### Expected behaviour

When creating a new page the fieldset should be saved along with the new page
### Actual behaviour

The fieldset is not saved
### Server configuration

**Operating system**:
windows 10

**Web server:**
ampps

**PHP version:**
5.5

**Statamic version:**
2.1.2
**Updated from an older Statamic or fresh install:**
updated from 2.0.11
**List of installed addons:**
None
#### Web server error log

```
Insert your webserver log here
```
#### Statamic error log (`/local/storage/logs/statamic.log`)

```
Insert Statamic log here
[statamic-2016-08-05.zip](https://github.com/statamic/v2-hub/files/404391/statamic-2016-08-05.zip)


```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by jackmcdade** [comment]
Is this still an issue for you Sean? I can't say I've seen this kind of behavior ever, especially not recently. Please reopen if so!

**Comment by andypillip** [comment]
I'm seeing that behaviour in v1 actually: https://lodge.statamic.com/questions/2701-fieldset-not-saved-to-page-md-v1#reply-1

If this issue somehow still exists, it's probably from v1.

**Comment by maxfahl** [comment]
I've got this problem myself. Though I was doing something wrong.

**Comment by jasonvarga** [comment]
@maxfahl In v1 or v2?

**Comment by maxfahl** [comment]
Sorry for the late answer @jasonvarga. I'm currently using version 2.6.9.
