### ISSUE TITLE
theme tag inside glide tag treats it as an external url

### ISSUE THREAD

**Issue by jasonvarga** [statamic/v2-hub#841]

**Comment by GMCz** [comment]
**Given this:**
'{{ glide width="300" height="300" crop="focal" fit="crop" }}{{theme:img src="Web-6.jpg"}}{{ /glide }}'

**You get:**
`src="/img/http/aHR0cDovLzQxd2VzdC5kZXYvdGhlbWVzL21haW4vaW1nL1dlYi0xMy5qcGc=?w=800&h=600&crop=focal&fit=crop&s=03aa5af4272a8691f1391dc053c049c9"`

---

**@jasonvarga's temp solution:**
in `statamic/bundles/Theme/ThemeTags.php` on line 202, change:

`return $url;` to `return URL::makeRelative($url);`

---

After restarting valet (`valet restart`) and clearing the cache (`php please clear:cache`) everything was back to normal for me! 👍🏼

**Comment by edalzell** [comment]
@gmcz looking at the code I think this has been fixed, right? If so, can you please close?

**Comment by gmcz** [comment]
Yes, this was fixed back in 2.5.x-something-or-other! @jasonvarga, you can close this!
