### ISSUE TITLE
CP treats the number zero as a falsey value and doesn't write it to file.

### ISSUE THREAD

**Issue by jasonvarga** [statamic/v2-hub#845]
cc @alexroper

https://lodge.statamic.com/questions/2440-how-can-i-save-a-text-value-of-zero-0

**Comment by jasonvarga** [comment]
cc @alexroper

**Comment by thomasgerard** [comment]
Hello,
The bug is still present as of v2.5.5

**Comment by jackmcdade** [comment]
Unfortunately that's how YAML works. The best workaround is to not use the number `0` or `1` explicitly as data. What's your use case? Maybe we can help you find a solid solution?

**Comment by alexroper** [comment]
Use case is listing the number of bedrooms for an apartment floor plan. Studio apartment = 0 bedrooms. Is there no way to store zero with quotes around it?

**Comment by edalzell** [comment]
This is solvable @jackmcdade/@jasonvarga if there was an `Integer` fieldtype. Just put `return $data ? $data : "0";` in the `preProcess` method of the `IntegerFieldtype.php`?

Or an `integer` tag that changes a null to 0?

**Comment by jasonvarga** [comment]
Fixed for next release.
