### ISSUE TITLE
Users field data not showing up in CP

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#847]
### Steps to reproduce
1. have a relate field in your data. (Author, in my case)
2. Set it in the CP (works properly)
3. Reload the entry w/ the relate field

### Expected behaviour
See the proper data

### Actual behaviour
Don't see the data

This is 2.1.2.

![oregon coast statamic 2016-08-09 16-35-43](https://cloud.githubusercontent.com/assets/6069653/17532959/dcfb79bc-5e50-11e6-91b1-c80228e3c890.png)

YAML:
```
---
title: Oregon Coast
author:
  - 950f647a-7fff-49f9-9904-87be70619d26
categories:
  - 4f6cebe6-8038-42fe-be1b-2f40d8bf4f89
id: 7a152137-fc7d-4c50-988f-5eb82bc2f4f1
---
```

**Comment by jasonvarga** [comment]
It's a users field issue.

**Comment by edalzell** [comment]
I don't see this anymore.
