### ISSUE TITLE
cp large collection -- significant delay loading

### ISSUE THREAD

**Issue by igregson** [statamic/v2-hub#848]
In the control panel, when clicking on a large collection (in this case ~150 blog posts), there's a significant delay before all the entries load. Feels like a UX bug. A "fix" may be as simple as adding a loading indicator.

**Comment by jasonvarga** [comment]
👍

**Comment by sheldonkotyk** [comment]
I have 1610 entries in a collection (so far). It takes about 5 seconds to load on my local. A little longer on a web server. I'm hoping for pagination with sorting ability or something similar (50 entries a page maybe?)

On a different site that I'm getting ready to build we have about 8000 entries in a single collection.

**Comment by jackmcdade** [comment]
@sheldonkotyk I have a feeling 8,000 is larger than is appropriate for a Flat File CMS.

**Comment by edalzell** [comment]
dupe of #917?

**Comment by sheldonkotyk** [comment]
@edalzell technically yours is the dupe. ;)

**Comment by jasonvarga** [comment]
Pagination was added in 2.5 which helps. In 2.5.2 we added a loading graphic 😊

**Comment by sheldonkotyk** [comment]
Yay for loading graphics! 2.5.1 did help a massive amount. Thanks.
