### ISSUE TITLE
Asset conditional not working

### ISSUE THREAD

**Issue by stevieg83** [statamic/v2-hub#850]
If I wrap a conditional around my asset, the conditional fails.

The image exists if I remove the conditional.

```
{{ if asset:meta_image }}
{{ asset:meta_image }}
  <meta property="og:image" content="http://domain.com{{ glide:url }}" />
{{ /asset:meta_image }}
{{ /if }}
```

**Comment by GMCz** [comment]
Why are you trying to wrap `{{ asset:meta_image }}` in a conditional? If there's no `meta_image` Statamic shouldn't render anything between your `{{ asset }}` tag pair.

**Comment by jasonvarga** [comment]
The condition should just be `{{ if meta_image }}`.

The `{{ asset:` indicates you're using the Asset Tag, which takes the ID and converts it into asset data. In the conditional, simply checking that the field exists is all you need.
