### ISSUE TITLE
Create new taxonomy entry is broken

### ISSUE THREAD

**Issue by fredrik-sogaard** [statamic/v2-hub#851]
### Steps to reproduce
1. Create new taxonomy
2. Go to newly created taxonomy
3. Click Create ...
4. "Whoops, looks like something went wrong."

### Expected behaviour
Should create a new entry in that taxonomy

### Actual behaviour
Throws error.
See short screencast here: https://cl.ly/0W063g2W1z2t
See error message here: https://cl.ly/3O2E0C3b0900

### Server configuration
**Operating system**: Mac OS X

**Web server:** Apache

**PHP version:** 7

**Statamic version:** 2.1.2
 
**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** None

**Comment by sheldonkotyk** [comment]
Note that this occurs in the 'tags' taxonomy in the CP panel with the demo.

**Comment by danieljwestman** [comment]
Very frustrating!

**Comment by sheldonkotyk** [comment]
![pasted image at 2016_08_09 01_08 pm](https://cloud.githubusercontent.com/assets/622598/17860089/05e36f98-6841-11e6-8975-4a720a1e4459.png)

Temp fix while we wait for 2.1.3
