### ISSUE TITLE
FR: Option to auto-sort/file date entries into year subfolders

### ISSUE THREAD

**Issue by chris-79** [statamic/v2-hub#853]
As I commented in #833, we have a couple collections that have _so. many. entries._ I'd **love** to have them auto-sorted/filed into year subfolders like:

```
events
├─ 2014
│  ├─ 2014-08-06-1600.new-website.md
│  ├─ 2014-08-18-0800.fall-semester-classes-begin.md
│  ├─ ...
│  └─ 2014-12-25-1123.christmas-2014.md
├─ 2015
│  ├─ 2015-01-01-1125.new-years-2014.md
│  ├─ 2015-01-07-0900.coffee-and-conversation-with-coe-student-ambassadors.md
│  ├─ ...
│  └─ 2015-12-25-0800.winter-break-2015.md
├─ 2016
│  ├─ 2016-01-01-0800.new-years-2015.md
│  ├─ 2016-01-11-0800.classes-begin-spring-2016.md
│  ├─ ...
│  └─ _2016-09-09-1300.olli-bash-an-activity-fair.md
└─ folder.yaml
```

I'm currently doing this by hand with a shell script, but as of v2.1.2, I'm getting errors like:

> DuplicateIdException in AbstractDriver.php line 211:
> 
> Cannot add [collections/events/2016-09-08-0830.progress-monitoring-for-ieps-fall-2016.md] to Stache repository [entries]. File at [collections/events/2016/2016-09-08-0830.progress-monitoring-for-ieps-fall-2016.md] already exists in repository [entries/events] with an ID of [e5492811-5974-4b39-9c35-7cd021ec667e].

**Comment by jasonvarga** [comment]
Collections can't have subfolders in v2, that's why you're getting errors.

**Comment by jasonvarga** [comment]
Also, why do you need them in folders? What's that solving?

**Comment by chris-79** [comment]
Scratching an OCD itch, mostly lol 😄  I love tidiness.

One collection has (at the moment) 429 files and the other has 674. The CP pagination is probably more important

**Comment by humanjpg** [comment]
Dayum - I have a collection with 167 entries... How is your CP even loading?

**Comment by jackmcdade** [comment]
At this point we won't be making architecture changes this large in v2. Closing it down!
