### ISSUE TITLE
Fieldset with no custom fields empties title value on blur

### ISSUE THREAD

**Issue by andregoldstein** [statamic/v2-hub#854]
### Steps to reproduce
1. Create new fieldset
2. Add no custom fields (use case is creating entries with just titles)
3. Add a new entry
4. Type a title
5. Go to save page
### Expected behaviour

The page should save
### Actual behaviour

The title field gets emptied (seemingly on blur)
### Server configuration

**Operating system**: Mac OS

**Web server:** MAMP

**PHP version:** 5.6?

**Statamic version:** 2.1.2

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** None
#### Web server error log

```
Insert your webserver log here
```
#### Statamic error log (`/local/storage/logs/statamic.log`)

```
Insert Statamic log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by jackmcdade** [comment]
As long as your fieldset is an array, this works now.

`fields: []`
