### ISSUE TITLE
Glide tag + `square` doesn't work

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#856]
### Steps to reproduce
1. Use a `glide` tag w/ `square="200"`
2. Load a page that displays that image

### Expected behaviour
Image should be square

### Actual behaviour
It ain't square

**Comment by jasonvarga** [comment]
Either set `auto_crop: true` in `site/settings/assets.yaml` (or just remove it, since the default is `true)`, or add a `fit=""` parameter to the glide tag.
