### ISSUE TITLE
Basic tag pair doesn't work for taxonomies in 2.1.2 but does in 2.0.11

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#858]
Basic tag pair for listing taxonomies isn't working on 2.1.2, but the same code does work for 2.0.11.

```
{{ taxonomy:categories }}
    {{ id }}
{{ /taxonomy:categories }}
```

**Comment by jasonvarga** [comment]
Please provide some more details.

What is and isn't working?
Do you have a taxonomy exactly named `categories`? ie. `site/content/taxonomies/categories/`?
Do any entries use this taxonomy?

**Comment by thestepafter** [comment]
Yes, we have a taxonomy named categories. When we try to reference the taxonomy using the code above no results are returned. There are no errors in the log either. We have some collections using this taxonomy.

**Comment by PhilippeGauthier** [comment]
Probably related to this? https://github.com/statamic/v2-hub/issues/844

**Comment by thestepafter** [comment]
Probably, we are looking to do what you are doing once we get this issue figured out.

**Comment by thestepafter** [comment]
This was solved by changing the field set field name to match that of the taxonomies slug.

**Comment by danielfowler** [comment]
@thestepafter can you elaborate on "field set field name"? Is that the label in the entry's fieldset? The title of the fieldset? The fieldset filename? Or something else?

My taxonomy subfolder is `event_type`, the title in the folder.yaml is `Event Type` and I don't have a fieldset defined for this taxonomy.

**Comment by thestepafter** [comment]
@danielfowler What I did is mentioned in the taxonomy docs, although not very clearly.

https://docs.statamic.com/guides/taxonomies

Look for this line:

If you are trying to associate those terms with your content, you should make sure the field name is the same as the name of the taxonomy. 

This means that the field name in the field set that you use to relate the taxonomy to a piece of content needs to match the taxonomy subfolder name.

**Comment by danielfowler** [comment]
So `{{ taxonomy:event_type }}` isn't listing all the event types available in the taxonomy, it's only iterating through the event_type field values for a particular page? That doesn't seem right.

Shouldn't `{{ taxonomy:things }}` work like `{{ collection:other_things }}` and iterate through all available values in that taxonomy source?

**Comment by jasonvarga** [comment]
Think back to v1. A taxonomy listing only lists things that you put in entries. Add a new term to an entry, it appears in the listing.

In v2, you can create the term, but it will only show up in a listing once you use it within an entry.

Unless you add `show="all"` to the taxonomy tag. In that case, it'll loop through them all, regardless of whether they've been used in an entry.

The point @thestepafter was making was that in order to "use" a taxonomy term in an entry, the field name in the entry needs to be the same as the taxonomy itself, like this:

```
---
title: My Entry
event_type: id_of_an_event_type
---
```

This assumes that the taxonomy is named `event_type` (ie. `site/content/taxonomies/event_type`)

**Comment by danielfowler** [comment]
So `{{ taxonomy:event_type show="all" }}` would operate the way I'm expecting, showing a dozen values even if my current entry is tagged with two?

**Comment by jasonvarga** [comment]
Adding `show="all"` will make loop through all the taxonomy terms in the folder. Correct.
