### ISSUE TITLE
SectionFieldtype needs to be translatable or at least be shown in localized content editor

### ISSUE THREAD

**Issue by mwesten** [statamic/v2-hub#859]
### Steps to reproduce
1. Add multiple sections to a fieldset that contains localizable items
2. edit the page/entry in the localized version
### Expected behaviour

You should see the Section headers appear on localized edit-pages too, if there are fields that belong to that section that are translatable.
**Default language:**
![image](https://cloud.githubusercontent.com/assets/66753/17698314/bef2bd4e-63ba-11e6-9d70-2ccdf574a46e.png)
### Actual behaviour

All fields that are translatable are shown without the Section-header.
**Localized content:**
![image](https://cloud.githubusercontent.com/assets/66753/17698335/e363d1b8-63ba-11e6-9fe4-ce36fd5440e3.png)
### Solution:

Quickfix: in `statamic\bundles\Section\SectionFieldtype.php` set the returnvalue of `canBeLocalized()` to `true`.

Better option:
Change the display code of the localized content page editor to always show sections if translatable fields below them are present....
### Server configuration

**Operating system**:  OSX 10.11.6

**Web server:** Apache 2.4.18

**PHP version:** 7.0.4

**Statamic version:** 2.1.2

**Updated from an older Statamic or fresh install:** Fresh install

**List of installed addons:** none

**Comment by jasonvarga** [comment]
Since 2.9, all fields are displayed, regardless of whether they are localizable.
