### ISSUE TITLE
Styling issue with localisation button in cp 

### ISSUE THREAD

**Issue by mwesten** [statamic/v2-hub#860]
### Steps to reproduce
1. enable multiple locales
2. edit a page that contains translatable content
   3.on the localised page, the button breaks trough the right-side border
### Expected behaviour

Button fits in pane as in default language
**Default language:**
![local_button_1](https://cloud.githubusercontent.com/assets/66753/17699129/52b26008-63bf-11e6-8dec-c598bbfaa14b.png)
### Actual behaviour

Button sticks over the pane
![local_button_2](https://cloud.githubusercontent.com/assets/66753/17699133/5a56abde-63bf-11e6-8b15-72d4267490c6.png)
### Server configuration

**Operating system**:  OSX 10.11.6

**Web server:** Apache 2.4.18

**PHP version:** 7.0.4

**Statamic version:** 2.1.2

**Updated from an older Statamic or fresh install:** Fresh install

**List of installed addons:** none

**Comment by jackmcdade** [comment]
Has been fixified!
