### ISSUE TITLE
Table rendering

### ISSUE THREAD

**Issue by TheOldDesigner** [statamic/v2-hub#861]
### Steps to reproduce

Add 2 instances of the short tag  to display a table (2 different tables) to the same page
### Expected behaviour

Both should output a table each with distinct data
### Actual behaviour

The first tag works correctly the second fails to render
### Server configuration

**CentOS Linux 6.5**:

**Web server:**
Apache

**PHP version:**
5.6.10

**Statamic version:**
2.12

**Updated from an older Statamic or fresh install:**
Fresh

**List of installed addons:**
None
#### Web server error log

```
Insert your webserver log here
```
#### Statamic error log (`/local/storage/logs/statamic.log`)

```
Insert Statamic log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by jackmcdade** [comment]
Do you have a code example for this?

**Comment by TheOldDesigner** [comment]
hi Jack, not any more this was an old issue, it may well Have righted itself In upgrades, I will see if I can reproduce over weekend when playing with 2.5 version.

--  
 Richard (The Old Designer)
 +44(0)1904 630622
 Me@TheOldDesigner.co.uk
___

**Comment by jackmcdade** [comment]
Alrighty, I'll close it for now, but feel free to reopen if it's something you hit again!
