### ISSUE TITLE
When an oauth user's email matches an already existent user it should not create a new user. 

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/v2-hub#863]
### Steps to reproduce
1. Create a new user through the CP or with regular registration.
2. Login using oauth with same email address.
3. Voila, 2 users.
### Expected behaviour

User information should "merge"
### Actual behaviour

Two users are created
### Server configuration

**Operating system**:
Mac OSX using Valet

**Statamic version:**
2.1.2

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**
OAuth (with Google)

**Comment by lesaff** [comment]
I agree. Either merge or send a notification back to the login screen to tell user that:

- email address already exists
- do you want to merge or cancel?

**Comment by sheldonkotyk** [comment]
I'd prefer to just auto merge. Can't think of a time someone would want to cancel. What's your thinking on the user wanting to cancel Rudy?

**Comment by jasonvarga** [comment]
This will need some thought.

Let's say I have an account. I change my email to sheldon@kotyk.com because I'm a jerk.

Now, when _you_ authenticate with oauth, what happens?

**Comment by sheldonkotyk** [comment]
well, I would then own your statamic account, which is what you get for being a jerk.

**Comment by jasonvarga** [comment]
No, I'd have yours. Or. Something. Kind of a weird thing. It'll take a little brainpower.

**Comment by jasonvarga** [comment]
Or what about if you changed your email on your github account to my email address before you oauth'ed. Then you authenticate. Then you get my account?

**Comment by sheldonkotyk** [comment]
Doesn't github require a confirmation that you own an email address before you can use them for OAuth?

**Comment by jasonvarga** [comment]
Maybe Github does but that doesn't mean others will.

**Comment by danieljwestman** [comment]
+1

**Comment by Nevcairiel** [comment]
You can implement this yourself today already by creating a Listener in an addon and return the existing user from the "Statamic\Events\OAuth\FindingUser" event.

**Comment by christopherburton** [comment]
Shouldn't an ID be the unique identifier here?

**Thoughts:**
+ Change email to test@test.com on Twitter
+ Login to site.com via Twitter oauth
+ site.com checks for existing user_id against user_id from Twitter
+ Since email is different, site.com updates user's email

**Comment by jasonvarga** [comment]
Closing this in favor of [the solution suggested by @Nevcairiel](https://github.com/statamic/v2-hub/issues/863#issuecomment-281973951)
