### ISSUE TITLE
"Update Available" appearing when at latest version (2.1.4)

### ISSUE THREAD

**Issue by danielfowler** [statamic/v2-hub#864]
In CP of 2.1.2, most recent version, the "Update Available" text still appears by the Statamic logo in top left.

**Comment by jackmcdade** [comment]
How about with 2.1.3?

**Comment by danielfowler** [comment]
'tis gone!

**Comment by jackmcdade** [comment]
Still?

**Comment by danielfowler** [comment]
Ummm, I don't have a site running the latest version at the moment.

**Comment by jackmcdade** [comment]
No worries! I saw the same issue the last few versions, and no more for me. If you see it again (>= 2.1.12) feel free to reopen!
