### ISSUE TITLE
Links to add/edit collection from pages broken if collection starts with uppercase character

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#866]
### Steps to reproduce
1. Create a collection named i.e. News, Blog (anything starting with an uppercase)
2. Mount to a page
3. Try and edit/add from the _Pages_ page in the CP 
### Expected behaviour

It should go to the relevant edit/add section of that collection
### Actual behaviour

An "Access denied" error appears, likely because the URL generated is converted to lowercase, i.e. the add link will be: /cp/collections/entries/news/create when it should be /cp/collections/entries/News/create
The links to add/edit from the collections section do not make the URL lowercase, and so work as expected

**Comment by jackmcdade** [comment]
Collections should always be lowercase.

**Comment by jasonvarga** [comment]
(We should validate for that, then)

**Comment by jackmcdade** [comment]
This issue is a bit stale so we're closing it for now. If it rears its head again, please feel free to reopen and ping us!
