### ISSUE TITLE
FR: Hide form submissions in CP and/or prevent saving data

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#867]
## Common use case

A lot of contact forms don't need to save submissions to files. They just need to send the email and be done with it. The contact form submissions in the CP are just clutter, potentially distracting from other useful info.
## My current use case

I'm experimenting with using the core Form bundle to handle submissions for addons. It means I don't have to duplicate the Tags and Listener functionality. It's mostly working well.

I can put whatever fields in the formset I want so that it saves data if I want it to, or just throw in a dummy field and not put it in the actual form.

I can use a formset to hold form-specific addon config, which will be really handy in the future for some Stripe stuff.

The only "issues" I'm running into are:
- It's saving empty files in `storage/forms` since I'm making sure to remove all fields scoped to my addon (payment details) and there are no fields to save.
- The submissions (or lack of) are visible in the CP.
## Request

It'd be nice to be able to add something like `hide: true` and/or `submission_save_to_file: false` to formsets like with Raven in v1.

**Comment by jackmcdade** [comment]
You can do this now.
![image](https://user-images.githubusercontent.com/44739/41050970-d71c9816-6982-11e8-98e4-cc019a367104.png)
