### ISSUE TITLE
Bug:  Adding taxonomy term shows duplicate

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#868]
### Steps to reproduce
1. Install Statamic v2.1.2
2. Run `php please clear:site`
3. Create taxonomy
4. Add taxonomy term

![taxonomies](https://cloud.githubusercontent.com/assets/414211/17779890/2e585e14-651e-11e6-9161-6d4297f02f56.gif)

### Actual behaviour
Two taxonomy terms appear. You can then clear the cache to remove it.

### Server configuration
**Operating system**:
mac

**Web server:**
valet

**PHP version:**

**Statamic version:**
2.1.2

**Updated from an older Statamic or fresh install:**
Fresh install 

**List of installed addons:**
none

#### Web server error log
```
Insert your webserver log here
```

#### Statamic error log (`/local/storage/logs/statamic.log`)
```
Insert Statamic log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by dannyuk1982** [comment]
I get the same running Apache 2.2.29 and PHP 5.5.26
