### ISSUE TITLE
Takes over a minute to save an entry

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#870]
### Steps to reproduce
1. save an entry

### Expected behaviour
It should save in only a few seconds

### Actual behaviour
Takes over a minute (I stopped counting) to save.

### Server configuration
Dreamhost

**Statamic version:**
2.1.2

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**
![addons statamic 2016-08-21 17-38-25](https://cloud.githubusercontent.com/assets/6069653/17840891/1b5abd70-67c6-11e6-8835-d20515175e58.png)

**Comment by edalzell** [comment]
also slow saving a new taxonomy.

**Comment by edalzell** [comment]
fascinating, re-saving the same post (and publishing) was fast.

**Comment by jackmcdade** [comment]
What about without addons?

**Comment by jasonvarga** [comment]
You only just started noticing this? Did it only start happening after you updated? The entry you saved, how big is the collection it belongs to?

**Comment by edalzell** [comment]
@jasonvarga it started w/ 2.1. The collection is large, 200+ entries I believe.

@jackmcdade I'll try later tonight.

**Comment by jackmcdade** [comment]
How about with 2.1.3?

**Comment by edalzell** [comment]
Still there. It's because the search index is being updated. Related to #887 .

@jasonvarga says each entry is calling Algolia instead of just the edited one.
