### ISSUE TITLE
Nav filter on fieldset doesn't work in non-basic-locales (bug, localization)

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#874]
### Steps to reproduce
1. Create multilingual website according to the guide (en, fr)
2. Create a page with fieldset _foo_
3. Exclude pages with that fieldset from your nav: `{{ nav from="/" fieldset:isnt="foo" }}`
3. Visit your site in French

### Expected behaviour
The navigation should exclude the foo-page.

### Actual behaviour
It's listing the foo-page.

### Server configuration
**Operating system**: F24

**Web server:** PHP -S

**PHP version:** 5.6.24

**Statamic version:** 2.1.2

**Updated from an older Statamic or fresh install:** Mixture

**List of installed addons:** None

**Comment by jackmcdade** [comment]
By `fieldset` do you mean the actual fieldset mapping, the system field?

**Comment by andypillip** [comment]
@jackmcdade jap.

**Comment by andypillip** [comment]
Thanks, guys.
