### ISSUE TITLE
Related fields show ID instead of title in custom collection’s table columns

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#875]
### Steps to reproduce
1. Add a related fieldset to a collection (pages or other collection)
2. Add field to `folder.yaml` under `columns`
### Expected behaviour

Show the title of the related field
### Actual behaviour

Shows the related field's ID

<img width="1013" alt="screen shot 2016-08-23 at 18 47 41" src="https://cloud.githubusercontent.com/assets/5065331/17901469/d05c780a-6963-11e6-8c03-2ca1a15cec9f.png">

**Comment by jackmcdade** [comment]
We don't support related fields the columns customization, just strings at this time.

**Comment by jasonvarga** [comment]
Feature request?

**Comment by jackmcdade** [comment]
I was gonna remove the feature entirely but fine ;)

**Comment by aryehdesigns** [comment]
Ah ok, fair enough. Would be a handy feature 😊

**Comment by jackmcdade** [comment]
I agree! It's a tad complicated though :)
