### ISSUE TITLE
style bug: system page of cp, windows, firefox, >1399px wide

### ISSUE THREAD

**Issue by beckysoll** [statamic/v2-hub#876]
### Steps to reproduce
1. login to CP
2. navigate to configure > settings

### Bug
When viewing the configure > system page in the cp, on windows in firefox (chrome is fine), at a browser width greater than 1399px, the page is unreadable.

### Server configuration
**Operating system**:
Windows 7
**Web server:**
WAMP
**PHP version:**
5.6.19
**Statamic version:**
2.1.2
**Updated from an older Statamic or fresh install:**
freshie
**List of installed addons:**
none, just installed statamic, haven't updated anything other than 1 user

![system-cp-ff-bug](https://cloud.githubusercontent.com/assets/5340428/17904907/2cdcc0be-693f-11e6-863e-386247a91a97.png)

**Comment by jackmcdade** [comment]
Fixed for 2.1.3
