### ISSUE TITLE
Timeout after first load after a cache clear

### ISSUE THREAD

**Issue by tyvdh** [statamic/v2-hub#877]
### Steps to reproduce
1. Clear cache
2. Load page
3. Rage quit
### Expected behaviour

Page should load quickly like it has in the past. This is a new issue. Something between 2.0.11 and 2.1.0
### Actual behaviour

Page times out on initial load after a cache clear. Like it's looking for a folder that doesn't exist until after it runs once.
### Server configuration

**Operating system**:

**Web server:**
Nginx

**PHP version:**
PHP 7.0.9-1+deb.sury.org~xenial+1 (cli) ( NTS )

**Statamic version:**
2.1.0

**Updated from an older Statamic or fresh install:**
2.0.11
#### Web server error log

```
Insert your webserver log here
```
#### Statamic error log (`/local/storage/logs/statamic.log`)

http://tyler.link/hE1q
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by jackmcdade** [comment]
Can you try with 2.1.3? We made a bunch of performance improvements (some of which were from regressions introduced in 2.1.0).

**Comment by tyvdh** [comment]
@jackmcdade Nope. Still there. Dies on the first reload after an application cache clear.

**Comment by jasonvarga** [comment]
Do you get an error or a whitescreen or what?

**Comment by tyvdh** [comment]
<img width="991" alt="screen shot 2016-08-25 at 3 11 37 pm" src="https://cloud.githubusercontent.com/assets/4383610/17982545/3d481528-6ad6-11e6-9ee8-065e3137e560.png">

**Comment by jasonvarga** [comment]
Turn on debug mode to see the stack trace, or just look at your logs for what the error was.

```
Statamic error log (/local/storage/logs/statamic.log)

Insert Statamic log here
```

Unfortunately the log you provided us was not helpful. :)

**Comment by tyvdh** [comment]
@jasonvarga Updated. Sorry. 
http://tyler.link/hE1q

**Comment by tyvdh** [comment]
Looking into it a bit more it looks like it has something to do with S3 images that have a reference on Statamic but are no longer in the bucket.

Tried syncing assets and now the site is totally botched.

**Comment by jasonvarga** [comment]
Why was the image removed from the bucket? Was it manually removed?

**Comment by tyvdh** [comment]
Yeah that's very likely.

**Comment by jasonvarga** [comment]
Also, to clear it up, syncing assets will find any assets that don't exist in your meta files (the stuff in the site/storage/assets/*/folder.yaml files) and add them.

So if you clear the asset references and re-sync, they will get new IDs assigned. Any references in your content will be incorrect.

**Comment by tyvdh** [comment]
Sounds like what we need then is to disconnect or ignore non existent files. Again this is a new bug. I haven't changed anything file wise between 2.0.11 and 2.1.3. 

On Thu, Aug 25, 2016 at 5:05 PM Jason Varga

<
mailto:Jason Varga <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Also, to clear it up, syncing assets will find any assets that don't exist in your meta files (the stuff in the site/storage/assets/*/folder.yaml files) and add them.

So if you clear the asset references and re-sync, they will get new IDs assigned. Any references in your content will be incorrect.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/statamic/v2-hub/issues/877#issuecomment-242540331
, or

**Comment by jackmcdade** [comment]
Is this still an issue?

**Comment by tyvdh** [comment]
Don't think so.
