### ISSUE TITLE
Can't have all languages with a prefix in the url

### ISSUE THREAD

**Issue by smcyr** [statamic/v2-hub#879]
If I have two languages, English and French for example, and I put theses two urls in the config:
http://statamic.dev/en/
http://statamic.dev/fr/
with both a "en" and "fr" folder (with index.php and htaccess) in the website root folder.

Then, in the CP, I click on a page other than "Home" to edit it and it shows this message:
"No page found."

I'm on Windows 10 / IIS.

Thanks!

**Comment by jasonvarga** [comment]
What are you intending to have at http://statamic.dev/?

**Comment by smcyr** [comment]
I would like to redirect the user based on a mix of the browser language for first time (or default language if the browser language isn't in the available languages) and cookie after that.

**Comment by peimn** [comment]
I also want to use the main address as an intro which users select languages.

![screenshot_5](https://cloud.githubusercontent.com/assets/5695187/17998637/ade891b8-6b8a-11e6-9cb6-2ae794f10d20.png)

**Comment by zenboy4ever** [comment]
I had a similar issue. I used a redirect for domain.com/en/ to domain.com to allow me to use {{ locale }} in links (ie: /{{ locale }}/{{ segment_1 }}).

Hope that helps as a temporary workaround

**Comment by smcyr** [comment]
@jackmcdade hi, was it fixed?
