### ISSUE TITLE
Empty replicator field hidden by section field

### ISSUE THREAD

**Issue by gmcz** [statamic/v2-hub#881]
### Steps to reproduce
1. Create a replicator field
2. Place a section filed under it
3. Open the control panel to a page using the fieldset
### Expected behavior

Replicator field should be visible.
![](http://link.colker.net/1a6iJ+)
### Actual behavior

Replicator field is not visible, section appears to overlap the area.
![](http://link.colker.net/1fSw5+)
### Server configuration

**Operating system**: Mac OS X

**Web server:** Valet

**PHP version:** 7

**Statamic version:** 2.1.2

**Updated from an older Statamic or fresh install:** Updated.

**List of installed addons:** None.
### Relevant Files

about.yaml, and search_and_social.yaml: https://gist.github.com/GMCz/91fc732d6dba4b77fd698b41f7318819

---

**Edit:** I had put the wrong version number, this is happening on 2.1.2

**Comment by jackmcdade** [comment]
I can't recreate this. Can you confirm with 2.1.2?

**Comment by GMCz** [comment]
Yep... 2.1.2.

![(http://link.colker.net/11efQ+)

Do you want me to see if I can give you access to the site itself?

**Comment by jackmcdade** [comment]
I straight up can't recreate this in any browser. Also, your Asset fieldtype looks wrong.. actually a lot of stuff looks wrong. The Title block should be it's own card style. Can you clear your browser cache or something? I have no idea what's happening.

**Comment by GMCz** [comment]
Hm. 🤔 It's happening across Safari and Chrome for several folks on this particular project. I may have copied the partial over from a v1 site initially so I'll double check the fieldsets and report back.

**Comment by GMCz** [comment]
Yeah, I don't know what's going on. Cleared cache, nothing. Disabled cache, nothing. Open in other browsers (Google Chrome Canary, Safari Technology Preview) and still see it. I did discover that it doesn't happen when the browser window is narrow enough that you switch to single-column:

![](http://link.colker.net/108QH+)

**Comment by jackmcdade** [comment]
I dunno dude... maybe it's a Canary/Preview cutting edge thing?

![image](https://cloud.githubusercontent.com/assets/44739/18011318/a4235f12-6b82-11e6-9b4f-a8d24b79b7d7.png)

**Comment by jackmcdade** [comment]
Can you tinker with the CSS in your inspector and see what fixes it?
