### ISSUE TITLE
FR: Ability to open sneak peek automatically

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#883]
Sneak peek is a cool feature that I'd like to use more myself but also encourage my clients to use. 

Would you guys consider making it available from the site's frontend? Here's a concept of how I think it could work:

**1) Edit Toggle appears (bottom right) when logged in and viewing site:**
![screenshot 2016-08-24 12 49 39](https://cloud.githubusercontent.com/assets/414211/17945601/63914a66-69f9-11e6-8d78-a2a145a0d729.png)

**2) Turning the Edit Toggle on activates the Sneak Peek sidebar:**

![screenshot 2016-08-24 12 49 14](https://cloud.githubusercontent.com/assets/414211/17945602/639176ee-69f9-11e6-8ec0-20cbd95aa97d.png)

**3) Turning the Edit Toggle off or clicking Done deactivates Sneak Peek mode.**

![screenshot 2016-08-24 12 49 39](https://cloud.githubusercontent.com/assets/414211/17945601/63914a66-69f9-11e6-8d78-a2a145a0d729.png)

**Comment by jasonvarga** [comment]
In a word, no. :)

You have the {{ edit_url }} available to you. You can link to the appropriate place in the CP to edit it, then flick open sneak peek there.

**Comment by mikemartin** [comment]
@jasonvarga Dang. 

Okay, I'll just make a simple Edit button then. 👍

**Comment by jasonvarga** [comment]
Otherwise we have to build a CP around the frontend somehow which just sounds like something that will give me nightmares for the rest of my life.

**Comment by mikemartin** [comment]
Totally get it. 

Could you support appending a hash after the {{ edit_url }} to trigger Sneak Peek?

**Comment by jasonvarga** [comment]
Good idea. I'll change this issue to say that.

**Comment by mikemartin** [comment]
Great. And if it's of any interest, here are the buttons I've added that point to `edit_url`:

`Edit {{if is_page}}Page{{else}}Entry{{/if}}`
![screenshot 2016-08-24 13 20 19](https://cloud.githubusercontent.com/assets/414211/17946544/a12ac7ea-69fd-11e6-9314-9488abf995f3.png)
![screenshot 2016-08-24 13 20 25](https://cloud.githubusercontent.com/assets/414211/17946545/a12afc56-69fd-11e6-93e9-611b92bab6e7.png)

**Comment by jackmcdade** [comment]
Not going to make this one a priority at the moment. I'm very sorry.
