### ISSUE TITLE
Create User button misaligned

### ISSUE THREAD

**Issue by than** [statamic/v2-hub#884]
### Steps to reproduce
1. Drive your browser car to `/cp/users`

### Expected behavior
I expect a supremely polished control panel experience where LITERALLY ALL OF THE BUTTONS are where they are supposed to be.

### Actual behavior
This. 

![](http://than.to/GYol.png)

### Server configuration
**Operating system**:
OS X

**Web server:**
Local

**PHP version:**

**Statamic version:**
2.1.2

**Updated from an older Statamic or fresh install:**
The freshness of 2.1.2

**List of installed addons:**
None

**Comment by jackmcdade** [comment]
Closing because this hurts my feelings. Feel free to open with better manners.

**Comment by jackmcdade** [comment]
That was rude too. Sorry man. We're working on a fix :)

**Comment by edalzell** [comment]
on the 'pending release', do you mean for 2.1.4?

I ask because all of those buttons are still not aligned in 2.1.3 on Safari.

**Comment by jasonvarga** [comment]
Yes 2.1.4

**Comment by than** [comment]
Safari only? Weird. ♻
