### ISSUE TITLE
Installer URL error

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#888]
### Steps to reproduce

Installing new Statamic 2.1.3
### Expected behaviour

Clicking on 'Continue to next step' should send us to next page.
### Actual behaviour

The URL is broken
### Server configuration

**Operating system**: Win7

**Web server:** XAMPP

**PHP version:** 7

**Statamic version:** 2.1.3

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** ---

![screenshot_2](https://cloud.githubusercontent.com/assets/5695187/17957486/55223aa4-6aa7-11e6-94ff-ad386df93a52.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/5695187/17957489/5db20744-6aa7-11e6-8389-b630ef60d4fe.png)

**Comment by jackmcdade** [comment]
Do you have your rewrite rules setup?

**Comment by peimn** [comment]
Yes

**Comment by jackmcdade** [comment]
So you can visit `/cp` or `/about`?

**Comment by peimn** [comment]
Yes
![screenshot_4](https://cloud.githubusercontent.com/assets/5695187/17996683/98975412-6b7f-11e6-9a81-2e4e73e91821.png)

**Comment by peimn** [comment]
Same in 2.1.5:
![screenshot_9](https://cloud.githubusercontent.com/assets/5695187/18025284/5e19bbb6-6c3a-11e6-92ae-80db9f93f8f0.png)

**Comment by peimn** [comment]
2.1.6:
![screenshot_14](https://cloud.githubusercontent.com/assets/5695187/18076296/fba913d2-6e91-11e6-976c-926a841d8873.png)

**Comment by jackmcdade** [comment]
It's been established something is wrong, and we haven't fixed it yet. Hang in there.

**Comment by JohnathonKoster** [comment]
Within the `installer.php` file, the `url` helper function generates incorrect URLs on Windows systems when `pathinfo($_SERVER['SCRIPT_NAME'])['dirname']` returns a backslash `\` character.

For example, it might generate a path that looks like this:

`\/index.php/installer`

That path causes issues when attempting to continue to the next installation step.

This can be fixed by either returning a portion of the `$url` when it starts with a `\` character:

```php
// installer.php
function url($url)
{
    $url = pathinfo($_SERVER['SCRIPT_NAME'])['dirname'] . '/index.php' . $url;

    // If the dirname starts with a `\` character (which can happen on Windows),
    // we need to remove it, as it can cause problems with the URL generator.
    if (substr($url, 0, 1) == '\\') {
       $url = substr($url, 1);
    }

    return str_replace('//', '/', $url);
}
```

or just blatantly replacing all occurrences of `\` with `/`:

```php
// installer.php
function url($url)
{
    $url = pathinfo($_SERVER['SCRIPT_NAME'])['dirname'] . '/index.php' . $url;

    // If the dirname starts with a `\` character (which can happen on Windows),
    // we need to remove it, as it can cause problems with the URL generator.
    $url = str_replace('\\', '/', $url);

    return str_replace('//', '/', $url);
}
```
