### ISSUE TITLE
Redactor toolbar upload button appears by default

### ISSUE THREAD

**Issue by iboxifoo** [statamic/v2-hub#896]
### Steps to reproduce
1. Set up redactor fieldtype using stock basic settings
2. Leave Asset Container without selection
### Expected behaviour

Redactor toolbar contains stock basic buttons only
### Actual behavior

Redactor toolbar contains asset upload button as well as stock basic buttons

NOTE: The upload button is removed from the toolbar by editing the `fieldset.yaml` and deleting the relevant `container: null` line. Would be great if this could be achieved via the CP.

**Comment by edalzell** [comment]
I can't reproduce this @iboxifoo, does it still happen?

**Comment by iboxifoo** [comment]
@edalzell looks like it got fixed somewhere else. Can't reproduce either.
