### ISSUE TITLE
Clicking on 'Add' button picks row for move

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#899]
![screenshot_7](https://cloud.githubusercontent.com/assets/5695187/17999481/b193b9b0-6b8e-11e6-8253-1adaf1e70dc8.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/5695187/17999480/b187afda-6b8e-11e6-979a-69692d055ea0.png)

**Comment by jackmcdade** [comment]
What browser? I can't recreate this.

**Comment by peimn** [comment]
I don't know what happened! It now works!

**Comment by jackmcdade** [comment]
Yay!
