### ISSUE TITLE
Asset files listing in parent directory

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/v2-hub#901]
### Steps to reproduce
1. Upload images to sub-directories in Assets 
2. View parent directory in control panel
### Expected behaviour

I should only see the directories, not files within those directories.
### Actual behaviour

The files from those sub-directories are being listed as well.
### Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**PHP version:** 7.0

**Statamic version:** 2.1.3

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:** None

**Comment by jeremydouglas** [comment]
I was given this as a fix from @jasonvarga in slack. My attempt to add this didn't work.
![pasted_image_at_2016_08_25_11_14_pm](https://cloud.githubusercontent.com/assets/113216/18009236/538ccf7e-6b79-11e6-80fd-394b7a2ec99c.png)

**Comment by cibgraphics** [comment]
I am seeing this as well... fix did not work for me.

**Comment by jasonvarga** [comment]
Alrighty guys. Thanks, we'll sort this out.

**Comment by jeremydouglas** [comment]
@jasonvarga I've updated to 2.1.4 and cleared my cache. The issue remains :(

**Comment by jeffmckeand** [comment]
Same experience here. Issue still remains in 2.1.8
