### ISSUE TITLE
CP Search Safari bug

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#904]
Sorry Jack

![search statamic 2016-08-26 13-12-16](https://cloud.githubusercontent.com/assets/6069653/18019008/e6fdfef8-6b8e-11e6-8d48-f103499c0ea3.png)

**Comment by jackmcdade** [comment]
STOP USING SAFARI GOSH

**Comment by edalzell** [comment]
Downloading Opera now...

**Comment by edalzell** [comment]
can't retest due to #827

**Comment by lukeagsmith** [comment]
Not to overstep, but if you haven't had a chance to look at this yet and it saves you some time, adding `left: 0;` to the `#typeahead ul` class fixes it for me in Safari.
