### ISSUE TITLE
[bug] Undefined view variables creating addon Controller

### ISSUE THREAD

**Issue by ianhubbard** [statamic/v2-hub#906]
### Steps to reproduce
1. Create a new Controller addon with `php please make:controller AddonName`
2. Create meta.yaml
3. View addon page in CP at /cp/addons/AddonName

### Expected behaviour
The default (empty) index view would display with "Content"

### Actual behaviour
PHP error `Undefined variable: update_available (View: <snip>/statamic/resources/views/partials/nav-main.blade.php)`

There are 3 variable errors - `update_available`, `is_trial` and `is_unlicensed`.

Adding those to the view data array resolves the issue (eg):
`return $this->view('index', ['update_available' => false, 'is_trial' => true, 'is_unlicensed' => false]);`

Alternatively removing the 2 partials lines `@include('partials.nav-main')` and `@include('partials.alerts')` from layout.blade.php also resolves the issue.

Obviously neither of these options is ideal. Grepping the code shows that you are sharing `update_available` in the Outpost Middleware, but presumably that isn't included for Addon Routes or something? The other 2 variables don't appear:
```
$ grep -rn "view()->share" *
statamic/core/Http/Middleware/Outpost.php:104:        view()->share('update_available', $this->outpost->isUpdateAvailable());
```

### Server configuration
**Operating system**:
Debian Stretch (Linux)

**Web server:**
Nginx

**PHP version:**
7.0.9-2

**Statamic version:**
2.1.3

**Updated from an older Statamic or fresh install:**
From 2.1.2 I think

**List of installed addons:**
(none other than the base example)

**Comment by ianhubbard** [comment]
Have just updated to shiny 2.1.5 and still have the same issue.

**Comment by jeremykendall** [comment]
I just ran into this today running 2.1.17 in Homestead 0.5.0. Any additional info?
