### ISSUE TITLE
FR: Pagination for users

### ISSUE THREAD

**Issue by Robert-Black** [statamic/v2-hub#908]
### Steps to reproduce
1. I'd like to use pagination tags for my user templates
2. `{{ prev_page }}` and `{{ next_page }}` return nothing inside `{{users}}`

### Expected behaviour
The Docs for `{{users}}` say "This tag has the same functionality as the collection tag, with some differences." Well, one of the differences is that pagination tags don't seem to work.

### Actual behaviour
```
{{ users sort="last_name"  paginate="true" }}
        {{ paginate }}
            <a href="{{ prev_page }}">Previous</a>

            {{ current_page }} of {{ total_pages }} pages
            (There are {{ total_items }} posts)

            <a href="{{ next_page }}">Next</a>
        {{ /paginate }}
    {{ /users }}
```
`{{ prev_page }}` and `{{ next_page }}` both return ""

### Server configuration
**Operating system**:
OS X "El Capitan" 10.11.6

**Web server:**
Apache

**PHP version:**
PHP Version 5.5.29

**Statamic version:**
2.1.5

**Updated from an older Statamic or fresh install:**
fresh

**List of installed addons:**
nil

**Comment by gmcz** [comment]
Hey Robert, I’m not 100% sure but I think you need to set a limit for the pagination to kick in. For example:

```
{{ users sort="last_name"  paginate=“true” limit=“5" }}
```

**Comment by gmcz** [comment]
_And_ you need to have more to display than whatever the limit is.

**Comment by jackmcdade** [comment]
@gmcz you're 100% correct. Until there's a limit, there's no pagination.

**Comment by Robert-Black** [comment]
You are correct, that works. Thank you :-) Since I posted this, I've learnt that what I was **actually** after was is `user:previous` and `user:next`, which don't exist yet but have been flagged as an existing feature request. Meanwhile, I subsequently managed to hack together a working solution for my immediate needs via javascript and the `{{users}}` tag.
