### ISSUE TITLE
Globals - edit layout does not work

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#912]
### Steps to reproduce
1. In the CP > Globals > General > choose Edit Layout
2. Move the layout around and save new layout
3. Reload the page
### Expected behaviour

The new layout should have saved
### Actual behaviour

The layout is the same as before
### Server configuration

**Operating system**: Mac

**Web server:** MAMP (apache 2)

**PHP version:** 7

**Statamic version:** 2.1.6

**Updated from an older Statamic or fresh install:** upgrade

**Comment by matthewjumpsoffbuildings** [comment]
im seeing the same behaviour, any news on this?
