### ISSUE TITLE
Fix `target="_blank"` vulnerability?

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#915]
I came across this: [https://dev.to/ben/the-targetblank-vulnerability-by-example](https://dev.to/ben/the-targetblank-vulnerability-by-example)

>The Practical Developer
>The target="_blank" vulnerability by example
>Instagram leaves its users open to a simple phishing attack (18KB)
 
…and wanted to share w/ you’s.

Off the shelf, I find 7 hits of `target="_blank"` in 6 files in {{S}} 1.11.3, and 14 hits in 10 files in {{S}} 2.1.6, but no hits of `noopener` in either one. According to the article, the hot setup is to always include `rel="noopener noreferrer"`, but I’m not qualified to judge the validity of the article or its advice, so,… just askin’… (?)

(The above copy/pasted from the "General" Statamic topic on Slack)

**Comment by jackmcdade** [comment]
I don't see how this is relevant to Statamic. Do you mean the control panel? How would you click on someone else's link to your own control panel? That should be a secret URL.
