### ISSUE TITLE
Short versions of asset and relate tags

### ISSUE THREAD

**Issue by wojtiku** [statamic/v2-hub#919]
Many times when referencing an `{{ asset:field }}` or `{{ relate:field }}` I don't want to iterate over anything, I just want it to output an url - this is actually the most common scenario for me. Would be awesome if it would be possible.

So, instead of:
```
<a href="{{ relate:link}}{{ url }}{{ /relate:link}}">
    {{ asset:image }}
        <img src="{{ url }}" alt=""> {{ link_text }}
    {{ /asset:image }}
</a>
```
I could do
```
<a href="{{ relate:link}}">
    <img src="{{ asset:image }}" alt=""> {{ link_text }}
</a>
```
or something similar.

**Comment by dannyuk1982** [comment]
If you don't have an asset though, or there is a problem with it your code won't break with the long tags, i.e. say asset:image is blank for an entry, then you just get nothing output. With the short style you end up with <img src="" alt="">

**Comment by wojtiku** [comment]
I always defensively check for assets and field values - usually you want to display something else (e.g. default user avatar is one is not set). I am not saying that we remove the verbose version as it makes sense in some cases. I would just like a short one as in most of my templates this is what I want.

**Comment by jackmcdade** [comment]
It's possible with the "get" modifier and "URL" modifier. 

{{ image | url }} or {{ field | get:title }}

**Comment by wojtiku** [comment]
YOU GUYS ROCK :)
I totally missed those! Just close this, please.

**Comment by wojtiku** [comment]
BTW, the `url` modifier is not on the [list](https://docs.statamic.com/reference/modifiers). So that needs fixing.

**Comment by jackmcdade** [comment]
It's an alias for `| get:url`. But yes.
