### ISSUE TITLE
FR: ability to set logger settings in the environment yaml

### ISSUE THREAD

**Issue by subpixelch** [statamic/v2-hub#920]
### Steps to reproduce
1. Open your dev.yaml in environments folder
2. Add loggers to settings, like

```
settings:
  debug:
    loggers:
      slack: ...
```
### Expected behaviour

The .env file triggers the new loggers-setting in my dev.yaml
### Actual behaviour

It does! But not the **new** loggers setting ...
- This is by design right now  
  (direct quote from Jason: the loggers get bootstrapped earlier than everything else - before the environment stuff)
- **But** would be useful to set logger settings with the environment yaml.
### Server configuration

**Operating system**:
OSX
**Web server:**
Valet
**PHP version:**
7.0.0
**Statamic version:**
2.1.6
**Updated from an older Statamic or fresh install:**
Yep

**Comment by jackmcdade** [comment]
Can you make this request more specific? You _can_ do that for most settings. Logging is an exception.

**Comment by subpixelch** [comment]
OK, didn't know that...

**Comment by sebszocinski** [comment]
+1 and bumping this guy... I want to set email logging on my live env only and not on dev or staging.

**Comment by jackmcdade** [comment]
You can do that with `{env:setting_name}` now. :)
