### ISSUE TITLE
Widget in dashboard: button to create entry has bad label (fieldset instead of title)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#928]
Default widgets in the default dashboard
### Expected behavior

The buttons to create new entries should be labelled "New entry for Blog" and "New entry for Things"

Therefore, the default language string should be `create_entry => 'New entry for :noun'` where `:noun`is the TITLE of the collection
### Actual behavior

The buttons to create new entries are labelled with the name of the fieldset instead of the title of the collection: "New Blog Post" and "New Things" are indeed related to the name of the fieldset for both collections!

Collection title : Blog
Collection default fieldset: Blog Post

This is also visible in the language file:
The string currently is: `create_entry => 'New :noun'` where `:noun` is populated with the name of the default fieldest
### Steps to reproduce

visit the default dashboard on the default install 
### Server configuration

**Statamic version: 2.1.6**

**Comment by ebeauchamps** [comment]
As this been corrected? or was it intended?

In the language (locale) file, the string currently is: create_entry => 'New :noun' where :noun is populated with the name of the default fieldsest

**Comment by jasonvarga** [comment]
Fieldset titles are intended.

If your collection title is "Blog", saying "New Blog" doesn't make sense.
The noun would be the fieldset title. "New Blog Post".

Also, people don't always need to care that it's an entry.

Collection: Blog
Fieldset: Post
"New entry in Blog" vs. "New Post"

Collection: Locations
Fieldset: Location
"New entry in Locations" vs. "New Location"
