### ISSUE TITLE
Markdown field format breaking

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/v2-hub#930]
### Expected behaviour
Markdown field will save properly.

### Actual behaviour
Markdown field is saved starting with a pipe character and tabbed indents for each line.

### Steps to reproduce
1.  Save content from Control Panel with Markdown field nested in a Replicator.
2. Accidentally enter a few hard returns at the end of the textarea.
2. View live page.
2.  Markdown content gets thrown off by an added pipe character to the beginning and tab indenting to each line.

Here's a screenshot of how it ends up:

![screen shot 2016-09-07 at 11 33 32 am](https://cloud.githubusercontent.com/assets/113216/18319402/91d44bee-74f3-11e6-91c1-34a4a02b3243.png)

And in the template:

![screen shot 2016-09-07 at 12 14 15 pm](https://cloud.githubusercontent.com/assets/113216/18319652/a6d6becc-74f4-11e6-9d70-cc2806f0e31f.png)

Seems to happen when there are hard returns at the end of a textarea. I'm not sure if there are other instances that will trigger this as well.

### Server configuration
**Operating system**: Ubuntu

**Web server:**  Linode

**PHP version:** 7

**Statamic version:** 2.1.6

**Updated from an older Statamic or fresh install:** Updated from V1, but this is a new Fieldset and Collection.

### Logs
From my server error log
```
[Wed Sep 07 15:32:22.884057 2016] [proxy_fcgi:error] [pid 22461:tid 140533619984128] (104)Connection reset by peer: [client 72.38.112.218:57574] AH01075: Error dispatching request to : (passing brigade to output filters), referer: http://wentworthlandscapes.com/blog/bridal-wreath-spirea
[Wed Sep 07 15:32:22.910761 2016] [proxy_fcgi:error] [pid 22210:tid 140533678733056] (104)Connection reset by peer: [client 72.38.112.218:57576] AH01075: Error dispatching request to : (passing brigade to output filters), referer: http://wentworthlandscapes.com/blog/bridal-wreath-spirea
[Wed Sep 07 15:32:23.266870 2016] [proxy_fcgi:error] [pid 22461:tid 140533578020608] (104)Connection reset by peer: [client 72.38.112.218:57594] AH01075: Error dispatching request to : (passing brigade to output filters), referer: http://wentworthlandscapes.com/blog/bridal-wreath-spirea

```

**Comment by jeremydouglas** [comment]
@edalzell helped me out on this. We found that it is an issue with [spyc](https://packagist.org/packages/mustangostang/spyc). @jasonvarga has an [open issue.](https://github.com/mustangostang/spyc/issues/54)

There is a [fix](https://github.com/mustangostang/spyc/pull/46). We've [requested a release.](https://github.com/mustangostang/spyc/issues/55) 

Can anything be done to encourage that release?

**Comment by edalzell** [comment]
I reached out to the dev on twitter and email but no response.

**Comment by jackmcdade** [comment]
We can peg composer on a specific commit, but we'll want watch for updates after that.

**Comment by edalzell** [comment]
The commit is [here](https://github.com/mustangostang/spyc/pull/46) @jackmcdade

**Comment by jackmcdade** [comment]
Yep got it. Thanks!
