### ISSUE TITLE
Bug: Cannot reorder formset fields

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#931]
### Expected behaviour

When _editing_ a formset, you can reorder the fields using the drag handle.
### Actual behaviour

Cannot drag fields to reorder.
### Steps to reproduce
1.  Create fieldset with several fields
2.  Edit fieldset
3.  Attempt to reorder fields
### Server configuration

**Operating system**: Mac

**Web server:** Valet

**PHP version:**

**Statamic version:** 2.1.6 and 2.1.7

**Updated from an older Statamic or fresh install:**

**List of installed addons:**
### Logs

If any logs (browser, server, or Statamic) are appropriate...

```
Add those logs here
```

**Comment by jackmcdade** [comment]
What purpose would there be to reordering them?

**Comment by mikemartin** [comment]
Here's a GIF to demonstrate the bug:
![field-reordering](https://cloud.githubusercontent.com/assets/414211/18320300/18c6462c-74de-11e6-865f-1498fb8c54d6.gif)

**Comment by jackmcdade** [comment]
Ah okay i see because we’re using the Grid field to manage the setting. Got it. Thanks for the report!
