### ISSUE TITLE
When running in a subdirectory, the subdirectory is used in the CP edit URL.

### ISSUE THREAD

**Issue by jasonvarga** [statamic/v2-hub#937]
Subfolder.

Putting that word there so searches can pick it up. :) Github SEO.

**Comment by jasonvarga** [comment]
Subfolder.

Putting that word there so searches can pick it up. :) Github SEO.

**Comment by sarahkyler** [comment]
Has this been fixed? I'm still running into this issue on some of my sites.

**Comment by mattrock1** [comment]
I've run into the same issue as well. Would really appreciate help on this (not sure why this issue was closed)

**Comment by jasonvarga** [comment]
Unintentionally closed. It's fixed for next release now.
