### ISSUE TITLE
[bug] Php error on Addon CP page with timed out session

### ISSUE THREAD

**Issue by ianhubbard** [statamic/v2-hub#940]
### Expected behaviour
Be redirected to the CP login page

### Actual behaviour
FatalErrorException in PermissionComposer.php line 13:
Call to a member function permissions() on null

### Steps to reproduce
1.  Access a /cp/addons/myaddon URL with a timed out session

### Server configuration
**Operating system**: Linux (Debian Jessie 8.5)

**Web server:**: Nginx 1.6.2

**PHP version:**: PHP v5.6.24

**Statamic version:**: v2.1.8

**Updated from an older Statamic or fresh install:** Upgrade

**List of installed addons:**
1 Custom addon

**Comment by ianhubbard** [comment]
I was thinking the lack of redirect might be due to a lack of middleware, but the upgrade to 2.1.8 included middleware in bindAddonRoutes() so it isn't that.

**Comment by edalzell** [comment]
This is a duplicate...finding original...

**Comment by ianhubbard** [comment]
Ahhh yes. I searched, but not on the error message. Duplicate of #150
