### ISSUE TITLE
FR: Unable to set focal point on images if filesystem is above webroot

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#942]
### Expected behaviour

We keep our filesystems above root. We thought the CP always used Glide to display images, which made this okay. However, when setting a focal point, it doesn't, so…
### Actual behaviour

…imgs are broken.

**Comment by jasonvarga** [comment]
This is done for 2.2

**Comment by curtisblackwell** [comment]
today was the first day i saw focal point in action and i loved it
