### ISSUE TITLE
2.1.9 UI issue in CONFIGURE/Settings/CSRF excluded URLs

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#943]
### Expected behavior
Same UI as "Application Key" (above in the same menu)

### Actual behaviour
![capture d ecran 2016-09-09 a 21 13 50](https://cloud.githubusercontent.com/assets/1823359/18399734/abfff0fa-76d2-11e6-8b4c-f4c1e3fbe208.png)

```

**Comment by jackmcdade** [comment]
It's not a string, it's an array. Hence the list fieldtype.
