### ISSUE TITLE
Bug: saving a User file does not trigger a stache update

### ISSUE THREAD

**Issue by jsblair9** [statamic/v2-hub#947]
### Expected behavior
When saving a user file with updated content, I'd like it to be considered a publish event, which would trigger a stache update. This way that content would be reflected in the CP on save. 

### Actual behavior
Currently, on save (or save-continue) in the CP for a user file, the changes are not reflected on the post save view. The changes are saved in the file, and if you manually update the stache, the changes are reflected in the CP. 

### Steps to reproduce
1. Open a user file from the CP
2. Change some information in any fieldset
3. Hit save or save-continue
4. Notice that changes do not appear to be saved
5. Clear Stache manually
6. Refresh that user file in CP
7. See the changes accurately reflected

### Server configuration
**Operating system**:   

**Web server:** `Nginx 1.10.1` `Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-57-generic x86_64)`

**PHP version:** `php 7.0.10`

**Statamic version:** `2.1.8`

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:** ask if needed and I'll update

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Browser:
Uncaught TypeError: t.dmUploader is not a function
  bindUploader @ jabbascripts.js?v=2.1.8:4
  (anonymous function) @ johnny-deps.js?v=2.1.8:5
  (anonymous function) @ jabbascripts.js?v=2.1.8:4
  s @ johnny-deps.js?v=2.1.8:7
  t @ johnny-deps.js?v=2.1.8:7
```

**Comment by jasonvarga** [comment]
What's in your `site/settings/caching.yaml`?
