### ISSUE TITLE
Error on saving globals

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#948]
### Server configuration
**Operating system**: Redhat

**Web server:** Apache

**PHP version:** 5.6

**Statamic version:** 2.1.9

**Updated from an older Statamic or fresh install:** Freash

**List of installed addons:** ---

### Logs
PHP Fatal error:  Call to a member function in() on null in ~/statamic/core/CP/Publish/GlobalsPublisher.php on line 44

**Comment by jackmcdade** [comment]
Fix coming in the next patch.
