### ISSUE TITLE
Changing name of a filed doesn't change the column's name that belongs to that field

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#949]
### Expected behaviour

Name of the column that belongs to a specific field has to be changed.
### Actual behaviour

Not changed.
### Steps to reproduce
1.  Go to fieldsets and edit things fieldset
2.  Change one of the fields and rename it.
3.  Go to collections>things and you'll see your changed label doesn't change
### Server configuration

**Operating system**: Redhat

**Web server:** Apache

**PHP version:** 5.6

**Statamic version:** 2.1.9

**Updated from an older Statamic or fresh install:** fresh

**List of installed addons:** --

**Comment by jackmcdade** [comment]
Can you add screenshots? I’m not entirely sure which area you’re referring to.

**Comment by peimn** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/5695187/18445317/3f1c32ca-7932-11e6-827a-85d37776853e.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/5695187/18445318/3f4c8f38-7932-11e6-8d15-de1ab7325e70.png)

**Comment by jackmcdade** [comment]
Ah okay gotcha. That’s because we slugify the fieldname. Noted, thanks!
