### ISSUE TITLE
Cannot Change Slug on Parent Page

### ISSUE THREAD

**Issue by zenboy4ever** [statamic/v2-hub#951]
### Expected behaviour

Changed a page title and page slug 
### Actual behaviour

If page has no child pages, the slug change is successful but the spinning Loading icon remains on the screen. You can see the new slug name after clearing the cache.

If page has child pages, the page with the new slug is created but the old page with the old slug  is not removed and child pages remain with the old page. The spinning Loading icon remains on the screen.
### Steps to reproduce
1.  Open page
2.  Change the slug
### Server configuration

**Operating system**:
OSX 10.11.6
**Web server:**
MAMP Pro 4
**PHP version:**
7.0.10
**Statamic version:**
2.1.9
**Updated from an older Statamic or fresh install:**
Updated

**Comment by curtisblackwell** [comment]
I have the same problem.

1. Change slug via CP.
2. Statamic creates new folder with appropriate slug and moves index.md into it.
3. Old folder persists with all other content (3 child pages and a folder.yaml).

**Comment by esonesson** [comment]
Any news on this? I have the same issue, when I change the slug on a page with children the children disappear in cp. But if I change the slug back the children are there. Aren't the child pages supposed to follow?

**Comment by sheldonkotyk** [comment]
For a workaround, change the folder name of the parent in the filesystem.

**Comment by anthubbard** [comment]
I seem to still have this now on 2.5.11 - this is a pretty serious bug @jasonvarga? Any word on it... This makes it impossible for clients to change the slug of any page in their site that has children... unless there's something I'm missing, that's almost a game-stopper.

**Comment by peda** [comment]
just came across the same exact issue - that's super annoying - because now have to babysit the site while the SEO guy does his job

**Comment by jackmcdade** [comment]
Somehow this one slipped right past us. Will get it fixed asap!
