### ISSUE TITLE
FR: please add a Currency Modifier

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#954]
Format's the number as a currency.

Code:
```
class CurrencyModifier extends Modifier
{
    /**
     * Modify a value
     *
     * @param mixed  $value    The value to be modified
     * @param array  $params   Any parameters used in the modifier
     * @param array  $context  Contextual values
     * @return mixed
     */
    public function index($value, $params, $context)
    {
		setlocale(LC_MONETARY, 'en_US.UTF-8');
		return money_format('%.2n', $value / 100);
    }
}
```

**Comment by dannyuk1982** [comment]
Won't that just output dollar signs?

**Comment by edalzell** [comment]
No, it takes something in cents and converts to dollars...and adds the currency symbol

**Comment by dannyuk1982** [comment]
Yea.. my point being - outside the US it doesn't seem much use

**Comment by jackmcdade** [comment]
In this form i'd call it `| to_dollars` or something. As a core feature we'd need it to have a wide use. Would need to implement something like [moltin/currency](https://github.com/moltin/currency).

**Comment by edalzell** [comment]
great idea Jack, I look forward to it!! ;=)

**Comment by jasonvarga** [comment]
Sorry to be that guy. I don't think this belongs in the core.
