### ISSUE TITLE
Cannot output page url with get modifier

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#957]
### Expected behaviour
Output a page url using `{{ page_link | get:url }}`

### Actual behaviour
No output. 

But this works:
```
{{ relate:page_link }}{{ url }}{{/relate:page_link}}
```

### Steps to reproduce
1.  Create page fieldtype named `page_link`
2.  Output related values using get modifier

### Server configuration
**Operating system**:

**Web server:**

**PHP version:**

**Statamic version:** 2.1.10

**Updated from an older Statamic or fresh install:**

**List of installed addons:**

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Add those logs here
```

**Comment by jackmcdade** [comment]
URL is special: `{{ page_link | url }}`.

**Comment by mikemartin** [comment]
Cool!
