### ISSUE TITLE
Form redirect parameters to /page#anchor don't work

### ISSUE THREAD

**Issue by mikegraham00** [statamic/v2-hub#960]
### Expected behaviour

{{ form:create in="formset" redirect="/page#anchor" error_redirect="/page#anchor" }}
Should redirect to #anchor location on the same page.

Also, redirect="#anchor" should redirect to anchor on same page.
### Actual behaviour

Displays top of page on submit (success or error).

**Comment by jasonvarga** [comment]
Seems to work fine when doing something like `redirect="/foo#bar"`. Do you end up on a URL with a hash on it?

(The request for it to work with only a hash is a separate thing)

**Comment by mikegraham00** [comment]
No doesn't change the URL. Tried redirect="/completely-different-page" and that doesn't work either for me. Maybe a version issue? We're on 2.1.2 but I don't see anything more recent in changelog about form redirect.

**Comment by jackmcdade** [comment]
Fixed in 2.1.19.
