### ISSUE TITLE
FR: dump data sorted

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#961]
Lames request, can the data shown with `dump` be sorted alphabetically?

**Comment by jasonvarga** [comment]
I don't think so. The point is to see the stuff. Modifying it before displaying could be confusing.

You can sort the data before dumping.

**Comment by edalzell** [comment]
How?

**Comment by jasonvarga** [comment]
`{{ array | sort | dump }}`

You can't do it with the `dump` tag.

**Comment by edalzell** [comment]
but I'd want the whole context sorted (that was the point of the request), is there a way to do that?

This is not a huge thing, but wading through the context unsorted is a pain. Perhaps I'll make my own tag.

**Comment by jasonvarga** [comment]
Go for it. It's just a one line helper tag, we don't want to add bells and whistles to it.
