### ISSUE TITLE
Empty array causes a `looped_tags` error

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#962]
This data:
![v2 devplacid 2016-09-15 18-13-27](https://cloud.githubusercontent.com/assets/6069653/18572853/b0722a68-7b73-11e6-94ca-4770ca2bc1ea.png)

Used in this template:

```
     {{ departments }}
       <div class="department {{ name|slugify }}">
         {{ jobs }}
           {{ if first }}
             <h4 class="department-title">{{ name }}</h4>
             <a class="department-content-trigger" data-dept-trigger-text="Show positions" data-dept-trigger-text-swap="Hide positions" href="#">Show positions</a>
             <div class="department-content">
                 {{ /if }}
           <div class="job-item">
             <p class="job-title"><a href="/about/careers/job?jobid={{ id }}">{{ title }}</a></p>
             <p class="job-location">{{ location }}{{ name }}{{ /location }}</p>
           </div>

           {{ if last }}</div>{{ /if}}
         {{ /jobs }}
       </div>
       <!-- </div> -->
     {{ /departments }}
```

Causes a `looped_tags` error

**Comment by vladdu** [comment]
The same happens with all arrays, most visible probably when a blog post has no tags attached, using the stock Redwood theme. It feels clunky to need to check if the array is empty, and even if that would be the recommended way, the Redwood theme should use it.

**Comment by anthubbard** [comment]
Hi Jason,

Do you have a rough timeline on when this will be fixed (2.6 released)? This shows on my empty replicator loops - is there a temp fix / way to not display the error?

**Comment by jasonvarga** [comment]
`{{ if replicator }} {{ replicator }} ... {{ /replicator }} {{ /if }}`

**Comment by anthubbard** [comment]
Well thats embarrassing...
