### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by dddom** [statamic/v2-hub#972]
I couldn't find an already existing issue about this. so is there any way to set the site in maintenance mode, much like `php artisan down` would do?

It'd be great if `please` supported this but if there's a way to do it manually, I'd love to hear about it.

Cheers!

**Comment by jasonvarga** [comment]
Statamic is Laravel, so `php artisan down` still exists (except `please` instead of `artisan`).

However, we're using the 503 template for displaying our invalid license page, so things will appear more broken than they should.

I've just fixed that all up now though. It'll be in the next release.

**Comment by dddom** [comment]
Hey @jasonvarga thanks for the info, looking forward to the next release, would be sweet!
