### ISSUE TITLE
Saving an entry does not invalidate the stache

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#973]
### Expected behaviour
Saving an entry invalidates the stache

### Actual behaviour
It doesn't

### Steps to reproduce
1. Save an entry 
2.  Don't manually clear the cache
3.  The entry doesn't appear on the site

### Server configuration
**Statamic version:**
2.1.10

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**
None

### YAML
`caching.yaml` is
```stache_always_update: true
static_caching_enabled: true
static_caching_length:
static_caching_type: file
static_caching_file_path: static
static_caching_ignore_query_strings: true
static_caching_exclude: [ ]
static_caching_invalidation: [ ]```

**Comment by jasonvarga** [comment]
Does the entry appear in the CP?

**Comment by dannyuk1982** [comment]
Yes, CP side all works fine. And without `static_caching_enabled` on it works fine - with that on it won't show up until the cache is manually cleared

**Comment by jasonvarga** [comment]
Okay I misunderstood your problem when you explained it in Slack. I thought you were saying new entries weren't appearing _anywhere_, including the CP.

This is all expected then.

You don't have any invalidation rules. You'll need to tell it to wipe the listing pages (and whatever else) when something is edited.

```
static_caching_invalidation:
  collections:
    blog:
      urls:
        - /blog
        - /blog/category/*
        - /
```

This says to clear `/blog`, child pages of `/blog/category` and the home page whenever something in the `blog` collection is saved.

**Comment by dannyuk1982** [comment]
Thank you! Just pasting this from slack too


danny [3:53 PM]  
a line in the CP under it would be awesome, i.e.

`If you're using the control panel to manage content, you can disable this as the Stache will get updated when you publish pages only, for collection entries you need to set the urls to invalidate (see docs for details)`

as I just read `the Stache will get updated when you publish` and assumed as the entries all have a `publish` button it would work

**Comment by jackmcdade** [comment]
Have you tried 2.1.11? Should be fixed.

**Comment by dannyuk1982** [comment]
Hey Jack, Jason solved it earlier - I wasn't using the URL rules, so not a bug
