### ISSUE TITLE
Array modifier order matters, but shouldn't

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#974]
### Expected behaviour
I should be able to place my modifiers in any order and get the same results.

### Actual behaviour
Placing offset after limit returns unexpected results.

### Steps to reproduce
1.  Have an array.
2.  Iterate over that array with a set limit and offset (with limit first).

**Comment by jackmcdade** [comment]
Nope, Modifiers are 100% order dependent by design.

**Comment by curtisblackwell** [comment]
😢 :trombone:

**Comment by jackmcdade** [comment]
Think about it. Each modifier modifies the data and then sends it back. If you offset and then limit, or limit and then offset, you're going to have two totally different results.

**Comment by jasonvarga** [comment]
`{{ string | backspace:2 | reverse }}`

Without order, what would you expect to happen here?

**Comment by curtisblackwell** [comment]
I guess I just don't see why the order should matter for limit and offset. When would you ever want to limit then offset? Though it's definitely not worth breaking the mold over.

**Comment by jackmcdade** [comment]
Those would be maybe the only two you'd want to work that way. And then we'd need to find a way to make them bypass the normal Modifier logic, and then document that those two are special... best to just order them as you will, and move on.

**Comment by curtisblackwell** [comment]
Right, I agree. Just didn't think of them as modifiers since I wrote them like parameters.
