### ISSUE TITLE
When running in a subdirectory, CP has the wrong link to create a page

### ISSUE THREAD

**Issue by sarahkyler** [statamic/v2-hub#977]
### Expected behaviour

Click the button, select the fieldset, go to create the page
### Actual behaviour

After selecting the fieldset, the create link is missing the /sub/ part of the url. 
So instead of:
http://domain.com/**sub**/cp/pages/create?fieldset=fieldset
It tries to go to:
http://domain.com/cp/pages/create?fieldset=fieldset
and subsequently fails. 

The rest of the site and CP are completely functional with the subdirectory setup. (except editing pages, but that's another issue: #937 )
### Server configuration

**Operating system**:
CentOS release 6.8 (Final)
Linux 4.6.5-x86_64-linode71

**Web server:**
Apache 2.2.31

**PHP version:**
PHP 5.6.25

**Statamic version:**
2.1.11
(has existed in previous versions though)

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**
None

I apologize if this is a duplicate issue, searching gave me nothing.

**Comment by jackmcdade** [comment]
Did you set your site_root in your `index.php` file?

```
$site_root = '/**sub**/';
```

**Comment by sarahkyler** [comment]
Yes, the index.php, .htaccess and control panel settings are all set up correctly. It's just this one link that doesn't work.

**Comment by jcohlmeyer** [comment]
I am also experiencing this issue and in addition edit page links do not work unless I set `/site/settings/system.yaml' locales url to `/` but this breaks the front-end of the site ...

**Comment by mattrock1** [comment]
I'm experiencing the issue here as well.

**Comment by jasonvarga** [comment]
Fixed for the next release.
