### ISSUE TITLE
FR: display character count for a field

### ISSUE THREAD

**Issue by stevieg83** [statamic/v2-hub#978]
I feel like https://github.com/LkeMitchll/statamic-limited should be a core feature if you have validation set for max length on a field

**Comment by jackmcdade** [comment]
Hi Steven! This is a duplicate of #822, which happens to be yours as well. 😂

**Comment by jasonvarga** [comment]
He's trying to game the system. I'm onto you, @stevieg83

**Comment by jackmcdade** [comment]
![No soup!](https://cdn.meme.am/instances/65152924.jpg)
