### ISSUE TITLE
Translate CP - even labels 

### ISSUE THREAD

**Issue by danieljwestman** [statamic/v2-hub#980]
It would be great if there was possible to translate the CP without hacking the core...

In addition it would be great to be able to translate/localize the labels in a fieldset.

**Comment by ebeauchamps** [comment]
My CP is 95% translated and I never hacked the core?! "just" translate the files located in the `en` folder, put them in your own language folder (ie `fr` or `nl` or `de` ...) and here we go!

**Comment by danieljwestman** [comment]
Well yes, but you have to put the custom language folder in the statamic folder everytime there is an update. Yes? That's not to much work, but is it the correct way?

How do you translate the labels for a fieldset?

**Comment by ebeauchamps** [comment]
Yes, the update should not throw away our language folder (already wrote that to the Gentlemen: this language folder doesn't appear to be in the right folder)

I cannot answer your second request.

**Comment by jackmcdade** [comment]
Closing in favor of #991's clearer title
