### ISSUE TITLE
OAuth - provider name in events

### ISSUE THREAD

**Issue by danieljwestman** [statamic/v2-hub#981]
It would be neat if the current provider name where available in all the event classes;

`Statamic\Events\OAuth\FindingUser` <-- here you have it as $event->provider
`Statamic\Events\OAuth\GeneratingUsername` <-- not here, only $event->user
`Statamic\Events\OAuth\GeneratingUserData` <-- same here, only $event->user

I've added it my self in `statamic/core/Http/Controllers/Auth/OAuthController.php` and it works as it should.

oAuthUserData():

`if ($data = Event::fireFirst(new GeneratingUserData($provider, $user))) { ...`

**Comment by christopherburton** [comment]
Agreed. Had to do the following to get the provider name:

**findUser**
```php
public function findUser(FindingUser $event)
{
  return $this->provider = $event->provider;
}
```
**userData**
```php
public function userData(GeneratingUserData $event)
{
  return    [
    // other stuff here
    'url' => 'https://' . $this->provider . '.com/' . $event->user->nickname,
    ... other stuff here
  ];
}

**Comment by jasonvarga** [comment]
Added to next release.
