### ISSUE TITLE
format_localized not translating

### ISSUE THREAD

**Issue by zenboy4ever** [statamic/v2-hub#987]
### Expected behaviour
format_localized should display translated and formatted dates

### Actual behaviour
The date is formatted correctly but not translated

### Steps to reproduce
1.  {{ date format_localized="%d %B %Y" }}

### Server configuration
**Operating system**:
Linux
**Web server:**
Apache
**PHP version:**
7.0
**Statamic version:**
2.1.9
**Updated from an older Statamic or fresh install:**
Updated

**Comment by jackmcdade** [comment]
Did you set your locale on the system level? It follows the php.ini setting.

**Comment by zenboy4ever** [comment]
I changed the locale and it is working now. Thanks for the suggestion Jack.

**Comment by jackmcdade** [comment]
👍
