### ISSUE TITLE
Update to 2.1.12 with modified filesystem in system.yaml causes error

### ISSUE THREAD

**Issue by gmcz** [statamic/v2-hub#990]
### Expected behaviour
Everything works, but is better.

### Actual behaviour
Get the following error:

![](http://link.colker.net/10OUs+)

### Steps to reproduce
**1.** Have custom theme filesystem in system.yaml such as:

```
filesystems:
  themes:
    driver: local
    root: public/themes
    url: /themes
```

**2.** Run the updater, get the error.

### Server configuration
**Operating system**:
macOS Sierra
**Web server:**
Valet
**PHP version:**
7
**Statamic version:**
2.1.12
**Updated from an older Statamic or fresh install:**
Updated from 2.1.10 and 2.1.11
**List of installed addons:**
Spock

### Jason’s Fix
This worked to solve the issue:
> copy the whole array from `statamic/settings/defaults/system.yaml` and then modify your `themes` filesystem

**Comment by edalzell** [comment]
I encounter a similar problem. My `systems.yaml` did NOT have a themes section and the default did not load.

It made my site broken as it couldn't find the theme.

Copying in the default `themes` section from the system defaults fixed it for me.
