### ISSUE TITLE
2.1.12+ Move/support locale/translations folder outside /statamic

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#991]
### Expected behavior
When upgrading, we should never lose our own locale folder(s) that is/are in use for translating the CP

### Actual behaviour
Any folder located in resources/lang/ is cleared when upgrading. The `en` folder is swapped for a fresh one, but any locale folder within lang is completely cleared! The locale folder should be located in a folder that is not cleared when upgrading (like in EE) OR the locale strings should be downloaded from a central repo (CDN, like in CRAFT) each time you upgrade

This problem was detected with 2.0

Related to #980

**Comment by jasonvarga** [comment]
We have this on our internal to-do list. Good to have this here too, though.

**Comment by ebeauchamps** [comment]
Great!

**Comment by jackmcdade** [comment]
@ebeauchamps would it possible to send us a copy of your `lang` folder for us to test?

**Comment by ebeauchamps** [comment]
Can you get it from here?

https://github.com/statamic/i18n/pull/64

If not, I can send it to you (2.1.11, because 2.1.12 isn't finished yet)
Let me know

**Comment by jackmcdade** [comment]
Ahh yes this is great. That repo is still setup for v1 which why we haven't merged your PR yet.

**Comment by ebeauchamps** [comment]
Great work on this! Thanks.
