### ISSUE TITLE
2.1.12 Still many untranslated strings in the CP

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#992]
### Expected behavior
The CP in the language of my client

### Actual behavior
Still a lot of US English throughout the CP

### Examples
CONFIGURE (in the sidebar)
Search for anything... (top of the CP)
Show URLs / Show Titles (in the Pages menu)
Edit / Delete / Create Page / Mount Collection (actions on the right of Pages and Collections screens)
...

**Comment by jackmcdade** [comment]
There are lot of new language variables. Search for anything is `cp.search_for_anything`, `cp.create_page_button` is the Create Page button... Can you confirm you're using them in your translation? I can't find any of these missing.

**Comment by ebeauchamps** [comment]
These strings are present, you are right, but are not fetched from my translated files.

**Comment by jackmcdade** [comment]
Okay, that might be more of a bug than a missing translation. We haven’t actually made it translatable officially yet (files outside /statamic etc). coming soon.

**Comment by ebeauchamps** [comment]
As I reported back when 2.0.0 went out, you could have fully translated files in your own locale folder, but the CP was only translated at about 50%. It's clearly getting better, but some string are missing.

The CONFIGURE submenu in the sidebar was included not long ago, but It is still untranslated despite being present in my own language file. Yet, all other submenus are now translated!

**Comment by jackmcdade** [comment]
Fixed for next release.

**Comment by ebeauchamps** [comment]
Nice, very nice! Thanks.

**Comment by jackmcdade** [comment]
@ebeauchamps 

> Why is this one untranslated, I don't quite understand.

The reason is, it's really hard. There are 10s of thousands of lines of code to paw through to find text strings in javascript, php, html, server callbacks, ajax responses, api calls, blade templates.... We're so close. Thanks for being patient :)

**Comment by patrikkernke** [comment]
Hello Jackmcdade,
I have the same problem here. Tried to translate the whole control panel in german. 95% are okay, but there are problems with dynamic translations in vue like 
```php
// File: statamic/resources/views/pages.blade.php
// Row 12-40
...

<div class="controls">
    
    <div class="btn-group" v-if="arePages">
        <button type="button" class="btn btn-default" v-on:click="expandAll">

            {{ translate('cp.expand') }} // OKAY TRANSLATED

        </button>
        <button type="button" class="btn btn-default" v-on:click="collapseAll">

            {{ translate('cp.collapse') }} // OKAY TRANSLATED

        </button>
        <button type="button" class="btn btn-default" v-on:click="toggleUrls" 
            
            v-text="translate('cp.show_'+show)" >
            // NOT OKAY, IS NOT TRANSLATED (DYNAMIC PARAMETER)
            // The translation string exists in english and german: cp.show_url 
            // and cp.show_titles. But it returns only the default english.

        </button>
    </div>
    
    @can('pages:create')
        <div class="btn-group">
            <button type="button" class="btn btn-primary" @click="createPage('/')">

                {{ translate('cp.create_page_button') }} // OKAY TRANSLATED

            </button>
       </div>
   @endcan
   
   @can('pages:reorder')
       <div class="btn-group" v-if="arePages && changed">
           <button type="button" class="btn btn-secondary" v-if="! saving" @click="save">

               {{ translate('cp.save_changes') }} // OKAY TRANSLATED

           </button>
           <span class="btn btn-primary btn-has-icon-right disabled" v-if="saving">

               {{ translate('cp.saving') }} // OKAY TRANSLATED
               <i class="icon icon-circular-graph animation-spin"></i>

           </span>
       </div>
  @endcan

</div>

...

```

The same happens in the file `statamic/resources/views/settings/edit.blade.php`

```php
// Row 5-11

<div class="tabs">
        @foreach ($settings as $setting)
            <a href="{{ route('settings.edit', $setting) }}" class="{{ $setting !== $slug ?: 'active' }}">
                
                 {{ translate('cp.settings_'.$setting) }}
                 // NOT WORKING, DYNAMIC PARAMETER

            </a>
        @endforeach
</div>
```

I appreciate your hard work! Thanks in advanced. I am testing Statamic and wish I could use it in my projects. But the translation thing is a crucial thing for my clients ...

**Comment by ebeauchamps** [comment]
Patrick, try adding `locale: de` to `site/settings/cp.yaml`
