### ISSUE TITLE
Sibling pages w/ same beginning slug

### ISSUE THREAD

**Issue by AdamChlan** [statamic/v2-hub#993]
### Expected behaviour
I would expect all sibling pages to be siblings, rather than one being incorrectly considered a parent.

### Actual behaviour
It two sibling pages share the same slug beginning, the one with the shorter slug is considered a parent. For instance:

site.com/test <- This is considered a parent of the page below, even when they are siblings
site.com/test-again 

### Steps to reproduce
1.  Create two sibling pages in the style shown above.
2.  Build a navigation displaying pages, and add a conditional to add a class to parent pages. 
3.  When on site.com/test-again, the nav link for site.com/test will receive the parent class.

### Server configuration
**Operating system**:
OS X 
**Web server:**
Ubuntu 14.4
**PHP version:**
5.6.x I believe
**Statamic version:**
2.1.12
**Updated from an older Statamic or fresh install:**
updated
**List of installed addons:**
Bluebird

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Add those logs here
```

**Comment by jackmcdade** [comment]
Nice find! Fixed for next release.
