### ISSUE TITLE
Deleting ordered pages doesn't renumber them

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#994]
### Expected behaviour
Page folders are sequential

### Actual behaviour
Pages keep their original number

### Steps to reproduce
1.  Have several pages ordered by `number`
2.  Delete some
3.  Look in your `pages` folder

**Comment by jackmcdade** [comment]
That's actually desired behavior. They're still in the same _order_, and we don't affect more files than necessary for `git` changes.

**Comment by jasonvarga** [comment]
I'm pretty sure you opened this exact issue before :)

**Comment by edalzell** [comment]
I'm forgetful but consistent.
