### ISSUE TITLE
__double underscore v1 files will create a dupe content file and 404 site if edited from the CP.

### ISSUE THREAD

**Issue by peterbaker** [statamic/v2-hub#995]
### Actual behaviour

404 the entire site
### Steps to reproduce
1.  If you have one collection file named `__0.something.md` (which we had from a v1 site, a hidden page)
2.  Statamic will create another file named `_something.md`
3.  And every page that gets visited will 404 after that
### Server configuration

**Operating system**:
Mac OS
**Web server:**
Apache
**PHP version:**
7
**Statamic version:**
2.1.12
**Updated from an older Statamic or fresh install:**
Updated
**List of installed addons:**
### Logs

If any logs (browser, server, or Statamic) are appropriate...

```
Add those logs here
```

**Comment by jasonvarga** [comment]
A 404 no longer happens. Instead, a duplicate ID warning is shown in the CP with the ability for you to resolve.
