### ISSUE TITLE
2.1.12 Experimenting with changing the locale in index.php results in no CP access

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/v2-hub#996]
Changed the default locale in `index.php` from `en` to `fr`
There is a `fr`folder in the `lang`folder

Also tried by changing to `nl` without such a folder in the `lang`folder

### Expected behavior
I should be able to access the CP in my language or at least in English

### Actual behavior
No access to the CP.
"Safari cannot open the page. Too much redirects"

### Server configuration
**Operating system**: Mac OS X El Capitan

**Web server:** MAMP Apache

**PHP version:** 7.0.0

**Statamic version:** 2.1.12

**Updated from an older Statamic or fresh install:** update

**Comment by jackmcdade** [comment]
Do you also have the local set in `system.yaml`?

**Comment by ebeauchamps** [comment]
hum...no
Let me try this

**Comment by ebeauchamps** [comment]
Something like this?
```
locales:
  en:
    full: en_US
    name: Anglais
    url: http://statamic2.dev/
  fr:
    full: fr_FR
    name: Français
    url: http://statamic2.dev/fr/
```
Same behavior if I visit http://statamic2.dev/cp

**Comment by jackmcdade** [comment]
Yes, and the locale name in index.php must match the `full` value, e.g.` fr_FR`.

**Comment by ebeauchamps** [comment]
1. But why is it accepting `en`though?

2. So I put `$locale = 'fr_FR';`
But I got "Whoops, looks like something went wrong"

log:
```
[2016-09-28 19:53:11] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Carbon\Carbon::setLocale(): Failed opening required '/Users/efb/Sites/statamic2/statamic/vendor/nesbot/carbon/src/Carbon/Lang/fr_FR.php' (include_path='.:/Applications/MAMP/bin/php/php7.0.0/lib/php') in /Users/efb/Sites/statamic2/statamic/vendor/nesbot/carbon/src/Carbon/Carbon.php:962
Stack trace:
#0 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /Users/efb/Sites/statamic2/statamic/core/Providers/AppServiceProvider.php(44): Carbon\Carbon::setLocale()
#4 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): Statamic\Providers\AppServiceProvider->boot()
#5 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array:{/Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php:507}()
#6 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call()
#7 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider()
#8 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#9 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk()
#10 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#11 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#12 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(222): Illuminate\Foundation\Application->bootstrapWith()
#13 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->bootstrap()
#14 /Users/efb/Sites/statamic2/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#15 /Users/efb/Sites/statamic2/index.php(142): Illuminate\Foundation\Http\Kernel->handle()
#16 /Users/efb/Sites/statamic2/index.php(0): {main}()
#17 {main} 
```

**Comment by ebeauchamps** [comment]
In #587 I succeeded in connecting to the CP, so part of the behavior has changed since then.

I also have another problem when the FIRST locale in `system.yaml` is `fr` instead of `en`. Can I open a separate issue?

**Comment by jackmcdade** [comment]
That one has been opened many times.

**Comment by ebeauchamps** [comment]
ok, my bad, I didn't find anything in the opened issues.

**Comment by jasonvarga** [comment]
> I also have another problem when the FIRST locale in system.yaml is fr instead of en.

What _is_ the problem?

@ebeauchamps

**Comment by ebeauchamps** [comment]
OK...I did not want to bother you, but I appreciate you take some time with this.

Setup:
Default locale in idex.php is `en`
There is a `fr`folder in the `lang`folder
In the CP (or directly in `system.yaml`I change the order of the locale to put `fr`in FIRST and `en`in SECOND
```
locales:
  fr:
    full: fr_FR
    name: Français
    url: http://statamic2.dev/fr/
  en:
    full: en_US
    name: Anglais
    url: http://statamic2.dev/
```
Now:
1. when any user visit http://statamic2.dev/ most css styles aren't applied anymore. See a screen copy of the default Redwood site below

![capture d ecran 2016-09-30 a 18 46 03](https://cloud.githubusercontent.com/assets/1823359/18999507/44bee406-873e-11e6-8244-6a2e737cbc36.png)

2. when any user visit http://statamic2.dev/cp  this address is immediately redirected to http://statamic2.dev/fr/cp  which of course cannot be find

The `.htaccess` file is the default one provided.

**Comment by jasonvarga** [comment]
If English is the root URL, and French is in a `fr` subfolder, I would argue that English is your default locale.

**Comment by ebeauchamps** [comment]
Why not, but I don't quite understand your remark, sorry

**Comment by ebeauchamps** [comment]
Putting `fr`in first means that French is the default locale?

**Comment by jasonvarga** [comment]
The first locale in that array is your "default" locale.

If I go to yoursite.com, I should see English. So, the default should be English.
If I make extra effort to go to yoursite.com/fr/, it tells me that French should _not_ be the default.

**Comment by ebeauchamps** [comment]
hum hum

**Comment by jasonvarga** [comment]
Why are you trying to put French first? So the Control Panel will be French?

Try adding `locale: fr` to your user file.

**Comment by ebeauchamps** [comment]
I guess you are totally right. Let me think about that some more. Thanks

**Comment by jasonvarga** [comment]
In 2.1.13, you will be able to add `locale: fr` to your `site/settings/cp.yaml` and that's what the CP will appear in.
