### ISSUE TITLE
Feature Request: Static Caching Exclude Variables

### ISSUE THREAD

**Issue by humanjpg** [statamic/v2-hub#999]
When static caching is enabled, in `site/settings/caching.yaml` it would be awesome if you could exclude entire collections and taxonomies like so:

```
static_caching_exclude:
 - /{ blog }
 - /{ genres }
 - /{ posts }
```

**Comment by jasonvarga** [comment]
Not sure why you need the curlies.

We just need to support wildcards like we do with invalidation rules.

```
static_caching_exclude:
 - /blog/*
 - /genres/*
 - /posts/*
```

**Comment by humanjpg** [comment]
Sorry, literally just came to the same conclusion and celebrated with a donut. Solves most use cases.

I can think of a use case though. If you have a load of landing pages that come off the back of the root domain... e.g. `/chicken`, `/fish`, `/moose`

Would maybe be cool if you could set a variable in the `folder.yaml` like `static_cache_exclude: true`?
